import { describe, expect, it } from 'vitest'
import { QUESTION_BANK } from '../src/bank'
import { AUTHORED_FORM_04_ITEMS } from '../src/authoredForm04'
import { AUTHORED_FORM_05_ITEMS } from '../src/authoredForm05'
import { AUTHORED_FORM_06_ITEMS } from '../src/authoredForm06'
import { AUTHORED_FORM_07_ITEMS } from '../src/authoredForm07'
import { AUTHORED_FORM_08_ITEMS } from '../src/authoredForm08'
import { AUTHORED_FORM_09_ITEMS } from '../src/authoredForm09'
import { AUTHORED_FORM_10_ITEMS } from '../src/authoredForm10'
import { AUTHORED_FORM_11_ITEMS } from '../src/authoredForm11'
import { AUTHORED_FORM_12_ITEMS } from '../src/authoredForm12'

// Frozen semantic review: /private/tmp/focus-exam-audit-listening.json
// SHA-256 69b4e80f952db063056ef8bf01e6a1abe6557efb1fb88f37246a46aea89c60a1.
// Match correct option TEXT, because the prepared bank balances option positions.
const expectedAnswerTextById: Record<string, string> = {
  "f04-announcement-clinic-0": "It determines how much consultation time their case may require",
  "f04-announcement-clinic-1": "A traveler whose departure is beyond the priority window",
  "f04-announcement-observatory-0": "It may be reassigned to someone waiting",
  "f04-announcement-observatory-1": "The event will shift to an indoor instructional activity",
  "f04-announcement-printmaking-0": "Designated staff members and qualified advanced monitors",
  "f04-announcement-printmaking-1": "Notify personnel without changing the ventilation settings",
  "f04-conversation-assistantship-1": "Document the schedule in a message that includes both officials",
  "f04-conversation-exhibit-0": "A functional analysis challenged an inference drawn mainly from appearance",
  "f04-conversation-exhibit-1": "To demonstrate the process by which scholarship corrects itself",
  "f04-conversation-freezer-0": "A temporary warming event may have affected the contents despite recovery",
  "f04-conversation-prerequisite-0": "It cannot automatically match the external course to the prerequisite",
  "f04-conversation-prerequisite-1": "Meeting the prerequisite and obtaining an available seat are separate issues",
  "f04-response-1": "Certainly, the control switch is beside the podium.",
  "f04-talk-biofilm-0": "It creates a partial barrier and supports a protected local environment",
  "f04-talk-biofilm-1": "Intervening before the community matures may require less effort",
  "f04-talk-dark-matter-0": "Outer stars retain unexpectedly high orbital speeds",
  "f04-talk-dark-matter-1": "They provide separate tests of whether the proposed mass distribution is coherent",
  "f04-talk-manuscripts-0": "It may indicate that two copies inherited material from a common source",
  "f04-talk-manuscripts-1": "Direct borrowing between copies can mimic shared descent",
  "f04-talk-pragmatics-1": "The usual implication can be withdrawn without literal contradiction",
  "f04-talk-wetlands-0": "Temporary care can mask an unresolved water-flow problem",
  "f04-talk-wetlands-1": "As informative models that still require site-specific adjustment",
  "f05-announcement-chemistry-0": "The student receives refresher training rather than performing the synthesis",
  "f05-announcement-chemistry-1": "The procedure requires supervision unavailable during regular open hours",
  "f05-announcement-debate-0": "Every listed participant must complete the conduct agreement",
  "f05-announcement-debate-1": "No new replacement participant may be added",
  "f05-announcement-film-0": "The contents and organization of saved playlists",
  "f05-announcement-film-1": "Replace them during the temporary redirection period",
  "f05-conversation-invoice-1": "Charging an ineligible future service for the sake of speed",
  "f05-conversation-keys-0": "Have the clerk open it after verifying residency",
  "f05-conversation-keys-1": "To prevent an unnecessary replacement charge",
  "f05-conversation-plants-0": "Unequal light exposure associated with treatment group",
  "f05-conversation-plants-1": "Transparent documentation and sensitivity analysis",
  "f05-conversation-score-0": "The musical effect must remain physically performable and clear",
  "f05-conversation-score-1": "The same pitches could be divided differently among performers",
  "f05-talk-groundwater-0": "Each marker answers only part of the source-and-age problem",
  "f05-talk-groundwater-1": "It may no longer be measurable after a long residence time",
  "f05-talk-predictive-0": "New evidence should sometimes overturn an established expectation",
  "f05-talk-predictive-1": "Varying cue reliability independently of sensory clarity",
  "f05-talk-price-1": "Expanded sales and the allocation of gains can affect groups differently",
  "f05-talk-taphonomy-0": "Species differ in how likely their remains are to survive and be collected",
  "f05-talk-taphonomy-1": "To infer processes that accumulated and modified the remains",
  "f05-talk-thermal-inertia-0": "The likely ability of the material to store and conduct heat",
  "f05-talk-thermal-inertia-1": "They help separate material effects from heating differences caused by terrain",
  "f06-announcement-archive-0": "Create sanitized accessible versions for submission",
  "f06-announcement-archive-1": "An interactive link used to collect payments",
  "f06-announcement-cafe-0": "At any campus café participating in the trial",
  "f06-announcement-cafe-1": "The container is accepted, but the deposit is forfeited",
  "f06-announcement-orientation-0": "Their field notebooks for indoor specimen practice",
  "f06-announcement-orientation-1": "Prior-year completion does not authorize this year’s trip",
  "f06-conversation-census-0": "Later observation reduced the chance of detecting active birds",
  "f06-conversation-census-1": "Restrict analysis to temporally comparable recording data and disclose the change",
  "f06-conversation-data-use-1": "Obtain an amended authorization specifying the expanded use",
  "f06-conversation-kiln-0": "The test objects experienced different earlier firing conditions",
  "f06-conversation-kiln-1": "The heat work actually experienced during the new test",
  "f06-conversation-projection-0": "The display surface and projection geometry do not match",
  "f06-conversation-projection-1": "To evaluate the alternative layout from seats with different sight lines",
  "f06-talk-network-0": "Users risk losing access to an established web of contacts",
  "f06-talk-network-1": "It weakens the need for all contacts to use one provider",
  "f06-talk-provenance-0": "They survive transport better than less resistant source material",
  "f06-talk-provenance-1": "A proposed source is possible but may not be unique",
  "f06-talk-reinforcement-0": "Removing an unpleasant stimulus makes the preceding action more likely",
  "f06-talk-reinforcement-1": "An observed increase in the behavior it followed",
  "f06-talk-soundscape-0": "Nonbiological noise or one dominant caller may inflate the summary",
  "f06-talk-soundscape-1": "Recording repeatedly at comparable times and validating acoustic summaries",
  "f06-talk-spectra-1": "Several physical processes alter spectral features at the same time",
  "f07-announcement-costumes-0": "Check the fit of all assigned costume pieces",
  "f07-announcement-costumes-1": "A correction needed to move safely during performance",
  "f07-announcement-elections-0": "A link intended to collect campaign funds",
  "f07-announcement-elections-1": "An office-verified correction of factual information",
  "f07-announcement-ice-0": "Measured thickness is inconsistent and below the required safety standard",
  "f07-announcement-ice-1": "A land-based exercise using the same positioning skill",
  "f07-conversation-oven-0": "The clock resets rather than merely ending a cooking cycle",
  "f07-conversation-oven-1": "Avoid the oven and use the offered alternative appliance",
  "f07-conversation-reserve-0": "Volunteers may confuse a protected native with the target plant",
  "f07-conversation-reserve-1": "Trained leaders will supervise work in designated locations",
  "f07-conversation-sample-size-1": "A sensitivity calculation across a defensible range of expected effects",
  "f07-conversation-translation-0": "Semantically similar wording may not produce equivalent measurement",
  "f07-conversation-translation-1": "Measurement differences could be mistaken for group differences",
  "f07-talk-agglomeration-0": "Proximity supports specialized matching and information exchange",
  "f07-talk-agglomeration-1": "More capable firms may select the same locations that appear advantageous",
  "f07-talk-deltas-1": "Material must reach and remain in the locations needing elevation gain",
  "f07-talk-gene-culture-0": "A learned practice can alter which inherited traits confer an advantage",
  "f07-talk-gene-culture-1": "Population movement can mimic a relationship attributed to selection",
  "f07-talk-mantle-0": "It deforms gradually when observed over geological time",
  "f07-talk-mantle-1": "Plate forces and mantle properties interact in more than one direction",
  "f07-talk-working-memory-0": "Memory quality can decline gradually as more items compete for resources",
  "f07-talk-working-memory-1": "It reveals how precisely a feature was retained",
  "f08-announcement-dance-0": "Change from socks into clean dance footwear indoors",
  "f08-announcement-dance-1": "After padding receives technical approval",
  "f08-announcement-donation-0": "The decision about the destination of items the library does not retain",
  "f08-announcement-donation-1": "Arrange an independent appraisal before donating",
  "f08-announcement-market-0": "Relocate their vehicles away from the market ramp",
  "f08-announcement-market-1": "From the alternate entrance after parking elsewhere",
  "f08-conversation-codes-1": "They document how and why the coding rule changed",
  "f08-conversation-isotopes-0": "The chemical signature has more than one geographical or dietary source",
  "f08-conversation-isotopes-1": "Whether exposure during later life differed from childhood exposure",
  "f08-conversation-lights-0": "The sensor fails to register movement during quiet work",
  "f08-conversation-lights-1": "To balance reliable occupancy detection against false activation",
  "f08-conversation-piano-0": "Key resistance requires mechanical regulation rather than pitch adjustment",
  "f08-conversation-piano-1": "Place the piano finally, regulate its action, and then tune it",
  "f08-talk-acoustics-1": "Occupied seats change absorption and therefore the hall response",
  "f08-talk-episodic-0": "It can signal prior encounter without retrieving event context",
  "f08-talk-episodic-1": "No single report perfectly separates overlapping internal processes",
  "f08-talk-kinetics-0": "Most enzyme active sites are already occupied",
  "f08-talk-kinetics-1": "Additional interactions and changing concentrations violate the simplified setting",
  "f08-talk-niche-0": "Several mechanisms besides current competition can generate the pattern",
  "f08-talk-niche-1": "A species broadens resource use after a rival is experimentally removed",
  "f08-talk-volcanic-aerosol-0": "Their small stratospheric particles remain aloft for a longer period",
  "f08-talk-volcanic-aerosol-1": "Temporary volcanic forcing does not cancel persistent greenhouse forcing",
  "f09-announcement-auditions-0": "A brief view of the student identification card",
  "f09-announcement-auditions-1": "A performer auditioning on a wind instrument",
  "f09-announcement-catering-0": "A revision to the registrant’s dietary selection",
  "f09-announcement-catering-1": "They are transferred for donation",
  "f09-announcement-trail-0": "Permit holders as well as ordinary trail users",
  "f09-announcement-trail-1": "Notify staff without entering the closed section",
  "f09-conversation-loan-0": "The proposed duration and display environment differ from the approved conditions",
  "f09-conversation-loan-1": "The borrower must document the new environment and coverage",
  "f09-conversation-map-license-1": "Crediting a source does not mean claiming its endorsement",
  "f09-conversation-plagiarism-0": "Standard technical language can legitimately recur",
  "f09-conversation-plagiarism-1": "Retain essential terms while independently explaining and citing the procedure",
  "f09-conversation-replicates-0": "They share the same biological source and do not represent independent variation",
  "f09-conversation-replicates-1": "As tentative evidence awaiting independent biological replication",
  "f09-talk-color-0": "It combines properties of the surface with properties of illumination",
  "f09-talk-color-1": "Context leads the visual system to infer different lighting conditions",
  "f09-talk-externality-0": "Some harm is excluded from the costs guiding its decision",
  "f09-talk-externality-1": "Marginal harm is difficult to estimate and unevenly distributed",
  "f09-talk-fluorescence-0": "Technical conditions and labeling efficiency also influence detected light",
  "f09-talk-fluorescence-1": "It can injure the living sample being observed",
  "f09-talk-seriation-1": "They connect parts of the relative order to calendar time",
  "f09-talk-tolerance-0": "Some self-reactive cells remain after developmental screening",
  "f09-talk-tolerance-1": "Limiting self-damage without blocking useful defense",
  "f10-announcement-lab-tour-0": "It becomes available to a standby visitor at the start time",
  "f10-announcement-lab-tour-1": "In the demonstration room but not the fabrication area",
  "f10-announcement-print-0": "A user needing close consistency with an earlier exhibition proof",
  "f10-announcement-print-1": "Inspect a small sample produced on the temporary paper",
  "f10-announcement-writing-0": "Exclusively through an online appointment",
  "f10-announcement-writing-1": "One due within the next two hours",
  "f10-conversation-loan-art-0": "The required acclimation time began later because transport was delayed",
  "f10-conversation-loan-art-1": "Adjust the rehearsal and install only after acclimation",
  "f10-conversation-package-0": "The courier’s delivery status refers to a central campus facility",
  "f10-conversation-package-1": "File the tracking information through the designated form",
  "f10-conversation-prerecord-1": "Insert a self-contained recorded explanation with matched sound",
  "f10-conversation-sensors-0": "All sensors shifted together without an independent environmental signal",
  "f10-conversation-sensors-1": "They allow the team to recompute values under verified calibration rules",
  "f10-talk-auctions-0": "The bidder may lose even when the sale price would have been acceptable",
  "f10-talk-auctions-1": "Real settings may violate assumptions about values and constraints",
  "f10-talk-harmony-0": "They show whether speakers apply the pattern beyond stored examples",
  "f10-talk-harmony-1": "They help reveal boundaries and competing constraints on the pattern",
  "f10-talk-isostasy-0": "The land may rise faster than the local water surface",
  "f10-talk-isostasy-1": "An estimate of vertical land movement at the observing site",
  "f10-talk-ndvi-1": "Control for atmospheric and geometric differences in acquisition",
  "f10-talk-overturning-0": "Actual circulation has branching paths and multiple driving processes",
  "f10-talk-overturning-1": "No single current measurement captures the full three-dimensional circulation",
  "f11-announcement-collections-0": "Leave them sealed for staff assessment",
  "f11-announcement-collections-1": "Some materials could be damaged by low temperature",
  "f11-announcement-mentors-0": "A reference from a faculty member",
  "f11-announcement-mentors-1": "A scheduled academic class",
  "f11-announcement-poetry-0": "After the stated ten-minute holding period ends",
  "f11-announcement-poetry-1": "The reading shares space with an active exhibition",
  "f11-conversation-choir-1": "Amplification cannot fix destructive interference",
  "f11-conversation-label-0": "Separate archaeological evidence from a less certain earlier interpretation",
  "f11-conversation-label-1": "It can make evidential revision understandable rather than merely vague",
  "f11-conversation-species-0": "The detection algorithm changed between years",
  "f11-conversation-species-1": "Background conditions may still differ between recording periods",
  "f11-conversation-ventilation-0": "Operation sound does not establish safe airflow direction or volume",
  "f11-conversation-ventilation-1": "Adjusting ventilation beyond authorized settings",
  "f11-talk-caves-0": "They connect measured stalagmite chemistry to current environmental processes",
  "f11-talk-caves-1": "A break in deposition that interrupts the time sequence",
  "f11-talk-commons-0": "Users receive private benefits while sharing depletion costs",
  "f11-talk-commons-1": "It can work under certain institutional and ecological conditions",
  "f11-talk-metamemory-0": "Temporary processing fluency is mistaken for durable retention",
  "f11-talk-metamemory-1": "Whether confidence ranks relatively strong and weak memories correctly",
  "f11-talk-pollen-0": "Species differ greatly in production and transport distance",
  "f11-talk-pollen-1": "Alternative causes of vegetation change can be evaluated",
  "f11-talk-vot-1": "To isolate how changing one timing cue affects identification",
  "f12-announcement-fair-0": "Graduate students",
  "f12-announcement-fair-1": "Early access to the general exhibition area",
  "f12-announcement-lecture-0": "Take notes for their own study",
  "f12-announcement-lecture-1": "Survey participants must review applicable content",
  "f12-announcement-samples-0": "Staff must repeat the physical count",
  "f12-announcement-samples-1": "Contact the shipping lead before adding it",
  "f12-conversation-display-0": "Specular reflection is directed toward the viewer",
  "f12-conversation-display-1": "Use offset main lighting plus weaker fill and test multiple viewpoints",
  "f12-conversation-identifier-1": "It documents the error and supports a complete impact audit",
  "f12-conversation-lock-0": "A time-specific access priority took effect",
  "f12-conversation-lock-1": "Recover the property without restoring practice access",
  "f12-conversation-salinity-0": "Temperature and possibly compensation settings varied with measurement",
  "f12-conversation-salinity-1": "A documented recalculation from preserved raw inputs",
  "f12-talk-adverse-0": "An average price fails to compensate them for superior quality",
  "f12-talk-adverse-1": "When poor-quality sellers would find it costly to imitate",
  "f12-talk-clouds-0": "They can distribute liquid water among more, smaller droplets",
  "f12-talk-clouds-1": "Weather conditions can affect both variables and create confounding",
  "f12-talk-code-switching-1": "Social motivations for switching emerge in real relationships and contexts",
  "f12-talk-pruning-0": "It can refine circuits by selectively stabilizing useful patterns",
  "f12-talk-pruning-1": "Available human measures are indirect and behavior has many causes",
  "f12-talk-thermoluminescence-0": "The last heating that reset trapped-electron energy",
  "f12-talk-thermoluminescence-1": "Stored energy must be related to the rate at which radiation accumulated",
}

const sourceItems = [
  ...AUTHORED_FORM_04_ITEMS,
  ...AUTHORED_FORM_05_ITEMS,
  ...AUTHORED_FORM_06_ITEMS,
  ...AUTHORED_FORM_07_ITEMS,
  ...AUTHORED_FORM_08_ITEMS,
  ...AUTHORED_FORM_09_ITEMS,
  ...AUTHORED_FORM_10_ITEMS,
  ...AUTHORED_FORM_11_ITEMS,
  ...AUTHORED_FORM_12_ITEMS,
]

describe('frozen listening answer regression for authored forms 04–12', () => {
  it('keeps exactly the 198 semantically verified answer texts in source and prepared banks', () => {
    const expectedIds = Object.keys(expectedAnswerTextById)
    expect(expectedIds).toHaveLength(198)
    expect(new Set(expectedIds).size).toBe(198)
    const rawById = new Map(sourceItems.map((item) => [item.id, item]))
    const preparedById = new Map(QUESTION_BANK.map((item) => [item.id, item]))
    for (const [id, correctText] of Object.entries(expectedAnswerTextById)) {
      const raw = rawById.get(id)
      const prepared = preparedById.get(id)
      expect(raw, `missing raw item ${id}`).toBeDefined()
      expect(prepared, `missing prepared item ${id}`).toBeDefined()
      expect(raw?.options, `raw options for ${id}`).toHaveLength(4)
      expect(prepared?.options, `prepared options for ${id}`).toHaveLength(4)
      expect(raw?.options?.filter((option) => option === correctText), `unique raw answer text for ${id}`).toHaveLength(1)
      expect(prepared?.options?.filter((option) => option === correctText), `unique prepared answer text for ${id}`).toHaveLength(1)
      expect(raw?.options?.[raw.answer as number], `source answer for ${id}`).toBe(correctText)
      expect(prepared?.options?.[prepared.answer as number], `prepared answer for ${id}`).toBe(correctText)
    }
  })
})
