import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f21')

const reading: BaseItem[] = [
  cloze('cloze-pollen', '고환경학', 'C1', 'Pollen grains preserved in lake sediment can reveal past vegetation because plants produce distinctive microscopic forms. Wind-pollinated species often rel___ enormous quantities, so pollen abundance does not map directly to local plant cover. Grains can tra___ far, and lakes differ in the area they sample. Sediment also inte___ pollen deposited over time. Researchers extract sediment cores, count pollen by depth, and build age models. Changes in percentages are compositional: if one taxon inc___, another percentage can fall without an absolute decline. Analysts add marker spores or influx estimates to assess concentration. Preservation also var___ because oxidation and chemical conditions destroy some grains preferentially. A sudden rise in grass pollen might refl___ climate, fire, grazing, cultivation, or erosion from the watershed. Charcoal, plant macrofossils, geochemistry, and historical evidence help sep___ these causes. Statistical reconstruction cal___ modern pollen against vegetation or climate, but past communities may lack exact modern analogues. Researchers therefore report uncertainty and avoid equ___ one pollen type with one landscape. Long records are strongest when chronology and deposition remain con___.', 'ease|vel|grates|reases|ies|ect|arate|ibrates|ating|strained'),
  cloze('cloze-tolerance', '면역학', 'C1', 'The immune system must respond to pathogens while tolerating the body’s own molecules. During development, many lymphocytes that bind strongly to self are elim___ or inactivated. This central tolerance is incomplete, so peripheral mechanisms rest___ escaped cells. Additional checkpoints oper___ in tissues. Regulatory T cells suppress harmful activation, and lack of costimulatory signals can induce anergy. Tissue barriers and controlled antigen presentation also lim___ exposure. Autoimmunity can arise when genetics, infection, tissue damage, or environmental factors dis___ several safeguards. Molecular mimicry is one proposed route, in which a microbial epitope res___ a self target, but sequence similarity alone does not prove disease causation. Immune tolerance is not simple weakness: it actively prev___ destructive responses while preserving protection. Therapies that broadly suppress immunity may reduce symptoms yet inc___ infection risk. Researchers distinguish biomarkers from mechanisms by tracking cell specificity, timing, and intervention effects. A circulating autoantibody may prec___ illness, accompany damage, or have little functional consequence. Strong inference req___ showing how the response reaches and alters target tissue.', 'inated|rain|ate|it|rupt|embles|ents|rease|ede|uires'),
  cloze('cloze-clock', '기술사', 'B2', 'Mechanical clocks transformed timekeeping by using an escapement to release stored energy in regular increments. A falling weight or spring pow___ the mechanism, while gears transmit motion to hands or bells. The escapement reg___ energy release. Early clocks were not highly acc___, but they coordinated collective schedules. Pendulums later imp___ rate stability, though motion, temperature, and friction still mattered. Public clocks often displayed civic authority as well as time. Surviving mechanisms may contain replacement parts from centuries of repair. Conservators exam___ tool marks, metal composition, and wear before deciding which phase to preserve. Running a clock demonstrates function but also cau___ abrasion. Digital models can sim___ gear motion without operating fragile originals. Historians compare written accounts with mechanisms because terminology changed and idealized diagrams may not match practice. Standard time zones emerged much later with railways and telegraphy, so local clock time could dif___ among towns. The history of clocks therefore comb___ technical precision with institutional coordination and social discipline, rather than ass___ that one invention instantly standardized daily life.', 'ers|ulates|urate|roved|ine|ses|ulate|fer|ines|uming'),
  daily('daily-centrifuge-balance', '실험 장비', 'B2', 'Centrifuge tubes must be balanced by mass, not merely by equal liquid height. Solutions with different densities can appear level while imposing unequal loads. Use matched adapters and record the maximum mass difference permitted for the rotor.', ['Why is matching liquid height insufficient?', ['Equal volumes can have different masses when solution densities differ', 'Matched adapters automatically change every solution density', 'Rotor limits are specified only by tube color', 'Mass balance matters only after centrifugation ends'], 0, 'The rotor responds to mass distribution.']),
  daily('daily-oral-embargo', '구술 기록', 'C1', 'An interview restricted until a named person’s death cannot be opened from an unverified online obituary. Archive staff require an authoritative death record or written permission from the rights holder. Until verification, catalog metadata may remain visible while the recording stays closed.', ['What is needed to lift the restriction?', ['Reliable documentation or explicit authorization from the responsible rights holder', 'Any online page claiming that the named person died', 'Removal of all public catalog metadata', 'A researcher’s promise not to quote the recording'], 0, 'The release condition must be verified.']),
  daily('daily-transect-flag', '생태 조사', 'B2', 'Transect flags identify permanent sampling points and should not be moved to make mowing easier. Grounds staff may temporarily mark a flag with a protective cone, but relocation requires the research team to resurvey coordinates and document the change.', ['What must happen if a sampling flag is relocated?', ['Its position must be resurveyed and the change recorded', 'The old coordinates remain valid without comment', 'A protective cone permanently replaces the research marker', 'Mowing staff may select a more convenient point independently'], 0, 'Permanent sampling depends on spatial continuity.']),
  daily('daily-vendor-demo', '장비 구매', 'B2', 'A vendor demonstration may use prepared samples that favor the instrument. Evaluation teams should include a blinded sample representative of their own work and score it with criteria agreed before the visit. Price discussions occur after technical scoring.', ['Why bring a blinded local sample?', ['To test performance on relevant material without revealing the expected result', 'To allow the vendor to replace the evaluation criteria', 'To determine price before observing technical performance', 'To ensure prepared samples always perform poorly'], 0, 'Independent material reduces demonstration bias.']),
  daily('daily-stack-request', '도서관 서고', 'B1', 'Same-day stack requests submitted before two are delivered within ninety minutes. Later requests are ready the following morning. A request marked “located” is still in transit; wait for “reading room ready” before arriving at the desk.', ['Which status means the material can be collected?', ['Confirmation that delivery to the reading room is complete', 'A location result from the closed stacks', 'A request submitted beyond the same-day cutoff', 'A notice that transport toward the desk has begun'], 0, 'The final delivery status authorizes collection.']),
  daily('daily-camera-clock', '다중 카메라 촬영', 'B2', 'Camera clocks must be synchronized before each behavioral session. Matching file creation times afterward does not correct drift within a long recording. Record a visible synchronization event at both the beginning and end so analysts can estimate residual timing error.', ['Why record synchronization at both ends?', ['The two events reveal clock drift accumulated during the session', 'File creation times erase all timing differences', 'A visible event changes camera frame rate automatically', 'Clock synchronization is needed only after recording'], 0, 'Endpoint comparison measures temporal drift.']),
  daily('daily-repository-license', '소프트웨어 공개', 'B2', 'Uploading code to a public repository does not give others clear reuse rights unless a license is included. A citation request in the README is not a substitute for legal permission. Contributors should confirm that third-party components allow the chosen license.', ['What should accompany publicly reusable code?', ['A compatible license that states permitted use', 'Only a request that readers cite the repository', 'Third-party material with unknown terms', 'A private access setting after publication'], 0, 'Visibility and legal permission are distinct.']),
  daily('daily-kiln-witness', '도자기 소성', 'B2', 'Witness cones record heat work, which combines temperature and time. A controller reading may reach the target while the ware receives insufficient heat work. Place cones where they can be viewed safely after cooling and retain a photograph with the firing log.', ['What do witness cones reveal beyond a peak reading?', ['The combined thermal effect of temperature over time', 'The chemical identity of every glaze ingredient', 'The exact atmospheric pressure outside the kiln', 'Whether ware can be removed before cooling'], 0, 'Heat work integrates duration and temperature.']),
  daily('daily-caption-speaker', '영상 접근성', 'B2', 'Captions should identify a speaker when the voice is not visually obvious or when a change matters to meaning. Labels need not repeat before every sentence by the same person. Background speech essential to the scene should be distinguished from incidental crowd noise.', ['When is a speaker label particularly necessary?', ['When listeners cannot otherwise infer who is speaking and identity matters', 'Before every sentence regardless of continuity', 'Only when all background sound is irrelevant', 'Whenever the visible speaker remains unchanged'], 0, 'Identification supports comprehension at meaningful changes.']),
  daily('daily-chemical-return', '시약 공급실', 'B1', 'Unopened reagent bottles may be returned within seven days if they remained under required storage conditions. Opened bottles and temperature-sensitive packages without logger evidence are not restocked. Submit the storage record with the return form.', ['Which item is eligible for restocking?', ['A sealed bottle with documented compliant storage', 'An opened bottle returned the next morning', 'A chilled package lacking temperature evidence', 'A sealed reagent stored outside its required range'], 0, 'Seal and storage documentation are both required.']),
  ...readingGroup('academic-propensity', '관찰연구 방법론', 'C1', 'A propensity score is the probability of receiving treatment conditional on observed covariates. Matching, weighting, or stratifying on the score can balance those measured variables between treatment groups. It does not balance causes that were omitted or measured poorly. Good prediction of treatment is not the primary goal; overlap and covariate balance matter. Including a variable caused by treatment can introduce bias, while excluding a true pre-treatment confounder leaves bias. Extreme scores create unstable weights because some participants have few comparable counterparts. Researchers inspect balance after adjustment and state the population represented by remaining overlap.', [
    ['What limitation remains after perfect score-based balance?', ['Unmeasured confounders may still differ between treatment groups', 'Treatment probability becomes identical for every participant', 'Observed covariates can no longer predict treatment', 'The adjusted estimate automatically applies to all populations'], 0, 'The method addresses only represented pre-treatment information.'],
    ['Why can an excellent treatment-prediction model be unsuitable?', ['Prediction can separate groups so strongly that comparable observations and stable weights vanish', 'Propensity scores must be unrelated to treatment assignment', 'Balance requires maximizing classification accuracy above all else', 'Extreme scores eliminate uncertainty from weighting'], 0, 'Causal adjustment prioritizes overlap and balance.'],
    ['Why should balance be checked after adjustment?', ['A fitted score does not guarantee that the chosen procedure equalized covariates', 'Balance can be inferred solely from the outcome estimate', 'Post-adjustment checks introduce treatment-caused variables', 'Matching necessarily preserves every original imbalance'], 0, 'The realized adjusted sample must be diagnosed.'],
  ]),
  ...readingGroup('academic-optimality', '행동생태학', 'C1', 'Optimality models ask which behavior would maximize a defined currency under specified constraints. A foraging model might predict prey choice from energy gain and handling time. The prediction is a benchmark, not a claim that animals calculate equations or achieve perfection. Deviations can reveal missing constraints such as predation risk, nutrient balance, learning, or competition. A model becomes difficult to test if its currency is changed after observing every outcome. Researchers specify alternatives in advance and compare simple models with richer ones while considering the cost of added parameters.', [
    ['What does an optimality prediction represent?', ['A conditional benchmark derived from an explicit objective and constraints', 'Proof that animals consciously solve mathematical equations', 'A description that cannot be contradicted by behavior', 'A guarantee that energy is the only biological currency'], 0, 'The model formalizes a testable conditional expectation.'],
    ['Why are deviations scientifically useful?', ['They can expose omitted tradeoffs or constraints in the model', 'They show that behavior has no relation to natural selection', 'They require redefining the currency after every observation', 'They eliminate the need to compare alternative explanations'], 0, 'Mismatch directs refinement when the benchmark is fixed.'],
  ]),
  ...readingGroup('academic-papyri', '고대행정문서', 'C1', 'Papyri from dry archaeological contexts preserve contracts, petitions, tax receipts, private letters, and literary texts. Their survival is geographically biased toward environments where organic fibers decay slowly. A tax receipt records a payment, not every liability or every resident. Reused sheets may carry older writing on one side and later text on the other. Dates can follow regnal years or local eras that require conversion. Documents purchased without excavation context lose association with buildings, archives, and other texts. Historians compare handwriting, formulas, fibers, ink, named officials, and parallel documents, while recognizing that the surviving corpus overrepresents literate administration.', [
    ['How does preservation climate bias the documentary record?', ['Dry regions contribute disproportionately to surviving papyrus evidence', 'Humid environments preserve organic writing material indefinitely', 'Literary texts occur only where tax receipts decay', 'Fiber composition determines which officials are named'], 0, 'Survival is environmentally selective.'],
    ['Why is a receipt not a direct population count?', ['It documents a transaction under an administrative system with limited coverage', 'Every resident was required to receive one identical receipt', 'Payment records exclude all names and dates', 'Tax liability always equals household size'], 0, 'Fiscal evidence has a narrower unit than population.'],
    ['What is lost when a papyrus lacks excavation context?', ['Its spatial and archival relationships to other activities and documents', 'The ability to observe any handwriting on the sheet', 'All information about language and ink', 'The possibility that either side was reused'], 0, 'Association is a major source of interpretation.'],
  ]),
  ...readingGroup('academic-aerogel', '재료공학', 'C1', 'Aerogels are highly porous solids made by replacing the liquid in a gel without collapsing its network. Conventional evaporation creates capillary forces that can shrink or fracture the structure, so supercritical drying or other techniques avoid a liquid–gas boundary. The resulting material can have very low density and thermal conductivity, yet fragility and moisture sensitivity limit use. Adding fibers or polymers improves toughness but may increase conductivity or mass. Laboratory conductivity measured in dry, still air may not predict a building panel exposed to humidity, joints, compression, and aging.', [
    ['Why is ordinary evaporation problematic during production?', ['Surface-tension forces can collapse the delicate pore network', 'It eliminates every liquid–gas interface before drying', 'It always increases the solid’s mechanical toughness', 'Capillary forces create perfectly uniform large pores'], 0, 'The meniscus stresses the gel structure.'],
    ['Why might reinforcement involve a tradeoff?', ['Greater toughness can reduce the extreme lightness or insulation performance', 'Fibers remove all solid pathways for heat', 'Polymers guarantee complete moisture resistance without mass', 'Mechanical strength and conductivity are necessarily unrelated'], 0, 'Improving one property can compromise others.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the behavioral cameras share the end synchronization event?', ['Yes, all three captured the same flashing marker.', 'The cameras record sixty frames per second.', 'Synchronization events appear as bright squares.', 'I shared the meeting notes with the team.'], 0, 'The response confirms a common temporal marker.'),
  response(1, 'Why was the papyrus request returned for revision?', ['The papyrus contains a petition to a governor.', 'Its date used a local era not identified on the form.', 'I revised the manuscript after peer review.', 'Requests are delivered in padded folders.'], 1, 'An ambiguous dating system required clarification.'),
  response(2, 'Could the propensity weights be too variable?', ['The propensity model includes twelve covariates.', 'Weights create a synthetic comparison population.', 'Yes, if some participants have almost no counterparts in the other group.', 'I varied the sample temperature during testing.'], 2, 'Limited overlap generates extreme weights.'),
  response(3, 'I thought the vendor certificate authenticated our culture.', ['The vendor supplies frozen cells in sealed vials.', 'Authentication compares genetic profiles.', 'I certified the translation for the visa office.', 'It documents the starting material, not months of local handling.'], 3, 'Local propagation creates new identity risk.'),
  response(4, 'May we compress the aerogel panel before thermal testing?', ['Only if mechanical loading is part of the registered test sequence.', 'The panel contains a silica network reinforced with fibers.', 'Thermal testing measures heat flow across thickness.', 'I compressed the images before uploading them.'], 0, 'Compression changes structure and must be planned.'),
  response(5, 'Where are the original pollen-count worksheets?', ['The pollen sequence spans nine thousand years.', 'In the archive folder linked to each core depth.', 'Pollen counts are converted to percentages.', 'I counted the blank slides before class.'], 1, 'The answer gives depth-linked raw storage.'),
  response(6, 'Shouldn’t we exclude variables measured after treatment?', ['The analysis estimates a treatment effect on recovery.', 'Several variables were collected at follow-up.', 'Usually, because adjusting for treatment consequences can create bias.', 'I measured the sculpture after treatment by the conservator.'], 2, 'Post-treatment adjustment can block or open causal paths.'),
  response(7, 'The clock lost two minutes after we moved it.', ['The clock uses a spring-driven escapement.', 'Movement can disturb a mechanical regulator.', 'I moved the legend beside the second figure.', 'Let it settle and document rate before changing the mechanism.'], 3, 'Observation should precede intervention.'),
  response(8, 'Is the restricted interview open after that online obituary?', ['Not until staff verify the release condition through an authoritative source.', 'The interview discusses a local election campaign.', 'Online notices vary in detail and permanence.', 'I opened the audio editor this morning.'], 0, 'Unverified information cannot trigger access.'),
  response(9, 'Why did the treated groups lose common support?', ['The groups were recruited from separate clinics.', 'Treatment assignment became nearly deterministic at extreme ages.', 'I supported the frame with padded blocks.', 'Common support is displayed as overlapping distributions.'], 1, 'Near-deterministic assignment removes comparisons.'),
  response(10, 'Can this pollen rise prove cultivation began?', ['The grain type belongs to a grass family.', 'Cultivation changes vegetation and erosion.', 'Not without evidence that separates crops from grazing, fire, and transport.', 'I cultivated the cell line for three passages.'], 2, 'The pollen signal has multiple plausible causes.'),
  response(11, 'I cannot find the license for this public code.', ['The repository has been online for two years.', 'The code depends on several open-source packages.', 'I found the error in the license-number field.', 'Treat reuse as unclear until the owner adds compatible terms.'], 3, 'Public visibility does not imply permission.'),
  response(12, 'Has the kiln firing record included the witness-cone image?', ['Yes, it is attached beside the controller log.', 'The cones bend at calibrated heat work.', 'Kiln records include glaze and clay codes.', 'I witnessed the equipment inspection yesterday.'], 0, 'The answer confirms paired evidence.'),
  response(13, 'When should the pigment sample enter the analytical queue?', ['The sample weighs less than a milligram.', 'After conservation signs the destructive-analysis request.', 'I entered the queue before the laboratory opened.', 'Pigment analysis can use several instruments.'], 1, 'Authorization precedes destructive testing.'),
  response(14, 'Would trimming the largest propensity weights help?', ['The largest weights belong to older participants.', 'Trimming changes the population represented by the estimate.', 'It may stabilize variance, but we must report the altered target and possible bias.', 'I trimmed the paper support around the photograph.'], 2, 'Stability comes with an estimand tradeoff.'),
  response(15, 'Who may return the restricted chemical to active stock?', ['The bottle has an intact manufacturer seal.', 'Active stock is inventoried by shelf and owner.', 'The holding cabinet is under ventilation.', 'The chemical-safety manager must verify ownership and storage history.'], 3, 'A qualified authority clears the unknown container.'),
  response(16, 'This aerogel sample seems much denser near the edge.', ['Inspect whether drying caused shrinkage gradients before averaging its properties.', 'The sample is pale blue under room light.', 'Density is mass divided by volume.', 'I averaged the survey responses by district.'], 0, 'Spatial heterogeneity can invalidate one bulk value.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-overlap', 'Listen to a Conversation', '관찰연구', 'C1', 'Student: After matching, I retained only forty percent of treated patients. The covariates are balanced now. Advisor: Balanced for whom? Student: Mostly middle-aged patients from large clinics. Advisor: Then your estimate may be credible for the overlap population, but do not present it as the effect for every treated patient. Describe who was discarded and why.', [
    ['What limitation follows from the matching result?', ['The estimate represents a restricted subset rather than all treated patients', 'Covariate balance becomes impossible after any exclusion', 'Large clinics contain no valid comparison patients', 'Discarding observations guarantees hidden confounding is absent'], 0, 'Limited overlap narrows the target population.'],
    ['What reporting does the advisor request?', ['A description of retained and excluded participants and the resulting estimand', 'A claim that forty percent equals the full treatment population', 'Deletion of all balance diagnostics', 'Replacement of matching with outcome prediction only'], 0, 'Transparency about selection defines generalizability.'],
  ]),
  ...listeningGroup('conversation-gear', 'Listen to a Conversation', '기계식 시계', 'B2', 'Curator: The clock runs only when the case is slightly tilted. Technician: That suggests wear or misalignment, not that the historic case was designed that way. Curator: Should we level the movement internally? Technician: First map the pivot wear and previous repairs. An adjustment that makes it run today could erase evidence or increase uneven force.', [
    ['What does the need for tilting probably indicate?', ['A mechanical condition such as wear or misalignment', 'An intentional historic requirement for an uneven case', 'Perfect balance in every gear pivot', 'A digital simulation controlling the clock'], 0, 'Orientation sensitivity signals a mechanical problem.'],
    ['Why delay adjustment?', ['Restoring operation without diagnosis may damage or obscure historical evidence', 'A stationary clock contains no information', 'Pivot wear disappears when documented', 'Leveling always reduces force on every part'], 0, 'Function is not the only conservation objective.'],
  ]),
  ...listeningGroup('conversation-core', 'Listen to a Conversation', '호수 퇴적물', 'C1', 'Assistant: The pollen diagram shows an abrupt boundary, but the core photograph has a disturbed layer there. Paleoecologist: Then the vegetation change may be an artifact of mixed sediment. Assistant: Can we remove those depths? Paleoecologist: Flag them first, compare magnetic and geochemical profiles, and see whether another core preserves the same transition before excluding evidence.', [
    ['Why is the pollen boundary questionable?', ['Physical disturbance may have mixed material from different ages', 'Pollen percentages cannot change abruptly in nature', 'Core photographs reveal plant cover directly', 'Magnetic profiles always match pollen counts'], 0, 'Stratigraphic integrity is uncertain at the boundary.'],
    ['What would support a genuine regional transition?', ['A comparable sequence in an independent undisturbed core', 'Deletion of every sample near the photograph boundary', 'One pollen type reaching one hundred percent', 'Absence of any geochemical measurement'], 0, 'Replication across intact records strengthens interpretation.'],
  ]),
  ...listeningGroup('conversation-caption', 'Listen to a Conversation', '강의 영상', 'B2', 'Instructor: The caption file labels every off-screen voice as “speaker.” Accessibility Editor: That is not enough when two students debate. Instructor: Their names were not recorded. Editor: Use descriptive labels such as “student near window” consistently, and note overlapping speech when words cannot be separated.', [
    ['Why is the generic label inadequate?', ['Listeners cannot distinguish turns between multiple unseen speakers', 'Every speaker must be identified by a legal name', 'Off-screen speech should be removed from captions', 'Debates contain no meaningful speaker changes'], 0, 'Turn attribution matters even without names.'],
    ['What alternative does the editor propose?', ['Stable descriptive identifiers based on available context', 'Invented personal names for each voice', 'One label for all student speech', 'Omission of simultaneous dialogue'], 0, 'Consistent descriptions preserve distinctions honestly.'],
  ]),
  ...listeningGroup('conversation-optimal', 'Listen to a Conversation', '채집 행동', 'C1', 'Student: The birds chose smaller prey than the energy-maximizing model predicts. Ecologist: Did the larger prey occur in exposed water? Student: Yes, and hawks were active. Ecologist: Then predation risk may be a missing cost. Test the original model against a preregistered risk-adjusted alternative rather than redefining energy gain after seeing the data.', [
    ['What explains the apparent nonoptimal prey choice?', ['Larger energetic rewards may carry greater predation danger', 'Small prey always provide more energy per handling time', 'Hawks reduce the availability of all exposed water', 'The original model already included every possible cost'], 0, 'A survival tradeoff can alter the optimal currency.'],
    ['Why preregister the alternative model?', ['It prevents flexible redefinition from making any outcome seem optimal', 'It guarantees birds choose the largest prey', 'It removes the need to measure predation risk', 'It converts energy into an observed behavior'], 0, 'Advance specification preserves testability.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-clean-bench', 'Listen to an Announcement', '무균 작업대', 'B2', 'Clean Bench Three will be certified Friday morning. Work may resume only after the airflow sticker is posted, even if the technician finishes early. Materials left inside Thursday night will be moved to a sealed cart; owners must verify labels before returning them to the bench.', [
    ['What authorizes work to resume?', ['The posted certification sticker rather than the technician’s departure', 'The presence of materials inside the bench', 'An owner returning a cart without inspection', 'Thursday night passing without an alarm'], 0, 'Documented certification controls reopening.'],
    ['What should owners do with moved materials?', ['Confirm identity labels before replacing them', 'Assume cart position proves ownership', 'Remove the airflow sticker', 'Leave every item sealed permanently'], 0, 'Handling can disrupt spatial assumptions, so labels must govern.'],
  ]),
  ...listeningGroup('announcement-ferry', 'Listen to an Announcement', '현장 이동', 'B1', 'The research ferry departs the main pier at seven. Because of low tide, it returns to the east pier at four rather than the main pier. Equipment vehicles should wait at the east pier; passengers without vehicles can take the campus shuttle back from there.', [
    ['What changes about the return trip?', ['The ferry arrives at a different pier', 'The morning departure moves to four', 'Equipment vehicles board at the main pier after return', 'The campus shuttle travels to the research island'], 0, 'Low tide changes the arrival location.'],
    ['Who can use the shuttle after return?', ['Passengers needing transport from the east pier', 'Equipment vehicles waiting to load', 'Researchers still on the island at seven', 'Only the ferry crew'], 0, 'The shuttle connects the alternate pier to campus.'],
  ]),
  ...listeningGroup('announcement-papyrus', 'Listen to an Announcement', '파피루스 열람', 'C1', 'The papyrus collection will undergo imaging next week. Confirmed readers may keep appointments, but requested fragments will be available only after the imaging team releases them each afternoon. Do not schedule tightly timed comparisons across boxes; release order follows conservation condition, not catalog number.', [
    ['What remains available during imaging week?', ['Confirmed appointments with material released gradually', 'Immediate access to every requested fragment in number order', 'Unsupervised handling before conservation review', 'Guaranteed simultaneous delivery of several boxes'], 0, 'Reading continues under a rolling release process.'],
    ['Why should researchers avoid tightly timed comparisons?', ['Material availability follows condition-based workflow rather than predictable catalog sequence', 'Imaging permanently changes every catalog number', 'Confirmed appointments end before afternoon release', 'Fragments may never return to the collection'], 0, 'Release timing is uncertain and nonsequential.'],
  ]),
  ...listeningGroup('announcement-concert', 'Listen to an Announcement', '야외 공연', 'B2', 'The chamber concert remains outdoors despite light rain. Fabric canopies protect performers, but audience umbrellas must stay in the rear section to preserve sightlines. Front-section ticket holders who need an umbrella may exchange their places at the information desk before seven forty-five.', [
    ['Where may audience umbrellas be used?', ['In the rear area designated to protect sightlines', 'Anywhere in the front ticket section', 'Under the performers’ fabric canopy', 'Only after the concert ends'], 0, 'Umbrella placement balances weather protection and visibility.'],
    ['What option is available to a front-section attendee?', ['Exchange the seat before the stated cutoff', 'Move the performers’ canopy over the audience', 'Use an umbrella without changing location', 'Request cancellation of light rain'], 0, 'The desk can relocate the attendee.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-eddies', 'Listen to an Academic Talk', '해양역학', 'C1', 'Mesoscale eddies are rotating bodies of water tens to hundreds of kilometers across. They can trap heat, salt, nutrients, and organisms, transporting them away from the region where the eddy formed. A warm-core eddy may depress density surfaces, while a cold-core eddy raises them. Satellite sea-surface height and temperature reveal many eddies, but subsurface floats and ship measurements are needed to determine depth structure. Not every circular feature persists as a coherent transporter; water may leak through deformation and mixing.', [
    ['How can an eddy affect distant ecosystems?', ['It can carry trapped physical and biological properties across regions', 'Rotation prevents any nutrient from entering its water', 'Every circular surface pattern extends to the seafloor', 'Warm cores always raise subsurface density surfaces'], 0, 'Coherent motion redistributes water properties.'],
    ['Why are subsurface observations necessary?', ['Surface appearance does not establish the eddy’s vertical extent and contents', 'Satellites directly measure every deep current', 'Ship measurements cannot observe temperature', 'All eddies have an identical depth'], 0, 'Three-dimensional structure determines transport.'],
  ]),
  ...listeningGroup('talk-defaults', 'Listen to an Academic Talk', '행동공공정책', 'C1', 'A default is the option implemented when a person makes no active choice. Defaults can strongly influence enrollment in retirement plans or organ-donor registries because switching requires attention or effort and because people may interpret the default as recommended. Effects are not automatically benign. A poorly chosen default can exploit inattention, and high enrollment may not reflect informed preference. Ethical evaluation considers transparency, ease of opting out, evidence about welfare, and whose interests shaped the default.', [
    ['Why might people follow a default besides simple laziness?', ['They may infer that the preselected option carries an endorsement', 'Switching options is legally impossible in every system', 'Defaults reveal each person’s fully informed preference', 'Enrollment always reduces administrative effort to zero'], 0, 'Default status conveys possible social information.'],
    ['Why is a high take-up rate not enough to judge success?', ['Participation can arise from inattention rather than improved individual welfare', 'Take-up directly measures every participant’s understanding', 'Ethical defaults must prevent opting out', 'Transparency necessarily lowers welfare'], 0, 'Behavioral response is not the same as benefit.'],
  ]),
  ...listeningGroup('talk-face', 'Listen to an Academic Talk', '시각인지', 'C1', 'Face perception relies on local features and their spatial configuration. Turning a face upside down disproportionately impairs recognition, suggesting that experience tunes observers to upright relationships. The composite-face illusion occurs when aligned halves from different faces are fused perceptually, making one half harder to judge independently. Expertise and attention influence these effects, but they do not prove a dedicated face module operating in isolation. Researchers compare faces with other categories and manipulate alignment, orientation, and familiarity.', [
    ['What does the inversion effect suggest?', ['Recognition depends heavily on learned upright configurations', 'Upside-down images contain fewer visual features', 'Observers identify every isolated feature more accurately', 'Spatial relations matter only for unfamiliar objects'], 0, 'Orientation disrupts configural processing.'],
    ['Why manipulate alignment in composite faces?', ['Misalignment weakens integration and tests whether halves are processed holistically', 'Alignment removes all local feature information', 'Composite faces can be created only from familiar people', 'Orientation and alignment have identical physical effects'], 0, 'The manipulation isolates compulsory integration.'],
  ]),
  ...listeningGroup('talk-arches', 'Listen to an Academic Talk', '건축구조사', 'B2', 'A masonry arch transfers load through compression along its curve and pushes outward at its supports. During construction, temporary centering holds stones until the keystone and surrounding masonry complete the load path. The keystone is visually prominent but does not alone support the arch. Settlement can alter thrust and open joints. Buttresses or adjacent walls resist lateral force, so removing nearby masonry may destabilize an arch that appears intact.', [
    ['Why is temporary centering needed?', ['The incomplete arch cannot carry compression through a closed load path', 'The keystone supports every stone before placement', 'Compression occurs only in wooden structures', 'Buttresses eliminate construction loads'], 0, 'Support is required until the geometry becomes self-carrying.'],
    ['Why can removing an adjacent wall be dangerous?', ['It may have resisted the arch’s outward thrust', 'An intact arch produces no lateral force', 'Settlement strengthens all mortar joints', 'The wall prevents placement of the keystone'], 0, 'Structural behavior depends on connected supports.'],
  ]),
  ...listeningGroup('talk-creoles', 'Listen to an Academic Talk', '접촉언어학', 'C1', 'Creole languages emerge in intense language-contact settings, often where speakers lack one shared first language. Earlier accounts sometimes described creoles as simplified or exceptional, but research shows they have systematic grammar and expressive capacity like other languages. Vocabulary may come largely from one lexifier, while grammatical patterns reflect multiple sources, universal tendencies, and innovation. Similar features across creoles do not imply one origin or an absence of history. Scholars examine social conditions, documented stages, substrate languages, and ongoing change.', [
    ['Why is calling creoles merely simplified misleading?', ['They possess organized, productive grammatical systems rather than incomplete language', 'Their vocabulary never comes from another language', 'Contact prevents innovation and historical development', 'All creoles share one identical grammar'], 0, 'Reduced social prestige is not linguistic deficiency.'],
    ['Why do shared features not prove a single origin?', ['Parallel contact pressures and structural tendencies can yield similar outcomes', 'Every creole developed in one historical community', 'Substrate languages contribute no patterns', 'Lexifier vocabulary determines all grammar'], 0, 'Convergence has several possible sources.'],
  ]),
  ...listeningGroup('talk-fire', 'Listen to an Academic Talk', '화재생태학', 'C1', 'Wildfire behavior depends on fuel, weather, and topography. Fine dry fuels ignite readily and carry flames, while larger fuels sustain heat. Wind supplies oxygen, bends flames toward unburned material, and transports embers. Fire often moves faster uphill because flames preheat fuel above. Fuel treatment can reduce intensity locally, but extreme weather may overwhelm it, and treatment placement matters. Burn severity describes ecological effects, not simply flame height during the event. Postfire assessment combines satellite change with field measurements of soil and vegetation.', [
    ['Why does fire commonly accelerate uphill?', ['Fuel upslope receives more radiant and convective preheating', 'Gravity removes oxygen from ascending flames', 'Large fuels disappear on slopes', 'Embers can travel only downhill'], 0, 'Slope brings flame and unburned fuel into closer thermal interaction.'],
    ['Why is field assessment needed after satellite mapping?', ['Spectral change does not fully reveal soil heating and biological damage', 'Satellites cannot observe any burned area', 'Flame height directly equals ecological severity', 'Vegetation response is identical across fuel types'], 0, 'Severity is multidimensional and ground truth refines inference.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the adjusted estimate unstable?', 'Had sufficient overlap existed at the extremes', ['no participant', 'would have received', 'such a disproportionately', 'large weight'], 'f21-had-existed-negative-result'],
  ['What did the core comparison show?', 'Absent from the undisturbed sequence was', ['the abrupt', 'pollen shift', 'that had seemed', 'so prominent', 'inside the damaged', 'core'], 'f21-absent-locative-inversion'],
  ['Why was the clock left stationary?', 'Valuable though its movement would be for demonstration', ['operating it', 'would accelerate wear', 'on several', 'original pivots'], 'f21-adjective-though-gerund-subject'],
  ['How should the optimality model be tested?', 'Only if its currency is specified before observing behavior', ['can a deviation', 'genuinely challenge', 'the model’s', 'prediction'], 'f21-only-if-passive-inversion'],
  ['What complicated the papyrus date?', 'The regnal year being ambiguous', ['two competing', 'calendar conversions', 'remained', 'historically plausible'], 'f21-nominative-absolute-being'],
  ['Why did the aerogel panel underperform?', 'The more moisture its pores absorbed', ['the less closely', 'its conductivity resembled', 'the dry laboratory', 'value'], 'f21-double-comparative-perfect'],
  ['What did the matching procedure accomplish?', 'Not so much did it recover the full treated population', ['as it created', 'a balanced subset', 'for which comparison', 'was defensible'], 'f21-not-so-much-inversion-as'],
  ['Why retain the two-sided papyrus?', 'Even if the later text is the primary document', ['the earlier writing', 'may reveal', 'how the sheet', 'was reused'], 'f21-even-if-concessive-primary'],
  ['What condition applied to the field sample?', 'Under no circumstances was the vendor to know', ['which blinded specimen', 'represented', 'the team’s', 'ordinary material'], 'f21-under-no-circumstances-inversion'],
  ['Why did the reviewers limit the claim?', 'So dependent was performance on dry conditions that', ['the laboratory result', 'could not be', 'generalized directly', 'to buildings'], 'f21-so-dependent-inversion-passive'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '세포주 인증', 'C1', 420), instruction: '현재 증거의 한계, 연구 위험, 필요한 검사와 기록 절차를 구체적으로 작성하세요.', prompt: 'You discover that a cell line used for several months has a vendor certificate but has never been authenticated after arriving in the laboratory. Write to the project leader. Explain why the certificate is insufficient, describe the risk to current results, and request authentication, quarantine, and a documented decision about affected experiments.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '행동 정책의 기본값', 'C1', 600), instruction: '효율성, 자율성, 투명성을 구체적인 정책 조건과 함께 평가하세요.', prompt: 'Professor Amari: Is it ethical for governments or employers to automatically enroll people in beneficial programs unless they actively opt out?', passage: 'Chloe: Defaults help people obtain benefits they intend to choose but often postpone.\nRavi: Automatic enrollment can manipulate inattentive people and may conceal options that fit them better.' })

const repeatSentences = ['Welcome to the university paleoenvironment laboratory.', 'Confirm the core section and depth before opening its sample bag.', 'Clean every tool between levels to prevent sediment transfer.', 'Add the marker spores before beginning chemical preparation.', 'Count pollen along systematic microscope transects rather than preferred fields.', 'Record damaged grains and uncertain identifications in separate categories.', 'After analysis, archive the count sheet, calculation file, slide code, and remaining sediment so another researcher can reconstruct every processing step.']
const interviewQuestions = ['Describe a policy that uses a default option when people make no active choice.', 'Why might the default increase participation?', 'How could the default work against an individual’s interests?', 'What information and opt-out process would make the policy more ethical?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '화분 분석실', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f21-repeat', scenarioId: 'f21-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '기본값과 선택', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f21-interview', scenarioId: 'f21-interview', sequenceIndex })),
]

export const AUTHORED_FORM_21_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_21_IDS = AUTHORED_FORM_21_ITEMS.map((item) => item.id)
