import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f17')

const reading: BaseItem[] = [
  cloze('cloze-telomeres', '세포생물학', 'C1', 'Chromosome ends require protection because ordinary DNA-repair systems might mistake them for broken strands. Telomeres consist of repeated sequences and associated proteins that shi___ natural ends from repair. Conventional replication cannot fully copy the end of a linear chromosome, so telomeres often shor___ as cells divide. The enzyme telomerase can ext___ them using an internal RNA template. It is active in many stem and reproductive cells but rest___ in most adult tissues. Short telomeres can trigger senescence, which lim___ damaged-cell proliferation yet may impair tissue renewal. Many cancers react___ telomerase or another maintenance pathway. Telomere length is therefore neither a simple clock nor an independent cause of every age-related condition. Inheritance, stress, cell composition, and measurement method all aff___ observed values. Researchers use longitudinal designs to sep___ change within individuals from differences among cohorts and avoid inf___ mechanism from correlation al___.', 'eld|ten|end|ricted|its|ivate|ect|arate|erring|one'),
  cloze('cloze-isostasy', '지형학', 'C1', 'Large ice sheets press Earth’s crust downward. After the ice melts, the reduced load allows the land to reb___ gradually, a process called glacial isostatic adjustment. The mantle flows slowly, so uplift cont___ for thousands of years. Some coastlines rise relative to sea level, while nearby areas may sub___ as a peripheral bulge collapses. Tide-gauge records therefore comb___ global ocean change with vertical land motion. Satellite positioning helps sep___ the components. The response depends on past ice thickness and mantle vis___, allowing observations to constr___ Earth models. Ancient shorelines provide longer evidence but may be til___ or eroded. Researchers integrate geological and geodetic data rather than ass___ that present uplift rates were constant. Adjustment also redistr___ mass, subtly influencing gravity and Earth’s rotation.', 'ound|inues|side|ine|arate|cosity|ain|ted|uming|ibutes'),
  cloze('cloze-illumination', '사본미술사', 'B2', 'Illuminated manuscripts combine handwritten text with painted decoration. Gold leaf may be appl___ over a prepared ground and burnished to reflect light. Pigments were mixed with binders that adh___ them to parchment. Artists planned margins, initials, and images before or during copying, yet later owners also add___ notes and coats of arms. Variations in style can rev___ collaboration among specialists. Scientific imaging iden___ underdrawing and altered passages without always requiring a sample. Material analysis can trace a pigment but not automatically loc___ the workshop, since valuable substances circulated widely. Binding changes may trim decoration or rearr___ pages. Scholars compare textual sequence, quire structure, and wear to rec___ the object’s history. Conservation must bal___ visibility with the light sensitivity of colorants and doc___ modern repair.', 'ied|ered|ed|eal|tifies|ate|ange|onstruct|ance|ument'),
  daily('daily-vacuum-pump', '진공 장비', 'B2', 'Shared vacuum pumps must cool for twenty minutes before oil level is checked. A low reading taken while the pump is hot can be misleading. Users should log unusual noise immediately but must not add oil without technician authorization.', ['Why is the oil check delayed after operation?', ['Temperature can distort the apparent level in the pump', 'Cooling permanently removes oil from the reservoir', 'Noise can be logged only after new oil is added', 'Technicians cannot authorize maintenance while equipment is warm'], 0, 'The reading becomes reliable after cooling.']),
  daily('daily-map-room', '지도 자료실', 'B2', 'Oversized maps are retrieved onto a horizontal table and remain flat during consultation. Researchers may photograph sections from above but cannot roll the map to fit a camera frame. Staff provide weighted polyester strips to hold curling edges without adhesive.', ['How should a curling map edge be secured?', ['With the supplied nonadhesive weighted strip', 'By rolling the sheet tightly around the camera', 'With removable tape attached to the original paper', 'By folding the oversized section beneath the table'], 0, 'The approved weight controls curl without attachment.']),
  daily('daily-participant-payment', '연구 참여비', 'C1', 'Participant payment is issued for completed visits, not contingent on producing usable data. A sensor failure after the participant followed instructions does not cancel compensation. Partial payment rules for early withdrawal must appear in the consent form before enrollment.', ['Who remains entitled to the scheduled visit payment?', ['A compliant participant whose equipment failed during collection', 'A participant promised compensation only after the data pass analysis', 'A researcher who omitted withdrawal terms from consent', 'A sensor manufacturer whose device produced unusable output'], 0, 'Compensation recognizes participation rather than data success.']),
  daily('daily-rehearsal-room', '공연 연습실', 'B1', 'Rehearsal Room Four has no piano until Thursday while its instrument is tuned. Groups may move to Room Six if they reserve it separately. The original reservation does not transfer automatically because Room Six has a smaller capacity.', ['What must a group do to use Room Six?', ['Make a separate booking for the alternative room', 'Wait for the piano tuner inside Room Four', 'Transfer the original booking without checking capacity', 'Reduce its membership after arriving unannounced'], 0, 'The alternative requires its own reservation.']),
  daily('daily-anonymization', '데이터 공유', 'C1', 'Removing names does not necessarily anonymize a dataset. Rare combinations of age, location, and occupation may identify individuals when linked with public information. Before release, the data steward evaluates both direct identifiers and plausible linkage attacks, then reduces detail or restricts access accordingly.', ['Why can a nameless record still disclose identity?', ['A distinctive combination of attributes may match external information', 'Direct identifiers automatically reappear after file download', 'Public information contains no demographic attributes', 'Restricted access increases the number of rare combinations'], 0, 'Reidentification can exploit quasi-identifiers.']),
  daily('daily-courier-window', '미술품 운송', 'B2', 'The art courier’s arrival window begins at eight, but the loading dock opens at eight thirty. Drivers arriving earlier must wait in the secured vehicle area; objects cannot be left at the exterior desk. The registrar signs custody only after crate seals are inspected inside.', ['When does institutional custody formally begin?', ['After the registrar inspects the seals and signs indoors', 'When the vehicle first enters the secured waiting area', 'At the start of the courier’s stated arrival window', 'When a crate is placed at the exterior service desk'], 0, 'Custody transfer requires inspection and signature.']),
  daily('daily-office-hours', '교수 상담', 'B2', 'Students may join virtual office hours without an appointment for brief questions. Draft reviews longer than one page require a reserved fifteen-minute slot and submission by the previous evening. Joining the open queue does not substitute for the draft-review process.', ['What should a student seeking detailed draft feedback do?', ['Reserve a timed slot and send the draft beforehand', 'Enter the brief-question queue with several pages', 'Submit the draft after the meeting has concluded', 'Assume an open queue guarantees a fifteen-minute review'], 0, 'Long review requires scheduling and advance material.']),
  daily('daily-sample-photo', '고고학 기록', 'B2', 'Find photographs are named with context number, object number, and scale status. A photo without a scale may document color or condition but cannot replace the measured identification view. Renaming files after upload must be synchronized with the field register.', ['What is a limitation of a photograph lacking a scale?', ['It cannot serve as the primary dimensional identification image', 'It becomes unusable for recording surface condition', 'It automatically loses the object’s context number', 'It cannot be renamed in coordination with the register'], 0, 'Measurement interpretation needs a scale reference.']),
  daily('daily-library-renewal', '자료 대출', 'B1', 'A recalled book cannot be renewed online, even when the current due date has not arrived. Return it by the revised recall date shown in the notice. If another copy becomes available first, the library will remove the recall and email a new renewal option.', ['What could restore the option to renew?', ['Availability of another copy that satisfies the recall', 'Ignoring the revised return date until the original due date', 'Deleting the library’s recall notification', 'Keeping the requested copy outside the catalog'], 0, 'A replacement copy can resolve demand.']),
  daily('daily-weather-station', '기상 관측', 'B2', 'A weather-station battery replacement creates a documented break in the time series. Do not interpolate rainfall across the break because the gauge may have been unable to record an event. Mark the interval missing and use a nearby station only in a separately described reconstruction.', ['Why should rainfall not be interpolated automatically?', ['An unobserved event could have occurred while the gauge lacked power', 'Battery replacement proves that precipitation was zero', 'Nearby stations always report identical local rainfall', 'A documented break removes the need to flag missing data'], 0, 'Missing observation is not evidence of no rain.']),
  ...readingGroup('academic-did', '정책평가', 'C1', 'Difference-in-differences estimates a policy effect by comparing outcome changes over time between a treated group and a comparison group. It removes stable group differences and shocks common to both groups. Identification relies on parallel trends: without the policy, the groups’ average outcomes would have changed similarly. Similar pre-policy trends support but cannot prove this counterfactual. Anticipation, changing group composition, or another group-specific event can bias the estimate. With treatment adopted at different times, conventional two-way fixed-effects estimates may combine comparisons with problematic weights when effects vary. Researchers inspect event-time patterns and use estimators appropriate to staggered adoption.', [
    ['Which counterfactual pattern must be assumed for this design?', ['How treated outcomes would have evolved relative to comparison outcomes without the policy', 'Whether the groups had identical outcome levels before treatment', 'Whether every individual responds to the policy by the same amount', 'How common shocks affect only the treated group'], 0, 'The assumption is about counterfactual changes, not levels.'],
    ['Why are similar pre-policy trends not definitive proof?', ['Post-policy counterfactual trends remain unobserved and may diverge for new reasons', 'Pre-policy data contain no outcomes for either group', 'Stable differences cannot be removed by differencing', 'Common shocks necessarily begin before every policy'], 0, 'Historical fit cannot verify an unobserved future path.'],
    ['What complication arises with staggered adoption?', ['Standard estimates can mix cohort and timing comparisons in misleading ways', 'All groups receive treatment at one identical date', 'Event-time analysis becomes impossible when effects are constant', 'Fixed effects automatically exclude untreated observations'], 0, 'Heterogeneous timing and effects alter implicit weighting.'],
  ]),
  ...readingGroup('academic-biological-market', '상호작용생태학', 'C1', 'Biological market theory applies ideas of partner choice and competition to mutualisms. Cleaner fish may provide parasite removal to client fish, while plants exchange carbon for nutrients with microbial partners. If partners can choose among providers, individuals offering better terms may receive more interactions. Yet the analogy to human markets has limits: exchange currencies may be difficult to measure, partners can manipulate one another, and ecological constraints may prevent switching. Observing reciprocal benefit alone does not demonstrate a market. Researchers seek variation in supply, demand, partner choice, and adjustment of exchanged services.', [
    ['What distinguishes a biological market from mutual benefit alone?', ['Partner choice and competition must influence the terms or frequency of exchange', 'Both organisms must use money to value the service', 'One species must receive every benefit without providing anything', 'Partners must be unable to switch after an interaction'], 0, 'Market logic adds choice and supply-demand responses.'],
    ['Why may market competition be weak in some mutualisms?', ['Spatial or ecological constraints can leave partners with few alternatives', 'Reciprocal benefit eliminates all possibility of manipulation', 'Exchange services are always measured in one universal currency', 'Abundant providers prevent any organism from choosing'], 0, 'Limited outside options restrict bargaining-like dynamics.'],
  ]),
  ...readingGroup('academic-oral-formula', '구전문학', 'C1', 'Oral-formulaic theory explains how performers can compose long narratives during performance by drawing on reusable phrases, type-scenes, and metrical patterns. Repetition is not necessarily evidence of mechanical memorization or artistic failure; formulas provide flexible building blocks. A singer may adapt an episode to audience, occasion, and available time while preserving recognizable structure. Written texts can record one performance but may also reflect editing, dictation, or interaction with literary traditions. Scholars compare variants and performance practice rather than treating one transcription as the definitive original.', [
    ['How do formulas assist oral performers?', ['They provide adaptable units that support composition in real time', 'They require the performer to reproduce one fixed text verbatim', 'They eliminate the influence of audience and occasion', 'They indicate that every repeated phrase was added by an editor'], 0, 'Reusable patterns reduce compositional burden while allowing variation.'],
    ['Why is a written version not necessarily the unique original?', ['It may capture one variable event and undergo processes beyond performance', 'Oral narratives cannot be transcribed in metrical form', 'Editing always removes every formula from a text', 'A performer never repeats an episode across occasions'], 0, 'Textual fixation is one stage in a changing tradition.'],
    ['What evidence best supports analysis of oral composition?', ['Comparison across performances, variants, and recurring structural units', 'Selection of the longest surviving transcription as authoritative', 'Elimination of all passages shared by two singers', 'Assumption that repetition reveals poor memory'], 0, 'Variation and patterned reuse expose the compositional system.'],
  ]),
  ...readingGroup('academic-catalysis', '표면화학', 'C1', 'A catalyst accelerates a reaction by providing a pathway with lower activation barriers, but it does not change the equilibrium composition at a fixed temperature. It speeds forward and reverse reactions. Heterogeneous catalysis occurs at a surface: reactants adsorb, bonds rearrange, and products desorb. Stronger adsorption is not always better. If molecules bind too weakly, they do not react; if products bind too strongly, they block active sites. Catalysts can deactivate through poisoning, sintering, or deposition. Measuring initial conversion alone may therefore conceal declining performance and does not reveal which elementary step controls the rate.', [
    ['Why does a catalyst not change equilibrium composition?', ['It accelerates pathways in both reaction directions without altering thermodynamic favorability', 'It prevents reverse reactions from occurring at the surface', 'It increases activation energy until products dominate', 'It removes temperature from the equilibrium condition'], 0, 'Kinetics change while equilibrium thermodynamics remain.'],
    ['Why can very strong adsorption reduce catalytic activity?', ['Products or intermediates may occupy sites and prevent further turnover', 'Reactants cannot encounter a surface unless they remain in the gas phase', 'Strong binding always raises equilibrium product concentration', 'Adsorption permanently eliminates activation barriers'], 0, 'Site blockage can offset capture of reactants.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the replacement electrode pass its drift test?', ['Yes, after it stabilized in the reference solution.', 'The electrode is stored in a protective sleeve.', 'Drift appears as gradual signal change.', 'I passed the laboratory on my way outside.'], 0, 'The response confirms successful testing.'),
  response(1, 'Why did the archive reject my image request?', ['The image depicts a nineteenth-century port.', 'The requested resolution exceeds the permitted license.', 'I rejected the automatic color correction.', 'Archive requests normally take three business days.'], 1, 'A license restriction explains rejection.'),
  response(2, 'Could anticipation bias the policy estimate?', ['The estimate compares two outcome changes.', 'Anticipation occurs before formal implementation.', 'Yes, if people changed behavior before the recorded start date.', 'I anticipated a question about the sampling design.'], 2, 'Pre-treatment response contaminates timing.'),
  response(3, 'I assumed the field course provided rubber boots.', ['The course visits wetlands and coastal dunes.', 'Rubber boots should be rinsed between sites.', 'I provided the requested tax form yesterday.', 'Chest waders are shared, but personal boots are required.'], 3, 'The response distinguishes available equipment.'),
  response(4, 'May we detach the frame to inspect the canvas edge?', ['Only with the paintings conservator supervising the procedure.', 'The frame contains carved botanical ornaments.', 'Canvas edges often preserve fastening evidence.', 'I inspected the edge cases in the algorithm.'], 0, 'Specialist supervision is required.'),
  response(5, 'Where is the original randomization sequence stored?', ['Randomization balanced expected treatment allocation.', 'In the encrypted registry separate from outcome data.', 'The sequence contains blocks of variable size.', 'I stored the sample tubes in randomized order.'], 1, 'Separation protects concealment.'),
  response(6, 'Shouldn’t the annotation guide define uncertain cases?', ['The guide uses examples from last year’s corpus.', 'Uncertainty can lower agreement among coders.', 'Yes, and it should specify when to escalate rather than guess.', 'I guided the visitor to the annotation exhibit.'], 2, 'A decision rule should handle ambiguity.'),
  response(7, 'The portable balance gives a different mass outdoors.', ['The balance measures to one milligram.', 'Outdoor samples were placed in sealed bags.', 'I balanced the discussion between two theories.', 'Shield it from wind and verify level before recalibrating.'], 3, 'Environmental effects should be checked first.'),
  response(8, 'Is the oral-history embargo still in effect?', ['Until the donor’s specified review date next spring.', 'The interview describes a community theater.', 'Embargoes can limit access for a defined period.', 'I reviewed the transcript for spelling errors.'], 0, 'The reply supplies the embargo endpoint.'),
  response(9, 'Why did the confidence band widen after weighting?', ['The band is shaded behind the estimated curve.', 'A few observations received large design weights.', 'I weighed each dry specimen before storage.', 'Confidence levels are listed in the methods section.'], 1, 'Extreme weights reduce effective precision.'),
  response(10, 'Can we treat this dark layer as one eruption?', ['The layer occurs beneath a buried soil horizon.', 'Eruptions deposit particles of various sizes.', 'Not without testing whether its glass chemistry is homogeneous.', 'I treated the corroded surface with a reversible coating.'], 2, 'Chemical variation may reveal multiple events.'),
  response(11, 'I cannot locate the source of this derived variable.', ['The variable combines household income and size.', 'Derived measures simplify several raw fields.', 'I located the archive on the campus map.', 'Trace its dependency entry in the data dictionary.'], 3, 'The dictionary should document derivation.'),
  response(12, 'Has the temporary humidity barrier been approved?', ['Provisionally, pending a twenty-four-hour sensor test.', 'Humidity affects dimensional change in wood.', 'The barrier consists of overlapping polymer sheets.', 'I approved the revised travel budget.'], 0, 'Approval depends on performance testing.'),
  response(13, 'When will the microscopy training certificates appear?', ['The course covers fluorescence and transmitted light.', 'After the instructor validates yesterday’s practical assessments.', 'I trained the classifier on annotated images.', 'Certificates remain valid for two years.'], 1, 'Validation precedes certificate posting.'),
  response(14, 'Would a placebo with mild sensations improve blinding?', ['The placebo group attends the same number of visits.', 'Mild sensations may alter participant expectations.', 'Perhaps, though those sensations could have effects of their own.', 'I placed the tablets in identical bottles.'], 2, 'An active placebo creates a new interpretive tradeoff.'),
  response(15, 'Who authorized release of the restricted coordinates?', ['The coordinates identify a vulnerable nesting colony.', 'Release requests require a documented purpose.', 'The map was released in a lower-resolution format.', 'The data steward approved access for the named conservation team.'], 3, 'The approving authority and scope are specified.'),
  response(16, 'This reconstructed vessel looks more symmetrical than the fragments.', ['Check whether the software mirrored missing geometry.', 'The vessel was used to store dry grain.', 'Fragments were arranged on a padded tray.', 'I reconstructed the argument from several quotations.'], 0, 'Automated symmetry may exceed the evidence.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-pretrend', 'Listen to a Conversation', '정책 데이터', 'C1', 'Student: The treated and comparison cities have similar trends for three years, except for a small divergence just before the policy. Advisor: That last change matters. It could be anticipation, a temporary shock, or ordinary noise. Student: Should I drop the year? Advisor: Not merely to improve the graph. Investigate contemporaneous events, show estimates with and without it, and reconsider whether this comparison group supports the design.', [
    ['Why does the advisor focus on the final pre-policy year?', ['Its divergence may signal a violation relevant to the counterfactual trend', 'It proves the policy had no effect after implementation', 'Three earlier years automatically make the last observation irrelevant', 'Dropping it guarantees unbiased estimation'], 0, 'A late deviation can reveal anticipation or a group-specific shock.'],
    ['What approach does the advisor recommend?', ['Diagnose and report sensitivity rather than deleting inconvenient evidence', 'Select the graph with the most parallel-looking lines', 'Treat the divergence as policy impact by definition', 'Replace city data with national averages'], 0, 'Transparent investigation precedes specification choice.'],
  ]),
  ...listeningGroup('conversation-exhibit-sound', 'Listen to a Conversation', '박물관 음향', 'B2', 'Designer: Visitors hear the next station before finishing this one. Curator: Could we lower every speaker? Designer: Then speech may be inaudible for users who need the bench. Directional speakers and a short buffer between tracks would reduce overlap without lowering the accessible listening level.', [
    ['What problem does the designer identify with lowering all speakers?', ['It could reduce intelligibility at the intended listening position', 'It would make the next station begin earlier', 'Directional speakers cannot reproduce speech', 'Visitors sitting on the bench prefer overlapping tracks'], 0, 'Global level reduction harms access.'],
    ['What combined solution is suggested?', ['Constrain the sound field and separate playback timing', 'Remove the seating and increase every volume', 'Play both stations through one central loudspeaker', 'Replace spoken interpretation with silent labels only'], 0, 'Spatial direction and temporal spacing address bleed.'],
  ]),
  ...listeningGroup('conversation-contamination', 'Listen to a Conversation', '고대 DNA', 'C1', 'Assistant: The negative control contains a few human reads. Geneticist: Were the extraction blanks processed with the bones? Assistant: Yes, in alternating positions. Geneticist: Then contamination may have entered during extraction or sequencing. Do not remove matching reads and proceed as if nothing happened. Compare damage patterns, read lengths, and batch positions, and repeat critical samples independently.', [
    ['What does the negative control reveal?', ['Human DNA entered at some stage without an archaeological specimen', 'Every ancient bone contains identical modern sequences', 'Alternating positions prevent all laboratory contamination', 'Sequencing cannot produce reads from an extraction blank'], 0, 'A blank signal indicates workflow background.'],
    ['Why examine damage patterns and read lengths?', ['Ancient and recent DNA may exhibit different molecular signatures', 'They identify the exact person who handled each tube', 'They guarantee contamination occurred only during excavation', 'Removing matching reads makes independent replication unnecessary'], 0, 'Molecular characteristics help assess authenticity.'],
  ]),
  ...listeningGroup('conversation-accession', 'Listen to a Conversation', '기증 문서', 'C1', 'Archivist: The donor agreement transfers the papers but restricts correspondence for twenty years. Historian: The donor has since published excerpts online. Does that open the archive copies? Archivist: Not automatically. Public disclosure may affect sensitivity, but the contractual restriction remains until amended. I can ask the donor to narrow it for letters already released.', [
    ['Why does online publication not automatically open the archive?', ['The repository remains bound by the terms of its agreement', 'Published excerpts transfer ownership back to the historian', 'Contractual restrictions apply only to unpublished writers', 'The archive cannot identify which letters appeared online'], 0, 'External disclosure and repository authorization are distinct.'],
    ['What possible remedy does the archivist offer?', ['Seek a formal modification for material already made public', 'Ignore the agreement because sensitivity has decreased', 'Extend the restriction to all of the donor’s publications', 'Return every unrestricted paper immediately'], 0, 'An amendment can align access with current circumstances.'],
  ]),
  ...listeningGroup('conversation-sensor-site', 'Listen to a Conversation', '도시 열 연구', 'B2', 'Student: The downtown sensor is consistently warmer than the park sensor. Professor: It may be a real urban difference, but the downtown unit is mounted above an air-conditioning vent. Student: Should we relocate it? Professor: First colocate both sensors at a neutral site. If they agree, move the downtown unit to a representative location and document the break in the series.', [
    ['Why is the current comparison ambiguous?', ['The sites differ environmentally and one installation may have a local heat source', 'Park sensors cannot measure urban temperature', 'Colocation creates a permanent break in every time series', 'Air-conditioning vents always lower nearby readings'], 0, 'Site effect and sensor or placement effect are confounded.'],
    ['What will colocation test?', ['Whether the instruments report comparably under shared conditions', 'Whether downtown remains warmer than the park during all seasons', 'Whether the vent can be turned off permanently', 'Whether historical data need no documentation'], 0, 'A common environment isolates instrument agreement.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-centrifuge', 'Listen to an Announcement', '원심분리실', 'B2', 'Centrifuge Two is available again after rotor inspection, but only the fixed-angle rotor has been cleared. The swinging-bucket rotor remains tagged out. Reservations stay active; users needing buckets may move to Centrifuge Four if they update the equipment field before loading samples.', [
    ['Which component is approved for use?', ['The fixed-angle rotor in Centrifuge Two', 'The tagged swinging-bucket assembly', 'Every rotor that fits Centrifuge Four', 'An uninspected rotor brought by a user'], 0, 'Clearance is rotor-specific.'],
    ['What must users do before switching machines?', ['Change the equipment entry attached to the reservation', 'Cancel all reservations for Centrifuge Two', 'Load samples before selecting Centrifuge Four', 'Remove the official tag from the bucket rotor'], 0, 'The booking record must match actual equipment.'],
  ]),
  ...listeningGroup('announcement-poetry', 'Listen to an Announcement', '낭독 행사', 'B1', 'The poetry reading starts at six in the courtyard. If wind exceeds the sound-system limit, it moves to the library atrium; light rain alone will not move it. Check the venue message at five fifteen. Indoor seating is smaller, so courtyard tickets become first-come entry if relocation occurs.', [
    ['What condition triggers relocation?', ['Wind above the operating limit for the audio equipment', 'Any amount of rain before the reading', 'A shortage of courtyard tickets', 'The library closing before six'], 0, 'Wind, not light rain, controls the venue decision.'],
    ['What changes if the event moves indoors?', ['Original tickets no longer guarantee a seat', 'The start time advances to five fifteen', 'The venue message will not be posted', 'Every poem must be read without amplification'], 0, 'Reduced capacity changes admission priority.'],
  ]),
  ...listeningGroup('announcement-biobank', 'Listen to an Announcement', '바이오뱅크', 'C1', 'The biobank inventory audit begins Monday. Vials may be retrieved for urgent clinical analysis, but research withdrawals pause until Wednesday. An urgent retrieval requires two staff signatures and a photograph of the slot before and after removal. Do not fill the empty slot; its temporary vacancy is part of the audit trail.', [
    ['Which withdrawal remains possible during the pause?', ['A documented retrieval needed for urgent clinical analysis', 'Routine research sampling with one staff signature', 'Relocation of another vial into every open slot', 'Removal without photographing the rack position'], 0, 'The exception is narrowly controlled.'],
    ['Why must the empty position remain unfilled?', ['Its vacancy documents where the audited vial was removed', 'The freezer cannot cool a rack containing adjacent vials', 'Photographs are allowed only when every slot is empty', 'Clinical samples are always stored outside the inventory'], 0, 'Spatial continuity supports the audit trail.'],
  ]),
  ...listeningGroup('announcement-workshop', 'Listen to an Announcement', '논문 작성 워크숍', 'B2', 'Tomorrow’s revision workshop is full. Registered participants should upload one paragraph by nine tonight; the instructor will anonymize examples before class. People on the waiting list may attend the opening lecture online, but only confirmed participants receive small-group feedback.', [
    ['Why must paragraphs be uploaded tonight?', ['The instructor needs time to prepare anonymous examples', 'Waiting-list members will grade them before class', 'The opening lecture cannot be streamed without text', 'Small groups meet before registration is confirmed'], 0, 'Advance processing protects identity and supports instruction.'],
    ['What is available to waiting-list participants?', ['Remote access to the initial lecture segment', 'Guaranteed personalized feedback in a small group', 'Automatic promotion to confirmed registration', 'Publication of their paragraph as a model'], 0, 'The lecture is broader than the capacity-limited workshop.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-alkalinity', 'Listen to an Academic Talk', '해양화학', 'C1', 'Ocean alkalinity measures the water’s capacity to neutralize acid, largely through bicarbonate and carbonate ions. It is not the same as pH, which describes hydrogen-ion activity at a moment. Adding alkalinity can shift dissolved carbon chemistry and potentially increase ocean uptake of atmospheric carbon dioxide. Proposed enhancement methods include adding weathered alkaline minerals. Evaluating them requires accounting for mining, energy, trace metals, ecological effects, and whether additional carbon storage persists rather than merely relocating emissions.', [
    ['How does alkalinity differ from pH?', ['It describes acid-neutralizing capacity rather than the current hydrogen-ion state', 'It measures only the temperature of carbonate minerals', 'It is identical to the amount of atmospheric carbon', 'It excludes bicarbonate from seawater chemistry'], 0, 'Capacity and instantaneous acidity are related but distinct.'],
    ['Why must lifecycle effects be included?', ['Upstream extraction and processing can offset or complicate claimed carbon benefits', 'Mineral addition prevents any ecological response', 'Persistent storage depends solely on water color', 'Mining energy is already part of ocean pH'], 0, 'Net benefit extends beyond the reaction site.'],
  ]),
  ...listeningGroup('talk-monopsony', 'Listen to an Academic Talk', '노동경제학', 'C1', 'A labor market has monopsony power when employers face an upward-sloping labor supply: raising wages attracts or retains more workers. This can arise even with several employers because search costs, location, scheduling, or specialized skills make jobs imperfect substitutes. A wage floor in such a market can raise both wages and employment up to a point by limiting the employer’s incentive to suppress pay. The result is not universal; effects depend on the floor’s level, worker mobility, and employer responses such as reduced hours or increased automation.', [
    ['Why can monopsony power exist with multiple firms?', ['Workers may face frictions that prevent treating all jobs as equivalent options', 'Monopsony requires one legally protected employer in the entire economy', 'Several employers always make labor supply perfectly elastic', 'Specialized skills eliminate search and relocation costs'], 0, 'Imperfect mobility gives firms wage-setting power.'],
    ['How could a moderate wage floor increase employment?', ['It can counteract employment restriction associated with below-competitive wage setting', 'It makes labor supply slope downward at every wage', 'It prohibits employers from attracting additional workers', 'It removes every nonwage difference among jobs'], 0, 'The policy can reduce a monopsonistic distortion.'],
  ]),
  ...listeningGroup('talk-embodiment', 'Listen to an Academic Talk', '인지과학', 'C1', 'Embodied cognition emphasizes that thinking depends partly on bodily capacities and action in an environment. Concepts of space or tools may recruit sensorimotor systems, and gesture can support problem solving. Strong claims that cognition is entirely reducible to bodily interaction go beyond this evidence. Brain-damaged patients can sometimes retain conceptual knowledge despite impaired action, and abstract reasoning uses learned symbols. Researchers distinguish whether motor activation is necessary for understanding, merely facilitates it, or follows from imagining the described event.', [
    ['What distinction is central to evaluating motor activation?', ['Whether it causes or supports understanding rather than simply accompanying it', 'Whether abstract symbols can be written by hand', 'Whether every gesture has one universal meaning', 'Whether bodily systems operate outside any environment'], 0, 'Correlation in timing does not establish functional necessity.'],
    ['Why are patients with impaired action informative?', ['Preserved concepts can challenge claims that motor ability is always required', 'Their injuries prove symbols have no role in reasoning', 'They cannot perform any task involving semantic knowledge', 'Motor impairment invariably improves abstract thought'], 0, 'Dissociation tests strong embodiment hypotheses.'],
  ]),
  ...listeningGroup('talk-domes', 'Listen to an Academic Talk', '건축사', 'B2', 'A masonry dome directs much of its load through compression, but outward thrust develops near its base. Builders countered that thrust with thick walls, buttressing, chains, or surrounding half-domes. Cracks do not all indicate imminent collapse; some reflect settlement or past adjustment that has stabilized. Structural interpretation considers crack direction, movement over time, material condition, and load path. Cosmetic filling before monitoring can conceal whether a crack remains active.', [
    ['Why is support needed around a dome’s base?', ['The curved structure produces outward forces as it carries weight', 'Masonry can withstand only tension and no compression', 'Half-domes remove all vertical loading from a building', 'Thick walls cause every settlement crack'], 0, 'Lateral thrust must be resisted.'],
    ['Why monitor a crack before filling it?', ['Movement data distinguish active structural change from a stable trace', 'Filling increases the direction of the original load', 'All old cracks indicate immediate failure', 'Cosmetic repair reveals hidden settlement'], 0, 'A repair can erase diagnostic evidence.'],
  ]),
  ...listeningGroup('talk-linkage', 'Listen to an Academic Talk', '유전학', 'C1', 'Genes close together on a chromosome tend to be inherited together because a crossover is less likely to occur between them. Recombination frequency therefore provides a map distance, but the relationship is not perfectly linear over long intervals. Multiple crossovers can restore the parental marker arrangement and go undetected, making distant genes appear closer than they are. Mapping functions model this issue, and physical sequence distance offers complementary evidence. Recombination rates also vary by sex, genomic region, and species.', [
    ['Why does observed recombination underestimate long distances?', ['Even numbers of crossovers can hide exchange between the endpoint markers', 'Nearby genes always undergo more crossovers than distant genes', 'Physical sequence distance is identical across every species', 'Parental marker arrangements cannot reappear after meiosis'], 0, 'Unobserved multiple events break simple counting.'],
    ['Why is map distance not a universal conversion to physical distance?', ['Crossover probability varies across genomes and biological contexts', 'Every chromosome has the same sequence length', 'Mapping functions eliminate all regional variation', 'Recombination occurs only between different species'], 0, 'The recombination landscape is heterogeneous.'],
  ]),
  ...listeningGroup('talk-heat-equity', 'Listen to an Academic Talk', '도시기후', 'C1', 'Urban heat exposure reflects both physical temperature and people’s ability to avoid it. Tree canopy, building materials, traffic, and waste heat shape local conditions. Housing quality, energy cost, work schedules, age, and health shape vulnerability. A citywide average can hide hotter neighborhoods and unequal indoor exposure. Planting trees brings cooling but requires time, water, maintenance, and protection against displacement if improved neighborhoods become less affordable. Effective adaptation combines physical measures with social policy and neighborhood-level monitoring.', [
    ['Why is temperature alone an incomplete measure of heat risk?', ['Exposure and harm also depend on housing, resources, work, and health', 'Physical temperature is uniform within every city', 'Tree canopy affects only social vulnerability', 'Indoor conditions cannot differ from outdoor averages'], 0, 'Hazard interacts with capacity to cope.'],
    ['What unintended consequence can neighborhood cooling create?', ['Rising desirability may displace residents intended to benefit', 'Tree maintenance immediately increases traffic heat', 'Watering makes every building less energy efficient', 'Local monitoring eliminates affordability concerns'], 0, 'Environmental improvement can interact with housing markets.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why did the estimate change?', 'Had the comparison cities not experienced a separate recession', ['the policy effect', 'would have appeared', 'considerably smaller', 'than it did'], 'f17-past-counterfactual-comparative'],
  ['What makes the record unusual?', 'Nowhere else in the archive is there', ['a contract', 'in which both parties', 'renegotiate', 'the exchange terms'], 'f17-nowhere-locative-inversion'],
  ['Why was the public file withdrawn?', 'So readily could the rare attributes be linked', ['to outside records', 'that removing names', 'provided', 'little protection'], 'f17-so-adverb-modal-inversion'],
  ['What did the conservator recommend?', 'Rather than having the faded textile exposed continuously', ['she proposed', 'that it rotate', 'with a replica', 'under lower light'], 'f17-rather-than-perfect-gerund-subjunctive'],
  ['How should the finding be interpreted?', 'Whether the motor response is indispensable or merely facilitative', ['remains', 'to be determined', 'by experiments', 'that disrupt it'], 'f17-whether-correlative-subject-clause'],
  ['Why compare multiple performances?', 'Were one transcription treated as definitive', ['variation essential', 'to oral composition', 'would be mistaken', 'for copying error'], 'f17-were-passive-counterfactual'],
  ['When was the contamination discovered?', 'Only upon examining the extraction blanks', ['did the team realize', 'that modern DNA', 'had entered', 'the entire batch'], 'f17-only-upon-gerund-inversion'],
  ['Why was the catalyst redesigned?', 'Strongly though the intermediate bound to the surface', ['it failed', 'to leave enough', 'vacant sites', 'for continued turnover'], 'f17-adverb-though-concessive'],
  ['What limits the geographic inference?', 'The evidence is consistent with trade insofar as', ['the same pigment', 'could have circulated', 'far beyond', 'its production source'], 'f17-insofar-as-modal-perfect'],
  ['Why did the committee postpone release?', 'Such extensive linkage would have been possible that', ['no amount', 'of simple name removal', 'could have rendered', 'the records anonymous'], 'f17-such-that-counterfactual-result'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '현장 관측 결측', 'C1', 420), instruction: '자료 결손의 원인과 해석 위험, 복구·보고 절차를 명확히 제안하세요.', prompt: 'After a storm, you notice that a weather station resumed transmitting but its rainfall channel remained frozen at zero for nine hours. Write to the field-data coordinator. Explain why the zeros may not represent no rain, identify evidence that should be checked, and request a documented correction and flagging procedure.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '대학 연구 데이터 공개', 'C1', 600), instruction: '재현성과 개인정보 보호 사이의 조건을 구체적인 정책 기준으로 평가하세요.', prompt: 'Professor Mbatha: Should universities require researchers to make the data behind every published study publicly downloadable?', passage: 'Hannah: Open data permits error checking and enables new discoveries from existing research.\nOmar: Some datasets contain sensitive information or community knowledge that cannot be safely anonymized.' })

const repeatSentences = ['Welcome to the university biobank retrieval area.', 'Check the request code before opening any freezer rack.', 'Keep insulated gloves on while handling frozen storage boxes.', 'Photograph the occupied slot before removing the requested vial.', 'Verify the vial label against both the manifest and custody form.', 'Place the specimen directly into the monitored transport container.', 'Before leaving, photograph the empty position, update the inventory, and obtain the second staff signature required for custody transfer.']
const interviewQuestions = ['Describe a situation in which sharing information could benefit the public.', 'What harm might occur if the information were released without restrictions?', 'Who should decide whether the benefit justifies the privacy risk?', 'What kind of access system could support research while protecting affected people?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '바이오뱅크 반출', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f17-repeat', scenarioId: 'f17-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '정보 공유와 보호', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f17-interview', scenarioId: 'f17-interview', sequenceIndex })),
]

export const AUTHORED_FORM_17_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_17_IDS = AUTHORED_FORM_17_ITEMS.map((item) => item.id)
