import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f12')

const reading: BaseItem[] = [
  cloze('cloze-nitrogen', '미생물생태학', 'C1', 'Although nitrogen gas is abundant in air, most organisms cannot use it directly. Nitrogen-fixing microbes con___ the gas into ammonia through an energy-intensive enzyme system. Some live freely in soil, while others form sym___ with plants. In legumes, bacteria occupy root nodules and rec___ sugars in exchange for usable nitrogen. Oxygen can dam___ the fixation enzyme, so nodules regulate gas exposure. Adding fertilizer may red___ the plant’s investment in the partnership. Researchers mea___ fixation with isotopes and compare nodulated plants with controls. The association ben___ agriculture but does not eliminate every nutrient limitation. Phosphorus, water, and temperature still aff___ growth. Understanding these interactions helps farmers man___ fertilizer and lim___ nitrogen pollution.', 'vert|bioses|eive|age|uce|sure|efits|ect|age|it'),
  cloze('cloze-tree-rings', '연륜연대학', 'C1', 'Trees in seasonal climates often produce one growth ring each year. Ring width can refl___ moisture, temperature, competition, and tree age. Dendrochronologists match patterns of wide and narrow rings among living trees and old wood. Overlapping sequences ext___ the chronology beyond the life of one tree. A ring count alone can be mis___ if growth stopped temporarily or a partial ring formed. Cross-dating iden___ the exact calendar year of each ring. Wood reused in a building may pre___ construction, so the youngest surviving ring provides context rather than an automatic building date. Researchers stan___ measurements, remove age-related growth trends, and comp___ many trees. Agreement reveals a regional signal, while differences may capt___ local conditions. Carefully dated rings also cal___ radiocarbon ages and rec___ past climate variability.', 'ect|end|leading|tifies|date|dardize|are|ure|ibrate|ord'),
  cloze('cloze-bronze-casting', '금속공예사', 'B2', 'Lost-wax casting creates a metal object from a wax model. The model is enc___ in heat-resistant material, and heating rem___ the wax, leaving a cavity. Molten metal is po___ into that space and solidifies. The surrounding mold is then bro___ away, so each direct wax model usually yields one casting. Artists can use an intermediate mold to rep___ a design. Air channels allow gases to esc___ and reduce defects. Surface marks may rev___ where channels were cut or repairs added. Metallurgical analysis iden___ alloy composition, but it cannot alone determ___ who made the object. Scholars comb___ technical traces with style, workshop debris, and historical records.', 'ased|oves|ured|ken|roduce|ape|eal|tifies|ine|ine'),
  daily('daily-stable-isotope', '분석 실험실', 'C1', 'Stable-isotope samples are accepted in sealed glass vials with a solvent-resistant label. A handwritten code on the cap is not sufficient because caps may be exchanged during preparation. The submission sheet must link each side label to a project-specific sample ID.', ['Why must the sample code appear on the vial body?', ['Caps can become separated from their original samples', 'Glass prevents every label from resisting solvent', 'Project identifiers are assigned after analysis only', 'Submission sheets cannot contain sample links'], 0, 'Body labeling preserves identity through cap handling.']),
  daily('daily-hall-booking', '행사 운영', 'B1', 'Lecture Hall B may be booked until nine, but amplification must end at eight thirty because nearby classrooms have evening examinations. Quiet cleanup may continue afterward. Groups exceeding one hundred attendees need a separate crowd-management plan.', ['What may continue after amplification stops?', ['Non-noisy cleanup within the reservation', 'A loud performance until nine', 'Admission of any crowd without a plan', 'Use of speakers during nearby examinations'], 0, 'The sound restriction precedes the room-booking end.']),
  daily('daily-fossil-cast', '교육 소장품', 'B2', 'Teaching casts may be handled during class, but original fossils marked with a gold dot remain in their trays. A cast can reproduce shape without preserving original material. Students uncertain about a label should ask before lifting the specimen.', ['What does the gold dot indicate?', ['The specimen is original and should remain supported', 'The object is a disposable classroom cast', 'The label may be removed for inspection', 'The fossil can be handled without supervision'], 0, 'The mark distinguishes restricted originals from handling copies.']),
  daily('daily-server-quota', '연구 컴퓨팅', 'B2', 'Project storage above quota becomes read-only after a seven-day warning. Deleting files does not immediately restore write access; the nightly audit must confirm usage below the limit. Users facing an urgent analysis should request temporary space rather than repeatedly retrying writes.', ['Why might writing remain blocked after files are removed?', ['Quota status is recalculated during a scheduled audit', 'Deletion permanently disables the project account', 'Temporary storage is unavailable for analysis', 'Read-only projects cannot be measured for size'], 0, 'Access updates lag until the next audit.']),
  daily('daily-choir-audition', '음악 프로그램', 'B1', 'Choir placement auditions assess vocal range and sight-reading. Students do not need to prepare a solo. Those unable to attend Tuesday may request Wednesday only before the Tuesday schedule is published.', ['What should a student seeking the alternate day do?', ['Request it before the original schedule is released', 'Prepare a solo instead of attending', 'Wait until Tuesday auditions have ended', 'Skip the sight-reading assessment'], 0, 'The alternate date has an advance-request cutoff.']),
  daily('daily-ethics-renewal', '연구 행정', 'C1', 'An annual ethics renewal must report enrollment totals and adverse events even when no procedures changed. If approval expires, data collection must stop; submitting a late renewal does not create retroactive authorization. Analysis of already collected de-identified data may continue only if the original approval permits it.', ['What is the consequence of an approval lapse?', ['New participant data collection must pause', 'A late form retroactively validates all procedures', 'Annual totals no longer need reporting', 'Every analysis of prior data is automatically prohibited'], 0, 'Prospective activity requires current approval.']),
  daily('daily-film-projector', '미디어 장비', 'B2', 'The archive projector accepts preservation copies only under staff supervision. Researchers may operate the viewing projector independently after training. If the viewing copy is damaged, stop playback rather than switching to the preservation copy.', ['What should a trained researcher do after a viewing copy fails?', ['Stop and request staff assistance', 'Load the preservation copy independently', 'Continue playback through visible damage', 'Move the archive projector to another room'], 0, 'Training does not authorize unsupervised preservation-media use.']),
  daily('daily-greenhouse-seed', '온실 연구', 'B2', 'Seeds entering the greenhouse must have a source label and pest declaration. Commercial packets still require the declaration because packaging does not verify storage history. Unlabeled seeds may be kept in sealed quarantine for seven days while documentation is obtained, after which they are discarded.', ['What happens to seeds whose documentation remains missing?', ['They are discarded after the quarantine period', 'They enter the greenhouse because packaging is intact', 'They receive an automatic source label', 'They remain in quarantine indefinitely'], 0, 'The holding period has a fixed endpoint.']),
  daily('daily-archive-pencil', '기록 보관', 'B1', 'Researchers use pencils in the archive reading room. Personal mechanical pencils are allowed if they contain ordinary graphite and have no built-in eraser. Colored leads, ink, and correction tape must remain in lockers.', ['Which writing tool may a researcher bring to the desk?', ['A mechanical pencil with standard graphite', 'A pen containing erasable ink', 'A pencil loaded with colored lead', 'A roll of correction tape'], 0, 'The permitted personal tool meets material restrictions.']),
  daily('daily-waste-pickup', '화학 폐기물', 'B2', 'Waste pickup requests received by Wednesday are normally collected Friday. Containers must remain in secondary containment until staff sign the transfer log. Placing a container in the corridor does not accelerate collection and creates a safety violation.', ['When may a waste container leave laboratory containment?', ['After staff formally accept it on the transfer record', 'Immediately after an online request is submitted', 'Whenever the corridor appears empty', 'Before the scheduled Friday collection'], 0, 'Custody changes only at documented pickup.']),
  ...readingGroup('academic-mediation', '인과방법론', 'C1', 'Mediation analysis asks whether part of a treatment effect operates through an intermediate variable. If a training program improves employment partly by increasing skills, skill gain is a proposed mediator. Simply controlling for post-training skill does not isolate the pathway: skill may share unmeasured causes with employment, and conditioning on it can introduce bias. Strong causal mediation claims require assumptions about both treatment–mediator and mediator–outcome relations. Randomizing treatment solves only the first relation. Researchers conduct sensitivity analyses and distinguish descriptive decomposition from a mechanistic conclusion.', [
    ['Why is adding the mediator to a regression not automatically causal?', ['The mediator and outcome may remain confounded after treatment', 'The mediator necessarily occurs before treatment', 'Randomization measures every intermediate process', 'Employment cannot be represented as an outcome'], 0, 'Post-treatment association needs its own identification assumptions.'],
    ['What does treatment randomization establish most directly?', ['The causal effect of assignment on downstream variables', 'The absence of hidden causes between mediator and outcome', 'The exact proportion transmitted through every pathway', 'That conditioning on skill never introduces bias'], 0, 'Random assignment protects treatment contrasts, not all post-treatment links.'],
    ['Why perform a sensitivity analysis?', ['To examine how conclusions change under possible mediator–outcome confounding', 'To make a descriptive decomposition automatically mechanistic', 'To remove the mediator from the hypothesized pathway', 'To ensure the total effect is always statistically significant'], 0, 'Sensitivity quantifies dependence on unverifiable assumptions.'],
  ]),
  ...readingGroup('academic-dispersal', '상호작용생태학', 'B2', 'Many plants rely on animals to disperse seeds. A fruit-eating bird may carry seeds away from the parent plant, reducing competition and escape from specialized enemies. Yet not every fruit consumer is an effective disperser. Some crush seeds, deposit them in unsuitable habitat, or move them only a short distance. Ecologists measure germination after gut passage, tracking distance, and the quality of deposition sites. A decline in a large-bodied disperser may not be offset by several small species if only the large animal can transport big seeds.', [
    ['Why is fruit consumption not equivalent to successful dispersal?', ['Consumers differ in whether and where they deposit viable seeds', 'All animals carry seeds the same distance', 'Gut passage always destroys germination', 'Parent plants benefit only from nearby deposition'], 0, 'Function depends on seed survival and destination.'],
    ['Why might small dispersers fail to replace a large species?', ['They may be physically unable to handle or transport the largest seeds', 'Small animals always deposit seeds farther away', 'Large fruits contain no viable seeds', 'Several species necessarily perform one identical role'], 0, 'Body size can make ecological functions nonredundant.'],
  ]),
  ...readingGroup('academic-coins', '고고학 경제사', 'C1', 'Coins carry dates, rulers’ names, images, and metal composition, but their archaeological meaning depends on context. A coin minted in one century can circulate or be kept for generations. The latest coin in a sealed deposit provides a terminus post quem: the deposit cannot predate that coin, though it may be considerably later. Hoards may reflect emergency concealment, savings, or ritual deposition. Wear patterns and denomination mixes help evaluate use. Metal analysis can identify debasement or source differences, but cleaning may remove surface evidence and counterfeit coins can imitate official types.', [
    ['What does the newest coin securely establish for a sealed deposit?', ['An earliest possible date rather than the exact burial year', 'The identity of the person who buried it', 'That every coin entered circulation together', 'The ritual purpose of the deposit'], 0, 'The deposit must be no earlier than its newest contained item.'],
    ['Why are wear and denomination patterns examined?', ['They help distinguish circulation history and possible deposit function', 'They guarantee that a hoard was hidden during war', 'They determine metal source without chemical analysis', 'They prove every official-looking coin is genuine'], 0, 'Use traces and composition of the group inform behavioral interpretation.'],
    ['What conservation caution is mentioned?', ['Cleaning can erase evidence located on the surface', 'Metal analysis requires complete destruction of every coin', 'Counterfeits never share official imagery', 'Debasement makes a coin impossible to date'], 0, 'Intervention can remove historically informative traces.'],
  ]),
  ...readingGroup('academic-grammaticalization', '언어변화', 'C1', 'Grammaticalization occurs when a lexical word or construction develops a more grammatical function. A verb meaning “go” may become a future marker, first in contexts where movement and intention overlap. Over time, its pronunciation may reduce and its use may extend beyond literal motion. The process is gradual and can coexist with the original lexical meaning. Similar outcomes in unrelated languages do not prove direct borrowing because common communicative inferences can generate parallel changes. Researchers trace dated texts and conversational variation to reconstruct intermediate stages rather than comparing only endpoints.', [
    ['Why can a movement verb develop future meaning?', ['Contexts of intended movement invite an inference about later action', 'Future markers always begin as nouns for location', 'Pronunciation reduction prevents semantic change', 'The original movement sense must disappear first'], 0, 'Bridging contexts support reinterpretation from intention to futurity.'],
    ['Why are intermediate historical stages important?', ['They show a plausible pathway linking lexical and grammatical uses', 'They establish that parallel change requires borrowing', 'They prove language change occurs instantaneously', 'They eliminate coexistence of old and new meanings'], 0, 'Chronological transitions provide evidence for the proposed development.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you make sure the incubator door latched?', ['I’ll check the seal and indicator light.', 'The door opens toward the corridor.', 'Incubation lasted three days.', 'I made the graph in a spreadsheet.'], 0, 'The seal and light verify closure.'),
  response(1, 'Why was the reading group moved online?', ['The group is discussing a recent novel.', 'The library room is being recarpeted.', 'I moved the paragraph to the conclusion.', 'Online readings use a larger font.'], 1, 'Room maintenance explains the format change.'),
  response(2, 'Have the loan forms been countersigned?', ['The forms describe insurance limits.', 'Counters are located near the entrance.', 'All but the document from the partner museum.', 'I signed into the archive this morning.'], 2, 'The response reports one outstanding form.'),
  response(3, 'Would you mind demonstrating the sample-loading procedure?', ['The sample weighs less than a gram.', 'Loading begins after calibration.', 'Procedures should be documented clearly.', 'Not at all; gather everyone by the instrument.'], 3, 'The reply accepts and organizes the demonstration.'),
  response(4, 'I thought the meal voucher included the reception.', ['It covers lunch only; the reception requires registration.', 'The reception desk holds lost property.', 'Vouchers are printed with a blue border.', 'I included the citation in my essay.'], 0, 'The response clarifies coverage.'),
  response(5, 'Where can I find the revised evacuation route?', ['The route avoids the construction area.', 'On the safety page under Building Updates.', 'I revised the first section yesterday.', 'Evacuation drills occur twice a year.'], 1, 'The answer gives the document location.'),
  response(6, 'Shouldn’t the raters score the essays independently?', ['The essays address environmental policy.', 'Scoring guides reduce inconsistency.', 'Yes, before they discuss any disagreements.', 'I independently verified the citation.'], 2, 'Initial independence prevents mutual influence.'),
  response(7, 'The registration portal lists the wrong supervisor.', ['The supervisor teaches two graduate courses.', 'Registration closes tomorrow afternoon.', 'I listed the equipment by serial number.', 'Contact the department before submitting the final form.'], 3, 'The record should be corrected before submission.'),
  response(8, 'Can the telescope remain outside between observations?', ['Only if the weather cover is secured and staff approve.', 'The telescope tracks stars automatically.', 'Outside observations begin after sunset.', 'I remained in the laboratory until noon.'], 0, 'The response gives conditional permission.'),
  response(9, 'Why did the software omit those survey cases?', ['The survey contains optional questions.', 'A default filter excluded incomplete records.', 'I omitted a repeated phrase from the draft.', 'Software licenses renew annually.'], 1, 'A filtering rule explains the omission.'),
  response(10, 'Could the mediator be affected by an unmeasured cause?', ['The cause is described in the discussion.', 'Mediation occurs through an intermediate variable.', 'Yes, which would weaken the pathway estimate.', 'I measured the sample twice.'], 2, 'Unmeasured mediator–outcome confounding threatens inference.'),
  response(11, 'I can’t tell whether these images use the same exposure.', ['Exposure settings affect brightness.', 'The images show adjacent tissue sections.', 'They were saved in different folders.', 'Read the acquisition metadata instead of judging by appearance.'], 3, 'Metadata offers direct technical evidence.'),
  response(12, 'Is the archive open on the holiday Monday?', ['No, appointments resume Tuesday morning.', 'The archive contains municipal records.', 'Monday is the first day of the workshop.', 'I opened the box with staff present.'], 0, 'The response states closure and reopening.'),
  response(13, 'When should the corrected proof arrive?', ['The proof includes the revised index.', 'Production expects to send it by Thursday.', 'I arrived before the gallery opened.', 'Corrections improve the final version.'], 1, 'The reply gives expected timing.'),
  response(14, 'Would bootstrapping address the skewed uncertainty?', ['The boots are stored beside the field gear.', 'Uncertainty is shown with shaded bands.', 'It may, if the resampling scheme matches the data structure.', 'I addressed the reviewer’s second point.'], 2, 'Bootstrap validity depends on appropriate resampling units.'),
  response(15, 'Who authorized access to the restricted cabinet?', ['The cabinet holds ceremonial objects.', 'Authorization expires at the end of term.', 'Access is recorded in the sign-in log.', 'The collections manager approved the request.'], 3, 'The approving authority is named.'),
  response(16, 'The reference software split one organization into several authors.', ['Correct the item type and reimport its metadata.', 'The organization publishes an annual report.', 'Several authors contributed to the handbook.', 'I split the sample into equal portions.'], 0, 'The metadata type controls author parsing.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-chapter', 'Listen to a Conversation', '논문 작성', 'C1', 'Student: My committee says the literature chapter is too long, but each subsection covers a different theory. Advisor: Length is not the only issue. Several sections summarize studies without showing how they change your research question. Student: Should I delete the older theory? Advisor: Keep what establishes the debate. Combine repetitive study descriptions into a comparison table and use the prose to explain the unresolved assumptions your experiment tests.', [
    ['What weakness does the advisor identify?', ['The review describes sources without connecting them to the thesis problem', 'Every theory in the chapter is historically recent', 'A comparison table cannot contain study details', 'The experiment has no assumptions to examine'], 0, 'Relevance and synthesis, not mere coverage, are missing.'],
    ['What revision is recommended?', ['Compress repeated description and foreground the intellectual gap', 'Remove all older scholarship regardless of relevance', 'Expand each study summary into a separate chapter', 'Replace the research question with a table'], 0, 'Tabular compression creates room for analytical prose.'],
  ]),
  ...listeningGroup('conversation-lock', 'Listen to a Conversation', '연습실', 'B1', 'Student: My practice-room code worked yesterday but not today. Clerk: The room changed from open access to percussion priority this morning. Your ordinary code no longer opens it during the priority block. Student: I left my music stand inside. Clerk: I can retrieve it, but you need to reserve another room for practice.', [
    ['Why did the code stop working?', ['A time-specific access priority took effect', 'The student entered the code incorrectly yesterday', 'The room was permanently removed from the building', 'Music stands deactivate door locks'], 1, 'The authorization changed with the scheduled block.'],
    ['What will the clerk do?', ['Recover the property without restoring practice access', 'Give the student percussion priority', 'Cancel all other room reservations', 'Leave the stand locked inside permanently'], 1, 'Item retrieval and room use are handled separately.'],
  ]),
  ...listeningGroup('conversation-salinity', 'Listen to a Conversation', '해양 실험', 'C1', 'Researcher: The salinity treatments differ, but conductivity was measured at different temperatures. Assistant: Then the raw values are not directly comparable because conductivity changes with temperature. Researcher: The meter has automatic compensation. Assistant: Verify that it was enabled for every run and inspect the reference solution records. If compensation settings changed, recompute from raw conductivity and temperature rather than adjusting values by eye.', [
    ['What threatens comparability among treatments?', ['Temperature and possibly compensation settings varied with measurement', 'Salinity has no relationship to conductivity', 'Reference solutions cannot be recorded', 'Automatic compensation always uses identical settings'], 2, 'The measurement process may be confounded with treatment.'],
    ['What correction does the assistant prefer?', ['A documented recalculation from preserved raw inputs', 'Visual adjustment until treatment means look similar', 'Deletion of every temperature record', 'Assumption that compensation was active'], 2, 'Recomputation is transparent and reproducible.'],
  ]),
  ...listeningGroup('conversation-display', 'Listen to a Conversation', '박물관 조명', 'C1', 'Curator: The new spotlight makes the silver bowl dramatic, but the engraved lines disappear in glare. Designer: The light is nearly aligned with the visitor’s view. Move it sideways and use a broader beam. Curator: Will that make the bowl look flat? Designer: We can add a weaker fill light from the opposite side. First optimize legibility, then test the overall form at several viewing heights.', [
    ['Why are the engravings hard to see?', ['Specular reflection is directed toward the viewer', 'The bowl absorbs all incident light', 'A broad beam is already positioned sideways', 'The object has no engraved surface'], 3, 'Light and viewing angles produce glare.'],
    ['How will the design balance detail and form?', ['Use offset main lighting plus weaker fill and test multiple viewpoints', 'Increase the aligned spotlight without testing', 'Remove all illumination from the opposite side', 'Judge the bowl from one fixed height'], 3, 'Layered lighting can preserve texture and volume.'],
  ]),
  ...listeningGroup('conversation-identifier', 'Listen to a Conversation', '데이터 관리', 'B2', 'Analyst: Two survey waves used the same participant number for different people. Manager: The local number was unique only within each wave. Join on the encrypted master identifier plus wave, not on the visible number alone. Analyst: I already merged part of the file. Manager: Save that version for the audit trail, reverse the join, and report how many rows were affected before continuing.', [
    ['Why did the erroneous merge occur?', ['An identifier was treated as globally unique when it was wave-specific', 'Encrypted identifiers were identical for every participant', 'The analyst used both wave and master fields', 'Survey waves contained no visible numbers'], 0, 'The key lacked the scope needed for uniqueness.'],
    ['Why preserve the incorrect intermediate file?', ['It documents the error and supports a complete impact audit', 'It should replace the corrected dataset', 'It prevents the join from being reversed', 'It removes the need to count affected rows'], 1, 'Auditability requires evidence of what went wrong.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-water', 'Listen to an Announcement', '건물 시설', 'B2', 'Water service in the arts building will stop Thursday from nine to eleven. Restrooms on the first floor will close, but facilities in the connected library remain available. Studios using water-based processes must finish cleanup before nine. Do not store rinse water in open buckets during the outage.', [
    ['Where can building users find an available restroom?', ['In the connected library', 'Inside the closed first-floor area', 'In a studio using open buckets', 'At the water-service valve'], 0, 'The linked building provides the alternative.'],
    ['What must studio users complete before the shutdown?', ['Cleanup requiring running water', 'Storage of rinse water in open containers', 'Every dry artistic process', 'Maintenance on the building pipes'], 0, 'Water-dependent cleanup cannot continue during the outage.'],
  ]),
  ...listeningGroup('announcement-fair', 'Listen to an Announcement', '취업 행사', 'B1', 'The engineering career fair opens to graduate students at ten and all students at eleven. Employers conducting private interviews will use the second-floor rooms; an interview invitation does not allow early entry to the main fair. Bags may be checked free near the entrance.', [
    ['Who may enter the main fair at ten?', ['Graduate students', 'Every undergraduate applicant', 'Anyone with a later private interview', 'Only employers on the second floor'], 1, 'The first hour has a graduate-student restriction.'],
    ['What does an interview invitation not provide?', ['Early access to the general exhibition area', 'Entry to an assigned interview room', 'Use of the free bag-check service', 'Permission to meet an employer'], 1, 'Interview access and fair opening rules are separate.'],
  ]),
  ...listeningGroup('announcement-samples', 'Listen to an Announcement', '현장 연구', 'C1', 'The field station will ship frozen samples Monday. Place boxes in the backup freezer by Sunday noon with the electronic manifest completed. Staff will verify box counts Sunday afternoon. A manifest edit after verification requires a new count; do not add a late sample without notifying the shipping lead.', [
    ['What happens after a verified manifest is changed?', ['Staff must repeat the physical count', 'The electronic record becomes unnecessary', 'Late samples enter without notification', 'Shipment automatically moves to Tuesday'], 2, 'Verification links the listed and physical contents.'],
    ['What should a researcher do with a late sample?', ['Contact the shipping lead before adding it', 'Hide it inside a counted box', 'Delete the entire manifest', 'Place it in an ordinary refrigerator'], 2, 'Unannounced additions break custody and count records.'],
  ]),
  ...listeningGroup('announcement-lecture', 'Listen to an Announcement', '공개 강연', 'B2', 'Tonight’s climate lecture will include unpublished community survey data. The talk remains public, but recording and live streaming are not permitted. The university will post an edited video after participants review the relevant segments. Note-taking for personal study is allowed.', [
    ['What may audience members do during the lecture?', ['Take notes for their own study', 'Broadcast the talk live', 'Record unpublished participant segments', 'Post an unreviewed complete video'], 3, 'Personal notes are allowed despite media restrictions.'],
    ['Why will the official video be delayed?', ['Survey participants must review applicable content', 'The lecture is closed to the public', 'Climate data cannot appear in videos', 'The university has prohibited all editing'], 3, 'Participant review protects unpublished community data.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-tides', 'Listen to an Academic Talk', '해양물리학', 'C1', 'Tides result mainly from the gravitational pull of the Moon and Sun and Earth’s rotation. The Moon pulls more strongly on Earth’s near side than its far side, creating differential forces. Local tidal height, however, is not determined by astronomy alone. Coastline shape, water depth, friction, and resonance can amplify or delay the response. A narrow bay may experience an extreme range while a nearby open coast does not. Tide tables therefore combine harmonic astronomical components with observations specific to each location.', [
    ['Why can neighboring coasts have different tidal ranges?', ['Local basin geometry and resonance modify the astronomical forcing', 'The Moon exerts gravity on only one coastline', 'Earth stops rotating inside narrow bays', 'Water depth has no effect on tidal waves'], 0, 'The same forcing interacts with different coastal systems.'],
    ['Why are local observations used in tide prediction?', ['They calibrate how a particular site responds to recurring forces', 'They replace all knowledge of lunar motion', 'They guarantee weather never affects water level', 'They make coastline geometry identical'], 0, 'Harmonic components need site-specific amplitude and phase.'],
  ]),
  ...listeningGroup('talk-adverse', 'Listen to an Academic Talk', '정보경제학', 'C1', 'Adverse selection arises when one side of a market knows more about product quality or risk before a transaction. If buyers cannot distinguish reliable used cars from defective ones, they offer a price reflecting average quality. Owners of the best cars may withdraw, lowering average quality further. Warranties, inspections, and reputational systems can signal or verify quality, but each has costs. A warranty is informative only if honoring it is more credible or less costly for a high-quality seller than for a low-quality one.', [
    ['Why might high-quality sellers leave the market?', ['An average price fails to compensate them for superior quality', 'Buyers can identify every defect perfectly', 'Inspections force all prices to become equal', 'Defective products receive no offers'], 1, 'Information asymmetry compresses offers below good sellers’ values.'],
    ['When is a warranty a credible quality signal?', ['When poor-quality sellers would find it costly to imitate', 'When no buyer expects it to be honored', 'When every seller faces identical expected repair costs', 'When product quality is already perfectly observed'], 1, 'Differential signaling cost supports separation.'],
  ]),
  ...listeningGroup('talk-pruning', 'Listen to an Academic Talk', '발달신경과학', 'C1', 'Early neural development produces abundant synaptic connections, some of which are later weakened or eliminated. This pruning is activity-dependent: frequently coordinated pathways can be stabilized while less effective connections decline. More synapses are not automatically better, and pruning is not simply destruction. It refines networks in interaction with experience and genetic programs. Human imaging measures broad developmental change but cannot directly count every synapse, so claims linking one behavioral difference to “too much” or “too little” pruning require caution.', [
    ['What functional role can pruning serve?', ['It can refine circuits by selectively stabilizing useful patterns', 'It eliminates every connection formed through experience', 'It guarantees that fewer synapses always reduce ability', 'It operates independently of activity and development'], 2, 'Selective removal helps organize efficient networks.'],
    ['Why are simple behavioral claims about pruning risky?', ['Available human measures are indirect and behavior has many causes', 'Imaging directly counts every synapse in a living brain', 'Genetic programs never influence neural development', 'Pruning ends before any experience occurs'], 2, 'Inference from coarse measurements to mechanism is limited.'],
  ]),
  ...listeningGroup('talk-thermoluminescence', 'Listen to an Academic Talk', '고고연대측정', 'C1', 'Mineral grains accumulate trapped electrons from natural environmental radiation. Heating can release the stored energy as light. In thermoluminescence dating, the light signal estimates radiation received since an object was last strongly heated, as when pottery was fired. The method requires the environmental dose rate and assumes traps were sufficiently emptied at firing. A date refers to the last heating event, which may precede later reuse or burial. Sampling must avoid accidental heating and characterize surrounding sediment.', [
    ['What event does a pottery thermoluminescence age most directly estimate?', ['The last heating that reset trapped-electron energy', 'The date the clay minerals originally formed', 'Every later occasion on which the vessel was used', 'The moment the surrounding sediment was excavated'], 3, 'Firing typically resets the mineral clock.'],
    ['Why is the environmental dose rate needed?', ['Stored energy must be related to the rate at which radiation accumulated', 'It identifies the potter who shaped the vessel', 'It proves later reuse never occurred', 'It prevents all electrons from becoming trapped'], 3, 'Age depends on total dose divided by dose accumulation rate.'],
  ]),
  ...listeningGroup('talk-code-switching', 'Listen to an Academic Talk', '사회언어학', 'C1', 'Bilingual speakers may alternate languages within a conversation, a practice called code-switching. The switch is not random confusion. Grammatical constraints shape where it can occur, and speakers use it to mark quotation, topic, identity, or relationship. Which language is considered neutral depends on setting and community history. Researchers analyze natural interaction as well as controlled tasks, because a laboratory prompt may suppress the social functions that make switching meaningful.', [
    ['Why does the lecturer reject the idea that switching reflects confusion?', ['Switches show systematic grammatical and social patterning', 'Bilingual speakers never alternate inside one conversation', 'Laboratory tasks capture every community meaning', 'One language is universally neutral'], 0, 'Structured constraints and discourse functions indicate competence.'],
    ['Why is natural conversation important to study?', ['Social motivations for switching emerge in real relationships and contexts', 'Controlled tasks contain no grammatical language', 'Natural speakers never respond to laboratory prompts', 'Community history has no effect on language choice'], 2, 'Interactional functions may be absent from artificial elicitation.'],
  ]),
  ...listeningGroup('talk-clouds', 'Listen to an Academic Talk', '대기물리학', 'C1', 'Cloud droplets form when water vapor condenses on aerosol particles. A cloud with many small droplets can reflect more sunlight than one containing fewer large droplets with the same liquid water. Droplet size also affects how readily collisions produce rain. Aerosols therefore can alter cloud brightness and lifetime, but the response depends on humidity, cloud type, and atmospheric motion. Correlations between pollution and bright clouds are not automatically causal because meteorological conditions influence both aerosol concentration and cloud properties.', [
    ['How can added aerosol particles change cloud reflectivity?', ['They can distribute liquid water among more, smaller droplets', 'They eliminate condensation from the atmosphere', 'They make every droplet collide and rain immediately', 'They reduce the number of available condensation sites'], 1, 'More small droplets present greater reflective area.'],
    ['Why is a pollution–brightness correlation difficult to interpret?', ['Weather conditions can affect both variables and create confounding', 'Cloud type never changes aerosol response', 'Humidity is independent of cloud formation', 'Brightness directly measures aerosol causation'], 3, 'Shared meteorological causes can generate the association.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why did controlling for the mediator create concern?', 'Affected as it', ['was by treatment', 'the mediator', 'could not be', 'handled like', 'a baseline variable'], 'f12-affected-as-concession-passive'],
  ['Did the newest coin date the burial exactly?', 'All that could', ['be established', 'was that', 'the deposit', 'was no earlier', 'than the coin'], 'f12-all-fused-relative-passive'],
  ['Why was the large animal functionally important?', 'Only it could', ['transport seeds', 'whose size', 'prevented smaller', 'species from', 'swallowing them'], 'f12-only-subject-relative-prevent'],
  ['Could the grammatical marker have been borrowed?', 'Whether it developed', ['internally or', 'entered through contact', 'cannot be decided', 'from the', 'modern form alone'], 'f12-whether-coordinate-passive'],
  ['What weakened the pathway claim?', 'Had mediator and', ['outcome shared', 'an omitted cause', 'the apparent', 'indirect effect', 'would be biased'], 'f12-inverted-third-conditional'],
  ['Why retain the surface deposits?', 'To remove them', ['without analysis', 'would risk', 'destroying evidence', 'that could', 'not be replaced'], 'f12-infinitive-subject-relative-modal'],
  ['Did the sequence reflect one universal change?', 'Rather than occurring', ['simultaneously the shift', 'appeared first', 'in a subset', 'of frequently', 'used forms'], 'f12-rather-than-gerund-participial'],
  ['How was the interpretation strengthened?', 'Not by chemistry', ['alone but', 'by its agreement', 'with production', 'debris and', 'settlement routes'], 'f12-not-by-but-by'],
  ['Why did the authors avoid a mechanistic label?', 'So demanding are', ['the identification', 'assumptions that', 'a descriptive', 'decomposition was', 'more defensible'], 'f12-so-adjective-inversion'],
  ['Should every missing observation be imputed?', 'Under no circumstances', ['should values', 'be invented', 'without examining', 'why they', 'are absent'], 'f12-under-no-circumstances-inversion-passive'],
]
const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '표본 추적', 'B2', 420), instruction: '문제와 위험, 필요한 확인 절차를 구체적으로 작성하세요.', prompt: 'You notice that several sample caps and vial labels use different codes after preparation. Write to the laboratory supervisor. Describe the discrepancy, explain why guessing the match would compromise the study, and request quarantine, record checking, and a prevention step for future handling.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '공동자원 관리', 'C1', 600), instruction: '제시된 관점을 평가하고 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Ndlovu: Are local communities generally better than national governments at managing shared resources such as forests, fisheries, and water?', passage: 'Camila: Local users have detailed knowledge and can monitor rule breaking at lower cost.\nIsaac: Local power inequalities may exclude vulnerable users, so broader legal oversight remains necessary.' })

const repeatSentences = ['Welcome to the campus instrument-loan center.', 'Inspect every item before signing the checkout form.', 'Keep protective caps on sensors during transportation.', 'Use only the chargers assigned to the numbered equipment case.', 'Report a damaged cable before connecting it to an outlet.', 'Return memory cards separately if they contain restricted data.', 'At check-in, wait while staff verify the inventory, review battery condition, and close the electronic loan record.']
const interviewQuestions = ['Describe a resource that many people share in your community.', 'What behavior could damage or exhaust that resource?', 'Should users make their own rules, or should an outside authority regulate them?', 'How can a management system remain fair to people with less power?']
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '장비 대여 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f12-repeat', scenarioId: 'f12-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '공동자원과 규칙', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f12-interview', scenarioId: 'f12-interview', sequenceIndex })),
]

export const AUTHORED_FORM_12_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_12_IDS = AUTHORED_FORM_12_ITEMS.map((item) => item.id)
