import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f09')

const reading: BaseItem[] = [
  cloze('cloze-acidification', '해양화학', 'C1', 'The ocean absorbs a substantial share of carbon dioxide released by human activity. Dissolved carbon dioxide rea___ with water and forms carbonic acid, which rel___ hydrogen ions. As acidity increases, carbonate ions become less ava___ to organisms building calcium-carbonate shells or skeletons. The response var___ among species and life stages. Some organisms reg___ internal chemistry, while others grow more slowly or form weaker structures. Laboratory studies can iso___ acidity, but natural ecosystems also experience warming, oxygen loss, and food changes. Field observations and long experiments help rev___ combined effects. Reducing local pollution may improve resilience, yet it does not rem___ the global chemical driver. Researchers therefore mon___ biological responses alongside seawater chemistry and exp___ uncertainty in regional forecasts.', 'cts|eases|ilable|ies|ulate|late|eal|ove|itor|licitly'),
  cloze('cloze-domestication', '진화고고학', 'C1', 'Domestication is a prolonged evolutionary relationship rather than a single invention. Humans sel___ plants or animals with useful traits, intentionally or through repeated management. In crops, nonshattering seeds may have acc___ because they were easier to harvest, even before farmers understood inheritance. Archaeologists tra___ changes in seed shape, animal size, and settlement patterns. No one trait alone estab___ domestication, since climate and local ecology can produce similar variation. Genetic evidence can iden___ ancestral populations but is shaped by later mixing. Researchers comp___ specimens across time and regions to recon___ pathways that may differ. The process often invol___ both human choice and unintended selection. Recognizing this complexity prev___ a simple divide between wild and domestic and emph___ gradual change.', 'ected|umulated|ck|lishes|tify|are|struct|ved|ents|asizes'),
  cloze('cloze-reconsolidation', '기억신경과학', 'C1', 'Retrieving a memory can make it temporarily open to modification before it stabilizes again. This proposed reconsolidation process may upd___ old information with new experience. In experiments, a reminder is followed by interference or learning, and later recall is comp___ with a control condition. Timing matters because the memory must be act___ but not simply extinguished through repeated exposure. Results vary with memory age, strength, and emotional salience. A changed report does not nec___ mean the stored memory trace was rewritten; response strategy may have shi___. Researchers use physiological and neural measures to stren___ inference. Clinical applications remain prom___ but uncertain, because laboratory tasks differ from complex personal memories. Ethical concerns also ar___ when deliberately altering distressing recollections. Careful replication is req___ before broad treatment claims are acc___.', 'ate|ared|ivated|essarily|fted|gthen|ising|ise|uired|epted'),
  daily('daily-autoclave', '실험실 안전', 'B2', 'Autoclave reservations include heating and cooling time. Users must not open the chamber merely because the programmed cycle has ended; the pressure gauge must read zero and liquid loads must cool for the additional period shown on the posted chart.', ['What determines when a liquid load may be removed?', ['Both zero pressure and completion of the specified cooling interval', 'The end of the programmed heating cycle alone', 'Whether another user is waiting for the chamber', 'A temperature estimate made without reading the chart'], 0, 'Cycle completion does not by itself establish safe pressure and temperature.']),
  daily('daily-portfolio', '디자인 수업', 'B1', 'Final portfolios may include collaborative work if each project identifies the student’s individual contribution. A group credit line without role descriptions is insufficient. Drafts shown only in class do not require teammate permission, but public online portfolios do.', ['What must accompany collaborative work in a public portfolio?', ['A description of the student’s role and permission for public use', 'Only a general list of all group members', 'No explanation if the draft appeared in class', 'A claim that the student completed every task alone'], 0, 'Public display requires attribution of contribution plus consent.']),
  daily('daily-nmr', '분석 장비', 'C1', 'NMR users may queue samples overnight only when the sequence includes a verified solvent and temperature for every tube. The instrument manager reviews unusual temperatures before the run. A queue containing an unreviewed setting will pause before that sample, delaying every item behind it.', ['How can a user avoid blocking the overnight queue?', ['Obtain advance review for any nonstandard temperature setting', 'Leave solvent information blank until morning', 'Place the unusual sample first without notifying anyone', 'Assume later samples will bypass a paused sequence'], 0, 'A verified configuration prevents automatic stoppage.']),
  daily('daily-residence-inspection', '기숙사 관리', 'B2', 'Annual room inspections check smoke detectors, blocked exits, and prohibited heating devices. Residents need not be present if staff can enter with the housing key. Anyone requesting a specific time for accessibility or medical reasons must submit the accommodation form by Tuesday.', ['Who needs to complete the advance scheduling form?', ['A resident requiring a time-related accommodation', 'Every resident who will be absent during inspection', 'Only someone storing an approved heating device', 'A resident whose smoke detector works normally'], 0, 'Ordinary absence is allowed; special timing requires documented arrangement.']),
  daily('daily-repository-license', '연구 데이터', 'C1', 'Choosing an open license for a dataset does not override restrictions in participant consent or third-party agreements. Before deposit, remove fields that cannot be shared and document any files withheld. The repository can display a metadata record even when access to the underlying data must be reviewed case by case.', ['What can the repository provide when open file access is inappropriate?', ['A public description with controlled review of data requests', 'Automatic cancellation of participant restrictions', 'An open license that supersedes external ownership', 'Unedited files with prohibited fields left visible'], 0, 'Discoverability and unrestricted download can be separated.']),
  daily('daily-farmers-market', '지역 행사', 'B1', 'Vendors at the campus farmers’ market must label foods requiring refrigeration and keep them below the posted temperature. Ice alone is acceptable only when a thermometer remains inside the container. Market staff may suspend sales until a missing temperature record is restored.', ['What must accompany food cooled with ice?', ['A thermometer that verifies storage temperature', 'A label stating that refrigeration is unnecessary', 'Permission to sell without any temperature record', 'A second container kept at room temperature'], 0, 'Cooling method must be monitored, not merely assumed effective.']),
  daily('daily-museum-case', '전시 시설', 'B2', 'Only collections staff may open display cases. In an urgent situation involving visible water, security should close the gallery and call the emergency collections number rather than moving an object. The case microclimate may still protect the object until trained staff arrive.', ['What should security do after noticing water near a display case?', ['Restrict access and contact the collections emergency team', 'Open the case immediately to inspect the object', 'Move the object to a public hallway', 'Turn off the case monitor and reopen the gallery'], 0, 'Containment and specialist response take priority over unauthorized handling.']),
  daily('daily-interview-room', '미디어 시설', 'B2', 'The sound-treated interview room includes fixed cameras but no operator. Users should reserve setup time before the participant arrives. A thirty-minute booking that starts at the interview time does not include equipment checks, and later reservations cannot be displaced if setup runs long.', ['Why should a researcher reserve extra time before an interview?', ['To test unattended recording equipment without shortening the session', 'To obtain an operator included with every room booking', 'To extend automatically into the next reservation', 'To avoid checking the cameras before participants arrive'], 0, 'Setup belongs within the user’s reserved block.']),
  daily('daily-lab-coat', '세탁 서비스', 'B1', 'Laboratory coats placed in the Tuesday collection bin return the following Monday. Coats contaminated with biological or chemical material must stay in the laboratory’s hazardous-laundry container and require a separate pickup request. Do not mark contamination by placing a note in an ordinary pocket.', ['Which coat needs a separate collection request?', ['One exposed to hazardous laboratory material', 'One placed in the ordinary Tuesday bin', 'One needed again the following Monday', 'One labeled with the owner’s department'], 0, 'Contaminated garments use a controlled handling route.']),
  daily('daily-tree-work', '캠퍼스 시설', 'B2', 'The east courtyard closes Thursday while arborists remove a damaged branch. Buildings remain accessible from their north entrances. Bicycle racks inside the courtyard must be cleared Wednesday night; locked bicycles left there may be moved by security to the temporary rack beside the theater.', ['What should a cyclist do before Thursday’s work?', ['Remove the bicycle from the courtyard racks', 'Use only the east building entrances', 'Ask arborists to protect a bicycle in place', 'Leave the bicycle locked for permanent storage'], 0, 'The work zone must be cleared in advance.']),
  ...readingGroup('academic-synthetic', '정책평가', 'C1', 'The synthetic-control method estimates what might have happened to one treated unit by constructing a weighted combination of untreated units. If a city adopts a unique policy, several other cities can be weighted so their pre-policy outcomes and predictors resemble the treated city. Post-policy divergence then suggests an effect, provided no other event uniquely affected the treated city and comparison units were not influenced by the policy. A close pre-treatment fit is important, but researchers also run placebo analyses: they pretend each untreated unit was treated and compare the resulting gaps. If many placebo gaps are as large as the actual one, the apparent effect is less unusual.', [
    ['Why are several untreated units assigned weights?', ['To construct a comparison trajectory resembling the treated unit before policy', 'To ensure every city receives the policy simultaneously', 'To eliminate all predictor differences after treatment', 'To make the treated city part of the control pool'], 0, 'Weighted donors approximate the missing counterfactual.'],
    ['What would violate the no-interference requirement?', ['The policy changes outcomes in cities used to build the comparison', 'The treated city has a measurable pre-policy outcome', 'Weights differ among untreated units', 'Researchers observe the outcome after implementation'], 0, 'Contaminated donor units no longer represent untreated alternatives.'],
    ['How do placebo analyses help interpret the estimated gap?', ['They show whether similarly large divergences arise without actual treatment', 'They guarantee that the treated city experienced no other event', 'They replace the need for pre-policy fit', 'They force every comparison unit to receive equal weight'], 0, 'The distribution of false assignments supplies a reference for unusualness.'],
  ]),
  ...readingGroup('academic-xylem', '식물생리학', 'C1', 'Water rises through xylem largely because evaporation from leaves creates tension in a continuous column of water. This mechanism can move water without a mechanical pump, but it makes the column vulnerable to cavitation: air bubbles can interrupt transport. Narrow conduits often resist cavitation better, whereas wider conduits can move more water efficiently. Plants therefore face a safety–efficiency trade-off. Drought increases tension and embolism risk, and species differ in whether they repair blocked conduits or produce new ones. Measurements made on cut branches can introduce air, so sampling technique influences apparent vulnerability.', [
    ['What trade-off is associated with xylem conduit width?', ['Greater transport capacity may come with higher cavitation vulnerability', 'Narrow vessels always move more water than wide ones', 'Efficient conduits eliminate evaporation from leaves', 'Cavitation makes water columns mechanically stronger'], 0, 'Width improves flow but can reduce hydraulic safety.'],
    ['Why can cutting a branch bias an experiment?', ['The procedure itself may introduce the air blockage being measured', 'Detached branches immediately produce new conduits', 'Cutting removes every difference among species', 'Sampling lowers water tension to exactly zero'], 0, 'A measurement artifact can mimic natural embolism.'],
  ]),
  ...readingGroup('academic-epigraphy', '고대사', 'C1', 'Epigraphers study texts carved or painted on durable surfaces. An inscription’s wording matters, but so do letter forms, material, placement, and evidence of reuse. A ruler’s decree displayed in a central square addressed a different audience from the same words hidden in a tomb. Damaged passages are reconstructed by comparing formulaic expressions and surviving strokes. Editorial conventions distinguish visible letters from uncertain restorations, because a plausible completion is not an observation. Inscriptions often present official self-images rather than neutral reports, so historians compare them with archaeological and documentary evidence.', [
    ['Why does the physical location of an inscription matter?', ['It helps identify the intended audience and social function', 'It determines the exact pronunciation of every letter', 'It makes damaged text fully visible', 'It proves that the wording was privately composed'], 0, 'Placement is part of the communicative context.'],
    ['What is the purpose of marking restored letters editorially?', ['To separate inferred text from surviving evidence', 'To hide formulaic parallels from readers', 'To claim that every gap has only one solution', 'To replace all damaged surfaces with modern stone'], 0, 'Transparent notation preserves the boundary between observation and reconstruction.'],
    ['Why should official inscriptions be compared with other evidence?', ['Their claims may serve political representation rather than impartial description', 'Durable materials cannot preserve historical language', 'Archaeological data always repeat the same official account', 'A public decree has no intended audience'], 0, 'Institutional authors have motives that shape presentation.'],
  ]),
  ...readingGroup('academic-radio', '전파천문학', 'C1', 'Radio telescopes collect weak electromagnetic signals with dish antennas or arrays. An interferometric array combines observations from separated antennas to achieve resolution related to the distance between them, called the baseline. It does not collect as much light as one filled dish the size of the entire array. Earth’s rotation changes the projected baselines and improves sampling, but missing spatial frequencies can make extended emission difficult to reconstruct. Calibration uses known sources to correct atmospheric and instrumental effects. Images are therefore model-based reconstructions from incomplete measurements, not direct photographs.', [
    ['What benefit comes from widely separated antennas?', ['They can resolve finer angular detail through long baselines', 'They form a completely filled collecting surface', 'They eliminate the need for calibration sources', 'They measure every spatial frequency at once'], 0, 'Maximum separation governs potential resolving power.'],
    ['Why might an array miss broad, diffuse emission?', ['Its sampled baselines may lack the spatial information needed for large structures', 'Earth’s rotation removes all signal from compact sources', 'Calibration converts radio waves into visible photographs', 'One antenna always blocks every other antenna'], 0, 'Incomplete short-spacing coverage can filter extended structure.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you confirm that the meeting is still in Room 214?', ['I’ll check the updated booking page.', 'The meeting lasted forty minutes.', 'Room 214 has movable tables.', 'I confirmed the shipment yesterday.'], 0, 'The booking record can confirm the venue.'),
  response(1, 'Why did the manuscript return without review?', ['The manuscript contains three figures.', 'It did not follow the journal’s scope.', 'I reviewed the abstract this morning.', 'The return address is on the envelope.'], 1, 'A scope rejection explains the editorial return.'),
  response(2, 'Have the replacement batteries been charged?', ['The batteries fit two recorder models.', 'Charging takes about three hours.', 'All but the one with a damaged connector.', 'I replaced the labels on the storage box.'], 2, 'The reply gives status plus an exception.'),
  response(3, 'Would you be able to lead the software demonstration?', ['The software requires a recent browser.', 'The demonstration begins after lunch.', 'Leadership can be learned through practice.', 'Yes, if I can test the projector beforehand.'], 3, 'The conditional acceptance is directly relevant.'),
  response(4, 'I thought the museum pass covered the special exhibition.', ['It covers general admission, but that gallery needs a timed ticket.', 'The exhibition displays early photographs.', 'Museum passes expire at the end of the year.', 'I covered the table with protective paper.'], 0, 'The response clarifies the pass limitation.'),
  response(5, 'Where should we meet the visiting field guide?', ['The guide includes maps of local trails.', 'Beside the reserve office at the south gate.', 'I visited the field station last summer.', 'Meeting notes are stored in the shared folder.'], 1, 'The answer supplies the requested meeting point.'),
  response(6, 'Shouldn’t the figure legend define every abbreviation?', ['The figure compares the three treatment groups.', 'Abbreviations save space in a table.', 'Yes, even those already used in the main text.', 'I defined the sampling area on the map.'], 2, 'Figures should be interpretable on their own.'),
  response(7, 'The accessibility captions are out of sync with the video.', ['The video introduces the course instructors.', 'Captions can include descriptions of sound.', 'Synchronization is measured in seconds.', 'Pause publication and send the timing file back for correction.'], 3, 'The issue should be fixed before release.'),
  response(8, 'Can I extend this equipment loan through the break?', ['Only if your supervisor confirms the project remains active.', 'The equipment weighs nearly twelve kilograms.', 'Break periods are listed on the academic calendar.', 'I extended the graph to include last year.'], 0, 'The reply states the approval condition.'),
  response(9, 'Why are the survey responses missing timestamps?', ['The timestamps usually appear in the first column.', 'Anonymous mode was configured to suppress metadata.', 'I responded to the survey yesterday.', 'Missing data should be documented.'], 1, 'A privacy setting explains the absent field.'),
  response(10, 'Could the result be driven by one unusually large site?', ['The site occupies twelve hectares.', 'Large results require careful explanation.', 'It could, so we should repeat the model without that site.', 'I drove past the field station this morning.'], 2, 'A leave-one-out check tests the concern.'),
  response(11, 'I can’t determine which version the authors analyzed.', ['The authors published in several journals.', 'Analysis can reveal a hidden pattern.', 'Versions are numbered in the file history.', 'Compare the reported checksum with the archived files.'], 3, 'A checksum provides exact version evidence.'),
  response(12, 'Is the rehearsal open to visitors?', ['No, but the final run-through will be streamed publicly.', 'Visitors should wear badges in the laboratory.', 'The rehearsal schedule changed twice.', 'I opened the score at the marked page.'], 0, 'The reply distinguishes closed rehearsal from public access.'),
  response(13, 'When will the repaired microscopes be returned?', ['The microscopes use LED illumination.', 'Facilities expects delivery on Friday afternoon.', 'I returned the library book this morning.', 'Repairs are covered by the service contract.'], 1, 'The answer supplies a delivery estimate.'),
  response(14, 'Would centering the predictor change the fitted relationship?', ['The predictor appears in two model terms.', 'The center is located near the station.', 'Not the fitted values, though it can change coefficient interpretation.', 'Relationships develop through repeated interaction.'], 2, 'Centering may reparameterize without changing fit.'),
  response(15, 'Who approved destroying the duplicate samples?', ['Duplicate samples improve quality control.', 'The approval form is stored digitally.', 'Destruction requires a witnessed inventory.', 'The laboratory director signed the disposal record.'], 3, 'The responsible authority is identified.'),
  response(16, 'The export replaced accented characters with symbols.', ['Choose UTF-8 encoding and compare a small test export first.', 'The symbols indicate categories in the codebook.', 'Accented speech patterns vary by region.', 'I replaced the missing cable yesterday.'], 0, 'Correct encoding and a test prevent repeated corruption.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-weather', 'Listen to a Conversation', '현장 수업', 'B2', 'Student: The forecast shows rain, but the field trip page still says “confirmed.” Instructor: Confirmation means the bus and permit are ready, not that weather cannot change the plan. I will make a final safety decision at six tomorrow morning. Student: Should I bring the sampling equipment to campus? Instructor: Bring waterproof clothing, but leave the electronic meter in the laboratory until you receive the message. We have a manual backup kit on the bus.', [
    ['What does “confirmed” mean in this situation?', ['Logistical arrangements are in place, while weather approval remains pending', 'Students must use electronic instruments in the rain', 'The instructor has guaranteed safe weather', 'The field permit has been canceled'], 0, 'Administrative readiness and final go/no-go status differ.'],
    ['Why should the electronic meter remain in the laboratory?', ['The team can avoid exposing it before the safety decision and use a backup', 'The instrument is prohibited on every field trip', 'Waterproof clothing interferes with its readings', 'The bus has no space for scientific equipment'], 0, 'A manual kit preserves capability without risking sensitive equipment.'],
  ]),
  ...listeningGroup('conversation-plagiarism', 'Listen to a Conversation', '학술 글쓰기', 'B2', 'Student: The similarity report flags my methods section, but the wording describes a standard protocol. Tutor: Some overlap is expected for fixed technical phrases. Check whether you copied longer explanatory sentences from the source. Student: Should I replace every technical term? Tutor: No. Cite the protocol, keep necessary terminology, and rewrite the explanation in a way that reflects what your study actually did.', [
    ['Why does the tutor not treat every match as misconduct?', ['Standard technical language can legitimately recur', 'Similarity software verifies authorship perfectly', 'Methods sections never require citations', 'Long copied explanations are always acceptable'], 1, 'Fixed terminology differs from uncredited extended wording.'],
    ['What revision strategy is recommended?', ['Retain essential terms while independently explaining and citing the procedure', 'Substitute inaccurate synonyms for all scientific terms', 'Delete the methods section from the paper', 'Ignore extended matches because the protocol is common'], 1, 'Accurate terminology, original explanation, and attribution can coexist.'],
  ]),
  ...listeningGroup('conversation-replicates', 'Listen to a Conversation', '분자 실험', 'C1', 'Researcher: Three wells show the expected response, but they came from the same cell preparation. Assistant: Then they are technical replicates, not three independent biological samples. Averaging them can estimate measurement precision, but it does not triple our biological sample size. Researcher: The second preparation failed quality control. Assistant: Report the first result as preliminary and repeat the experiment. Do not calculate significance as though there were three independent preparations.', [
    ['What is the problem with counting the wells as three samples?', ['They share the same biological source and do not represent independent variation', 'Technical replicates cannot reveal measurement consistency', 'Every well received a different cell population', 'Averaging always creates additional biological material'], 2, 'Repeated measurement of one preparation is pseudoreplication.'],
    ['How should the current finding be presented?', ['As tentative evidence awaiting independent biological replication', 'As a definitive test with a sample size of three', 'Without mentioning the failed preparation', 'As proof that quality control is unnecessary'], 2, 'Only one qualifying biological preparation supports the pattern.'],
  ]),
  ...listeningGroup('conversation-loan', 'Listen to a Conversation', '박물관 대여', 'C1', 'Curator: The borrowing museum wants to extend the sculpture loan by six months. Registrar: Our insurance certificate ends in July, and the condition report covers the original display case only. Curator: They plan to move it into a larger gallery. Registrar: Then we need a new facility report, case specifications, light levels, and an updated insurance certificate before the director considers an extension.', [
    ['Why is the existing documentation insufficient?', ['The proposed duration and display environment differ from the approved conditions', 'The sculpture is no longer owned by the lending museum', 'A larger gallery never requires insurance', 'The original condition report permanently authorizes any venue'], 3, 'Material changes require new risk review.'],
    ['What will happen before an extension decision?', ['The borrower must document the new environment and coverage', 'The sculpture will move before specifications are reviewed', 'The registrar will cancel the original ownership record', 'The director will approve without consulting conditions'], 3, 'Updated evidence precedes authorization.'],
  ]),
  ...listeningGroup('conversation-map-license', 'Listen to a Conversation', '공공 데이터', 'B2', 'Student: I used the city’s open map in our commercial prototype, but the app store rejected our attribution page. Librarian: The license still requires credit. Put a short attribution in the app and link to a full notice on your website. Student: Could I remove the city logo? Librarian: The license requests source text, not necessarily the logo. Do not imply that the city endorses your product.', [
    ['What problem must the student solve?', ['Provide required source credit in a format compatible with the app', 'Obtain city endorsement for the commercial product', 'Replace the open map with an unlicensed copy', 'Display the city logo on every screen'], 0, 'Attribution is mandatory even if one presentation format failed.'],
    ['What distinction does the librarian make?', ['Crediting a source does not mean claiming its endorsement', 'A logo is always the only valid attribution', 'Commercial use removes all license duties', 'Website notices cannot supplement in-app credit'], 1, 'Source acknowledgment and institutional approval are separate.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-power', 'Listen to an Announcement', '연구 시설', 'B2', 'The west laboratory wing will lose ordinary power Tuesday from eight to ten while a panel is replaced. Emergency outlets remain active but must be reserved for freezers, incubators, and active safety systems. Do not plug computers or chargers into them. Experiments requiring ventilation should not begin unless they can finish before eight.', [
    ['Which device may remain on an emergency outlet?', ['An incubator holding temperature-sensitive cultures', 'A laptop used for ordinary data entry', 'A personal phone charger', 'A projector prepared for a seminar'], 0, 'Protected power is restricted to critical equipment and safety.'],
    ['What should happen to ventilation-dependent experiments?', ['They should be scheduled to finish before the outage or delayed', 'They may start at eight using an ordinary outlet', 'They should continue without active ventilation', 'They take priority over freezer power'], 0, 'The outage removes required infrastructure.'],
  ]),
  ...listeningGroup('announcement-auditions', 'Listen to an Announcement', '음악 동아리', 'B1', 'Orchestra auditions begin next week. Submit one continuous recording containing both excerpts; edited compilations will not be reviewed. The camera may show only the performer’s hands and instrument, but the student identification card must appear briefly at the beginning. Audio-only files are accepted for wind instruments but not for percussion.', [
    ['What must every submitted recording include at its start?', ['A brief view of the student identification card', 'A separate edited introduction for each excerpt', 'A full view of the performer’s face throughout', 'An audio-only test for percussion applicants'], 1, 'Identity verification is required across submissions.'],
    ['Which applicant may submit audio without video?', ['A performer auditioning on a wind instrument', 'A percussionist demonstrating hand technique', 'Anyone combining separately edited excerpts', 'A student omitting identification'], 1, 'The stated format exception applies to winds.'],
  ]),
  ...listeningGroup('announcement-trail', 'Listen to an Announcement', '환경 안전', 'B2', 'The riverside trail remains open north of the footbridge, but the southern boardwalk is closed after flooding displaced several supports. Barriers mark the closure. Researchers with sampling permits are not exempt and should use the upstream access point. Report damaged barriers; do not cross them to inspect the boardwalk.', [
    ['Who must obey the southern closure?', ['Permit holders as well as ordinary trail users', 'Only visitors without research equipment', 'Workers assigned to repair the supports', 'People approaching from the upstream access point'], 2, 'The announcement explicitly removes a permit-based exception.'],
    ['How should a user respond to a damaged barrier?', ['Notify staff without entering the closed section', 'Cross it to evaluate structural supports personally', 'Move it to make an opening for researchers', 'Ignore it because the northern trail is open'], 2, 'Reporting preserves safety without unauthorized inspection.'],
  ]),
  ...listeningGroup('announcement-catering', 'Listen to an Announcement', '행사 운영', 'B2', 'Conference catering numbers become final at noon Friday. Registrants may change dietary selections until then. After the deadline, organizers can still remove a meal for someone who cancels, but they cannot guarantee a newly requested specialty meal. Unclaimed meals will be donated after the lunch service rather than held for the evening.', [
    ['What change is still guaranteed before Friday noon?', ['A revision to the registrant’s dietary selection', 'A specialty meal requested after the count is final', 'Storage of an unclaimed lunch for evening pickup', 'Automatic transfer of a canceled meal to another diet'], 3, 'Selections remain editable until the final count.'],
    ['What happens to meals left after lunch?', ['They are transferred for donation', 'They remain reserved until the evening', 'They are used to expand new specialty orders', 'They are returned to individual registrants'], 3, 'The disposal plan is donation after service.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-paleomagnetism', 'Listen to an Academic Talk', '지구과학', 'C1', 'When some volcanic rocks cool, magnetic minerals align with Earth’s field and lock in a remanent magnetization. Because magnetic polarity has reversed many times, sequences of normal and reversed rock can be matched to a dated polarity time scale. Ocean-floor stripes symmetric around mid-ocean ridges provided powerful evidence for seafloor spreading. Alteration or reheating can reset a rock’s magnetic signal, so geologists test mineral stability and compare multiple samples before interpreting age or plate position.', [
    ['How do magnetic reversals help date rock sequences?', ['Their polarity pattern can be aligned with an independently calibrated chronology', 'Every rock records only the current magnetic field', 'Normal polarity always indicates one exact mineral', 'Reversal removes all remanent magnetization'], 0, 'A sequence of polarity intervals acts as a temporal pattern.'],
    ['Why must researchers check for alteration?', ['Later processes may overwrite the original field record', 'Mineral stability prevents any magnetic measurement', 'Symmetric ocean stripes form only after laboratory heating', 'Plate position is unrelated to magnetization'], 0, 'A secondary magnetic signal could be misread as primary.'],
  ]),
  ...listeningGroup('talk-externality', 'Listen to an Academic Talk', '환경경제학', 'C1', 'An externality occurs when an activity affects people who are not fully represented in the decision-maker’s private costs or benefits. A factory may consider fuel and labor but not health damage from pollution. A tax equal to marginal external damage can align private incentives with social cost in theory. In practice, damage is uncertain, varies by location, and may fall unequally across communities. Regulation therefore involves measurement, distribution, and enforcement, not merely selecting one price.', [
    ['Why may an unregulated factory produce too much pollution?', ['Some harm is excluded from the costs guiding its decision', 'Every health effect appears in the fuel price', 'Private and social costs are necessarily equal', 'Labor expenses rise with cleaner air'], 1, 'Unpriced third-party damage weakens the incentive to reduce emissions.'],
    ['What complicates setting a corrective tax?', ['Marginal harm is difficult to estimate and unevenly distributed', 'External damage never varies geographically', 'Enforcement is automatic after naming a price', 'A tax eliminates all distributional concerns'], 1, 'Real-world damages and burdens are heterogeneous and uncertain.'],
  ]),
  ...listeningGroup('talk-tolerance', 'Listen to an Academic Talk', '면역생물학', 'C1', 'The immune system must react to pathogens while avoiding destructive responses to the body’s own molecules. During development, many strongly self-reactive lymphocytes are removed or inactivated, a process called central tolerance. Some escape, so peripheral mechanisms suppress or regulate them in tissues. Tolerance is not simple inactivity: immune cells integrate signals about molecular recognition, inflammation, and location. Failure can contribute to autoimmune disease, whereas excessive suppression can impair responses to infection or tumors.', [
    ['Why are peripheral tolerance mechanisms necessary?', ['Some self-reactive cells remain after developmental screening', 'Central tolerance removes every lymphocyte in the body', 'Inflammation always prevents molecular recognition', 'Tumors require complete immune inactivity'], 2, 'Initial screening is incomplete and needs later control.'],
    ['What trade-off does immune regulation face?', ['Limiting self-damage without blocking useful defense', 'Maximizing suppression under every condition', 'Recognizing only molecules found in pathogens', 'Eliminating all variation among tissues'], 2, 'Too little regulation risks autoimmunity; too much weakens protection.'],
  ]),
  ...listeningGroup('talk-color', 'Listen to an Academic Talk', '시각과학', 'B2', 'Color constancy allows an object to appear roughly the same color under different illumination. The light reaching the eye depends on both the object’s reflectance and the spectrum of the light source. The visual system uses surrounding surfaces, shadows, and assumptions about illumination to estimate reflectance. These corrections are useful but not perfect. Carefully designed displays can create color illusions because the same physical patch is interpreted under different inferred lighting.', [
    ['Why is the retinal signal alone ambiguous?', ['It combines properties of the surface with properties of illumination', 'Reflectance changes into a shadow before reaching the eye', 'Every light source has an identical spectrum', 'Surrounding surfaces never affect interpretation'], 3, 'The observed spectrum has two contributing causes.'],
    ['How can identical patches appear different?', ['Context leads the visual system to infer different lighting conditions', 'Their measured light is physically unrelated', 'Color constancy prevents all visual illusions', 'The eye receives no light from either patch'], 3, 'Perceptual correction depends on the scene model.'],
  ]),
  ...listeningGroup('talk-seriation', 'Listen to an Academic Talk', '고고학 방법론', 'C1', 'Seriation orders archaeological assemblages by changes in artifact styles or frequencies. If a pottery type gradually becomes popular and later declines, sites can sometimes be arranged so its frequency forms a unimodal pattern. The order is relative, not a calendar date, and trade or regional preferences can violate the assumed sequence. Archaeologists compare several artifact types and anchor portions of the order with independently dated material. A neat curve is evidence for one chronology only if the assemblages are genuinely comparable.', [
    ['What does frequency seriation directly provide?', ['A relative sequence based on patterned changes in artifact prevalence', 'An exact year for every archaeological layer', 'Proof that trade never influenced pottery use', 'A guarantee of one regional style'], 0, 'The technique orders rather than absolutely dates assemblages.'],
    ['Why are independently dated materials useful?', ['They connect parts of the relative order to calendar time', 'They force every artifact type into the same frequency curve', 'They remove differences among regions', 'They make assemblage comparability irrelevant'], 2, 'External dates anchor an otherwise relative chronology.'],
  ]),
  ...listeningGroup('talk-fluorescence', 'Listen to an Academic Talk', '생물영상학', 'C1', 'Fluorescent molecules absorb light at one wavelength and emit some energy at a longer wavelength. Researchers attach fluorescent labels to particular proteins and use filters to distinguish emitted light from excitation light. A bright image does not automatically mean more protein: illumination intensity, detector settings, bleaching, and label efficiency all matter. Quantitative comparisons require consistent acquisition settings, background correction, and ideally calibration standards. Excess excitation can also damage living cells, a problem called phototoxicity.', [
    ['Why is image brightness not a direct protein measure?', ['Technical conditions and labeling efficiency also influence detected light', 'Fluorescent molecules emit only the excitation wavelength', 'Detector settings never change recorded intensity', 'Background correction removes the labeled protein'], 1, 'Signal magnitude is jointly determined by biology and acquisition.'],
    ['What is one cost of using excessive excitation light?', ['It can injure the living sample being observed', 'It prevents molecules from absorbing any photons', 'It guarantees stable fluorescence indefinitely', 'It eliminates the need for calibration'], 3, 'Phototoxicity is measurement-induced biological damage.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the apparent policy effect questioned?', 'Had the comparison', ['cities also changed', 'their behavior', 'the estimated gap', 'would not represent', 'an untreated trend'], 'f09-inverted-third-conditional-negative'],
  ['Did the new evidence disprove the account?', 'What it did', ['was narrow', 'the range', 'of explanations', 'rather than', 'select one'], 'f09-what-cleft-rather-than'],
  ['Why can the old inscription not be read confidently?', 'So extensively has', ['the surface eroded', 'that several letters', 'can be restored', 'only by', 'analogy'], 'f09-so-adverb-inversion-passive'],
  ['Should the result be generalized nationally?', 'Local though the', ['estimate is', 'it may still', 'reveal a mechanism', 'worth testing', 'elsewhere'], 'f09-adjective-though-concession'],
  ['How was the missing emission recovered?', 'By combining measurements', ['taken at different', 'baselines the team', 'was able', 'to reconstruct', 'a broader structure'], 'f09-by-gerund-past-able'],
  ['Why did the reviewers request raw data?', 'They wanted to', ['verify not only', 'which cases', 'had been excluded', 'but on', 'what grounds'], 'f09-not-only-embedded-passive'],
  ['Could the association reflect reverse causation?', 'That possibility cannot', ['be dismissed', 'unless temporal order', 'is established', 'independently of', 'self-report'], 'f09-unless-passive'],
  ['What makes the trade-off difficult?', 'To improve efficiency', ['is often', 'to reduce', 'the margin', 'by which', 'failure is avoided'], 'f09-infinitive-parallel-preposition-relative'],
  ['Did the revised model explain every site?', 'There were still', ['locations for which', 'neither mechanism', 'accounted adequately', 'for the', 'observed pattern'], 'f09-existential-relative-neither'],
  ['Why report the negative finding?', 'Were it omitted', ['readers might infer', 'that every test', 'had supported', 'the original', 'prediction'], 'f09-inverted-passive-counterfactual'],
]
const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '박물관 대여', 'B2', 420), instruction: '문제, 근거, 필요한 후속 조치를 분명히 제시하는 이메일을 작성하세요.', prompt: 'A borrowed exhibit object is scheduled to move to a different gallery, but the loan agreement approves only its current display case and light level. Write to the exhibition coordinator. Explain the documentation problem, describe the risk of moving it now, and request the information and approvals needed before relocation.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '인과 정책평가', 'C1', 600), instruction: '두 관점을 평가하고 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Chandra: When randomized experiments are impossible, what should make policy makers trust a causal conclusion from observational data?', passage: 'Eva: A well-designed natural experiment can approximate random assignment and provide useful guidance.\nRavi: Sophisticated statistics cannot rescue a study whose identifying assumptions are implausible or poorly documented.' })

const repeatSentences = ['Welcome to the coastal field station dormitory.', 'Store wet boots on the rack beside the entrance.', 'Label every food container placed in the shared refrigerator.', 'Keep exterior doors closed to prevent insects from entering.', 'Quiet hours begin before tomorrow morning’s early survey.', 'Report damaged screens or water leaks to the station manager.', 'Before checkout, clean your work surface, remove refrigerated samples, and return the room key with the completed inventory sheet.']
const interviewQuestions = ['Describe a decision that had to be made without a controlled experiment.', 'What evidence made the decision reasonable or unreasonable?', 'How can decision makers communicate uncertainty without appearing indecisive?', 'When is waiting for stronger evidence more harmful than acting on imperfect information?']
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '해안 현장기지 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f09-repeat', scenarioId: 'f09-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '불완전한 증거와 결정', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f09-interview', scenarioId: 'f09-interview', sequenceIndex })),
]

export const AUTHORED_FORM_09_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_09_IDS = AUTHORED_FORM_09_ITEMS.map((item) => item.id)
