import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f16')

const reading: BaseItem[] = [
  cloze('cloze-paleomagnetism', '지구물리학', 'C1', 'When certain minerals form or cool, their magnetic grains can align with Earth’s field. The grains can pres___ its direction, and because the planet’s magnetic polarity has rev___ many times, sequences of normal and reversed orientation provide chronological markers. Geophysicists mea___ remanent magnetization in oriented rock or sediment samples. The record can be dist___ by later heating, chemical alteration, or physical rotation. Researchers demag___ specimens step by step to isolate components acquired at different times. They then comp___ local patterns with independently dated reversal scales. A polarity match alone may be amb___ if several intervals share the same orientation. Stratigraphy and radiometric ages nar___ the alternatives. Paleomagnetic directions also rev___ movement of tectonic plates, but interpretation req___ correcting for deformation after magnetization.', 'erve|ersed|sure|urbed|netize|are|iguous|row|eal|uires'),
  cloze('cloze-homeostasis', '생리학', 'B2', 'Homeostasis keeps internal conditions within ranges compatible with life. Sensors det___ a change, control centers compare it with a target, and effectors prod___ a response. Negative feedback opp___ the initial disturbance: sweating reduces elevated body temperature, for example. The target itself can sh___ with time or context, so regulation is not absolute constancy. Fever temporarily ra___ the defended temperature range. Multiple systems may comp___ or cooperate, and a response beneficial in the short term can become cost___ if prolonged. Scientists distinguish correlation from feedback by perturbing a variable and tracking delayed effects. A stable measurement does not prove inactivity; active processes may be bal___ opposing flows. Understanding the loop req___ identifying signals, response timing, and limits beyond which compensation fa___.', 'ect|uce|oses|ift|ises|ete|ly|ancing|uires|ils'),
  cloze('cloze-dyes', '직물보존과학', 'C1', 'Natural textile dyes may be extracted from plants, insects, or minerals, but their color depends on fiber, mordant, preparation, and aging. A mordant can bind dye to cloth and alt___ its hue. Light may bre___ chromophores, while acidity and metal ions accel___ other reactions. Conservators sample sparingly because even a tiny fiber is lost from the object. Chromatography sep___ dye compounds, and spectroscopy provides complementary information without always identifying a unique source. Historical recipes help, but artisans mod___ procedures and traded materials widely. A chemical match does not establish where a textile was woven. Researchers integ___ technical results with fiber structure, pattern, provenance, and documentary evidence. Display limits red___ cumulative fading, though damage already caused by light is rarely rev___. Detailed baselines allow later staff to det___ subtle change and adj___ exposure.', 'er|ak|erate|arates|ified|rate|uce|ersible|ect|ust'),
  daily('daily-core-hours', '연산 자원', 'B2', 'High-memory compute nodes are billed by reserved core-hour, even when a job uses fewer cores than requested. Canceling a queued job incurs no charge, but terminating a running job does. Users should profile a short test before reserving an entire node.', ['Why is a short profiling run recommended?', ['It helps avoid paying for capacity the full job will not use', 'It makes every running reservation free to terminate', 'It converts high-memory nodes into ordinary desktop computers', 'It guarantees that queued jobs begin without scheduling delay'], 0, 'Resource requests should match actual demand.']),
  daily('daily-lending-copy', '도서관 상호대차', 'B2', 'An interlibrary-loan scan may be retained for personal research under the supplying library’s terms. Uploading it to a course site requires separate permission, even if access is limited to enrolled students. The request record identifies the license that applies.', ['What should an instructor check before posting the scan?', ['Whether the supplying license authorizes course-site distribution', 'Whether every enrolled student owns the printed journal', 'Whether personal research use has already expired', 'Whether the request record can be deleted after download'], 0, 'Personal delivery does not automatically cover redistribution.']),
  daily('daily-reef-permit', '해양 현장조사', 'B2', 'A reef permit limits both the number of fragments collected and the area disturbed. Photographing an additional colony is allowed, but scraping it for identification counts as collection. Unused fragment allowances cannot be transferred to another protected site.', ['Which action counts against the collection limit?', ['Removing surface material from a colony for identification', 'Taking a noncontact photograph of another colony', 'Leaving part of the approved allowance unused', 'Viewing a different protected site from the boat'], 0, 'Physical removal qualifies as collection.']),
  daily('daily-proof-stage', '학술 출판', 'B2', 'Page proofs are intended for production errors and minor factual corrections, not substantial rewriting. A change that alters pagination may require editorial approval and delay publication. Authors should answer every typesetter query, including queries whose proposed wording they reject.', ['Why must a rejected query still receive an answer?', ['Production staff need an explicit decision rather than an unresolved flag', 'Rejecting wording automatically removes the query from the proof', 'Every queried sentence must be rewritten to change pagination', 'Editorial approval is unnecessary for unanswered issues'], 0, 'The typesetter must know how to close each issue.']),
  daily('daily-accelerator-badge', '입자가속기', 'C1', 'Radiation badges are assigned to individuals and cannot be shared to admit a colleague. A lost badge must be reported before entering a controlled area; dose records cannot be reconstructed reliably from another person’s monitor. Temporary access requires a separately issued electronic dosimeter.', ['Why is borrowing another researcher’s badge unacceptable?', ['It would attribute exposure to the wrong individual', 'A shared badge prevents the controlled door from opening', 'Electronic dosimeters contain no personal identifier', 'Dose records are based solely on room reservations'], 0, 'Personal monitoring preserves exposure attribution.']),
  daily('daily-deaccession', '박물관 운영', 'B2', 'An object proposed for deaccession remains part of the collection until the governing board approves removal. Staff may research title and condition but cannot promise it to another institution in advance. Any proceeds must follow the museum’s collection policy rather than cover routine operating deficits.', ['What is prohibited before board approval?', ['Committing the object to a recipient as though removal were final', 'Investigating the legal title attached to the object', 'Documenting damage found during a condition review', 'Consulting the museum’s existing collection policy'], 0, 'A proposal does not yet authorize disposition.']),
  daily('daily-lab-meeting', '연구실 회의', 'B2', 'Presenters circulate one figure without its interpretation the day before the lab meeting. Members annotate what the axes show, what comparisons are justified, and what information is missing. The presenter adds the conclusion only after this independent reading exercise.', ['Why is the conclusion initially withheld?', ['To reveal how others interpret the evidence without being anchored by the presenter', 'To prevent members from examining labels on the figure', 'To replace discussion with anonymous manuscript review', 'To guarantee that everyone reaches an identical explanation'], 0, 'Independent interpretation exposes ambiguity and assumptions.']),
  daily('daily-soil-export', '생물시료 운송', 'B2', 'Soil leaving the country may require both an export certificate and an import permit from the destination. A courier’s willingness to accept the package proves neither. Researchers should obtain the destination document first because its conditions determine treatment and packaging.', ['Why should the import permit be obtained first?', ['Its requirements shape how the soil must be prepared for shipment', 'Courier acceptance automatically supplies the export certificate', 'The destination country cannot regulate incoming biological material', 'Packaging conditions are determined only after customs delivery'], 0, 'Receiving-country rules influence upstream preparation.']),
  daily('daily-oral-citation', '발표 평가', 'B2', 'In an oral presentation, a brief author-and-year reference is sufficient when the full source appears on the final slide. Direct quotations still require a visible page or section locator. Images need source labels at the moment they appear, not only in a closing bibliography.', ['Which item needs a source label during its display?', ['An image incorporated into a presentation slide', 'A paraphrase followed by an audible author and year', 'A source listed fully on the final reference slide', 'An original chart created from the speaker’s own observations'], 0, 'Visual attribution should accompany the material.']),
  daily('daily-control-update', '소프트웨어 재현성', 'B2', 'A container image tagged “latest” may change without warning. Analyses intended for publication should record the immutable image digest as well as the readable version name. Rebuilding from a moving tag can install different dependencies even when the command is unchanged.', ['What makes the image digest important?', ['It identifies the exact dependency environment used for the analysis', 'It ensures the readable version name can never be updated', 'It removes every external package from the container', 'It converts a command into a permanently running process'], 0, 'The digest pins content rather than a mutable label.']),
  ...readingGroup('academic-discontinuity', '인과추론', 'C1', 'Regression discontinuity designs exploit a rule that assigns treatment at a threshold, such as a scholarship awarded above a test-score cutoff. Units just above and below the cutoff may be comparable except for treatment status. The causal estimate is local to the threshold and depends on potential outcomes changing smoothly in the absence of treatment. If applicants can manipulate scores precisely, comparability may fail. Analysts inspect the density of the running variable, test predetermined characteristics, and examine sensitivity to bandwidth and functional form. A visible jump is not automatically causal if another policy begins at the same cutoff.', [
    ['Why does the design focus on observations near the threshold?', ['Nearby units are more plausibly alike apart from treatment assignment', 'Treatment effects must be identical at every possible score', 'Scores far from the cutoff contain no measured outcomes', 'The threshold removes every source of sampling uncertainty'], 0, 'Local comparison supports the quasi-experimental argument.'],
    ['How can precise score manipulation undermine the design?', ['People on opposite sides may differ systematically because they sorted around the cutoff', 'It guarantees a larger treatment effect for every applicant', 'It makes the running variable independent of all prior traits', 'It prevents analysts from selecting any bandwidth'], 0, 'Sorting breaks continuity-based comparability.'],
    ['Why check for another policy at the same threshold?', ['A coincident intervention could cause the observed outcome discontinuity', 'Multiple policies ensure the target treatment is isolated', 'Predetermined characteristics can change only when no policy exists', 'The density test directly measures every policy effect'], 0, 'A shared cutoff creates causal ambiguity.'],
  ]),
  ...readingGroup('academic-niche', '진화생태학', 'C1', 'Niche construction occurs when organisms modify environments in ways that alter selection pressures. Beavers build dams, earthworms change soil, and plants influence fire regimes. Environmental modification is not unique to humans and need not be intentional. If effects persist, descendants may inherit an altered habitat as well as genes, a process sometimes called ecological inheritance. This framework does not replace natural selection; it emphasizes reciprocal causation between organisms and environments. Demonstrating niche construction requires more than showing that an organism changes its surroundings: researchers must connect the modification to differential survival or reproduction and evaluate alternative pathways.', [
    ['Why is intention unnecessary for niche construction?', ['Evolutionary consequences depend on environmental effects, not conscious planning', 'Only human activities can persist across generations', 'Natural selection stops whenever organisms modify a habitat', 'Ecological inheritance requires teaching behavior to offspring'], 0, 'Functional consequences can arise without foresight.'],
    ['What evidence goes beyond documenting environmental change?', ['A link from the modification to altered fitness or selection', 'A photograph showing an organism present at the site', 'Proof that every descendant inherits identical genes', 'Elimination of all reciprocal influence from the environment'], 0, 'The evolutionary claim needs a selection-related consequence.'],
  ]),
  ...readingGroup('academic-iconoclasm', '미술사', 'C1', 'Iconoclasm is often described as image destruction, but altered objects can continue to acquire meaning. Faces may be scratched out while bodies remain displayed; statues may be relocated, recarved, buried, or reused as building material. Damage can signal condemnation, ritual neutralization, political succession, or later neglect. Scholars therefore distinguish when and how interventions occurred. Tool marks, weathering, archaeological context, and written accounts help separate ancient alteration from modern vandalism. An intact object is not necessarily one that escaped conflict: it may have been hidden, reclassified, or protected by a new interpretation.', [
    ['Why is the category of simple destruction inadequate?', ['Alteration and reuse can communicate distinct social and political meanings', 'Every damaged image was accidentally weathered after excavation', 'Recarved statues cease to provide historical evidence', 'Building material cannot preserve traces of an earlier object'], 0, 'Material transformation may itself be purposeful communication.'],
    ['How can scholars distinguish phases of damage?', ['They combine physical traces with context and documentary chronology', 'They assume all missing faces were removed in modern times', 'They date intervention solely from the artistic style of intact portions', 'They treat burial as proof that no conflict occurred'], 0, 'Multiple evidence types establish sequence.'],
    ['Why might an intact image still reflect conflict?', ['Its survival may result from concealment or reinterpretation during contested periods', 'Lack of visible damage proves universal acceptance', 'Protected objects cannot be moved from their original setting', 'A new classification always leaves physical scars'], 0, 'Survival can be an active historical outcome.'],
  ]),
  ...readingGroup('academic-turbulence', '유체역학', 'C1', 'Turbulent flow contains irregular motions across many spatial scales. Energy typically enters at large scales, passes through an intermediate cascade, and dissipates as heat at small scales through viscosity. Although individual eddies are difficult to predict, statistical properties can be reproducible. The transition from laminar to turbulent flow depends strongly on the Reynolds number, which compares inertial and viscous effects, but geometry and disturbances also matter. Numerical simulation must resolve relevant scales or represent unresolved motion with a model. Increasing computational resolution does not remove uncertainty from boundary conditions or turbulence closures.', [
    ['How can turbulence be studied despite unpredictable eddies?', ['Stable statistical patterns may emerge even when exact trajectories vary', 'Viscosity prevents energy from reaching small spatial scales', 'Every large eddy repeats at the same location and time', 'Laminar equations contain no measurable quantities'], 0, 'Ensemble properties can be predictable without detailed motion.'],
    ['Why does finer simulation resolution not solve every problem?', ['Inputs and representations of unresolved processes can remain uncertain', 'Computational grids eliminate the influence of boundary conditions', 'Reynolds number becomes undefined when more scales are resolved', 'Geometry matters only in laboratory observations'], 0, 'Numerical detail cannot correct all modeling assumptions.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the scanner capture the manuscript’s watermark?', ['Yes, after we adjusted the transmitted-light setting.', 'The manuscript contains two ownership inscriptions.', 'Watermarks identify every paper mill uniquely.', 'I scanned the agenda before the committee meeting.'], 0, 'The response confirms capture and adjustment.'),
  response(1, 'Why was the soil shipment held at customs?', ['The soil came from three sampling depths.', 'The import permit listed an outdated treatment code.', 'I held the sample tube upright during weighing.', 'Customs records are retained for five years.'], 1, 'A document mismatch explains the hold.'),
  response(2, 'Could the threshold effect reflect another program?', ['The program began in the same fiscal year.', 'Threshold designs estimate local effects.', 'Yes, if both policies use the identical eligibility cutoff.', 'I reflected the light away from the detector.'], 2, 'A shared assignment point creates confounding.'),
  response(3, 'I thought the workshop fee included protective eyewear.', ['The workshop demonstrates three fabrication methods.', 'Protective eyewear must meet the posted impact standard.', 'I included the appendix with my application.', 'Standard glasses are provided; prescription inserts cost extra.'], 3, 'The reply clarifies what the fee covers.'),
  response(4, 'May we rotate the sculpture to inspect its reverse?', ['Only after the mount engineer approves the new load direction.', 'The sculpture depicts a seated civic official.', 'Rotation makes three-dimensional objects easier to photograph.', 'I inspected the reverse-coded survey items.'], 0, 'Load safety must precede movement.'),
  response(5, 'Where is the uncensored interview transcript?', ['The interview was conducted in the participant’s home.', 'In the access-controlled folder under its retention code.', 'Transcripts preserve pauses with a special notation.', 'I censored identifying details in the public quotation.'], 1, 'The answer gives a restricted location.'),
  response(6, 'Shouldn’t the model include a site-specific intercept?', ['The sites differ in annual rainfall and elevation.', 'An intercept shifts the expected response level.', 'Probably, because repeated observations are clustered within sites.', 'I included the map in the supplementary files.'], 2, 'Clustering motivates a site-level term.'),
  response(7, 'The specimen label and database disagree on collection depth.', ['Collection depth is reported in centimeters below surface.', 'The database was migrated from an older system.', 'I labeled the vertical axis with depth.', 'Quarantine the record pair until the field notebook resolves it.'], 3, 'Conflicting identity data should not be guessed.'),
  response(8, 'Is the departmental seminar open to undergraduates?', ['Yes, but they must request the preparatory reading in advance.', 'The department sponsors several seminar series.', 'Undergraduate degrees normally require four years.', 'I opened the attachment from the seminar coordinator.'], 0, 'The response grants access with a condition.'),
  response(9, 'Why did the reconstructed channel shift eastward?', ['The channel carries seasonal snowmelt.', 'A later levee constrained the western branch.', 'I shifted the plot labels to avoid overlap.', 'Reconstruction uses sediment texture and elevation.'], 1, 'A later constraint explains the path.'),
  response(10, 'Can we compare these calibrated dates directly?', ['The dates come from adjacent excavation units.', 'Calibration curves change over historical time.', 'Not before confirming they use the same curve and uncertainty convention.', 'I compared the new catalog with the printed inventory.'], 2, 'Method consistency is required for direct comparison.'),
  response(11, 'I cannot tell which pipeline generated this table.', ['The table summarizes three model specifications.', 'Pipelines automate repeated analytical steps.', 'I generated the figure after cleaning the data.', 'Check the provenance metadata attached to the output artifact.'], 3, 'Artifact metadata should identify its lineage.'),
  response(12, 'Has the gallery airflow returned to its normal range?', ['Yes, though staff are watching for another pressure drop.', 'The gallery contains several large textile cases.', 'Airflow moves from the corridor toward the storage room.', 'I returned the borrowed sensor this morning.'], 0, 'The response reports recovery with continued monitoring.'),
  response(13, 'When should we submit the revised machine drawing?', ['The drawing specifies tolerance for each joint.', 'By Monday, before the fabrication review is locked.', 'I revised the discussion to address two reviewers.', 'Machine drawings use several line conventions.'], 1, 'The response identifies the deadline and reason.'),
  response(14, 'Would trimming extreme weights stabilize the estimate?', ['The weights account for unequal selection probability.', 'Extreme observations appear at both tails.', 'It might, but we must quantify the bias introduced by trimming.', 'I trimmed the damaged edge of the backing paper.'], 2, 'Stability trades against altered estimand or bias.'),
  response(15, 'Who can reopen the sealed evidence cabinet?', ['The cabinet uses two independent locks.', 'Evidence handling requires a signed custody record.', 'The seal number appears in the incident report.', 'The compliance officer and collection custodian must be present together.'], 3, 'Dual attendance is required.'),
  response(16, 'This protein structure looks unusually compact.', ['Verify whether the visualization omitted disordered regions.', 'The protein was purified from cultured cells.', 'Compact structures often fit inside smaller crystals.', 'I structured the literature review around two mechanisms.'], 0, 'Display choices may explain apparent compactness.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-bandwidth', 'Listen to a Conversation', '회귀불연속 분석', 'C1', 'Student: The effect is significant with a wide bandwidth but disappears when I use only scores near the cutoff. Advisor: The wide estimate gains precision but relies more heavily on the functional form away from the threshold. Student: Which one should I report? Advisor: Report the prespecified bandwidth, justified alternatives, and the full sensitivity pattern. Do not select the window because it gives the preferred result.', [
    ['What tradeoff does the advisor identify?', ['A wider window adds information but depends more on extrapolating the fitted relationship', 'A narrow window guarantees that every estimate is statistically significant', 'Prespecification eliminates the need for any sensitivity analysis', 'Functional form matters only at the exact cutoff score'], 0, 'Bandwidth balances precision against modeling dependence.'],
    ['How should the student present the estimates?', ['Show principled specifications rather than choosing one by outcome', 'Hide the narrow result because it lacks significance', 'Use every possible bandwidth as an independent experiment', 'Replace the original analysis with the widest window only'], 0, 'Transparent sensitivity prevents result-driven selection.'],
  ]),
  ...listeningGroup('conversation-dialect', 'Listen to a Conversation', '방언 인터뷰', 'C1', 'Researcher: The speaker uses the local vowel in casual conversation but not during my word list. Linguist: The formal task may have shifted attention toward a prestige pronunciation. Researcher: Does that make the list useless? Linguist: No. It reveals style shifting. Combine it with spontaneous speech and note who was present, because audience and task both affect the variant.', [
    ['Why did pronunciation change during the word list?', ['The formal elicitation context may have increased monitoring of speech', 'The local vowel cannot occur inside isolated words', 'Prestige pronunciation is used only with family members', 'Spontaneous speech contains no social variation'], 0, 'Task formality can influence style.'],
    ['How does the linguist interpret the contrasting recordings?', ['They provide evidence about context-sensitive variation', 'They prove one recording device altered the vowel', 'They require discarding all elicited speech', 'They show the speaker permanently changed dialect'], 0, 'The contrast is itself sociolinguistic data.'],
  ]),
  ...listeningGroup('conversation-repair', 'Listen to a Conversation', '건축 보존', 'B2', 'Architect: The replacement bricks match the wall’s color exactly today. Conservator: That may not last. New bricks weather differently, and an exact fresh match can become conspicuous later. Architect: Should we choose a darker brick? Conservator: Choose compatible material first, then evaluate a range that remains distinguishable on close inspection without dominating the facade.', [
    ['Why is an exact current color match questionable?', ['New and historic materials may age along different trajectories', 'Replacement bricks are required to be darker than every original', 'Close inspection should never reveal a conservation repair', 'Weathering makes all masonry converge to one color'], 0, 'Present appearance does not predict long-term match.'],
    ['What priority does the conservator set?', ['Physical compatibility before fine adjustment of visual integration', 'Complete invisibility regardless of material performance', 'Maximum contrast with the surrounding historical wall', 'Selection based solely on the cheapest available brick'], 0, 'Material behavior precedes aesthetic nuance.'],
  ]),
  ...listeningGroup('conversation-randomization', 'Listen to a Conversation', '온라인 실험', 'C1', 'Assistant: Participants are assigned randomly, but the treatment group has more mobile-phone users. Investigator: Randomization balances characteristics in expectation, not perfectly in every sample. Assistant: Should I rerandomize until the groups match? Investigator: Not after viewing assignments. Keep the valid allocation, report the imbalance, and adjust only according to the analysis plan.', [
    ['What misconception does the investigator correct?', ['Random assignment does not ensure exact balance in a finite sample', 'Mobile users cannot participate in randomized experiments', 'Viewing assignments is required before every rerandomization', 'Covariate adjustment invalidates all experimental comparisons'], 0, 'Chance imbalance is compatible with valid randomization.'],
    ['Why should the assistant not rerandomize now?', ['Choosing after inspection could make allocation depend on observed characteristics', 'The existing groups already contain identical device proportions', 'Rerandomization always reduces statistical precision to zero', 'Analysis plans cannot mention baseline covariates'], 0, 'Post hoc allocation selection threatens design integrity.'],
  ]),
  ...listeningGroup('conversation-catalog', 'Listen to a Conversation', '표본 분류', 'B2', 'Student: Two shells share an old catalog number but have different collection labels. Registrar: The number may have referred to a lot later divided into specimens. Student: Should I assign suffixes? Registrar: Preserve the historical number, create provisional child records, and wait for the accession book before making permanent identifiers.', [
    ['What likely explains the shared catalog number?', ['The original record may have described a group rather than individual objects', 'Both labels must refer to one physically identical shell', 'Collection locations were deliberately removed from the archive', 'Suffixes existed before the specimens were acquired'], 0, 'Historical cataloging may operate at lot level.'],
    ['Why are the new records provisional?', ['Archival evidence is needed before finalizing the identifier relationship', 'Child records cannot contain collection labels', 'The old number must be erased before checking the book', 'Permanent identifiers are assigned by the student alone'], 0, 'The accession book may confirm or alter the reconstruction.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-roof', 'Listen to an Announcement', '옥상 온실', 'B2', 'The rooftop greenhouse closes at four today because crane work begins beside the building. Experiments with automated irrigation may continue unattended, but researchers must remove loose tools and lower all shade screens by three thirty. Remote sensor access remains available throughout the closure.', [
    ['Which activity may continue after the greenhouse closes?', ['Previously configured automatic watering', 'Manual adjustment of unsecured shade screens', 'Tool storage on exposed rooftop benches', 'In-person sampling during crane operation'], 0, 'Unattended automation is allowed.'],
    ['What must be completed by three thirty?', ['Securing loose equipment and lowering the screens', 'Disabling every remote environmental sensor', 'Ending all automated irrigation experiments', 'Moving the crane to another campus building'], 0, 'Wind and crane safety require site preparation.'],
  ]),
  ...listeningGroup('announcement-transcript', 'Listen to an Announcement', '강의 기록', 'B2', 'Transcripts for Monday’s guest lecture will be posted Wednesday. The audio is available now, but minute twenty-two contains a speaker-name error in the automatic captions. A correction notice appears beside the player. Students citing that passage should use the reviewed transcript, not copy the current caption text.', [
    ['What is wrong with the current caption file?', ['It assigns one portion of speech to the wrong person', 'It omits the entire guest lecture after minute twenty-two', 'It prevents students from playing the audio', 'It contains no notice about pending correction'], 0, 'Speaker attribution is inaccurate at a known point.'],
    ['What source should be used for citing the affected passage?', ['The human-reviewed transcript released Wednesday', 'The uncorrected automatic caption displayed now', 'A student’s memory of the live lecture', 'The audio player’s correction notice alone'], 0, 'The reviewed text will be authoritative.'],
  ]),
  ...listeningGroup('announcement-mass-spec', 'Listen to an Announcement', '질량분석실', 'C1', 'The mass spectrometer will run a high-salt cleaning sequence overnight. Samples already in the autosampler remain scheduled, but users must confirm that their vial caps are compatible with the extended wash solvent. Unconfirmed trays will be removed at six and returned without analysis. Confirmation closes at five thirty in the instrument portal.', [
    ['Which samples risk removal from the run?', ['Those lacking timely confirmation of cap compatibility', 'Every vial scheduled before the cleaning sequence', 'Samples whose trays contain no high-salt wash solvent', 'All analyses confirmed before five thirty'], 0, 'The run retains only verified containers.'],
    ['Why is cap compatibility relevant?', ['The prolonged solvent exposure may affect unsuitable closures', 'Caps determine the mass range detected by the instrument', 'The autosampler cannot identify any confirmed tray', 'Cleaning eliminates the need for sealed vials'], 0, 'The modified wash changes material exposure.'],
  ]),
  ...listeningGroup('announcement-screening', 'Listen to an Announcement', '영화 상영', 'B1', 'Friday’s documentary screening is free, but the discussion afterward has limited seating. Screening tickets do not reserve discussion places. Collect a numbered discussion pass at the lobby desk before the film; unclaimed passes will be offered again when the credits begin.', [
    ['What does a film ticket not guarantee?', ['Admission to the limited post-screening discussion', 'Entry to the documentary itself on Friday', 'Access to the lobby before the film starts', 'The ability to watch the closing credits'], 0, 'The two events use separate capacity controls.'],
    ['When are unused discussion passes redistributed?', ['As the film reaches its closing credits', 'After the entire discussion has concluded', 'Before the lobby desk opens', 'When free screening tickets are first printed'], 0, 'A second allocation occurs near the film’s end.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-lichen', 'Listen to an Academic Talk', '공생생물학', 'C1', 'A lichen is a stable association involving a fungus and one or more photosynthetic partners, often algae or cyanobacteria. The fungus structures the body and captures water and minerals; the partner supplies fixed carbon. Many lichens also contain diverse bacteria and yeasts, so the organism is better viewed as a small consortium than a simple pair. Partners that live independently may behave differently inside the association. Classification traditionally follows the fungal component because it shapes morphology and reproduction, but ecological function emerges from interaction.', [
    ['Why is describing a lichen as two organisms incomplete?', ['Additional microbial partners can contribute to the functioning association', 'The photosynthetic partner always replaces the fungus', 'Fungal cells perform all carbon fixation independently', 'Every bacterium in the environment becomes part of the lichen'], 0, 'The symbiosis can include a broader community.'],
    ['Why is classification usually based on the fungus?', ['It provides major body structure and reproductive identity', 'It is the only partner capable of living independently', 'It prevents any ecological interaction with algae', 'It supplies all photosynthetic carbon to the consortium'], 0, 'Taxonomic convention follows the dominant structural partner.'],
  ]),
  ...listeningGroup('talk-inflation', 'Listen to an Academic Talk', '거시경제학', 'C1', 'A price index combines changes in many goods into one measure of inflation. A fixed basket is transparent but can overstate cost increases when consumers substitute away from products whose prices rise. A changing basket captures substitution yet may make comparisons less intuitive. Quality improvement creates another challenge: a higher price for a more capable product is not pure inflation. Statistical agencies use hedonic models, replacement rules, and multiple indexes, each suited to different questions. No single number describes every household’s experience because spending patterns differ.', [
    ['Why can a fixed basket overstate the rise in living cost?', ['It ignores consumers’ ability to shift purchases toward relatively cheaper alternatives', 'It removes every product whose price remains constant', 'It treats quality improvement as an automatic price decrease', 'It changes expenditure weights after each transaction'], 0, 'Substitution can reduce the cost of achieving similar utility.'],
    ['Why may households experience different inflation?', ['They purchase different combinations of goods whose prices change unequally', 'Statistical agencies assign a separate currency to each family', 'A price index excludes all frequently purchased products', 'Quality adjustment forces every household to upgrade devices'], 0, 'Aggregate weights need not match individual budgets.'],
  ]),
  ...listeningGroup('talk-placebo', 'Listen to an Academic Talk', '임상방법론', 'C1', 'A placebo control helps separate a treatment’s specific effects from expectations, attention, and natural change. Blinding is imperfect when side effects reveal assignment. An active placebo mimics some sensations without delivering the hypothesized mechanism, but it may have physiological effects of its own. Researchers assess guesses about assignment and interpret differences alongside adherence and dropout. Calling any improvement in the placebo group a placebo effect is misleading because regression to the mean and spontaneous recovery also contribute.', [
    ['Why can side effects threaten blinding?', ['Participants may infer assignment and change expectations or behavior', 'They ensure that the placebo contains the active mechanism', 'They prevent researchers from measuring any clinical outcome', 'Participants with side effects are always in the control group'], 0, 'Perceived assignment can alter nonspecific effects.'],
    ['Why is improvement in a placebo group not a pure placebo effect?', ['Several nonintervention processes can produce change over time', 'Placebos necessarily cure the target condition biologically', 'Regression to the mean occurs only in treated participants', 'Spontaneous recovery is identical to treatment adherence'], 0, 'The group’s trajectory mixes multiple causes.'],
  ]),
  ...listeningGroup('talk-perspective', 'Listen to an Academic Talk', '회화사', 'B2', 'Linear perspective represents depth by making parallel lines converge toward vanishing points and scaling objects with distance. It is a convention grounded in geometry, not a neutral copy of vision. Viewers normally move their eyes and bodies, whereas a perspective construction assumes a fixed station point. Artists may violate the system to preserve important figures, combine viewpoints, or create expressive distortion. Judging every image by strict perspective therefore mistakes one representational goal for a universal standard.', [
    ['Why is linear perspective described as a convention?', ['It organizes a scene from an idealized fixed viewpoint using geometric rules', 'It reproduces all aspects of moving human vision automatically', 'It prohibits artists from representing distant objects', 'It assigns symbolic importance without using spatial cues'], 0, 'The system formalizes one viewing condition.'],
    ['Why might an artist depart from strict perspective?', ['Other communicative or expressive priorities may outweigh geometric consistency', 'Vanishing points cannot be used in any architectural scene', 'Objects lose cultural importance when shown at constant size', 'Viewers are unable to interpret combined viewpoints'], 0, 'Representation serves goals beyond optical simulation.'],
  ]),
  ...listeningGroup('talk-thermokarst', 'Listen to an Academic Talk', '한랭지형학', 'C1', 'Thermokarst landscapes form when ice-rich permafrost thaws and the ground subsides. Depressions may fill with water, accelerating local thaw because dark water absorbs heat and transfers it to surrounding soil. Yet a drained lake can expose sediment that freezes again or supports vegetation, changing the trajectory. Satellite images reveal expansion and drainage over large areas, but shallow seasonal ponds can be confused with persistent lakes. Field measurements and multi-year records are needed to distinguish temporary surface water from structural landscape change.', [
    ['How can a thaw lake reinforce local subsidence?', ['Absorbed solar energy promotes additional melting around the depression', 'Water permanently insulates all underlying ice from heat', 'Lake formation removes every dark surface from the landscape', 'Subsidence raises frozen ground above its original elevation'], 0, 'Water creates a local positive feedback.'],
    ['Why are single satellite images insufficient?', ['Seasonal water may resemble a persistent thermokarst feature', 'Satellites cannot observe any water surface at high latitude', 'Field measurements eliminate the need for temporal comparison', 'Drained lakes always refreeze within one day'], 0, 'Persistence distinguishes transient hydrology from landform evolution.'],
  ]),
  ...listeningGroup('talk-bilingual-control', 'Listen to an Academic Talk', '심리언어학', 'C1', 'Bilingual speakers often activate information from both languages even when using one. Selecting the intended word may require competition control, but evidence for a broad bilingual advantage in unrelated executive tasks is mixed. Group differences in education, migration, socioeconomic background, and language use complicate comparison. Laboratory tasks also have limited reliability. Researchers increasingly measure individual language experience continuously rather than labeling everyone simply bilingual or monolingual.', [
    ['Why is a general executive advantage difficult to establish?', ['Language groups differ in many experiences and task measures can be noisy', 'Both languages are never active during single-language speech', 'Word selection requires no control over competing representations', 'Continuous language measures eliminate all confounding'], 0, 'Group labels and measurement limitations obscure causal interpretation.'],
    ['Why use continuous measures of language experience?', ['Frequency, proficiency, and switching vary substantially within broad categories', 'Every bilingual person uses two languages in the same context', 'Monolingual speakers cannot complete executive tasks', 'Continuous scores guarantee random assignment to language history'], 0, 'Experience is multidimensional rather than binary.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the policy effect uncertain?', 'Even were the discontinuity precisely estimated', ['it would apply', 'primarily to applicants', 'whose scores lay', 'near the threshold'], 'f16-even-were-concessive-inversion'],
  ['What happened after the lake drained?', 'The surface water having disappeared', ['exposed sediment', 'began to freeze', 'from above', 'during winter'], 'f16-absolute-perfect-participle'],
  ['Why did the archive revise the date?', 'No sooner had the seal been identified', ['than researchers found', 'a matching impression', 'in a securely dated', 'administrative layer'], 'f16-no-sooner-than-inversion'],
  ['How did the model perform?', 'The farther predictions extended beyond the sampled range', ['the more heavily', 'they depended', 'on assumptions', 'about functional form'], 'f16-double-comparative-dependence'],
  ['Why keep the damaged image?', 'Damaged though the panel may be', ['its altered surface', 'preserves evidence', 'of successive', 'political interventions'], 'f16-adjective-though-inversion'],
  ['What should the report acknowledge?', 'There being no independent record of exposure', ['the estimated dose', 'cannot be verified', 'from the shared badge', 'after the fact'], 'f16-existential-absolute-clause'],
  ['Could earlier action have helped?', 'If the warning system were functioning now as designed', ['the overnight excursion', 'would likely have been', 'detected', 'before morning'], 'f16-mixed-counterfactual-present-past'],
  ['Why was the comparison persuasive?', 'Not only were the samples collected independently', ['but their analyses', 'were also performed', 'by laboratories', 'using blinded codes'], 'f16-not-only-correlative-inversion'],
  ['What makes the interpretation provisional?', 'Much remains to be established as to whether', ['the observed damage', 'preceded burial', 'or resulted', 'from later excavation'], 'f16-as-to-whether-embedded'],
  ['Why did the engineer reject the patch?', 'It was incompatible to such a degree that', ['seasonal movement', 'would have concentrated', 'stress along', 'the repaired edge'], 'f16-to-such-degree-result'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '연구 소프트웨어 변경', 'C1', 420), instruction: '재현성 문제, 현재 증거, 즉각적 조치와 장기 절차를 구체적으로 작성하세요.', prompt: 'You discover that a shared analysis pipeline automatically updated a dependency between the preliminary and final runs, but neither output records the software digest. Write to the research-computing lead. Explain the discrepancy and its consequences, request a controlled rerun, and propose a version-locking and provenance procedure.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '도시 기후 적응', 'C1', 600), instruction: '효율성뿐 아니라 형평성, 불확실성, 장기 효과를 평가해 논지를 발전시키세요.', prompt: 'Professor Diallo: Should cities prioritize protecting existing neighborhoods from climate hazards or help residents relocate from the highest-risk areas?', passage: 'Sofia: Infrastructure investment preserves communities and avoids disruptive displacement.\nMalik: Repeated protection can become unsustainable when risk rises and may delay safer relocation.' })

const repeatSentences = ['Welcome to the campus conservation imaging room.', 'Set personal items on the shelf outside the marked work area.', 'Confirm the object number before opening its protective enclosure.', 'Position support blocks without covering inscriptions or fragile edges.', 'Use the approved light sequence and record every exposure setting.', 'Do not apply image corrections to the archival master file.', 'When imaging is complete, verify the file checksum, restore the object to its enclosure, and submit the condition and handling record.']
const interviewQuestions = ['Describe a place that faces a growing environmental hazard.', 'What factors make protection or relocation difficult there?', 'How should decision makers compare financial cost with community disruption?', 'What assistance would make a relocation policy more voluntary and fair?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '보존 촬영실', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f16-repeat', scenarioId: 'f16-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '기후 위험과 이주', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f16-interview', scenarioId: 'f16-interview', sequenceIndex })),
]

export const AUTHORED_FORM_16_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_16_IDS = AUTHORED_FORM_16_ITEMS.map((item) => item.id)
