import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f14')

const reading: BaseItem[] = [
  cloze('cloze-permafrost', '기후생지화학', 'C1', 'Permafrost refers to soil, sediment, or rock held at or below freezing for two successive years. It can pres___ organic matter that microbes would otherwise decompose. When climate warming tha___ the active layer more deeply, microbes gain access to this material and rel___ carbon dioxide or methane. Those gases intensify warming, creating a positive feed___. Yet the response is not uniform. Drainage, vegetation, soil ice, and oxygen ava___ determine which gas forms and how rapidly carbon escapes. Abrupt ground collapse may exp___ deep deposits, while plant growth can abs___ some carbon. Scientists comb___ field chambers, aircraft measurements, and models to est___ regional change. Uncertainty about timing does not imp___ that the stored carbon is irrelevant to future climate.', 'erve|ws|ease|back|ilability|ose|orb|ine|imate|ly'),
  cloze('cloze-epigenetics', '분자생물학', 'C1', 'Cells with identical DNA can perform different functions because they activate different genes. Epigenetic mechanisms help main___ these patterns without altering the nucleotide sequence. Chemical tags on DNA or histone proteins can aff___ how readily transcription machinery reaches a gene. Some marks are sta___ through cell division, whereas others change with development or environment. Calling a trait epigenetic does not prove it is inh___ across generations. Most marks are reset during reproduction, and maternal physiology can conf___ apparent transmission. Researchers use controlled crosses and molecular assays to dist___ germ-line inheritance from shared exposure. Epigenetic regulation comp___ genetic control rather than replacing it. Its effects depend on cell type, timing, and genomic con___, so broad claims should be eval___ against a defined mechanism and rep___ evidence.', 'tain|ect|ble|erited|ound|inguish|lements|text|uated|licated'),
  cloze('cloze-binding', '서지학', 'B2', 'A historical bookbinding is evidence about how a volume was made, used, and repaired. Sewing supports conn___ folded gatherings, while boards prot___ the text block. Leather, cloth, or paper may cov___ the exterior. A new-looking binding does not necessarily indicate a new text because old pages were often reb___. Conservators exam___ thread holes, adhesive, wear, and fragments hidden under the spine. Removing a binding can rev___ earlier structure but also destr___ relationships among parts. Noninvasive imaging helps doc___ features before treatment. Scholars comp___ workshop techniques across books and rec___ later repairs separately from original construction.', 'ect|ect|er|ound|ine|eal|oy|ument|are|ord'),
  daily('daily-telescope-queue', '천문 관측', 'B2', 'Targets in the observatory queue are ranked by scientific priority and current sky conditions. A high-ranked object may be skipped if its required seeing is unavailable; it returns to the queue rather than losing approval. Observers should not interpret sequence as a guaranteed clock time.', ['Why might an approved high-priority target not be observed first?', ['Atmospheric conditions may not satisfy its specific measurement requirements', 'Queue approval expires whenever another object is visible', 'Scientific priority is assigned only after observations finish', 'Every target must be observed at a fixed local hour'], 0, 'Execution depends jointly on priority and feasible conditions.']),
  daily('daily-herbarium-loan', '식물표본관', 'B2', 'Loaned herbarium sheets must remain attached to their original backing. Researchers may place removable annotation slips beside a specimen but must not write corrections directly on its historic label. Proposed identifications become part of the record only after curatorial review.', ['How should a researcher suggest a revised species name?', ['Add it on a removable slip for later curatorial assessment', 'Erase the historic label and write the new identification', 'Detach the dried plant from its original backing sheet', 'Replace the curator’s record before returning the loan'], 0, 'Annotations preserve the original evidence and undergo review.']),
  daily('daily-caption', '접근성 지원', 'B2', 'Automatic captions may be used during a live seminar, but the archived recording requires human review. Technical terms and speaker changes must be corrected before publication. If review cannot be completed within two days, publish the slides first and mark the video as pending.', ['What should happen when caption review is delayed?', ['Release the accessible slides while withholding the unfinished video', 'Publish unreviewed technical captions as the permanent archive', 'Remove all speaker labels from the seminar recording', 'Cancel access to the presentation materials indefinitely'], 0, 'The slides provide interim access without releasing faulty captions.']),
  daily('daily-animal-room', '동물 연구시설', 'C1', 'Entering an animal room in the wrong order can transfer pathogens between colonies. Staff follow the day’s posted sequence from highest health status to lowest. Returning to a cleaner room after entering a lower-status room requires showering and a complete change of protective clothing.', ['What determines the normal room-entry sequence?', ['The relative health status assigned to each colony', 'The alphabetical order of the animals’ species names', 'The time at which each investigator arrives', 'The amount of protective clothing stored outside'], 0, 'Movement proceeds from cleaner to less protected colonies.']),
  daily('daily-consulting', '통계 상담', 'C1', 'The statistical consulting service can advise on design before data collection and diagnose code afterward. Consultants do not certify a result merely because software runs without error. Requests should include the research question, sampling process, and a reproducible example rather than screenshots alone.', ['Why are screenshots inadequate for a consulting request?', ['They omit executable context needed to reproduce and diagnose the analysis', 'They reveal the research question more clearly than code', 'Consultants accept only results that contain software errors', 'Sampling procedures become irrelevant once a graph is visible'], 0, 'Reproducibility requires data and code context.']),
  daily('daily-gallery-humidity', '전시 보존', 'B2', 'A humidity alarm reports thirty-minute averages, not instantaneous peaks. Before moving an object, staff check the underlying sensor trace and a second calibrated instrument. A brief door opening may trigger an average warning without exposing the collection to a sustained unsafe condition.', ['Why do staff inspect the detailed sensor trace?', ['To distinguish a short fluctuation from prolonged hazardous exposure', 'To convert every average warning into an evacuation order', 'To recalibrate the gallery by moving a sensitive object', 'To prevent the door from opening during public hours'], 0, 'Duration matters for conservation risk.']),
  daily('daily-makerspace', '제작 실습실', 'B2', 'Completed safety training permits independent use of hand tools, but powered cutting equipment requires a separate machine endorsement. Watching another user does not count as an endorsement. A supervisor may demonstrate the machine, yet only the named trainee may complete the practical assessment.', ['Who may take the machine’s practical assessment?', ['The trainee whose authorization is being evaluated', 'Any observer who has watched the demonstration', 'A friend holding general hand-tool training', 'Every visitor accompanied by an endorsed user'], 0, 'The endorsement is individually assessed.']),
  daily('daily-visa', '방문 연구자', 'C1', 'A visiting scholar may begin remote collaboration before immigration documents are issued, but cannot perform paid work physically on campus. Travel should not be booked from an invitation letter alone; the international office must confirm both status approval and an appropriate entry date.', ['What must occur before the scholar books campus travel?', ['Confirmation of approved status and permissible arrival timing', 'Completion of all remote collaboration from another country', 'Payment for physical work under an invitation letter', 'Publication of the host laboratory’s research results'], 0, 'An invitation does not establish immigration authorization.']),
  daily('daily-field-blank', '수질 분석', 'B2', 'A field blank is clean water opened and handled at the sampling site like an ordinary sample. It is not poured into the stream. Detecting a compound in the blank suggests contamination from bottles, transport, air, or handling and changes how matching detections in environmental samples should be interpreted.', ['What does a contaminant in the field blank indicate?', ['The sampling process may have introduced the compound independently of the stream', 'The clean water accurately measures the river’s natural concentration', 'Every environmental detection must be larger than the blank value', 'The blank should have been released upstream before collection'], 0, 'The control reveals contamination along the workflow.']),
  daily('daily-defense', '학위 심사', 'B2', 'A doctoral defense is public until the questioning period ends. The committee then meets privately; the candidate and audience must leave. A request for remote attendance applies to the public portion only unless the graduate school explicitly authorizes a remote committee member.', ['Which part is ordinarily closed to the audience?', ['The committee’s private deliberation after questioning', 'The candidate’s opening research presentation', 'The announced public question period', 'The introduction of the committee members'], 0, 'Deliberation is distinct from the public defense.']),
  ...readingGroup('academic-signaling', '게임이론', 'C1', 'In signaling models, one party possesses information that another lacks. A signal can convey type only if different types face different incentives or costs. Education, for example, might signal productivity even when it adds little skill, provided obtaining the credential is less costly for highly productive workers. If low-productivity workers can imitate it just as cheaply, employers cannot infer much from the credential. A separating equilibrium assigns different signals to types; a pooling equilibrium leaves them observationally alike. The model does not establish that education is merely a signal. Empirical analysis must distinguish productivity gains from information effects and consider institutions that alter costs.', [
    ['What condition allows a credential to separate worker types?', ['Its relative cost or benefit must differ sufficiently across the hidden types', 'Every worker must receive exactly the same return from obtaining it', 'Employers must already observe productivity without any credential', 'Education must be legally prohibited from teaching useful skills'], 0, 'Separation requires type-dependent incentives.'],
    ['What occurs in a pooling equilibrium?', ['Different underlying types choose an indistinguishable observable action', 'Employers learn each worker’s productivity with complete certainty', 'Only highly productive workers are permitted to enter the market', 'The cost of signaling becomes negative for every participant'], 0, 'A common signal fails to reveal type.'],
    ['Why is empirical evidence still needed?', ['The same educational pattern may reflect skill formation as well as signaling', 'A theoretical equilibrium automatically measures causal effects in real labor markets', 'Institutions cannot influence the cost of acquiring credentials', 'Productivity is defined solely by the number of years in school'], 0, 'The observed association has competing mechanisms.'],
  ]),
  ...readingGroup('academic-coral', '해양생리생태학', 'C1', 'Reef-building corals host photosynthetic algae within their tissues. The algae supply organic carbon, while the coral provides nutrients and a protected, illuminated habitat. Heat stress can disrupt this partnership and cause bleaching, the loss of algae or their pigments. Bleached coral is not immediately dead, but prolonged energy shortage increases mortality and reduces growth and reproduction. Some colonies tolerate heat better because of host genetics, prior exposure, algal partners, or local water conditions. This variation creates potential for acclimatization and selection, yet rapid warming and repeated marine heatwaves may outpace recovery.', [
    ['Why can a bleached coral initially remain alive?', ['Bleaching removes a major energy source without necessarily killing host tissue at once', 'The coral immediately replaces its algae with stored mineral pigment', 'Heat stress increases photosynthesis throughout the colony', 'Reproduction supplies enough carbon to repair every damaged cell'], 0, 'Symbiont loss creates vulnerability rather than instant host death.'],
    ['What limits optimism about heat-tolerant colonies?', ['The pace and recurrence of warming may exceed biological adjustment and recovery', 'All colonies share one genetically identical thermal threshold', 'Previous exposure invariably makes coral less tolerant', 'Local water conditions cannot influence bleaching outcomes'], 0, 'Adaptive capacity operates under rate and frequency constraints.'],
  ]),
  ...readingGroup('academic-sound-change', '역사언어학', 'C1', 'Regular sound change means that a phonetic shift generally affects all eligible words in a speech community, not that every word changes without exception. Lexical borrowing, analogy, dialect mixture, and conditioning environments can create apparent irregularity. If a consonant changes only before front vowels, words in other environments are not counterexamples. Comparative linguists establish correspondences across many basic words and reconstruct ancestral forms. Superficial resemblance is insufficient because chance and borrowing also produce similar sounds. A proposed relationship becomes stronger when multiple sound correspondences recur systematically and grammatical evidence supports the same grouping.', [
    ['Why might an unchanged word fail to refute a regular sound change?', ['It may not occur in the phonological environment that triggered the shift', 'Regularity requires every consonant in a language to disappear', 'Borrowed vocabulary always preserves the oldest ancestral pronunciation', 'Analogy prevents linguists from identifying any historical pattern'], 0, 'Eligibility depends on conditioning context.'],
    ['Why are isolated similar words weak evidence of related languages?', ['Chance resemblance and borrowing can mimic common inheritance', 'Basic vocabulary never retains traces of ancestral forms', 'Related languages must have identical modern pronunciation', 'Grammatical structure cannot contribute to classification'], 0, 'A relationship needs patterned correspondences, not anecdotes.'],
    ['What evidence most strengthens a genealogical proposal?', ['Recurring sound mappings across numerous words reinforced by compatible grammar', 'One culturally important word pronounced alike in two communities', 'A recent loan translated into several neighboring dialects', 'Matching spelling conventions imposed by a modern school system'], 0, 'Independent systematic patterns support shared descent.'],
  ]),
  ...readingGroup('academic-optogenetics', '신경공학', 'C1', 'Optogenetics allows researchers to influence selected neurons with light after introducing light-sensitive ion channels. Genetic targeting determines which cells express the channel, while an implanted fiber or other device delivers light with temporal precision. Activating a circuit and observing behavior can support a causal role, but interpretation requires controls. Light may heat tissue, viral delivery may alter cells, and a targeted genetic marker may occur in more than one functional population. Silencing and activation can also produce different network responses. Researchers therefore verify expression, measure unintended effects, and compare multiple manipulations rather than equating one behavioral change with a complete circuit explanation.', [
    ['What gives optogenetics cell-type selectivity?', ['Restricted expression of the light-sensitive channel through genetic targeting', 'The assumption that implanted fibers illuminate only one neuron', 'Behavioral observation without any anatomical verification', 'Tissue heating caused by prolonged light delivery'], 0, 'Expression control determines which cells respond directly.'],
    ['Why does one induced behavior not fully explain a circuit?', ['Technical side effects and network-wide consequences can support alternative interpretations', 'A causal manipulation cannot influence behavior under any condition', 'Activation and silencing must always yield mirror-image results', 'Genetic markers identify exactly one functional population by definition'], 0, 'Perturbation evidence remains conditional on specificity and mechanism.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the isotope standards arrive on dry ice?', ['Yes, and the receiving temperature was logged immediately.', 'The standard curve contains six concentration levels.', 'Dry ice sublimates instead of forming a liquid.', 'I arrived before the departmental meeting.'], 0, 'The reply confirms condition and documentation.'),
  response(1, 'Why was my studio reservation shortened?', ['The studio has adjustable acoustic panels.', 'A safety inspection now begins at six.', 'I shortened the abstract by two sentences.', 'Reservations can be viewed through the student portal.'], 1, 'A scheduled inspection explains the change.'),
  response(2, 'Could we infer migration from this isotope value alone?', ['Migration influenced settlement patterns in the region.', 'The isotope ratio was measured by mass spectrometry.', 'No; diet and local baseline variation must also be considered.', 'I inferred the missing year from the archive index.'], 2, 'Alternative sources prevent a single-value inference.'),
  response(3, 'I thought the equipment grant covered maintenance contracts.', ['The maintenance company visits twice each year.', 'Equipment grants require an itemized budget.', 'I covered the instrument before leaving the room.', 'It funds initial installation, but recurring service needs another account.'], 3, 'The reply distinguishes eligible cost categories.'),
  response(4, 'May I bring a guest to the graduate colloquium?', ['Yes, if you register the visitor before noon.', 'The colloquium speaker studies public finance.', 'Guest parking is behind the administration building.', 'I brought the handouts from the copy center.'], 0, 'The answer grants permission conditionally.'),
  response(5, 'Where did you archive the uncompressed images?', ['Image compression reduced the transfer time.', 'In the restricted folder labeled by acquisition date.', 'The archive retains datasets for at least ten years.', 'I photographed the specimen from three angles.'], 1, 'The reply gives a precise storage location.'),
  response(6, 'Shouldn’t the control group receive the same reminder?', ['The control condition excludes the active training.', 'Reminder timing appears in the protocol appendix.', 'Yes, unless reminders themselves are part of the intervention.', 'I controlled the temperature during incubation.'], 2, 'Equivalent contact is needed unless it defines treatment.'),
  response(7, 'The bibliography software changed all the capitalization.', ['Capitalization conventions vary among publication styles.', 'The bibliography contains several translated titles.', 'I changed the heading after peer review.', 'Restore the original titles before applying the journal-specific rule.'], 3, 'Source accuracy should precede style transformation.'),
  response(8, 'Is this solvent compatible with the acrylic enclosure?', ['Only after a materials test on an inconspicuous sample.', 'The enclosure protects objects from airborne dust.', 'Solvent bottles are stored in a ventilated cabinet.', 'I compared the acrylic painting with an oil sketch.'], 0, 'Compatibility requires empirical testing.'),
  response(9, 'Why did the confidence interval become asymmetric?', ['The interval is plotted with vertical end caps.', 'The estimate was transformed back from a logarithmic scale.', 'I became confident after checking the derivation.', 'Asymmetry appears in many historical distributions.'], 1, 'Back-transformation can distort symmetric limits.'),
  response(10, 'Can the archived interview be translated publicly?', ['The interview discusses neighborhood redevelopment.', 'Translation may change culturally specific expressions.', 'Only if the access agreement permits a derivative text.', 'I translated the abstract for the conference program.'], 2, 'A derivative requires its own authorization.'),
  response(11, 'I cannot find the preregistered exclusion threshold.', ['The threshold excluded observations below detection.', 'Preregistration separates planned and exploratory analysis.', 'The file was uploaded before participant recruitment.', 'Open the timestamped supplement rather than the editable project page.'], 3, 'The immutable record contains the original plan.'),
  response(12, 'Has the replacement filter reduced the airflow alarm?', ['For now, but engineering is monitoring the pressure trend.', 'The filter captures particles above a specified diameter.', 'Airflow alarms sound at both laboratory entrances.', 'I replaced an unclear phrase in the methods section.'], 0, 'The response reports provisional improvement and monitoring.'),
  response(13, 'When should we thaw the reference cultures?', ['Reference strains are stored in duplicate freezers.', 'The protocol says forty-eight hours before inoculation.', 'I referred the question to the biosafety officer.', 'Cultures grow at different rates in liquid media.'], 1, 'The protocol supplies a relative time.'),
  response(14, 'Would a clustered standard error be appropriate here?', ['The standard error appears in parentheses below each estimate.', 'Clusters were sampled from several districts.', 'Possibly, if observations share unmodeled dependence within schools.', 'I clustered the labels by collection location.'], 2, 'Within-group dependence motivates cluster-robust inference.'),
  response(15, 'Who approved opening the sealed deposition box?', ['The box contains materials from the northern trench.', 'Approval records are stored with conservation reports.', 'We opened the gallery after the alarm test.', 'The excavation director and collections registrar signed jointly.'], 3, 'The responsible signatories are named.'),
  response(16, 'This satellite image looks sharper than the earlier one.', ['Check pixel size and processing history before assuming resolution improved.', 'The satellite crosses the equator twice during each orbit.', 'Earlier images are arranged chronologically in the catalog.', 'I sharpened the argument in the final paragraph.'], 0, 'Appearance can reflect processing rather than sensor resolution.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-replicates', 'Listen to a Conversation', '실험 설계', 'C1', 'Student: I measured each leaf three times, so I reported ninety replicates from thirty plants. Advisor: Those are repeated measurements, not ninety independent biological units. Student: Should I average within each leaf? Advisor: Possibly, but first model the hierarchy: readings are nested in leaves and leaves in plants. Your uncertainty must reflect where independent sampling occurred.', [
    ['What error did the student make?', ['Treating repeated readings as independent biological samples', 'Averaging measurements before calibrating the instrument', 'Sampling too many separate plants for a hierarchical model', 'Reporting fewer instrument readings than were actually recorded'], 0, 'Measurement replication does not create new independent organisms.'],
    ['What does the advisor recommend?', ['Represent the nested sampling structure when estimating uncertainty', 'Delete all but one plant to balance the dataset', 'Use the number of readings as the sole sample-size measure', 'Assume leaves from one plant have no relationship'], 0, 'Dependence follows the design hierarchy.'],
  ]),
  ...listeningGroup('conversation-acoustic', 'Listen to a Conversation', '강의실 음향', 'B2', 'Instructor: Students in the back say my microphone is loud but unclear. Technician: Increasing volume will not fix reflections from the bare rear wall. Instructor: Can we replace the sound system? Technician: First add temporary absorptive panels and move the speakers forward. If speech clarity improves, we will know the room acoustics are the main issue.', [
    ['Why does the technician reject simply raising the volume?', ['Reflected sound can reduce intelligibility even when loudness is adequate', 'The microphone cannot produce sound in the rear half of the room', 'Students requested quieter speech instead of clearer speech', 'Temporary panels increase electronic amplification automatically'], 0, 'Reverberation, not insufficient level, is suspected.'],
    ['What is the purpose of the temporary changes?', ['They provide a diagnostic test before costly equipment replacement', 'They permanently redesign the entire lecture hall', 'They ensure reflections reach the back wall more strongly', 'They allow the instructor to stop using speech amplification'], 0, 'A reversible intervention identifies the limiting factor.'],
  ]),
  ...listeningGroup('conversation-weights', 'Listen to a Conversation', '표본 가중치', 'C1', 'Analyst: The survey sample has the same number of rural and urban respondents, so I compared raw percentages. Statistician: But the population is mostly urban, and selection probabilities differed. Analyst: Then the balanced sample is a problem? Statistician: It is useful for subgroup precision, but population estimates need design weights. Also inspect whether nonresponse within each group requires an additional adjustment.', [
    ['Why are raw percentages unsuitable for the population estimate?', ['The sample composition does not mirror unequal selection and population shares', 'Rural respondents cannot answer the same survey as urban respondents', 'Subgroup precision declines whenever a sample is deliberately balanced', 'Design weights remove all observations from the smaller group'], 0, 'Oversampling must be accounted for in aggregation.'],
    ['What additional issue should the analyst examine?', ['Whether differential nonresponse remains within the sampled groups', 'Whether every respondent selected the identical answer option', 'Whether urban population size can be made equal to rural size', 'Whether subgroup analysis should exclude all survey weights'], 0, 'Selection correction may not address response propensity.'],
  ]),
  ...listeningGroup('conversation-provenance', 'Listen to a Conversation', '박물관 출처 조사', 'C1', 'Curator: The donor said this mask was collected in 1928, but the accession ledger lists 1936. Researcher: The dates may refer to acquisition by different owners. Do we have shipping labels or sale records? Curator: Only a photograph with an undated inscription. Researcher: Then record both claims and their sources. Do not merge them into one precise history until we can connect the transfers.', [
    ['Why might both dates be meaningful?', ['They may describe separate stages in the object’s chain of ownership', 'The accession ledger always records the date an object was manufactured', 'Donors are required to use a different calendar from museums', 'An undated photograph proves the earlier claim is exact'], 0, 'Collection and institutional accession can occur at different times.'],
    ['How should the conflicting evidence be documented?', ['Keep each claim attributed and preserve uncertainty about the intervening history', 'Average the two years and publish the midpoint as definitive', 'Discard the ledger because oral information is necessarily older', 'Add a date to the photograph based solely on handwriting style'], 0, 'Source-specific claims should not be falsely reconciled.'],
  ]),
  ...listeningGroup('conversation-storm', 'Listen to a Conversation', '생태 현장조사', 'B2', 'Student: The storm washed away three insect traps, so our sites have different sampling durations. Ecologist: Do not divide every count by days and assume the catch rate was constant. Activity changed with the weather. Student: Can the affected sites still be used? Ecologist: Yes, if we model exposure time and weather together and report how conclusions change when those sites are excluded.', [
    ['Why is a simple count-per-day correction questionable?', ['The storm likely changed insect activity as well as trap duration', 'Every trap collected exactly the same number before the storm', 'Sampling duration cannot be included in an ecological model', 'Weather affects only the physical labels on field equipment'], 0, 'Exposure and the biological process changed simultaneously.'],
    ['What robustness check is proposed?', ['Repeat the analysis without the sites whose traps were lost', 'Replace missing counts with the highest intact-site total', 'Assume the storm occurred after all sampling ended', 'Combine every site into one unweighted observation'], 0, 'Exclusion reveals dependence on compromised sites.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-fumehood', 'Listen to an Announcement', '실험실 환기', 'C1', 'Annual fume-hood testing begins Wednesday. A red tag means the hood has failed and must remain empty; a yellow tag permits storage but prohibits active chemical work until adjustment is complete. Testing staff will not dispose of materials left inside. Owners must secure or relocate unstable reactions before their floor’s scheduled window.', [
    ['What activity is allowed at a yellow-tagged hood?', ['Passive storage without conducting chemical procedures', 'Continuation of every reaction already placed inside', 'Disposal of unclaimed chemicals by the testing staff', 'Independent adjustment of the ventilation controls'], 0, 'Yellow status restricts active work but not storage.'],
    ['What must researchers do before testing reaches their floor?', ['Stabilize or move any reaction that cannot safely be interrupted', 'Remove the official tag from a previously failed hood', 'Ask testing staff to identify ownership of all materials', 'Begin new experiments so airflow can be measured under load'], 0, 'Users remain responsible for active materials.'],
  ]),
  ...listeningGroup('announcement-archive-hours', 'Listen to an Announcement', '자료실 운영', 'B2', 'During inventory week, the map archive opens at noon rather than nine. Morning appointments already confirmed will take place in the reference room, where staff will deliver requested folders. Walk-in visitors must wait until noon, and no same-day retrieval requests will be accepted after three.', [
    ['Who may still receive service during the morning?', ['Researchers holding previously confirmed appointments', 'Any walk-in visitor arriving before the inventory begins', 'People submitting a same-day request after three', 'Only staff who intend to remove maps permanently'], 0, 'Existing appointments are honored in another room.'],
    ['What restriction applies after three o’clock?', ['New requests for retrieval that same day are no longer accepted', 'The reference room immediately closes to confirmed researchers', 'Every delivered folder must remain overnight', 'Inventory work moves from the archive to the map gallery'], 0, 'The cutoff concerns same-day pulls.'],
  ]),
  ...listeningGroup('announcement-sequencer', 'Listen to an Announcement', '유전체 장비', 'C1', 'The sequencing core will update its sample-index software Friday. Index designs approved under the old version remain valid for runs already scheduled, but unscheduled plates must be rechecked for newly identified barcode conflicts. Submit the plate map, not just the barcode list, because neighboring wells and pooling groups affect the review.', [
    ['Which samples require a new index review?', ['Unscheduled plates designed before the software update', 'Every run that has already been assigned a date', 'Only plates created after all barcode conflicts are removed', 'Samples with no relationship to pooling arrangements'], 0, 'Grandfathering applies only to scheduled runs.'],
    ['Why is the full plate map required?', ['Index compatibility depends partly on well and pooling context', 'Barcode sequences are never included in a plate map', 'The software update changes the physical volume of each well', 'Scheduled runs cannot contain neighboring samples'], 0, 'Arrangement provides information missing from a list.'],
  ]),
  ...listeningGroup('announcement-debate', 'Listen to an Announcement', '공개 토론', 'B2', 'Tonight’s policy debate begins at seven. Audience questions must be submitted electronically by six forty-five so moderators can combine duplicates and screen personal attacks. Submitting a question does not guarantee it will be asked. A quiet viewing room with live captions is available next door and requires no separate ticket.', [
    ['Why is there an advance deadline for audience questions?', ['Moderators need time to consolidate and review submissions', 'Panelists receive every question before entering the building', 'Electronic forms stop functioning once captions begin', 'The quiet room admits only people who submit questions'], 0, 'Review occurs before the debate starts.'],
    ['What is stated about the adjacent viewing room?', ['It offers captioned access without additional admission', 'It opens only after the main debate has finished', 'It permits audience members to question panelists privately', 'It requires a second ticket purchased by six forty-five'], 0, 'The room is an accessible parallel venue.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-groundwater', 'Listen to an Academic Talk', '수문지질학', 'C1', 'Groundwater age is not simply the time since every molecule entered an aquifer. A pumped sample mixes water traveling along paths of different lengths. Tracers such as tritium or dissolved gases respond to different age ranges and can be altered by decay, gas exchange, or rock interaction. An apparent tracer age therefore depends on a model of mixing and transport. Combining tracers helps constrain that model, while well depth and pumping rate influence which flow paths contribute to the sample.', [
    ['Why is one pumped sample likely to contain mixed ages?', ['The well draws water that followed multiple subsurface travel paths', 'Every tracer resets to zero when it enters an aquifer', 'Rock interaction forces all molecules to move at one speed', 'Well depth determines the exact entry year of each molecule'], 0, 'A well integrates contributions rather than isolating one parcel.'],
    ['Why are several tracers useful?', ['Their different sensitivities can restrict plausible transport and mixing histories', 'Combining them prevents radioactive decay from occurring', 'Every tracer measures an identical age range without assumptions', 'They eliminate effects of pumping rate on sampled flow paths'], 0, 'Complementary tracer behavior improves identification.'],
  ]),
  ...listeningGroup('talk-auctions', 'Listen to an Academic Talk', '행동경제학', 'C1', 'In a common-value auction, the item has roughly the same underlying value to every bidder, but estimates differ. The winner tends to be the bidder with the most optimistic estimate. If bidders ignore this selection effect, the winner may pay more than the item is worth, a pattern called the winner’s curse. Experienced bidders often shade their bids downward, especially as the number of competitors grows. The curse is not mere regret after losing; it arises from conditioning on having submitted the highest estimate.', [
    ['Why is the winning estimate systematically suspect?', ['Winning selects the bidder whose valuation error was likely unusually optimistic', 'The auctioneer reveals the true value only to losing bidders', 'Common-value items provide different physical benefits to each buyer', 'More competitors guarantee that every estimate becomes accurate'], 0, 'The maximum estimate contains selection bias.'],
    ['Why might bidders lower bids when participation increases?', ['More rivals make an extreme overestimate more likely to be the winner', 'Additional bidders reduce the underlying value of the item to zero', 'Bid shading ensures that the lowest estimate always wins', 'Experienced participants are prohibited from using value information'], 0, 'Competition intensifies the winner-selection problem.'],
  ]),
  ...listeningGroup('talk-mosaic', 'Listen to an Academic Talk', '미술고고학', 'B2', 'Ancient mosaics were assembled from small pieces of stone, glass, or ceramic called tesserae. Material and placement affected both color and reflected light. Floor mosaics needed durable surfaces and were viewed obliquely, whereas wall mosaics could use angled glass to catch illumination. Modern reconstructions sometimes make every row perfectly even, but slight original variations may have been intentional optical adjustments rather than poor workmanship.', [
    ['Why could wall mosaics use angled glass pieces?', ['Their orientation redirected available light toward viewers', 'Glass made floor surfaces more resistant to foot traffic', 'Angled pieces eliminated the need for any binding mortar', 'Walls were always viewed from directly above'], 0, 'Tilt changes reflection from a vertical surface.'],
    ['What caution is raised about regular reconstructions?', ['Uniform alignment may erase purposeful adjustments in the historical work', 'Ancient craftspeople lacked any control over tessera placement', 'All uneven rows prove that a mosaic was repaired recently', 'Modern materials cannot reproduce visible color'], 0, 'Variation can encode optical intention.'],
  ]),
  ...listeningGroup('talk-priming', 'Listen to an Academic Talk', '인지심리학', 'C1', 'Semantic priming occurs when processing one item influences response to a related item. People may recognize “nurse” faster after “doctor” than after an unrelated word. The effect can reflect spreading activation, learned prediction, or strategic expectations, depending on timing and task. A very brief prime may reduce conscious strategy, but it does not automatically isolate one mechanism. Researchers vary the interval, proportion of related trials, and response requirements, then compare models rather than treating faster reaction time as a direct meter of association strength.', [
    ['Why does a short prime not identify a unique mechanism?', ['Several automatic processes can still generate similar response-time facilitation', 'Brief presentations prevent the visual system from processing any word', 'Strategic expectation is the only possible source of priming', 'Association strength can be read directly from one reaction time'], 0, 'Reducing one explanation does not establish another exclusively.'],
    ['Why manipulate the proportion of related trials?', ['It helps reveal whether participants develop predictive task strategies', 'It makes every target word equally frequent in the language', 'It prevents learned relationships from affecting recognition', 'It converts reaction time into a measure of neural anatomy'], 0, 'Trial structure changes the usefulness of expectation.'],
  ]),
  ...listeningGroup('talk-river-avulsion', 'Listen to an Academic Talk', '퇴적지형학', 'C1', 'A river avulsion occurs when a channel abandons its course and establishes a new one on the floodplain. As sediment raises the existing bed, a shorter or steeper route may become favorable. A flood can trigger the switch, but long-term aggradation prepared the instability. Levees may prevent small diversions while allowing elevation differences to grow, potentially making a later failure more abrupt. Geologists reconstruct former channels from sediment, topography, and dating rather than assuming every abandoned channel formed during one catastrophic event.', [
    ['What distinction does the lecturer make about floods?', ['A flood may trigger a switch whose underlying conditions developed gradually', 'Floodwater always creates a new channel without prior sediment buildup', 'Long-term aggradation lowers the active bed below its floodplain', 'Avulsion can occur only where artificial levees are absent'], 0, 'Trigger and preconditioning operate on different timescales.'],
    ['How can levees increase eventual disruption?', ['They can postpone minor shifts while the perched channel becomes more unstable', 'They remove all sediment from the river before deposition', 'They guarantee that abandoned channels share one date', 'They make every alternative route longer and flatter'], 0, 'Suppression can accumulate the gradient for a larger failure.'],
  ]),
  ...listeningGroup('talk-standards', 'Listen to an Academic Talk', '기술사', 'C1', 'Technical standards can create compatibility among products made by different firms. Their value often grows as more users adopt them, but early choices may persist even when another design has advantages. Switching requires coordinated replacement, training, and agreement across organizations. This path dependence does not mean history makes improvement impossible. Adapters, backward compatibility, or gradual migration can lower transition costs. Analysts compare technical performance with institutional incentives rather than assuming the dominant standard won solely because it was superior.', [
    ['Why can an established standard survive despite a better alternative?', ['Coordinated switching costs can outweigh individual gains from changing', 'Compatibility becomes less valuable as adoption expands', 'Organizations are legally unable to train workers on new systems', 'Technical performance never influences standard selection'], 0, 'Network coordination creates inertia.'],
    ['How can backward compatibility support transition?', ['It lets new components interact with existing investments during migration', 'It requires every organization to replace equipment simultaneously', 'It proves the old standard was technically optimal', 'It removes the need for agreement about future specifications'], 0, 'Interoperability reduces the cost of staged adoption.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the specimen rejected?', 'Much as the team wanted to retain it', ['the missing label', 'made it impossible', 'to establish', 'a secure provenance'], 'f14-much-as-concessive'],
  ['What did the simulation reveal?', 'What the simplified model failed to capture', ['was how strongly', 'small delays', 'could amplify', 'network congestion'], 'f14-wh-cleft-complement'],
  ['Could the policy have worked elsewhere?', 'Had local enforcement been more consistent', ['the same rule', 'might well have', 'produced', 'a different outcome'], 'f14-inverted-counterfactual-modal'],
  ['Why did the editor request another analysis?', 'The association was too sensitive to the exclusion rule', ['for the conclusion', 'to be considered', 'robust without', 'a specification check'], 'f14-too-adjective-for-infinitive'],
  ['When was the mismatch discovered?', 'It was not until the files were decrypted', ['that investigators', 'could compare', 'the identifiers', 'record by record'], 'f14-it-cleft-not-until'],
  ['What complicates the causal claim?', 'Besides having selected their own treatment', ['participants differed', 'in several traits', 'likely to affect', 'the outcome'], 'f14-besides-perfect-gerund'],
  ['How convincing was the evidence?', 'Such was the consistency across laboratories', ['that even', 'initially skeptical reviewers', 'accepted', 'the central finding'], 'f14-such-inversion-result'],
  ['Why preserve the obsolete instrument?', 'The device is valuable insofar as it documents', ['how researchers', 'once translated', 'physical signals', 'into numerical records'], 'f14-insofar-as-clause'],
  ['What condition did the board impose?', 'The board approved the trial on condition that no participant', ['be enrolled', 'before the revised', 'consent procedure', 'had been tested'], 'f14-on-condition-mandative'],
  ['Why compare multiple archives?', 'Rarely does a single collection contain enough evidence', ['to determine', 'whether the silence', 'was accidental', 'or politically imposed'], 'f14-rarely-inversion-whether'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '공동 장비 예약', 'C1', 420), instruction: '충돌의 근거와 영향, 공정한 해결 절차를 구체적으로 제안하세요.', prompt: 'You discover that a laboratory group has reserved nearly every evening slot on a shared instrument by using several members’ accounts, although the booking policy limits each project’s weekly time. Write to the facility manager. Explain the pattern and its effect on your work, provide evidence you can share, and request a fair corrective arrangement.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '문화유산 디지털화', 'C1', 600), instruction: '상충하는 가치와 실제 시행 조건을 평가해 자신의 논지를 발전시키세요.', prompt: 'Professor Mensah: Should museums make high-resolution digital copies of culturally sensitive objects freely available online?', passage: 'Elena: Broad digital access supports education and reduces physical handling of fragile objects.\nTariq: Unrestricted images can violate community protocols and enable commercial misuse without consent.' })

const repeatSentences = ['Welcome to the environmental sampling preparation room.', 'Verify the bottle code against the printed field schedule.', 'Wear powder-free gloves before handling any sterile container.', 'Keep travel blanks sealed beside the samples during transportation.', 'Record the time and weather before collecting water from each location.', 'Place every filled bottle upright inside the chilled secondary container.', 'After returning, transfer the samples with the custody form so laboratory staff can check the seals, temperatures, and requested analyses.']
const interviewQuestions = ['Describe a technology standard that affects products or services you use.', 'What benefits come from many people following the same standard?', 'When might society benefit from replacing an established standard?', 'Who should bear the cost when a transition benefits future users more than current ones?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '환경 시료 채취', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f14-repeat', scenarioId: 'f14-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '기술 표준과 전환', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f14-interview', scenarioId: 'f14-interview', sequenceIndex })),
]

export const AUTHORED_FORM_14_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_14_IDS = AUTHORED_FORM_14_ITEMS.map((item) => item.id)
