import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f10')

const reading: BaseItem[] = [
  cloze('cloze-quorum', '미생물학', 'C1', 'Some bacteria coordinate behavior through quorum sensing. Cells rel___ signaling molecules whose concentration generally rises as a population becomes denser. When the signal exc___ a threshold, receptors trigger changes in gene expression across many cells. This can coord___ light production, biofilm formation, or secretion of enzymes. The system does not count cells directly; concentration also dep___ on diffusion, flow, and chemical breakdown. A signal may therefore accum___ in a confined space even when cell number is modest. Researchers disr___ signaling genes to test causal roles, but mutations can have unintended effects. They comp___ genetic, chemical, and imaging evidence. Quorum sensing can be expl___ as a drug target, yet blocking communication may sel___ for resistant strategies. Ecological context must be cons___ before generalizing laboratory findings.', 'ease|eeds|inate|ends|ulate|upt|bine|ored|ect|idered'),
  cloze('cloze-parchment', '문서보존학', 'C1', 'Parchment is made from animal skin whose collagen fibers respond strongly to humidity. When moisture changes, a sheet may exp___, contract, or distort unevenly. Conservators avoid flattening it with force because tension can tear weak areas or dam___ ink. Instead, they sta___ the environment and introduce controlled humidity only when necessary. Historical repairs are evaluated before rem___, since they may contain evidence about earlier use. Light exposure is lim___ to slow chemical change. Imaging can rev___ text hidden by folds without opening them fully. Every treatment is doc___ and designed to remain as rev___ as possible. The aim is not to make the document look new but to pre___ its material history while enab___ safe study.', 'and|age|bilize|oval|ited|eal|umented|ersible|serve|ling'),
  cloze('cloze-lakes', '담수생태학', 'B2', 'Deep lakes often form layers because warm water is less dense than cold water. During summer, a warm surface layer may remain sep___ from cooler deep water. Wind mixes the surface but may not pen___ the boundary between layers. Organisms in deep water con___ oxygen as they decompose sinking material. If mixing is limited, oxygen can dec___ while nutrients accum___ below. Seasonal cooling reduces the density difference and allows the lake to tur___ over. Climate warming can len___ stratification and alter habitat. Researchers meas___ temperature and oxygen at many depths rather than relying on a surface sample. Nutrient reduction can imp___ water quality, but its effects may take time because sediments sto___ phosphorus from earlier pollution.', 'arate|etrate|sume|line|ulate|n|gthen|ure|rove|re'),
  daily('daily-sequencer', '유전체 시설', 'B2', 'Sequencing reservations include one standard quality check. Libraries that fail because their concentration is below the published minimum may be rerun only after the user prepares a new library. A failed run caused by an instrument fault is repeated without another usage charge.', ['When is a repeat run provided without an added instrument fee?', ['When facility equipment caused the failure', 'When the submitted library was too dilute', 'Whenever a user wants a higher read count', 'Before any quality check has been performed'], 0, 'The facility assumes cost only for its own technical failure.']),
  daily('daily-water-sample', '환경 분석', 'C1', 'Drinking-water samples for bacterial analysis must reach the laboratory within six hours and remain chilled without freezing. A sample arriving late may still be tested for mineral content, but its microbiological result would not be valid. Record collection time on both the bottle and submission form.', ['What can the laboratory still do with a sample delivered after the microbial limit?', ['Analyze appropriate nonbiological properties', 'Issue a valid bacterial count without qualification', 'Recover the original collection time from temperature alone', 'Freeze it and restart the six-hour interval'], 0, 'Late arrival invalidates one analysis, not necessarily every test.']),
  daily('daily-costume-archive', '공연 기록', 'B2', 'Historic costumes may be examined on padded tables but not worn. Researchers requesting an interior construction view should ask staff to position the garment; turning it inside out can strain seams. Measurement tapes and pencils are provided, while adhesive notes are prohibited.', ['How should a researcher inspect the inside of a costume?', ['Have trained staff reposition it safely', 'Wear it briefly to expose the lining', 'Reverse it without support on the table', 'Attach notes directly to fragile seams'], 0, 'Staff handling reduces stress on historic construction.']),
  daily('daily-waitlist', '수강 신청', 'B1', 'The environmental law course uses an automatic waitlist until the first class. After that meeting, students still seeking a place must attend and obtain an instructor code if a seat opens. Remaining on the electronic list alone will not enroll anyone after the first day.', ['What must a waitlisted student do after the first class begins?', ['Attend and seek an instructor code if space becomes available', 'Rely exclusively on the automatic list', 'Register without regard to capacity', 'Request a code before attending any meeting'], 0, 'The enrollment procedure changes after the opening class.']),
  daily('daily-chemical-order', '연구 구매', 'C1', 'Restricted chemicals require safety approval before a purchase order is submitted. Adding approval after delivery does not correct an unauthorized purchase. If a supplier offers a substitute concentration, the requester must update the hazard review even when the total quantity and chemical name remain unchanged.', ['What should happen when the vendor proposes a different concentration?', ['Revise the safety review before accepting the substitution', 'Accept it because the chemical name is unchanged', 'Wait until delivery to request original approval', 'Increase the quantity without changing documentation'], 0, 'Concentration changes exposure and handling risk.']),
  daily('daily-studio-key', '예술 시설', 'B2', 'Graduate studio keys remain active during breaks only for students listed on a faculty-sponsored access roster. Paying the studio fee does not itself extend access. Sponsors submit rosters one week before the break; security cannot add names at the door.', ['What ensures break-period studio entry?', ['Inclusion on the advance faculty roster', 'Payment of an ordinary studio fee alone', 'A request made to security upon arrival', 'Possession of any expired graduate key'], 0, 'Authorization depends on the submitted roster.']),
  daily('daily-survey-incentive', '연구 참여', 'C1', 'Participants receive the base survey payment even if they skip optional questions. A completion bonus applies only after the attention check and final submission page are reached, but it cannot depend on whether answers support the research hypothesis. Withdrawn participants keep compensation already earned.', ['Which condition may legitimately determine the bonus?', ['Completion of specified procedural steps', 'Agreement with the investigators’ prediction', 'Disclosure of every optional personal detail', 'Forfeiture of all payment after withdrawal'], 0, 'Compensation may track completion, not desired content.']),
  daily('daily-flute', '악기 대여', 'B1', 'Loaned flutes should be returned with the case open so staff can inspect moisture pads. Do not clean pads with alcohol. If the instrument was exposed to rain, inform staff at return even when it appears dry.', ['What should a borrower report at return?', ['Any exposure of the instrument to rain', 'Only damage visible after alcohol cleaning', 'Whether the closed case fits in a locker', 'The number of pieces performed'], 0, 'Moisture exposure matters even without obvious damage.']),
  daily('daily-rooftop', '건물 접근', 'B2', 'The rooftop weather station is reached through a locked mechanical room. Approved researchers may reserve access, but a facilities escort is required during scheduled ventilation maintenance. The reservation page shows maintenance blocks in orange; booking an adjacent open time does not authorize crossing the room during a block.', ['What is required when access overlaps ventilation work?', ['A facilities escort through the mechanical area', 'Only a reservation in the nearest open slot', 'Permission to bypass the locked room', 'Cancellation of all weather observations for the term'], 0, 'Maintenance introduces a supervised-access requirement.']),
  daily('daily-late-poster', '학회 운영', 'B2', 'Poster files submitted after the printing deadline are not included in the group order. Authors may arrange individual printing at their own cost and still present if the poster meets size requirements. The conference office cannot accept delivery from printers after registration closes Friday evening.', ['What option remains for an author who missed group printing?', ['Purchase compliant printing independently before delivery closes', 'Add the file retroactively to the completed group order', 'Present without observing the poster dimensions', 'Deliver the poster after registration has closed'], 0, 'Independent production remains possible within later logistical limits.']),
  ...readingGroup('academic-its', '공중보건 평가', 'C1', 'An interrupted time-series study examines repeated observations before and after an intervention. It can estimate whether the outcome’s level or slope changed when a policy began. A single before-and-after comparison cannot distinguish intervention effects from an existing trend, whereas many pre-policy points characterize that trend. The design still faces threats: another event at the same time may cause the break, seasonal cycles may be mistaken for change, and anticipation can shift behavior before the official date. Researchers model autocorrelation, inspect alternative intervention dates, and, when possible, include a comparison series unaffected by the policy.', [
    ['Why are numerous pre-policy observations valuable?', ['They reveal the trajectory that was already underway', 'They guarantee no simultaneous event occurred', 'They remove all correlation between adjacent measurements', 'They make seasonal adjustment unnecessary'], 0, 'Baseline trend is needed to interpret a later break.'],
    ['What is the main threat from a simultaneous event?', ['The observed discontinuity may be wrongly attributed to the target policy', 'The pre-policy slope becomes impossible to estimate', 'Every comparison series receives identical treatment', 'Autocorrelation disappears after the intervention'], 0, 'Co-occurring causes confound the timing-based inference.'],
    ['What might an artificial intervention-date test reveal?', ['Similar breaks at other dates would weaken a unique policy explanation', 'The official date is always recorded incorrectly', 'Seasonality can be ignored if one placebo fails', 'Anticipation occurs only after implementation'], 0, 'Placebo timing assesses whether the chosen breakpoint is distinctive.'],
  ]),
  ...readingGroup('academic-tools', '동물인지', 'C1', 'Tool use is often defined as manipulating an external object to alter another object, organism, or the user’s own condition. The definition includes a bird using a twig to extract insects but may exclude a nest that functions after construction without continued manipulation. Observing tool use does not by itself reveal advanced planning. An animal may learn through trial and error or follow an inherited behavioral tendency. Researchers vary access to materials, present unfamiliar problems, and examine whether an individual prepares a tool before the relevant need is visible. Performance must also be compared with the animal’s ordinary motor abilities.', [
    ['Why does tool use not automatically demonstrate foresight?', ['The behavior may arise through learning or predisposition without representing a future goal', 'Every external object requires explicit planning', 'Inherited behavior cannot involve object manipulation', 'Trial and error occurs only after a tool succeeds'], 0, 'The same action can be generated by simpler mechanisms.'],
    ['What would provide stronger evidence of planning?', ['Preparing an appropriate object before the problem is immediately present', 'Repeating a familiar motion after receiving food', 'Choosing the material most common in the enclosure', 'Building a structure that is never manipulated again'], 0, 'Advance preparation separates future-directed selection from immediate response.'],
  ]),
  ...readingGroup('academic-obsidian', '고고학과 지구화학', 'C1', 'Obsidian forms when silica-rich lava cools rapidly into volcanic glass. Deposits often have distinctive trace-element combinations, allowing artifacts to be matched chemically with geological sources. A source match shows where the raw material originated, not who transported it or whether the artifact moved directly. A blade found far away may have passed through several communities, and finished objects can be recycled. Archaeologists examine production debris, settlement routes, artifact form, and chronological context to distinguish direct procurement from exchange. Sampling many objects is important because one prestigious item may not represent ordinary trade.', [
    ['What can trace-element matching establish most directly?', ['The geological origin of an artifact’s raw glass', 'The identity of every person who exchanged it', 'A direct route from quarry to final settlement', 'Whether the artifact was never recycled'], 0, 'Chemistry identifies source material, not the social pathway.'],
    ['Why is production debris relevant?', ['It may indicate where raw material was worked rather than merely consumed', 'It guarantees that finished objects were made at the volcano', 'It removes the need for chronological evidence', 'It proves that no exchange network existed'], 0, 'Waste locates stages of manufacture and helps reconstruct movement.'],
    ['Why should archaeologists analyze more than an exceptional object?', ['Rare prestige goods may follow exchange patterns unlike everyday material', 'Trace elements occur only in ordinary tools', 'A large sample makes source chemistry irrelevant', 'Prestigious artifacts cannot be dated'], 0, 'Broader sampling prevents an unusual pathway from being generalized.'],
  ]),
  ...readingGroup('academic-atmosphere', '행성과학', 'C1', 'Scientists infer an exoplanet’s atmosphere by measuring starlight filtered through it during a transit. Molecules absorb particular wavelengths, leaving small features in the spectrum. Clouds or hazes can flatten those features, and stellar spots can imitate a planetary signal because the star’s surface is not uniform. Different combinations of temperature, composition, and cloud height may fit the same data. Researchers observe multiple transits, model the host star, and report a range of atmospheric scenarios. Detecting a molecule is not equivalent to detecting life, since many biological and nonbiological processes produce the same gas.', [
    ['Why can atmospheric retrieval yield several plausible solutions?', ['Different physical combinations can create similar spectral features', 'Every molecule absorbs exactly the same wavelength', 'Clouds always make absorption stronger', 'A transit directly photographs atmospheric layers'], 0, 'The inverse problem is degenerate under limited data.'],
    ['Why must host-star activity be modeled?', ['Surface variation on the star can masquerade as planetary absorption', 'Stellar spots exist only after a planet transits', 'The star has no effect on measured light', 'Planetary clouds remove all stellar variation'], 0, 'The background light source is itself spatially and temporally variable.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you see whether the rehearsal piano was unlocked?', ['I’ll ask the stage manager who has the key.', 'The piano was built in Vienna.', 'Rehearsal begins after the lecture.', 'I unlocked the spreadsheet cells.'], 0, 'The reply initiates a relevant check.'),
  response(1, 'Why was my equipment request placed on hold?', ['The request includes two camera lenses.', 'Your safety checkout expired last month.', 'I held the container upright.', 'Equipment can be reserved online.'], 1, 'Expired authorization directly explains the hold.'),
  response(2, 'Have the water samples reached the analytical lab?', ['The laboratory measures several nutrients.', 'Samples were collected downstream.', 'Yes, and the receiving temperatures were acceptable.', 'I reached the trail before noon.'], 2, 'The answer confirms both arrival and condition.'),
  response(3, 'Would you be able to proofread the revised caption?', ['The proof is printed on glossy paper.', 'Captions help explain visual evidence.', 'I revised the budget instead.', 'Certainly; send the final figure with it.'], 3, 'The response agrees and asks for necessary context.'),
  response(4, 'I thought the dormitory desk accepted oversized parcels.', ['It accepts ordinary boxes, but large deliveries need resident pickup.', 'The desk closes during the staff meeting.', 'Oversized figures extend beyond the margin.', 'I accepted the invitation yesterday.'], 0, 'The reply corrects the scope of service.'),
  response(5, 'Where can I dispose of this cracked glass pipette?', ['The pipette measures small liquid volumes.', 'In the rigid sharps container beside the sink.', 'I disposed of the old draft.', 'Cracks can change measurement accuracy.'], 1, 'The answer identifies the safe waste stream.'),
  response(6, 'Shouldn’t the control interview last the same amount of time?', ['The interview room is available for one hour.', 'Control conditions should isolate the treatment.', 'Yes, unless duration itself is the intended manipulation.', 'I lasted until the end of the workshop.'], 2, 'Timing should match unless explicitly experimental.'),
  response(7, 'The online map shows the footpath crossing private land.', ['Private land surrounds the northern reserve.', 'The crossing is marked with a dashed line.', 'I mapped the survey points yesterday.', 'Check the official access layer before planning the route.'], 3, 'An authoritative access source should resolve the conflict.'),
  response(8, 'Can I photograph the manuscript without the color target?', ['Only for reference; analytical images must include it.', 'The manuscript uses several ink colors.', 'Photography is discussed in the archive guide.', 'I targeted the central paragraph.'], 0, 'The response distinguishes casual and analytical use.'),
  response(9, 'Why did the system reject the revised participant code?', ['The system stores encrypted identifiers.', 'It contains a character outside the approved format.', 'I revised the coding manual.', 'Participants entered through another door.'], 1, 'A format violation explains rejection.'),
  response(10, 'Could measurement error attenuate this correlation?', ['The measurement device was purchased recently.', 'Correlation does not establish causation.', 'Yes, especially if the predictor is measured unreliably.', 'I attended the morning seminar.'], 2, 'Noise in a predictor can bias association toward zero.'),
  response(11, 'I can’t find the consent version used at the second site.', ['Consent was obtained before every interview.', 'The second site is near the harbor.', 'Version numbers appear in the footer.', 'Check the ethics amendment log and site binder.'], 3, 'The formal records track approved version use.'),
  response(12, 'Is the sculpture garden open after sunset?', ['No, the gates close when the museum building closes.', 'The sculpture is made from weathered steel.', 'Sunset occurs later in summer.', 'I opened the package carefully.'], 0, 'The answer gives the operating restriction.'),
  response(13, 'When will the edited interview transcript be ready?', ['The transcript contains forty pages.', 'The editor expects to finish by Monday.', 'I interviewed the candidate yesterday.', 'Readiness depends on careful review.'], 1, 'The reply supplies the expected completion time.'),
  response(14, 'Would a nonlinear trend fit the baseline better?', ['The trend appears in the upper panel.', 'Nonlinear models use several forms.', 'Perhaps, but we should justify it before examining the policy effect.', 'The baseline microphone is beside the drum.'], 2, 'Model choice should not be driven by post-treatment results.'),
  response(15, 'Who authorized removing the rare book from display?', ['The display case controls humidity.', 'Authorization is noted in the catalog.', 'Rare books require careful support.', 'The head conservator approved the temporary move.'], 3, 'The reply identifies the accountable specialist.'),
  response(16, 'The audio software normalized every clip to a different level.', ['Undo the batch process and apply one documented reference level.', 'The clips contain interviews from three sites.', 'Normalization can simplify a statistical model.', 'I documented the meeting in the minutes.'], 0, 'A common reference restores comparability.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-thesis-figure', 'Listen to a Conversation', '논문 작성', 'C1', 'Student: My thesis figure is unreadable when printed, even though it looks fine on screen. Designer: The labels are only seven points and the lines differ mainly by color. Increase the type size and add distinct dash patterns. Student: That may make the legend larger. Designer: Directly label the lines where possible. Also print a grayscale proof; accessibility should not depend on perfect color reproduction.', [
    ['Why does the screen view give insufficient evidence of quality?', ['Printing and color limitations expose features hidden on a display', 'Printed figures always use larger type than screens', 'Dash patterns cannot appear in a thesis', 'Legends are prohibited in grayscale documents'], 0, 'Output medium and color vision can change readability.'],
    ['What alternative to a large legend is proposed?', ['Place identifying text beside the data series themselves', 'Remove all labels from the lines', 'Use color as the only distinction', 'Reduce the figure to seven-point type'], 0, 'Direct labeling saves lookup and legend space.'],
  ]),
  ...listeningGroup('conversation-package', 'Listen to a Conversation', '기숙사 배송', 'B1', 'Resident: The tracking page says my package was delivered, but the residence desk has no record. Clerk: Some couriers mark items delivered when they reach the campus sorting center. Check whether the location says “Central Receiving.” Resident: It does. Clerk: Then it should arrive here tomorrow. If the status does not change by afternoon, submit the tracking number through our missing-package form.', [
    ['Why is the package not yet at the residence desk?', ['The courier’s delivery status refers to a central campus facility', 'The clerk returned it without recording it', 'The resident entered an invalid tracking number', 'The sorting center is inside the residence desk'], 1, 'The scan marks an intermediate campus delivery.'],
    ['What should the resident do if it remains missing tomorrow afternoon?', ['File the tracking information through the designated form', 'Ask the courier to mark it delivered again', 'Enter the central receiving room without permission', 'Remove the item from the desk record'], 1, 'The escalation process begins after the expected transfer window.'],
  ]),
  ...listeningGroup('conversation-sensors', 'Listen to a Conversation', '생태 모니터링', 'C1', 'Researcher: The soil sensors show a sudden moisture increase at midnight across every plot. Technician: Did it rain? Researcher: No, and the manual probes were unchanged this morning. Technician: A synchronized jump suggests the software applied a new calibration, not a real field event. Preserve the raw voltages, check the update log, and do not overwrite the converted values until we can reproduce the change.', [
    ['Why does the technician suspect a processing artifact?', ['All sensors shifted together without an independent environmental signal', 'Manual probes also recorded heavy rain', 'Each plot changed at a different random time', 'Calibration cannot alter converted readings'], 2, 'Synchronized change plus conflicting ground checks points to software.'],
    ['Why preserve raw voltages?', ['They allow the team to recompute values under verified calibration rules', 'They guarantee that soil moisture truly increased', 'They erase the effects of every sensor fault', 'They replace the need to examine software logs'], 2, 'Unprocessed measurements support reproducible correction.'],
  ]),
  ...listeningGroup('conversation-loan-art', 'Listen to a Conversation', '미술관 운영', 'B2', 'Curator: The loan agreement requires the painting to rest twenty-four hours after transport, but installation is scheduled tomorrow morning. Coordinator: The truck was delayed, so that rest period will not be complete. Curator: Then move the opening rehearsal, not the installation condition. Keep the crate in the climate-controlled room and record its arrival. We can hang the work tomorrow evening after the acclimation period.', [
    ['What constraint conflicts with the installation schedule?', ['The required acclimation time began later because transport was delayed', 'The gallery has no climate-controlled room', 'The painting must be rehearsed before transport', 'The agreement permits immediate uncrating'], 3, 'Late arrival pushes completion of the rest period.'],
    ['What plan preserves the loan condition?', ['Adjust the rehearsal and install only after acclimation', 'Open the crate immediately to regain time', 'Shorten the recorded transport duration', 'Move the painting into an uncontrolled hallway'], 3, 'The event schedule changes, not the conservation requirement.'],
  ]),
  ...listeningGroup('conversation-prerecord', 'Listen to a Conversation', '온라인 강의', 'B2', 'Instructor: My prerecorded lecture refers to a reading I removed from the course. Editor: We can cut that sentence, but the next example also depends on the reading. Instructor: Could we add a caption instead? Editor: A caption will not supply enough context. Record a two-minute replacement explaining the example independently. I will match the audio level and insert it between the existing slides.', [
    ['Why is deleting one sentence inadequate?', ['A later example still assumes knowledge of the removed reading', 'The lecture contains no editable audio', 'Captions cannot display any text', 'The instructor must restore every old reading'], 0, 'The dependency extends beyond the explicit reference.'],
    ['How will the editor preserve continuity?', ['Insert a self-contained recorded explanation with matched sound', 'Replace the entire lecture with captions', 'Leave a silent gap between unrelated slides', 'Increase the volume of the original reference'], 1, 'A short replacement resolves context and production consistency.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-air', 'Listen to an Announcement', '환경 안전', 'B2', 'Outdoor athletic practices are canceled until two because smoke has raised the air-quality index. Indoor facilities remain open with filtered ventilation. Coaches should not move canceled teams indoors without a reservation, since the field house is already assigned to scheduled classes. Air quality will be checked again at noon.', [
    ['What may coaches not do automatically?', ['Relocate outdoor teams into already scheduled indoor space', 'Cancel activity during the smoke advisory', 'Consult the noon air-quality update', 'Use a previously reserved indoor facility'], 0, 'Indoor operation does not imply unreserved capacity.'],
    ['When will officials reconsider afternoon outdoor activity?', ['After the midday air-quality assessment', 'Only after every indoor class ends', 'Before the morning smoke reading', 'At the end of the academic term'], 0, 'The next decision point follows the noon check.'],
  ]),
  ...listeningGroup('announcement-writing', 'Listen to an Announcement', '학습 지원', 'B1', 'The writing center is adding Sunday appointments during final-project week. These sessions are online only and must be booked by Saturday evening. Sunday tutors can discuss organization and clarity but cannot provide new feedback on a paper due in less than two hours.', [
    ['How are the additional Sunday sessions delivered?', ['Exclusively through an online appointment', 'At the usual physical writing-center desk', 'Without any advance booking', 'Only after a paper’s deadline'], 1, 'The temporary sessions are remote.'],
    ['Which paper may not receive new Sunday feedback?', ['One due within the next two hours', 'One booked before Saturday evening', 'One needing help with organization', 'One shared through the online system'], 1, 'The near-deadline limit protects appropriate revision time.'],
  ]),
  ...listeningGroup('announcement-lab-tour', 'Listen to an Announcement', '연구 홍보', 'B2', 'Friday’s public laboratory tour is full. Registered visitors must arrive ten minutes early for safety glasses. At the start time, unclaimed places will be offered to the standby line. Children under twelve may enter the demonstration room but cannot join the adjacent fabrication-area portion.', [
    ['What happens to an unclaimed registered place?', ['It becomes available to a standby visitor at the start time', 'It remains empty throughout every part of the tour', 'It transfers automatically to a child under twelve', 'It allows entry without safety glasses'], 2, 'Late arrival risks reassignment.'],
    ['Where may a child under twelve participate?', ['In the demonstration room but not the fabrication area', 'Only inside the fabrication workspace', 'In every area with no age restriction', 'Only while standing in the standby line'], 2, 'The age rule divides the tour into accessible and restricted portions.'],
  ]),
  ...listeningGroup('announcement-print', 'Listen to an Announcement', '출판 시설', 'B2', 'The large-format printer is using a temporary matte paper while the standard roll is unavailable. Existing reservations remain valid, but colors and contrast may differ from earlier proofs. Users who require an exact match for an exhibition should postpone printing; ordinary conference posters can proceed after reviewing a small test strip.', [
    ['Who is advised to delay a print job?', ['A user needing close consistency with an earlier exhibition proof', 'Anyone able to review a small conference-poster test', 'A user whose reservation remains active', 'Everyone printing on matte paper for ordinary use'], 3, 'Exact matching is not reliable with the substitute medium.'],
    ['What should an ordinary poster user do first?', ['Inspect a small sample produced on the temporary paper', 'Cancel the reservation without viewing the output', 'Assume colors will match the unavailable roll', 'Print the entire poster before checking contrast'], 3, 'A test strip reveals the medium-specific change.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-plasticity', 'Listen to an Academic Talk', '발생생태학', 'C1', 'Developmental plasticity allows one genotype to produce different traits under different environmental conditions. Water fleas exposed to chemical cues from predators may develop protective structures. The response can be adaptive if the cue reliably predicts danger, but producing a defense has energetic costs. Plasticity itself can evolve, and its limits matter: an organism cannot express a useful phenotype if it lacks the developmental machinery or if the cue arrives too late. Researchers use reaction norms to plot phenotype across environments for different genotypes.', [
    ['When is a cue-triggered defense most likely to be adaptive?', ['When the cue predicts risk well enough to justify the production cost', 'When the defense requires no developmental capacity', 'When the signal always arrives after development ends', 'When every environment produces an identical phenotype'], 0, 'Predictive value must outweigh energetic and opportunity costs.'],
    ['What does a reaction norm represent?', ['How a genotype’s expressed trait changes across environments', 'The exact DNA sequence of every predator', 'A fixed phenotype that ignores all conditions', 'The energy content of one defensive structure'], 0, 'It maps environmental input to phenotype for a genotype.'],
  ]),
  ...listeningGroup('talk-auctions', 'Listen to an Academic Talk', '시장설계', 'C1', 'In a second-price sealed-bid auction, the highest bidder wins but pays the second-highest bid. Under standard assumptions, bidding one’s true value is a dominant strategy: bidding lower risks losing a profitable purchase, while bidding higher risks winning at a price above one’s value. The conclusion depends on private independent values and simple preferences. Repeated interaction, budget constraints, or value that depends on others’ information can change behavior. Auction rules cannot be evaluated solely from the name of the mechanism.', [
    ['Why can bidding below true value be costly?', ['The bidder may lose even when the sale price would have been acceptable', 'The winner always pays their own lower bid', 'A low bid raises the second-highest price', 'Private value disappears after bidding'], 1, 'Underbidding can forfeit positive surplus.'],
    ['Why does the lecturer qualify the strategy result?', ['Real settings may violate assumptions about values and constraints', 'Second-price auctions never identify a winner', 'Every repeated auction has independent private values', 'Mechanism details are irrelevant to incentives'], 1, 'The theorem is conditional on a stylized environment.'],
  ]),
  ...listeningGroup('talk-isostasy', 'Listen to an Academic Talk', '지구동역학', 'C1', 'During an ice age, a thick ice sheet depresses the crust and displaces viscous mantle material. After the ice melts, the land rebounds over thousands of years as mantle flows back. This glacial isostatic adjustment continues today in formerly glaciated regions. It changes relative sea level because both land height and Earth’s gravity field evolve. Tide-gauge trends therefore combine ocean-volume change with vertical land motion. Satellite geodesy and geological shoreline markers help separate these contributions.', [
    ['Why can sea level appear to fall at a rebounding coast?', ['The land may rise faster than the local water surface', 'Melting ice always reduces global ocean volume', 'Mantle flow permanently lowers every coastline', 'Tide gauges measure only the gravity field'], 2, 'Relative sea level depends on motion of both reference surfaces.'],
    ['What does satellite geodesy add to tide-gauge interpretation?', ['An estimate of vertical land movement at the observing site', 'A direct measurement of ancient ice thickness everywhere', 'Proof that ocean volume never changes', 'A replacement for every geological marker'], 2, 'Independent crustal motion helps isolate ocean change.'],
  ]),
  ...listeningGroup('talk-harmony', 'Listen to an Academic Talk', '음운론', 'C1', 'In vowel harmony, vowels within a word tend to share a feature such as tongue position or lip rounding. An affix may therefore appear in different forms depending on the stem. Some vowels are transparent and do not participate, while others block harmony. Linguists analyze whether speakers extend the pattern to invented words, which tests productive grammatical knowledge rather than memorized vocabulary. Loanwords and exceptions do not necessarily disprove the rule; they can reveal how speakers rank competing phonological and lexical pressures.', [
    ['Why are invented words useful in studying harmony?', ['They show whether speakers apply the pattern beyond stored examples', 'They guarantee that every vowel participates identically', 'They remove the need to observe affixes', 'They prove that loanwords never affect grammar'], 3, 'Novel items test productive generalization.'],
    ['What can exceptions contribute to analysis?', ['They help reveal boundaries and competing constraints on the pattern', 'They establish that no grammatical regularity exists', 'They force all transparent vowels to become blockers', 'They make lexical knowledge irrelevant'], 3, 'Structured exceptions can diagnose the grammar.'],
  ]),
  ...listeningGroup('talk-ndvi', 'Listen to an Academic Talk', '환경원격탐사', 'C1', 'The normalized difference vegetation index uses red and near-infrared reflectance to estimate green vegetation. Healthy leaves absorb much red light for photosynthesis and reflect strongly in the near infrared. A high index often indicates dense vegetation, but it can saturate in closed forests and respond to soil brightness or atmospheric conditions. Comparing dates requires consistent correction and awareness of viewing geometry. NDVI is a useful proxy, not a direct measurement of biomass or ecosystem health.', [
    ['Why can the index stop distinguishing very dense vegetation?', ['Its response can saturate once canopy cover is high', 'Healthy leaves reflect no near-infrared energy', 'Red absorption always decreases with plant density', 'Closed forests expose only bright soil'], 0, 'At high leaf area, additional biomass produces little index change.'],
    ['What is required for defensible comparison across dates?', ['Control for atmospheric and geometric differences in acquisition', 'Interpret every high value as equal biomass', 'Remove near-infrared reflectance from the calculation', 'Assume soil background never varies'], 2, 'Nonvegetation acquisition effects can mimic change.'],
  ]),
  ...listeningGroup('talk-overturning', 'Listen to an Academic Talk', '물리해양학', 'C1', 'Ocean overturning circulation moves water masses through differences in density, wind forcing, and mixing. Cold, salty water can become dense enough to sink at high latitudes, but calling the system a simple global conveyor belt is misleading. Pathways branch, waters mix, and wind drives much of the return flow. Freshwater input can reduce surface density and weaken deep-water formation. Short observations of one current do not measure the entire overturning system, so researchers combine moorings, tracers, floats, and models.', [
    ['Why is the conveyor-belt metaphor incomplete?', ['Actual circulation has branching paths and multiple driving processes', 'All ocean water follows one closed pipe without mixing', 'Wind affects only coastal waves', 'Density plays no role at high latitudes'], 1, 'The real system is a network, not one uniform loop.'],
    ['Why are multiple observation methods combined?', ['No single current measurement captures the full three-dimensional circulation', 'Tracers directly control freshwater input', 'Floats eliminate the need for models', 'Moorings observe every ocean basin simultaneously'], 3, 'Different tools constrain complementary parts of a distributed system.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the policy date difficult to interpret?', 'Scarcely had the', ['new rule begun', 'when another reform', 'altered the same', 'outcome making', 'attribution uncertain'], 'f10-scarcely-when-inversion'],
  ['Did the animal’s success demonstrate planning?', 'Successful though it', ['was the behavior', 'could have arisen', 'through repeated', 'trial and', 'error'], 'f10-successful-though-concession'],
  ['Why were the restored letters bracketed?', 'The editors wished', ['to distinguish', 'what could be', 'seen from', 'what had been', 'inferred'], 'f10-wh-clause-passive-parallel'],
  ['Can the spectral feature identify life?', 'For it to', ['constitute such evidence', 'nonbiological sources', 'would first', 'have to be', 'excluded'], 'f10-for-infinitive-modal-passive'],
  ['How was the regional estimate constructed?', 'Each comparison area', ['was assigned', 'a weight proportional', 'to how closely', 'its earlier trend', 'matched'], 'f10-passive-proportional-relative'],
  ['Why not discard the failed trials?', 'Were they to', ['be omitted', 'the apparent reliability', 'of the method', 'would be', 'overstated'], 'f10-inverted-passive-counterfactual'],
  ['What did the field evidence establish?', 'No more could', ['be concluded', 'than that', 'the material', 'had reached', 'the settlement'], 'f10-no-more-inversion-than'],
  ['Did the correction alter the conclusion?', 'While leaving the', ['direction unchanged', 'it increased', 'the uncertainty', 'with which', 'the effect was estimated'], 'f10-while-participial-relative-passive'],
  ['Why was external validation necessary?', 'However well the', ['model described', 'the original sample', 'its performance', 'elsewhere remained', 'unknown'], 'f10-however-well-concession'],
  ['Should the alternative analysis be reported?', 'To do otherwise', ['would conceal', 'how sensitive', 'the result', 'was to', 'reasonable choices'], 'f10-infinitive-subject-embedded-how'],
]
const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '실험 데이터 이상', 'B2', 420), instruction: '문제와 근거, 즉시 필요한 조치를 구체적으로 작성하세요.', prompt: 'Every environmental sensor showed an identical jump at midnight, but manual measurements did not change and a software update occurred at the same time. Write to the data manager. Describe the discrepancy, explain why analysis should pause, and request preservation of raw values and a documented calibration check.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '동물 인지', 'C1', 600), instruction: '다른 학생의 관점을 평가하며 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Wallace: What kind of evidence should be required before researchers describe an animal behavior as intelligent planning rather than learned habit?', passage: 'Hana: Flexible behavior on a novel problem is strong evidence that the animal represents a future goal.\nMateo: Novel success may still result from general exploration unless experiments rule out simpler learning histories.' })

const repeatSentences = ['Welcome to the microscopy training laboratory.', 'Place prepared slides on the tray beside your workstation.', 'Begin with the lowest magnification before adjusting the focus.', 'Keep immersion oil away from objectives not designed for it.', 'Record exposure settings before capturing comparative images.', 'If the stage moves unexpectedly, stop and notify the instructor.', 'Before leaving, lower the stage, remove every slide, clean the approved lenses, and save images outside the workstation.']
const interviewQuestions = ['Describe a behavior that people often interpret as evidence of intelligence.', 'What simpler explanation could account for that behavior?', 'How could an experiment distinguish planning from repeated trial and error?', 'Should intelligence be defined in the same way for humans, animals, and machines?']
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '현미경 교육 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f10-repeat', scenarioId: 'f10-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '지능과 행동 해석', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f10-interview', scenarioId: 'f10-interview', sequenceIndex })),
]

export const AUTHORED_FORM_10_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_10_IDS = AUTHORED_FORM_10_ITEMS.map((item) => item.id)
