import { prepareSentenceTiles } from './sentenceTiles'
import type { BaseItem } from './types'

type Difficulty = NonNullable<BaseItem['difficulty']>
type Question = [prompt: string, options: string[], answer: number, explanation: string]

const base = (id: string, section: BaseItem['section'], kind: BaseItem['kind'], title: string, topic: string, difficulty: Difficulty, timeSeconds: number): BaseItem => ({
  id: `f05-${id}`, section, module: 1, kind, title, topic, difficulty, timeSeconds, instruction: '', sourceFamily: 'authored-form-05',
})
const cloze = (id: string, topic: string, difficulty: Difficulty, passage: string, answer: string): BaseItem => ({
  ...base(id, 'reading', 'complete-words', 'Complete the Words', topic, difficulty, 240), instruction: '첫 문장을 읽고 문맥, 문법, 철자에 맞게 열 개 단어를 완성하세요.', passage, answer,
  explanation: '각 어간이 요구하는 의미와 품사, 수 일치, 시제를 함께 적용해야 합니다.',
})
const daily = (id: string, topic: string, difficulty: Difficulty, passage: string, q: Question): BaseItem => ({
  ...base(id, 'reading', 'multiple-choice', 'Read in Daily Life', topic, difficulty, 75), instruction: '실용문의 조건과 예외를 구분해 답하세요.', passage, prompt: q[0], options: q[1], answer: q[2], explanation: q[3],
})
const readingGroup = (id: string, topic: string, difficulty: Difficulty, passage: string, questions: Question[]): BaseItem[] => questions.map((q, sequenceIndex) => ({
  ...base(`${id}-${sequenceIndex}`, 'reading', 'multiple-choice', 'Read an Academic Passage', topic, difficulty, 120), instruction: '학술 지문의 논증, 증거, 추론 범위를 파악하세요.', passage, prompt: q[0], options: q[1], answer: q[2], explanation: q[3], stimulusGroupId: `f05-${id}`, sequenceIndex,
}))
const response = (id: number, audioText: string, options: string[], answer: number, explanation: string): BaseItem => ({
  ...base(`response-${id}`, 'listening', 'listen-choice', 'Listen and Choose a Response', '캠퍼스 의사소통', id < 8 ? 'B1' : 'B2', 35), instruction: '짧은 말을 듣고 가장 자연스러운 응답을 고르세요.', audioText, options, answer, explanation,
})
const listeningGroup = (id: string, title: string, topic: string, difficulty: Difficulty, audioText: string, questions: Question[]): BaseItem[] => questions.map((q, sequenceIndex) => ({
  ...base(`${id}-${sequenceIndex}`, 'listening', 'listen-choice', title, topic, difficulty, title === 'Listen to an Announcement' ? 55 : title === 'Listen to an Academic Talk' ? 80 : 70),
  instruction: title === 'Listen to an Announcement' ? '공지에서 변화, 조건, 청자의 행동을 파악하세요.' : title === 'Listen to an Academic Talk' ? '강의의 핵심 개념과 증거 관계를 파악하세요.' : '대화의 문제, 제약, 해결 방안을 파악하세요.',
  audioText, prompt: q[0], options: q[1], answer: q[2], explanation: q[3], stimulusGroupId: `f05-${id}`, sequenceIndex,
}))

const reading: BaseItem[] = [
  cloze('cloze-mycorrhiza', '균근생태학', 'C1', 'Many plant roots form associations with mycorrhizal fungi. Fine fungal threads exte___ beyond the root and acc___ nutrients that would otherwise remain unavailable. In return, the plant sup___ carbohydrates produced through photosynthesis. The exchange is not always equ___ beneficial; its value dep___ on soil fertility and water. Under nutrient-rich conditions, maintaining the fungus may con___ more carbon than the plant gains in minerals. Experiments must therefore comp___ inoculated and uninoculated plants under controlled conditions. Field networks are even more com___ because several species can be connected. Researchers avoid ass___ that every connection transfers resources and seek direct evidence before inf___ cooperation.', 'nd|ess|plies|ally|ends|sume|are|plex|uming|erring'),
  cloze('cloze-codicology', '기록문화사', 'C1', 'A manuscript can reveal information beyond the words it contains. Codicologists exa___ its paper, ink, binding, and page arrangement. Watermarks may nar___ the place or period of production, although paper was often tra___ far from its mill. Changes in handwriting can ind___ several scribes, while erased notes may pre___ an earlier use. Scholars doc___ physical features before conservation alters them. They also comp___ related volumes, because a single characteristic rarely estab___ origin by itself. Material clues supp___ historical interpretation, but uncertainty should remain vis___ whenever the evidence permits several explanations.', 'mine|row|ded|icate|serve|ument|are|lishes|ort|ible'),
  cloze('cloze-upwelling', '해양학', 'B2', 'Along some coasts, winds move surface water away from land. Deeper water then ri___ to replace it, carrying dissolved nutrients into sunlit layers. This upwelling sup___ large populations of microscopic algae and, consequently, productive fisheries. The process can var___ from year to year as atmospheric circulation changes. If upwelling weak___, food availability may decline even when fishing pressure remains constant. Strong upwelling can also bri___ low-oxygen or acidic water toward shore. Scientists track wind, temperature, oxygen, and biological res___ rather than treating productivity as a simple mea___ of fish abundance. Coastal communities dep___ on accurate forecasts. Linked observations help distin___ natural variability from human effects and impr___ management decisions.', 'ses|ports|y|ens|ng|ponses|sure|end|guish|ove'),
  daily('daily-vivarium', '동물 연구 시설', 'C1', 'Entry to the vivarium requires both annual biosafety training and project-specific animal-care authorization. Completing the online course renews only the first requirement. Researchers added to an approved protocol must wait until the facility receives confirmation from the animal-care office before their access card is activated.', ['A researcher has renewed biosafety training and joined a project team. What remains necessary for entry?', ['Confirmation that the researcher is authorized under the relevant protocol', 'A second access card issued before completing any online course', 'Permission from another researcher already inside the facility', 'Evidence that the project uses no living organisms'], 0, 'General training and protocol authorization are independent access requirements.']),
  daily('daily-darkroom', '사진 실습', 'B2', 'The photography darkroom provides standard black-and-white chemicals. Students using alternative processes must submit a safety sheet and take all unused chemicals away after the session. Waste may enter the labeled collection bottle only after staff verify that it is chemically compatible with the existing contents.', ['What must happen before alternative-process waste is added to the shared bottle?', ['Staff must confirm that mixing the materials is safe', 'The student must remove the bottle from the building', 'Every standard chemical must first be discarded', 'The safety sheet must be replaced with a verbal description'], 0, 'Compatibility review prevents hazardous reactions in mixed waste.']),
  daily('daily-thesis', '대학원 행정', 'C1', 'A thesis submitted by the initial deadline may be returned for formatting corrections without delaying graduation. Submissions after that deadline enter the next review cycle unless the graduate school has documented a technical failure in its own portal. Problems with personal software or internet service do not qualify for an exception.', ['Which late submission could still be reviewed in the current cycle?', ['One delayed by a failure officially recorded in the university system', 'One uploaded late because the writer’s home connection was slow', 'One containing errors that were noticed before the deadline', 'One converted using software not supported by the graduate school'], 0, 'Only a verified institutional portal failure creates the stated exception.']),
  daily('daily-seedling-sale', '지역 행사', 'B1', 'The botanical club’s seedling sale begins at ten. Preordered plants are held until noon; after that, uncollected orders may be sold to visitors. Buyers should bring boxes because the club has only a small supply of carrying trays.', ['How can a customer ensure receiving a preordered plant?', ['Collect it before the noon holding period expires', 'Arrive after the plants are released to general buyers', 'Wait until the club obtains additional carrying trays', 'Purchase a box from the botanical club at ten'], 0, 'The reservation is protected only until midday.']),
  daily('daily-laser', '공학 안전', 'C1', 'The laser laboratory’s illuminated warning sign means that protective eyewear is required before the inner door opens. Do not enter merely because the beam appears inactive; alignment procedures can produce invisible radiation. Visitors without assigned eyewear must remain behind the exterior viewing window with their host.', ['Why is visual inspection of the beam not an adequate safety check?', ['Hazardous radiation may be present even when no beam is visible', 'The warning light operates only after visitors enter', 'Assigned eyewear makes every alignment procedure unnecessary', 'The exterior window intensifies visible laser radiation'], 0, 'Some laser wavelengths and alignment emissions cannot be seen.']),
  daily('daily-peer-tutor', '학습 지원', 'B2', 'Peer tutors may explain course concepts and comment on a draft, but they may not solve questions from a currently graded take-home examination. If an assignment’s status is unclear, bring the course instructions; the tutor will pause the session until the academic-integrity restriction can be determined.', ['What will a tutor do when the instructions do not reveal whether help is permitted?', ['Suspend assistance while the assignment status is clarified', 'Complete only the examination’s shortest questions', 'Assume the work is an ordinary ungraded exercise', 'Ask the student to remove the course instructions'], 0, 'Uncertainty triggers a pause rather than unauthorized assistance.']),
  daily('daily-soil-core', '표본 대여', 'C1', 'Archived soil cores may be subsampled only when the requested analysis cannot use imaging or another nondestructive method. Applications must specify the minimum material needed and explain why equivalent cores from a less complete sequence are unsuitable. Approval does not guarantee immediate shipment because curators first photograph each removal location.', ['What must an applicant justify when asking to remove material from a core?', ['Why destructive sampling and that particular sequence are necessary', 'Why photography should occur after the sample leaves the archive', 'Why the largest possible quantity will improve every analysis', 'Why incomplete substitute records are always scientifically superior'], 0, 'The archive requires both methodological necessity and collection-specific need.']),
  daily('daily-recital', '음악 공연', 'B2', 'Degree-recital programs must list composers’ full names and the approximate duration of each work. Submit the editable file, not a scanned image, seven days before printing. The music office proofreads layout and institutional wording but does not verify historical dates supplied by performers.', ['Which information remains the performer’s responsibility to verify?', ['The historical dates included in the program', 'The required institutional language in the layout', 'Whether the office can edit a scanned image', 'The location of the printing deadline in the file'], 0, 'Content accuracy for historical dates is excluded from the office’s review.']),
  daily('daily-community-garden', '커뮤니티 시설', 'B1', 'Garden plots not cleared by November 15 will be prepared for winter by volunteers. Gardeners who want perennial plants left in place should attach the provided blue marker and trim dead growth. An unlabeled plant may be removed even if it appears healthy.', ['How should a gardener protect a perennial over winter?', ['Mark it with the designated tag and complete the requested trimming', 'Leave the whole plot uncleared without notifying volunteers', 'Move the plant into an unmarked neighboring plot', 'Rely on its healthy appearance to prevent removal'], 0, 'The marker communicates the exception, and trimming is also required.']),
  daily('daily-language-test', '시험 행정', 'C1', 'Students requesting an alternative language-placement test must submit evidence of prior study before choosing an appointment. A booking made first will be canceled rather than held while documents are reviewed. Results from an approved alternative test replace, rather than supplement, the standard placement score.', ['What happens if a student schedules before prior-study evidence is accepted?', ['The premature reservation is canceled', 'The appointment remains reserved indefinitely', 'Both placement scores are averaged automatically', 'The document requirement is waived after booking'], 0, 'Eligibility review must precede scheduling.']),
  ...readingGroup('academic-dag', '인과추론', 'C1', 'Researchers sometimes represent causal assumptions with a directed acyclic graph. An arrow from exposure to outcome expresses a proposed direct causal path, while a common cause points to both variables. Conditioning on that common cause can block a noncausal association. However, conditioning on a variable caused by both exposure and outcome—a collider—can create an association that was absent. The graph does not discover causal structure from data alone; it makes assumptions explicit so that adjustment choices can be criticized. Two investigators may draw different graphs from the same dataset if their substantive theories differ.', [
    ['What benefit of a causal graph is emphasized?', ['It exposes theoretical assumptions that guide statistical adjustment', 'It automatically proves every arrow using observed correlations', 'It prevents researchers from proposing competing explanations', 'It requires conditioning on every measured variable'], 0, 'The graph clarifies assumptions rather than deriving them mechanically.'],
    ['Why can controlling for a collider be harmful?', ['It may introduce a spurious relationship between otherwise separate causes', 'It removes every direct pathway from exposure to outcome', 'It turns an acyclic graph into a randomized experiment', 'It guarantees that a common cause remains unmeasured'], 0, 'Selection on a shared effect can open a noncausal path.'],
    ['What would most likely lead two researchers to construct different graphs?', ['They hold different domain-based beliefs about how variables affect one another', 'They use the same substantive theory and identical definitions', 'They both avoid representing any unobserved process', 'They calculate the same descriptive mean from the data'], 0, 'Causal diagrams encode background theory, so theoretical disagreement matters.'],
  ]),
  ...readingGroup('academic-metamorphosis', '발생생물학', 'B2', 'During complete metamorphosis, a caterpillar and an adult butterfly occupy different ecological roles. The larva primarily eats and grows, whereas the adult disperses and reproduces. Inside the pupa, many larval tissues are reorganized, but the process is not a complete dissolution into undifferentiated material. Groups of cells established earlier contribute to adult structures, and some neural connections persist. Separating life stages may reduce competition for food between juveniles and adults, although metamorphosis also demands energy and creates a vulnerable transitional period.', [
    ['Which common misconception does the passage correct?', ['All larval organization disappears before adult tissues form', 'Adult butterflies perform no ecological function besides feeding', 'Juveniles and adults necessarily consume identical resources', 'Neural tissue can never persist through the pupal stage'], 0, 'Earlier cell groups and some connections survive the reorganization.'],
    ['What evolutionary trade-off is described?', ['Reduced resource competition comes with an energetically costly exposed transition', 'Faster reproduction prevents larvae from growing', 'Persistent neural connections eliminate adult dispersal', 'Pupation increases feeding competition while removing vulnerability'], 0, 'Stage specialization offers a benefit but metamorphosis has costs.'],
  ]),
  ...readingGroup('academic-restoration', '심리언어학', 'C1', 'In the phoneme-restoration effect, listeners hear a word even when one speech sound has been replaced by a cough or other noise. The perceived missing sound depends on lexical and sentence context: the same ambiguous segment may be heard differently in different words. This finding shows that speech perception is not a one-way process in which acoustic input alone determines recognition. Yet listeners are not simply imagining arbitrary sounds. The noise must plausibly mask the segment, and strong contradictory acoustic evidence can override contextual expectation. Perception integrates bottom-up signals with predictions formed from linguistic knowledge.', [
    ['What does the phoneme-restoration effect demonstrate about comprehension?', ['Prior linguistic knowledge contributes to interpreting incomplete sound', 'Listeners rely exclusively on the acoustic waveform', 'Any imagined word is accepted regardless of surrounding syntax', 'Background noise permanently erases lexical expectations'], 0, 'Context supplies a prediction when the signal is temporarily missing.'],
    ['Why does the author mention contradictory acoustic evidence?', ['To limit the claim that contextual prediction controls perception without constraint', 'To show that coughs contain precise hidden speech segments', 'To prove that lexical knowledge develops after hearing loss', 'To argue that sentence meaning never affects sound recognition'], 0, 'Bottom-up evidence can defeat expectation, so the system is integrative.'],
    ['Which outcome best illustrates the role of lexical context?', ['An identical unclear segment is perceived as different phonemes inside different familiar words', 'A clear tone is judged equally loud in two silent rooms', 'Listeners fail to recognize a word spoken without any masking noise', 'Every participant invents an unrelated sentence after hearing a cough'], 0, 'Different word candidates constrain how the same ambiguity is resolved.'],
  ]),
  ...readingGroup('academic-concrete', '재료고고학', 'C1', 'Some ancient Roman marine concrete contains fragments of reactive volcanic rock. When seawater penetrates microscopic cracks, chemical reactions can form new minerals that grow through the material and may hinder further cracking. This does not mean every Roman structure repairs itself indefinitely. Composition varied among sites, and mineral growth can also generate damaging pressure. Modern concrete is optimized for rapid, standardized construction and often has a different chemistry. Engineers study ancient samples not to copy a recipe unchanged, but to identify mechanisms that could inspire durable lower-carbon materials.', [
    ['Why can seawater sometimes contribute to durability in the ancient material?', ['It enables reactions whose products can obstruct crack propagation', 'It prevents any mineral from forming inside a fracture', 'It removes every variation in regional construction practice', 'It converts the concrete into standardized modern cement'], 0, 'Water-driven mineral formation may fill or bridge developing cracks.'],
    ['What attitude toward ancient concrete does the passage recommend?', ['Investigate useful mechanisms without assuming universal or direct imitation', 'Replace all contemporary mixtures with one historical formula', 'Ignore local composition because every structure behaves identically', 'Treat mineral growth as beneficial under all possible conditions'], 0, 'The evidence motivates selective engineering insight, not romanticized copying.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you reserve the spectrometer for Thursday afternoon?', ['I can, once you send me the project code.', 'The spectrum contains several narrow peaks.', 'Thursday’s seminar discusses visual art.', 'I reserved judgment until reading the report.'], 0, 'The response accepts the request while identifying needed information.'),
  response(1, 'Why was the outdoor screening postponed?', ['The screen is stored behind the auditorium.', 'High winds made the temporary structure unsafe.', 'I watched the earlier film indoors.', 'Posters were printed in several sizes.'], 1, 'Unsafe wind directly explains the postponement.'),
  response(2, 'Have you finished calibrating the balance?', ['The balance between work and rest is important.', 'Calibration records are filed by date.', 'Not yet; the reference weight is still stabilizing.', 'I finished the reading before breakfast.'], 2, 'The reply gives the status and relevant reason for delay.'),
  response(3, 'Would it be possible to move our appointment online?', ['The appointment calendar uses green labels.', 'I moved the boxes away from the doorway.', 'Online archives contain digitized newspapers.', 'Yes, I’ll replace the room number with a video link.'], 3, 'The reply agrees and describes the corresponding change.'),
  response(4, 'I assumed the application deadline was midnight.', ['It used to be, but this year the portal closes at five.', 'Your application includes two recommendation letters.', 'Midnight is twelve hours after noon.', 'The portal displays each uploaded filename.'], 0, 'The response corrects an outdated assumption.'),
  response(5, 'Where can I find the revised evacuation map?', ['The revision changed two paragraphs.', 'There’s a laminated copy beside each elevator.', 'I found my notebook under the table.', 'Evacuation drills occur every semester.'], 1, 'The reply supplies a location for the requested map.'),
  response(6, 'Shouldn’t these interviews be anonymized before sharing?', ['Interview techniques improve with practice.', 'Sharing a meal can strengthen a team.', 'Absolutely; the consent form permits only de-identified files.', 'These name tags were printed yesterday.'], 2, 'The response confirms the privacy requirement and its basis.'),
  response(7, 'The repair estimate is higher than our equipment budget.', ['Equipment must be inventoried each summer.', 'The estimate contains labor and shipping costs.', 'I repaired my bicycle near the station.', 'Then we may need to request replacement funds instead.'], 3, 'The reply proposes a relevant funding alternative.'),
  response(8, 'Can anyone attend tomorrow’s dissertation defense?', ['Yes, although the committee’s final discussion is private.', 'The dissertation has six main chapters.', 'Tomorrow is the last day of the exhibition.', 'Anyone can defend a carefully supported claim.'], 0, 'The answer distinguishes the public event from its closed deliberation.'),
  response(9, 'Why are two entries missing from the catalog?', ['The catalog is organized by accession number.', 'They were temporarily withdrawn for condition assessment.', 'I entered through the east gallery door.', 'Two copies are enough for the seminar.'], 1, 'Temporary conservation status explains the catalog absence.'),
  response(10, 'Would adding another predictor improve the model?', ['The prediction appeared in yesterday’s forecast.', 'Another model is displayed in the lobby.', 'Only if it adds information rather than fitting random noise.', 'Improvement is the goal of every revision.'], 2, 'The response identifies a valid condition and overfitting concern.'),
  response(11, 'I don’t think the microphone captured the final question.', ['The final examination allows handwritten notes.', 'The microphone stand adjusts to several heights.', 'Questions can be difficult to phrase clearly.', 'Let’s ask the speaker to repeat it before everyone leaves.'], 3, 'Repeating while the speaker is present addresses missing audio.'),
  response(12, 'Is there a fee for replacing a damaged access card?', ['Only when the damage resulted from misuse.', 'The access road curves around the stadium.', 'Damaged books should remain on the return cart.', 'I replaced the battery last weekend.'], 0, 'The reply gives the condition under which a charge applies.'),
  response(13, 'When are the revised lab sections being announced?', ['The laboratory has three adjoining rooms.', 'The department expects to post them by Wednesday.', 'I revised the methods section this morning.', 'Announcements are sent through the campus system.'], 1, 'The response directly provides the expected timing.'),
  response(14, 'Could the outlier be a transcription error?', ['Transcription software supports several languages.', 'The error bars overlap slightly.', 'It could, so I’m checking the original field sheet.', 'The outlier lives far beyond the city center.'], 2, 'The reply treats the hypothesis as testable against source records.'),
  response(15, 'Who is responsible for approving hazardous shipments?', ['The shipment arrived in three insulated containers.', 'Approval often requires an additional form.', 'Responsibility can be shared among team members.', 'The environmental safety officer reviews them.'], 3, 'The answer identifies the appropriate approving role.'),
  response(16, 'The citation manager duplicated every journal title.', ['Disable the automatic abbreviation rule and import the file again.', 'Journal titles are usually printed in italic type.', 'I managed the event registration last spring.', 'Every citation should identify its original source.'], 0, 'Changing the import rule directly addresses systematic duplication.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-map', 'Listen to a Conversation', '지리정보 과제', 'C1', 'Student: My land-use map suggests the forest expanded, but the earlier satellite image has much coarser pixels. Instructor: Then some apparent change may be a resolution artifact. Aggregate the newer image to the older resolution and classify both with the same categories. Student: That will erase small forest patches. Instructor: True, but comparing unequal detail would exaggerate change. You can present the fine-resolution map separately, as long as you do not treat it as directly comparable.', [
    ['What threatens the validity of the student’s initial comparison?', ['Different image resolutions can create apparent land-cover differences', 'The newer image contains no geographic coordinates', 'Forest patches cannot be represented with classification categories', 'Aggregation always increases the amount of visible detail'], 0, 'Unequal spatial detail confounds actual change with measurement change.'],
    ['What compromise does the instructor recommend?', ['Use matched resolution for inference and retain the detailed map for another purpose', 'Delete every small patch from both original satellite files', 'Compare fine and coarse classifications without acknowledging the difference', 'Replace the older image with an unrelated modern photograph'], 0, 'The common scale supports comparison while the detailed image remains informative separately.'],
  ]),
  ...listeningGroup('conversation-keys', 'Listen to a Conversation', '기숙사 관리', 'B2', 'Resident: My roommate took our shared mailbox key home for the weekend. Can I borrow a master key? Clerk: We cannot lend master keys, but I can open the mailbox after checking your identification and room assignment. Resident: Could you make a duplicate today? Clerk: Only the housing office issues replacements, and it is closed until Monday. If the original returns, tell them before they cut a new one or your account will still be charged.', [
    ['How can the resident access the mailbox immediately?', ['Have the clerk open it after verifying residency', 'Borrow a master key until the roommate returns', 'Ask the clerk to manufacture a duplicate', 'Enter the closed housing office without an appointment'], 1, 'Staff-assisted access is available, but keys are not lent or copied there.'],
    ['Why should the resident contact housing if the key returns?', ['To prevent an unnecessary replacement charge', 'To request identification from the roommate', 'To extend the weekend closure', 'To exchange the mailbox for another room'], 1, 'Canceling the pending replacement avoids being billed.'],
  ]),
  ...listeningGroup('conversation-plants', 'Listen to a Conversation', '생물학 실험', 'B2', 'Student: The control plants are taller than the treated ones, but two control pots were beside the window. Assistant: Light could explain the difference. We cannot move them now and pretend the positions were randomized. Record the placement, measure light at each bench, and report an analysis with and without those pots. Student: Should we repeat the experiment? Assistant: If time permits, yes, with positions assigned before planting. For this report, be explicit about the limitation.', [
    ['What possible confounder do the speakers identify?', ['Unequal light exposure associated with treatment group', 'A fertilizer applied only after all measurements ended', 'Random assignment of every pot before planting', 'Identical growth among control and treated plants'], 2, 'Window placement may influence height independently of treatment.'],
    ['What does the assistant prioritize for the current report?', ['Transparent documentation and sensitivity analysis', 'Relabeling the pot locations as if randomized', 'Discarding all measurements without explanation', 'Claiming that treatment caused the full difference'], 2, 'The existing flaw cannot be undone, but it can be assessed and disclosed.'],
  ]),
  ...listeningGroup('conversation-score', 'Listen to a Conversation', '음악 평가', 'C1', 'Composer: The ensemble says measure forty-two is impossible at the marked tempo. I wrote it that way to create tension. Conductor: Tension is useful only if the players can articulate the rhythm. Let us test it ten percent slower. If the effect remains, revise the tempo marking; if it disappears, redistribute two notes between instruments. Composer: I would rather not simplify the harmony. Conductor: Redistribution can preserve every pitch while changing who performs it.', [
    ['What criterion does the conductor apply to the intended tension?', ['The musical effect must remain physically performable and clear', 'Every instrument must play the same number of notes', 'The harmony should be removed before tempo is tested', 'The original marking must be kept regardless of rehearsal evidence'], 3, 'Artistic intent is evaluated together with executable articulation.'],
    ['How could redistribution solve the problem without simplifying harmony?', ['The same pitches could be divided differently among performers', 'The ensemble could omit the difficult measure entirely', 'Every note could be lowered by one scale degree', 'The rhythmic tension could be replaced by silence'], 3, 'Orchestration can alter physical demands while retaining harmonic content.'],
  ]),
  ...listeningGroup('conversation-invoice', 'Listen to a Conversation', '연구비 정산', 'B2', 'Assistant: The vendor invoice combines the field sensors and next year’s maintenance contract. Our grant ends this month. Administrator: Ask the vendor to separate the charges. We can pay for sensors received during the grant period, but we cannot prepay service that begins after the award closes. Assistant: What if the vendor cannot revise the invoice in time? Administrator: Submit the sensor delivery record now and flag the invoice. Do not charge the whole amount merely to meet the deadline.', [
    ['Why must the invoice be divided?', ['The two charges belong to different eligibility periods', 'The sensors were delivered by two competing vendors', 'Maintenance is always prohibited on research grants', 'The grant requires all equipment to arrive next year'], 0, 'Current equipment and future service do not share the same allowable period.'],
    ['What should the assistant avoid doing?', ['Charging an ineligible future service for the sake of speed', 'Providing evidence that the sensors were delivered', 'Asking the supplier for a corrected document', 'Marking the combined invoice for administrative review'], 1, 'A deadline does not justify posting the full mixed charge.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-elevator', 'Listen to an Announcement', '건물 접근성', 'B2', 'The library’s central elevator will be unavailable from Tuesday through Thursday. The smaller east elevator remains open but does not reach the archive level. Anyone needing step-free access to an archive appointment should contact staff by Monday afternoon so materials can be moved to an accessible consultation room. Ordinary requests made after Monday may need to be rescheduled.', [
    ['What should a visitor with an archive appointment do before the outage?', ['Ask staff in advance to relocate the requested material', 'Use the east elevator directly to the archive floor', 'Move archive boxes without staff assistance', 'Wait until Thursday to request any accommodation'], 0, 'Advance contact enables an accessible-room transfer.'],
    ['Why might a late request be postponed?', ['The remaining elevator cannot serve the archive level', 'The consultation room closes permanently on Tuesday', 'Archive materials may never leave their shelves', 'The central elevator is reserved for ordinary visitors'], 0, 'Access limitations require staff preparation before the closure.'],
  ]),
  ...listeningGroup('announcement-debate', 'Listen to an Announcement', '학생 행사', 'B2', 'Registration for the intercollegiate debate closes Friday, but submitting a team name is not enough. Each member must sign the conduct agreement before the team is entered into the bracket. Substitutions are allowed until Monday if the replacement signs immediately. After the bracket is published, a team missing a member may compete with fewer speakers but cannot add someone new.', [
    ['What must occur for a team to enter the competition bracket?', ['Every listed participant must complete the conduct agreement', 'The team must replace one speaker before Friday', 'A team name alone must be submitted after Monday', 'The bracket must be published before anyone registers'], 1, 'Individual signatures complete registration beyond naming the team.'],
    ['What restriction begins after publication of the bracket?', ['No new replacement participant may be added', 'Teams may no longer compete with fewer speakers', 'Conduct agreements cease to apply', 'Every team must change its registered name'], 1, 'Late staffing shortages are allowed, but additions are not.'],
  ]),
  ...listeningGroup('announcement-chemistry', 'Listen to an Announcement', '실험실 교육', 'C1', 'Friday’s advanced synthesis laboratory will begin with an ungraded readiness check covering air-sensitive techniques. Students who cannot demonstrate the glove-box transfer will complete a supervised refresher instead of the synthesis. This does not reduce the course grade, but the synthesis cannot be made up during ordinary open-lab hours because a specialist must be present. One additional supervised session will be offered next Wednesday.', [
    ['What happens to a student who does not pass the readiness check?', ['The student receives refresher training rather than performing the synthesis', 'The student automatically loses points from the course grade', 'The student repeats the synthesis alone during open laboratory hours', 'The specialist removes the glove box from the course'], 2, 'Readiness changes the activity, not the grade.'],
    ['Why is the makeup opportunity limited to a special session?', ['The procedure requires supervision unavailable during regular open hours', 'The synthesis can be completed only before the readiness check', 'The course has prohibited all work on Wednesdays', 'The refresher uses equipment located outside the laboratory'], 2, 'Specialist presence determines when the task can safely occur.'],
  ]),
  ...listeningGroup('announcement-film', 'Listen to an Announcement', '영화 자료실', 'B2', 'The media archive is replacing its streaming platform. Saved playlists will not transfer automatically, although viewing histories will remain available as downloadable files for thirty days. Faculty should export playlist titles by the end of this week and rebuild them after Monday’s launch. Links embedded in course pages will redirect for one month, but they should still be updated before the temporary redirects expire.', [
    ['Which information must users preserve themselves before migration?', ['The contents and organization of saved playlists', 'Every item in the archive’s master catalog', 'Viewing histories that remain online permanently', 'Course links that will never redirect'], 3, 'Playlists do not migrate and therefore require user export and reconstruction.'],
    ['What should instructors do about existing course-page links?', ['Replace them during the temporary redirection period', 'Delete every course page before the platform launches', 'Assume redirects will continue for the entire semester', 'Convert the links into downloadable viewing histories'], 3, 'The one-month bridge permits, but does not remove, required updating.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-allostery', 'Listen to an Academic Talk', '생화학', 'C1', 'An allosteric regulator binds to a protein at a site other than the active site. That binding can shift the protein toward a shape with greater or lower activity. In an enzyme pathway, the final product may inhibit an earlier enzyme through such a mechanism, limiting further production when enough product has accumulated. This feedback is rapid because it changes existing proteins rather than waiting for new genes to be expressed. The simplified diagram of an “on” and “off” enzyme is useful, but real proteins often occupy an ensemble of conformations.', [
    ['How can a pathway’s final product regulate its own abundance?', ['It can alter an earlier enzyme by binding away from the active site', 'It permanently removes every gene encoding the enzyme', 'It supplies additional substrate regardless of cellular need', 'It prevents proteins from adopting more than one shape'], 0, 'Feedback inhibition reduces upstream activity through allosteric binding.'],
    ['Why is the response described as rapid?', ['It modulates proteins that are already present', 'It requires transcription of many replacement genes', 'It waits until all substrate leaves the cell', 'It converts the final product into genetic material'], 0, 'Conformational control avoids the delay of gene expression.'],
  ]),
  ...listeningGroup('talk-taphonomy', 'Listen to an Academic Talk', '고생물학', 'C1', 'A fossil assemblage is not a transparent snapshot of an ancient community. After death, soft tissues decay, currents transport remains, scavengers separate bones, and burial conditions favor preservation of some materials over others. Taphonomy studies these processes. If one species has robust shells while another has fragile skeletons, fossil abundance may reflect preservability rather than original population size. Researchers compare breakage, orientation, sediment, and modern decay experiments to reconstruct how an assemblage formed.', [
    ['Why can fossil counts misrepresent past ecological abundance?', ['Species differ in how likely their remains are to survive and be collected', 'Every organism enters the sediment at the same location', 'Modern experiments cannot observe decay processes', 'Robust shells always indicate a small living population'], 1, 'Preservation filters the original community unevenly.'],
    ['What is the goal of examining orientation and breakage?', ['To infer processes that accumulated and modified the remains', 'To calculate the exact color of every living organism', 'To prevent sediment from covering future fossils', 'To classify only species with soft body parts'], 1, 'Physical patterns can reveal transport, scavenging, and burial history.'],
  ]),
  ...listeningGroup('talk-predictive', 'Listen to an Academic Talk', '인지신경과학', 'C1', 'Predictive-processing theories propose that the brain continually generates expectations about sensory input and updates them when prediction errors occur. A familiar object can therefore be recognized from incomplete information, because prior knowledge constrains plausible interpretations. But a flexible system must also assign sufficient weight to surprising evidence; otherwise expectation would dominate perception even when the world changes. Researchers study this balance by manipulating both the reliability of a cue and the strength of the sensory signal.', [
    ['Why must the system preserve sensitivity to prediction error?', ['New evidence should sometimes overturn an established expectation', 'Prior knowledge must eliminate every ambiguous perception', 'Sensory signals are always less reliable than contextual cues', 'Familiar objects never appear under changing conditions'], 2, 'Adaptation requires correction when observations conflict with predictions.'],
    ['What experimental manipulation would test the proposed balance?', ['Varying cue reliability independently of sensory clarity', 'Presenting one perfectly clear stimulus with no context changes', 'Measuring only whether participants know an object’s name', 'Removing all surprising trials from the analysis'], 2, 'Independent variation reveals how the two information sources are weighted.'],
  ]),
  ...listeningGroup('talk-groundwater', 'Listen to an Academic Talk', '수문학', 'B2', 'Water entering an aquifer carries isotopic and chemical signatures related to rainfall, geology, and human activity. As groundwater moves, some substances react with rock or decay at known rates. Researchers use several tracers because no single marker gives both age and source under every condition. A young-water tracer may reveal recent recharge but become undetectable in older water. A stable isotope may persist longer yet identify climate or elevation rather than travel time directly.', [
    ['Why do hydrologists combine different tracers?', ['Each marker answers only part of the source-and-age problem', 'Every chemical changes at exactly the same known rate', 'Stable isotopes directly measure travel time in all aquifers', 'Recent recharge contains no detectable substances'], 3, 'Complementary strengths compensate for individual limitations.'],
    ['What limitation of a young-water tracer is described?', ['It may no longer be measurable after a long residence time', 'It always indicates the elevation but never recent recharge', 'It reacts only with rainfall before entering the ground', 'It makes older water appear chemically identical to rock'], 3, 'Decay or loss restricts its usefulness for older groundwater.'],
  ]),
  ...listeningGroup('talk-price', 'Listen to an Academic Talk', '미시경제학', 'C1', 'Price discrimination occurs when a seller charges different prices that are not fully explained by cost differences. A student discount can fill otherwise empty seats by attracting buyers with lower willingness to pay, while regular customers pay more. For the strategy to work, the seller must distinguish customer groups and limit resale between them. The practice can increase total output, but its distributional effect depends on who receives the lower price and whether the seller gains market power.', [
    ['Why must resale be limited for the pricing strategy to persist?', ['Low-price buyers could otherwise sell to customers targeted for higher prices', 'Cost differences would automatically vanish after every purchase', 'Students would become unable to occupy empty seats', 'Sellers could no longer distinguish identical physical products'], 0, 'Arbitrage undermines separation between price groups.'],
    ['Why is the welfare effect not characterized as uniformly beneficial?', ['Expanded sales and the allocation of gains can affect groups differently', 'Different prices always reduce the number of transactions to zero', 'Market power is unrelated to how surplus is distributed', 'A lower student price necessarily raises production cost'], 2, 'Output may rise while distribution and market-power consequences remain ambiguous.'],
  ]),
  ...listeningGroup('talk-thermal-inertia', 'Listen to an Academic Talk', '행성과학', 'C1', 'A surface with high thermal inertia changes temperature slowly because it stores and conducts heat effectively. On a planet, exposed rock may remain warm after sunset, whereas fine dust cools quickly. Orbiting instruments measure daily temperature cycles and use them to infer surface texture. The inference is indirect: slope orientation, shadows, subsurface layering, and atmospheric conditions can produce similar temperature patterns. Scientists combine thermal images with topography and observations at multiple times of day to reduce ambiguity.', [
    ['What property can be inferred from the rate of surface temperature change?', ['The likely ability of the material to store and conduct heat', 'The exact chemical formula of every buried mineral', 'The age of the planet’s entire atmosphere', 'The number of shadows present at local noon'], 1, 'Thermal inertia links the cycle’s speed and amplitude to material behavior.'],
    ['Why are topographic data useful in this analysis?', ['They help separate material effects from heating differences caused by terrain', 'They guarantee that subsurface layers have identical composition', 'They replace the need for temperature observations at other times', 'They show that fine dust always remains warmer overnight'], 3, 'Slope and shadow alter illumination and can mimic material contrasts.'],
  ]),
]

const sentenceData: Array<[string, string, string[], string]> = [
  ['Why was the apparent trend misleading?', 'What the graph failed', ['to show was', 'that the measurement', 'procedure had changed', 'halfway through', 'the study'], 'f05-pseudo-cleft-infinitive'],
  ['Could the samples have been preserved?', 'Had they been', ['placed immediately', 'in sealed containers', 'less material', 'would have', 'degraded'], 'f05-inverted-third-conditional-passive'],
  ['Why did the editor request another citation?', 'The claim was', ['too consequential', 'to be accepted', 'without evidence', 'independent of', 'the original study'], 'f05-too-infinitive-preposition'],
  ['Did the policy affect every district equally?', 'Not only did', ['the initial conditions', 'differ considerably', 'but local officials', 'also implemented it', 'in distinct ways'], 'f05-not-only-inversion'],
  ['How should the null result be interpreted?', 'It does not establish', ['that no effect', 'exists but rather', 'that this experiment', 'was unable', 'to detect one'], 'f05-not-but-rather-clause'],
  ['Why preserve the metadata?', 'Without them', ['future analysts', 'would be unable', 'to determine', 'how the variables', 'were constructed'], 'f05-without-counterfactual'],
  ['Can the model be generalized?', 'Whether it applies', ['outside the sampled', 'population remains', 'to be tested', 'under substantially', 'different conditions'], 'f05-subject-whether-raising'],
  ['Why did the witness hesitate?', 'She spoke', ['as though', 'she had been', 'asked to recall', 'an event', 'she barely remembered'], 'f05-as-though-past-perfect-passive'],
  ['What makes the mechanism plausible?', 'Consistent with the theory', ['are several findings', 'that would otherwise', 'be difficult', 'to explain', 'together'], 'f05-subject-complement-inversion'],
  ['Should we exclude the incomplete records?', 'Before doing so', ['we ought to examine', 'whether their absence', 'is related to', 'the outcome', 'being estimated'], 'f05-before-gerund-embedded-passive'],
]

const writing: BaseItem[] = sentenceData.map(([prompt, starter, fragments, grammarFocus], index) => {
  const item = base(`sentence-${index}`, 'writing', 'sentence-build', 'Build a Sentence', '고급 문장 구조', index < 2 ? 'B2' : 'C1', 75)
  const tiles = prepareSentenceTiles(fragments, item.id)
  return { ...item, instruction: '모든 단어와 구를 한 번씩 사용해 자연스럽고 정확한 문장을 완성하세요.', prompt, starter, words: tiles.choices, answer: tiles.answer, grammarFocus, explanation: `${starter} ${tiles.correct.join(' ')}` }
})
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '공동 장비 사용', 'B2', 420), instruction: '독자와 상황에 맞게 문제, 영향, 해결 요청을 분명히 작성하세요.', prompt: 'You reserved a shared imaging instrument, but the previous user left an undocumented configuration that may affect your measurements. Write to the laboratory manager. Describe what you found, explain why proceeding could compromise the data, and request both immediate guidance and a longer-term documentation change.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '문화유산 보존', 'C1', 600), instruction: '다른 학생의 관점을 평가하며 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Haddad: When preserving a historic site conflicts with present-day community needs, what principles should guide the decision?', passage: 'Sofia: Irreplaceable historical evidence deserves strong protection because future generations cannot recover it once destroyed.\nMalik: Preservation loses legitimacy if residents bear costs while receiving little access, housing, or economic benefit.' })

const repeatSentences = [
  'Welcome to the university greenhouse orientation.',
  'Stay on the marked paths between research benches.',
  'Some plants are under quarantine and must not be touched.',
  'Read the colored label before watering any experimental specimen.',
  'Use the cleaning station before entering another climate-controlled room.',
  'Report insects to staff instead of applying any treatment yourself.',
  'At the end of your visit, return every tool and record any accidental contact in the facility log.',
]
const interviewQuestions = [
  'Describe a place that should be preserved for future generations.',
  'What kinds of evidence make a place historically important?',
  'How should preservation costs be shared between visitors, governments, and local residents?',
  'Can changing a historic place sometimes be the best way to keep it meaningful?',
]
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '온실 이용 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '문장을 한 번 듣고 준비 시간 없이 의미와 리듬을 살려 반복하세요.', audioText, stimulusGroupId: 'f05-repeat', scenarioId: 'f05-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '역사 장소의 보존', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f05-interview', scenarioId: 'f05-interview', sequenceIndex })),
]

export const AUTHORED_FORM_05_ITEMS: BaseItem[] = [
  ...reading.slice(0, 11).map((item) => ({ ...item, module: 1 })), ...reading.slice(11).map((item) => ({ ...item, module: 2 })),
  ...responses.slice(0, 9).map((item) => ({ ...item, module: 1 })), ...conversations.slice(0, 5).map((item) => ({ ...item, module: 1 })), ...announcements.slice(0, 4).map((item) => ({ ...item, module: 1 })), ...talks.slice(0, 6).map((item) => ({ ...item, module: 1 })),
  ...responses.slice(9).map((item) => ({ ...item, module: 2 })), ...conversations.slice(5).map((item) => ({ ...item, module: 2 })), ...announcements.slice(4).map((item) => ({ ...item, module: 2 })), ...talks.slice(6).map((item) => ({ ...item, module: 2 })),
  ...writing, ...speaking,
]

export const AUTHORED_FORM_05_IDS = AUTHORED_FORM_05_ITEMS.map((item) => item.id)
