import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f11')

const reading: BaseItem[] = [
  cloze('cloze-splicing', '분자유전학', 'C1', 'Many eukaryotic genes contain introns that are removed from RNA before translation. A molecular complex rec___ sequence signals, cuts the initial transcript, and jo___ the remaining exons. Alternative splicing can comb___ exons in different ways, allowing one gene to produce several RNA products. The process is tightly reg___ by cell type and developmental stage. A change in a splice site may disr___ protein function, but not every unusual transcript causes disease. Researchers quant___ isoforms across tissues and test their effects experimentally. Short sequencing reads can make closely related isoforms dif___ to distinguish, so long-read methods may imp___ reconstruction. Splicing expands molecular diversity without alt___ the underlying DNA sequence and dem___ why gene number alone does not predict organismal complexity.', 'ognizes|ins|ine|ulated|upt|ify|ficult|rove|ering|onstrates'),
  cloze('cloze-groundwater', '도시수문학', 'C1', 'Groundwater beneath a city interacts with pipes, foundations, tunnels, and paved surfaces. Leaking water mains can rechar___ an aquifer, while pumping for construction may low___ the water table. Impermeable pavement red___ direct infiltration but channels runoff toward drains or parks. Because several human flows overlap, a rising well level does not nec___ indicate increased rainfall. Researchers comp___ chemical tracers, pipe records, and hydraulic measurements to iden___ sources. Subsidence can occ___ when pumping compacts sediments, whereas a high water table can dam___ basements. Management therefore req___ coordination among utilities and planners. Long-term monitoring helps distin___ temporary construction effects from persistent changes.', 'ge|er|uces|essarily|bine|tify|ur|age|uires|guish'),
  cloze('cloze-fresco', '미술보존학', 'B2', 'A true fresco is painted onto fresh lime plaster. As the plaster dri___, pigments become bound within a mineral surface. The artist must work in sections that can be comp___ before the plaster sets. Later additions may be applied to dry plaster and often adh___ less securely. Moisture moving through a wall can dis___ salts, which crystallize near the surface and cau___ paint to flake. Conservators first inv___ the wall’s water source rather than simply reattaching color. Imaging can dif___ original fresco from later repairs. Cleaning tests begin in tiny areas because pigments rea___ differently. Treatment aims to sta___ surviving material and doc___ changes, not to recreate every lost detail.', 'es|leted|ere|solve|se|estigate|ferentiate|ct|bilize|ument'),
  daily('daily-biobank', '생명자원 관리', 'C1', 'Biobank samples may be released only for analyses covered by participant consent and the approved data-use plan. A collaborator added after approval must sign the access agreement before receiving coded specimens. Removing names does not eliminate this requirement.', ['What must a newly added collaborator do before receiving samples?', ['Complete the biobank access agreement', 'Rely on the absence of participant names', 'Rewrite the original participant consent', 'Analyze specimens before joining the approved plan'], 0, 'Coded status does not replace user authorization.']),
  daily('daily-art-delivery', '전시 운영', 'B2', 'Artwork deliveries use the museum loading dock between eight and eleven. Couriers arriving later must wait for a new dock slot; security staff at the public entrance cannot accept crates. Condition reports should travel separately from the object inside a waterproof envelope.', ['What happens when an art courier misses the dock window?', ['A new loading appointment is required', 'The crate may be left at the visitor entrance', 'Security signs the condition report immediately', 'The object can be stored without documentation'], 0, 'The public entrance is not an alternative receiving point.']),
  daily('daily-speech-clinic', '학생 지원', 'B1', 'The communication clinic offers screening appointments and longer therapy sessions. New clients book a screening first. A faculty referral is helpful but does not reserve treatment time; recommendations are made after the screening.', ['What is the first step for a new client?', ['Schedule an initial screening', 'Reserve recurring therapy through a professor', 'Begin treatment before evaluation', 'Submit a referral as a guaranteed booking'], 0, 'Service placement follows the screening.']),
  daily('daily-drone-data', '공간정보 연구', 'B2', 'Drone images containing identifiable people must remain in the restricted project folder until faces and vehicle plates are blurred. Low-resolution preview copies may be shared with collaborators only after the privacy officer verifies the masking method.', ['When may a preview be shared outside the restricted folder?', ['After the masking process receives privacy verification', 'As soon as image resolution is reduced', 'Before identifiable vehicles are obscured', 'Whenever the drone flight had location approval'], 0, 'Flight authorization and image privacy are separate checks.']),
  daily('daily-orchestra-seating', '공연 운영', 'B1', 'Orchestra seating assignments will be posted Monday. Requests based on instrument setup or accessibility should go to the stage manager by Sunday. Preferences for sitting beside a friend are not considered, and musicians should not exchange seats privately.', ['Which request may affect a seating assignment?', ['One concerning an accessibility need', 'One based only on friendship', 'An unreported private exchange', 'A preference submitted after the concert'], 0, 'Functional and accessibility needs receive formal review.']),
  daily('daily-dry-ice', '실험실 배송', 'C1', 'Dry ice shipments must use ventilated packaging because the solid releases carbon dioxide gas. Do not place the package in a sealed refrigerator or passenger compartment. The shipping label must show the net dry-ice mass even when the biological contents are nonhazardous.', ['Why must the outer package allow ventilation?', ['Gas from sublimation could otherwise build dangerous pressure', 'Ventilation keeps dry ice above room temperature', 'Biological samples produce the shipping label', 'A sealed compartment prevents carbon dioxide formation'], 0, 'Sublimation continues and gas needs an escape route.']),
  daily('daily-copyright', '수업 자료', 'B2', 'A professor may link to a licensed library article from the course page but should not upload a downloaded publisher PDF to a public website. Students retain course-page access through the term. Anyone needing access afterward should save the citation, not redistribute the file.', ['What may be placed on the restricted course page?', ['A link routing students through the library license', 'A publisher file on an unrestricted public site', 'A copied article redistributed after the term', 'A citation with no route to current licensed access'], 0, 'Linking respects access terms without republishing the file.']),
  daily('daily-hydrophone', '해양 장비', 'B2', 'Hydrophones returning from salt water should be rinsed with fresh water before their connectors are opened. A wet connector may look clean but can carry salt into the housing. Report any cracked seal before charging the instrument.', ['What should occur before opening a hydrophone connector?', ['Rinse the exterior after marine use', 'Charge the device despite a cracked seal', 'Open the wet housing to let salt enter', 'Judge cleanliness only by appearance'], 0, 'Fresh-water rinsing prevents concealed salt transfer.']),
  daily('daily-thesis-defense', '대학원 행정', 'B2', 'Defense announcements must be posted ten days in advance. If a committee member changes after posting, submit the revised approval form, but the defense date need not move unless the committee no longer meets membership rules.', ['When would a committee change force rescheduling?', ['When the revised group fails formal membership requirements', 'Whenever any name differs from the announcement', 'Only after the defense has occurred', 'When the revised form is submitted on time'], 0, 'Composition rules, not change alone, determine validity.']),
  daily('daily-bike-repair', '교통 지원', 'B1', 'The bicycle repair station provides tools and air pumps but no staff mechanic. Users may borrow a tire lever with identification and return it before the desk closes. Parts such as tubes and brake pads must be supplied by the rider.', ['What does a rider need to bring?', ['Replacement parts required for the repair', 'Every tool available at the station', 'A mechanic employed by the university', 'An air pump for ordinary inflation'], 0, 'The station supplies tools but not consumable components.']),
  ...readingGroup('academic-propensity', '관찰연구 방법론', 'C1', 'A propensity score is the estimated probability of receiving a treatment given observed background variables. Researchers may match, weight, or stratify observations using this score to improve balance between treated and untreated groups. Balance, not predictive accuracy alone, is the central diagnostic for causal use. The method cannot control a confounder that was not measured or was measured poorly. Including variables caused by treatment can also introduce bias. Analysts specify the covariates using knowledge of the treatment process, examine overlap in scores, and avoid making claims for treated cases with no comparable controls.', [
    ['What is the principal purpose of a propensity score in this context?', ['To create more comparable groups on observed pretreatment characteristics', 'To maximize treatment prediction regardless of balance', 'To recover every unmeasured confounder', 'To turn post-treatment variables into baseline causes'], 0, 'The score supports design-based balance among observed covariates.'],
    ['Why is strong treatment prediction not sufficient evidence of success?', ['A predictive model may still leave important covariates imbalanced', 'Causal analysis requires every score to equal one half', 'Prediction automatically measures hidden variables', 'Balance matters only after the outcome is analyzed'], 0, 'The relevant criterion is group comparability, not classification performance.'],
    ['What problem arises when treated units lack overlapping controls?', ['Their effects require extrapolation beyond comparable observations', 'Their treatment status becomes unknown', 'All untreated units must then be discarded', 'The propensity score controls unobserved causes perfectly'], 0, 'No common support means the data provide weak counterfactual evidence.'],
  ]),
  ...readingGroup('academic-phenology', '생태기후학', 'C1', 'Phenology is the timing of recurring biological events such as flowering, migration, or insect emergence. Many spring events now occur earlier as temperatures warm, but temperature is not the only cue. Day length remains unchanged by climate, and some species require winter chilling before responding to spring warmth. Interacting cues can therefore produce different rates of change among species. If a plant flowers before its pollinator emerges, their historical overlap may shrink. Long records from herbarium specimens, diaries, and monitoring networks help reveal trends, although observation effort and location must be accounted for.', [
    ['Why might two interacting species shift their timing differently?', ['They may respond to distinct combinations of temperature, light, and winter exposure', 'Day length becomes longer each year as climate warms', 'Every biological event uses temperature as its sole cue', 'Pollinators always emerge before flowering plants'], 0, 'Different cue systems yield mismatched phenological responses.'],
    ['What methodological concern applies to long phenology records?', ['Changes in who observed where can resemble biological timing change', 'Historical specimens contain no date information', 'Monitoring networks eliminate geographic variation', 'Diaries always measure temperature directly'], 0, 'Sampling effort and spatial coverage can confound trends.'],
  ]),
  ...readingGroup('academic-ancient-dna', '고유전체학', 'C1', 'Ancient DNA is fragmented, chemically damaged, and easily overwhelmed by modern contamination. Researchers work in clean rooms, sample protected parts of bones, and include blank controls that pass through extraction without ancient material. Genuine ancient molecules often show characteristic damage near fragment ends, but damage alone is not proof because laboratory processes can create artifacts. Independent replication, sex-chromosome patterns, and the proportion of sequences matching expected ancestry provide additional checks. Aggressive removal of damaged reads may reduce contamination while also discarding authentic information, so pipelines must balance specificity and sensitivity.', [
    ['What do blank extraction controls reveal?', ['Contamination introduced by reagents or laboratory handling', 'The ancestry of the sampled ancient person', 'Whether protected bone contains more DNA', 'The exact age of every recovered fragment'], 0, 'A blank tracks modern material added without a specimen.'],
    ['Why is terminal molecular damage useful but inconclusive?', ['It is typical of ancient DNA but can be mimicked by technical artifacts', 'It occurs only in long intact modern chromosomes', 'It identifies a person’s sex without sequencing', 'It guarantees that every read is authentic'], 0, 'The signature supports age but needs corroboration.'],
    ['What trade-off is involved in filtering damaged sequences?', ['Stricter cleaning may remove both contamination and real ancient molecules', 'Keeping every read eliminates modern contamination', 'Specificity and sensitivity always increase together', 'Authentic ancient DNA never contains chemical damage'], 0, 'A filter can reduce false positives at the cost of true signal.'],
  ]),
  ...readingGroup('academic-lexical', '역사언어학', 'C1', 'A sound change does not always affect every eligible word at once. In lexical diffusion, a new pronunciation spreads gradually through the vocabulary, appearing earlier in some words than others. Frequency can matter because common words are practiced often, but its effect differs across changes: frequent items may lead reductive changes yet resist changes that require careful analogy. Social groups and speaking styles also influence adoption. Researchers compare speakers of different ages and track individual words rather than assuming a categorical rule. Apparent lexical diffusion can sometimes result from borrowing words between dialects, so histories of contact must be considered.', [
    ['What distinguishes lexical diffusion from an instantaneous sound rule?', ['Eligible words adopt the new form at different times', 'Every speaker changes every word in one moment', 'Vocabulary frequency has an identical effect on all changes', 'Pronunciation never varies by social setting'], 0, 'The change advances item by item through the lexicon.'],
    ['Why must dialect contact be examined?', ['Borrowing may create a word-by-word pattern resembling internal spread', 'Contact forces every word to maintain its oldest pronunciation', 'Dialect history makes age comparisons impossible', 'Borrowed vocabulary cannot undergo sound change'], 0, 'External transfer is an alternative mechanism for the observed distribution.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you check whether the calibration gas has expired?', ['I’ll compare the cylinder date with the inventory record.', 'The gas expands when heated.', 'Calibration improves measurement accuracy.', 'I expired the old access code.'], 0, 'The date record answers the request.'),
  response(1, 'Why was the student exhibition shortened?', ['The exhibition includes thirty prints.', 'The gallery was booked for another event.', 'I shortened the introduction by one paragraph.', 'Students install the work themselves.'], 1, 'A scheduling conflict explains the shorter run.'),
  response(2, 'Have the interview files been de-identified?', ['The interviews lasted about an hour.', 'Identification cards are stored securely.', 'All except the transcript awaiting name review.', 'I filed the consent forms alphabetically.'], 2, 'The reply reports progress and one remaining exception.'),
  response(3, 'Would you be willing to monitor the poster session?', ['The posters are arranged by topic.', 'Monitoring requires a charged tablet.', 'The session begins in the east hall.', 'Yes, as long as someone covers my first ten minutes.'], 3, 'The speaker accepts with a relevant coverage condition.'),
  response(4, 'I thought the equipment fee covered consumable filters.', ['It covers instrument time, but supplies are billed separately.', 'The filter removes small particles.', 'Fees appear on the monthly statement.', 'I covered the samples with foil.'], 0, 'The reply distinguishes instrument and supply charges.'),
  response(5, 'Where should I leave the signed field permits?', ['The permits list three sampling sites.', 'In the locked tray outside the coordinator’s office.', 'I left the trail before sunset.', 'Fieldwork depends on careful preparation.'], 1, 'The secure submission location is given.'),
  response(6, 'Shouldn’t the blind reviewer receive a file without author names?', ['Reviewers submit comments through the journal portal.', 'The authors collected data at two sites.', 'Yes, and acknowledgments should be masked too.', 'I reviewed the named variables yesterday.'], 2, 'Both direct and indirect identifying text should be removed.'),
  response(7, 'The greenhouse humidity rose after the software update.', ['Humidity affects plant transpiration.', 'The update installed without an error.', 'Greenhouses contain several climate zones.', 'Compare the raw sensor output before changing the set point.'], 3, 'Verification should precede a control change.'),
  response(8, 'Can I cite the working paper as the final study?', ['No, label its current version and update the citation if it changes.', 'The final examination includes a research paper.', 'Citation software supports many styles.', 'I worked on the paper all weekend.'], 0, 'Version status must be represented accurately.'),
  response(9, 'Why did the archive deny the reproduction request?', ['The archive closes during national holidays.', 'The donor agreement prohibits commercial publication.', 'I reproduced the chart in vector format.', 'Requests usually take ten business days.'], 1, 'A rights restriction explains denial.'),
  response(10, 'Could differential testing explain the score gap?', ['The test has forty multiple-choice items.', 'The gap appears in the second semester.', 'Possibly, if one group received more practice with the format.', 'I tested the cable with another device.'], 2, 'Unequal familiarity is a plausible measurement confound.'),
  response(11, 'I can’t reconcile the sample labels with the freezer map.', ['The freezer has six shelves.', 'Labels should resist low temperatures.', 'Mapping helps visualize spatial data.', 'Quarantine the unmatched boxes until the chain of custody is checked.'], 3, 'Isolation prevents compounding an identity error.'),
  response(12, 'Is the public lecture being recorded?', ['Yes, but audience questions will be removed unless speakers consent.', 'The lecture examines public transportation.', 'Recordings are stored in the media archive.', 'I recorded the temperature every hour.'], 0, 'The reply confirms recording with a privacy limit.'),
  response(13, 'When will the updated accessibility map be posted?', ['The map uses high-contrast symbols.', 'Facilities expects to publish it tomorrow morning.', 'I posted the parcel at noon.', 'Accessibility requires more than one design feature.'], 1, 'The response directly supplies timing.'),
  response(14, 'Would excluding extreme values stabilize the variance?', ['Variance measures dispersion around a mean.', 'Extreme weather affected the field season.', 'Perhaps, but exclusion needs a rule independent of the result.', 'The values appear in scientific notation.'], 2, 'Outcome-driven trimming risks bias.'),
  response(15, 'Who approved changing the excavation boundary?', ['The boundary follows the old stone wall.', 'Approval is documented in the field log.', 'Excavation uses square grid units.', 'The site director authorized the revised permit map.'], 3, 'The responsible authority and record are identified.'),
  response(16, 'The imaging software applied sharpening to every raw file.', ['Disable the preset and restore originals from the acquisition archive.', 'Sharpening can make edges appear clearer.', 'Every file has a unique catalog name.', 'I applied for access last month.'], 0, 'Raw restoration and preset correction address the processing error.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-deposit', 'Listen to a Conversation', '연구비 행정', 'B2', 'Student: The conference hotel charged a deposit now, but my trip is next fiscal year. Can I reimburse it this month? Administrator: The charge belongs to the travel period unless the award specifically allows prepayment. Keep the receipt, but do not submit it against this year’s account. Student: The current grant closes soon. Administrator: Ask the grant officer whether the cost can transfer to the renewal. We cannot move the date simply because funds expire.', [
    ['Why can the deposit not automatically be charged now?', ['Its allowable period depends on the trip and award terms', 'Hotel deposits never receive reimbursement', 'The receipt does not show any payment', 'The next fiscal year has already ended'], 0, 'Accounting eligibility is not changed by a closing balance.'],
    ['What should the student do next?', ['Consult the grant officer about charging the renewal', 'Alter the receipt date to the current year', 'Submit the expense without travel documentation', 'Cancel the conference immediately'], 0, 'The possible solution requires formal funding guidance.'],
  ]),
  ...listeningGroup('conversation-ventilation', 'Listen to a Conversation', '도예 스튜디오', 'B2', 'Student: The glaze booth fan is running, but I can smell solvent near the door. Technician: Stop spraying and leave the booth closed. The fan sound does not prove adequate capture. I will test airflow at the opening and check whether the filter is blocked. Student: Should I turn the fan to maximum? Technician: No, use only approved controls. Changing the setting could spread contaminated air into the room.', [
    ['Why is fan noise not sufficient reassurance?', ['Operation sound does not establish safe airflow direction or volume', 'Solvent is harmless whenever a filter is present', 'The booth door must remain open during spraying', 'Maximum speed always prevents room contamination'], 1, 'Ventilation performance requires measurement.'],
    ['What is the student instructed to avoid?', ['Adjusting ventilation beyond authorized settings', 'Stopping the spraying process', 'Leaving the booth closed for inspection', 'Reporting the odor to technical staff'], 1, 'Unapproved adjustment could worsen exposure.'],
  ]),
  ...listeningGroup('conversation-species', 'Listen to a Conversation', '생태 데이터', 'C1', 'Researcher: Our automated classifier reports twice as many frog calls this year. Assistant: The new model is more sensitive, so counts across years are not directly comparable. Researcher: Could we rerun last year’s audio through the new model? Assistant: Yes. Then manually validate a stratified sample from both years. If noise conditions changed, equal software will not eliminate every detection difference.', [
    ['What confounds the apparent annual increase?', ['The detection algorithm changed between years', 'The same recordings were analyzed twice', 'Manual validation reduced the number of calls', 'Frog abundance cannot vary over time'], 2, 'Measurement sensitivity changed along with the reported outcome.'],
    ['Why is reprocessing old audio not a complete solution?', ['Background conditions may still differ between recording periods', 'The new model cannot analyze archived files', 'Stratified validation eliminates all environmental noise', 'Software sensitivity is unrelated to call detection'], 2, 'A common classifier fixes one component but not the input environment.'],
  ]),
  ...listeningGroup('conversation-label', 'Listen to a Conversation', '박물관 교육', 'C1', 'Student: My exhibit label says the necklace belonged to a queen, but the accession record says only “elite burial.” Curator: Then the label overstates the evidence. Explain that it was found in a richly furnished grave and that earlier catalogs proposed a royal owner. Student: Will visitors find that uncertainty frustrating? Curator: Not if you show why interpretations differ. Precision is more credible than an unsupported dramatic claim.', [
    ['What revision does the curator recommend?', ['Separate archaeological evidence from a less certain earlier interpretation', 'Remove all mention of the burial context', 'State royal ownership as an established fact', 'Replace the accession record with the label'], 3, 'The revised wording preserves evidence and hypothesis at different confidence levels.'],
    ['Why include the history of interpretation?', ['It can make evidential revision understandable rather than merely vague', 'It proves that the earliest catalog must be correct', 'It guarantees that visitors prefer dramatic certainty', 'It eliminates the need to describe the grave'], 3, 'Explaining the basis of disagreement gives uncertainty structure.'],
  ]),
  ...listeningGroup('conversation-choir', 'Listen to a Conversation', '공연 제작', 'B2', 'Conductor: The choir recording sounds balanced on headphones but the alto line disappears on the hall speakers. Engineer: The headphone mix is stereo, while the hall system is currently summing it to mono. If two microphones captured that section out of phase, cancellation could occur. Conductor: Should we raise the alto channel? Engineer: First reverse the polarity on the test mix. More volume will not restore frequencies being canceled.', [
    ['What may be causing the missing vocal line?', ['Phase cancellation when stereo channels are combined', 'The alto channel was never recorded', 'Headphones cannot reproduce stereo sound', 'Hall speakers increase every frequency equally'], 0, 'Opposing signals can cancel in mono playback.'],
    ['Why does the engineer test polarity before volume?', ['Amplification cannot fix destructive interference', 'Polarity determines the written musical pitch', 'The hall system has no volume control', 'A louder channel always causes more cancellation'], 1, 'The signal relationship, not simply level, is the likely problem.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-chiller', 'Listen to an Announcement', '연구 시설', 'B2', 'The central chiller will be offline Wednesday from seven to nine. Rooms with independent cooling are unaffected, but laboratories relying on chilled water should suspend heat-producing equipment before seven. Emergency ventilation remains active. Facilities will confirm restoration by message; do not restart equipment merely because pipe noise returns.', [
    ['Which laboratories need to stop heat-producing devices?', ['Those dependent on the central chilled-water loop', 'Every room with independent cooling', 'Only rooms without emergency ventilation', 'Offices using ordinary desktop computers'], 0, 'The outage targets the shared cooling system.'],
    ['What authorizes equipment restart?', ['An explicit restoration notice from facilities', 'Any sound heard inside a pipe', 'The beginning of the maintenance window', 'Operation of emergency ventilation alone'], 0, 'Observed noise is not proof of restored cooling.'],
  ]),
  ...listeningGroup('announcement-mentors', 'Listen to an Announcement', '학생 프로그램', 'B1', 'Applications for peer mentors close Thursday. Returning mentors submit only their availability, while new applicants also provide one faculty reference. Training is Saturday morning. A class conflict may be accommodated with a recorded module, but employment or travel conflicts do not waive training.', [
    ['What extra item must a first-time applicant provide?', ['A reference from a faculty member', 'A recording of Saturday training', 'Proof of previous mentor service', 'A travel schedule for the weekend'], 1, 'The reference distinguishes new from returning applicants.'],
    ['Which conflict may qualify for alternative training?', ['A scheduled academic class', 'Optional weekend travel', 'A work shift unrelated to class', 'Failure to submit availability'], 1, 'Only the class conflict receives the recorded accommodation.'],
  ]),
  ...listeningGroup('announcement-collections', 'Listen to an Announcement', '소장품 보존', 'C1', 'The anthropology collection will freeze incoming textile packages next week as part of pest control. Materials already cleared for display are unaffected. Researchers expecting new loans should not open shipping crates on arrival; staff will inspect wrapping, record temperature-sensitive components, and decide whether freezing is appropriate. Objects containing certain paints or adhesives may require another treatment.', [
    ['What should researchers do with newly arrived loan crates?', ['Leave them sealed for staff assessment', 'Place every object directly into the freezer', 'Move them immediately into the display gallery', 'Remove wrapping before temperature is recorded'], 2, 'Quarantine assessment precedes opening or treatment.'],
    ['Why might staff choose a nonfreezing method?', ['Some materials could be damaged by low temperature', 'Pest control applies only to displayed textiles', 'Shipping crates prevent all insect movement', 'Painted objects never require treatment'], 2, 'Material composition constrains the intervention.'],
  ]),
  ...listeningGroup('announcement-poetry', 'Listen to an Announcement', '문학 행사', 'B2', 'The poetry reading has moved to the smaller gallery. Doors open at six thirty, and reserved seats are held until six fifty. Because the gallery is beside an active exhibition, audience members must leave coats and large bags in the free lockers downstairs. Late arrivals will be seated only between poets.', [
    ['When may an unclaimed reserved seat be released?', ['After the stated ten-minute holding period ends', 'As soon as doors open at six thirty', 'Only after the final poet finishes', 'Before lockers become available'], 3, 'Reservations are protected until six fifty.'],
    ['Why are large belongings stored downstairs?', ['The reading shares space with an active exhibition', 'The gallery has no audience seating', 'Late visitors must carry coats between poems', 'The lockers require a separate admission fee'], 3, 'The adjacent collection imposes object-safety restrictions.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-superconductivity', 'Listen to an Academic Talk', '응집물질물리학', 'C1', 'Below a critical temperature, some materials enter a superconducting state with effectively zero electrical resistance. They also expel magnetic field from their interior, a phenomenon called the Meissner effect. Zero resistance alone is not the whole definition because a hypothetical perfect conductor could preserve a field already inside it. Strong magnetic fields or currents can destroy superconductivity, and practical wires require cooling. High-temperature superconductors operate warmer than conventional ones but still far below ordinary room temperature.', [
    ['What distinguishes a superconductor from a simple perfect conductor?', ['It actively excludes magnetic field when entering the state', 'It preserves every magnetic field inside itself', 'It functions only with high electrical resistance', 'It must remain at room temperature'], 0, 'The Meissner effect is a thermodynamic signature beyond zero resistance.'],
    ['Why does “high-temperature” not mean ordinary ambient operation?', ['The term is relative to even colder conventional superconductors', 'These materials lose resistance only when heated above boiling', 'Cooling always destroys the superconducting state', 'Critical temperature measures electrical current'], 0, 'The category is warmer by comparison, not warm in everyday terms.'],
  ]),
  ...listeningGroup('talk-commons', 'Listen to an Academic Talk', '환경거버넌스', 'C1', 'A common-pool resource is difficult to exclude people from using, yet one person’s use reduces what remains for others. Fisheries and irrigation systems can have these properties. Open access may encourage overuse, but collapse is not inevitable. Communities sometimes develop boundaries, monitoring, graduated sanctions, and conflict-resolution procedures. The success of local governance depends on ecology, trust, and authority; one institutional template does not fit every resource. State regulation and private rights are alternatives, but they also require information and enforcement.', [
    ['Why can open access create overuse incentives?', ['Users receive private benefits while sharing depletion costs', 'One person’s harvest increases the remaining stock', 'Exclusion is always costless and complete', 'Monitoring automatically restores the resource'], 1, 'Individual gains and collective losses are misaligned.'],
    ['What does the lecture imply about community governance?', ['It can work under certain institutional and ecological conditions', 'It succeeds without monitoring or conflict procedures', 'It is universally superior to state regulation', 'It requires identical rules for every resource'], 1, 'Local solutions are possible but context-dependent.'],
  ]),
  ...listeningGroup('talk-metamemory', 'Listen to an Academic Talk', '인지심리학', 'C1', 'Metamemory refers to judgments about one’s own learning and recall. Immediately after studying, material may feel fluent because it is still active, leading learners to overpredict later memory. Delaying a judgment and attempting retrieval can produce better calibration. Confidence is also influenced by familiarity and answer speed, neither of which guarantees accuracy. Researchers compare predicted performance with actual tests and examine both calibration—the match between confidence and accuracy—and resolution, the ability to distinguish stronger from weaker memories.', [
    ['Why can an immediate learning judgment be overoptimistic?', ['Temporary processing fluency is mistaken for durable retention', 'Delayed retrieval always makes every item familiar', 'Fast answers necessarily remain correct over time', 'Calibration measures only average response speed'], 2, 'Ease at study can fade before the later test.'],
    ['What does resolution measure?', ['Whether confidence ranks relatively strong and weak memories correctly', 'Whether mean confidence equals mean accuracy only', 'How quickly study material is first presented', 'Whether every prediction is equally high'], 2, 'Resolution concerns discrimination across items.'],
  ]),
  ...listeningGroup('talk-pollen', 'Listen to an Academic Talk', '고환경학', 'C1', 'Pollen grains preserved in lake sediment can reconstruct past vegetation. Their resistant outer walls often retain identifiable shapes, but pollen abundance does not equal local plant abundance. Wind-pollinated trees may produce enormous quantities carried over long distances, whereas insect-pollinated plants contribute less. Researchers calibrate modern pollen rain against known vegetation and compare multiple sediment depths. A change in pollen can reflect climate, disturbance, or human land use, so charcoal, plant macrofossils, and archaeological evidence add context.', [
    ['Why can raw pollen percentages misrepresent nearby vegetation?', ['Species differ greatly in production and transport distance', 'All pollen grains decay before reaching a lake', 'Insect-pollinated plants always dominate sediment', 'Outer-wall shape cannot identify broad plant groups'], 3, 'Representation is filtered by dispersal biology.'],
    ['What is gained by adding charcoal and archaeological evidence?', ['Alternative causes of vegetation change can be evaluated', 'Pollen no longer needs chronological ordering', 'Every grain can be assigned to one individual tree', 'Modern calibration becomes unnecessary'], 3, 'Independent proxies distinguish climate from fire or land use.'],
  ]),
  ...listeningGroup('talk-vot', 'Listen to an Academic Talk', '음성학', 'C1', 'Voice onset time is the interval between releasing a stop consonant and the beginning of vocal-fold vibration. Languages use this continuum differently to distinguish categories such as voiced and voiceless stops. Listeners often perceive a sharp categorical boundary even though the acoustic timing varies continuously. The boundary can shift with language experience and speaking rate. Researchers synthesize a series of sounds differing in small timing steps and ask listeners to identify or discriminate them.', [
    ['What does categorical perception mean here?', ['A continuous timing dimension is heard as discrete speech categories', 'Every acoustic step receives a unique consonant label', 'Vocal-fold vibration begins before all stop releases', 'Language experience cannot affect boundaries'], 0, 'Perceptual classification is sharper than the physical continuum.'],
    ['Why create a controlled series of synthetic sounds?', ['To isolate how changing one timing cue affects identification', 'To remove all measurable differences between tokens', 'To prove speaking rate never matters', 'To replace listener responses with written rules'], 2, 'Small systematic steps reveal category boundaries.'],
  ]),
  ...listeningGroup('talk-caves', 'Listen to an Academic Talk', '동굴지질학', 'C1', 'Stalagmites grow as mineral-rich water drips onto a cave floor and deposits calcium carbonate. Layer chemistry and oxygen isotopes can record changes in rainfall source, temperature, and cave processes. Growth is not always continuous: a dry interval may create a hiatus, while flooding can erode material. Uranium-thorium dating provides ages for selected layers, but interpreting climate requires monitoring modern drip water and comparing nearby records. A single isotope curve rarely maps uniquely onto rainfall amount.', [
    ['Why are modern cave observations important?', ['They connect measured stalagmite chemistry to current environmental processes', 'They guarantee that growth was continuous in the past', 'They replace all radiometric dating', 'They show one isotope responds only to rainfall amount'], 1, 'Calibration clarifies the proxy mechanism.'],
    ['What does a hiatus represent?', ['A break in deposition that interrupts the time sequence', 'A layer with a perfectly known annual rainfall', 'A period of accelerated continuous growth', 'A modern monitoring instrument'], 3, 'No material accumulated during the gap.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why did the matched estimate remain uncertain?', 'Had an important', ['confounder gone', 'unmeasured balance', 'on the recorded', 'variables would', 'not remove it'], 'f11-inverted-past-perfect-counterfactual'],
  ['Did earlier flowering help every species?', 'What benefited one', ['population sometimes', 'reduced its overlap', 'with the insects', 'on which', 'it depended'], 'f11-fused-relative-preposition-relative'],
  ['Why were blank controls processed?', 'So that contamination', ['introduced in', 'the laboratory', 'could be distinguished', 'from authentic', 'ancient material'], 'f11-so-that-passive'],
  ['Can high agreement prove coding validity?', 'By no means', ['does agreement alone', 'establish that', 'both coders', 'applied an', 'appropriate rule'], 'f11-by-no-means-inversion'],
  ['What made the linguistic pattern difficult to date?', 'Not until individual', ['words were tracked', 'did it become', 'clear how', 'gradually the change', 'had spread'], 'f11-not-until-inversion-past-perfect'],
  ['Why preserve the damaged fragments?', 'Imperfect though they', ['are they may', 'contain signals', 'that more selective', 'methods would', 'discard'], 'f11-adjective-though-modal'],
  ['Did the treatment effect apply to all patients?', 'The estimate pertained', ['chiefly to those', 'whose decision', 'had been altered', 'by the', 'eligibility rule'], 'f11-whose-passive-preposition'],
  ['How should the null comparison be described?', 'It is not', ['that the groups', 'were identical', 'but that', 'no meaningful difference', 'was detected'], 'f11-not-that-but-that-passive'],
  ['Could the archival note be contemporary?', 'For that interpretation', ['to hold the ink', 'would have to', 'match materials', 'available at', 'the time'], 'f11-for-infinitive-modal'],
  ['Why was the conclusion revised?', 'Only when the', ['excluded observations', 'were restored', 'did the original', 'pattern cease', 'to appear'], 'f11-only-when-inversion-passive'],
]
const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '생명자원 접근', 'B2', 420), instruction: '문제와 이유, 필요한 절차를 분명히 제시하는 이메일을 작성하세요.', prompt: 'A new collaborator needs coded biobank samples next week, but has not signed the access agreement and is not listed in the approved data-use plan. Write to the project lead. Explain why de-identification alone is insufficient, identify the missing approvals, and propose a compliant timeline.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '생태 시기 변화', 'C1', 600), instruction: '두 학생의 관점을 평가하면서 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Lindström: Should conservation programs actively move species when climate change disrupts the timing of migration, flowering, or food availability?', passage: 'Ava: Assisted movement may prevent extinction when species cannot adjust or disperse quickly enough.\nBen: Moving organisms can create invasive populations and unforeseen interactions in recipient ecosystems.' })

const repeatSentences = ['Welcome to the oral history recording room.', 'Place mobile phones outside the sound-treated booth.', 'Confirm the participant’s preferred name before recording.', 'Read the consent options aloud if any wording is unclear.', 'Keep a separate note of names that require later masking.', 'Pause the interview if the participant wishes to revise an answer.', 'Afterward, save the master file to the restricted server, verify the backup, and store the signed consent separately.']
const interviewQuestions = ['Describe a recurring natural or social event whose timing is important.', 'What factors can cause that event to occur earlier or later?', 'Who is affected when the timing changes?', 'Should people intervene to restore an old schedule or adapt to a new one?']
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '구술사 녹음 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f11-repeat', scenarioId: 'f11-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '시기 변화와 적응', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f11-interview', scenarioId: 'f11-interview', sequenceIndex })),
]

export const AUTHORED_FORM_11_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_11_IDS = AUTHORED_FORM_11_ITEMS.map((item) => item.id)
