import { prepareSentenceTiles } from './sentenceTiles'
import type { BaseItem } from './types'

type Difficulty = NonNullable<BaseItem['difficulty']>
type Question = [prompt: string, options: string[], answer: number, explanation: string]

const base = (id: string, section: BaseItem['section'], kind: BaseItem['kind'], title: string, topic: string, difficulty: Difficulty, timeSeconds: number): BaseItem => ({
  id: `f03-${id}`, section, module: 1, kind, title, topic, difficulty, timeSeconds,
  instruction: '', sourceFamily: 'authored-form-03',
})

const cloze = (id: string, topic: string, difficulty: Difficulty, passage: string, answer: string): BaseItem => ({
  ...base(id, 'reading', 'complete-words', 'Complete the Words', topic, difficulty, 240),
  instruction: '첫 문장을 읽고 문맥·문법·철자에 맞게 열 개 단어를 완성하세요.', passage, answer,
  explanation: '각 어간 뒤에 필요한 철자를 붙였을 때 문맥과 문법 형태가 모두 자연스러워야 합니다.',
})

const daily = (id: string, topic: string, difficulty: Difficulty, passage: string, question: Question): BaseItem => ({
  ...base(id, 'reading', 'multiple-choice', 'Read in Daily Life', topic, difficulty, 75),
  instruction: '실용문을 읽고 조건과 필요한 행동을 파악하세요.', passage,
  prompt: question[0], options: question[1], answer: question[2], explanation: question[3],
})

const readingGroup = (id: string, topic: string, difficulty: Difficulty, passage: string, questions: Question[]): BaseItem[] => questions.map((question, sequenceIndex) => ({
  ...base(`${id}-${sequenceIndex}`, 'reading', 'multiple-choice', 'Read an Academic Passage', topic, difficulty, 120),
  instruction: '학술 지문의 주장, 근거, 한계를 구분해 답하세요.', passage,
  prompt: question[0], options: question[1], answer: question[2], explanation: question[3],
  stimulusGroupId: `f03-${id}`, sequenceIndex,
}))

const response = (id: number, audioText: string, question: Question): BaseItem => ({
  ...base(`response-${id}`, 'listening', 'listen-choice', 'Listen and Choose a Response', '캠퍼스 의사소통', id < 9 ? 'B1' : 'B2', 35),
  instruction: '짧은 말을 듣고 상황에 가장 자연스럽게 이어지는 응답을 고르세요.', audioText,
  options: question[1], answer: question[2], explanation: question[3],
})

const listeningGroup = (id: string, title: string, topic: string, difficulty: Difficulty, audioText: string, questions: Question[]): BaseItem[] => questions.map((question, sequenceIndex) => ({
  ...base(`${id}-${sequenceIndex}`, 'listening', 'listen-choice', title, topic, difficulty, title === 'Listen to an Announcement' ? 55 : title === 'Listen to an Academic Talk' ? 80 : 70),
  instruction: title === 'Listen to an Announcement' ? '공지에서 변경 사항과 청자의 행동을 파악하세요.' : title === 'Listen to an Academic Talk' ? '강의의 중심 내용과 근거 관계를 파악하세요.' : '대화의 문제와 해결 과정을 파악하세요.',
  audioText, prompt: question[0], options: question[1], answer: question[2], explanation: question[3],
  stimulusGroupId: `f03-${id}`, sequenceIndex,
}))

const reading: BaseItem[] = [
  cloze('cloze-coral', '해양화학', 'B2', 'Coral skeletons are built from calcium carbonate. Reef growth dep___ on warm, clear water, but excessive heat can disr___ the partnership between coral and algae. When algae are exp___, the coral turns pale and loses an important energy source. Some colonies rec___ if temperatures fall quickly. Others exp___ prolonged stress and die. Researchers mon___ both heat exposure and recovery, because a single survey may misr___ temporary bleaching as permanent loss. Local pollution can fur___ weaken colonies. Protecting water quality does not stop ocean warming, but it imp___ the chance that reefs res___ after a heat event.', 'ends|upt|elled|over|erience|itor|ead|ther|roves|ist'),
  cloze('cloze-maps', '지도학', 'C1', 'A map always selects some features and omits others. Its scale det___ which details can remain visible. Symbols sim___ complex objects, while color and line weight guide attention. A projection tran___ Earth’s curved surface onto a flat sheet, inevitably dist___ shape, area, distance, or direction. Cartographers cho___ among these compromises according to purpose. A navigation chart emph___ different relationships than a population map. Readers should therefore exa___ the legend and projection before drawing conclusions. Digital maps can upd___ rapidly, but they still ref___ design decisions. No display is entirely neu___, even when its data are accurate.', 'ermines|plify|sfers|orting|ose|asizes|mine|ate|lect|tral'),
  cloze('cloze-rest', '인지심리학', 'B2', 'Sustained attention declines when people monitor an unchanging display for a long time. Brief breaks can res___ performance by interrupting habituation. The benefit does not req___ complete relaxation; even a short switch to another task may help. However, frequent notifications frag___ attention rather than restore it. Effective breaks are inten___ and limited. Workers can sch___ them before accuracy falls sharply. Researchers meas___ both speed and errors, because faster responses may con___ more mistakes. The ideal interval var___ with task demands and individual experience. A thoughtful routine prot___ concentration without creating unnecessary delays and all___ people to resume work efficiently.', 'tore|uire|ment|tional|edule|ure|tain|ies|ects|ows'),
  daily('daily-cold-room', '실험 시설', 'B2', 'The microscopy cold room will be available only by reservation this week. Sessions begin on the hour, and users must finish image exports before their slot ends. Files left on the workstation are deleted automatically at midnight. Researchers needing more than two hours should book consecutive slots under the same project name.', ['What should a researcher do to work in the room for three hours?', ['Save files after midnight', 'Reserve adjoining time slots', 'Create two unrelated project names', 'Begin between scheduled hours'], 1, 'Consecutive reservations provide uninterrupted time under one project.']),
  daily('daily-tutoring', '학습 지원', 'B1', 'Drop-in mathematics tutoring is moving to Room 306 on Mondays. Appointments scheduled for other weekdays remain in the Learning Center. Students seeking help with statistics should bring the software file as well as a description of the problem; tutors cannot access files stored in private course accounts.', ['What is requested from a student asking about statistics?', ['A printed Monday appointment', 'The relevant file and an explanation of the difficulty', 'Access to another student’s course account', 'A reservation for Room 306 every weekday'], 1, 'Tutors need both the working file and a description because they cannot enter private accounts.']),
  daily('daily-ceramics', '예술 스튜디오', 'B2', 'Kiln shelves will be coated on Friday, so no student firings can begin after Thursday evening. Work already inside the kiln will be completed normally. Unfired pieces on the drying racks should remain there; moving damp clay to lockers can cause cracking and will not protect it from the maintenance dust.', ['What should students do with damp, unfired work?', ['Leave it on the designated drying racks', 'Place it inside the operating kiln', 'Seal it in personal lockers', 'Remove it before Thursday evening'], 0, 'The notice explicitly says that the drying racks are the correct location.']),
  daily('daily-reimbursement', '연구비 행정', 'C1', 'Receipts for fieldwork reimbursement must show the payment method and date. A restaurant’s itemized order without proof of payment is insufficient by itself. If the original receipt is unavailable, submit the vendor record together with a card statement that masks all unrelated transactions and all but the final four digits of the account number.', ['Which submission can replace a missing original receipt?', ['An unitemized estimate from the vendor', 'A complete unredacted monthly bank statement', 'A vendor record paired with appropriately masked payment evidence', 'A verbal description approved by another student'], 2, 'The alternative requires both transaction detail and limited proof of payment while protecting unrelated information.']),
  daily('daily-seminar', '대학원 세미나', 'B1', 'The marine-policy seminar welcomes visitors, but Friday’s session includes unpublished survey results. Only enrolled students and invited reviewers may attend that meeting. The following week’s lecture on coastal law is open to everyone and requires no registration.', ['Who may attend this Friday’s restricted session?', ['Any visitor interested in coastal law', 'Enrolled students and specifically invited reviewers', 'Only people who register for next week', 'Members of the public carrying identification'], 1, 'Unpublished results limit attendance to the two named groups.']),
  daily('daily-bike-lockers', '자전거 시설', 'B2', 'Applications for covered bicycle lockers exceed the number available. Priority goes first to commuters who cycle at least four days per week and then to applicants whose buildings lack indoor bicycle storage. Submission time is used only to break a tie between applicants with the same priority.', ['When does applying earlier affect locker allocation?', ['Whenever an applicant cycles fewer than four days', 'Only after the stated priority factors are equal', 'Before indoor storage is considered', 'Whenever demand is lower than supply'], 1, 'Time of submission is a tie-breaker, not the primary criterion.']),
  daily('daily-orchestra', '공연 예매', 'B1', 'Student orchestra tickets become available online at noon. Seats are free, but each account may reserve no more than two. Unclaimed reservations are released fifteen minutes before the performance. Guests arriving after that time may join the standby line even if they previously held a reservation.', ['What happens to a reservation not claimed on time?', ['It changes into a paid ticket', 'It is released for standby admission', 'It guarantees entry after the performance begins', 'It moves automatically to another date'], 1, 'The seat returns to the available pool fifteen minutes before the event.']),
  daily('daily-samples', '지질 표본실', 'C1', 'The teaching collection may be photographed, but labels must remain beside their specimens. Do not rearrange samples to improve a picture. Researchers needing an unobstructed image should request a temporary photography tray from staff, who will record the original cabinet position before moving anything.', ['Why must staff record the cabinet position?', ['To preserve the collection’s documented organization', 'To calculate the camera’s exposure time', 'To assign ownership of each photograph', 'To prevent labels from appearing in an image'], 0, 'Recording location allows moved material to be returned without losing its catalog context.']),
  daily('daily-childcare', '학생 복지', 'B2', 'The conference childcare room accepts children from age three through ten. Space is assigned separately for each conference day, so a Friday confirmation does not guarantee Saturday care. Parents must remain in the conference building and provide a phone number that staff can reach immediately.', ['What must a parent do when requesting care for two days?', ['Receive confirmation for each day', 'Leave the conference building after check-in', 'Register only the older child', 'Use a different phone number on Saturday'], 0, 'Capacity is allocated by day, requiring separate confirmation.']),
  daily('daily-drone', '드론 안전', 'C1', 'Campus drone flights require approval even below the legal altitude limit. The aviation office evaluates crowd density, nearby research equipment, and planned emergency routes. Approval for one location and date cannot be transferred to another flight. Indoor flights in the netted engineering cage follow a separate booking process.', ['Which flight needs a new aviation-office approval?', ['A repeat flight at a different outdoor location', 'A session already booked inside the netted cage', 'A flight conducted under the legal height limit at the approved time', 'A simulation using no physical aircraft'], 0, 'Outdoor approval is specific to both place and date.']),
  ...readingGroup('academic-seeds', '식물생태학', 'C1', 'Seeds of some plant species remain viable in soil for decades, forming a seed bank. This reserve can help vegetation recover after fire or cultivation, but its composition does not mirror the plants currently visible above ground. Species differ in seed longevity, and conditions favorable for germination may occur only occasionally. Researchers sample soil at several depths because older seeds can become buried, yet depth alone is not a reliable clock: animals, roots, and erosion mix soil layers. Germination trials reveal which seeds can still grow, while genetic or imaging methods can detect dormant seeds that fail to sprout under laboratory conditions. Each method therefore answers a different question about potential vegetation.', [
    ['What is the passage mainly explaining?', ['Why every buried seed germinates after a fire', 'Why soil seed banks require multiple sampling and detection methods', 'How visible vegetation exactly predicts dormant seeds', 'Why deeper soil always contains younger material'], 1, 'The passage emphasizes uneven longevity, mixed layers, and complementary methods.'],
    ['Why is soil depth an imperfect measure of seed age?', ['Laboratory light destroys all older seeds.', 'Biological and physical processes redistribute soil.', 'Seeds remain only on the surface after cultivation.', 'Genetic methods cannot identify plant species.'], 1, 'Animals, roots, and erosion can move seeds between layers.'],
    ['What can imaging or genetic methods reveal that a germination trial may miss?', ['Seeds that remain detectable but do not sprout in the trial', 'The exact year in which every seed entered the soil', 'Only the species growing above the sampled location', 'Whether a fire will occur in the next decade'], 0, 'A viable-looking or identifiable dormant seed may not germinate under the chosen laboratory conditions.'],
  ]),
  ...readingGroup('academic-bronze', '재료보존학', 'B2', 'Bronze objects often develop a surface layer as copper in the alloy reacts with air, moisture, and soil chemicals. A stable brown or green patina can slow further reaction and may contain historical information about burial conditions. Conservators do not automatically polish it away. By contrast, powdery pale-green spots may indicate an active chloride reaction sometimes called bronze disease. Because this reaction can continue in humid air, treatment focuses on removing or stabilizing chlorides and controlling moisture rather than restoring a uniformly shiny surface.', [
    ['Why might a conservator preserve a stable patina?', ['It can protect the surface and retain evidence about the object’s environment.', 'It proves that the alloy contains no copper.', 'It guarantees that chloride reactions will never occur.', 'It makes every bronze object appear newly manufactured.'], 0, 'The passage assigns both protective and historical value to a stable layer.'],
    ['How is active bronze disease distinguished in the passage?', ['By a smooth dark-brown layer', 'By powdery light-green areas that can keep reacting', 'By scratches made during excavation', 'By the complete absence of moisture'], 1, 'The powdery pale-green corrosion is described as active and humidity-sensitive.'],
  ]),
  ...readingGroup('academic-sleep', '신경과학', 'C1', 'During non-rapid-eye-movement sleep, the brain produces brief bursts of activity called sleep spindles. Studies often find that people with more spindles after learning perform better on certain memory tests the next day. This correlation has encouraged the hypothesis that spindles help stabilize new memories. However, spindle number may also reflect a third factor, such as general brain health, that independently supports learning. Researchers therefore use carefully timed sounds or electrical stimulation to alter spindle activity. If memory changes only when stimulation modifies the relevant sleep pattern—and not merely because it wakes or disturbs participants—the causal claim becomes stronger.', [
    ['What hypothesis is motivated by the correlation described?', ['Sleep spindles contribute to stabilizing recently learned information.', 'All memory formation occurs only during rapid-eye-movement sleep.', 'People can learn new material from sounds while unconscious.', 'General brain health is determined by a single spindle count.'], 0, 'Better later performance following more spindles suggests a possible consolidation role.'],
    ['Why does the author introduce general brain health?', ['To offer an alternative explanation for the observed correlation', 'To show that stimulation permanently damages sleep', 'To argue that memory tests cannot be administered after sleep', 'To prove that spindle activity never varies'], 0, 'A third variable could cause both spindle differences and stronger learning.'],
    ['What comparison would best support a causal interpretation?', ['Memory after spindle-specific stimulation versus memory after equally disruptive control stimulation', 'Spindle counts from participants who learned entirely different subjects', 'Morning performance compared only with each person’s age', 'Brain health measured without recording sleep'], 0, 'A control with similar disturbance isolates the consequence of changing the spindle pattern itself.'],
  ]),
  ...readingGroup('academic-avulsion', '하천지형학', 'B2', 'A river usually follows a channel toward lower ground, but sediment gradually raises its bed relative to the surrounding floodplain. During a flood, water may break through a bank and establish a steeper, shorter route. This sudden shift is called an avulsion. Levees can delay avulsion by confining the river, yet confinement may allow the channel bed to rise further and make a later failure more disruptive. Ancient channel deposits help geologists identify where a river has moved before, but urban construction can obscure those traces.', [
    ['What condition makes an avulsion more likely?', ['A channel bed elevated by accumulated sediment', 'A floodplain located above every possible river route', 'Permanent removal of water from the channel', 'A decrease in the slope of all alternative paths'], 0, 'An elevated bed and a flood can allow water to escape onto a steeper route.'],
    ['What trade-off involving levees does the passage identify?', ['They reveal old channels but prevent construction.', 'They may postpone a shift while increasing the consequence of later failure.', 'They lower the riverbed while raising the floodplain.', 'They cause frequent small avulsions instead of rare ones.'], 1, 'Confinement offers near-term control but can leave an increasingly elevated channel.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you check whether the incubator alarm is active?', ['Choose the best response.', ['Yes, the green indicator is flashing.', 'The samples incubated for two days.', 'I checked the article out yesterday.', 'The alarm clock is beside my bed.'], 0, 'The reply reports the current alarm status.']),
  response(1, 'Why was my room request rejected?', ['Choose the best response.', ['The room has a large whiteboard.', 'You submitted it after the booking deadline.', 'I requested the equipment list.', 'Rejection is a strong word.'], 1, 'A late submission directly explains the rejection.']),
  response(2, 'Would it help if I brought an extension cable?', ['Choose the best response.', ['Yes, the nearest outlet is across the room.', 'The cable extends for five meters.', 'I helped with the event last year.', 'Bring the discussion to an end.'], 0, 'The outlet location makes the offered cable useful.']),
  response(3, 'Who approved the revised interview questions?', ['Choose the best response.', ['They were revised twice.', 'The ethics committee chair did.', 'The interview lasts an hour.', 'Questions usually need approval.'], 1, 'The response identifies the approving person.']),
  response(4, 'Haven’t the replacement filters arrived yet?', ['Choose the best response.', ['No, the supplier moved the delivery to Thursday.', 'The filters remove fine particles.', 'I replaced the lamp already.', 'They arrived through the north entrance.'], 0, 'The negative answer and new delivery date address “yet.”']),
  response(5, 'Where can I recharge the field recorder?', ['Choose the best response.', ['The recording begins at sunrise.', 'There is a powered locker in the equipment room.', 'It records in a compressed format.', 'I charged the travel expense.'], 1, 'The powered locker is a relevant charging location.']),
  response(6, 'How did the audience react to your demonstration?', ['Choose the best response.', ['Several people asked to try it afterward.', 'The reaction uses two chemicals.', 'I demonstrated it near the entrance.', 'The audience arrived by bus.'], 0, 'Follow-up interest describes the audience’s reaction.']),
  response(7, 'Should I cite the dataset as well as the article?', ['Choose the best response.', ['The data are arranged by year.', 'Yes, they have separate publication records.', 'I cited the final paragraph.', 'The article contains six figures.'], 1, 'Separate records justify citing both sources.']),
  response(8, 'When does the last shuttle leave the observatory?', ['Choose the best response.', ['From the lower parking area.', 'At ten fifteen on weekdays.', 'The observatory opened in 1998.', 'It leaves the equipment behind.'], 1, 'The question requires a departure time.']),
  response(9, 'Couldn’t we measure the samples before lunch?', ['Choose the best response.', ['We could, once the calibration finishes.', 'Lunch is served in the atrium.', 'The samples measure three centimeters.', 'I finished before the lecture.'], 0, 'The answer accepts the proposal subject to calibration.']),
  response(10, 'What made you change the title of your paper?', ['Choose the best response.', ['The original one implied a conclusion the data did not support.', 'I changed trains at Central Station.', 'The paper title appears in bold type.', 'Data collection ended in May.'], 0, 'The response explains the reason for revising the title.']),
  response(11, 'Do you happen to know if the workshop has a waiting list?', ['Choose the best response.', ['I listed the tools on the table.', 'It does; the form appears after registration closes.', 'The workshop builds wooden frames.', 'Waiting made the session longer.'], 1, 'The response confirms the waiting list and explains access.']),
  response(12, 'Why don’t we divide the presentation by case study?', ['Choose the best response.', ['That would give each of us a clear section.', 'The case study involved two villages.', 'I divided the samples by weight.', 'Presentations begin next week.'], 0, 'The reply evaluates the proposed division positively.']),
  response(13, 'Has Mira finished labeling the photographs?', ['Choose the best response.', ['Only the images from the second site remain.', 'The labels are printed on white paper.', 'Mira photographed the ceremony.', 'I finished reading the captions.'], 0, 'The remaining subset answers the progress question.']),
  response(14, 'Which entrance is open during the renovation?', ['Choose the best response.', ['Renovation will take three months.', 'Use the glass door beside the loading area.', 'The entrance fee is waived.', 'It opened with a metal key.'], 1, 'The reply gives a usable entrance location.']),
  response(15, 'Would you mind sending me the raw audio files?', ['Choose the best response.', ['Not at all; I will share the folder this afternoon.', 'The audio sounds clearer now.', 'Raw vegetables are in the refrigerator.', 'I minded the equipment desk.'], 0, '“Not at all” accepts the request and supplies a plan.']),
  response(16, 'How often should the sensor be recalibrated?', ['Choose the best response.', ['After every fifth measurement series.', 'The sensor is attached with two screws.', 'Calibration was surprisingly accurate.', 'It often measures humidity.'], 0, 'The answer provides a frequency.']),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-telescope', 'Listen to a Conversation', '천문관측 실습', 'C1', 'Student: The star positions in my images are all shifted by the same amount. Technician: Did you update the telescope clock before observing? Student: I synchronized the laptop, but not the camera controller. Technician: Then the pointing software used an old time. Correct the image headers first; you probably do not need to repeat the observation. Compare one known star after the correction, and if its position matches the catalog, process the rest.', [
    ['What pattern does the student observe in the images?', ['Every star has the same brightness.', 'All recorded positions share a systematic offset.', 'Only cataloged stars appear blurred.', 'The camera controller deleted the image times.'], 1, 'The student says that all positions are shifted similarly.'],
    ['What likely caused the problem?', ['Unsynchronized time in the camera controller', 'A damaged catalog of known stars', 'Excessive brightness from the laptop', 'A failure to focus the telescope mirror'], 0, 'The pointing calculation used an outdated controller clock.'],
    ['Why does the technician suggest checking one known star?', ['To test whether correcting the metadata resolves the systematic error', 'To replace the catalog with a single image', 'To determine whether the star has moved since observation', 'To synchronize the laptop without processing data'], 0, 'A cataloged reference can validate the correction before batch processing.'],
  ]),
  ...listeningGroup('conversation-makerspace', 'Listen to a Conversation', '제작실 이용', 'B2', 'Student: I completed the online laser-cutter course. Can I book the machine now? Coordinator: The online part covers design rules, but you still need a supervised cut. Bring a small test file to Tuesday’s induction. Once the supervisor signs your card, booking access activates overnight. Student: My project is due Tuesday evening. Coordinator: Then use the hand tools for this version; the induction cannot be shortened.', [
    ['What requirement has the student not completed?', ['Submitting the final project online', 'Performing a supervised test cut', 'Learning the basic design rules', 'Booking the machine overnight'], 1, 'Machine access requires an in-person supervised cut after the online course.'],
    ['What does the coordinator advise for the immediate deadline?', ['Delay the induction until the next semester', 'Complete this version with tools already available', 'Ask another student to sign the access card', 'Skip the test file and shorten the course'], 1, 'The deadline comes before authorization, so hand tools are the permitted alternative.'],
  ]),
  ...listeningGroup('conversation-internship', 'Listen to a Conversation', '인턴십 보고서', 'C1', 'Student: My internship report needs a concrete example, but the company marked the project data confidential. Advisor: You can analyze your decision process without giving the client name or exact numbers. Ask the company whether ranges and a fictional label are acceptable. Student: Would that make the report too vague? Advisor: Not if you explain the criteria you used, the alternatives you rejected, and what evidence changed your choice.', [
    ['What conflict does the student face?', ['The company requires publication before graduation.', 'A useful example contains restricted information.', 'The advisor rejected every internship topic.', 'The client asked for more exact numbers.'], 1, 'The report needs specificity while company data must remain confidential.'],
    ['What should the student ask the company to approve?', ['Publishing the client’s actual name', 'Using ranges and an invented identifier', 'Removing all discussion of the project', 'Changing the company’s decision criteria'], 1, 'The proposed anonymization preserves analysis without exposing exact details.'],
    ['According to the advisor, what would keep the report substantive?', ['A detailed account of criteria, alternatives, and changing evidence', 'A complete table of confidential measurements', 'A longer description of the company’s history', 'A fictional conclusion unrelated to the project'], 0, 'Reasoning can be concrete even when identifiers and exact values are withheld.'],
  ]),
  ...listeningGroup('conversation-choir', 'Listen to a Conversation', '합창단 일정', 'B2', 'Singer: The rehearsal calendar lists a sectional practice and a full rehearsal at the same time Thursday. Director: The sectional was moved to Wednesday, but the shared calendar did not update. I will correct it. Keep Thursday evening free, though; the accompanist can attend only then, and we need to rehearse the new tempo together.', [
    ['Why does the calendar show a conflict?', ['The accompanist scheduled two performances.', 'A moved rehearsal remained on the old date.', 'The singer joined two different choirs.', 'The director canceled Wednesday practice.'], 1, 'The sectional changed days but the shared calendar retained the earlier entry.'],
    ['Why is Thursday’s full rehearsal important?', ['The group must work with the accompanist at the available time.', 'The director plans to teach the sectional parts again.', 'The shared calendar can update only on Thursday.', 'The singer will select a different composition.'], 0, 'The accompanist’s availability and the new tempo require the full group.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-water', 'Listen to an Announcement', '연구동 시설', 'B2', 'Water service in the north science building will stop from seven until eleven tomorrow morning while a backflow valve is replaced. Laboratories may use water stored before the shutdown only for cleaning, not for experiments requiring verified purity. Safety showers will be supplied by a temporary line and must remain unobstructed. Any procedure that continuously requires tap water should be postponed until facilities announces that pressure has stabilized.', [
    ['Which activity may use water stored before the shutdown?', ['An experiment requiring certified purity', 'Routine cleaning of laboratory surfaces', 'Continuous cooling through an open tap', 'Testing the temporary safety-shower line'], 1, 'Stored water is allowed only for cleaning.'],
    ['What must wait even after water first returns?', ['Procedures needing continuous flow, until pressure is confirmed stable', 'Every activity involving dry laboratory equipment', 'Cleaning performed with previously stored water', 'Access to the north building entrance'], 0, 'Facilities must confirm stable pressure before continuous-use procedures resume.'],
  ]),
  ...listeningGroup('announcement-shuttle', 'Listen to an Announcement', '캠퍼스 교통', 'B1', 'The evening shuttle will bypass College Avenue tonight because of a street festival. Temporary stops are located at the post office and the east athletics gate. The last departure remains at eleven thirty, but trips may take ten minutes longer. Riders connecting to the regional train should use the earlier shuttle whenever possible.', [
    ['What remains unchanged tonight?', ['The route along College Avenue', 'The time of the final departure', 'The length of every trip', 'The stop beside the street festival'], 1, 'The final shuttle still leaves at eleven thirty.'],
    ['Why are train passengers advised to leave earlier?', ['The regional train has canceled its last service.', 'The detour may lengthen shuttle travel time.', 'The athletics gate closes before the post office.', 'Festival tickets are checked on the shuttle.'], 1, 'A longer trip could make a tight train connection unreliable.'],
  ]),
  ...listeningGroup('announcement-gallery', 'Listen to an Announcement', '미술 전시', 'B2', 'The student printmaking exhibition opens Friday in the west gallery. One installation uses ink that remains sensitive to bright light, so the gallery windows will be covered and photography will not be permitted in that room. Visitors may photograph the other works without flash. At six, the artists will discuss how different papers affected their prints; seating for the talk is limited, but the exhibition itself requires no reservation.', [
    ['Why is photography prohibited in one room?', ['The installation material can be harmed by strong light.', 'The artists have not finished printing the labels.', 'The covered windows make every camera unusable.', 'The room is reserved exclusively for the evening talk.'], 0, 'Light-sensitive ink motivates both window covering and the photography restriction.'],
    ['Which activity has limited capacity?', ['Entering the overall exhibition', 'Attending the artists’ paper discussion', 'Viewing works in the west gallery', 'Photographing works outside the restricted room'], 1, 'Only seating for the six o’clock talk is described as limited.'],
  ]),
  ...listeningGroup('announcement-registration', 'Listen to an Announcement', '수강 신청', 'C1', 'The add-and-drop system closes at midnight Friday. A course instructor’s email approval does not enroll a student; the change must also appear in the registration portal before the deadline. Students blocked by an unresolved prerequisite error should submit the help form with a screenshot before midnight. The registrar can review a timely documented error afterward, but requests first reported after the deadline will not be considered.', [
    ['What must happen in addition to receiving instructor approval?', ['The enrollment change must be recorded in the portal.', 'The instructor must remove every prerequisite.', 'The student must visit the registrar after midnight.', 'The course must appear in a screenshot before approval.'], 0, 'Email consent alone does not complete registration.'],
    ['How can a student preserve a claim involving a portal error?', ['Wait until the registrar discovers it independently.', 'Report it with documentation before the deadline.', 'Send the first request after the system closes.', 'Enroll in a different course without using the form.'], 1, 'A timely help form and screenshot allow later review.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-niche', 'Listen to an Academic Talk', '진화생태학', 'C1', 'Organisms do not merely adapt to environments; they can modify the conditions that influence later selection. Earthworms change soil structure, and beavers create ponds. This process is called niche construction. The modified environment may affect the builders, other species, and even descendants that never encountered the original conditions. The concept does not replace natural selection. Instead, it expands the account of where selective pressures come from by recognizing that organisms partly create those pressures.', [
    ['What distinguishes niche construction in the lecture?', ['Organisms alter conditions that later shape selection.', 'Species stop responding to environmental pressure.', 'Descendants inherit only genetic changes.', 'Natural selection is replaced by intentional design.'], 0, 'The key idea is feedback from organism-created environmental change.'],
    ['Why does the lecturer say the concept does not replace natural selection?', ['It explains a source of selective conditions rather than denying selection.', 'It applies only to animals that build visible structures.', 'It proves that acquired traits are always inherited.', 'It concerns environments with no evolutionary change.'], 0, 'Niche construction complements selection by explaining how some pressures arise.'],
  ]),
  ...listeningGroup('talk-bayes', 'Listen to an Academic Talk', '통계학', 'C1', 'A Bayesian analysis combines a prior distribution with new evidence. The prior represents plausible parameter values before the current data are considered. Critics sometimes describe this as injecting opinion, but every analysis contains assumptions. The advantage of a formal prior is that the assumption is visible and can be tested. With abundant precise data, reasonable priors often lead to similar results. With limited data, the prior matters more, so analysts should report how conclusions change under alternative defensible priors.', [
    ['What is a prior distribution meant to represent?', ['Plausible values before incorporating the current evidence', 'Only the values observed after an experiment ends', 'A guarantee that analysts share one opinion', 'Errors removed from a large dataset'], 0, 'The prior encodes pre-data plausibility.'],
    ['When does the choice of prior generally have greater influence?', ['When the new evidence is sparse or imprecise', 'When all defensible priors are identical', 'When assumptions are hidden from the analysis', 'When a parameter has already been measured exactly'], 0, 'Limited data leave more weight on the starting assumptions.'],
  ]),
  ...listeningGroup('talk-foxing', 'Listen to an Academic Talk', '종이보존학', 'B2', 'Old paper sometimes develops scattered reddish-brown spots known as foxing. The exact chemistry varies, but moisture, metal particles, and fungal activity can contribute. A conservator first stabilizes the storage environment because aggressive bleaching may weaken paper or alter inks. The visible spots may remain even after active deterioration has stopped. Treatment success therefore cannot be judged only by whether the sheet becomes uniformly white.', [
    ['Why might a conservator avoid immediately bleaching foxed paper?', ['Bleaching can damage the sheet or its writing.', 'Foxing always disappears without environmental control.', 'White paper cannot be stored in low humidity.', 'Metal particles protect every historic ink.'], 0, 'Cosmetic removal may create irreversible material harm.'],
    ['What criterion for success does the lecturer recommend?', ['Whether deterioration is stabilized, not simply whether stains vanish', 'Whether all old paper reaches the same shade of white', 'Whether fungal activity becomes visible to visitors', 'Whether moisture is added to soften the sheet'], 0, 'Remaining discoloration does not necessarily mean ongoing decay.'],
  ]),
  ...listeningGroup('talk-phonemes', 'Listen to an Academic Talk', '언어학', 'C1', 'Speech sounds vary continuously, yet listeners often perceive categories. In a classic experiment, researchers create a series of sounds that changes gradually from one consonant to another. Listeners may label several neighboring sounds as the same phoneme, then switch abruptly to the other label. This categorical pattern is shaped by language experience: a boundary important in one language may not separate words in another. Infants initially distinguish many contrasts, but sensitivity changes as they learn which differences carry meaning around them.', [
    ['What demonstrates categorical perception in the experiment?', ['Labels change abruptly despite gradual acoustic variation.', 'Every sound receives a unique linguistic label.', 'Listeners ignore consonants from their own language.', 'Infants hear fewer contrasts than all adults.'], 0, 'A sharp labeling boundary emerges along a continuous sound series.'],
    ['How does language experience affect perception?', ['It tunes sensitivity toward contrasts that distinguish meaning.', 'It prevents adults from recognizing any gradual change.', 'It makes phoneme boundaries identical across languages.', 'It removes categorical responses during infancy.'], 0, 'Experience emphasizes sound differences used functionally in the surrounding language.'],
  ]),
  ...listeningGroup('talk-heat-pumps', 'Listen to an Academic Talk', '에너지공학', 'B2', 'A ground-source heat pump exchanges heat with soil through buried pipes. Several meters below the surface, temperature changes less across seasons than air temperature does. In winter, the system draws heat from the ground; in summer, it transfers building heat back into the ground. Electricity still powers pumps and compressors, so the system is not energy-free. Installation can also be expensive where drilling is difficult, making long-term use and local geology important in evaluating cost.', [
    ['Why is the ground useful as a heat-exchange medium?', ['Its subsurface temperature is relatively stable across seasons.', 'It produces electricity without mechanical equipment.', 'Its temperature is always higher than indoor air.', 'It eliminates the need for buried pipes.'], 0, 'Reduced seasonal fluctuation supports heating and cooling exchange.'],
    ['What limitation does the lecturer identify?', ['The system cannot cool buildings in summer.', 'Installation cost depends partly on drilling conditions.', 'Compressors operate without any electricity.', 'Local geology has no effect on construction.'], 1, 'Difficult drilling can raise the initial cost.'],
  ]),
  ...listeningGroup('talk-ants', 'Listen to an Academic Talk', '집단행동', 'C1', 'An ant that finds food may deposit a pheromone trail on its return to the nest. Other ants are more likely to follow a stronger trail and reinforce it if they also reach food. Because a shorter route can be completed more often in the same period, it may accumulate pheromone faster and eventually attract most traffic. This does not mean an individual ant compares every route. The colony-level pattern emerges from repeated local choices, evaporation of old trails, and feedback.', [
    ['Why can a shorter route become dominant?', ['It can be traveled and reinforced more frequently.', 'Every ant measures all routes before moving.', 'Pheromone remains permanently on longer paths.', 'Food sources shift toward the strongest trail.'], 0, 'Faster round trips add reinforcement at a higher rate.'],
    ['What larger principle does the example illustrate?', ['Complex group organization can emerge from simple local behavior.', 'Individual ants possess a complete map of the environment.', 'Evaporation prevents colonies from changing routes.', 'Only one ant is responsible for collective decisions.'], 0, 'No central comparison is required for a coordinated colony pattern.'],
  ]),
]

const sentenceData: Array<[string, string, string[], string]> = [
  ['Why was the second trial more reliable?', 'It included', ['a control group', 'that had not', 'received the treatment', 'used in', 'the first trial'], 'f03-relative-past-perfect-participle'],
  ['Can the archive lend the map?', 'The curator explained', ['that it', 'could be viewed', 'only in', 'the reading room', 'because its paper', 'was unusually fragile'], 'f03-reported-passive-because'],
  ['What will happen if demand rises?', 'The service will add', ['another evening shuttle', 'provided that', 'enough drivers', 'are available', 'after six'], 'f03-provided-that-condition'],
  ['Why did you revise the graph?', 'I wanted to make', ['the difference', 'between groups', 'easier for readers', 'to recognize', 'without changing', 'the scale'], 'f03-object-complement-infinitive'],
  ['Did the committee accept the proposal?', 'Not until', ['the safety estimates', 'had been reviewed', 'independently', 'did the committee', 'approve the design'], 'f03-negative-fronting-inversion'],
  ['How should the specimens be stored?', 'They need to remain', ['where the temperature', 'can be monitored', 'throughout', 'the entire', 'transport period'], 'f03-where-passive-modal'],
  ['Why was attendance lower?', 'Had the notice', ['been sent earlier', 'more students', 'might have planned', 'to participate', 'in the event'], 'f03-inverted-third-conditional'],
  ['What did the interviews reveal?', 'They showed', ['not only why', 'residents objected', 'but also', 'what changes', 'would make it', 'more acceptable'], 'f03-not-only-but-also-embedded'],
  ['Will the field team leave today?', 'That depends on', ['whether the river', 'falls far enough', 'for the bridge', 'to reopen', 'safely today'], 'f03-whether-enough-infinitive'],
  ['Why preserve the original files?', 'Doing so allows', ['future researchers', 'to test conclusions', 'that could not', 'be examined', 'with current software'], 'f03-gerund-object-relative'],
]

const writing: BaseItem[] = sentenceData.map(([prompt, starter, fragments, grammarFocus], index) => {
  const item = base(`sentence-${index}`, 'writing', 'sentence-build', 'Build a Sentence', '문장 구성', index < 4 ? 'B1' : index < 8 ? 'B2' : 'C1', 75)
  const tiles = prepareSentenceTiles(fragments, item.id)
  return { ...item, instruction: '모든 단어와 구를 사용해 문맥에 맞는 문장을 완성하세요.', prompt, starter, words: tiles.choices, answer: tiles.answer, grammarFocus, explanation: `${starter} ${tiles.correct.join(' ')}` }
})
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '학술 포스터', 'B2', 420), instruction: '상황과 독자를 고려해 목적이 분명한 이메일을 작성하세요.', prompt: 'The print shop produced your conference poster with one graph cropped and a color scale that is difficult to read. Write to the print manager. Identify the order, explain how the errors affect the presentation, and request a corrected copy before tomorrow afternoon.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '시민과학', 'C1', 600), instruction: '두 학생의 의견에 기여하면서 자신의 입장과 근거를 제시하세요.', prompt: 'Professor Alvarez: How should researchers balance the large scale of citizen-science data with concerns about inconsistent observations?', passage: 'Nina: Training and automatic checks can make volunteer observations useful at a scale professionals cannot match.\nEli: Uneven equipment and experience may create patterns that look scientific but are actually measurement bias.' })

const repeatSentences = [
  'Welcome to the special collections reading room.',
  'Place bags and drinks in the lockers outside.',
  'Use only the pencils provided at your desk.',
  'Keep each document flat on its supporting cushion.',
  'Turn fragile pages from the edge without pressing the binding.',
  'If an item appears damaged, stop and notify a staff member.',
  'Before leaving, return every folder in its original order and wait while staff verify the contents.',
]
const interviewQuestions = [
  'Describe a situation in which public data helped you make a decision.',
  'What makes a government or university dataset trustworthy?',
  'When might protecting privacy be more important than releasing detailed data?',
  'How could public institutions help nonexperts interpret complex data responsibly?',
]
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '희귀자료 열람 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 그대로 반복하세요.', audioText, stimulusGroupId: 'f03-repeat', scenarioId: 'f03-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '공공 데이터', sequenceIndex < 2 ? 'B2' : 'C1', 45), instruction: '같은 주제로 이어지는 질문에 이유와 사례를 들어 답하세요.', audioText, stimulusGroupId: 'f03-interview', scenarioId: 'f03-interview', sequenceIndex })),
]

export const AUTHORED_FORM_03_ITEMS: BaseItem[] = [
  ...reading.slice(0, 11).map((item) => ({ ...item, module: 1 })),
  ...reading.slice(11).map((item) => ({ ...item, module: 2 })),
  ...responses.slice(0, 9).map((item) => ({ ...item, module: 1 })),
  ...conversations.slice(0, 5).map((item) => ({ ...item, module: 1 })),
  ...announcements.slice(0, 4).map((item) => ({ ...item, module: 1 })),
  ...talks.slice(0, 6).map((item) => ({ ...item, module: 1 })),
  ...responses.slice(9).map((item) => ({ ...item, module: 2 })),
  ...conversations.slice(5).map((item) => ({ ...item, module: 2 })),
  ...announcements.slice(4).map((item) => ({ ...item, module: 2 })),
  ...talks.slice(6).map((item) => ({ ...item, module: 2 })),
  ...writing,
  ...speaking,
]

export const AUTHORED_FORM_03_IDS = AUTHORED_FORM_03_ITEMS.map((item) => item.id)
