import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f13')

const reading: BaseItem[] = [
  cloze('cloze-osmoregulation', '동물생리학', 'C1', 'Aquatic animals must regulate water and dissolved ions because their body fluids often differ from the surrounding environment. A freshwater fish tends to ga___ water across its gills and lo___ salts by diffusion. It rarely drinks and prod___ abundant dilute urine. Specialized cells act___ transport ions inward against concentration gradients. Marine bony fish face the opposite problem: seawater dr___ water from their tissues. They drink, abs___ water in the intestine, and exc___ excess salts through the gills. These processes req___ metabolic energy. If salinity changes too rapidly, regulatory mechanisms may be overw___, disrupting nerve and muscle function. Species that tol___ broad salinity ranges adjust transporter abundance over time.', 'in|se|uces|ively|aws|orb|rete|uire|helmed|erate'),
  cloze('cloze-tephra', '화산연대학', 'C1', 'A volcanic eruption may scatter a thin layer of ash across a vast region. Once chemically ident___, that tephra layer can link sediments from separate lakes, bogs, or archaeological sites. Researchers comp___ glass shards by major and trace elements rather than relying only on color. A layer deposited quickly provides an approx___ synchronous marker, although ash may later be rew___ by wind or water. Microscopic grains can rev___ eruptions invisible to the naked eye. The method dep___ on reliable source samples and careful stratigraphy. Similar volcanoes may prod___ overlapping compositions, so analysts use multiple elements and uncertainty estimates. Tephrochronology does not rep___ every dating method; it constr___ sequences by tying them to independently dated eruptions and helps det___ missing or disturbed sediment.', 'ified|are|imately|orked|eal|ends|uce|lace|ains|ect'),
  cloze('cloze-fresco', '벽화보존학', 'B2', 'A true fresco is painted onto wet lime plaster. As the plaster dr___, chemical reactions bind pigments into the surface. Artists must work in sec___ that can be completed before the plaster sets. Later additions may be appl___ to dry walls with another binder, making them more vulner___ to moisture and flaking. Conservators first diag___ salts, cracks, and previous repairs. Injecting grout can sta___ detached plaster, but excessive pressure may cau___ new damage. Cleaning tests begin in small areas because pigments res___ differently. A bright result is not necessarily auth___; aggressive cleaning may remove intentional glazes. Treatment records allow future specialists to dist___ original material from modern intervention.', 'ies|tions|ied|able|nose|bilize|se|pond|entic|inguish'),
  daily('daily-cryo-box', '생물표본 관리', 'C1', 'Cryogenic boxes are mapped by rack, shelf, and grid position. Removing a vial without recording its replacement position breaks the chain of location even if the sample label remains legible. Temporary moves must be entered in the freezer log before the door is closed.', ['Why must a temporary vial move be logged immediately?', ['Its physical coordinates otherwise cease to match the inventory record', 'A readable specimen label automatically changes after freezing', 'The freezer door cannot close while a box is outside', 'Shelf numbers are assigned only after a sample is analyzed'], 0, 'The location system depends on every move being recorded.']),
  daily('daily-language-table', '언어 교환', 'B2', 'Conversation tables display a colored card for the language currently being practiced. Participants may request clarification in another language, but extended side conversations should move to the lounge so beginners at the table retain an immersive environment.', ['When should participants relocate to the lounge?', ['When a long exchange shifts away from the table language', 'Whenever a beginner requests one brief clarification', 'Before selecting the colored language card', 'Only after the scheduled practice session has ended'], 0, 'The relocation rule concerns prolonged use of another language.']),
  daily('daily-darkroom', '사진 실습실', 'B2', 'The darkroom reservation includes ten minutes for chemical cleanup. Users booking consecutive sessions may leave shared trays in place only after confirming that the next user needs the same process. Mixed or unidentified solutions must never be returned to stock bottles.', ['Under what condition may shared trays remain prepared?', ['The following user explicitly confirms an identical chemical process', 'Two reservations appear anywhere on the same calendar day', 'The solutions have already been poured back into storage', 'Every tray has lost its identifying process label'], 0, 'Continuation requires direct confirmation of compatible use.']),
  daily('daily-peer-review', '학술지 운영', 'C1', 'Reviewers who recognize a manuscript may continue only if prior contact with the authors does not create a conflict. Merely working in the same broad field is not disqualifying. A recent collaboration, financial rivalry, or access to unpublished results should be disclosed to the editor, who decides whether reassignment is necessary.', ['Which circumstance requires disclosure rather than an automatic personal decision?', ['A recent collaboration that could compromise impartial assessment', 'General familiarity with the manuscript’s research discipline', 'Recognition of a method commonly used across the field', 'Agreement with a published theory cited by the authors'], 0, 'The editor evaluates declared conflicts.']),
  daily('daily-kiln-cooling', '도예 공방', 'B2', 'The kiln controller may display room temperature while thick ceramic pieces remain hot internally. Do not unload solely because the display is low. The firing supervisor must confirm that the programmed cooling interval has elapsed, and heat-resistant gloves remain mandatory during inspection.', ['Why is the temperature display insufficient for unloading?', ['Dense objects can retain internal heat after the chamber air cools', 'The controller reports only temperatures outside the building', 'Protective gloves interfere with the programmed cooling cycle', 'The supervisor cannot view readings during a firing'], 0, 'Air temperature can fall before the ware cools throughout.']),
  daily('daily-orcid', '연구자 식별', 'B2', 'Authors should connect their persistent researcher identifier before final submission. Name spelling can change across publications, whereas the identifier links records consistently. Adding it after acceptance is possible but may delay automatic indexing by external databases.', ['What is the main advantage of connecting the identifier early?', ['It preserves authorship links despite variations in published names', 'It prevents editors from requesting any manuscript revision', 'It guarantees immediate acceptance by external databases', 'It converts a temporary submission number into copyright'], 0, 'A stable identifier resolves changing name forms.']),
  daily('daily-audio-consent', '구술사 연구', 'C1', 'An interviewee may permit quotation while restricting public release of the audio. The transcript and recording therefore have separate access fields. Researchers must honor the more specific restriction rather than assuming permission for one format covers every derivative file.', ['What should a researcher infer from permission to quote?', ['It does not by itself authorize publication of the sound recording', 'It eliminates the need to record format-specific restrictions', 'It requires immediate release of every derivative interview file', 'It prohibits scholarly use of an approved transcript excerpt'], 0, 'Consent is granular across representations of the interview.']),
  daily('daily-rooftop', '도시 생태 조사', 'B2', 'Rooftop survey access begins at sunrise, but sampling cannot start until the safety officer records wind speed. If gusts exceed the threshold, observers may conduct indoor identification work while waiting; the missed outdoor interval must not be reconstructed from memory.', ['What may the team do while wind conditions are unsafe?', ['Identify previously collected material inside the building', 'Estimate unobserved rooftop counts from recollection', 'Begin sampling before the wind measurement is entered', 'Lower the official gust threshold for the morning'], 0, 'Indoor identification is the authorized alternative.']),
  daily('daily-license-seat', '소프트웨어 이용', 'B2', 'A floating software license is released fifteen minutes after an inactive session disconnects. Closing a laptop lid does not necessarily end the remote process. Users who no longer need the program should sign out within the application so another researcher can obtain the seat promptly.', ['Why might closing the laptop fail to free a license?', ['The remote application process can continue after the local screen sleeps', 'Inactive licenses are permanently assigned to the first researcher', 'The program counts every laptop lid as an additional user', 'A license becomes available only after the annual renewal'], 0, 'The server process, not the physical lid, holds the seat.']),
  daily('daily-field-notebook', '현장 기록', 'C1', 'Field notebooks use consecutive pages, including for corrections. An erroneous entry should be crossed with one line, dated, and explained nearby. Removing a page or obscuring the original wording prevents auditors from reconstructing how an interpretation changed.', ['Which correction preserves an adequate audit trail?', ['Retaining the readable original beside a dated explanation', 'Erasing the observation before entering a cleaner version', 'Detaching the page and replacing it with an unsigned copy', 'Covering the initial wording with an opaque correction label'], 0, 'Transparent correction preserves both states of the record.']),
  ...readingGroup('academic-bayesian', '베이지안 추론', 'C1', 'Bayesian inference combines a prior distribution with a likelihood derived from observed data to produce a posterior distribution. A prior need not express arbitrary personal belief; it can encode previous measurements, physical constraints, or deliberately weak information. With abundant, highly informative data, many reasonable priors yield similar posteriors. With sparse data, prior assumptions matter more and should be examined through sensitivity analysis. A narrow posterior is not proof that the model is correct: omitted mechanisms or a misspecified likelihood can produce confident but misleading estimates. Posterior predictive checks compare simulated observations from the fitted model with relevant features of the actual data.', [
    ['Why can two analysts obtain different posteriors from a small dataset?', ['Their defensible prior assumptions may exert substantial influence when evidence is limited', 'Bayesian likelihoods cannot incorporate any observed measurement', 'Every prior becomes identical as soon as one datum is recorded', 'Posterior distributions exclude uncertainty about parameter values'], 0, 'Sparse evidence leaves more inferential weight on prior structure.'],
    ['What limitation of a narrow posterior does the passage emphasize?', ['Precision within a flawed model need not imply an accurate account of reality', 'A concentrated distribution always signals insufficient computation', 'Narrow intervals prevent researchers from simulating new observations', 'Model assumptions become irrelevant whenever uncertainty decreases'], 0, 'Conditional certainty can coexist with misspecification.'],
    ['What is the role of a posterior predictive check?', ['To test whether model-generated data reproduce important observed patterns', 'To replace the likelihood with an undocumented subjective judgment', 'To guarantee that no scientifically relevant process was omitted', 'To make competing prior distributions numerically indistinguishable'], 0, 'Predictive discrepancies reveal ways the fitted model may be inadequate.'],
  ]),
  ...readingGroup('academic-islands', '섬 생물지리학', 'B2', 'Island biogeography predicts that species richness reflects a balance between colonization and extinction. Colonization tends to decline as an island accumulates species because fewer mainland species remain absent. Extinction tends to rise because more resident populations compete and some remain small. Distance reduces arrival rates, while larger area generally lowers extinction by supporting bigger populations and more habitats. The equilibrium is dynamic: the number of species may remain similar even as identities change. Habitat fragments resemble islands in some respects, but the surrounding matrix can be partly permeable, so literal transfer of the model requires caution.', [
    ['How can species richness remain stable while the community changes?', ['New colonizations may offset extinctions of different resident species', 'Every original population persists once equilibrium is reached', 'Distance stops affecting arrivals after the first colonist', 'The mainland eventually contains no potential source species'], 0, 'Equilibrium concerns rates and totals, not fixed membership.'],
    ['Why should habitat fragments not be treated as perfect islands?', ['Organisms may cross or use the intervening landscape to differing degrees', 'Fragments necessarily contain more habitat than continents', 'Extinction cannot occur in a terrestrial patch', 'Oceanic distance is unrelated to colonization probability'], 0, 'The matrix varies in permeability rather than forming an absolute barrier.'],
  ]),
  ...readingGroup('academic-scribes', '문헌사', 'C1', 'Before printing, scribes copied texts by hand, and variation was inevitable. Some differences were accidental, such as skipped lines caused by similar endings. Others were deliberate: a copyist might modernize spelling, clarify an obscure phrase, or harmonize a passage with a familiar version. Textual critics compare families of manuscripts rather than simply selecting the oldest surviving copy, which may descend from an already altered exemplar. A reading shared by several manuscripts is not automatically original if those witnesses depend on one common source. Scholars evaluate genealogical relationships, likely copying errors, historical language, and whether one reading plausibly gave rise to the others.', [
    ['Why is the oldest surviving manuscript not necessarily the best witness?', ['It may reproduce changes introduced in an earlier lost ancestor', 'Its physical material prevents comparison with later documents', 'Copyists never preserved wording from an exemplar faithfully', 'Historical spelling makes every early reading unintelligible'], 0, 'Survival date and textual ancestry are different properties.'],
    ['Why can agreement among several manuscripts be misleading?', ['The agreeing copies may inherit one innovation from a shared source', 'Independent witnesses are required to contain different wording', 'Deliberate clarification always restores the author’s exact expression', 'A majority reading cannot be analyzed genealogically'], 0, 'Numerical support overcounts evidence when witnesses are dependent.'],
    ['What criterion helps choose between competing readings?', ['Whether one variant can explain how the alternatives arose during copying', 'Whether the longest wording appears in the newest physical manuscript', 'Whether modern readers prefer a standardized grammatical construction', 'Whether all scribes used an identical regional spelling system'], 0, 'Explanatory direction is part of textual-critical reasoning.'],
  ]),
  ...readingGroup('academic-phase-change', '재료공학', 'C1', 'Phase-change materials store thermal energy by melting and release it when they solidify. Because the transition absorbs or emits latent heat at a nearly constant temperature, a material embedded in a wall can moderate indoor temperature swings. Selecting a substance with an appropriate melting point is crucial: one that rarely reaches its transition contributes little useful storage. Engineers must also manage leakage, flammability, cycling degradation, and slow heat transfer. Encapsulating the material can prevent escape but adds cost and may reduce the volume available for storage. Reported laboratory capacity therefore does not directly establish whole-building energy savings under variable weather and occupancy.', [
    ['Why must the melting point match the intended environment?', ['Thermal storage is useful only if ordinary conditions repeatedly cross the phase transition', 'A lower transition temperature invariably increases total building insulation', 'Solid materials cannot release previously absorbed latent heat', 'Indoor temperature remains constant regardless of climate or occupancy'], 0, 'The phase change must actually be activated during operation.'],
    ['Why might laboratory capacity overstate practical savings?', ['System losses, heat-transfer limits, and real operating patterns affect delivered performance', 'Encapsulation always doubles the mass of active storage material', 'Weather variation causes latent heat to disappear chemically', 'Building walls cannot contain any substance that changes phase'], 0, 'Material capacity is only one component of system-level effectiveness.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Has the microscopy room passed its vibration check?', ['Not yet; facilities will repeat the measurement after lunch.', 'The microscope magnifies the specimen four hundred times.', 'Room reservations open at the start of each month.', 'I checked the bibliography for missing page numbers.'], 0, 'The reply reports the pending verification.'),
  response(1, 'Why is my reimbursement listed as incomplete?', ['The conference fee increased after early registration.', 'Your receipt does not show the currency conversion.', 'I completed the survey during the return flight.', 'Reimbursement policies appear in the staff handbook.'], 1, 'A missing conversion record explains the status.'),
  response(2, 'Could we postpone calibration until the morning?', ['The morning sample has already been labeled.', 'Calibration curves are stored beside the instrument.', 'Only if no one uses the detector overnight.', 'I postponed the seminar because the speaker was ill.'], 2, 'The condition protects calibration validity.'),
  response(3, 'I assumed the anthology included the complete translation.', ['The translator also wrote a critical introduction.', 'Complete editions are shelved on the lower floor.', 'The anthology was assigned in last year’s seminar.', 'It contains selected passages; the unabridged text is online.'], 3, 'The response corrects the mistaken scope.'),
  response(4, 'Can visitors enter the restoration studio?', ['Yes, during the guided period behind the marked barrier.', 'The studio restored three panels this semester.', 'Visitor badges use a different color on weekends.', 'I entered the measurements in the condition report.'], 0, 'The reply gives bounded permission.'),
  response(5, 'Where should the anonymous consent forms be stored?', ['The consent language was revised by the ethics board.', 'In the locked cabinet separate from coded research data.', 'Anonymous surveys usually omit direct identifiers.', 'I stored the spare batteries near the recorder.'], 1, 'Separation and secure storage protect records.'),
  response(6, 'Wouldn’t a logarithmic axis make that trend clearer?', ['The axis label should include the measured unit.', 'A trend can be described in the results section.', 'Perhaps, but we must show that equal spacing represents multiplicative change.', 'I logged into the visualization server this morning.'], 2, 'The reply accepts conditionally and notes interpretive clarity.'),
  response(7, 'The courier delivered the loan crate upside down.', ['The courier route passes the north entrance.', 'Loan agreements specify a six-week display period.', 'I turned the page to view the diagram.', 'Photograph every side before opening it with the registrar present.'], 3, 'The response preserves evidence before inspection.'),
  response(8, 'Is there enough sediment left for a replicate analysis?', ['There should be, provided we use the smaller extraction protocol.', 'The sediment accumulated below the inlet pipe.', 'Replicate estimates improve uncertainty assessment.', 'I left the sample list on the shared drive.'], 0, 'The answer links feasibility to a lower-volume method.'),
  response(9, 'Why were those participants removed from the model?', ['The participants attended two different workshop sessions.', 'Their outcome dates preceded the recorded intervention.', 'I removed an outdated table from the appendix.', 'The model contains three random-effect terms.'], 1, 'Impossible temporal ordering motivates exclusion.'),
  response(10, 'Can I cite the preliminary catalog number?', ['The catalog describes objects acquired before 1950.', 'Citation styles differ across archaeology journals.', 'Use the persistent accession number instead.', 'I numbered the preliminary figures consecutively.'], 2, 'The stable identifier is appropriate for citation.'),
  response(11, 'I cannot reproduce the color profile on this monitor.', ['The profile was designed for printed photographs.', 'Color perception changes under different lighting.', 'The monitor arrived with a protective cover.', 'Check whether the operating system replaced the calibrated profile.'], 3, 'A system-level profile change could explain the mismatch.'),
  response(12, 'Did the committee approve the revised sampling boundary?', ['Conditionally; they requested a buffer around the nesting site.', 'The committee meets in the ecology conference room.', 'Sampling boundaries are drawn with dashed lines.', 'I approved the final invoice yesterday.'], 0, 'The approval includes an ecological condition.'),
  response(13, 'When will the replacement humidity sensor be installed?', ['The old sensor reported values every five minutes.', 'Building services scheduled it for Wednesday morning.', 'Humidity can affect the paper collection.', 'I installed the statistical package on my laptop.'], 1, 'The response supplies the scheduled time.'),
  response(14, 'Should we preregister the secondary analysis too?', ['The analysis uses a publicly archived dataset.', 'Secondary outcomes appear below the primary endpoint.', 'Yes, if we intend to distinguish it from later exploration.', 'I registered for the methods workshop last week.'], 2, 'Preregistration clarifies confirmatory status.'),
  response(15, 'Who can authorize a key after the department closes?', ['The key opens both rooms in the laboratory suite.', 'Authorization forms require a supervisor signature.', 'After-hours access expires at the end of the term.', 'The on-call safety coordinator can approve emergency entry.'], 3, 'The responsible after-hours authority is identified.'),
  response(16, 'This map projection makes the polar regions look enormous.', ['Use an equal-area projection if relative surface size is the comparison.', 'Polar fieldwork requires insulated navigation equipment.', 'The map legend lists elevation in twenty-meter intervals.', 'I projected next year’s enrollment from current applications.'], 0, 'Projection choice should match the analytical purpose.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-baseline', 'Listen to a Conversation', '분광 분석', 'C1', 'Student: The absorption peak is in the expected place, but the baseline slopes upward. Technician: Did you run the blank after the lamp reached operating temperature? Student: I ran it immediately after switching the instrument on. Technician: Then the lamp drift may be embedded in your reference. Let it stabilize, rerun the blank, and compare both raw spectra before applying any mathematical correction.', [
    ['What most likely caused the sloping baseline?', ['The reference was collected while the light source was still stabilizing', 'The sample absorbed no wavelength measured by the instrument', 'A mathematical correction had already erased the raw spectrum', 'The expected peak shifted because the blank contained the analyte'], 0, 'An unstable reference carries lamp drift into the ratio.'],
    ['Why does the technician request both raw spectra?', ['To distinguish an acquisition problem from an artifact introduced during correction', 'To average the expected peak with an unrelated wavelength', 'To avoid waiting for the lamp to reach operating temperature', 'To replace the blank with the student’s analyzed sample'], 0, 'Raw comparison preserves diagnostic evidence.'],
  ]),
  ...listeningGroup('conversation-score', 'Listen to a Conversation', '공연 자료', 'B2', 'Student: May I scan the orchestra score for everyone in the ensemble? Librarian: The library owns one licensed performing set, but ownership does not permit unlimited duplication. Student: Rehearsal starts before the publisher can ship extras. Librarian: I can request a short-term digital rental. Until permission arrives, place the licensed parts on reserve and organize staggered practice.', [
    ['Why can the student not simply scan the score?', ['Possessing a licensed set does not include unrestricted copying rights', 'The scanner cannot capture pages containing musical notation', 'The ensemble has already returned every performing part', 'Digital rentals are available only after the concert'], 0, 'Physical access and reproduction permission are distinct.'],
    ['What interim arrangement does the librarian propose?', ['Share the authorized parts through scheduled reserve use', 'Rewrite the entire composition from performers’ memory', 'Cancel rehearsal until permanent copies are purchased', 'Publish the scanned score on an open website'], 0, 'Staggered access uses the existing licensed materials.'],
  ]),
  ...listeningGroup('conversation-occupation', 'Listen to a Conversation', '사회조사 코딩', 'C1', 'Researcher: Respondents wrote job titles in their own words, and I coded “lab manager” as scientist. Supervisor: That may be wrong. One manager may conduct research; another may handle budgets and compliance. Use the task descriptions, not prestige implied by the title. Researcher: Some descriptions are missing. Supervisor: Mark those cases unresolved and test how alternative plausible codes affect the results.', [
    ['What problem does the supervisor identify?', ['A job title alone may conceal substantially different occupational tasks', 'Respondents were required to select only scientific occupations', 'Budget work always belongs in the same category as laboratory research', 'Free-text answers cannot be coded under any circumstances'], 0, 'Functional duties, not labels, determine the classification.'],
    ['How should cases without task descriptions be handled?', ['Represent their ambiguity and examine sensitivity to plausible classifications', 'Assign every manager to the category with the highest social status', 'Delete the entire survey before calculating any results', 'Infer the missing descriptions from respondents’ salaries alone'], 0, 'Explicit uncertainty is preferable to unsupported certainty.'],
  ]),
  ...listeningGroup('conversation-rights', 'Listen to a Conversation', '기록물 사용 허가', 'C1', 'Historian: The archive allowed me to photograph the letters, so I assumed I could reproduce one in my book. Archivist: Photography permission supports private research. Publication rights may belong to the writer’s estate, while the archive owns the physical paper. Historian: The letter is central to my argument. Archivist: Cite the collection now, but contact the rights holder before sending final illustrations to the press.', [
    ['Which distinction did the historian overlook?', ['Permission to make a research copy differs from permission to publish it', 'The archive cannot own any physical historical document', 'A scholarly citation transfers copyright to the book publisher', 'Photographs are prohibited whenever an estate owns literary rights'], 0, 'Access, object ownership, and reproduction rights are separate.'],
    ['What should the historian do before final production?', ['Obtain authorization from whoever controls reproduction rights', 'Remove the collection citation from the manuscript', 'Donate the original letter to the writer’s estate', 'Ask the printer to determine legal ownership independently'], 0, 'The relevant rights holder must approve publication.'],
  ]),
  ...listeningGroup('conversation-core', 'Listen to a Conversation', '토양 코어', 'B2', 'Assistant: The upper section of this soil core fell apart during transport. Ecologist: Do not compress it back into the tube. We would lose the original depth relationships. Assistant: Should I discard the core? Ecologist: No. Photograph the disturbance, preserve the intact lower section, and flag the surface interval as unsuitable for layer-by-layer analysis.', [
    ['Why should the assistant avoid repacking the loose soil?', ['Artificial compression would create a false vertical sequence', 'The transport tube cannot hold any material from the surface', 'Photography requires discarding every disturbed specimen', 'The lower core is useful only when mixed with the upper layer'], 0, 'Reconstruction would fabricate stratigraphic position.'],
    ['What does the ecologist decide about the core?', ['Retain valid portions while documenting limits on the damaged interval', 'Treat every depth as undisturbed after taking one photograph', 'Discard the intact lower layers to keep sampling balanced', 'Use the mixed surface material for precise chronological inference'], 0, 'Partial damage does not invalidate every component.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-laser', 'Listen to an Announcement', '레이저 실험실', 'C1', 'The laser laboratory reopens Monday under a revised access system. Previous training remains valid, but every user must complete the new interlock demonstration before independent entry. Demonstrations run hourly without reservation. Until completion is recorded, trained users may enter only with an authorized operator.', [
    ['What must returning users complete?', ['A practical demonstration of the revised safety interlock', 'The entire introductory optics course for a second time', 'An advance reservation for every hourly demonstration', 'A written request to remove the authorized operator'], 0, 'Prior training is retained, but the new control needs verification.'],
    ['What is allowed before the new requirement is recorded?', ['Entry under the supervision of an authorized operator', 'Independent overnight work using the previous access card', 'Disabling the interlock during a scheduled demonstration', 'Training other users without entering the laboratory'], 0, 'Supervised access bridges the transition.'],
  ]),
  ...listeningGroup('announcement-shuttle', 'Listen to an Announcement', '캠퍼스 교통', 'B2', 'For the next two weeks, the east shuttle stop will move one block south because of utility excavation. Buses follow the usual timetable, but riders should allow five extra minutes to reach the temporary location. The accessible boarding platform remains at the original stop until Friday and then moves with the route on Saturday.', [
    ['What remains unchanged during the relocation?', ['The published departure schedule for the shuttle', 'The walking distance from every campus building', 'The boarding position throughout both weeks', 'The completion date of the utility excavation'], 0, 'Only the stop location changes, not scheduled times.'],
    ['Why is Friday operationally different?', ['Accessible boarding still occurs at the original location that day', 'All shuttle service ends before the platform is moved', 'The temporary stop returns to its normal northern position', 'Riders no longer need additional walking time after Friday'], 0, 'The platform transition lags behind the general stop relocation.'],
  ]),
  ...listeningGroup('announcement-freezer', 'Listen to an Announcement', '표본 저장', 'C1', 'Freezer three will undergo preventive maintenance Tuesday. Move temperature-sensitive specimens to the labeled backup racks by Monday at four. Staff will transfer boxes still inside after that deadline, but they cannot verify undocumented internal arrangements. Photograph each open box before relocation and update the position manifest after, not before, the move.', [
    ['Why should researchers photograph open boxes?', ['To preserve evidence of internal arrangement before handling', 'To substitute images for every specimen identification label', 'To authorize staff to discard undocumented samples', 'To calculate the maintenance temperature from box color'], 0, 'Images document organization that staff cannot independently verify.'],
    ['When should the location manifest be updated?', ['After the specimens occupy their actual backup positions', 'Before any rack destination has been selected', 'Only when maintenance of the original freezer is canceled', 'While undocumented boxes remain inside freezer three'], 0, 'Records should describe completed physical placement.'],
  ]),
  ...listeningGroup('announcement-workshop', 'Listen to an Announcement', '시민과학 행사', 'B2', 'Saturday’s stream-monitoring workshop has reached its indoor capacity. Registered participants retain seats until ten minutes before the start; after that, unclaimed places go to the waiting list. The outdoor demonstration remains open to walk-in visitors at noon, but borrowing a test kit requires completion of the indoor safety briefing.', [
    ['When may waiting-list participants receive indoor seats?', ['Ten minutes before the session if registered places are unclaimed', 'Immediately after the outdoor demonstration concludes', 'Only when they bring a privately owned test kit', 'Before registered participants are allowed to check in'], 0, 'Seat guarantees expire at the stated cutoff.'],
    ['What requires attending the indoor briefing?', ['Borrowing equipment for the water-testing demonstration', 'Watching the noon activity without handling a kit', 'Joining the waiting list for a vacant classroom seat', 'Walking to the stream with an already trained staff member'], 0, 'Equipment lending is conditional on safety instruction.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-mangrove', 'Listen to an Academic Talk', '생태지구화학', 'C1', 'Mangrove forests store carbon in wood, but much of their long-term stock lies in waterlogged soil. Slow decomposition allows organic matter to accumulate below ground. Measuring only trunks can therefore underestimate carbon loss when a forest is cleared or eroded. Restoration does not immediately recreate the old stock: young trees may grow rapidly while deep sediment carbon develops over decades or centuries. Researchers compare intact, degraded, and restored sites, accounting for sediment deposition and carbon transported in or out by tides.', [
    ['Why can a tree-only inventory misrepresent mangrove carbon?', ['A large persistent pool may be stored beneath the visible vegetation', 'Mangrove trunks contain no carbon after reaching maturity', 'Tidal water prevents researchers from measuring plant biomass', 'All belowground organic matter arrives from distant forests'], 0, 'Soil is a major and easily omitted reservoir.'],
    ['Why is rapid growth insufficient evidence of full restoration?', ['Vegetation recovery can precede rebuilding of deep sediment stores', 'Young trees invariably release more carbon than degraded soil', 'Restored sites immediately lose every tidal sediment input', 'Long-term carbon depends only on the number of tree species'], 0, 'Different ecosystem pools recover on different timescales.'],
  ]),
  ...listeningGroup('talk-pricing', 'Listen to an Academic Talk', '산업조직론', 'C1', 'Price discrimination occurs when a seller charges different effective prices not fully explained by cost differences. It requires some market power and a way to sort customers or induce them to self-select. Student discounts use observable categories; airline fare restrictions encourage travelers with flexible schedules to choose cheaper tickets. The practice can raise profit and sometimes expand output to price-sensitive buyers, yet it may also transfer surplus from consumers. Whether welfare rises depends on who gains access, how total production changes, and the resources spent enforcing separation.', [
    ['Why do restrictive ticket conditions help an airline separate buyers?', ['Customers reveal willingness to pay through the inconvenience they accept', 'Every passenger imposes a different physical cost on the aircraft', 'Flexible travelers are legally prohibited from buying expensive seats', 'Market power disappears once more than one fare is offered'], 0, 'Self-selection links preferences to contract choice.'],
    ['Why is the welfare effect ambiguous?', ['Expanded access can coexist with redistribution and costly market separation', 'Different prices necessarily reduce the number of units sold', 'Producer profit is excluded from every welfare calculation', 'Observable customer categories eliminate all enforcement expense'], 0, 'Several effects may move welfare in opposing directions.'],
  ]),
  ...listeningGroup('talk-reconsolidation', 'Listen to an Academic Talk', '기억과학', 'C1', 'A retrieved memory is not always a fixed recording. Under some conditions, retrieval makes the memory temporarily labile before it is stabilized again, a process called reconsolidation. Information presented during this window may modify later recall. However, failure to reproduce an effect does not necessarily refute reconsolidation; prediction error, memory age, strength, and timing can determine whether destabilization occurs. Conversely, any post-retrieval change should not automatically be labeled reconsolidation because ordinary interference or new learning may explain it.', [
    ['What is meant by a memory becoming labile?', ['Retrieval temporarily makes its stored representation susceptible to modification', 'The remembered event is permanently erased at the moment of recall', 'Every new experience becomes indistinguishable from the old memory', 'Stabilization prevents any later retrieval from occurring'], 0, 'Lability is a temporary state of modifiability.'],
    ['Why does the lecturer caution against broad claims?', ['Both boundary conditions and alternative learning mechanisms must be evaluated', 'Reconsolidation occurs identically for memories of every age and strength', 'Prediction error measures whether a participant is deliberately lying', 'Interference can operate only before an event is initially encoded'], 0, 'Observed change alone does not uniquely identify the mechanism.'],
  ]),
  ...listeningGroup('talk-photonic', 'Listen to an Academic Talk', '광학재료', 'C1', 'Some vivid biological colors come from microscopic structure rather than pigment. Repeated layers or ordered features on a scale comparable to wavelengths of light cause certain wavelengths to reinforce while others cancel. Because the optical path changes with viewing angle, structural colors may appear iridescent. Disorder can broaden the reflected range and produce a more angle-independent color. Engineers imitate these structures for sensors and low-fade coatings, but reproducing nanoscale order over large flexible surfaces remains difficult.', [
    ['What produces selective reflection in a structural color?', ['Interference among light waves interacting with regularly spaced features', 'Chemical dyes absorbing every wavelength at the same rate', 'Heat emitted from microscopic biological pigments', 'Flexible surfaces eliminating all nanoscale variation'], 0, 'Geometry creates wavelength-dependent constructive interference.'],
    ['How can disorder reduce iridescence?', ['It mixes structural spacings and directions so reflection varies less sharply with angle', 'It converts reflected light entirely into chemical energy', 'It forces every layer to adopt one perfectly uniform thickness', 'It prevents any visible wavelength from reaching the observer'], 0, 'A distribution of structures broadens and averages the response.'],
  ]),
  ...listeningGroup('talk-domestication', 'Listen to an Academic Talk', '고고생물학', 'B2', 'Domestication changes populations across generations, but not every trait associated with humans was intentionally selected. Early cultivators may have favored plants with larger seeds, while harvesting practices unintentionally favored seed heads that did not shatter. Archaeologists track gradual shifts in seed size and dispersal structures across dated deposits. A single unusually large specimen is weak evidence because wild populations vary and preservation can distort dimensions. Patterns across many specimens and sites better reveal sustained selection.', [
    ['How could nonshattering seed heads increase without deliberate selection?', ['Harvesting and resowing disproportionately retained seeds that stayed attached', 'Wild plants stopped producing any variable dispersal structures', 'Preservation enlarged every cultivated specimen equally', 'Early farmers manually changed the genes of each seed head'], 0, 'A repeated harvesting filter can cause unintended evolutionary change.'],
    ['Why is one large ancient seed inconclusive?', ['Natural variation and preservation effects can produce an isolated extreme value', 'Seed dimensions cannot be measured in archaeological deposits', 'Intentional cultivation always reduces seed size at first', 'Domestication must occur simultaneously at every site'], 0, 'Population-level change requires a distributional pattern.'],
  ]),
  ...listeningGroup('talk-pluralism', 'Listen to an Academic Talk', '법인류학', 'C1', 'Legal pluralism describes situations in which state law operates alongside customary, religious, professional, or community rules. These orders are not sealed systems. People may choose a forum strategically, and institutions may borrow concepts from one another. A dispute over land, for example, can involve a government title, lineage claims, and local mediation at once. Calling one order informal does not mean it lacks coercive force or legitimacy for participants. Researchers therefore study actual practices and power relations, not merely written codes.', [
    ['What does strategic forum choice imply?', ['People may invoke the normative system most favorable or accessible to their claim', 'Only government courts can recognize a dispute involving land', 'Customary rules remain completely isolated from state institutions', 'Written codes determine which legal order participants consider legitimate'], 0, 'Overlapping orders create opportunities and constraints for claimants.'],
    ['Why does the lecturer emphasize observed practice?', ['Formal texts alone miss interaction, enforcement, and unequal power among rule systems', 'Community norms never appear in any written form', 'Professional regulation has no consequences outside state courts', 'Researchers can infer legitimacy solely from the age of a rule'], 0, 'Law in action may differ from categorical descriptions.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the anomaly overlooked?', 'Only after rechecking the raw files', ['did we notice', 'that the sensor', 'had drifted', 'during calibration'], 'negative-inversion-after-only'],
  ['Could the conclusion have changed?', 'Had the missing cases been included', ['the estimated effect', 'might have been', 'substantially smaller', 'than reported'], 'inverted-third-conditional'],
  ['Why retain the older model?', 'Although it fits less precisely', ['it makes', 'fewer assumptions', 'about mechanisms', 'we cannot observe'], 'concessive-relative-clause'],
  ['Which samples were reanalyzed?', 'The specimens collected near the outflow', ['having shown', 'unexpected isotope ratios', 'were tested', 'by another laboratory'], 'perfect-participial-clause'],
  ['When did the committee recognize the conflict?', 'Not until the contracts were compared', ['did the reviewers', 'realize that', 'both bidders', 'shared an owner'], 'not-until-inversion'],
  ['What makes the archive valuable?', 'Its significance lies not merely in its age', ['but in', 'the continuity', 'with which records', 'were preserved'], 'not-merely-but-prepositional'],
  ['Why repeat the experiment?', 'Were the pattern to disappear', ['under blinded conditions', 'we would have', 'reason to suspect', 'an observer effect'], 'inverted-second-conditional'],
  ['How should the policy be assessed?', 'What matters is not whether it sounds equitable', ['but whether', 'its implementation', 'actually benefits', 'excluded groups'], 'pseudo-cleft-correlative'],
  ['What did the editor require?', 'The editor insisted that every numerical claim', ['be linked', 'to a table', 'whose assumptions', 'were stated explicitly'], 'mandative-subjunctive-relative'],
  ['Why is the comparison difficult?', 'So unevenly were the sites sampled', ['that apparent differences', 'could reflect', 'survey effort', 'rather than ecology'], 'so-adverb-inversion-result'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '데이터 무결성', 'C1', 420), instruction: '상황, 연구 위험, 즉각적 조치와 재발 방지 절차를 구체적으로 작성하세요.', prompt: 'During a shared analysis, you discover that several rows were manually reordered after the participant identifiers had been hidden, so outcomes may no longer match the correct records. Write to the project leader. Explain what you found, describe why continuing would be unsafe, and request a documented recovery and verification procedure.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '과학적 불확실성', 'C1', 600), instruction: '두 관점의 한계를 평가하고 명확한 논거와 사례로 자신의 입장을 발전시키세요.', prompt: 'Professor Adeyemi: When scientific evidence is uncertain but a potential harm is serious, should governments act before researchers reach strong consensus?', passage: 'Priya: Early precaution can prevent irreversible damage while evidence develops.\nJonas: Premature rules can impose large costs and lock society into an incorrect explanation.' })

const repeatSentences = ['Welcome to the university special-collections orientation.', 'Place coats and personal bags in the secure lockers.', 'Use the foam supports whenever you open a bound manuscript.', 'Turn fragile pages from their outer edges without pressing the surface.', 'Keep each archival folder aligned with its original placeholder card.', 'Ask a staff member before unfolding maps or removing attached fasteners.', 'Before leaving, return all materials to the desk so staff can verify their order, record their condition, and close your request.']
const interviewQuestions = ['Describe a situation in which people had to make a decision with incomplete evidence.', 'What risks came from acting too early or waiting too long?', 'Who should decide how much uncertainty is acceptable in that situation?', 'How should experts communicate uncertainty without causing either panic or false reassurance?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '특별 소장품 이용', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f13-repeat', scenarioId: 'f13-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '불확실성과 의사결정', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f13-interview', scenarioId: 'f13-interview', sequenceIndex })),
]

export const AUTHORED_FORM_13_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_13_IDS = AUTHORED_FORM_13_ITEMS.map((item) => item.id)
