import { prepareSentenceTiles } from './sentenceTiles'
import type { BaseItem } from './types'

type Difficulty = NonNullable<BaseItem['difficulty']>
type Question = [prompt: string, options: string[], answer: number, explanation: string]
const base = (id: string, section: BaseItem['section'], kind: BaseItem['kind'], title: string, topic: string, difficulty: Difficulty, timeSeconds: number): BaseItem => ({ id: `f06-${id}`, section, module: 1, kind, title, topic, difficulty, timeSeconds, instruction: '', sourceFamily: 'authored-form-06' })
const cloze = (id: string, topic: string, difficulty: Difficulty, passage: string, answer: string): BaseItem => ({ ...base(id, 'reading', 'complete-words', 'Complete the Words', topic, difficulty, 240), instruction: '첫 문장을 읽고 문맥과 문법에 맞게 열 개 단어를 완성하세요.', passage, answer, explanation: '의미뿐 아니라 품사, 시제, 수 일치에 맞는 철자가 필요합니다.' })
const daily = (id: string, topic: string, difficulty: Difficulty, passage: string, q: Question): BaseItem => ({ ...base(id, 'reading', 'multiple-choice', 'Read in Daily Life', topic, difficulty, 75), instruction: '실용문의 조건, 제한, 예외를 구분해 답하세요.', passage, prompt: q[0], options: q[1], answer: q[2], explanation: q[3] })
const readingGroup = (id: string, topic: string, difficulty: Difficulty, passage: string, questions: Question[]): BaseItem[] => questions.map((q, sequenceIndex) => ({ ...base(`${id}-${sequenceIndex}`, 'reading', 'multiple-choice', 'Read an Academic Passage', topic, difficulty, 120), instruction: '학술 지문의 주장, 방법, 한계와 함의를 파악하세요.', passage, prompt: q[0], options: q[1], answer: q[2], explanation: q[3], stimulusGroupId: `f06-${id}`, sequenceIndex }))
const response = (id: number, audioText: string, options: string[], answer: number, explanation: string): BaseItem => ({ ...base(`response-${id}`, 'listening', 'listen-choice', 'Listen and Choose a Response', '캠퍼스 의사소통', id < 8 ? 'B1' : 'B2', 35), instruction: '짧은 말을 듣고 가장 자연스러운 응답을 고르세요.', audioText, options, answer, explanation })
const listeningGroup = (id: string, title: string, topic: string, difficulty: Difficulty, audioText: string, questions: Question[]): BaseItem[] => questions.map((q, sequenceIndex) => ({ ...base(`${id}-${sequenceIndex}`, 'listening', 'listen-choice', title, topic, difficulty, title === 'Listen to an Announcement' ? 55 : title === 'Listen to an Academic Talk' ? 80 : 70), instruction: title === 'Listen to an Announcement' ? '공지의 변경 사항과 필요한 행동을 파악하세요.' : title === 'Listen to an Academic Talk' ? '강의의 핵심 개념과 증거 관계를 파악하세요.' : '대화의 문제, 제약, 해결 과정을 파악하세요.', audioText, prompt: q[0], options: q[1], answer: q[2], explanation: q[3], stimulusGroupId: `f06-${id}`, sequenceIndex }))

const reading: BaseItem[] = [
  cloze('cloze-radiocarbon', '연대측정학', 'C1', 'Radiocarbon dating estimates when once-living material stopped exchanging carbon with the environment. Radioactive carbon-14 dec___ at a known average rate, so the remaining proportion can ind___ elapsed time. The method does not directly date stone or metal. Contamination can int___ younger or older carbon, and atmospheric carbon has var___ through history. Researchers cal___ raw ages against independently dated records such as tree rings. They also sel___ samples whose relationship to the event is clear. A wooden beam may pre___ a building if old timber was reused. Reliable interpretation therefore req___ laboratory precision, archaeological context, and exp___ uncertainty rather than a single exact year being rep___ without qualification.', 'ays|icate|roduce|ied|ibrate|ect|date|uires|licit|orted'),
  cloze('cloze-green-roofs', '도시생태학', 'B2', 'Green roofs cover buildings with vegetation and engineered soil. They can abs___ rainfall, cool roof surfaces, and provide habitat for insects. Their performance dep___ on soil depth, plant choice, climate, and maintenance. A roof that ret___ water during a small storm may overflow during an extreme one. Added weight also req___ structural assessment. Researchers comp___ green roofs with similar conventional roofs and mon___ them across seasons. Energy savings may be lar___ in poorly insulated buildings than in efficient ones. Because benefits var___ by setting, city programs should not ass___ that one design is optimal everywhere. Long-term data help planners pri___ installations with the greatest likely value.', 'orb|ends|ains|uires|are|itor|ger|y|ume|oritize'),
  cloze('cloze-epigenetics', '분자생물학', 'C1', 'Cells with the same DNA can express different genes. Epigenetic mechanisms help reg___ this activity without changing the nucleotide sequence. Chemical marks on DNA or histone proteins can aff___ how readily genes are transcribed. Some marks respond to development or environment, but they are not simple rec___ of every experience. During cell division, certain patterns can be main___; across generations, many are reset. Claims of inherited environmental effects therefore req___ careful evidence that excludes genetic variation and shared conditions. Researchers distin___ correlation from mechanism and rep___ findings in independent samples. Epigenetics exp___ how stable cellular identities arise, yet it does not imp___ that genes cease to matter or that acquired traits are uni___ inherited.', 'ulate|ect|ords|tained|uire|guish|licate|lains|ly|versally'),
  daily('daily-clean-room', '반도체 시설', 'C1', 'Clean-room access expires when either respirator clearance or contamination-control training lapses. The badge system may continue to display an active date for several hours after a health clearance is withdrawn. Users are responsible for checking both records in the safety portal before entering.', ['Why should a user not rely exclusively on the badge display?', ['Its status may temporarily lag behind a withdrawn safety authorization', 'It records contamination training but never respirator information', 'The badge becomes valid before any training is completed', 'Health clearance applies only after a user enters the room'], 0, 'The access display can be stale after a separate prerequisite changes.']),
  daily('daily-special-collections', '희귀자료 예약', 'B2', 'Readers may request six archival boxes per appointment, but only one box is delivered to the desk at a time. Requests added after noon on the preceding business day are not guaranteed. Photographing is allowed unless a folder carries a restriction slip; copying a neighboring unrestricted page does not remove that restriction.', ['Which material may a reader photograph?', ['A page in a folder without a restriction notice', 'Any document beside an unrestricted archival page', 'All six boxes immediately after a late request', 'A restricted folder after another box is delivered'], 0, 'Permission is determined at the folder level, not by nearby material.']),
  daily('daily-swim-test', '수상 안전', 'B1', 'Students joining the coastal field course must complete a swim test by May 10. A lifeguard certificate does not replace the test, but students with a documented mobility condition may request an adapted assessment through accessibility services.', ['Who may use an altered assessment procedure?', ['A student whose mobility accommodation has been documented', 'Any participant holding a current lifeguard certificate', 'A student who registers after the May deadline', 'Every participant who prefers not to enter the pool'], 0, 'The adapted route is tied to a documented accessibility need.']),
  daily('daily-procurement', '연구 구매', 'C1', 'Purchases above five thousand dollars normally require three written quotations. A sole-source justification may replace competing quotations only when it explains which essential technical feature no alternative supplier can provide. Convenience, prior familiarity, or a short internal deadline is insufficient.', ['What could justify buying expensive equipment from one supplier?', ['A documented capability uniquely required by the research', 'The laboratory’s preference for a familiar sales representative', 'A deadline created by delayed internal planning', 'The absence of time to compare ordinary specifications'], 0, 'The exception requires an essential feature that competitors genuinely lack.']),
  daily('daily-gallery-talk', '박물관 교육', 'B1', 'Saturday’s gallery talk is free with museum admission, but space in the conservation studio is limited. Visitors collect same-day passes at the information desk beginning at eleven. Online admission tickets do not reserve a place in the talk.', ['How does a visitor secure a place in the gallery talk?', ['Obtain a separate pass at the museum on Saturday', 'Purchase any online admission ticket in advance', 'Enter the conservation studio before eleven', 'Request a reservation from the speaker by email'], 0, 'General admission and the limited-capacity talk use separate access procedures.']),
  daily('daily-drill-press', '제작실 안전', 'B2', 'The drill press may be used independently only after an in-person checkout. Watching the training video allows a student to attend the checkout but does not authorize solo operation. Damaged bits should be placed in the red container and reported; do not return them to the shared drawer.', ['What does completing the video permit a student to do?', ['Proceed to the supervised equipment checkout', 'Operate the drill press alone immediately', 'Return damaged components to general storage', 'Skip the required in-person demonstration'], 0, 'The video is a prerequisite for, not a substitute for, the checkout.']),
  daily('daily-language-table', '회화 프로그램', 'B2', 'Conversation-table hosts submit attendance after each meeting. Participants earn program credit only when they remain for at least forty minutes and sign in with their university identifier. A host’s memory of attendance cannot replace a missing identifier after the weekly report is filed.', ['What must a participant do to receive credit?', ['Stay for the minimum time and provide the required identifier', 'Ask the host to reconstruct attendance after filing', 'Attend briefly without using the sign-in system', 'Lead the entire meeting instead of participating'], 0, 'Both duration and recorded identity are required.']),
  daily('daily-boat', '해양 조사', 'C1', 'Research-boat departures depend on both wind limits and the harbor master’s clearance. A favorable forecast does not confirm sailing. The chief scientist sends final notice ninety minutes before departure; until then, team members should prepare samples but must not transport refrigerated material to the dock.', ['When should refrigerated samples be taken to the dock?', ['Only after the chief scientist issues the final sailing notice', 'As soon as the wind forecast falls below the limit', 'Before the harbor master evaluates conditions', 'Ninety minutes before any possible departure date'], 0, 'Forecasts are provisional; the final message authorizes transport.']),
  daily('daily-counseling', '학생 지원', 'B1', 'Same-day counseling consultations address urgent concerns and help students choose next steps. They are not recurring therapy appointments. Students seeking ongoing care can still use a consultation, but the counselor may refer them to a scheduled campus service or an external provider.', ['What is one purpose of a same-day consultation?', ['To identify appropriate follow-up support', 'To guarantee a weekly appointment with the same counselor', 'To replace every form of long-term treatment', 'To register an external provider as campus staff'], 0, 'The visit assesses immediate needs and routes later care.']),
  daily('daily-heritage-language', '학점 인정', 'C1', 'Heritage speakers may earn language credit through an assessment, but they cannot enroll in the introductory course solely to obtain an easy grade. Students who can understand family conversation yet lack literacy should meet the placement coordinator; the appropriate course may emphasize reading and formal writing rather than elementary speaking.', ['What is recommended for a heritage speaker with uneven language skills?', ['Placement based on the specific gap between oral and literacy abilities', 'Automatic entry into the lowest speaking course', 'Credit awarded without any assessment', 'Exclusion from courses involving formal written language'], 0, 'A targeted placement can build literacy without repeating mastered oral basics.']),
  ...readingGroup('academic-did', '정책평가', 'C1', 'Difference-in-differences is used when a policy affects one group but not another. Researchers compare the treated group’s change over time with the comparison group’s change, subtracting the latter from the former. This removes stable differences between groups and common time shocks. The key parallel-trends assumption is not that the groups had equal outcome levels; it is that, without treatment, their trends would have evolved similarly. Pre-policy trends can make this assumption more plausible, but matching lines before treatment cannot prove what would have happened afterward. Anticipation, simultaneous policies, or changes in group composition can still bias the estimate.', [
    ['What does the comparison group contribute to the design?', ['An estimate of the time change that might have occurred without treatment', 'Proof that both groups began with identical outcome levels', 'A method for eliminating every policy introduced simultaneously', 'A guarantee that group membership never changes'], 0, 'Its trajectory provides the counterfactual time component.'],
    ['What does the parallel-trends assumption concern?', ['The untreated evolution of outcomes rather than their starting levels', 'The requirement that treatment begin before all observations', 'The equality of sample sizes in every period', 'The absence of any measured baseline difference'], 0, 'Different levels are compatible with parallel counterfactual movement.'],
    ['Why are similar pre-policy trends insufficient as definitive proof?', ['Post-policy counterfactual behavior remains unobserved and other changes may intervene', 'Historical observations contain no information about trend plausibility', 'The method requires treatment to occur in both groups', 'Similar lines show that outcomes cannot respond to policy'], 0, 'Pretrends support but cannot verify the unobserved assumption.'],
  ]),
  ...readingGroup('academic-islands', '생물지리학', 'B2', 'The equilibrium theory of island biogeography predicts that species richness reflects a balance between immigration and extinction. Islands near a mainland receive colonists more often, while larger islands generally support bigger populations and more varied habitats, reducing extinction risk. The equilibrium number is dynamic: species can disappear and be replaced even when total richness stays similar. Real islands differ in age, habitat, and evolutionary history, so distance and area are not complete explanations. The framework is valuable because it generates comparative predictions, not because every island must contain a fixed number of species.', [
    ['Why may species composition change while richness remains stable?', ['Extinctions and new colonizations can offset one another numerically', 'Every immigrant belongs to a species already present', 'Large islands permanently prevent all local extinction', 'Distance determines the identity of each arriving organism'], 0, 'Turnover can preserve the total while replacing particular species.'],
    ['How should the theory be used according to the passage?', ['As a source of testable tendencies alongside additional island history', 'As proof that area is the only cause of biological diversity', 'As an exact inventory for any island at any moment', 'As evidence that isolated islands receive colonists most frequently'], 0, 'The framework predicts patterns but does not exhaust real-world causes.'],
  ]),
  ...readingGroup('academic-writing', '문자학', 'C1', 'Writing systems represent language in different ways. An alphabet typically marks consonants and vowels, while an abjad primarily records consonants and a syllabary uses signs for syllables. These categories describe organizing principles, not rigid boxes. English spelling preserves historical distinctions that no longer match pronunciation, and readers of an abjad can use optional vowel marks or contextual knowledge. A script may also adapt when borrowed for another language. Evaluating a system by asking whether it perfectly transcribes speech overlooks other functions, including linking related words, preserving tradition, and allowing readers across dialects to share texts.', [
    ['Why does the author resist treating script categories as rigid?', ['Actual systems combine conventions and change across languages and history', 'Every sign in every script represents a complete sentence', 'Pronunciation remains identical wherever a script is borrowed', 'Optional markings prevent readers from using context'], 0, 'Real orthographies modify their dominant representational principle.'],
    ['What limitation is identified in judging spelling only by phonetic accuracy?', ['It ignores morphological, historical, and cross-dialectal functions', 'It assumes that related words should always look different', 'It places excessive value on traditional written continuity', 'It proves that alphabets cannot represent consonants'], 0, 'Writing can preserve relationships and accessibility that sound-only criteria miss.'],
    ['Which example best supports the claim that readers use more than written vowel information?', ['Context helps an abjad reader select a plausible vocalization', 'A syllabary assigns one sign to every paragraph', 'Borrowed scripts are never altered by new users', 'English spelling changes whenever one speaker’s accent shifts'], 0, 'Interpretation can draw on lexical and sentence context when vowels are not fully marked.'],
  ]),
  ...readingGroup('academic-tomography', '지구물리학', 'C1', 'Seismic tomography uses earthquake waves to infer structures inside Earth, much as medical tomography uses signals passing through a body. Wave speed depends on temperature, composition, pressure, and whether rock is partially molten. Scientists combine arrival times from many earthquakes recorded at many stations and solve an inverse problem for a three-dimensional model. Coverage is uneven because earthquakes and instruments are not distributed uniformly. A slow region is therefore not automatically a hot rising plume; alternative materials or limited resolution may explain it. Independent geological and geochemical evidence helps constrain interpretation.', [
    ['Why are many earthquake-station paths combined?', ['Different routes provide constraints for estimating a three-dimensional interior', 'A single wave measures temperature without any ambiguity', 'Uniform global coverage makes inverse modeling unnecessary', 'Medical instruments can be placed directly inside Earth'], 0, 'Crossing paths make otherwise inaccessible spatial structure estimable.'],
    ['What caution applies to interpreting a slow-wave region?', ['Several physical causes and inadequate resolution can produce the observation', 'Slow speed uniquely proves the presence of molten rock', 'Arrival time is independent of composition and pressure', 'Geochemical evidence becomes irrelevant after tomography'], 0, 'Velocity is influenced by multiple properties, so corroboration is needed.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you upload the revised consent form today?', ['Yes, after the principal investigator signs the final page.', 'The upload speed is faster in the library.', 'Consent can be withdrawn at any time.', 'I revised my travel plans last night.'], 0, 'The response accepts the request subject to the relevant signature.'),
  response(1, 'Why is the east studio unavailable?', ['The studio contains adjustable lighting.', 'A ceiling leak is being repaired there.', 'I studied eastern architecture last term.', 'Availability depends on the reservation length.'], 1, 'The repair directly explains the closure.'),
  response(2, 'Did the printer produce the transparent overlays?', ['The printer stands beside the supply cabinet.', 'Transparency is important in public policy.', 'Only two; it ran out of the special film.', 'I overlaid the maps in the software.'], 2, 'The reply gives the result and reason for incomplete production.'),
  response(3, 'Would you be able to chair the afternoon panel?', ['The chairs are arranged in a semicircle.', 'The panel examines renewable energy.', 'Afternoons are usually quieter in this building.', 'I can, provided my earlier session ends on time.'], 3, 'The conditional acceptance is relevant to scheduling.'),
  response(4, 'I thought the fellowship covered health insurance.', ['It does, but you must enroll before the waiver deadline.', 'The fellowship application asks for two essays.', 'Insurance can reduce unexpected financial risk.', 'I covered the equipment before leaving.'], 0, 'The reply confirms coverage while adding a necessary action.'),
  response(5, 'Where should the replacement filters be stored?', ['The filter removed most of the background noise.', 'In the dry cabinet labeled for unopened supplies.', 'Replacement costs increased this year.', 'I stored the results in a spreadsheet.'], 1, 'The answer identifies the correct storage location.'),
  response(6, 'Shouldn’t the axes use the same numerical scale?', ['The numerical methods class meets on Tuesday.', 'An axis can be horizontal or vertical.', 'Yes, if we want the visual comparison to be fair.', 'The scales were calibrated before fieldwork.'], 2, 'The reply links equal scales to valid visual comparison.'),
  response(7, 'The department moved my lecture to a smaller room.', ['The department offers six lecture courses.', 'I moved the microscope very carefully.', 'The smaller sample has wider uncertainty.', 'Then confirm that its capacity still meets your enrollment.'], 3, 'Capacity is the relevant consequence of the room change.'),
  response(8, 'Can this voucher be used for train travel?', ['Only for travel listed in the approved project budget.', 'The train reaches the airport in forty minutes.', 'This voucher is printed on recycled paper.', 'I used the last sample during calibration.'], 0, 'The reply states the governing eligibility condition.'),
  response(9, 'Why did the ethics office return the application?', ['The office is across from the health center.', 'The risk section did not describe data retention.', 'I applied the coating with a soft brush.', 'Return postage is included in the fee.'], 1, 'A missing required protocol detail explains the return.'),
  response(10, 'Could selection bias account for the difference?', ['The selection committee has seven members.', 'Different accounts use separate passwords.', 'Possibly, because participation was voluntary.', 'I biased the lamp away from the screen.'], 2, 'Voluntary participation is a plausible selection mechanism.'),
  response(11, 'I can’t tell which specimen this label belongs to.', ['The specimen came from a deep sediment layer.', 'Labels are printed with waterproof ink.', 'Belonging can strengthen community trust.', 'Leave both untouched until the catalog record is checked.'], 3, 'Preserving the uncertain association prevents a damaging guess.'),
  response(12, 'Is tomorrow’s rehearsal still in the concert hall?', ['No, it has been moved to the black-box theater.', 'Tomorrow’s concert features a string quartet.', 'The hall was designed for natural acoustics.', 'I rehearsed the introduction twice.'], 0, 'The response supplies the updated venue.'),
  response(13, 'When will the replacement access cards arrive?', ['The cards use an encrypted identification chip.', 'Security expects them early next week.', 'I arrived before the building opened.', 'Replacement is preferable to temporary repair.'], 1, 'The reply provides the expected delivery period.'),
  response(14, 'Would removing that variable solve the collinearity problem?', ['The solution contains a weak acid.', 'Variables appear in the appendix table.', 'It might, but we should first examine why they overlap.', 'I removed the duplicate page from the report.'], 2, 'The response favors diagnosing the relationship before modification.'),
  response(15, 'Who can authorize overtime for the field assistants?', ['Field assistants record weather and location.', 'Authorization should be requested in writing.', 'Overtime begins after the contracted weekly total.', 'The project director must approve it in advance.'], 3, 'The answer names the responsible approver and timing.'),
  response(16, 'The reference manager changed all the author initials.', ['Restore the original import settings and rerun the metadata update.', 'The manager referenced an earlier version of the policy.', 'Initial findings often change after peer review.', 'Every author approved the final manuscript.'], 0, 'Restoring settings addresses a systematic metadata transformation.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-transcript', 'Listen to a Conversation', '학점 인정', 'B2', 'Student: My exchange transcript lists the course as “Topics in Biology,” so the department will not count it toward ecology. Advisor: The title is too broad. Ask the host university for a syllabus showing weekly content and assessment. Student: The instructor retired. Advisor: The international office may have an archived syllabus. If not, obtain a departmental description from that year. A current description will not establish what your section covered.', [
    ['Why has the course not yet been approved?', ['Its transcript title does not provide enough evidence about subject content', 'The student received the transcript after returning home', 'Ecology courses cannot transfer from exchange programs', 'The current instructor refuses to assign a grade'], 0, 'The generic title cannot establish equivalence.'],
    ['What kind of substitute evidence might be acceptable?', ['An official description corresponding to the year the course was taken', 'A present-day advertisement for a different biology class', 'The student’s memory without institutional documentation', 'A retirement notice for the former instructor'], 0, 'Contemporaneous institutional evidence can document the actual course.'],
  ]),
  ...listeningGroup('conversation-kiln', 'Listen to a Conversation', '도예 작업', 'B2', 'Student: The glaze on my bowl blistered, but the test tile looked smooth. Technician: Was the bowl bisque-fired in the same kiln as the tile? Student: No, it came from the older kiln. Technician: Then the clay may have retained more moisture or the firing curve differed. Before changing the glaze recipe, test another bowl from that batch in the newer kiln and place a witness cone beside it.', [
    ['Why does the technician hesitate to blame the glaze formula?', ['The test objects experienced different earlier firing conditions', 'The smooth tile used an entirely undocumented color', 'Witness cones can alter the chemical recipe', 'The older kiln always produces lower moisture clay'], 1, 'The firing history is confounded with object type.'],
    ['What will the witness cone help determine?', ['The heat work actually experienced during the new test', 'The exact moisture content before bisque firing', 'Whether the bowl’s shape is aesthetically successful', 'Which student originally mixed the glaze'], 1, 'A cone records the combined thermal exposure of the firing.'],
  ]),
  ...listeningGroup('conversation-census', 'Listen to a Conversation', '현장 생태', 'C1', 'Researcher: Bird counts fell sharply at our western site this month. Assistant: We also changed the survey start from dawn to nine because the road gate opens later. Researcher: So the decline may reflect lower detectability rather than fewer birds. Assistant: We can compare only the overlapping hours from acoustic recorders and note the protocol break. For next season, we should arrange gate access or keep autonomous recorders at every site.', [
    ['What alternative explanation is proposed for the lower count?', ['Later observation reduced the chance of detecting active birds', 'The road gate permanently removed habitat from the site', 'Acoustic recorders increased the true bird population', 'Every species migrated because the survey used dawn hours'], 2, 'Changed timing can affect measurement independently of abundance.'],
    ['How will the researchers make the current comparison more defensible?', ['Restrict analysis to temporally comparable recording data and disclose the change', 'Treat manual counts and recordings as identical at every hour', 'Delete the western site because its count is lower', 'Estimate dawn activity using no observations'], 2, 'Matched hours reduce the timing confound while reporting the limitation.'],
  ]),
  ...listeningGroup('conversation-projection', 'Listen to a Conversation', '공연 기술', 'B2', 'Director: The subtitles are readable from the center, but not from the side seats. Designer: The projector is aligned to a flat screen while the backdrop curves. We could move the text to the upper rectangular panel. Director: Would that distract from the actors? Designer: Let us test two sizes during rehearsal and photograph the view from the outer seats. Brightness alone will not fix geometric distortion.', [
    ['What causes the readability problem?', ['The display surface and projection geometry do not match', 'The actors are speaking more softly from the side', 'The text uses an excessively bright background color', 'The outer seats are closer to the rectangular panel'], 3, 'A curved backdrop distorts an image aligned for a plane.'],
    ['Why will the team photograph several viewing positions?', ['To evaluate the alternative layout from seats with different sight lines', 'To replace the subtitles with still images of actors', 'To measure only the projector’s electricity use', 'To avoid testing font sizes during rehearsal'], 3, 'Evidence from side seats directly tests whether the new placement works.'],
  ]),
  ...listeningGroup('conversation-data-use', 'Listen to a Conversation', '데이터 협약', 'C1', 'Student: The city gave us traffic records for the bus study. Can I use them for my separate project on emergency response? Supervisor: Not under the current agreement. It limits use to transit planning and requires derived files to stay on the secure server. Student: The records are already anonymized. Supervisor: That reduces privacy risk, but it does not expand contractual permission. Submit an amendment describing the new purpose, variables, and collaborators before doing any analysis.', [
    ['Why is anonymization insufficient for the new project?', ['Permitted use is constrained independently by the data agreement', 'Anonymous records contain no variables useful for analysis', 'Emergency response is identical to transit planning', 'The secure server automatically approves new research purposes'], 0, 'Privacy protection and authorized purpose are separate requirements.'],
    ['What must the student do before beginning the additional analysis?', ['Obtain an amended authorization specifying the expanded use', 'Move all derived files onto a personal computer', 'Add collaborators without identifying them', 'Reidentify traffic records to verify their origin'], 1, 'A formal amendment must precede work outside the existing scope.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-heating', 'Listen to an Announcement', '기숙사 시설', 'B2', 'Heating in Maple Residence will be reduced tomorrow from ten to two while valves are balanced. Rooms should remain above the minimum indoor standard, but residents with temperature-sensitive medical equipment should contact housing tonight so backup space can be arranged. Opening windows will interfere with the balancing process, so report an overheated room instead of ventilating it.', [
    ['Who should contact housing before the maintenance period?', ['Residents whose medical equipment depends on stable temperature', 'Everyone planning to open a window tomorrow', 'Only students assigned to backup maintenance work', 'Residents who prefer a warmer room for studying'], 0, 'A specific equipment-related need warrants advance arrangements.'],
    ['What should a resident do if a room becomes too warm?', ['Notify housing rather than changing airflow through a window', 'Leave every valve open after maintenance ends', 'Move immediately into the equipment backup room', 'Adjust the building balance without assistance'], 0, 'Open windows would undermine the system test.'],
  ]),
  ...listeningGroup('announcement-archive', 'Listen to an Announcement', '디지털 기록', 'C1', 'The university archive will preserve student-organization websites at the end of term. Dynamic pages requiring a login cannot be captured automatically. Groups should export public-facing copies of important members-only pages and remove personal contact information before submitting them. The archive preserves historical appearance but does not maintain interactive forms, payment links, or external video embeds.', [
    ['What must organizations do for important restricted pages to be archived?', ['Create sanitized accessible versions for submission', 'Give the archive permanent member passwords', 'Leave private contact details visible for historical accuracy', 'Convert all public pages into payment forms'], 1, 'The crawler needs accessible static content without exposed personal data.'],
    ['Which feature will not remain functional in the archived site?', ['An interactive link used to collect payments', 'The visual layout of a public information page', 'A submitted static copy of a members-only announcement', 'Text describing the organization’s past activities'], 1, 'Interactive services are outside preservation scope.'],
  ]),
  ...listeningGroup('announcement-orientation', 'Listen to an Announcement', '현장실습', 'B2', 'Tomorrow’s geology field orientation has moved indoors because the quarry path is flooded. Bring field notebooks anyway; instructors will practice rock descriptions using the teaching collection. The outdoor safety briefing remains mandatory and will be delivered in the lecture hall. Students who miss it cannot join next week’s quarry trip even if they have completed last year’s briefing.', [
    ['What should students bring to the relocated session?', ['Their field notebooks for indoor specimen practice', 'Protective gear for entering the flooded quarry', 'Only proof of last year’s safety attendance', 'Samples collected independently from the quarry'], 2, 'The materials remain useful for the substitute activity.'],
    ['Why must returning students attend the safety briefing?', ['Prior-year completion does not authorize this year’s trip', 'The briefing occurs on the quarry path despite flooding', 'Rock description is prohibited without a new notebook', 'The teaching collection contains no geological material'], 2, 'Current participation depends on the current mandatory briefing.'],
  ]),
  ...listeningGroup('announcement-cafe', 'Listen to an Announcement', '캠퍼스 식당', 'B1', 'The student café will test reusable takeaway containers beginning Monday. Pay a small deposit at checkout and return the rinsed container to any participating campus café within seven days. It does not need to return to the original location. Containers returned late are still accepted, but the deposit becomes a program fee and is not refunded.', [
    ['Where may a borrowed container be returned?', ['At any campus café participating in the trial', 'Only at the exact checkout counter', 'At an off-campus recycling station', 'In an ordinary residence trash bin'], 3, 'The return network includes multiple participating cafés.'],
    ['What is the consequence of returning it after seven days?', ['The container is accepted, but the deposit is forfeited', 'The café refuses the container permanently', 'The deposit doubles before being refunded', 'The borrower loses access to every dining location'], 3, 'Late return does not block acceptance but changes the payment status.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-phototropism', 'Listen to an Academic Talk', '식물생리학', 'B2', 'A young shoot often bends toward light because the hormone auxin becomes unevenly distributed. On the shaded side, auxin promotes greater cell elongation, causing that side to grow faster and curve the shoot toward the light source. The plant is not moving like an animal; differential growth changes its form. Mature tissues may respond less strongly, and roots can react differently because hormone concentration and tissue sensitivity alter the effect.', [
    ['What directly produces bending in the young shoot?', ['Unequal elongation rates on its illuminated and shaded sides', 'Rapid contraction of muscles inside the stem', 'Complete removal of auxin from shaded tissue', 'Identical growth on every side of the plant'], 0, 'Asymmetric growth curves the organ.'],
    ['Why might roots respond differently to the same hormone?', ['Tissue type and concentration modify the biological response', 'Roots receive light through specialized animal eyes', 'All mature tissues lack any sensitivity to hormones', 'Auxin always makes every plant cell elongate equally'], 0, 'Hormonal effects are context- and dose-dependent.'],
  ]),
  ...listeningGroup('talk-network', 'Listen to an Academic Talk', '산업경제학', 'C1', 'A network effect exists when a service becomes more valuable to a user as more compatible users join. Communication platforms are an obvious example, but size alone is not sufficient. A large network with poor matching or congestion can provide less value than a smaller well-organized one. Network effects can make entry difficult for competitors because customers hesitate to leave established contacts. Interoperability can reduce this barrier by allowing users of different services to communicate.', [
    ['Why can an incumbent platform be difficult to challenge?', ['Users risk losing access to an established web of contacts', 'Every large network necessarily eliminates congestion', 'Competitors are prohibited from improving match quality', 'Service value depends only on production cost'], 1, 'Existing connections raise the switching cost for coordinated users.'],
    ['How can interoperability change the competitive situation?', ['It weakens the need for all contacts to use one provider', 'It guarantees that the largest service has perfect organization', 'It prevents users on different platforms from communicating', 'It removes every cost of developing a new service'], 1, 'Cross-network communication reduces lock-in to a single installed base.'],
  ]),
  ...listeningGroup('talk-provenance', 'Listen to an Academic Talk', '퇴적지질학', 'C1', 'Sediment provenance research asks where grains in a basin originated. Mineral composition can link sediment to a source rock, while the age of resistant zircon crystals can identify distinct geological regions. Rivers mix material from many tributaries, however, and durable minerals are overrepresented because fragile grains break down during transport. A match between basin grains and one mountain range therefore shows compatibility, not exclusive origin. Researchers combine mineral chemistry, grain shape, transport pathways, and multiple source samples.', [
    ['Why can durable minerals distort a provenance reconstruction?', ['They survive transport better than less resistant source material', 'They form only after sediment reaches the final basin', 'Their ages cannot be measured by any method', 'They prevent rivers from mixing tributary sediment'], 2, 'Selective survival changes the observed mineral proportions.'],
    ['What does a geological age match establish?', ['A proposed source is possible but may not be unique', 'No other region contributed sediment to the basin', 'All grains followed an identical transport path', 'Fragile minerals were originally absent from the source'], 2, 'Compatibility supports a source without proving exclusivity.'],
  ]),
  ...listeningGroup('talk-reinforcement', 'Listen to an Academic Talk', '행동과학', 'B2', 'In operant conditioning, reinforcement increases the future probability of a behavior. Positive reinforcement adds a desirable consequence, while negative reinforcement removes an aversive condition. The word “negative” does not mean punishment. If fastening a seat belt stops an irritating alarm and seat-belt use increases, the removal of the sound is negative reinforcement. Punishment, by contrast, is intended to reduce behavior. Whether a consequence functions as reinforcement must be determined by the behavioral change, not by the researcher’s label.', [
    ['Why is stopping the alarm classified as negative reinforcement?', ['Removing an unpleasant stimulus makes the preceding action more likely', 'Adding a desirable sound reduces seat-belt use', 'The alarm punishes every person who fastens a belt', 'The consequence has no effect on later behavior'], 3, 'An aversive condition is removed following the target behavior.'],
    ['What determines whether a consequence was actually reinforcing?', ['An observed increase in the behavior it followed', 'Whether the researcher considers it morally positive', 'The physical removal of every environmental stimulus', 'A decrease that occurs before the consequence'], 3, 'Function is defined by the later behavioral effect.'],
  ]),
  ...listeningGroup('talk-spectra', 'Listen to an Academic Talk', '천체물리학', 'C1', 'When starlight is separated by wavelength, dark absorption lines appear where atoms in a cooler outer layer remove particular energies. Each element produces a characteristic pattern, allowing astronomers to infer composition. Line positions can also shift through the Doppler effect, revealing motion toward or away from the observer. Temperature, pressure, rotation, and magnetic fields change line shape, so a spectrum is not read from a simple lookup table. Models fit many lines simultaneously to distinguish overlapping influences.', [
    ['How can a spectrum identify an element in a star?', ['A distinctive set of missing wavelengths acts as a chemical signature', 'Every atom absorbs all wavelengths equally', 'Doppler motion creates new elements in the outer layer', 'Only visible brightness determines composition'], 0, 'Atomic energy levels yield recognizable absorption patterns.'],
    ['Why do astronomers model multiple lines together?', ['Several physical processes alter spectral features at the same time', 'A single line always measures every stellar property exactly', 'Pressure and magnetic fields have no spectral effects', 'Rotation prevents light from being separated by wavelength'], 2, 'Joint fitting helps separate confounded effects on line shape.'],
  ]),
  ...listeningGroup('talk-soundscape', 'Listen to an Academic Talk', '음향생태학', 'C1', 'Soundscape ecologists record entire acoustic environments rather than focusing on a single species. Dawn recordings may contain birds, insects, wind, traffic, and machinery. Automated indices summarize properties such as frequency diversity, but a high index is not automatically evidence of high biodiversity: rain or one loud insect can dominate the signal. Researchers validate indices against identified calls and field observations. Repeated recordings at matched times are especially important because animal activity and human noise follow daily and seasonal cycles.', [
    ['Why can an acoustic diversity index be biologically misleading?', ['Nonbiological noise or one dominant caller may inflate the summary', 'Every species occupies precisely the same sound frequency', 'Field identification always detects fewer organisms than recordings', 'Daily cycles eliminate variation among recording times'], 1, 'The numerical index can respond to sound sources unrelated to species richness.'],
    ['What design choice improves comparison across soundscapes?', ['Recording repeatedly at comparable times and validating acoustic summaries', 'Using one unverified index from a single rainy morning', 'Removing all quiet species from field observations', 'Comparing seasons without accounting for activity cycles'], 3, 'Temporal matching and ground truth reduce confounding.'],
  ]),
]

const sentenceData: Array<[string, string, string[], string]> = [
  ['Why did the association disappear?', 'Once the analysis', ['had been adjusted', 'for age', 'the two variables', 'were no longer', 'related'], 'f06-once-past-perfect-passive'],
  ['Could the archive release the letters?', 'Were the donor', ['to withdraw', 'the restriction', 'the letters', 'could be made', 'publicly available'], 'f06-inverted-conditional-passive'],
  ['What surprised the research team?', 'Rarely had they', ['observed such', 'a rapid response', 'under conditions', 'that appeared', 'so stable'], 'f06-negative-adverb-inversion'],
  ['Why compare several reconstructions?', 'It is by examining', ['where they diverge', 'that researchers', 'can identify', 'which assumptions', 'matter most'], 'f06-cleft-by-gerund'],
  ['Did the intervention reduce inequality?', 'Although average access', ['increased overall', 'the improvement', 'was concentrated', 'among residents', 'already well served'], 'f06-concession-passive'],
  ['Why is the estimate only provisional?', 'There remain', ['several observations', 'whose reliability', 'cannot be evaluated', 'until the instruments', 'are recalibrated'], 'f06-existential-relative-passive'],
  ['How could the protocol have been clearer?', 'The instructions should', ['have specified', 'not merely what', 'participants would do', 'but why each', 'step was necessary'], 'f06-modal-perfect-not-merely-but'],
  ['Can the same explanation fit both cases?', 'For that to be', ['plausible we would', 'have to assume', 'that two distinct', 'mechanisms produced', 'identical patterns'], 'f06-for-subject-infinitive'],
  ['Why did the committee reject the shortcut?', 'However convenient', ['it might have', 'seemed it would', 'have compromised', 'the independence', 'of the review'], 'f06-however-adjective-concession'],
  ['What does the replication establish?', 'What it strengthens', ['is the claim', 'that the phenomenon', 'can occur', 'not that it', 'always does'], 'f06-pseudo-cleft-not-that'],
]
const writing: BaseItem[] = sentenceData.map(([prompt, starter, fragments, grammarFocus], index) => { const item = base(`sentence-${index}`, 'writing', 'sentence-build', 'Build a Sentence', '고급 문장 구조', index < 2 ? 'B2' : 'C1', 75); const tiles = prepareSentenceTiles(fragments, item.id); return { ...item, instruction: '모든 단어와 구를 한 번씩 사용해 문맥에 맞는 문장을 완성하세요.', prompt, starter, words: tiles.choices, answer: tiles.answer, grammarFocus, explanation: `${starter} ${tiles.correct.join(' ')}` } })
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '현장 조사 일정', 'B2', 420), instruction: '문제와 영향, 가능한 대안을 구체적으로 제시하는 이메일을 작성하세요.', prompt: 'A required field survey was moved to a date when you are scheduled to present at another academic event. Write to the field-course instructor. Explain the conflict, show that you understand the survey requirement, and propose two realistic ways to complete equivalent work.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '연구 재현성', 'C1', 600), instruction: '다른 관점에 기여하면서 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Ito: Should journals require researchers to share data and analysis code whenever they publish an empirical study?', passage: 'Amara: Sharing lets other researchers detect errors and build efficiently on prior work.\nJonas: Universal requirements may expose participants or penalize scholars working with licensed and community-owned data.' })

const repeatSentences = ['Welcome to the digital fabrication safety briefing.', 'Keep loose clothing away from every moving component.', 'Confirm the material setting before starting the laser cutter.', 'Remain beside the machine throughout the entire cutting process.', 'If smoke accumulates, stop the job and close the protective lid.', 'Allow recently cut material to cool before moving it to storage.', 'Before you leave, remove small scraps, record equipment problems, and confirm that the ventilation cycle has finished.']
const interviewQuestions = ['Describe a situation in which sharing information helped a group solve a problem.', 'What kinds of personal or institutional information should not be shared openly?', 'How can researchers make their work transparent while respecting legitimate restrictions?', 'When does a demand for complete transparency become unrealistic or harmful?']
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '디지털 제작실 안전', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f06-repeat', scenarioId: 'f06-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '정보 공유와 투명성', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '같은 주제의 연속 질문에 이유와 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f06-interview', scenarioId: 'f06-interview', sequenceIndex })),
]

export const AUTHORED_FORM_06_ITEMS: BaseItem[] = [
  ...reading.slice(0, 11).map((item) => ({ ...item, module: 1 })), ...reading.slice(11).map((item) => ({ ...item, module: 2 })),
  ...responses.slice(0, 9).map((item) => ({ ...item, module: 1 })), ...conversations.slice(0, 5).map((item) => ({ ...item, module: 1 })), ...announcements.slice(0, 4).map((item) => ({ ...item, module: 1 })), ...talks.slice(0, 6).map((item) => ({ ...item, module: 1 })),
  ...responses.slice(9).map((item) => ({ ...item, module: 2 })), ...conversations.slice(5).map((item) => ({ ...item, module: 2 })), ...announcements.slice(4).map((item) => ({ ...item, module: 2 })), ...talks.slice(6).map((item) => ({ ...item, module: 2 })), ...writing, ...speaking,
]
export const AUTHORED_FORM_06_IDS = AUTHORED_FORM_06_ITEMS.map((item) => item.id)
