import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f08')

const reading: BaseItem[] = [
  cloze('cloze-glaciers', '빙하학', 'C1', 'A glacier flows because accumulated ice deforms under its own weight. Snow first comp___ into dense ice as air is squeezed from it. Gravity then dri___ the mass downhill, although movement may be only centimeters per day. Ice can def___ internally, and the glacier may also sli___ over water or sediment at its base. Surface cracks form where strain is too rapid for ice to bend. Scientists tra___ stakes and satellite features to meas___ velocity. A glacier can retreat even while ice still flows forward if melting exc___ the arrival of new ice at its end. Changes in length therefore integ___ snowfall, temperature, and dynamics. Researchers comb___ field data with models to proj___ future water supply and sea-level contribution.', 'acts|ves|orm|de|ck|ure|eeds|rate|ine|ect'),
  cloze('cloze-oral-tradition', '구전역사', 'C1', 'Oral traditions transmit accounts through performance rather than fixed documents. Repetition can pre___ important themes, but each telling also adapts to audience and circumstance. Variation does not nec___ indicate careless memory; it may reveal what a community currently emphasizes. Historians comp___ versions recorded at different times and exa___ who was permitted to speak. A late recording may contain old material alongside rec___ reinterpretation. Translation adds another layer because metaphors and social roles may not map dir___ between languages. Researchers document context, ack___ the interviewer’s influence, and avoid tre___ one version as a literal transcript of distant events. Used critically, oral evidence can exp___ experiences absent from official archives and chal___ narratives produced by institutions.', 'serve|essarily|are|mine|ent|ectly|nowledge|ating|ose|lenge'),
  cloze('cloze-catalysts', '화학반응론', 'B2', 'A catalyst speeds a chemical reaction without being consumed overall. It prov___ an alternative pathway with a lower activation-energy barrier. More molecules can then rea___ a reactive state at the same temperature. A catalyst does not cha___ the energy difference between reactants and products or move the equilibrium position. It accel___ both forward and reverse reactions. Catalytic surfaces may lose activity when impurities blo___ key sites. Temperature and pressure also aff___ performance. Engineers meas___ reaction rate and selectivity, since producing an unwanted compound quickly is not useful. They reg___ catalysts or replace them when activity declines. Understanding the mechanism helps researchers des___ more efficient materials and red___ energy use in industrial processes.', 'ides|ch|nge|erates|ck|ect|ure|enerate|ign|uce'),
  daily('daily-cryogenic', '저온 시설', 'B2', 'Cryogenic samples must travel in approved insulated carriers. The service elevator may be reserved for large dewars, but a reservation does not authorize unattended transport. Two trained users are required whenever the container exceeds the marked single-person weight.', ['What additional condition applies to a heavy dewar?', ['Two qualified people must accompany its transport', 'The carrier may be left alone inside the elevator', 'An elevator reservation replaces required training', 'The sample must be transferred into an open container'], 0, 'The weight threshold activates a two-person handling rule.']),
  daily('daily-rehearsal-recording', '공연 기록', 'B1', 'Cast members may review rehearsal video through the private course page. Downloading is disabled because performers have not consented to public distribution. Clips needed for a portfolio require separate written permission from every identifiable person in the selected segment.', ['What is needed before a student uses a rehearsal clip in a portfolio?', ['Written approval from each recognizable participant', 'Access to the private course page alone', 'Removal of the course page’s download button', 'Permission from only the student editing the clip'], 0, 'Private viewing consent does not cover external portfolio use.']),
  daily('daily-microloan', '학생 창업', 'B2', 'The student venture fund offers interest-free equipment loans up to two thousand dollars. Recipients submit receipts and return any unused balance. Labor, advertising, and recurring subscription fees are ineligible. A software license purchased once and retained by the team may qualify if it is itemized separately from cloud-service charges.', ['Which expense could qualify for the venture loan?', ['A one-time software license listed apart from subscriptions', 'Monthly online hosting throughout the next year', 'Wages paid to a student designer', 'An advertising campaign for product launch'], 0, 'A retained one-time tool may count as equipment, unlike recurring services.']),
  daily('daily-specimen-photo', '자연사 소장품', 'B2', 'Specimen photographs from the teaching database may be used in student presentations with attribution. Images intended for publication require a high-resolution request because the teaching copy lacks a color standard and may have been cropped. Publication permission is evaluated separately from delivery of the file.', ['Why should an author request a different image for publication?', ['The teaching image may be unsuitable for accurate reproduction', 'Student presentations prohibit any collection attribution', 'A high-resolution file automatically includes reuse permission', 'Published images should omit a color reference'], 0, 'The available copy may not preserve scale, color, or full framing.']),
  daily('daily-commuter-grant', '학생 복지', 'B2', 'Emergency commuter grants cover temporary transportation after an unexpected disruption, such as a stolen bicycle or canceled regional bus. They do not reimburse ordinary monthly travel. Applicants may request help before obtaining a police report, but final payment requires documentation of the disruption.', ['When may a student begin an application without complete documentation?', ['Immediately after an unexpected travel disruption', 'For routine commuting expenses every month', 'Only after the final grant has been paid', 'When no evidence of disruption will ever be available'], 0, 'Initial help can precede documentation, although payment cannot.']),
  daily('daily-ethnography', '연구 윤리', 'C1', 'Researchers observing a public festival may take general field notes under the approved protocol, but recording an identifiable private conversation requires consent. Moving to a public street does not make a deliberately overheard personal exchange public data. When uncertain, record the setting rather than the content and consult the project supervisor.', ['What should a researcher do after overhearing an identifiable personal conversation?', ['Avoid documenting its content until consent and protocol coverage are established', 'Treat it as unrestricted because the festival occurs outdoors', 'Publish the exchange while omitting only the street name', 'Assume general field-note approval covers audio recording'], 0, 'Location alone does not remove a reasonable privacy expectation.']),
  daily('daily-instrument-loan', '음악 장비', 'B1', 'Department instruments are due before the final examination period. Students performing in an approved recital during finals may request a one-week extension from the ensemble director. The extension is not automatic when a recital appears on the calendar.', ['Who can authorize a longer instrument loan?', ['The ensemble director after receiving a request', 'Any student listed in the recital calendar', 'The audience attending the final performance', 'The examination office without recital information'], 0, 'A qualifying recital permits a request, not automatic renewal.']),
  daily('daily-freezer-alarm', '실험실 관리', 'C1', 'Freezer alarms escalate first to the assigned laboratory and then to facilities if no one acknowledges them within ten minutes. Pressing “acknowledge” confirms receipt but does not silence later alerts if temperature remains outside range. The responder must add an action note before closing the event.', ['What does acknowledging an alarm accomplish?', ['It records that someone received the warning', 'It proves the freezer returned to its safe range', 'It permanently disables further temperature alerts', 'It closes the incident without an action note'], 0, 'Acknowledgment changes notification status, not physical conditions.']),
  daily('daily-accessibility-copy', '수업 자료', 'B2', 'Course readings sent for accessible-format conversion should be final versions. Replacing a reading after conversion restarts processing and may delay release. Instructors who must revise a file should identify exactly which pages changed so staff can determine whether partial replacement is possible.', ['How can an instructor reduce delay after revising a converted reading?', ['Specify the pages affected by the revision', 'Submit the entire file without explaining changes', 'Ask students to compare inaccessible versions themselves', 'Wait until after the reading is assigned to report it'], 0, 'Page-level information may allow targeted reprocessing.']),
  daily('daily-greenhouse-pests', '온실 생물안전', 'B2', 'Plants arriving from outside campus remain in the intake bay until pest screening is complete. Even plants showing no visible insects must not enter research rooms. Owners may water them in the bay using labeled cans but may not apply personal pesticides.', ['Which action is allowed before screening is complete?', ['Watering the plant with designated intake-bay equipment', 'Moving an apparently healthy plant into a research room', 'Treating the plant with a personally supplied pesticide', 'Skipping inspection when no insects are visible'], 0, 'Controlled care is permitted while movement and treatment are restricted.']),
  ...readingGroup('academic-iv', '계량경제학', 'C1', 'An instrumental variable is used when the treatment of interest is entangled with unmeasured causes of the outcome. A valid instrument changes treatment uptake but affects the outcome only through that treatment and shares no hidden causes with it. Distance to a training center might influence participation, for example, but it would fail as an instrument if distance also changes employment through access to other services. Even a valid instrument usually identifies an effect for people whose treatment decision responds to the instrument, not necessarily for everyone. The assumptions are partly substantive and cannot be established by a strong first-stage correlation alone.', [
    ['What is the exclusion requirement for an instrument?', ['It must influence the outcome only by changing the treatment', 'It must predict the outcome more strongly than treatment does', 'It must assign treatment identically to every participant', 'It must be measured after the final outcome'], 0, 'A separate causal route from instrument to outcome invalidates interpretation.'],
    ['Why might distance to a center be invalid in the example?', ['It could alter employment through services unrelated to the training', 'It necessarily has no relationship with participation', 'It makes all people accept the treatment', 'It is impossible to measure geographical distance'], 0, 'Other access channels would violate exclusion.'],
    ['Why is a large correlation between instrument and treatment insufficient?', ['Relevance does not prove absence of confounding or alternative outcome pathways', 'Strong prediction automatically lowers measurement accuracy', 'Every valid instrument must have a weak first stage', 'Correlation eliminates the need for domain knowledge'], 0, 'Strength addresses relevance, only one of several assumptions.'],
  ]),
  ...readingGroup('academic-magnetism', '동물행동학', 'C1', 'Migratory animals may use Earth’s magnetic field as a compass or a map. A compass provides direction, whereas a map supplies information about position. In laboratory experiments, researchers rotate the magnetic field around an animal while keeping visual cues constant. A corresponding change in orientation supports magnetic sensitivity, but artificial fields can produce stress or interfere with other senses. Evidence for a positional magnetic map requires more: animals exposed to field values characteristic of another location should behave as if displaced, even though they have not moved physically.', [
    ['What result would support use of a magnetic compass?', ['The animal changes direction when the experimental field is rotated', 'The animal ignores every alteration in field direction', 'A visual landmark moves while magnetism stays constant', 'The animal identifies its latitude from sunlight alone'], 0, 'Orientation tracking the manipulated field supports directional sensing.'],
    ['How does a test of a magnetic map differ?', ['It asks whether simulated location values elicit displacement-like behavior', 'It requires no manipulation of magnetic information', 'It measures only whether the animal experiences stress', 'It assumes direction and position are the same information'], 0, 'Map use concerns inferred position, not merely heading.'],
  ]),
  ...readingGroup('academic-marginalia', '독서사', 'C1', 'Notes written in a book’s margins can reveal how past readers engaged with a text. Underlining may identify passages considered important, while corrections, objections, or cross-references show active interpretation. Attribution is difficult when a volume had several owners, and apparently contemporary ink may have been added much later. Scholars compare handwriting with signed documents, examine ink and paper, and trace ownership records. Even when the writer is known, marginalia should not be treated as a transparent record of private belief: a note may rehearse an argument, prepare instruction, or respond to another reader.', [
    ['Why are ownership records useful when studying marginal notes?', ['They narrow the people and periods plausibly associated with the writing', 'They prove that only the first owner ever opened the book', 'They reveal the chemical formula of every ink', 'They convert unsigned comments into published arguments'], 0, 'Provenance constrains attribution without guaranteeing it.'],
    ['What does comparing handwriting with signed material accomplish?', ['It tests a proposed identification using an independent known sample', 'It establishes that all notes were written at publication', 'It determines the author’s private beliefs directly', 'It removes the need to examine ink or paper'], 0, 'Known writing provides comparative evidence for authorship.'],
    ['Why does the author caution against reading marginalia as straightforward belief?', ['Annotations can serve situational purposes other than personal endorsement', 'Readers never write opinions inside books', 'A named writer cannot respond to another person', 'Cross-references are always added by printers'], 0, 'The pragmatic purpose of a note may differ from confession.'],
  ]),
  ...readingGroup('academic-soil-carbon', '토양생지화학', 'C1', 'Soil carbon can persist because organic molecules become physically protected inside aggregates or bind to mineral surfaces. Persistence is not simply an intrinsic property of “recalcitrant” plant material. Microbes can decompose many compounds when conditions and access permit, while even simple molecules may remain if minerals shield them. Disturbance that breaks aggregates can expose previously protected carbon. Warming may accelerate microbial activity, but moisture and nutrient limitations modify the response. Models increasingly represent accessibility and mineral association rather than assigning every compound a fixed decay rate.', [
    ['What view of soil-carbon persistence does the passage challenge?', ['That molecular complexity alone determines how long carbon remains', 'That minerals can interact with organic molecules', 'That disturbance may alter physical protection', 'That microbes respond to temperature and moisture'], 0, 'Environmental access and stabilization matter alongside chemistry.'],
    ['Why can breaking soil aggregates increase decomposition?', ['It makes formerly isolated material reachable by microbes', 'It converts all minerals into new plant tissue', 'It lowers temperature below microbial tolerance', 'It guarantees permanent nutrient limitation'], 0, 'Physical disruption removes a barrier to access.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you verify that the reference samples arrived frozen?', ['I’ll check the receiving temperature log.', 'The references appear at the end of the article.', 'Frozen ground is common at high latitudes.', 'I sampled the lake before sunrise.'], 0, 'The receiving log contains the relevant evidence.'),
  response(1, 'Why was the guest lecture removed from the schedule?', ['The schedule is posted near the entrance.', 'The speaker’s flight was canceled.', 'I removed a duplicate slide.', 'Guest lectures are open to the public.'], 1, 'The travel disruption directly explains the change.'),
  response(2, 'Did facilities repair the leaking valve?', ['The valve controls water entering the chamber.', 'Facilities requests use a numbered ticket.', 'Yes, but we should monitor it during the next cycle.', 'I repaired the figure legend yesterday.'], 2, 'The reply confirms repair and proposes relevant follow-up.'),
  response(3, 'Would you be willing to summarize the committee’s concerns?', ['The summary table has four columns.', 'Committees usually meet once a month.', 'I was concerned about the missing sample.', 'Of course; I’ll send the three main points this afternoon.'], 3, 'The response accepts and specifies a useful deliverable.'),
  response(4, 'I assumed the travel award paid registration directly.', ['It reimburses you after you submit proof of payment.', 'The registration page closes on Monday.', 'Direct flights are more expensive this season.', 'I awarded the highest score to the second design.'], 0, 'The answer corrects the payment mechanism.'),
  response(5, 'Where can I borrow a tripod for the field camera?', ['The camera has an image-stabilization setting.', 'Equipment services keeps them behind the media desk.', 'I borrowed the article through another library.', 'The field site is two hours from campus.'], 1, 'The reply gives the appropriate pickup location.'),
  response(6, 'Shouldn’t we preregister the primary outcome?', ['Registration is required for conference entry.', 'The primary source was written in Latin.', 'Yes, before looking at the treatment results.', 'We registered the vehicle at the gate.'], 2, 'Preregistration must precede outcome-informed choices.'),
  response(7, 'The archive scan cuts off the handwritten date.', ['The archive stores several handwritten diaries.', 'The date appears in a different format elsewhere.', 'I scanned my access card at the door.', 'Request a new image that includes the page edge.'], 3, 'A reframed scan directly restores the missing evidence.'),
  response(8, 'Can the makerspace cut this unknown plastic?', ['Not until staff identify it and review the safety data.', 'The plastic sheet is three millimeters thick.', 'I made the prototype during last week’s class.', 'Unknown values are marked with a question mark.'], 0, 'Material identity is required for safe processing.'),
  response(9, 'Why hasn’t the abstract appeared in the program?', ['The program lists sessions by theme.', 'You uploaded it after the revision cutoff.', 'Abstract language should remain concise.', 'I appeared in a student performance.'], 1, 'A missed submission cutoff explains the omission.'),
  response(10, 'Could seasonal migration explain the lower count?', ['The migration exhibit opens in spring.', 'The count is written beside each species name.', 'Possibly, since this survey occurred six weeks later.', 'Lower shelves hold the heavier equipment.'], 2, 'Changed seasonal timing is a plausible alternative.'),
  response(11, 'I can’t reproduce the color scale in the paper.', ['The scale ranges from blue to yellow.', 'The paper was published three years ago.', 'Color reproduction differs among printers.', 'Check the supplementary code for the exact palette values.'], 3, 'The code is the best source for precise settings.'),
  response(12, 'Is the field station open during the semester break?', ['Yes, although overnight access requires advance notice.', 'The station measures rainfall every ten minutes.', 'The semester contains two shorter terms.', 'I opened the data file with a text editor.'], 0, 'The answer confirms access and supplies a condition.'),
  response(13, 'When should I expect feedback on the grant draft?', ['The draft has a two-page budget explanation.', 'By Thursday, unless the review panel runs late.', 'I expected the reaction to proceed faster.', 'Feedback can improve a proposal.'], 1, 'The response provides timing with a relevant caveat.'),
  response(14, 'Would matching on age remove all selection bias?', ['The sample’s average age is forty-two.', 'Matching can be done with several algorithms.', 'No, other causes of participation could remain unbalanced.', 'Selection menus appear at the top of the page.'], 2, 'Balancing one variable does not address every confounder.'),
  response(15, 'Who authorized releasing the embargoed photographs?', ['The photographs show the excavation trench.', 'Authorization was requested last week.', 'The embargo lasts until publication.', 'The project’s data steward approved the release.'], 3, 'The reply identifies the accountable role.'),
  response(16, 'The spreadsheet converted all specimen codes into dates.', ['Import the column as text and compare it with the original file.', 'The specimens were collected on several dates.', 'Spreadsheet formulas begin with an equals sign.', 'I converted the weights from grams to kilograms.'], 0, 'Text import and source comparison address destructive reformatting.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-embargo', 'Listen to a Conversation', '학위논문', 'C1', 'Student: My thesis includes a chapter under journal review. The publisher permits repository deposit, but my coauthor wants a two-year embargo. Librarian: The university normally allows one year unless you document a contractual or patent reason. Journal review alone does not require secrecy. Student: Could I restrict only that chapter? Librarian: The repository applies an embargo to the whole thesis, but you can request a justified extension from the graduate school.', [
    ['Why is a two-year embargo not automatically available?', ['It exceeds the ordinary period and needs a recognized justification', 'Repository deposit is forbidden for any submitted article', 'The coauthor alone controls all university policies', 'A thesis can never contain material under journal review'], 0, 'Longer restriction requires more than a preference tied to review.'],
    ['What limitation of the repository system is mentioned?', ['It cannot hide one chapter while releasing the rest', 'It cannot store a thesis containing multiple authors', 'It automatically grants every requested patent delay', 'It releases journal articles before submission'], 0, 'Embargo settings operate at the document level.'],
  ]),
  ...listeningGroup('conversation-lights', 'Listen to a Conversation', '강의실 시설', 'B1', 'Instructor: The lights in my classroom switch off whenever students work quietly. Technician: The occupancy sensor is probably timing out because it detects motion, not sound. I can extend the delay, but first I need to observe one class so I do not make it so sensitive that hallway movement triggers it. Instructor: Tomorrow’s session includes a silent quiz. Technician: That would be a useful test period.', [
    ['What likely causes the lights to turn off?', ['The sensor fails to register movement during quiet work', 'The hallway produces too much sound', 'The instructor manually shortens the timer', 'Students disconnect the classroom power'], 1, 'Still occupants may not refresh a motion-based timer.'],
    ['Why does the technician want to observe a class?', ['To balance reliable occupancy detection against false activation', 'To grade the students’ silent quiz', 'To replace motion sensing with a sound recorder', 'To measure only the hallway lighting level'], 1, 'Sensitivity must catch real use without reacting to adjacent traffic.'],
  ]),
  ...listeningGroup('conversation-isotopes', 'Listen to a Conversation', '고고학 분석', 'C1', 'Student: The isotope values from these teeth match the coastal region, so can I say the people migrated from the coast? Advisor: Say the enamel formed where coastal geology or diet produced those values. Similar signatures occur in another valley, and food could have been imported. Student: Would bone samples help? Advisor: They reflect later years and may show whether residence changed, but compare local plants and water before assigning geography.', [
    ['Why does the advisor reject a direct migration conclusion?', ['The chemical signature has more than one geographical or dietary source', 'Tooth enamel changes continuously throughout adult life', 'Imported food cannot affect isotopic composition', 'The coastal region has no measurable baseline values'], 2, 'Nonunique baselines and diet make location underdetermined.'],
    ['What could comparing enamel with bone indicate?', ['Whether exposure during later life differed from childhood exposure', 'The exact route traveled on a particular day', 'Whether every food item was produced locally', 'The age of the surrounding archaeological layer'], 2, 'The tissues record different periods of life.'],
  ]),
  ...listeningGroup('conversation-piano', 'Listen to a Conversation', '공연 준비', 'B2', 'Pianist: Several keys feel uneven after the instrument was moved. Can we tune it before tonight? Manager: Pitch tuning will not fix key resistance. The technician needs to regulate the action, and moving it again immediately afterward could undo the work. Pianist: The stage crew planned to reposition it after lunch. Manager: Then settle the final location first. The technician can regulate it at three and tune it once the action is stable.', [
    ['What distinction does the manager make?', ['Key resistance requires mechanical regulation rather than pitch adjustment', 'Moving a piano always improves its tuning', 'Stage crews are responsible for repairing the action', 'Uneven keys result only from room temperature'], 3, 'Touch and pitch are different maintenance problems.'],
    ['What sequence will avoid wasted work?', ['Place the piano finally, regulate its action, and then tune it', 'Tune it before every planned movement', 'Regulate it and immediately move it again', 'Cancel regulation and ask the pianist to adapt'], 3, 'Mechanical work should follow relocation, with tuning after stabilization.'],
  ]),
  ...listeningGroup('conversation-codes', 'Listen to a Conversation', '질적 연구', 'C1', 'Researcher: Our two coders agree on most interview passages, but they disagree whenever a participant is joking. Methodologist: A single agreement percentage may hide that pattern. Define how tone, context, and explicit laughter markers affect the code, then double-code a new sample. Researcher: Should we revise earlier cases? Methodologist: First keep the original decisions and audit trail. After the rule is finalized, recode all passages that could be affected, not just the known disagreements.', [
    ['What weakness is identified in the overall agreement rate?', ['It can conceal systematic disagreement within a particular category', 'It proves that every joking passage has been coded correctly', 'It cannot be calculated when there are two coders', 'It automatically revises ambiguous earlier cases'], 0, 'An aggregate metric can mask a concentrated reliability problem.'],
    ['Why retain the original decisions before recoding?', ['They document how and why the coding rule changed', 'They ensure that no affected passage is ever revised', 'They increase agreement without clarifying the rule', 'They remove the need to test a new sample'], 1, 'An audit trail makes methodological revision transparent.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-network', 'Listen to an Announcement', 'IT 유지보수', 'B2', 'The research network will be restarted Sunday between six and seven. Computers may remain powered on, but unsaved remote sessions will disconnect. Large data transfers begun before the restart will not resume automatically. Save scripts locally, end database transactions, and schedule transfers for after seven unless your system administrator has confirmed a recovery process.', [
    ['What should users do with large transfers?', ['Begin them after the maintenance window unless recovery is arranged', 'Assume every interrupted transfer resumes by itself', 'Turn off all computers before saving scripts', 'Keep database transactions open throughout restart'], 0, 'Transfers lack automatic recovery under the general setup.'],
    ['Which preparation protects ongoing computational work?', ['Saving local copies of scripts before remote disconnection', 'Starting a new transaction at six', 'Deleting all files from the local computer', 'Disconnecting the network administrator'], 0, 'Local copies survive loss of the remote session.'],
  ]),
  ...listeningGroup('announcement-market', 'Listen to an Announcement', '지역 행사', 'B1', 'Saturday’s campus market has moved from the lawn to the covered parking level because of rain. Vendors should unload at the west ramp before nine and then move vehicles to ordinary parking. The ramp becomes pedestrian-only when the market opens, so late arrivals must carry goods from the east entrance.', [
    ['What must vendors do after unloading before nine?', ['Relocate their vehicles away from the market ramp', 'Leave vehicles beside the stalls all day', 'Wait until pedestrians occupy the west ramp', 'Carry goods from the east entrance immediately'], 1, 'The unloading area must be cleared before opening.'],
    ['How will late vendors bring in their goods?', ['From the alternate entrance after parking elsewhere', 'By driving through the pedestrian-only west ramp', 'Across the rain-soaked lawn with no route', 'Through a reserved underground vehicle lane'], 1, 'Late vehicle access closes, leaving the east entry.'],
  ]),
  ...listeningGroup('announcement-donation', 'Listen to an Announcement', '도서관 수집', 'C1', 'The library is accepting faculty book donations through Friday. Staff will retain titles that fill collection gaps, offer duplicates to partner institutions, and recycle damaged copies. Donors may request a list of accepted titles but cannot direct where each rejected item goes. Tax valuations are not provided; donors needing one must consult an independent appraiser before transfer.', [
    ['What control do donors give up when transferring books?', ['The decision about the destination of items the library does not retain', 'The ability to request a list of accepted titles', 'Ownership of books before they are physically delivered', 'The option to consult an independent valuation expert'], 2, 'Disposition of unneeded material belongs to the library.'],
    ['What should a donor needing a tax value do?', ['Arrange an independent appraisal before donating', 'Ask library staff to estimate every title afterward', 'Use the list of accepted books as an official valuation', 'Require a partner institution to determine the amount'], 2, 'The library explicitly declines valuation service.'],
  ]),
  ...listeningGroup('announcement-dance', 'Listen to an Announcement', '공연 수업', 'B2', 'The dance studio floor was refinished yesterday and cannot support outdoor shoes until Monday. For weekend rehearsals, arrive wearing socks and change into cleaned dance shoes inside the lobby. Props with metal edges must remain off the floor unless the technical director approves protective padding.', [
    ['How should dancers enter for weekend rehearsal?', ['Change from socks into clean dance footwear indoors', 'Walk across the studio in outdoor shoes', 'Wear metal-edged props as footwear', 'Apply additional floor finish before dancing'], 3, 'The change procedure prevents outdoor contamination.'],
    ['When may a metal-edged prop be used?', ['After padding receives technical approval', 'Whenever the prop is carried from outside', 'Only while dancers wear ordinary shoes', 'Before anyone inspects its contact surface'], 3, 'Protective treatment requires director approval.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-signaling', 'Listen to an Academic Talk', '진화행동학', 'C1', 'A signal can remain reliable when producing it is more costly for low-quality individuals than for high-quality ones. A large ornament might be energetically manageable for a healthy animal but prohibitively expensive for a weak one. Reliability does not require waste for its own sake; it requires that cheating be difficult or unprofitable. Some signals are instead constrained by physical linkage, such as a call whose frequency depends on body size. Researchers test signaling theories by measuring receiver response, production costs, and whether signal variation actually predicts the claimed quality.', [
    ['Why can differential cost maintain signal honesty?', ['Low-quality individuals cannot profitably imitate the same display', 'Every signal imposes identical costs on all senders', 'Receivers ignore variation in the ornament', 'Healthy individuals are unable to produce costly traits'], 0, 'Unequal feasibility prevents cheap deception.'],
    ['What evidence is needed beyond measuring an ornament?', ['A demonstrated relationship among the trait, underlying quality, cost, and receiver behavior', 'Proof that the ornament is visually noticeable to humans', 'A guarantee that every signal is deliberately wasteful', 'Removal of all physical constraints on production'], 0, 'A signaling account must connect production and interpretation.'],
  ]),
  ...listeningGroup('talk-kinetics', 'Listen to an Academic Talk', '효소학', 'C1', 'At low substrate concentration, adding substrate often increases an enzyme reaction rate sharply because many active sites are unoccupied. At high concentration, the enzyme approaches saturation and rate levels off near a maximum. The substrate concentration at half the maximum rate is commonly used to characterize apparent affinity under a specified model. Cells are more complicated than a purified assay: products accumulate, inhibitors compete, and enzyme abundance changes. Parameter estimates therefore depend on experimental conditions and should not be treated as permanent universal constants.', [
    ['Why does the rate plateau at high substrate concentration?', ['Most enzyme active sites are already occupied', 'Substrate begins removing enzymes from the assay', 'Maximum rate requires zero enzyme molecules', 'Every product turns back into substrate immediately'], 1, 'Limited enzyme availability constrains further rate increase.'],
    ['Why might parameters from a purified assay fail inside a cell?', ['Additional interactions and changing concentrations violate the simplified setting', 'Cellular enzymes never bind substrate', 'Affinity is independent of any model assumptions', 'Products cannot accumulate in biological systems'], 1, 'The cellular environment adds mechanisms absent from the assay.'],
  ]),
  ...listeningGroup('talk-volcanic-aerosol', 'Listen to an Academic Talk', '대기과학', 'C1', 'A major volcanic eruption can inject sulfur dioxide into the stratosphere, where it forms sulfate aerosols. These particles reflect some incoming sunlight and can temporarily cool Earth’s surface. The effect differs from ash falling near the volcano; coarse ash leaves the atmosphere relatively quickly, whereas fine stratospheric aerosols can persist. Cooling is uneven across regions and seasons, and aerosols also alter stratospheric chemistry. A short cooling episode does not reverse long-term greenhouse warming, because the particles eventually settle while carbon dioxide remains much longer.', [
    ['Why can sulfate aerosols influence climate longer than coarse ash?', ['Their small stratospheric particles remain aloft for a longer period', 'They permanently remove all atmospheric carbon dioxide', 'Coarse ash reflects sunlight for centuries', 'They form only after reaching the ground'], 2, 'Altitude and particle persistence extend their radiative effect.'],
    ['What distinction does the lecturer make about time scale?', ['Temporary volcanic forcing does not cancel persistent greenhouse forcing', 'Every eruption produces permanent global cooling', 'Carbon dioxide settles faster than volcanic ash', 'Seasonal variation disappears after an eruption'], 2, 'The two influences have very different atmospheric lifetimes.'],
  ]),
  ...listeningGroup('talk-episodic', 'Listen to an Academic Talk', '기억과학', 'C1', 'Episodic memory involves recollecting an event with aspects of its context, such as where and when it occurred. Familiarity can produce a sense that something was encountered before without recovering that context. Laboratory recognition tests sometimes ask participants to distinguish “remember” from “know” judgments, but verbal reports are imperfect. Confidence and recollection can overlap, and people interpret the labels differently. Researchers combine subjective reports with source-memory questions and response-time patterns rather than assuming a single measure cleanly isolates each process.', [
    ['How does familiarity differ from episodic recollection?', ['It can signal prior encounter without retrieving event context', 'It always provides exact time and location', 'It occurs only for completely new material', 'It prevents any confident recognition response'], 3, 'A feeling of knowing need not include contextual recovery.'],
    ['Why are several memory measures combined?', ['No single report perfectly separates overlapping internal processes', 'Response time directly reveals every remembered detail', 'Participants interpret all labels identically', 'Source questions eliminate subjective confidence'], 3, 'Converging imperfect indicators support a stronger inference.'],
  ]),
  ...listeningGroup('talk-acoustics', 'Listen to an Academic Talk', '건축음향학', 'B2', 'A concert hall needs some reflected sound because early reflections increase loudness and help listeners feel enveloped. Too much late reverberation, however, blurs rapid notes and speech. Designers shape walls and ceilings to distribute reflections and add absorptive material where needed. An empty hall behaves differently from a full one because audiences absorb sound. Acoustic testing therefore uses both computer models and measurements made under conditions approximating an actual performance.', [
    ['Why are reflections not eliminated completely?', ['Early reflected energy can strengthen and enrich perceived sound', 'All reflected sound makes speech unintelligible', 'Absorptive material produces musical notes itself', 'An empty hall contains more audience members'], 0, 'Useful early energy differs from excessive late reverberation.'],
    ['Why test conditions resembling a performance?', ['Occupied seats change absorption and therefore the hall response', 'Computer models cannot represent any wall shape', 'Audience members increase every echo equally', 'Late reverberation occurs only in empty buildings'], 2, 'Real occupancy alters the acoustic environment.'],
  ]),
  ...listeningGroup('talk-niche', 'Listen to an Academic Talk', '생태학', 'C1', 'Resource partitioning can allow related species to coexist by using food, space, or time differently. Two lizards may hunt similar insects but occupy different heights in vegetation. The pattern is consistent with reduced competition, yet present-day separation does not prove that competition caused it. Species may differ because of physiology or evolutionary history. Experiments that alter competitor presence, combined with measurements of resource availability, can test whether niches expand when a rival is removed.', [
    ['Why is observational niche separation causally ambiguous?', ['Several mechanisms besides current competition can generate the pattern', 'Coexisting species must use identical resources', 'Physiology cannot influence habitat use', 'Evolutionary history is observed only in experiments'], 1, 'The present distribution has multiple possible causes.'],
    ['What result would support a competition-based explanation?', ['A species broadens resource use after a rival is experimentally removed', 'Both species remain unmeasured in identical conditions', 'Resource availability is assumed constant without observation', 'One species changes height before any manipulation'], 3, 'Release from competition predicts niche expansion.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the proposed instrument rejected?', 'Had distance affected', ['employment only', 'through training', 'it might have', 'served as', 'a valid instrument'], 'f08-inverted-third-conditional-only-through'],
  ['Did the excavation confirm the interpretation?', 'What was uncovered', ['was compatible with', 'the hypothesis', 'but by no means', 'sufficient to', 'establish it'], 'f08-pseudo-cleft-by-no-means'],
  ['Why did the estimate become less precise?', 'The smaller the', ['effective sample became', 'the wider', 'the uncertainty interval', 'was expected', 'to grow'], 'f08-correlative-comparative'],
  ['Could a different model fit the observations?', 'Not until alternative', ['mechanisms have been', 'specified can', 'we determine', 'whether the fit', 'is distinctive'], 'f08-not-until-inversion-perfect-passive'],
  ['What made the annotation historically valuable?', 'Written as it', ['was by', 'an identifiable reader', 'it linked', 'the text to', 'a particular debate'], 'f08-concessive-participial-as'],
  ['Why retain the original resolution?', 'Doing so prevents', ['later processing', 'from obscuring', 'features that', 'future methods', 'might detect'], 'f08-gerund-prevent-from-relative'],
  ['Did all sites respond alike?', 'Whereas the northern', ['plots recovered quickly', 'those farther south', 'continued to decline', 'despite receiving', 'the same treatment'], 'f08-whereas-despite-gerund'],
  ['How strong is the evidence for inheritance?', 'For the claim', ['to be credible', 'shared environments', 'would need', 'to have been', 'carefully excluded'], 'f08-for-subject-infinitive-modal-perfect'],
  ['Why did the authors emphasize uncertainty?', 'Lest the average', ['be mistaken', 'for a universal', 'response they reported', 'the full distribution', 'of outcomes'], 'f08-lest-passive'],
  ['Can a null result settle the debate?', 'At most it', ['shows that', 'an effect of', 'the predicted magnitude', 'was not observed', 'here'], 'f08-at-most-passive'],
]
const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '데이터 저장소', 'B2', 420), instruction: '문제와 영향, 필요한 조치를 분명하게 전달하는 이메일을 작성하세요.', prompt: 'You discovered that the public version of your team’s dataset includes an outdated variable description that could cause other researchers to misinterpret missing values. Write to the repository manager. Identify the record, explain the risk, and request both an immediate correction notice and a reviewed replacement file.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '과학적 측정', 'C1', 600), instruction: '다른 견해를 평가하면서 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Adeyemi: When an important concept cannot be measured directly, how should researchers decide whether an indirect indicator is good enough?', passage: 'Mina: Multiple imperfect indicators can be persuasive when they converge on the same conclusion.\nTheo: Apparent convergence may be misleading if every indicator shares the same hidden bias.' })

const repeatSentences = ['Welcome to the archaeological materials laboratory.', 'Leave coats and personal bags in the entrance lockers.', 'Handle each fragment above its padded tray.', 'Keep the catalog label beside the object at all times.', 'Use the scale bar in every photograph intended for analysis.', 'If two fragments appear to join, ask staff before fitting them together.', 'At the end of the session, verify every catalog number, return the tools, and document any new surface damage.']
const interviewQuestions = ['Describe an indirect sign you have used to judge something that could not be observed directly.', 'What makes an indirect measurement convincing?', 'How should people respond when several indicators disagree?', 'Can a precise measurement still lead to a misleading conclusion?']
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '고고학 자료실 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f08-repeat', scenarioId: 'f08-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '간접 측정과 판단', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f08-interview', scenarioId: 'f08-interview', sequenceIndex })),
]

export const AUTHORED_FORM_08_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_08_IDS = AUTHORED_FORM_08_ITEMS.map((item) => item.id)
