import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f20')

const reading: BaseItem[] = [
  cloze('cloze-circadian', '시간생물학', 'C1', 'Circadian clocks generate near-daily rhythms even without external time cues. In mammals, a central clock in the brain syn___ peripheral clocks using light information from the eyes. Molecular feedback loops cause clock proteins to accum___ and inhibit their own production, then degrade so the cycle can restart. Environmental signals such as light, meals, and activity entr___ the clock to exactly twenty-four hours. Sleep pressure inter___ with circadian signals. A sudden time-zone shift separates internal rhythms from the new schedule. Different tissues readj___ at different rates, contributing to jet lag. Light timing matters: exposure in the evening may delay the clock, whereas morning light may adv___ it. Individual response depends on prior schedule and intrinsic period. Researchers mea___ melatonin, body temperature, sleep, and gene expression rather than inf___ phase from one bedtime. Repeated night work can produce chronic misalignment even if a worker feels adapted. Effective interventions cons___ intensity, wavelength, timing, and the need to preserve sufficient sleep, while av___ claims that one schedule fits everyone.', 'chronizes|ulate|ain|acts|ust|ance|sure|erring|ider|oiding'),
  cloze('cloze-provenance', '퇴적학', 'C1', 'Sediment provenance analysis asks where grains came from and how they reached a deposit. Wind and water trans___ and sort grains before deposition. Mineral composition, grain shape, isotopes, and detrital crystal ages can fin___ source regions. No tracer is perfectly unique because different rocks may share properties and transport can sort grains. Durable minerals may be overrep___ after weaker ones weather away. Rivers can rec___ older deposits, mixing signals from several episodes. Landscape storage can del___ their arrival. Researchers sample potential sources and model mixtures rather than matching one grain to one map unit. A change in provenance may refl___ tectonic uplift, river capture, climate-driven erosion, or altered sediment storage. Dating individual zircon crystals records their crystallization, not necessarily the time of deposition. The youngest reliable grains can constr___ a maximum depositional age, but absence of young grains may result from limited sampling. Analysts comb___ field stratigraphy with multiple tracers, quan___ uncertainty, and test whether apparent shifts exceed analytical and sampling var___.', 'port|gerprint|esented|ycle|ay|ect|ain|ine|tify|iation'),
  cloze('cloze-printmaking', '판화사', 'B2', 'In relief printmaking, raised areas receive ink while recessed areas remain unprinted. Artists carve a block, roll ink across its surface, and pr___ paper against it. The image prints in reverse, so lettering must be planned accordingly. A block can prod___ many impressions, but wear, recutting, and inking create differences among states. In intaglio methods, ink sits inside inc___ lines and transfers under high pressure. Plate marks can help iden___ the process. Paper, ink, dampening, and press force aff___ the result. A later impression is not automatically less valuable; it may document intentional revision or a distinct edition. Scholars exam___ line character, watermark, plate condition, and publication history. Modern restrikes from an old plate can res___ the design without reproducing its original context. Conservators limit light and handle margins carefully because repeated display and mounting can wea___ fibers. Catalogs dist___ impressions, states, and reproductions to rec___ how an image circulated.', 'ess|uce|ised|tify|ect|ine|emble|ken|inguish|onstruct'),
  daily('daily-solar-roof', '태양광 연구시설', 'B2', 'Roof-array access is suspended whenever lightning is detected within ten kilometers. The all-clear requires thirty minutes without a new strike. A clear sky above the building does not override the automated radius alert.', ['When may researchers return to the roof?', ['After the required strike-free interval within the monitored radius', 'As soon as clouds directly above the building disappear', 'While the automated lightning alert remains active', 'Ten minutes after the first detected strike'], 0, 'The timed regional all-clear controls access.']),
  daily('daily-special-diet', '연구 참여', 'B2', 'Participants in the metabolism study receive standardized meals. Allergies can be accommodated if reported during screening, but personal food preferences cannot be added after enrollment because changing one menu would alter the experimental comparison.', ['Why are late menu preferences not accommodated?', ['Unplanned dietary changes would modify the controlled intervention', 'Allergies are considered personal preferences after screening', 'Standardized meals contain no measurable nutrients', 'Participants prepare every study meal independently'], 0, 'Menu consistency is part of the design.']),
  daily('daily-negative-scan', '사진 아카이브', 'B2', 'Film negatives are scanned emulsion side down using a clean carrier. Dust should be removed with approved air, not a cloth that can scratch the surface. A digital dust filter may create a derivative access image, but the unfiltered archival master must also be saved.', ['Which file should be preserved as the archival master?', ['The scan before digital dust-removal processing', 'Only the filtered image used for convenient access', 'A photograph of the empty scanner carrier', 'The file created after scratches are retouched manually'], 0, 'The master retains the captured evidence without content-altering cleanup.']),
  daily('daily-chemical-fridge', '시약 보관', 'B2', 'The explosion-safe refrigerator is for flammable laboratory chemicals, not food or biological samples. Unopened solvent bottles still require an inventory label. Containers without a responsible group will be moved to controlled holding until ownership is established.', ['What happens to an unlabeled solvent container?', ['It enters controlled holding while responsibility is investigated', 'It remains in active storage because the bottle is unopened', 'It is transferred to the biological-sample refrigerator', 'It becomes exempt from the chemical inventory'], 0, 'Unknown ownership triggers secure investigation.']),
  daily('daily-accessible-pdf', '강의 접근성', 'B2', 'A PDF that visually resembles a reading may still be inaccessible if its pages are only images. Before posting, instructors should check text selection, reading order, headings, and alternative text. Optical character recognition helps but requires review for equations and unusual names.', ['Why must OCR output be reviewed?', ['Specialized notation and names may be recognized incorrectly', 'Text selection prevents a screen reader from working', 'Headings are automatically removed from every accessible file', 'Image-only pages already contain perfect reading order'], 0, 'Automated recognition is error-prone on complex content.']),
  daily('daily-sequence-embargo', '유전체 데이터', 'C1', 'Human sequence files remain under controlled access even after direct identifiers are removed because genetic data can be inherently identifying. Summary allele frequencies may be public if the approved release test shows low reidentification risk. Project membership alone does not authorize downloading individual-level genomes.', ['Why do de-identified genomes remain restricted?', ['The sequence itself can be linked back to an individual or relatives', 'Removing names destroys every scientific use of genetic data', 'Summary frequencies always reveal each participant’s genome', 'Project membership transfers participant consent automatically'], 0, 'Genetic uniqueness persists without names.']),
  daily('daily-stage-load', '공연 안전', 'B1', 'The stage loading limit applies to equipment and people together. A piano placement diagram assumes no riser beside it. Adding a riser requires the technical director to recalculate the load before rehearsal, even if the audience area is empty.', ['What triggers a new load calculation?', ['Adding equipment not included in the approved placement diagram', 'Removing audience members from the hall', 'Beginning rehearsal with the original piano position', 'Using the stage without any people or equipment'], 0, 'The structural calculation depends on the actual configuration.']),
  daily('daily-calibration-gas', '대기 측정', 'B2', 'Calibration gas cylinders have certified concentration and expiration dates. A cylinder past expiration may be used for training but not to validate field measurements. Mark training-only status prominently so its readings cannot enter the quality-controlled dataset.', ['How may an expired calibration cylinder be used?', ['For practice that is kept outside validated measurement records', 'To certify the accuracy of new field observations', 'As an unmarked substitute in the quality-control workflow', 'To extend the manufacturer’s concentration certificate'], 0, 'Expired reference material cannot support validation.']),
  daily('daily-archive-seat', '도서관 예약', 'B1', 'Special-collections seats are held for fifteen minutes after the appointment time. Researchers delayed by campus transport should call before the hold expires. Staff can preserve the seat but may return requested boxes to storage if no revised arrival time is provided.', ['What information helps staff keep materials ready?', ['A revised arrival time communicated before the hold ends', 'A general complaint about campus transportation afterward', 'A request to remove the appointment from the calendar', 'Silence until the researcher reaches the reading room'], 0, 'Advance notice supports both seat and material planning.']),
  daily('daily-reagent-lot', '실험 재현성', 'C1', 'A new antibody lot must be bridged against the current lot on shared positive and negative controls. Similar packaging does not establish equivalent performance. If the old lot is exhausted, retain its final control images and report the limitation rather than presenting an untested lot change as continuous.', ['What is the purpose of a lot-bridging test?', ['To determine whether the replacement performs comparably on common controls', 'To prove that identical packaging guarantees identical binding', 'To eliminate the need for reporting an exhausted old lot', 'To make positive and negative controls produce the same signal'], 0, 'Common controls reveal discontinuity between lots.']),
  ...readingGroup('academic-its', '시계열 인과추론', 'C1', 'Interrupted time-series analysis examines whether an outcome’s level or trend changes after an intervention. It uses the preintervention trajectory to estimate what might have happened without the change. A long series helps characterize baseline trend and seasonality, but the design remains vulnerable to another event occurring at the same time. Autocorrelation affects uncertainty because adjacent observations are related. A gradual policy rollout may require a ramp rather than an immediate step. Researchers predefine the interruption date, inspect functional form, model serial dependence, and use comparison series when possible. A striking before-and-after difference based on two points is not a credible interrupted time series.', [
    ['What is the central counterfactual in this design?', ['The outcome trajectory expected after the interruption had the intervention not occurred', 'The exact outcome of every individual before enrollment', 'A series in which adjacent observations are independent by definition', 'The policy effect under an unrelated implementation date'], 0, 'The preperiod supports a projected no-intervention path.'],
    ['Why can a simultaneous external event threaten inference?', ['Its effect cannot be separated from the intervention’s temporal break', 'It guarantees the baseline trend remains linear', 'Autocorrelation occurs only when no external event exists', 'A comparison series becomes unnecessary'], 0, 'Coincident causes are time-confounded.'],
    ['Why might a ramp function be appropriate?', ['Exposure or impact may increase progressively rather than switch instantly', 'Seasonality disappears during gradual implementation', 'A ramp forces all observations to have equal values', 'Policy rollout always ends before the interruption date'], 0, 'The effect shape should reflect implementation.'],
  ]),
  ...readingGroup('academic-hydraulics', '식물생리학', 'C1', 'Water moves through plants along gradients in water potential, from soil through roots and xylem to the atmosphere. Transpiration creates tension that pulls a continuous water column upward. Under drought or freezing, air can enter conduits and create embolisms that block transport. Narrow conduits may resist embolism but carry less water, producing tradeoffs between hydraulic safety and efficiency. Stomata close to reduce loss, yet closure also limits carbon dioxide uptake and cooling. Species differ in rooting depth, conduit anatomy, storage, and repair, so one leaf-water measurement cannot fully describe whole-plant drought strategy.', [
    ['What tradeoff can conduit width create?', ['Structures that transport water efficiently may be more vulnerable to hydraulic failure', 'Narrow conduits always carry more water under tension', 'Embolism increases carbon dioxide uptake through stomata', 'Wide conduits eliminate all effects of freezing'], 0, 'Capacity and safety can oppose one another.'],
    ['Why does stomatal closure have a cost?', ['It conserves water while restricting photosynthesis and evaporative cooling', 'It raises xylem flow without changing gas exchange', 'It repairs every embolized conduit immediately', 'It makes atmospheric water potential equal to soil'], 0, 'Water conservation limits other leaf functions.'],
  ]),
  ...readingGroup('academic-census', '고대사회사', 'C1', 'Ancient censuses and tax registers rarely counted populations in the same way as modern national censuses. They might list taxable households, adult men, landholders, or people liable for labor, omitting others. Administrative categories could change between documents, and households might conceal members or migrate to avoid obligations. A total therefore measures the recording institution as well as the population. Historians reconstruct broader demography by comparing registers with settlement area, grain supply, burial evidence, military lists, and later records. Multipliers that convert households to persons require assumptions about family structure and omission.', [
    ['Why can a register total differ substantially from population size?', ['Eligibility and avoidance determine who appears in the administrative count', 'Ancient officials always counted every resident twice', 'Settlement area contains no relationship to habitation', 'Household records directly list all births and deaths'], 0, 'The documented unit is often a fiscal category.'],
    ['What problem arises when comparing two registers?', ['Their categories and institutional purposes may not remain constant', 'Later documents necessarily use modern census definitions', 'Migration can affect only the earlier register', 'Tax obligations make household size exactly known'], 0, 'Apparent change may partly reflect classification change.'],
    ['Why are household-to-person multipliers uncertain?', ['Average household composition and undercounting must be inferred', 'Every recorded household contains an identical number of adults', 'Burial evidence directly labels each taxable family', 'Grain supply eliminates demographic assumptions'], 0, 'Conversion requires quantities not given by the register.'],
  ]),
  ...readingGroup('academic-quantum-dots', '나노재료', 'C1', 'Quantum dots are semiconductor nanocrystals whose electronic behavior depends on size. Confinement makes smaller dots emit shorter-wavelength light than larger dots of the same material. Their narrow, tunable emission is useful in displays and imaging. Performance also depends on surface chemistry: defects can trap charge and reduce brightness, so shells or ligands passivate the surface. Heavy-metal composition, photodegradation, aggregation, and blinking constrain applications. A spectrum measured in dilute solution may not predict behavior in a dense film where dots interact and energy transfers between them.', [
    ['Why does dot size change emitted color?', ['Quantum confinement alters the allowed electronic energy spacing', 'Larger particles always contain a different semiconductor element', 'Surface ligands determine wavelength independently of the core', 'Aggregation eliminates every electronic energy level'], 0, 'Size controls the confinement energy.'],
    ['Why might a dense film perform differently from a solution?', ['Close particles can exchange energy and aggregate in ways isolated dots do not', 'Dilution permanently removes all surface defects', 'A film prevents light from interacting with nanocrystals', 'Solution spectra directly include every solid-state interaction'], 0, 'Interparticle effects emerge at high concentration.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the new antibody lot pass the bridge test?', ['Yes, its controls stayed within the predefined acceptance range.', 'The antibody binds a membrane protein.', 'The lot number appears on each vial.', 'I crossed the pedestrian bridge after class.'], 0, 'The response confirms controlled comparability.'),
  response(1, 'Why was the roof survey canceled despite clear skies?', ['The survey measures panel reflectance.', 'Lightning remained within the exclusion radius.', 'I canceled a duplicate calendar invitation.', 'Clear skies improve satellite imagery.'], 1, 'Regional lightning status overrides local appearance.'),
  response(2, 'Could another event explain the time-series break?', ['The series contains monthly observations.', 'The intervention began at the fiscal-year boundary.', 'Yes, if it occurred concurrently and affected the same outcome.', 'I broke the sample into smaller pieces.'], 2, 'Time-coincident causes are confounded.'),
  response(3, 'I thought the archive seat guaranteed my boxes all day.', ['The archive has twelve reading-room seats.', 'Boxes are retrieved from climate-controlled storage.', 'I guaranteed the estimate under stronger assumptions.', 'The seat is held briefly; materials need an updated arrival time.'], 3, 'The reply clarifies the conditional hold.'),
  response(4, 'May we section the quantum-dot film for microscopy?', ['Only after documenting the intact optical spectrum and sample plan.', 'The film emits green light under ultraviolet illumination.', 'Microscopy resolves particles at high magnification.', 'I sectioned the literature review by method.'], 0, 'Destructive preparation should follow baseline documentation.'),
  response(5, 'Where is the original census-category crosswalk?', ['The census lists households by district.', 'In the versioned documentation beside the transcription.', 'Crosswalks map categories across record systems.', 'I crossed the street near the archive entrance.'], 1, 'The answer locates stable interpretive documentation.'),
  response(6, 'Shouldn’t we model monthly seasonality explicitly?', ['The policy started during the summer term.', 'Monthly outcomes show a repeating annual pattern.', 'Yes, or the intervention term may absorb a normal seasonal change.', 'I modeled the sculpture from archival photographs.'], 2, 'Seasonal structure can mimic interruption effects.'),
  response(7, 'The vial cap opened during refrigerated transport.', ['The vial contains a certified calibration solution.', 'Transport lasted less than two hours.', 'I opened the appendix in another window.', 'Quarantine it and document temperature and seal failure before testing.'], 3, 'Compromised integrity requires controlled assessment.'),
  response(8, 'Is this tax register a complete population list?', ['No, it records only households liable for the stated levy.', 'The register was written on reused parchment.', 'Population history combines several evidence types.', 'I listed the sources in chronological order.'], 0, 'The answer identifies the fiscal scope.'),
  response(9, 'Why did the leaf temperature rise after stomata closed?', ['The leaf was attached to a mature branch.', 'Reduced evaporation removed part of its cooling.', 'I closed the greenhouse window before sunset.', 'Temperature was measured with an infrared camera.'], 1, 'Evaporative cooling declined.'),
  response(10, 'Can we infer river capture from the zircon ages?', ['The zircons came from sandstone grains.', 'River capture changes drainage connections.', 'Only with stratigraphy and sources that rule out sediment recycling.', 'I captured the screen before updating the software.'], 2, 'Age spectra alone permit alternative pathways.'),
  response(11, 'I cannot select any text in the assigned PDF.', ['The PDF contains several scanned equations.', 'Text selection helps copying short quotations.', 'I selected the random sample with replacement.', 'It may be image-only; request OCR and accessibility review.'], 3, 'The symptom suggests an inaccessible scan.'),
  response(12, 'Has the calibration-gas cylinder been marked training-only?', ['Yes, a red label blocks it from the validated workflow.', 'The cylinder contains a methane mixture.', 'Training sessions occur every second Friday.', 'I marked the key finding in the abstract.'], 0, 'The answer confirms clear exclusion from validated use.'),
  response(13, 'When should we measure the post-policy slope change?', ['The slope summarizes change per month.', 'After defining whether implementation was immediate or gradual.', 'I measured the crystal under polarized light.', 'Policy outcomes appear on the dashboard.'], 1, 'Effect form should follow implementation timing.'),
  response(14, 'Would a shell improve the quantum dot’s brightness?', ['The shell uses a wider-bandgap semiconductor.', 'Brightness declines after prolonged exposure.', 'It might, by passivating surface traps that promote nonradiative loss.', 'I improved the sentence by shortening it.'], 2, 'Surface passivation can reduce trap-mediated loss.'),
  response(15, 'Who approved downloading individual-level genomes?', ['The genomes were sequenced at high coverage.', 'Controlled access requires an institutional account.', 'Download events appear in the audit log.', 'The data-access committee authorized the named project members.'], 3, 'A dedicated committee grants scoped access.'),
  response(16, 'This print appears darker than the museum’s impression.', ['Compare ink, paper, state, and exposure before assuming it is a later pull.', 'The block depicts a crowded city market.', 'Museum lighting is limited for works on paper.', 'I printed the regression table in landscape orientation.'], 0, 'Several production and aging factors affect tone.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-interruption', 'Listen to a Conversation', '의료 정책 평가', 'C1', 'Student: Emergency visits fell sharply after the clinic opened, so I used the month before and month after as an interrupted time series. Advisor: Two points cannot establish a prior trajectory or seasonality. Student: We have four years of monthly records elsewhere. Advisor: Then use the full series, check autocorrelation, and identify any simultaneous insurance or coding changes.', [
    ['Why is the two-point comparison inadequate?', ['It cannot distinguish intervention change from trend, seasonality, or random fluctuation', 'A monthly outcome can never be studied over four years', 'Autocorrelation affects only cross-sectional samples', 'Opening a clinic guarantees an immediate permanent effect'], 0, 'Interrupted series inference needs a modeled trajectory.'],
    ['What additional threat does the advisor mention?', ['Concurrent administrative changes that could alter the same outcome', 'Too many months before the clinic opening', 'Absence of any patient visits after treatment', 'The impossibility of identifying a policy date'], 0, 'Other changes at the interruption can confound attribution.'],
  ]),
  ...listeningGroup('conversation-lighting', 'Listen to a Conversation', '판화 전시', 'B2', 'Curator: The darker impressions need more light than the pale ones. Conservator: Increasing each case separately would create uneven exposure and visitor adaptation problems. Curator: Could we rotate them? Conservator: Yes. Use one safe level, rotate the most light-sensitive sheets, and provide a magnified digital view for fine detail.', [
    ['Why does the conservator reject individually brighter cases?', ['It would increase exposure and disrupt consistent visual adaptation', 'Dark impressions contain no visible detail under any light', 'Rotation is forbidden for works on paper', 'Digital magnification requires stronger gallery lamps'], 0, 'Object safety and viewing continuity argue against case-by-case intensity.'],
    ['What solution preserves access to fine detail?', ['A digital enlargement alongside controlled physical illumination', 'Permanent high illumination of the darkest original', 'Removal of all pale impressions from the exhibition', 'Reprinting the historic blocks on modern paper'], 0, 'Digital mediation supplements a safe display.'],
  ]),
  ...listeningGroup('conversation-xylem', 'Listen to a Conversation', '식물 수리 실험', 'C1', 'Researcher: Conductivity recovered overnight, so I concluded the embolisms repaired. Physiologist: Did the stem rehydrate under positive pressure after cutting? Researcher: Yes. Physiologist: Then the procedure itself may have refilled conduits. Measure intact plants or use a method that avoids cutting-induced artifacts before claiming biological repair.', [
    ['What alternative explanation is proposed for recovery?', ['Sample preparation may have forced water back into blocked conduits', 'Embolisms cannot reduce hydraulic conductivity', 'Intact plants always grow under positive pressure', 'Overnight measurement eliminates cutting artifacts'], 0, 'The method can manufacture the apparent repair.'],
    ['What evidence would strengthen the biological claim?', ['Recovery observed without the potentially refilling preparation step', 'A larger pressure applied to every cut stem', 'Conductivity measured only after complete rehydration', 'Removal of all intact plants from the experiment'], 0, 'An artifact-resistant method tests the mechanism.'],
  ]),
  ...listeningGroup('conversation-household', 'Listen to a Conversation', '역사 인구 추정', 'C1', 'Historian: I multiplied every registered household by five to estimate population. Demographer: Does the register include widows, servants, and tax-exempt households? Historian: It is unclear. Demographer: Then five is only one assumption. Build a range from comparative household evidence and vary the omission rate rather than presenting one precise total.', [
    ['Why is multiplying by five questionable?', ['Household composition and coverage of the register are uncertain', 'Ancient households could never contain five people', 'Tax records list every servant separately by definition', 'Comparative evidence produces one exact multiplier'], 0, 'Both unit size and undercount require assumptions.'],
    ['What reporting strategy is recommended?', ['Present a range under alternative plausible household and omission assumptions', 'Select the largest population value as definitive', 'Exclude all tax-exempt people from demographic interpretation', 'Use precision to conceal uncertainty in the source'], 0, 'Scenario ranges honestly represent incomplete knowledge.'],
  ]),
  ...listeningGroup('conversation-film', 'Listen to a Conversation', '나노소재 측정', 'B2', 'Student: The quantum dots are bright in solution but dim after I cast the film. Technician: Did the spectrum shift? Student: It broadened and moved to longer wavelength. Technician: That suggests aggregation or energy transfer. Try a lower concentration and inspect film morphology before changing the core material.', [
    ['What does the spectral change suggest?', ['Interactions among closely packed particles alter emission', 'The core semiconductor vanished during casting', 'Solution measurements always use longer wavelengths', 'Lower concentration causes unavoidable aggregation'], 0, 'Broad red-shifted emission is consistent with coupling.'],
    ['Why inspect morphology?', ['It can reveal clustering linked to the optical decline', 'It directly measures the bandgap of an isolated dot', 'It guarantees the film contains no ligands', 'It replaces all concentration experiments'], 0, 'Physical organization can explain changed performance.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-darkroom', 'Listen to an Announcement', '필름 보존실', 'B2', 'The preservation scanner is offline until Thursday, but the reference scanner remains available for access copies. Do not use the reference scanner for nitrate negatives; their handling procedure requires the preservation room and fire-rated staging cabinet. Existing nitrate appointments will be rescheduled automatically.', [
    ['Which material cannot use the available scanner?', ['Nitrate film requiring the specialized preservation setup', 'Ordinary reference copies requested for access', 'Digitized images already stored on the server', 'Modern photographic prints cleared for handling'], 0, 'Hazardous film needs the dedicated room.'],
    ['What happens to existing restricted appointments?', ['They receive automatic rescheduling rather than manual rebooking', 'They move immediately to the reference scanner', 'They proceed without the fire-rated cabinet', 'They are converted into access-copy requests'], 0, 'The facility handles the schedule change.'],
  ]),
  ...listeningGroup('announcement-orientation', 'Listen to an Announcement', '대학원 오리엔테이션', 'B1', 'Graduate orientation begins in Hall A at nine. The campus tour leaves at ten thirty from the north lobby. Students who skip the tour may attend the library account session instead, but both activities end at noon and neither is repeated this week.', [
    ['What alternative is offered during the tour?', ['A session for setting up library access', 'A second orientation lecture in Hall A', 'An afternoon repetition of both activities', 'An independent campus tour after noon'], 0, 'The two simultaneous options serve different needs.'],
    ['What scheduling limitation is stated?', ['The optional activities will not be offered again this week', 'Orientation starts only after the tour returns', 'The library session continues through the afternoon', 'Students may attend both options in sequence'], 0, 'They overlap and lack a near-term repeat.'],
  ]),
  ...listeningGroup('announcement-sequencing', 'Listen to an Announcement', '유전체 코어', 'C1', 'The sequencing core has detected index hopping in the current reagent lot. Runs continue, but low-frequency variant projects must use unique dual indexes and include a negative library. Standard expression projects may keep existing indexes if cross-sample contamination below the posted threshold would not change interpretation. Update the run form before plate submission.', [
    ['Which project faces the stricter indexing requirement?', ['A study interpreting rare sequence variants', 'A standard expression analysis insensitive to minimal mixing', 'A completed run with no plate submission', 'Any project lacking biological samples'], 0, 'Low-frequency signals are especially vulnerable to index misassignment.'],
    ['What must be changed before submission?', ['The run documentation reflecting index and control choices', 'The physical dimensions of every sequencing plate', 'The posted contamination threshold itself', 'The interpretation of a finished expression study'], 0, 'The core needs an accurate run plan.'],
  ]),
  ...listeningGroup('announcement-garden', 'Listen to an Announcement', '식물원 행사', 'B2', 'Saturday’s pollinator walk has moved from morning to three because the meadow path is flooded. The indoor specimen demonstration remains at eleven. Morning registrants keep places on the afternoon walk unless they cancel by noon, when waiting-list visitors are admitted.', [
    ['Which activity still occurs at eleven?', ['The indoor demonstration using preserved specimens', 'The relocated outdoor pollinator walk', 'Waiting-list admission to the meadow path', 'Cancellation of every morning registration'], 0, 'Only the outdoor activity changes time.'],
    ['When can waiting-list visitors receive walk places?', ['At noon after unused registrations are released', 'Before the indoor demonstration begins', 'Only after the three o’clock walk ends', 'Immediately when the path floods'], 0, 'The cancellation cutoff governs reassignment.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-methane', 'Listen to an Academic Talk', '습지생지화학', 'C1', 'Wetlands can emit methane because waterlogged soil limits oxygen and favors microbes that produce methane during decomposition. Other microbes consume part of that methane before it reaches the atmosphere, especially where oxygen enters near roots or the surface. Plants can also transport gas through internal air spaces, bypassing oxidizing layers. Emissions therefore depend on water level, temperature, organic substrates, vegetation, and transport pathway. Draining a wetland may reduce methane yet increase carbon dioxide from faster aerobic decomposition, so climate evaluation must consider multiple gases and timescales.', [
    ['How can vegetation both limit and increase methane release?', ['Roots introduce oxygen for consumption while plant tissues can provide a direct gas pathway', 'Plants eliminate every anaerobic microbe from wet soil', 'Internal air spaces convert methane entirely into carbon dioxide', 'Vegetation prevents organic matter from entering wetlands'], 0, 'Biological structure supports opposing mechanisms.'],
    ['Why is drainage not automatically a climate benefit?', ['Lower methane may be offset by greater carbon dioxide from exposed organic matter', 'Aerobic decomposition stops when soil dries', 'Methane is the only greenhouse gas influenced by wetlands', 'Water level has no effect on microbial activity'], 0, 'Gas tradeoffs and persistence determine net forcing.'],
  ]),
  ...listeningGroup('talk-grid', 'Listen to an Academic Talk', '전력시스템', 'C1', 'Variable wind and solar generation must be balanced with demand on multiple timescales. Geographic diversity smooths some fluctuations, while storage, flexible demand, transmission, and dispatchable generation provide complementary services. Energy capacity describes how long storage can supply power; power capacity describes how rapidly it can charge or discharge. A battery sized for brief frequency regulation may not cover a multiday low-wind period. Reliability studies model weather-correlated generation and outages rather than averaging annual production alone.', [
    ['Why are energy and power capacity distinguished?', ['Duration and instantaneous delivery impose different storage requirements', 'A high discharge rate guarantees unlimited stored energy', 'Annual solar output determines every short-term fluctuation', 'Transmission substitutes for all storage timescales'], 0, 'Storage must meet both rate and quantity needs.'],
    ['Why is annual average generation insufficient for reliability?', ['Shortfalls can coincide across regions and with equipment outages', 'Annual totals reveal the timing of every low-wind event', 'Flexible demand increases whenever supply disappears', 'Weather correlation matters only for fossil generation'], 0, 'System adequacy depends on temporal coincidence.'],
  ]),
  ...listeningGroup('talk-prediction', 'Listen to an Academic Talk', '계산신경과학', 'C1', 'Predictive-processing theories propose that the brain uses hierarchical models to anticipate sensory input and updates them through prediction error. This framework can explain why expectations influence perception, but broad formulations risk fitting almost any result after the fact. A useful model must specify what is predicted, at which level, how precision weights errors, and what behavior follows. Neural responses labeled prediction error may also reflect attention, novelty, or adaptation. Experiments manipulate expectation independently from stimulus frequency and compare quantitative alternatives.', [
    ['What makes a predictive-processing claim scientifically informative?', ['It generates specified, testable consequences rather than a post hoc verbal fit', 'It labels every neural response as prediction error', 'It excludes hierarchy and uncertainty from the model', 'It assumes expectations never alter perception'], 0, 'Precision and falsifiability distinguish explanation from description.'],
    ['Why manipulate expectation separately from frequency?', ['Common stimuli can be less novel even without being more expected in context', 'Frequency directly measures hierarchical model depth', 'Novelty and attention cannot affect neural responses', 'Prediction errors occur only for rare stimuli'], 0, 'The design separates competing sources of response change.'],
  ]),
  ...listeningGroup('talk-timber', 'Listen to an Academic Talk', '건축공학사', 'B2', 'Traditional timber frames use joints that transfer load without relying entirely on metal fasteners. Wood shrinks mainly across the grain as it dries, so joinery can loosen or tighten differently by direction. Craftspeople selected seasoned timber, oriented members, and allowed some movement. Modern rigid reinforcement may strengthen one point while shifting stress into adjacent historic wood. Engineers evaluate the whole load path and moisture behavior rather than maximizing local stiffness alone.', [
    ['Why does grain direction matter in timber joints?', ['Dimensional change is anisotropic as wood gains or loses moisture', 'Wood shrinks equally along every axis', 'Metal fasteners remove moisture from adjacent members', 'Seasoned timber cannot change dimension'], 0, 'Directional movement affects fit and force.'],
    ['What risk accompanies a very rigid local repair?', ['Stress may concentrate in weaker original material nearby', 'It guarantees that the entire frame shares load evenly', 'It makes moisture behavior irrelevant', 'It restores every joint to its original geometry'], 0, 'Local strength can redistribute failure elsewhere.'],
  ]),
  ...listeningGroup('talk-evidentiality', 'Listen to an Academic Talk', '언어유형론', 'C1', 'Evidential systems grammatically mark information source, such as direct observation, inference, or report. An evidential does not always indicate how certain a speaker is. A reported marker may be used for highly trusted information, while a direct marker can accompany doubt about interpretation. Meanings also shift with tense, person, genre, and interaction. Researchers analyze natural discourse and controlled judgments because translating every evidential as an English phrase like “apparently” can blur source and confidence.', [
    ['Why should evidentiality not be equated with certainty?', ['Source marking and confidence can vary independently', 'Direct observation always guarantees correct interpretation', 'Reported information is necessarily considered false', 'Every language uses the same evidential categories'], 0, 'Evidence source and epistemic commitment are distinct dimensions.'],
    ['Why can simple translation be misleading?', ['One adverb may collapse grammatical contrasts and contextual uses', 'English contains a separate exact word for every evidential', 'Natural discourse removes source information', 'Controlled judgments cannot examine grammar'], 0, 'Cross-language categories rarely map one-to-one.'],
  ]),
  ...listeningGroup('talk-marine-reserve', 'Listen to an Academic Talk', '보전생태학', 'C1', 'Marine reserves prohibit or limit extraction within boundaries. Fish biomass may increase inside, and larvae or mobile adults can contribute beyond the boundary. But a reserve can displace fishing effort into adjacent areas, and apparent recovery may reflect favorable habitat chosen for protection. Strong evaluation uses before-and-after data, comparable unprotected sites, enforcement measures, and movement information. Ecological success does not automatically imply equitable social outcomes if costs fall on communities with few alternatives.', [
    ['Why can comparison with outside areas be biased?', ['Protected sites may have had better habitat even before designation', 'Fish cannot move across reserve boundaries', 'Enforcement makes habitat quality unmeasurable', 'All fishing effort disappears after reserve creation'], 0, 'Site selection can confound treatment effects.'],
    ['Why assess social outcomes separately?', ['Ecological gains and distribution of livelihood costs are different criteria', 'Higher fish biomass guarantees equal household benefit', 'Communities never change fishing location', 'Larval export measures income directly'], 0, 'Conservation performance has biological and distributive dimensions.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the time-series claim weak?', 'Had only one preintervention month been observed', ['no credible', 'baseline trend', 'could have been', 'projected'], 'f20-had-only-counterfactual-passive'],
  ['What did the xylem image reveal?', 'Visible within several wide conduits were', ['air-filled spaces', 'that interrupted', 'the otherwise continuous', 'water columns'], 'f20-adjective-locative-inversion'],
  ['Why was the census estimate revised?', 'Much as historians valued the register', ['its categories', 'excluded groups', 'central to', 'the population question'], 'f20-much-as-transitive-concessive'],
  ['How did the policy effect appear?', 'Only gradually did the outcome depart', ['from the trajectory', 'that the preperiod', 'would otherwise', 'have predicted'], 'f20-only-adverb-gradual-inversion'],
  ['What limited the quantum-dot film?', 'The closer together the nanocrystals were packed', ['the more readily', 'energy migrated', 'toward', 'nonradiative traps'], 'f20-double-comparative-passive-pack'],
  ['Why was the apparent repair questioned?', 'The stems having been rehydrated under pressure', ['their recovered', 'conductivity might reflect', 'the preparation', 'rather than biology'], 'f20-absolute-perfect-passive'],
  ['What condition governed genome access?', 'No researcher was to download individual sequences unless', ['the committee', 'had approved', 'both the purpose', 'and security plan'], 'f20-was-to-unless-past-perfect'],
  ['Why compare an untreated coastline?', 'Were natural erosion cycles not represented', ['storm-driven recovery', 'could be mistaken', 'for an effect', 'of restoration'], 'f20-were-passive-counterfactual'],
  ['How certain was the provenance shift?', 'So strongly did recycling blur the mineral signal', ['that no single tracer', 'could distinguish', 'new erosion', 'from older sediment'], 'f20-so-adverb-inversion-could'],
  ['Why preserve the unfiltered scan?', 'However visually distracting the dust may be', ['removing it digitally', 'would create', 'a derivative', 'rather than a master'], 'f20-however-adjective-may-be'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '항체 로트 변경', 'C1', 420), instruction: '연속성 문제, 현재 증거, 검증과 보고 절차를 구체적으로 작성하세요.', prompt: 'You discover that a laboratory began using a new antibody lot after the previous lot was exhausted, but no bridging test was performed and the current report combines both periods. Write to the project supervisor. Explain the comparability problem, request control-based evaluation, and propose how results and limitations should be documented.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '해양 보호구역', 'C1', 600), instruction: '생태적 효과, 평가 설계, 지역사회 형평성을 함께 고려해 논지를 발전시키세요.', prompt: 'Professor Kamau: Should governments expand no-take marine reserves even when nearby fishing communities oppose the restrictions?', passage: 'Isabel: Protected breeding populations can restore ecosystems and eventually support fisheries outside reserve boundaries.\nBen: Restrictions can shift costs onto small communities while larger commercial fleets move elsewhere.' })

const repeatSentences = ['Welcome to the controlled-access genomic data room.', 'Store personal devices in the locker before signing into the workstation.', 'Verify that the approved project code matches the requested dataset.', 'Use only the analysis environment provided inside the secure network.', 'Do not copy individual records into notes or external software.', 'Review every export for aggregate disclosure risk before submission.', 'At the end of the session, delete temporary files, close the remote workspace, and sign the access log so staff can verify that no restricted data remain.']
const interviewQuestions = ['Describe a place where protecting nature limits how local people use resources.', 'What long-term environmental benefit might the restriction provide?', 'Which group is most likely to bear the immediate cost?', 'How could authorities share benefits or decision-making more fairly with that group?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '유전체 보안 분석실', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f20-repeat', scenarioId: 'f20-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '보전과 지역사회', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f20-interview', scenarioId: 'f20-interview', sequenceIndex })),
]

export const AUTHORED_FORM_20_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_20_IDS = AUTHORED_FORM_20_ITEMS.map((item) => item.id)
