import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { Question, SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f07')

const reading: BaseItem[] = [
  cloze('cloze-peatlands', '습지생태학', 'C1', 'Peatlands form where waterlogged conditions slow the decay of plant material. Partly decomposed matter acc___ over centuries and creates thick organic soil. Saturation limits oxygen and restr___ microbial activity. Although peatlands cover a modest area, they sto___ enormous quantities of carbon. Drainage for farming low___ the water table and expo___ peat to air, accelerating decomposition and rel___ greenhouse gases. Restoration often blocks drainage channels and rai___ water levels. Recovery is slow because vegetation and soil structure have been alt___. Managers therefore mon___ both hydrology and gas exchange rather than ass___ that a rewetted site immediately functions like an intact wetland.', 'umulates|icts|re|ers|ses|easing|ses|ered|itor|uming'),
  cloze('cloze-circadian', '시간생물학', 'B2', 'Human physiology follows a roughly twenty-four-hour circadian rhythm. An internal clock is syn___ mainly by light reaching specialized cells in the eye. Morning light can shi___ the cycle earlier, while evening light may delay it. The clock influ___ sleep, hormones, temperature, and digestion. Traveling across time zones creates mis___ between internal timing and the local day. Adjustment usu___ takes several days and is not determined by fatigue alone. Carefully timed light expo___ can help, whereas bright screens at the wrong hour may int___ with adaptation. Individual responses dif___ with age and routine. Researchers mea___ biological timing under controlled conditions, because self-reported sleep does not ful___ reveal the underlying clock.', 'chronized|ft|ences|alignment|ally|sure|erfere|fer|sure|ly'),
  cloze('cloze-immunity', '면역학', 'C1', 'Vaccination prepares the immune system to respond without requiring the full disease. An antigen stim___ lymphocytes capable of recognizing a pathogen. Some cells prod___ antibodies, while others become long-lived memory cells. On later exposure, these cells exp___ rapidly and mount a faster response. Protection may dec___ as antibody levels fall or pathogens evolve. A booster can rein___ memory, but the ideal schedule dep___ on disease biology and population risk. Vaccine effectiveness is est___ by comparing outcomes while accounting for differences in exposure and health. No intervention is perfect, yet reduced sev___ can remain important even when infection is not entirely prev___. Public recommendations are upd___ as evidence accumulates.', 'ulates|uce|and|line|force|ends|imated|erity|ented|ated'),
  daily('daily-telescope', '천문 관측', 'B2', 'Students may reserve the portable telescope overnight only after completing outdoor-equipment checkout. Cloudy weather does not automatically cancel a reservation, but borrowers who choose not to collect the telescope must release it by 4 p.m. so another project can use the mount indoors.', ['What should a borrower do after deciding not to collect the telescope?', ['Cancel by the stated afternoon deadline', 'Keep the reservation because the sky is cloudy', 'Take only the mount without completing checkout', 'Wait until the following morning to notify staff'], 0, 'Releasing the booking by four makes the equipment available to others.']),
  daily('daily-fume-hood', '화학 안전', 'B2', 'A green display on the fume hood confirms airflow at that moment; it does not certify that the sash position is safe for every procedure. Keep the sash below the marked operating height and stop work if the alarm sounds. Silencing the alarm without correcting airflow is prohibited.', ['What does the green display fail to guarantee?', ['That the hood is being used with an appropriate sash position', 'That any airflow is currently moving through the hood', 'That an alarm will sound when conditions change', 'That the marked height is visible to laboratory users'], 0, 'Current airflow and correct operating configuration are distinct conditions.']),
  daily('daily-proof', '출판 지원', 'B2', 'The university press sends authors one consolidated proof. Corrections should address typesetting errors, not introduce new arguments. Changes that alter pagination may incur a fee and require editorial approval. If several coauthors respond separately, the press will use only the file submitted by the designated corresponding author.', ['How should coauthors deliver their proof corrections?', ['Combine them in the corresponding author’s submission', 'Send competing files and let the press merge them', 'Add new analysis without requesting editorial approval', 'Ignore typesetting mistakes that affect pagination'], 0, 'The production process accepts one consolidated authorized file.']),
  daily('daily-locker', '체육 시설', 'B1', 'Day-use lockers open with a temporary code and must be emptied before the recreation center closes. Items remaining overnight go to lost property. Semester rental lockers have numbered keys and are not affected by the daily clearing procedure.', ['Which locker may contain belongings overnight?', ['A semester rental locker with its own key', 'Any day-use locker protected by a code', 'A temporary locker reported to lost property', 'Every locker emptied before closing'], 0, 'Only the longer-term rental is exempt from nightly clearing.']),
  daily('daily-translation-booth', '통역 시설', 'B2', 'The interpretation booth may be booked for live events or recording practice. Live events receive priority when requests overlap. A practice reservation is confirmed provisionally and may be moved until forty-eight hours before its start, after which it cannot be displaced by a later request.', ['When does a practice booking become protected from a later live-event request?', ['During the final forty-eight hours before the booking', 'Immediately after a provisional confirmation', 'Only once the practice recording is complete', 'Whenever both users submit at the same time'], 0, 'Priority reallocation ends at the stated cutoff.']),
  daily('daily-dataset', '데이터 저장소', 'B2', 'Depositing a dataset assigns a persistent identifier only after metadata review. Uploading files creates a private draft link, not a citable public record. Authors facing a manuscript deadline may request accelerated review, but they should not place the temporary draft address in the published article.', ['What is required before the dataset has a stable citation?', ['Completion of repository metadata review', 'Creation of any private upload link', 'Publication of the draft address in an article', 'Deletion of the underlying research files'], 0, 'The persistent identifier follows review rather than initial upload.']),
  daily('daily-allergy', '행사 운영', 'B2', 'Reception dishes display ingredient cards, but the kitchen cannot guarantee that shared preparation areas are free of trace allergens. Guests with severe allergies may request a sealed meal prepared by an external provider if they submit the dietary form five business days in advance.', ['What option is available to a guest needing strict allergen separation?', ['Order the externally prepared meal before the advance deadline', 'Rely solely on cards beside food from shared equipment', 'Ask the reception staff to reseal an ordinary dish', 'Submit the dietary form after arriving at the event'], 0, 'The sealed alternative requires advance notice.']),
  daily('daily-robotics', '로봇 실습실', 'C1', 'Autonomous robots may operate in the marked arena only when a trained observer holds the emergency stop. A successful simulation does not waive this requirement. During low-speed manual calibration, the observer and operator may be the same person if no other robot is powered inside the arena.', ['When may one person both operate and supervise a robot?', ['During isolated low-speed manual calibration', 'Whenever an autonomous program passed simulation', 'While several powered robots share the arena', 'During any high-speed autonomous experiment'], 0, 'The exception is narrow: manual, low speed, and no other active robot.']),
  daily('daily-choral-score', '음악 도서관', 'B1', 'Marked choral scores may be borrowed for rehearsal, but pencil annotations must remain visible until the conductor confirms that the production has ended. Performers should not erase another singer’s markings; library staff will clean the scores after final return.', ['Who is responsible for removing rehearsal annotations?', ['Library staff after the production’s materials are returned', 'Each performer before the final concert', 'The conductor at the start of rehearsal', 'Any singer borrowing a previously marked score'], 0, 'Cleaning occurs centrally after use has ended.']),
  daily('daily-field-permit', '생태 조사', 'C1', 'A reserve permit authorizes observation from established paths. Capturing insects, collecting feathers, or placing sensors requires an additional methods endorsement even when no protected species is targeted. Applications must list the exact equipment and removal date for every installed device.', ['Which activity requires approval beyond the ordinary observation permit?', ['Leaving a temporary acoustic sensor beside the path', 'Watching birds without leaving an established route', 'Taking handwritten notes about visible vegetation', 'Photographing the landscape from a public platform'], 0, 'Installing equipment is explicitly covered by the additional endorsement.']),
  ...readingGroup('academic-rdd', '계량사회과학', 'C1', 'A regression discontinuity design exploits a rule that assigns treatment when a score crosses a threshold. Students just above and just below a scholarship cutoff, for instance, may be similar except for receiving the award. A sharp change in later outcomes at the cutoff can estimate a local causal effect if people cannot precisely manipulate their score and other determinants vary smoothly. The result applies most directly to cases near the boundary, not necessarily to students with very high or low scores. Researchers inspect whether background characteristics also jump at the threshold and test alternative bandwidths around it.', [
    ['What creates the comparison used by this design?', ['A treatment rule that changes abruptly at a numerical boundary', 'Random assignment of every observation in the population', 'A requirement that outcome levels remain constant over time', 'Removal of all participants located near the threshold'], 0, 'Assignment discontinuity supplies locally comparable treated and untreated cases.'],
    ['Why would precise score manipulation threaten the design?', ['People on opposite sides might differ systematically in unobserved motivation or resources', 'The treatment rule would become easier to describe mathematically', 'Every outcome would vary smoothly at the threshold', 'The estimate would automatically generalize to distant scores'], 0, 'Sorting undermines the near-random comparison around the boundary.'],
    ['What does testing different bandwidths evaluate?', ['Whether the estimated jump depends excessively on the chosen neighborhood', 'Whether scholarships are awarded far above the cutoff', 'Whether all students have identical background characteristics', 'Whether the score is measured after the outcome'], 0, 'Robustness across reasonable local windows strengthens confidence.'],
  ]),
  ...readingGroup('academic-pollination', '군집생태학', 'B2', 'A pollination network links plant species to the animals that visit their flowers. Some interactions are specialized, while generalist pollinators visit many plants. A generalist can stabilize pollination when one specialist declines, but visit counts alone do not measure effectiveness: an animal may remove nectar without carrying useful pollen. Flowering times also determine which species can interact. Ecologists combine observation with pollen loads and seed production to distinguish frequent contact from successful pollination.', [
    ['Why are visitation records insufficient by themselves?', ['A frequent visitor may transfer little compatible pollen', 'Every observed animal is equally effective at fertilization', 'Flowering time has no influence on possible interactions', 'Seed production always occurs before an animal visit'], 0, 'Contact frequency and functional pollination are not equivalent.'],
    ['How might a generalist contribute to network stability?', ['It can maintain connections when a more specialized partner disappears', 'It prevents all flowering periods from changing', 'It visits exactly one plant and excludes competitors', 'It guarantees that every visit produces the same number of seeds'], 0, 'Multiple potential partners can provide redundancy.'],
  ]),
  ...readingGroup('academic-lidar', '원격탐사 고고학', 'C1', 'Airborne lidar sends laser pulses toward the ground and measures their return time. Some pulses pass through gaps in vegetation, allowing analysts to model terrain beneath a forest canopy. Subtle embankments or canals may become visible in the model even when they are difficult to see on foot. Lidar does not identify an archaeological feature merely by revealing a geometric shape. Modern drainage, logging tracks, and natural landforms can look similar. Researchers compare historical maps, excavate selected locations, and examine how features relate spatially before assigning an age or function.', [
    ['What advantage does lidar offer in forested landscapes?', ['It can estimate hidden ground form from pulses that reach through canopy gaps', 'It directly determines the date of every buried structure', 'It removes vegetation physically before field survey', 'It distinguishes natural and human shapes without interpretation'], 0, 'Ground-return measurements reveal topography obscured from ordinary view.'],
    ['Why is a geometric feature not conclusive archaeological evidence?', ['Several recent or natural processes can produce a similar form', 'Laser return time cannot be converted into elevation', 'Historical maps always omit human modifications', 'Excavation is possible only before lidar collection'], 0, 'Shape alone is underdetermined and needs contextual corroboration.'],
    ['Which next step would most directly test a proposed ancient canal?', ['Excavate a targeted segment and compare its sediments with mapped context', 'Increase screen contrast without examining outside evidence', 'Assume every linear depression carried water in antiquity', 'Discard locations that overlap any historical document'], 0, 'Ground truth and sediment evidence can evaluate age and function.'],
  ]),
  ...readingGroup('academic-meter', '음악인지', 'C1', 'Listeners often infer a musical beat even when not every beat is marked by a sound. They organize events into a metrical hierarchy, expecting some positions to be stronger than others. Syncopation creates tension by placing emphasis where the hierarchy predicts weakness or by omitting an expected strong event. These expectations reflect both timing cues and learned musical style. A rhythm that sounds strongly syncopated to one listener may be organized differently by someone familiar with another tradition. Researchers therefore avoid treating one culturally specific meter as a universal perceptual template.', [
    ['How can a silent position contribute to perceived rhythm?', ['The listener predicts a beat there from the surrounding temporal pattern', 'Silence prevents any metrical expectation from forming', 'Only sounded events can occupy strong positions', 'The missing sound changes every weak position into noise'], 0, 'An inferred pulse need not have an acoustic onset at every location.'],
    ['What broader caution follows from cross-cultural differences?', ['Models of meter should distinguish general timing processes from learned conventions', 'All listeners necessarily impose the same hierarchy', 'Musical exposure eliminates sensitivity to temporal cues', 'Syncopation can be measured without defining an expected pattern'], 0, 'Experience shapes the organization against which displacement is heard.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Could you check whether the seminar room has a document camera?', ['I’ll look at the equipment inventory now.', 'The seminar begins with a guest lecture.', 'That document has three color photographs.', 'The camera records at sixty frames per second.'], 0, 'The reply accepts the request and names an appropriate source.'),
  response(1, 'Why did my reimbursement total change?', ['The total appears in the final spreadsheet row.', 'One meal exceeded the daily allowance.', 'I changed trains at the central station.', 'Reimbursement forms require a signature.'], 1, 'The allowance limit directly explains the adjustment.'),
  response(2, 'Have the seedlings been moved out of quarantine?', ['The seedlings grew two centimeters this week.', 'Quarantine prevents accidental pest spread.', 'Not yet; the final inspection is tomorrow.', 'I moved the lamp closer to the shelf.'], 2, 'The response gives current status and timing.'),
  response(3, 'Would you mind introducing the visiting researcher?', ['The introduction summarizes previous literature.', 'Visitors sign in at the reception desk.', 'Her research concerns coastal migration.', 'Certainly; send me the pronunciation of her name.'], 3, 'The reply agrees and requests useful preparation.'),
  response(4, 'I thought the studio fee included clay.', ['It includes basic clay, but specialty bodies cost extra.', 'The studio has twelve pottery wheels.', 'Fees are collected through the student portal.', 'I included the appendix with my report.'], 0, 'The answer clarifies the coverage and exception.'),
  response(5, 'Where should I submit the corrected tax form?', ['The correction changes only one digit.', 'Upload it through the secure payroll page.', 'I submitted my article to a journal.', 'Tax forms are usually retained for several years.'], 1, 'The secure destination answers the question.'),
  response(6, 'Shouldn’t the control group receive the same instructions?', ['The instructions are printed on both sides.', 'A control group provides a comparison.', 'Yes, except for the treatment-specific step.', 'I received the materials yesterday.'], 2, 'The reply preserves procedural equivalence while identifying the designed difference.'),
  response(7, 'The bus pass stopped working before its expiration date.', ['The bus follows a new route this month.', 'Passes can be purchased at the station.', 'Expiration dates are printed below the photograph.', 'Bring it to transit services so they can test the chip.'], 3, 'Testing the card addresses an early technical failure.'),
  response(8, 'Can we store these recordings on a personal cloud account?', ['No, the consent agreement requires the encrypted university server.', 'Clouds can interfere with optical observations.', 'I recorded the interview in a quiet office.', 'Personal accounts use separate passwords.'], 0, 'The data agreement dictates the approved storage location.'),
  response(9, 'Why hasn’t the maintenance request been assigned?', ['The assignment contains three short questions.', 'It lacks a room number and contact person.', 'Maintenance staff inspected the roof yesterday.', 'Requests are sorted by building name.'], 1, 'Missing routing information prevents assignment.'),
  response(10, 'Could the apparent effect come from unequal attrition?', ['The effect appears only in the second figure.', 'Attrition damages soft stone surfaces.', 'Yes, if dropout differs between the groups.', 'Unequal numbers can still have equal means.'], 2, 'Differential dropout can bias the comparison.'),
  response(11, 'I can’t open the raw image files on this computer.', ['The computer lab closes at ten tonight.', 'Raw images preserve more sensor information.', 'The file contains several layers.', 'Install the camera codec or use the conversion workstation.'], 3, 'Both suggestions address format compatibility.'),
  response(12, 'Is the museum tour accessible without stairs?', ['Yes, but please request the platform lift when booking.', 'The museum acquired the stairs in the 1920s.', 'A tour usually lasts about one hour.', 'Accessibility is discussed in the design course.'], 0, 'The reply confirms access and specifies an advance step.'),
  response(13, 'When will the committee release its shortlist?', ['The shortlist contains five project titles.', 'Probably after Friday’s final interview.', 'I released the clamp slowly.', 'Committees often keep confidential minutes.'], 1, 'The response gives the expected sequence and time.'),
  response(14, 'Would a logarithmic scale make this pattern clearer?', ['A scale measures the mass of each sample.', 'The pattern repeats every four rows.', 'It might, especially if the values span several orders of magnitude.', 'Clarity depends on careful proofreading.'], 2, 'Wide multiplicative ranges are a relevant reason to use logs.'),
  response(15, 'Who approved extending the exhibition loan?', ['The exhibition examines maritime exchange.', 'Approval was recorded in the database.', 'Extending a loan may change the insurance period.', 'The lending museum’s registrar authorized it.'], 3, 'The response identifies the responsible external official.'),
  response(16, 'The database merged two participants with similar names.', ['Separate the records using their study identifiers and audit the linked entries.', 'The participants attended the same orientation.', 'Similar names are common in large databases.', 'I merged the comments into one document.'], 0, 'Stable identifiers and an audit repair the erroneous linkage.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-poster', 'Listen to a Conversation', '학술 발표', 'B2', 'Student: My poster has room for either the full methods diagram or a larger results graph. Advisor: What question will most viewers ask? Student: Probably whether the temperature difference is meaningful. Advisor: Then enlarge the graph and put the essential method beside it in three steps. Add a QR code for the complete protocol, but do not make the main claim depend on visitors scanning it.', [
    ['Why does the advisor prioritize the results graph?', ['It addresses the likely central concern of the audience', 'The full method contains no information worth preserving', 'QR codes are prohibited at academic conferences', 'The poster must omit every procedural detail'], 0, 'Visual space should support the audience’s key interpretive question.'],
    ['How will the complete protocol remain available?', ['Through linked supplementary material that is not essential to basic understanding', 'As text printed over the enlarged graph', 'Only in the advisor’s private notes', 'By removing the concise three-step method'], 0, 'The link preserves depth while the poster remains self-contained.'],
  ]),
  ...listeningGroup('conversation-oven', 'Listen to a Conversation', '공용 주방', 'B1', 'Resident: The residence oven turns off after ten minutes. Clerk: Does the display show an error code? Resident: No, the clock resets to zero. Clerk: That sounds like a power interruption, not the timer. Please stop using it. I will mark it out of service and ask facilities to inspect the outlet. The microwave is on another circuit if you need to heat dinner.', [
    ['Why does the clerk suspect an electrical problem?', ['The clock resets rather than merely ending a cooking cycle', 'The oven displays a documented timer code', 'The microwave uses the same damaged outlet', 'The resident set the temperature too low'], 1, 'A full reset indicates loss of power.'],
    ['What should the resident do next?', ['Avoid the oven and use the offered alternative appliance', 'Restart the oven repeatedly until facilities arrive', 'Inspect the outlet without authorization', 'Move the microwave onto the oven circuit'], 1, 'The faulty device is being removed from service.'],
  ]),
  ...listeningGroup('conversation-translation', 'Listen to a Conversation', '설문 연구', 'C1', 'Researcher: The translated survey has the same words as the original, but pilot participants interpret the response scale differently. Consultant: Literal equivalence is not enough. Ask bilingual reviewers to explain what each item means, then back-translate a revised version. Researcher: Should we compare scores across languages now? Consultant: Not until you test whether the scale functions similarly. Otherwise a numerical difference may reflect wording rather than the underlying attitude.', [
    ['What problem did the pilot reveal?', ['Semantically similar wording may not produce equivalent measurement', 'Bilingual reviewers refused to read the original survey', 'Back-translation automatically changes participant attitudes', 'Numerical scores cannot be collected in another language'], 2, 'Literal translation did not ensure comparable interpretation.'],
    ['Why does the consultant postpone cross-language comparison?', ['Measurement differences could be mistaken for group differences', 'The response scale contains no numbers', 'Every participant must answer in both languages', 'The original survey lacks any underlying construct'], 2, 'Measurement invariance must be evaluated before comparing scores.'],
  ]),
  ...listeningGroup('conversation-reserve', 'Listen to a Conversation', '환경 동아리', 'B2', 'Student: Our club wants to remove invasive plants beside the reserve trail this weekend. Ranger: Please do not begin without a work plan. One invasive species resembles a rare native plant before flowering. Student: Could you mark the target areas? Ranger: Yes, and I will train two team leaders. Everyone else should work only beside a trained leader, and all removed material must go into sealed bags.', [
    ['Why is unsupervised removal risky?', ['Volunteers may confuse a protected native with the target plant', 'Sealed bags cause invasive plants to flower sooner', 'The trail contains no species requiring identification', 'Team leaders are prohibited from marking work areas'], 3, 'The plants are difficult to distinguish in the current stage.'],
    ['What structure will make the project safer?', ['Trained leaders will supervise work in designated locations', 'Every volunteer will select a separate unmarked area', 'Removed plants will remain loose beside the trail', 'The club will wait until all plants lose their flowers'], 3, 'Training, marking, and supervised teams reduce identification errors.'],
  ]),
  ...listeningGroup('conversation-sample-size', 'Listen to a Conversation', '통계 상담', 'C1', 'Student: My pilot found a large effect, so I calculated that the main study needs only twelve participants. Statistician: Pilot effects are unstable, especially in small samples, and often look larger than the true effect. Base the calculation on a plausible range from prior studies, not just this estimate. Student: Should I ignore the pilot? Statistician: Use it to estimate feasibility and variance, but show how required size changes under several effect assumptions.', [
    ['Why does the statistician distrust the small required sample?', ['It depends too heavily on an imprecise and possibly inflated pilot effect', 'Prior research always reports exactly twelve participants', 'Variance cannot be estimated from pilot observations', 'Feasibility is unrelated to sample planning'], 0, 'Small pilots yield noisy effect sizes that bias planning if treated as exact.'],
    ['What analysis is recommended?', ['A sensitivity calculation across a defensible range of expected effects', 'Selection of the assumption producing the cheapest design', 'Removal of all pilot information from feasibility planning', 'A guarantee that the largest reported effect will recur'], 1, 'Scenario-based planning makes uncertainty visible.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-generator', 'Listen to an Announcement', '건물 유지보수', 'B2', 'The science building will test its emergency generator Wednesday at six in the morning. Ordinary outlets may lose power for up to thirty seconds, but red emergency outlets should remain active. Researchers must confirm that freezers and incubators needing uninterrupted power are connected to red outlets by Tuesday evening. Do not move plugs during the test itself.', [
    ['What should researchers verify before Wednesday morning?', ['Critical equipment is connected to the emergency circuit', 'Every ordinary outlet remains powered continuously', 'The generator test begins after laboratory work', 'Plugs can be moved safely during the interruption'], 0, 'The red outlets are the protected circuit.'],
    ['Why should plugs not be moved during the test?', ['The interruption period is not the time to reconfigure critical connections', 'Red outlets permanently stop working after six', 'Ordinary equipment must be connected to every circuit at once', 'Researchers are expected to switch off the generator manually'], 0, 'Preparation must be completed beforehand.'],
  ]),
  ...listeningGroup('announcement-elections', 'Listen to an Announcement', '학생 자치', 'B2', 'Voting for graduate representatives opens Monday. Candidate statements appear exactly as submitted except that the election office removes links to fundraising pages. Students may update a statement until Friday at noon; after that, only factual corrections verified by the office will be accepted. Endorsements sent by departments will not be added to candidate pages.', [
    ['What content will the election office remove from a submitted statement?', ['A link intended to collect campaign funds', 'A verified correction submitted after Friday', 'The candidate’s own description of experience', 'A policy proposal written before the deadline'], 1, 'Fundraising links are explicitly excluded.'],
    ['What change is possible after the ordinary revision deadline?', ['An office-verified correction of factual information', 'A new departmental endorsement', 'A rewritten platform with additional promises', 'An unverified change to the candidate’s biography'], 1, 'Only substantiated factual corrections remain eligible.'],
  ]),
  ...listeningGroup('announcement-ice', 'Listen to an Announcement', '현장 안전', 'C1', 'Tomorrow’s lake-sediment sampling will proceed from shore rather than from the ice. Recent cold weather has thickened the surface near the dock, but current measurements are uneven across the lake and do not meet the field station’s safety threshold. Teams will use the long corer from the platform and practice GPS transects on land. Do not bring personal ice cleats, since no participant is authorized to walk onto the lake.', [
    ['Why was shore-based work chosen despite visible ice?', ['Measured thickness is inconsistent and below the required safety standard', 'The field station has prohibited sediment analysis', 'Personal cleats make GPS equipment inaccurate', 'The long corer can operate only from the lake center'], 2, 'Appearance near one dock does not establish safe ice across the work area.'],
    ['What will replace the planned on-ice transect practice?', ['A land-based exercise using the same positioning skill', 'An unauthorized walk with personal safety equipment', 'A cancellation of every component of field training', 'A laboratory lecture with no sampling'], 2, 'The skill will be practiced on solid ground.'],
  ]),
  ...listeningGroup('announcement-costumes', 'Listen to an Announcement', '공연 의상', 'B1', 'Cast members should collect cleaned costumes from the wardrobe room after three today. Try on every piece before leaving. Alteration requests submitted by tomorrow noon will be completed before dress rehearsal; requests made later will be handled only if they affect safety or prevent movement on stage.', [
    ['What should performers do while still in the wardrobe room?', ['Check the fit of all assigned costume pieces', 'Submit every alteration after tomorrow noon', 'Take uncleaned costumes directly to rehearsal', 'Request changes only when appearance is affected'], 3, 'Trying items on immediately reveals fit issues within the normal alteration window.'],
    ['Which late request may still receive priority?', ['A correction needed to move safely during performance', 'A preference for a slightly different decorative color', 'A request to collect the costume before three', 'A change unrelated to fit, motion, or safety'], 3, 'Safety and movement remain exceptions after the deadline.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-crispr', 'Listen to an Academic Talk', '분자유전학', 'C1', 'CRISPR systems can be programmed with a guide RNA to direct a cutting enzyme toward a matching DNA sequence. The match need not be perfect, so cuts may also occur at off-target sites. Researchers predict likely sites computationally and sequence them after editing, but targeted checks can miss unexpected changes elsewhere in the genome. Whole-genome sequencing broadens detection, yet it also finds background variants unrelated to editing. Appropriate unedited controls help distinguish ordinary variation from treatment effects.', [
    ['Why can checking only predicted sites be inadequate?', ['Editing may affect locations the prediction model did not identify', 'Guide RNA always matches every genomic sequence perfectly', 'Whole-genome sequencing detects no background variation', 'Unedited controls receive the same programmed cut'], 0, 'Model-based candidates do not cover every possible off-target event.'],
    ['What role do unedited controls play?', ['They reveal variants likely unrelated to the editing procedure', 'They increase the guide RNA’s binding strength', 'They remove every mutation from the treated cells', 'They identify only changes already predicted computationally'], 0, 'Background differences appear even without the intervention.'],
  ]),
  ...listeningGroup('talk-agglomeration', 'Listen to an Academic Talk', '도시경제학', 'C1', 'Firms often cluster geographically because proximity can create agglomeration benefits. A shared labor pool helps employers find specialized workers, nearby suppliers reduce coordination costs, and informal contact can spread knowledge. Clustering also raises rents, congestion, and competition for staff. Observing productive firms in one city does not prove that the city made them productive; successful firms may choose to locate there. Researchers use plant relocations, policy boundaries, and historical infrastructure to separate selection from causal place effects.', [
    ['What is one mechanism that can make clustering productive?', ['Proximity supports specialized matching and information exchange', 'Congestion eliminates the cost of commercial property', 'Geographic concentration prevents workers from changing employers', 'Every supplier becomes part of the same firm'], 1, 'Dense local networks can improve matching and coordination.'],
    ['Why is a simple productivity comparison causally ambiguous?', ['More capable firms may select the same locations that appear advantageous', 'Firm output cannot be measured within a city', 'Historical infrastructure is identical everywhere', 'Relocation studies never involve geographic change'], 1, 'Sorting can produce the association without a place effect.'],
  ]),
  ...listeningGroup('talk-mantle', 'Listen to an Academic Talk', '지구과학', 'C1', 'Earth’s mantle is solid on short time scales, yet over millions of years it deforms and circulates. Hotter material is generally less dense and tends to rise, while cooler material sinks. This convection transports heat and contributes to plate motion, but plates are not simply passive rafts on circular currents. Sinking slabs can pull plates, and strength varies with depth, composition, and water content. Laboratory experiments and numerical models therefore represent mantle viscosity as strongly temperature-dependent.', [
    ['How can solid mantle rock participate in circulation?', ['It deforms gradually when observed over geological time', 'It melts completely beneath every tectonic plate', 'It behaves as a low-viscosity liquid over seconds', 'It remains stationary while only plates circulate'], 2, 'Solid-state creep accumulates over long periods.'],
    ['Why is the passive-raft analogy incomplete?', ['Plate forces and mantle properties interact in more than one direction', 'Mantle viscosity is constant at all depths', 'Sinking slabs have no mechanical effect on plates', 'Temperature cannot influence rock density'], 2, 'Slab pull and variable strength complicate one-way transport.'],
  ]),
  ...listeningGroup('talk-working-memory', 'Listen to an Academic Talk', '인지심리학', 'B2', 'Visual working memory holds a limited amount of information for brief use. Early theories described a fixed number of object slots. Later findings suggest that precision also matters: people may remember more objects, but each representation becomes less exact. Performance depends on similarity and attention, so a single capacity number can hide important variation. Experiments ask participants to reproduce a color or orientation, measuring error continuously rather than scoring only correct or incorrect responses.', [
    ['What refinement did later research add to fixed-slot accounts?', ['Memory quality can decline gradually as more items compete for resources', 'Every stored object retains identical perfect precision', 'Attention has no influence on short-term representation', 'Only verbal information can be measured continuously'], 3, 'Capacity involves fidelity as well as item count.'],
    ['Why use continuous reproduction error?', ['It reveals how precisely a feature was retained', 'It forces participants to remember unlimited objects', 'It removes similarity between visual items', 'It converts orientation into a verbal category only'], 3, 'Error magnitude captures representational quality.'],
  ]),
  ...listeningGroup('talk-deltas', 'Listen to an Academic Talk', '수문지형학', 'C1', 'A river delta persists only if sediment delivery can compensate for sinking land, wave erosion, and sea-level rise. Dams trap sediment upstream, while levees prevent floods from spreading fresh material across the delta plain. Engineers may divert part of a river through a controlled opening to rebuild wetlands. A diversion can deliver sediment but also change salinity and fisheries. Evaluating it requires measuring where grains settle, not merely how much sediment enters the channel.', [
    ['Why can levees contribute to delta loss?', ['They disconnect the floodplain from sediment that could raise its surface', 'They increase the amount of river sediment reaching every wetland', 'They prevent land from sinking beneath sea level', 'They eliminate the effect of waves on the coastline'], 0, 'Confinement blocks natural overbank deposition.'],
    ['Why is total sediment flow an incomplete success measure for a diversion?', ['Material must reach and remain in the locations needing elevation gain', 'Salinity cannot change when a river route is altered', 'Every grain entering a channel forms permanent land', 'Fisheries depend only on the diversion’s construction cost'], 2, 'Delivery to the target landscape matters more than channel throughput alone.'],
  ]),
  ...listeningGroup('talk-gene-culture', 'Listen to an Academic Talk', '인류진화학', 'C1', 'Gene–culture coevolution describes feedback between socially learned behavior and genetic selection. Dairy farming, for example, created environments in which adults able to digest lactose gained a nutritional advantage in some populations. The genetic trait did not cause every society to herd cattle, nor did culture directly rewrite genes. Rather, a cultural practice changed selection pressures over generations. Similar-looking associations can also reflect migration or ancestry, so researchers combine ancient DNA, archaeological evidence, and explicit demographic models.', [
    ['What does the dairy example illustrate?', ['A learned practice can alter which inherited traits confer an advantage', 'Cultural decisions directly edit an individual’s DNA', 'Lactose digestion inevitably produces cattle herding', 'Every farming population experiences identical selection'], 1, 'Culture modifies the environment in which genetic variants succeed.'],
    ['Why are demographic models needed?', ['Population movement can mimic a relationship attributed to selection', 'Ancient DNA contains no information about ancestry', 'Archaeological evidence proves that migration never occurred', 'Genetic change always happens within one generation'], 3, 'Migration and shared ancestry are alternative explanations for allele patterns.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the boundary comparison informative?', 'Had assignment not', ['changed abruptly', 'at the cutoff', 'the two groups', 'would have been', 'treated alike'], 'f07-inverted-counterfactual-negative'],
  ['Did the additional controls resolve the issue?', 'Far from eliminating', ['the uncertainty', 'they revealed', 'several assumptions', 'that had gone', 'untested'], 'f07-far-from-gerund-relative'],
  ['Why did the curator preserve the alteration?', 'It was considered', ['part of the object', 'as it had', 'been used', 'rather than damage', 'to be removed'], 'f07-as-passive-rather-than'],
  ['Can we infer the mechanism from this result?', 'Only if the rival', ['explanations can', 'be excluded', 'would such', 'an inference', 'be justified'], 'f07-only-if-inversion-passive'],
  ['What did the sensitivity analysis show?', 'Whichever threshold', ['the researchers chose', 'the principal estimate', 'remained within', 'a narrow', 'range'], 'f07-whichever-concessive'],
  ['Why was the narrative difficult to verify?', 'So few contemporary', ['records survive', 'that much of', 'what occurred', 'must be reconstructed', 'indirectly'], 'f07-so-few-result-passive'],
  ['Should the outlying cases be removed?', 'To exclude them', ['merely because', 'they weaken', 'the hypothesis', 'would introduce', 'another bias'], 'f07-infinitive-subject-would'],
  ['How might the conclusion have differed?', 'But for the', ['independent measurements', 'the apparent pattern', 'might have been', 'attributed entirely', 'to chance'], 'f07-but-for-modal-perfect-passive'],
  ['Why combine qualitative and quantitative evidence?', 'What one method', ['cannot capture', 'may be precisely', 'what the other', 'is able', 'to reveal'], 'f07-fused-relative-pseudo-cleft'],
  ['Did the authors claim universal validity?', 'They argued only', ['that the account', 'was more consistent', 'with the evidence', 'than were', 'its alternatives'], 'f07-comparative-subject-inversion'],
]
const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '공동 연구 일정', 'B2', 420), instruction: '상황, 영향, 구체적인 해결 요청을 갖춘 이메일을 작성하세요.', prompt: 'A collaborator changed the coding scheme after you had already analyzed half of the dataset, but did not document which categories were revised. Write to the collaborator. Explain the problem this creates, request the missing information, and propose a process to prevent inconsistent coding in the remaining work.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '도시 집중', 'C1', 600), instruction: '제시된 관점을 평가하고 자신의 주장과 근거를 발전시키세요.', prompt: 'Professor Romero: Should governments encourage high-technology firms to cluster in a few major cities or distribute them across regions?', passage: 'Leila: Clusters accelerate innovation because specialized workers and suppliers can exchange ideas efficiently.\nOmar: Concentration raises housing costs and leaves other regions with fewer opportunities and weaker tax bases.' })

const repeatSentences = ['Welcome to the campus radio production studio.', 'Place drinks on the shelf outside the control room.', 'Check each microphone level before the interview begins.', 'Keep the guest’s voice below the red peak indicator.', 'If a connection fails, continue recording on the backup device.', 'Write the correct program title in every saved filename.', 'Before leaving, export two verified copies, return the headphones, and note any technical fault in the studio log.']
const interviewQuestions = ['Describe a technology that has changed the community where you live.', 'Who has benefited most from that technology, and who may have been left out?', 'Should governments actively influence where technology companies locate?', 'How can a community gain economic benefits without becoming dependent on one industry?']
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '라디오 스튜디오 안내', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f07-repeat', scenarioId: 'f07-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '기술과 지역사회', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 이유와 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f07-interview', scenarioId: 'f07-interview', sequenceIndex })),
]

export const AUTHORED_FORM_07_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_07_IDS = AUTHORED_FORM_07_ITEMS.map((item) => item.id)
