import type { BaseItem } from './types'

const common = {
  section: 'listening' as const,
  module: 1,
  kind: 'listen-choice' as const,
  instruction: '오디오는 한 번 재생됩니다. 말하는 사람의 목적과 핵심 내용을 파악하세요.',
  sourceFamily: 'authored-supplement',
}

export const AUTHORED_SUPPLEMENT_ITEMS: BaseItem[] = [
  {
    ...common,
    id: 'a-l-response-archive',
    title: 'Listen and Choose a Response',
    topic: '기록 보관소 방문',
    difficulty: 'B1',
    timeSeconds: 35,
    audioText: 'Do you know whether the archive accepts walk-in visitors?',
    options: [
      'Only on Friday afternoons; otherwise, you need an appointment.',
      'The oldest documents are stored in acid-free boxes.',
      'I walked past the archive on my way to class.',
      'Visitors usually spend about an hour reading the catalog.',
    ],
    answer: 0,
    explanation: 'The speaker is asking about access without a reservation, so the reply must explain the walk-in policy.',
  },
  {
    ...common,
    id: 'a-l-conversation-printer-0', title: 'Listen to a Conversation', topic: '시제품 제작', context: '3D 프린터 치수 오차', difficulty: 'B2', timeSeconds: 70,
    stimulusGroupId: 'a-l-conversation-printer', sequenceIndex: 0,
    audioText: 'Student: The lid I printed is slightly too small for the sensor case, although the digital model has the correct dimensions. Technician: Which material did you use? Student: The new biodegradable filament. Technician: That material contracts more as it cools. Increase the model by two percent and print only the corner section first. If that piece fits, you can produce the entire lid without wasting another full batch.',
    prompt: 'What problem does the student report?',
    options: ['The printer changed the digital model.', 'The finished lid does not fit the sensor case.', 'The laboratory has run out of filament.', 'The sensor was damaged during cooling.'], answer: 1,
    explanation: 'The student says that the printed lid is smaller than the case even though the model dimensions are correct.',
  },
  {
    ...common,
    id: 'a-l-conversation-printer-1', title: 'Listen to a Conversation', topic: '시제품 제작', context: '3D 프린터 치수 오차', difficulty: 'B2', timeSeconds: 70,
    stimulusGroupId: 'a-l-conversation-printer', sequenceIndex: 1,
    audioText: 'Student: The lid I printed is slightly too small for the sensor case, although the digital model has the correct dimensions. Technician: Which material did you use? Student: The new biodegradable filament. Technician: That material contracts more as it cools. Increase the model by two percent and print only the corner section first. If that piece fits, you can produce the entire lid without wasting another full batch.',
    prompt: 'What does the technician identify as the likely cause?',
    options: ['The material shrinks after it leaves the printer.', 'The student measured a different sensor case.', 'The digital file contains a missing corner.', 'The printer uses an incorrect unit of measurement.'], answer: 0,
    explanation: 'The technician explains that the biodegradable filament contracts while cooling.',
  },
  {
    ...common,
    id: 'a-l-conversation-printer-2', title: 'Listen to a Conversation', topic: '시제품 제작', context: '3D 프린터 치수 오차', difficulty: 'B2', timeSeconds: 70,
    stimulusGroupId: 'a-l-conversation-printer', sequenceIndex: 2,
    audioText: 'Student: The lid I printed is slightly too small for the sensor case, although the digital model has the correct dimensions. Technician: Which material did you use? Student: The new biodegradable filament. Technician: That material contracts more as it cools. Increase the model by two percent and print only the corner section first. If that piece fits, you can produce the entire lid without wasting another full batch.',
    prompt: 'Why does the technician recommend printing only one corner first?',
    options: ['To compare two kinds of sensors', 'To reduce material use while testing the adjustment', 'To allow the digital model to cool more slowly', 'To reserve the full printer for another laboratory'], answer: 1,
    explanation: 'A small test piece can confirm the revised scale before material is spent on the complete lid.',
  },
  {
    ...common,
    id: 'a-l-conversation-field-trip-0', title: 'Listen to a Conversation', topic: '지질학 현장학습', context: '접근 가능한 관찰 지점', difficulty: 'C1', timeSeconds: 70,
    stimulusGroupId: 'a-l-conversation-field-trip', sequenceIndex: 0,
    audioText: 'Student: I use a wheelchair, and the field-trip notice says the quarry path has several steps. Professor: The lower quarry is inaccessible, but the same rock boundary is exposed beside the visitor center. I can move the first observation there. For the second activity, everyone analyzes samples in the classroom, so that part requires no change. Would you review the revised route with me before I send it to the class?',
    prompt: 'Why does the student speak with the professor?',
    options: ['A required field location may not be accessible.', 'The classroom samples were labeled incorrectly.', 'The visitor center canceled the entire trip.', 'A wheelchair was left beside the quarry path.'], answer: 0,
    explanation: 'The steps on the quarry route create an access barrier for the student.',
  },
  {
    ...common,
    id: 'a-l-conversation-field-trip-1', title: 'Listen to a Conversation', topic: '지질학 현장학습', context: '접근 가능한 관찰 지점', difficulty: 'C1', timeSeconds: 70,
    stimulusGroupId: 'a-l-conversation-field-trip', sequenceIndex: 1,
    audioText: 'Student: I use a wheelchair, and the field-trip notice says the quarry path has several steps. Professor: The lower quarry is inaccessible, but the same rock boundary is exposed beside the visitor center. I can move the first observation there. For the second activity, everyone analyzes samples in the classroom, so that part requires no change. Would you review the revised route with me before I send it to the class?',
    prompt: 'How will the professor modify the first activity?',
    options: ['Replace field observation with a written report', 'Move it to another exposure of the same geological feature', 'Ask only the student to remain at the visitor center', 'Analyze the classroom samples before leaving campus'], answer: 1,
    explanation: 'The same rock boundary can be observed at the accessible visitor-center location.',
  },
  {
    ...common,
    id: 'a-l-conversation-field-trip-2', title: 'Listen to a Conversation', topic: '지질학 현장학습', context: '접근 가능한 관찰 지점', difficulty: 'C1', timeSeconds: 70,
    stimulusGroupId: 'a-l-conversation-field-trip', sequenceIndex: 2,
    audioText: 'Student: I use a wheelchair, and the field-trip notice says the quarry path has several steps. Professor: The lower quarry is inaccessible, but the same rock boundary is exposed beside the visitor center. I can move the first observation there. For the second activity, everyone analyzes samples in the classroom, so that part requires no change. Would you review the revised route with me before I send it to the class?',
    prompt: 'What does the professor ask the student to do?',
    options: ['Select different rocks for the whole class', 'Confirm that the proposed route addresses the access problem', 'Explain the change during the classroom activity', 'Contact the quarry about rebuilding the lower path'], answer: 1,
    explanation: 'The professor wants the student to review the revised route before it is announced.',
  },
  {
    ...common,
    id: 'a-l-announcement-rare-books-0',
    title: 'Listen to an Announcement',
    topic: '희귀자료 열람실',
    context: '습도 조절 장비 교체',
    difficulty: 'B2',
    timeSeconds: 55,
    stimulusGroupId: 'a-l-announcement-rare-books',
    sequenceIndex: 0,
    audioText: 'Beginning Tuesday, the rare-books reading room will close for four days while its humidity-control equipment is replaced. Researchers may still request digital scans through the catalog. Requests submitted by noon will normally be delivered the following business day. Materials already reserved for in-person use will remain on hold until the room reopens; they will not be sent to the main circulation desk because they require supervised handling.',
    prompt: 'Why will the rare-books reading room close?',
    options: [
      'Its environmental-control equipment is being replaced.',
      'The library is transferring its collection to another campus.',
      'Researchers requested more time to examine reserved materials.',
      'The main circulation desk can no longer supervise visitors.',
    ],
    answer: 0,
    explanation: 'The closure is specifically for replacement of the humidity-control equipment.',
  },
  {
    ...common,
    id: 'a-l-announcement-rare-books-1',
    title: 'Listen to an Announcement',
    topic: '희귀자료 열람실',
    context: '습도 조절 장비 교체',
    difficulty: 'B2',
    timeSeconds: 55,
    stimulusGroupId: 'a-l-announcement-rare-books',
    sequenceIndex: 1,
    audioText: 'Beginning Tuesday, the rare-books reading room will close for four days while its humidity-control equipment is replaced. Researchers may still request digital scans through the catalog. Requests submitted by noon will normally be delivered the following business day. Materials already reserved for in-person use will remain on hold until the room reopens; they will not be sent to the main circulation desk because they require supervised handling.',
    prompt: 'What can a researcher do while the room is closed?',
    options: [
      'Collect rare materials from the circulation desk.',
      'Ask for a digital copy through the catalog.',
      'Enter the room after normal library hours.',
      'Take a reserved item to a different reading area.',
    ],
    answer: 1,
    explanation: 'Digital scan requests remain available even though in-person access is suspended.',
  },
  {
    ...common,
    id: 'a-l-announcement-theater-0',
    title: 'Listen to an Announcement',
    topic: '학생극장 안전 훈련',
    context: '공연 중 대피 절차',
    difficulty: 'B2',
    timeSeconds: 55,
    stimulusGroupId: 'a-l-announcement-theater',
    sequenceIndex: 0,
    audioText: 'Tonight’s rehearsal will include an unannounced evacuation drill. When the alarm sounds, performers should leave costumes and props where they are and exit through the nearest marked door. Stage managers will bring the attendance lists to the courtyard. The rehearsal will resume only after the safety officer checks the building. Because the drill must resemble an actual emergency, no one will be told exactly when it will begin.',
    prompt: 'What should performers do when the alarm sounds?',
    options: [
      'Carry valuable props into the courtyard.',
      'Wait on stage for the attendance list.',
      'Use the nearest designated exit immediately.',
      'Ask the stage manager whether the alarm is real.',
    ],
    answer: 2,
    explanation: 'Performers are told to leave belongings and use the nearest marked exit.',
  },
  {
    ...common,
    id: 'a-l-announcement-theater-1',
    title: 'Listen to an Announcement',
    topic: '학생극장 안전 훈련',
    context: '공연 중 대피 절차',
    difficulty: 'B2',
    timeSeconds: 55,
    stimulusGroupId: 'a-l-announcement-theater',
    sequenceIndex: 1,
    audioText: 'Tonight’s rehearsal will include an unannounced evacuation drill. When the alarm sounds, performers should leave costumes and props where they are and exit through the nearest marked door. Stage managers will bring the attendance lists to the courtyard. The rehearsal will resume only after the safety officer checks the building. Because the drill must resemble an actual emergency, no one will be told exactly when it will begin.',
    prompt: 'Why is the starting time of the drill being withheld?',
    options: [
      'The safety officer has not arrived yet.',
      'The exercise is intended to imitate a real emergency.',
      'The rehearsal schedule changes whenever props are moved.',
      'Stage managers must first count the audience members.',
    ],
    answer: 1,
    explanation: 'Not announcing the time makes participants respond as they would to an unexpected emergency.',
  },
  {
    ...common,
    id: 'a-l-talk-beavers-0',
    title: 'Listen to an Academic Talk',
    topic: '생태학',
    context: '비버가 하천에 미치는 영향',
    difficulty: 'B2',
    timeSeconds: 80,
    stimulusGroupId: 'a-l-talk-beavers',
    sequenceIndex: 0,
    audioText: 'Beavers are often called ecosystem engineers because their dams alter the physical structure of streams. Water slows behind a dam, sediment settles, and shallow ponds form. These ponds can provide habitat for amphibians and water birds, but they may also flood roads or farmland. The ecological effect therefore depends partly on location. Removing every dam can eliminate useful wetlands, whereas leaving every dam untouched may impose serious costs on nearby communities.',
    prompt: 'Why does the lecturer call beavers “ecosystem engineers”?',
    options: [
      'They select habitats already designed by other animals.',
      'Their structures change the conditions in a stream.',
      'They prevent sediment from entering all waterways.',
      'Their populations are managed by civil engineers.',
    ],
    answer: 1,
    explanation: 'By building dams, beavers physically modify water flow, sediment, and habitat.',
  },
  {
    ...common,
    id: 'a-l-talk-beavers-1',
    title: 'Listen to an Academic Talk',
    topic: '생태학',
    context: '비버가 하천에 미치는 영향',
    difficulty: 'B2',
    timeSeconds: 80,
    stimulusGroupId: 'a-l-talk-beavers',
    sequenceIndex: 1,
    audioText: 'Beavers are often called ecosystem engineers because their dams alter the physical structure of streams. Water slows behind a dam, sediment settles, and shallow ponds form. These ponds can provide habitat for amphibians and water birds, but they may also flood roads or farmland. The ecological effect therefore depends partly on location. Removing every dam can eliminate useful wetlands, whereas leaving every dam untouched may impose serious costs on nearby communities.',
    prompt: 'What conclusion does the lecturer draw about managing beaver dams?',
    options: [
      'One policy should be applied to every stream.',
      'Ecological benefits always outweigh property damage.',
      'Management decisions should reflect local consequences.',
      'Artificial wetlands should replace all natural ponds.',
    ],
    answer: 2,
    explanation: 'The lecture contrasts benefits and costs and says that the result depends on location.',
  },
  {
    ...common,
    id: 'a-l-talk-volcanoes-0',
    title: 'Listen to an Academic Talk',
    topic: '기후과학',
    context: '화산 분출과 지구 기온',
    difficulty: 'C1',
    timeSeconds: 80,
    stimulusGroupId: 'a-l-talk-volcanoes',
    sequenceIndex: 0,
    audioText: 'Large volcanic eruptions can affect climate in two opposing ways. Volcanoes release carbon dioxide, a greenhouse gas, but a single eruption usually adds far less carbon than human activity does in a year. More importantly in the short term, sulfur gases can form reflective particles high in the atmosphere. Those particles reduce the sunlight reaching Earth’s surface and may cool global temperatures for a few years before they gradually disappear.',
    prompt: 'What causes the short-term cooling described in the talk?',
    options: [
      'Volcanic carbon absorbs heat near the surface.',
      'Reflective particles reduce incoming sunlight.',
      'Ash permanently blocks the lower atmosphere.',
      'Human emissions decline after every eruption.',
    ],
    answer: 1,
    explanation: 'Sulfur-derived particles reflect sunlight and temporarily reduce surface heating.',
  },
  {
    ...common,
    id: 'a-l-talk-volcanoes-1',
    title: 'Listen to an Academic Talk',
    topic: '기후과학',
    context: '화산 분출과 지구 기온',
    difficulty: 'C1',
    timeSeconds: 80,
    stimulusGroupId: 'a-l-talk-volcanoes',
    sequenceIndex: 1,
    audioText: 'Large volcanic eruptions can affect climate in two opposing ways. Volcanoes release carbon dioxide, a greenhouse gas, but a single eruption usually adds far less carbon than human activity does in a year. More importantly in the short term, sulfur gases can form reflective particles high in the atmosphere. Those particles reduce the sunlight reaching Earth’s surface and may cool global temperatures for a few years before they gradually disappear.',
    prompt: 'Why does the lecturer compare volcanic carbon with human emissions?',
    options: [
      'To show that the two sources release equal amounts each year',
      'To explain why volcanic particles remain indefinitely',
      'To place the warming effect of one eruption in perspective',
      'To argue that carbon dioxide does not influence climate',
    ],
    answer: 2,
    explanation: 'The comparison shows that carbon from one eruption is relatively small beside annual human emissions.',
  },
  {
    ...common,
    id: 'a-l-talk-sunk-cost-0',
    title: 'Listen to an Academic Talk',
    topic: '행동경제학',
    context: '매몰비용과 의사결정',
    difficulty: 'C1',
    timeSeconds: 80,
    stimulusGroupId: 'a-l-talk-sunk-cost',
    sequenceIndex: 0,
    audioText: 'Imagine that you buy a ticket for an outdoor concert, but a storm begins before the performance. The ticket price cannot be recovered whether you attend or stay home, so it is a sunk cost. A forward-looking decision would compare only the remaining benefits and risks. Yet people often attend because wasting the ticket feels painful. The earlier expense influences a choice even though that expense cannot be changed by the choice.',
    prompt: 'Why is the ticket price considered a sunk cost?',
    options: [
      'Its value increases when the weather worsens.',
      'The purchaser can exchange it after the concert.',
      'The money cannot be recovered by either current choice.',
      'Its price includes both benefits and future risks.',
    ],
    answer: 2,
    explanation: 'The payment is already irreversible whether the person attends or stays home.',
  },
  {
    ...common,
    id: 'a-l-talk-sunk-cost-1',
    title: 'Listen to an Academic Talk',
    topic: '행동경제학',
    context: '매몰비용과 의사결정',
    difficulty: 'C1',
    timeSeconds: 80,
    stimulusGroupId: 'a-l-talk-sunk-cost',
    sequenceIndex: 1,
    audioText: 'Imagine that you buy a ticket for an outdoor concert, but a storm begins before the performance. The ticket price cannot be recovered whether you attend or stay home, so it is a sunk cost. A forward-looking decision would compare only the remaining benefits and risks. Yet people often attend because wasting the ticket feels painful. The earlier expense influences a choice even though that expense cannot be changed by the choice.',
    prompt: 'What behavior illustrates the bias discussed by the lecturer?',
    options: [
      'Checking the weather forecast before buying a ticket',
      'Attending a risky event mainly to avoid feeling that the ticket was wasted',
      'Comparing the concert’s remaining benefits with the danger of the storm',
      'Requesting a refund before the performance is canceled',
    ],
    answer: 1,
    explanation: 'The past payment improperly drives the current decision to attend despite the storm.',
  },
]
