import { prepareSentenceTiles } from './sentenceTiles'
import type { BaseItem } from './types'

type Difficulty = NonNullable<BaseItem['difficulty']>
type Question = [prompt: string, options: string[], answer: number, explanation: string]

const base = (id: string, section: BaseItem['section'], kind: BaseItem['kind'], title: string, topic: string, difficulty: Difficulty, timeSeconds: number): BaseItem => ({
  id: `f04-${id}`, section, module: 1, kind, title, topic, difficulty, timeSeconds,
  instruction: '', sourceFamily: 'authored-form-04',
})
const cloze = (id: string, topic: string, difficulty: Difficulty, passage: string, answer: string): BaseItem => ({
  ...base(id, 'reading', 'complete-words', 'Complete the Words', topic, difficulty, 240),
  instruction: '첫 문장을 바탕으로 문맥, 문법, 철자에 맞게 열 개 단어를 완성하세요.', passage, answer,
  explanation: '문장의 논리와 품사 형태를 함께 고려해야 모든 어간이 자연스럽게 완성됩니다.',
})
const daily = (id: string, topic: string, difficulty: Difficulty, passage: string, question: Question): BaseItem => ({
  ...base(id, 'reading', 'multiple-choice', 'Read in Daily Life', topic, difficulty, 75),
  instruction: '실용문에서 조건, 예외, 필요한 행동을 구분해 답하세요.', passage,
  prompt: question[0], options: question[1], answer: question[2], explanation: question[3],
})
const readingGroup = (id: string, topic: string, difficulty: Difficulty, passage: string, questions: Question[]): BaseItem[] => questions.map((q, sequenceIndex) => ({
  ...base(`${id}-${sequenceIndex}`, 'reading', 'multiple-choice', 'Read an Academic Passage', topic, difficulty, 120),
  instruction: '학술 지문의 주장, 근거, 추론, 연구 한계를 구분해 답하세요.', passage,
  prompt: q[0], options: q[1], answer: q[2], explanation: q[3], stimulusGroupId: `f04-${id}`, sequenceIndex,
}))
const response = (id: number, audioText: string, options: string[], answer: number, explanation: string): BaseItem => ({
  ...base(`response-${id}`, 'listening', 'listen-choice', 'Listen and Choose a Response', '캠퍼스 의사소통', id < 8 ? 'B1' : 'B2', 35),
  instruction: '짧은 말을 듣고 상황에 가장 자연스럽게 이어지는 응답을 고르세요.', audioText, options, answer, explanation,
})
const listeningGroup = (id: string, title: string, topic: string, difficulty: Difficulty, audioText: string, questions: Question[]): BaseItem[] => questions.map((q, sequenceIndex) => ({
  ...base(`${id}-${sequenceIndex}`, 'listening', 'listen-choice', title, topic, difficulty, title === 'Listen to an Announcement' ? 55 : title === 'Listen to an Academic Talk' ? 80 : 70),
  instruction: title === 'Listen to an Announcement' ? '공지의 변경 사항, 조건, 청자의 행동을 파악하세요.' : title === 'Listen to an Academic Talk' ? '강의의 중심 내용과 근거 및 한계를 파악하세요.' : '대화의 문제, 제약, 해결 과정을 파악하세요.',
  audioText, prompt: q[0], options: q[1], answer: q[2], explanation: q[3], stimulusGroupId: `f04-${id}`, sequenceIndex,
}))

const reading: BaseItem[] = [
  cloze('cloze-lichen', '공생생태학', 'B2', 'Lichens consist of a fungus living with a photosynthetic partner. The fungus prov___ structure and retains water, while the partner prod___ sugars. This association allows lichens to col___ bare rock where few organisms survive. They grow ext___ slowly and absorb substances directly from the air. Consequently, some species are sen___ to pollution and can ind___ changes in air quality. Their absence does not aut___ prove contamination, because climate and habitat also mat___. Scientists therefore comp___ multiple sites and meas___ pollutants before drawing conclusions.', 'ides|uces|onize|remely|sitive|icate|omatically|ter|are|ure'),
  cloze('cloze-peer-review', '과학방법론', 'C1', 'Peer review asks specialists to evaluate a study before publication. Reviewers ass___ whether the methods support the claims and whether important evidence has been over___. The process can det___ errors, but it cannot guar___ that every conclusion is correct. Reviewers may dis___ about interpretation, and shared assumptions can remain unq___. Journals sometimes publish reports openly to inc___ accountability. Replication supplies a different safeguard by testing whether findings rec___ under new conditions. Scientific reliability therefore dep___ on continuing scrutiny rather than a single act of appr___.', 'ess|looked|ect|antee|agree|uestioned|rease|ur|ends|oval'),
  cloze('cloze-permafrost', '기후지질학', 'C1', 'Permafrost is ground that remains frozen for at least two consecutive years. Its upper layer th___ seasonally, allowing shallow-rooted plants to grow. Rising temperatures can dee___ this active layer and dest___ ice within the soil. When ice melts, the surface may sub___ unevenly, damaging roads and buildings. Thawing organic matter also becomes ava___ to microbes, which rel___ carbon dioxide or methane. The amount emitted dep___ on moisture, vegetation, and microbial processes. Researchers com___ field measurements with models, yet large regional unc___ remain. These feedbacks make long-term mon___ essential.', 'aws|pen|roy|side|ilable|ease|ends|bine|ertainties|itoring'),
  daily('daily-isotope-lab', '분석 장비', 'C1', 'The isotope laboratory accepts samples on Tuesdays, but corrosive liquids require prior safety review. A reservation confirms instrument time, not sample approval. Users must upload a composition sheet at least two business days before arrival; samples lacking approval will be stored, not analyzed, and the reserved time will not be refunded.', ['A researcher has reserved Tuesday instrument time for a corrosive sample. What is still required?', ['Obtaining safety clearance through an advance composition submission', 'Requesting repayment after the material has been measured', 'Delivering the liquid without identifying its constituents', 'Changing the booking to a nonbusiness day'], 0, 'Instrument access and sample authorization are separate; corrosive material needs the earlier review.']),
  daily('daily-oral-history', '기록 보관', 'B2', 'Oral-history recordings may be quoted in coursework unless a donor restriction appears in the catalog. Downloading an unrestricted file does not permit posting the interview publicly. Students planning a public exhibit must obtain separate reuse permission and include the archive’s prescribed credit line.', ['What additional step applies when an interview will appear in an online exhibition?', ['Securing public-reuse permission from the archive', 'Removing the catalog record before publication', 'Replacing every quotation with an anonymous summary', 'Returning the downloaded audio on physical media'], 0, 'Course quotation access does not itself authorize public redistribution.']),
  daily('daily-greenhouse', '온실 운영', 'B2', 'Benches in Greenhouse B will be disinfected Wednesday. Move labeled experimental plants to the marked holding zone by 5 p.m. Tuesday. Staff will relocate unlabeled teaching plants, but they will not move research specimens whose ownership cannot be verified.', ['Which plants must researchers themselves relocate before cleaning?', ['Identifiable experimental specimens assigned to them', 'Unlabeled plants used in introductory classes', 'Every plant already inside the holding zone', 'Specimens delivered after Wednesday’s treatment'], 0, 'Researchers are responsible for their labeled experimental material.']),
  daily('daily-theater', '공연 제작', 'B1', 'Costume fittings are scheduled in twenty-minute blocks. Arrive five minutes early wearing the shoes required for your role. Anyone more than ten minutes late must contact the costume supervisor to arrange another time; another actor cannot exchange slots without approval.', ['What should a performer do after arriving twelve minutes late?', ['Ask the supervisor to reschedule the fitting', 'Take the next actor’s appointment without notice', 'Attend immediately without the role-specific shoes', 'Wait until the costume room closes for the day'], 0, 'Lateness beyond ten minutes requires an approved new appointment.']),
  daily('daily-field-vehicle', '현장 조사', 'C1', 'Department vehicles may enter the wetland reserve only on the gravel route shown in the permit. The permit covers equipment transport, not passenger pickup. If water reaches the red marker beside the entrance, drivers must leave the vehicle outside the gate even when the route itself appears dry.', ['Under which circumstance must a permitted department vehicle remain outside?', ['When the entrance gauge reaches the stated warning level', 'Whenever scientific equipment occupies the cargo area', 'If passengers have already walked through the reserve', 'When the gravel surface has no visible standing water'], 0, 'The water marker controls access independently of the route’s apparent condition.']),
  daily('daily-translation', '언어 지원', 'B2', 'The writing center reviews translated abstracts for clarity but does not certify legal or medical accuracy. Submit both the source text and the English draft. Requests under 500 words normally take three days; urgent review is available only for conference deadlines documented by an acceptance notice.', ['What must accompany a request for expedited abstract feedback?', ['Evidence of the relevant conference deadline', 'A legal certification from the writing center', 'An English draft exceeding five hundred words', 'Permission to omit the original-language text'], 0, 'Urgency must be supported by the conference acceptance documentation.']),
  daily('daily-ice-rink', '체육 시설', 'B1', 'The campus ice rink closes to recreational skaters at 6 p.m. on Thursday for team practice. Lockers remain accessible until 6:30, but skate rental returns must be completed at the counter before public skating ends.', ['By what time should a rented pair of skates be returned?', ['Before the recreational session ends at six', 'During team practice after the counter reopens', 'At the locker-access deadline of six thirty', 'Any time before Friday morning inspection'], 0, 'Rental returns are due when public skating concludes, earlier than locker closure.']),
  daily('daily-ethics', '연구 윤리', 'C1', 'Adding a new survey question after ethics approval may require an amendment even if the study population is unchanged. Investigators should send the revised instrument to the review office before collecting responses. Correcting spelling or formatting alone can be logged at the next annual update, provided the meaning is unaffected.', ['Which revision can wait until the annual update?', ['A typographical correction that leaves interpretation unchanged', 'A new item asking participants about household income', 'An added procedure involving a different type of risk', 'A rewritten prompt that changes the information requested'], 0, 'Only non-substantive presentation corrections qualify for later reporting.']),
  daily('daily-music-room', '연습실', 'B2', 'A grand piano is available in Practice Room 12 only to students registered for keyboard study. Other musicians may reserve the room but must not move the protective cover. The upright piano in Room 9 remains open to all students with a current music-building access card.', ['Where may a student not enrolled in keyboard study legally use a piano?', ['In Room 9 with valid building access', 'In Room 12 after folding the grand-piano cover', 'In either room without a current access credential', 'In Room 12 whenever no keyboard major is present'], 0, 'The unrestricted instrument is the upright piano, subject to building access.']),
  daily('daily-hazard-waste', '폐기물 안전', 'C1', 'Chemical-waste labels must list actual constituents rather than abbreviations or trade names. When a container becomes full, enter its pickup request in the safety portal and keep it in secondary containment. Placing it in the collection hallway before staff confirm a pickup date violates storage rules.', ['What is the correct procedure for a full waste container?', ['Request collection online while retaining it in secure containment', 'Move it immediately into the hallway to signal readiness', 'Replace the chemical names with a commercial product label', 'Empty it into a larger vessel without updating the record'], 0, 'Portal registration precedes pickup, and controlled storage continues until confirmation.']),
  ...readingGroup('academic-proxies', '고기후학', 'C1', 'Because direct temperature measurements extend back only a limited time, paleoclimatologists use proxies—physical or biological records that vary with climate. Oxygen-isotope ratios in ice, for example, are influenced by temperature, but also by where moisture originated and how air masses traveled. Tree-ring width can reflect growing-season conditions, yet soil nutrients, insects, and tree age also affect growth. Researchers therefore calibrate proxies against overlapping instrumental records and often combine independent archives. Agreement among proxies strengthens a reconstruction, although shared sensitivity to the same nonclimatic factor can still produce misleading convergence.', [
    ['Why does the author discuss several influences on isotope ratios and tree rings?', ['To explain why climatic signals must be separated from other causes', 'To demonstrate that instrumental thermometers predate natural archives', 'To argue that biological records never respond to temperature', 'To show that all proxy types contain identical measurement errors'], 0, 'Each record responds to climate plus possible confounders, so interpretation requires calibration.'],
    ['What is the purpose of comparing proxy records with an overlapping instrumental period?', ['To estimate how the indirect measure relates to observed climate', 'To extend modern weather stations farther into the future', 'To eliminate historical variation from every archive', 'To select only trees that have exceptionally wide rings'], 0, 'Calibration tests the empirical relationship between proxy behavior and measured conditions.'],
    ['Which situation would most weaken confidence based on agreement among proxies?', ['The records respond similarly to one unrelated environmental influence', 'The archives originate in geographically separated locations', 'Their calibrated estimates overlap within a narrow uncertainty range', 'Independent laboratories obtain comparable measurements'], 0, 'Apparent convergence is less informative when a shared confounder can create it.'],
  ]),
  ...readingGroup('academic-markets', '경제인류학', 'B2', 'In many societies, valuable goods circulate through more than one system of exchange. A household might purchase grain with money, trade labor with neighbors, and give ceremonial objects whose receipt creates a future social obligation. Calling all three transactions “markets” can conceal their different rules. Prices coordinate anonymous exchange, whereas reciprocal gifts often depend on durable relationships and expectations that need not be stated. Yet the categories are not sealed: money may appear in a ceremony, and a commercial interaction may gradually create trust. Anthropologists study what participants believe an exchange establishes, not merely which objects change hands.', [
    ['What central distinction does the passage emphasize?', ['Transfers of goods can create different social relationships and duties', 'Ceremonial objects are always more expensive than purchased food', 'Anonymous buyers refuse to participate in reciprocal exchanges', 'Money has disappeared from communities with gift traditions'], 0, 'The same broad act of transfer can operate under distinct rules and consequences.'],
    ['Why does the author say the categories are not sealed?', ['Actual exchanges may combine features associated with different systems', 'Researchers have stopped classifying economic behavior', 'Trust prevents participants from using monetary payment', 'A commercial price always creates a ceremonial obligation'], 0, 'Money, ritual, commerce, and trust can overlap in practice.'],
  ]),
  ...readingGroup('academic-exoplanets', '천체물리학', 'C1', 'One way to detect an exoplanet is to measure the slight dimming of a star when a planet crosses its face. The transit method favors planets whose orbits happen to align with the observer; many real planets never pass between their star and Earth. Large planets close to small stars also produce deeper, easier-to-detect signals. Consequently, the raw catalog is not a representative census. Astronomers estimate detection efficiency by injecting simulated transits into observational data and testing how often their pipeline recovers them. Population claims are then weighted to account for signals the survey would probably have missed, though estimates remain uncertain where sensitivity is especially low.', [
    ['Why is a catalog of detected transits a biased sample?', ['Orbital geometry and signal strength make some planets easier to observe', 'Every planet dims its star by exactly the same amount', 'Simulation removes distant planets from telescope images', 'Small stars cannot host planets with short orbital periods'], 0, 'Alignment and detectability filter the population before it enters the catalog.'],
    ['What does injecting simulated signals allow astronomers to estimate?', ['The proportion of specified events their detection process can recover', 'The chemical composition of planets that never cross a star', 'Whether a real star formed before its surrounding galaxy', 'The exact orbital inclination of every undetected planet'], 0, 'Recovery trials characterize the survey pipeline’s sensitivity.'],
    ['What can be inferred about estimates made in regions of very low sensitivity?', ['They depend heavily on corrections and should carry wider uncertainty', 'They require no assumptions because few signals are recorded', 'They necessarily underestimate the brightness of the host stars', 'They are more precise than estimates from frequently detected events'], 0, 'When detection is rare, correction factors are larger and less securely constrained.'],
  ]),
  ...readingGroup('academic-pigment', '고고화학', 'B2', 'The blue pigment found on some ancient objects can be identified through its mineral structure, but identification alone does not reveal where it was produced. The same mineral may occur in several regions, and artists could reuse older material. Trace elements sometimes provide a geographic signature because deposits formed under different conditions. Even then, archaeologists compare pigment with multiple mines and consider trade routes. A close chemical match supports a source hypothesis; it does not prove that the finished object was manufactured beside that mine.', [
    ['What does the passage identify as a limitation of determining a pigment’s mineral type?', ['The mineral can originate in more than one place', 'Mineral structure disappears immediately after excavation', 'Artists were unable to transport coloring materials', 'Trace elements always indicate the workshop itself'], 0, 'A shared mineral identity does not uniquely specify a geographic deposit.'],
    ['Which conclusion is justified by a strong trace-element match?', ['A proposed raw-material source becomes more plausible, subject to trade evidence', 'The artifact must have been completed at the extraction site', 'No ancient craftsperson could have reused an earlier pigment', 'All chemically different mines can be excluded without sampling'], 0, 'The match is supporting evidence for material provenance, not proof of manufacture location.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the registrar approve your course substitution?', ['Yes, it appeared on my degree audit this morning.', 'The substitute lecturer arrived before noon.', 'I registered the package at the front desk.', 'That course has three weekly readings.'], 0, 'The reply directly reports the approval outcome.'),
  response(1, 'Could you lower the projector screen before the speaker arrives?', ['Certainly, the control switch is beside the podium.', 'The speaker lowered her voice during questions.', 'The project deadline was moved to Friday.', 'I sat in the front row last semester.'], 1, 'The speaker accepts the request and identifies how to complete it.'),
  response(2, 'Why are these samples marked with red tape?', ['The tape measure belongs in the cabinet.', 'Red was the only color in the supply box.', 'They have not yet passed the contamination check.', 'I sampled the northern plot in July.'], 2, 'The marking is explained as a status indicator.'),
  response(3, 'Would you mind reviewing my abstract tonight?', ['The review journal publishes quarterly.', 'Your abstract describes two field sites.', 'Tonight’s lecture was unexpectedly brief.', 'Send it before six, and I can read it after dinner.'], 3, 'The response sets a workable condition for accepting the request.'),
  response(4, 'I thought the workshop included the software license.', ['So did I, but the access code is apparently sold separately.', 'The workshop begins beside the main staircase.', 'Software engineers designed the new entrance.', 'A license can display a photograph and address.'], 0, 'The reply acknowledges and corrects the same assumption.'),
  response(5, 'Where should I leave the borrowed field recorder?', ['Its microphone works best outdoors.', 'Put it in the padded return locker.', 'I recorded the lecture in stereo.', 'The field station closes during winter.'], 1, 'The answer supplies the requested return location.'),
  response(6, 'Haven’t we already submitted the revised budget?', ['The budget committee meets in that building.', 'Revision takes longer than proofreading.', 'We sent the draft, but not the version with signatures.', 'Our submission received the highest score.'], 2, 'The response distinguishes the incomplete draft from the required revision.'),
  response(7, 'The rehearsal room is much warmer than yesterday.', ['Yesterday’s rehearsal lasted nearly two hours.', 'The room contains twelve music stands.', 'I prefer the warmer color in the first photograph.', 'I’ll ask facilities whether the ventilation was turned off.'], 3, 'The reply treats the temperature change as a facilities issue.'),
  response(8, 'Can I cite the dataset before its final release?', ['Only if you label it as the provisional version.', 'The final seminar meets in the data laboratory.', 'Citation styles vary among academic journals.', 'I released the parking brake before driving.'], 0, 'The condition addresses citation of preliminary data.'),
  response(9, 'Why didn’t the committee rank either proposal?', ['The rank of professor requires several publications.', 'Both failed to meet the minimum feasibility criterion.', 'The committee room overlooks the central courtyard.', 'Either proposal could be printed in color.'], 1, 'Failure to clear a threshold explains the absence of ranking.'),
  response(10, 'Should the confidence interval be shown in the caption?', ['The caption was translated into French.', 'Confidence improves with presentation practice.', 'Yes, unless the journal requires it in the figure itself.', 'The interval between buses is fifteen minutes.'], 2, 'The response gives an appropriate recommendation with a relevant exception.'),
  response(11, 'I can’t reconcile these inventory totals.', ['The inventory is stored below the chemistry lab.', 'Totals are printed at the bottom of every receipt.', 'I reconciled with my teammate after the disagreement.', 'Check whether returned items were entered twice.'], 3, 'A duplicate entry is a plausible cause of mismatched totals.'),
  response(12, 'Is the west stairwell still closed?', ['No, the safety inspection ended an hour ago.', 'The western lecture covers migration history.', 'I closed the document without saving it.', 'The stairs are made from reinforced concrete.'], 0, 'The response clearly updates the stairwell’s present status.'),
  response(13, 'When will the microscopy images finish uploading?', ['The microscope uses a different objective lens.', 'At the current rate, shortly after three.', 'I finished labeling the glass slides.', 'Images can reveal very small structures.'], 1, 'The response estimates the requested completion time.'),
  response(14, 'Wouldn’t a pilot interview expose confusing questions?', ['The interview room has soundproof walls.', 'Confusion is common during the first week.', 'Exactly, which is why we should test the protocol now.', 'The pilot announced a delay before landing.'], 2, 'The reply agrees with the methodological reason for piloting.'),
  response(15, 'Who authorized moving the sculpture?', ['The sculpture represents a historical governor.', 'We moved the meeting from Tuesday to Wednesday.', 'Authorization forms are kept for seven years.', 'The collections director signed the transfer order.'], 3, 'The answer identifies the responsible authority.'),
  response(16, 'The grant portal keeps rejecting my attachment.', ['Try exporting it as a smaller PDF before uploading again.', 'The grant covers travel but not ordinary meals.', 'An attachment can make an email easier to understand.', 'I rejected the first estimate as too expensive.'], 0, 'The suggested file conversion directly addresses an upload failure.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-audio', 'Listen to a Conversation', '미디어 과제', 'B2', 'Student: My documentary interview has a loud ventilation hum. Can the media lab remove it? Technician: We can reduce a steady noise, but aggressive filtering may distort the speaker’s voice. Record ten seconds of the room alone next time; that gives the software a cleaner noise profile. For this file, I suggest moderate filtering and captions where a few words remain unclear. Student: I was hoping to submit it tonight. Technician: Leave the file with me now, and I can return a preview by four. You can decide whether the trade-off is acceptable before exporting the final version.', [
    ['Why does the technician advise against aggressive filtering?', ['It could damage the intelligibility or natural quality of the voice', 'The laboratory lacks access to any audio software', 'Captions are prohibited in documentary assignments', 'The student recorded too much silent room tone'], 0, 'Stronger removal may also alter the wanted speech signal.'],
    ['What will the student most likely do next?', ['Provide the file and evaluate a moderately filtered preview', 'Repeat the interview before the laboratory closes', 'Submit an uncaptained final video immediately', 'Purchase a new ventilation system for the room'], 0, 'The technician offers a same-day preview that lets the student judge the compromise.'],
  ]),
  ...listeningGroup('conversation-prerequisite', 'Listen to a Conversation', '수강 계획', 'C1', 'Student: The registration system says I lack the prerequisite for computational linguistics, but I took an equivalent programming course abroad. Advisor: The system cannot recognize external course numbers. Send me the syllabus and a transcript showing the grade. I can recommend a waiver, although the department chair makes the final decision. Student: The class is almost full. Advisor: Join the waitlist today. A waiver will establish eligibility, but it will not reserve a seat. If the chair approves after the class fills, we can discuss the later section.', [
    ['Why does the online system block the student?', ['It cannot automatically match the external course to the prerequisite', 'The student earned an insufficient grade in linguistics', 'The department chair has already denied a formal waiver', 'The later section requires no previous programming'], 1, 'The unfamiliar external course number prevents automatic recognition.'],
    ['What distinction does the advisor emphasize?', ['Meeting the prerequisite and obtaining an available seat are separate issues', 'A transcript can substitute for joining the registration waitlist', 'Only the advisor decides whether foreign coursework is valid', 'The first section and later section use different prerequisites'], 1, 'A waiver grants eligibility but does not guarantee capacity.'],
  ]),
  ...listeningGroup('conversation-freezer', 'Listen to a Conversation', '연구 시설', 'B2', 'Researcher: The freezer alarm sounded overnight, but the display now reads minus eighty. Manager: The temperature log shows it rose to minus fifty for about forty minutes. Do not assume the samples are usable just because the unit recovered. Check each project’s stability protocol and record which rack every vial came from. Researcher: Should I discard them now? Manager: No. Move the racks to the backup unit, label them as quarantined, and let each project leader assess them.', [
    ['Why does the manager reject the current display as sufficient evidence?', ['A temporary warming event may have affected the contents despite recovery', 'The display records only the position of each storage rack', 'Minus eighty is outside the freezer’s normal operating range', 'Every sample must be discarded after an alarm sounds'], 2, 'Present temperature does not erase the earlier excursion.'],
    ['What is the immediate plan for the samples?', ['Analyze every vial before moving the racks', 'Return them to their original projects without labels', 'Transfer and isolate them pending project-specific evaluation', 'Dispose of only the material stored on the upper shelf'], 2, 'Quarantine preserves material while responsible investigators apply their protocols.'],
  ]),
  ...listeningGroup('conversation-exhibit', 'Listen to a Conversation', '박물관 전시', 'C1', 'Student: I designed my exhibit label around the idea that this bowl was used in a royal household. Curator: That interpretation appeared in the old catalog, but it was based only on decoration. Residue analysis now suggests ordinary grain storage. Student: Should I remove the royal interpretation entirely? Curator: Present it as an earlier hypothesis and explain why the evidence changed. That shows visitors how conclusions are revised rather than making the museum look as though it never makes mistakes.', [
    ['How has the evidence about the bowl changed?', ['A functional analysis challenged an inference drawn mainly from appearance', 'A royal document confirmed the object’s original owner', 'The decoration was found to be a recent museum addition', 'Grain residue proved that the bowl was never used'], 3, 'Residue evidence undermines, but does not absolutely negate, the decoration-based royal claim.'],
    ['Why does the curator recommend retaining the older interpretation?', ['To demonstrate the process by which scholarship corrects itself', 'To avoid revising any wording in the existing catalog', 'To persuade visitors that decoration outweighs chemical evidence', 'To conceal uncertainty about the object’s storage location'], 3, 'Contrasting hypotheses makes revision visible and educational.'],
  ]),
  ...listeningGroup('conversation-assistantship', 'Listen to a Conversation', '대학원 재정', 'B2', 'Student: My assistantship letter lists twenty hours, but the laboratory expects me at a Saturday outreach event too. Coordinator: Outreach can count toward the weekly total if your supervisor reduces another assignment. It cannot simply be added as unpaid required work. Send the schedule to your supervisor and copy me. Student: What if the regular experiments cannot be postponed? Coordinator: Then participation must be optional, or the supervisor needs to request additional paid hours in advance.', [
    ['Under what condition can the outreach event be a normal assistantship duty?', ['Another responsibility is reduced so the contracted total is maintained', 'The student volunteers without documenting the weekend time', 'Regular experiments continue and the extra hours remain unpaid', 'The coordinator removes the appointment’s weekly limit'], 0, 'The event may replace, but not silently add to, contracted work.'],
    ['What does the coordinator ask the student to do first?', ['Document the schedule in a message that includes both officials', 'Cancel every experiment scheduled before the outreach event', 'Apply independently for a new assistantship position', 'Attend Saturday and calculate compensation afterward'], 1, 'Sending the schedule with the coordinator copied creates a record and starts resolution.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-water', 'Listen to an Announcement', '캠퍼스 시설', 'B2', 'Tomorrow from nine until noon, water in the north residence complex will be shut off while a main valve is replaced. Fill personal containers beforehand, but do not use laboratory sinks in the adjacent science building for drinking water. Bottled water will be available in each residence lobby. If maintenance finishes early, staff will send a text alert; otherwise service should resume at noon.', [
    ['What are residents advised to do before nine?', ['Store an appropriate personal supply of water', 'Collect drinking water from science laboratories', 'Wait in the lobby until maintenance is complete', 'Turn on every tap to test the replacement valve'], 0, 'Residents should prepare water in advance or use lobby bottles.'],
    ['How will residents learn that service has returned ahead of schedule?', ['Through a message sent by maintenance staff', 'From a notice posted only in the science building', 'By calling the valve manufacturer directly', 'Through an automatic extension of the shutdown'], 0, 'A text alert is promised only if the work ends early.'],
  ]),
  ...listeningGroup('announcement-observatory', 'Listen to an Announcement', '천문대 행사', 'B2', 'Tonight’s public telescope session is proceeding, but high clouds may limit faint-object viewing. Reserved visitors should check in by seven forty-five; unclaimed places enter the standby pool at eight. The dome is unheated, so bring warm clothing. If clouds become too dense for observing, the astronomer will give an indoor demonstration rather than cancel the program.', [
    ['What happens to a reserved place if its holder misses check-in?', ['It may be reassigned to someone waiting', 'It guarantees entry to the indoor lecture only', 'It transfers to the next telescope session', 'It remains protected until the program ends'], 1, 'At eight, unclaimed reservations become available to standby visitors.'],
    ['What will occur if the sky becomes unsuitable?', ['The event will shift to an indoor instructional activity', 'All participants will receive automatic refunds', 'The dome heaters will clear the cloud cover', 'Faint objects will be observed without telescopes'], 1, 'The contingency is a demonstration, not cancellation.'],
  ]),
  ...listeningGroup('announcement-clinic', 'Listen to an Announcement', '보건 서비스', 'C1', 'The travel clinic has added appointments for students departing within six weeks. Before booking, complete the online destination form; the system will then show the appropriate appointment length. Do not select a shorter general consultation merely because it is available sooner, since some vaccinations require records review. Students leaving later than six weeks should use the regular calendar, which opens additional dates every Monday.', [
    ['Why must students submit destination information before choosing a time?', ['It determines how much consultation time their case may require', 'It waives the need to provide previous vaccination records', 'It proves that travel will occur more than six weeks later', 'It grants immediate access to every Monday appointment'], 2, 'Trip-specific requirements control the appointment duration.'],
    ['Who should use the ordinary scheduling calendar?', ['A traveler whose departure is beyond the priority window', 'Anyone seeking the earliest general consultation', 'Only students unable to complete the online form', 'A traveler requiring several immunization records'], 2, 'The added slots target departures within six weeks; later travel uses the regular system.'],
  ]),
  ...listeningGroup('announcement-printmaking', 'Listen to an Announcement', '예술 스튜디오', 'B2', 'The printmaking studio will test a new solvent next week. Students who have completed the standard safety course may observe, but only staff and advanced monitors may handle the solvent during the trial. The south ventilation hood will be reserved for testing, so ordinary cleaning must use the north hood. Report any unusual odor to staff instead of adjusting the airflow controls yourself.', [
    ['Who is permitted to manipulate the new solvent?', ['Designated staff members and qualified advanced monitors', 'Every student who has watched a safety demonstration', 'Visitors accompanied by a standard-course student', 'Anyone working beside the north ventilation hood'], 3, 'Observation eligibility is broader than handling authorization.'],
    ['What should a student do after noticing an unexpected smell?', ['Notify personnel without changing the ventilation settings', 'Move the trial immediately to the cleaning hood', 'Increase airflow using the restricted controls', 'Carry the solvent into an unventilated workspace'], 3, 'Students must report the issue and leave controls to authorized staff.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-endogeneity', 'Listen to an Academic Talk', '계량경제학', 'C1', 'Suppose we observe that neighborhoods with more police also report more crime. It would be a mistake to infer that police presence causes crime, because officers may be assigned precisely where crime is already high. This reverse direction of influence is one form of endogeneity. Researchers seek a source of variation in police deployment that is unrelated to underlying crime risk, or they compare policy changes across otherwise similar locations. Neither strategy is automatically valid; its identifying assumptions must be defended with institutional evidence.', [
    ['Why is the simple correlation difficult to interpret?', ['Deployment can respond to the outcome it is supposed to influence', 'Crime reports never include information about location', 'Police presence is measured only after neighborhoods disappear', 'Institutional evidence cannot describe assignment policy'], 0, 'Reverse causation makes the observed relationship ambiguous.'],
    ['What caution does the lecturer give about alternative research designs?', ['Their causal interpretation rests on assumptions requiring justification', 'They make comparisons across locations mathematically impossible', 'They eliminate the need to understand how policy is implemented', 'Their estimates must always equal the original correlation'], 0, 'A design is credible only if its identifying logic fits the institutional setting.'],
  ]),
  ...listeningGroup('talk-biofilm', 'Listen to an Academic Talk', '미생물생태학', 'B2', 'A biofilm is a community of microorganisms attached to a surface and embedded in a matrix they produce. The matrix retains moisture and can slow the penetration of disinfectants. Cells within the same biofilm also occupy different chemical environments: oxygen may be abundant near the surface but scarce deeper inside. As a result, a treatment effective against freely suspended cells may perform poorly against an established biofilm. Preventing initial attachment can therefore be easier than removing the mature community.', [
    ['How does the matrix help make a biofilm difficult to treat?', ['It creates a partial barrier and supports a protected local environment', 'It forces every cell to remain freely suspended in liquid', 'It supplies equal oxygen concentrations at every depth', 'It converts disinfectants into nutrients immediately'], 1, 'The matrix retains conditions and limits treatment penetration.'],
    ['What practical implication follows from the lecture?', ['Intervening before the community matures may require less effort', 'Only deeper cells need to be exposed to additional oxygen', 'Treatments tested on free cells always work better over time', 'Surface attachment occurs only after complete matrix removal'], 1, 'Early prevention avoids the resistance of an established structure.'],
  ]),
  ...listeningGroup('talk-manuscripts', 'Listen to an Academic Talk', '문헌학', 'C1', 'Medieval manuscripts often survive in copies produced long after an original text was composed. A copyist might correct what seemed like an error, modernize unfamiliar spelling, or accidentally skip from one repeated phrase to another. Textual scholars compare multiple copies and construct a family tree of shared variations. A rare error appearing in two manuscripts can imply common ancestry, but only if one copyist did not directly consult the other. The tree is therefore a hypothesis about transmission, not a mechanical reconstruction of a lost original.', [
    ['Why can a shared unusual mistake be informative?', ['It may indicate that two copies inherited material from a common source', 'It establishes the exact date on which the original was written', 'It proves that copyists never altered unfamiliar spelling', 'It shows that repeated phrases prevent omissions'], 2, 'A distinctive inherited variant can link manuscripts genealogically.'],
    ['What limitation of the family-tree approach is mentioned?', ['Direct borrowing between copies can mimic shared descent', 'Every surviving manuscript necessarily comes from one copyist', 'Modern spelling makes manuscript comparison impossible', 'The method assumes that the original document still exists'], 2, 'Horizontal consultation complicates a simple branching history.'],
  ]),
  ...listeningGroup('talk-wetlands', 'Listen to an Academic Talk', '생태복원', 'B2', 'Restoring a wetland is not simply a matter of planting wetland species. The flow and timing of water determine which plants can persist, how oxygen moves through soil, and whether sediment accumulates or erodes. A project may initially look successful because planted vegetation survives irrigation. If the underlying hydrology remains altered, however, the system can decline once active maintenance stops. Ecologists thus use reference wetlands to set goals but adapt those goals to the constraints of the restored site.', [
    ['Why might an apparently successful planting project later deteriorate?', ['Temporary care can mask an unresolved water-flow problem', 'Reference wetlands prevent vegetation from receiving irrigation', 'Sediment accumulation always eliminates wetland plants', 'Restored sites contain more oxygen than any natural system'], 3, 'Plants may persist under maintenance despite unsuitable hydrology.'],
    ['How are reference wetlands used according to the lecturer?', ['As informative models that still require site-specific adjustment', 'As exact designs that every restoration must duplicate', 'As sources of artificial irrigation after maintenance ends', 'As evidence that hydrology has little ecological importance'], 3, 'Reference conditions guide targets but cannot erase local constraints.'],
  ]),
  ...listeningGroup('talk-pragmatics', 'Listen to an Academic Talk', '화용론', 'C1', 'When a speaker says, “Some of the reports were submitted,” listeners often infer that not all were submitted. Logically, however, “some” is compatible with “all.” The stronger interpretation is a conversational inference: if the speaker knew that all reports arrived and wished to be informative, the more specific word “all” would normally be expected. Context can cancel the inference. A speaker might continue, “In fact, every report was submitted,” without contradicting the literal meaning of the first sentence.', [
    ['Why do listeners commonly interpret “some” as “not all”?', ['They reason that a better-informed speaker would otherwise choose a stronger expression', 'The dictionary definition of “some” explicitly excludes the complete set', 'Every conversational statement must be logically false before clarification', 'Speakers are prohibited from revising claims in a later sentence'], 0, 'The inference depends on expectations of informative word choice.'],
    ['What does the possible continuation demonstrate?', ['The usual implication can be withdrawn without literal contradiction', 'The word “all” is less informative than the word “some”', 'Context never changes how quantity expressions are understood', 'Listeners cannot distinguish semantic content from pronunciation'], 2, 'Cancellation shows that the not-all meaning is pragmatic rather than entailed.'],
  ]),
  ...listeningGroup('talk-dark-matter', 'Listen to an Academic Talk', '우주론', 'C1', 'Astronomers infer dark matter partly from the speed of stars orbiting within galaxies. If visible mass were the only source of gravity, stars far from a galaxy’s center should orbit more slowly than many observations indicate. An extended distribution of unseen mass can account for the relatively flat rotation curve. Yet rotation alone does not identify the substance involved. Other evidence, including gravitational lensing and motions within galaxy clusters, tests whether the same mass model explains independent phenomena.', [
    ['What observation motivates the unseen-mass explanation?', ['Outer stars retain unexpectedly high orbital speeds', 'Visible matter emits increasingly bright light with distance', 'Central stars stop responding to gravitational attraction', 'Galaxy clusters contain no measurable motion'], 1, 'The measured rotation curve stays higher than visible mass predicts.'],
    ['Why does the lecturer mention lensing and galaxy clusters?', ['They provide separate tests of whether the proposed mass distribution is coherent', 'They reveal the chemical formula of dark matter directly', 'They eliminate the need to measure stellar rotation', 'They prove that every galaxy contains equal visible mass'], 3, 'Independent phenomena can corroborate or challenge the inferred model.'],
  ]),
]

const sentenceData: Array<[string, string, string[], string]> = [
  ['Why did the review board postpone approval?', 'Only after', ['the revised protocol', 'had addressed', 'the privacy concern', 'did the board', 'authorize recruitment'], 'f04-only-after-inversion'],
  ['Could the conclusion change?', 'Were additional evidence', ['to contradict', 'the initial estimate', 'we would need', 'to revise', 'our interpretation'], 'f04-inverted-second-conditional'],
  ['Why retain the unsuccessful trials?', 'They reveal', ['conditions under which', 'the method', 'is unlikely', 'to produce', 'reliable measurements'], 'f04-preposition-relative-clause'],
  ['Did the curator authenticate the letter?', 'She could not determine', ['whether it had', 'been written', 'by the person', 'to whom', 'it was attributed'], 'f04-embedded-whether-passive-relative'],
  ['How significant was the temperature effect?', 'So small was', ['the observed difference', 'that it disappeared', 'once the model', 'accounted for', 'seasonal variation'], 'f04-so-fronting-inversion'],
  ['Why use several indicators?', 'No single measure', ['is sufficiently precise', 'for the change', 'to be inferred', 'without supporting', 'evidence'], 'f04-raising-passive-infinitive'],
  ['What did the pilot study suggest?', 'It suggested that', ['had participants', 'received clearer instructions', 'fewer responses', 'would have been', 'excluded'], 'f04-mixed-inverted-conditional'],
  ['Will the archive digitize everything?', 'Much as the staff', ['would like', 'to expand access', 'fragile materials', 'must be handled', 'selectively'], 'f04-concessive-much-as'],
  ['Why is the estimate disputed?', 'What remains uncertain', ['is not whether', 'the glacier retreated', 'but how rapidly', 'the change', 'occurred'], 'f04-pseudo-cleft-correlation'],
  ['Can the variables be compared directly?', 'The units need', ['to be standardized', 'before differences', 'among the samples', 'can be interpreted', 'meaningfully'], 'f04-passive-before-modal'],
]

const writing: BaseItem[] = sentenceData.map(([prompt, starter, fragments, grammarFocus], index) => {
  const item = base(`sentence-${index}`, 'writing', 'sentence-build', 'Build a Sentence', '고급 문장 구조', index < 2 ? 'B2' : 'C1', 75)
  const tiles = prepareSentenceTiles(fragments, item.id)
  return { ...item, instruction: '모든 단어와 구를 한 번씩 사용해 문맥과 문법에 맞는 문장을 완성하세요.', prompt, starter, words: tiles.choices, answer: tiles.answer, grammarFocus, explanation: `${starter} ${tiles.correct.join(' ')}` }
})
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '연구 데이터 관리', 'B2', 420), instruction: '상황과 독자를 고려해 목적과 요청이 분명한 이메일을 작성하세요.', prompt: 'Your research team discovered that several shared files use inconsistent participant codes, and analysis begins in two days. Write to the project coordinator. Describe the inconsistency, explain the risk it creates, and propose a specific verification process before analysis starts.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '과학 정책', 'C1', 600), instruction: '두 학생의 관점을 연결하거나 비판하면서 자신의 입장과 근거를 발전시키세요.', prompt: 'Professor Mensah: When evidence is incomplete but delay also has costs, how should governments decide whether to regulate a new technology?', passage: 'Priya: Regulators should act early when potential harm is difficult to reverse, even if every mechanism is not yet proven.\nDaniel: Premature rules can lock in mistaken assumptions and prevent socially valuable experimentation.' })

const repeatSentences = [
  'Thank you for joining today’s river survey.',
  'Check that your sample bottles match the site numbers.',
  'We will begin upstream and work toward the footbridge.',
  'Rinse the probe with clean water between every measurement.',
  'Write unusual weather or water conditions beside the numerical reading.',
  'If the bank becomes unstable, step back and alert the group leader.',
  'Before departure, we will compare the inventory with the field log and secure every sample cooler.',
]
const interviewQuestions = [
  'Describe a time when new evidence caused you to change your opinion.',
  'How do you decide whether a source of information is credible?',
  'Why might reasonable people interpret the same evidence differently?',
  'Should uncertainty make decision makers postpone action, or can it justify acting sooner?',
]
const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '하천 수질 조사', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f04-repeat', scenarioId: 'f04-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '증거와 의사결정', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '같은 주제로 이어지는 질문에 주장, 이유, 구체적 사례를 들어 답하세요.', audioText, stimulusGroupId: 'f04-interview', scenarioId: 'f04-interview', sequenceIndex })),
]

export const AUTHORED_FORM_04_ITEMS: BaseItem[] = [
  ...reading.slice(0, 11).map((item) => ({ ...item, module: 1 })),
  ...reading.slice(11).map((item) => ({ ...item, module: 2 })),
  ...responses.slice(0, 9).map((item) => ({ ...item, module: 1 })),
  ...conversations.slice(0, 5).map((item) => ({ ...item, module: 1 })),
  ...announcements.slice(0, 4).map((item) => ({ ...item, module: 1 })),
  ...talks.slice(0, 6).map((item) => ({ ...item, module: 1 })),
  ...responses.slice(9).map((item) => ({ ...item, module: 2 })),
  ...conversations.slice(5).map((item) => ({ ...item, module: 2 })),
  ...announcements.slice(4).map((item) => ({ ...item, module: 2 })),
  ...talks.slice(6).map((item) => ({ ...item, module: 2 })),
  ...writing,
  ...speaking,
]

export const AUTHORED_FORM_04_IDS = AUTHORED_FORM_04_ITEMS.map((item) => item.id)
