import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f15')

const reading: BaseItem[] = [
  cloze('cloze-fractionation', '동위원소지구화학', 'C1', 'Isotopes of one element share chemical properties but differ in mass. During physical or chemical reactions, lighter and heavier isotopes may part___ at slightly different rates, a process called fractionation. Evaporation often fav___ lighter water molecules, leaving the remaining liquid relatively enriched in heavier isotopes. Condensation then rem___ heavier molecules preferentially. Scientists mea___ isotope ratios against standards and use the pattern to inf___ temperature, water source, or biological process. The signal is rarely unique. Mixing, later alteration, and multiple reaction steps can mod___ the original ratio. Researchers therefore constr___ mass-balance models and analyze complementary tracers. Calibration samples help quan___ systematic offsets, while uncertainty propagation prevents small analytical errors from being ampl___ into overly precise environmental claims that the data cannot sup___.', 'ition|ors|oves|sure|er|ify|uct|tify|ified|port'),
  cloze('cloze-biofilm', '미생물생태학', 'C1', 'A biofilm is a community of microorganisms attached to a surface and embedded in a self-produced matrix. The matrix ret___ water and nutrients, medi___ adhesion, and can slow the penetration of disinfectants. Cells within one biofilm exper___ different oxygen and nutrient conditions, so their metabolisms div___. Some enter slow-growing states that tol___ stresses better than rapidly dividing cells. Biofilms are not simply random accumulations: chemical signals and spatial competition infl___ development. They can benefit wastewater treatment but cau___ persistent infections or industrial fouling. Researchers image layers, sample gene expression, and test flow conditions. Removing visible material may not erad___ cells in microscopic crevices. Effective control often comb___ mechanical disruption with chemistry suited to the surface and org___ involved.', 'ains|ates|ience|erge|erate|uence|se|icate|ines|anisms'),
  cloze('cloze-papermaking', '기술사', 'B2', 'Traditional paper is made by suspending plant fibers in water and lifting them on a screen. As water dra___, fibers overlap and form a sheet. Beating the pulp fibr___ fiber surfaces, increasing bonding but sometimes reducing porosity. Sizing can lim___ ink absorption, while fillers alter color and texture. Handmade sheets often rev___ chain lines from the mold. Historians exam___ fiber species, watermarks, dimensions, and surface treatment to study production and trade. A watermark may ind___ a mold or workshop, but paper could travel far before use. Repair tissues should be comp___ in strength and aging behavior. Excessively rigid patches can conc___ stress at their edges. Conservators doc___ interventions because later scholars may otherwise mis___ modern additions for original manufacture.', 'ins|illates|it|eal|ine|icate|atible|entrate|ument|take'),
  daily('daily-cleanroom', '반도체 클린룸', 'B2', 'Cleanroom garments are issued in sealed bags by size. If a bag is open but the garment was not worn, place it in the inspection bin rather than returning it to the sterile shelf. Staff must verify packaging integrity before reissue.', ['Where should an opened, unused garment be placed?', ['In the designated inspection bin for integrity checking', 'Back among sealed garments of the same size', 'Inside the personal locker for the next visitor', 'On the equipment shelf beside processed wafers'], 0, 'Opening breaks the verified sterile chain.']),
  daily('daily-manuscript-request', '고문서 열람', 'C1', 'Requests for restricted manuscripts close at three on the preceding business day. A catalog request marked “submitted” is not yet approved; researchers should wait for a confirmation naming the reading-room desk. Travel plans do not create an exception to conservation limits.', ['What shows that a restricted request is ready?', ['A confirmation identifying the assigned service desk', 'The initial submitted status in the online catalog', 'Evidence that the researcher traveled from another city', 'A request entered after the previous business day’s cutoff'], 0, 'Approval is communicated through a specific confirmation.']),
  daily('daily-drone', '무인기 조사', 'B2', 'A campus drone permit authorizes a location and altitude range, not unrestricted flight throughout the approval period. Operators must still check temporary airspace notices and ground conditions before each launch. A permit should be amended if the takeoff point moves outside the mapped boundary.', ['Why must an approved operator check notices before every launch?', ['Temporary restrictions may supersede the standing location permit', 'The approved altitude changes automatically after each flight', 'Ground conditions are evaluated only when the permit expires', 'Moving within the mapped boundary always requires a new application'], 0, 'Standing approval does not override time-specific restrictions.']),
  daily('daily-seed-bank', '종자은행', 'B2', 'Seed-bank packets may be opened only inside the low-humidity workroom. Count discrepancies must be recorded before any seeds are removed for germination. Returning unused seeds to the original packet is prohibited once they have entered an uncontrolled environment.', ['When should a quantity discrepancy be documented?', ['Before material is withdrawn for a germination test', 'After unused seeds have been returned from the greenhouse', 'Only when the packet contains a commercial species', 'Once the low-humidity room has closed for the day'], 0, 'The baseline count must precede removal.']),
  daily('daily-preread', '대학원 세미나', 'B2', 'Discussion leaders upload a two-page guide by noon Monday. The guide should identify a disputed claim and two passages worth analyzing; it should not summarize every section. Late guides are circulated, but the author loses priority when choosing a presentation date.', ['What distinguishes the required guide from a full summary?', ['It selects a controversy and targeted textual evidence', 'It reproduces every section in chronological order', 'It omits passages that seminar members could discuss', 'It determines the author’s final course grade automatically'], 0, 'The task is analytical selection, not comprehensive synopsis.']),
  daily('daily-microscope', '공초점 현미경', 'B2', 'A booking includes fifteen minutes for exporting data and cleaning the objective. Users who need longer acquisition should reserve contiguous blocks; overrunning into another booking triggers an incident report even when the next user has not yet arrived.', ['Why should long experiments use consecutive reservations?', ['The cleanup and export interval must remain within authorized time', 'An absent next user transfers ownership of the schedule', 'Incident reports are issued only for short acquisitions', 'Objective cleaning can occur while another user is imaging'], 0, 'The full workflow is bounded by the reserved period.']),
  daily('daily-translation-consent', '다언어 연구', 'C1', 'A participant may sign a translated consent form only after the research team verifies that it matches the currently approved source version. An interpreter may explain unfamiliar terms but cannot improvise new risks or benefits. Any substantive clarification must be reviewed and added consistently to both versions.', ['What requires formal review?', ['A clarification that changes the substantive description of participation', 'An interpreter restating an approved term in ordinary speech', 'A participant asking to pause before signing the document', 'The use of an already verified translated source version'], 0, 'Material additions must remain approved and aligned across languages.']),
  daily('daily-inventory', '화학물질 관리', 'B2', 'The annual chemical inventory records each container, including empty cylinders awaiting pickup. Containers found without an owner are labeled for investigation, not immediately discarded. Disposal begins only after safety staff identify contents or apply the unknown-material procedure.', ['Why are ownerless containers not discarded at once?', ['Their contents and required disposal route must first be established safely', 'Empty cylinders are excluded from every annual inventory', 'An ownership label guarantees that a chemical is nonhazardous', 'Investigating a container removes it from the storage record'], 0, 'Unknown materials require controlled identification.']),
  daily('daily-accommodation', '시험 지원', 'B2', 'Students approved for extra testing time must reserve an accessibility-center seat at least four days before the exam. Instructor notification alone does not reserve space. If the center is full, it coordinates an equivalent supervised room rather than canceling the accommodation.', ['What does notifying the instructor fail to accomplish?', ['It does not secure a testing location through the accessibility center', 'It cancels previously approved additional examination time', 'It prevents the center from arranging an equivalent room', 'It replaces the four-day booking requirement with same-day entry'], 0, 'Approval and physical scheduling are separate.']),
  daily('daily-doi', '데이터 출판', 'B2', 'A dataset DOI should point to a stable release, not a folder that changes silently. Corrections after publication require a new version linked to the original record. Minor metadata spelling fixes may update in place, but altered values or files must remain traceable through version history.', ['Which change requires a new dataset version?', ['Replacing published values with corrected analytical results', 'Fixing a typographical error in the descriptive metadata', 'Adding a link that points back to the same release', 'Reformatting an author name without changing data files'], 0, 'Substantive data changes need an auditable release.']),
  ...readingGroup('academic-instruments', '계량경제학', 'C1', 'An instrumental variable can identify a causal effect when treatment is confounded, but only under demanding assumptions. The instrument must influence treatment, be independent of unmeasured causes of the outcome, and affect the outcome only through treatment. A weak instrument produces unstable estimates even when the other assumptions hold. In many applications, the estimate describes a local effect for people whose treatment changes because of the instrument, not an average effect for everyone. Statistical tests can assess relevance, yet the exclusion restriction usually depends on substantive argument. Merely finding a variable correlated with treatment does not make it a valid instrument.', [
    ['Why is correlation with treatment insufficient for instrument validity?', ['The candidate may also influence the outcome through another pathway or share hidden causes', 'A valid instrument must have no relationship whatsoever with treatment uptake', 'Instrumental estimates require every person to respond identically to treatment', 'Statistical relevance automatically proves the exclusion restriction'], 0, 'Relevance is only one identification condition.'],
    ['What problem arises from a weak instrument?', ['The causal estimate can become highly variable and sensitive to small data changes', 'The treatment necessarily loses all effect on the measured outcome', 'Unmeasured confounding is eliminated more completely than with a strong instrument', 'The local effect becomes an exact population average'], 0, 'Low first-stage information destabilizes inference.'],
    ['Why might the resulting effect be called local?', ['It pertains to individuals whose treatment behavior is shifted by the instrument', 'It applies only to outcomes measured near the research laboratory', 'It excludes every participant who complied with their assigned condition', 'It estimates solely the direct effect of the instrument itself'], 0, 'Identification can target instrument-responsive compliers.'],
  ]),
  ...readingGroup('academic-eusociality', '진화생물학', 'C1', 'Eusocial animal societies feature overlapping generations, cooperative care of young, and a reproductive division of labor. Sterile workers appear puzzling under a simple view of individual reproduction, but inclusive fitness includes effects on relatives who share genes. Relatedness alone, however, does not guarantee eusociality. Ecological conditions must make helping sufficiently beneficial, and conflicts remain over sex allocation, reproduction, and colony resources. Haplodiploid inheritance in many ants and bees can raise sister relatedness under particular conditions, yet termites are diploid and many haplodiploid species are solitary. Comparative studies therefore test interacting genetic and ecological explanations.', [
    ['How can sterile helping behavior contribute to evolutionary success?', ['It can increase reproduction by relatives carrying copies of the helper’s genes', 'It makes genetic relatedness irrelevant to natural selection', 'It guarantees that workers later inherit the queen’s role', 'It eliminates competition over resources inside the colony'], 0, 'Indirect genetic transmission contributes to inclusive fitness.'],
    ['Why does haplodiploidy not fully explain eusociality?', ['The inheritance system occurs without sociality, while eusociality also evolved under diploidy', 'Haplodiploid sisters never share more genes than unrelated individuals', 'Every termite colony lacks cooperative care and overlapping generations', 'Genetic systems determine ecology without any interaction'], 0, 'Contrasting cases show the factor is neither sufficient nor necessary.'],
  ]),
  ...readingGroup('academic-cuneiform', '고대행정사', 'C1', 'The earliest cuneiform tablets often record grain, livestock, labor, and institutional allocations rather than literary narratives. Their signs developed from administrative notation, but interpretation is difficult because a quantity may use different numerical systems depending on what was counted. Sealed envelopes and impressed tokens show that verification and accountability mattered. Archives are not neutral samples of ancient life: institutions preserved records useful to their operations, while household exchanges may leave little trace. When tablets are found outside documented excavation contexts, scholars lose information about rooms, associated objects, and chronological layers that could clarify their function.', [
    ['Why can the same written quantity be interpreted differently?', ['Numerical notation could depend on the category of commodity being recorded', 'Scribes refused to represent grain and labor on one tablet', 'Every sign had one fixed literary meaning from the beginning', 'Sealed envelopes eliminated the need to count physical goods'], 0, 'Metrological context determines numerical value.'],
    ['What bias affects conclusions drawn from tablet archives?', ['Institutional preservation overrepresents transactions important to administrative bodies', 'Household activity was legally required to use more durable records', 'Literary narratives constitute all surviving early tablets', 'Excavation context cannot contribute to functional interpretation'], 0, 'The documentary record reflects producers and survival processes.'],
    ['Why is an undocumented find location damaging?', ['It removes spatial and stratigraphic relationships needed to interpret use and date', 'It changes the clay signs into a different numerical system', 'It proves the tablet belonged to a private household', 'It prevents scholars from recognizing any written symbol'], 0, 'Context links an artifact to activities and chronology.'],
  ]),
  ...readingGroup('academic-superconductors', '응집물질물리학', 'C1', 'Below a critical temperature, a superconductor carries direct current without ordinary electrical resistance and expels magnetic flux through the Meissner effect. Zero resistance alone does not capture the full state: an ideal perfect conductor that merely trapped an existing magnetic field would behave differently during cooling. Type II superconductors admit magnetic flux in quantized vortices between two critical fields, enabling operation under stronger fields. Motion of those vortices dissipates energy, so material defects that pin them can improve practical current capacity. Very high critical temperature is valuable, but engineering also depends on brittleness, cooling cost, field tolerance, and fabrication into useful shapes.', [
    ['Why is the Meissner effect conceptually important?', ['It distinguishes superconducting magnetic behavior from simple perfect conductivity', 'It shows that superconductors retain every initial magnetic field unchanged', 'It guarantees zero energy loss under any alternating current', 'It defines the temperature at which ordinary metals melt'], 0, 'Flux expulsion characterizes the thermodynamic state.'],
    ['How can structural defects improve a Type II superconductor?', ['They can immobilize vortices whose movement would otherwise cause dissipation', 'They raise resistance so current remains below a safe value', 'They eliminate both critical magnetic fields from the material', 'They convert direct current into a trapped external field'], 0, 'Pinning suppresses a key loss mechanism.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did you verify the incubator’s carbon-dioxide reading?', ['Yes, against the independent handheld sensor.', 'The incubator contains six culture shelves.', 'Carbon dioxide dissolves readily in water.', 'I read the revised protocol this afternoon.'], 0, 'The response confirms an independent check.'),
  response(1, 'Why was the visiting lecture removed from the calendar?', ['The lecturer studies constitutional history.', 'The speaker’s travel authorization was delayed.', 'I removed duplicate events from my own calendar.', 'Lecture recordings remain available for one semester.'], 1, 'A travel constraint explains the removal.'),
  response(2, 'Could the missing values be informative rather than random?', ['The values were entered in separate spreadsheet columns.', 'Missing-data methods require explicit assumptions.', 'Yes, dropout may depend on an unobserved outcome.', 'I informed the project manager about the damaged file.'], 2, 'Outcome-dependent dropout is informative missingness.'),
  response(3, 'I assumed the field station supplied waterproof notebooks.', ['The station is located above the seasonal floodplain.', 'Waterproof ink can withstand brief immersion.', 'I supplied the coordinates with the permit application.', 'Only protective covers are provided; bring your own notebooks.'], 3, 'The response distinguishes supplied gear from required personal items.'),
  response(4, 'May we examine the seal under ultraviolet light?', ['Only after conservation confirms the exposure limit.', 'The seal contains an image of a winged animal.', 'Ultraviolet wavelengths are shorter than visible light.', 'I examined the regression residuals yesterday.'], 0, 'The method needs conservation authorization.'),
  response(5, 'Where can I find the codebook for wave three?', ['The third wave included an additional age group.', 'Beside the archived release in the documentation folder.', 'Codebooks define variable meanings and response values.', 'I found three coding errors in the import script.'], 1, 'The answer identifies the documentation location.'),
  response(6, 'Shouldn’t we randomize the order of these stimuli?', ['The stimuli contain photographs and short sentences.', 'Order effects can be estimated in the final model.', 'Yes, unless sequence is itself the experimental manipulation.', 'I ordered replacement electrodes from the supplier.'], 2, 'Randomization is appropriate unless order defines treatment.'),
  response(7, 'The temperature logger skipped the first hour.', ['The logger stores records on removable memory.', 'Temperature rose gradually after sunrise.', 'I skipped the introduction and read the results first.', 'Mark the gap and inspect startup diagnostics before interpolating.'], 3, 'Diagnostics should precede imputation.'),
  response(8, 'Is the archive transcription considered a citable edition?', ['Not until the editorial review and version release are complete.', 'The edition contains three previously unknown letters.', 'Transcription conventions are explained in the preface.', 'I cited the archival box and folder in my notes.'], 0, 'Draft status limits authoritative citation.'),
  response(9, 'Why did the colony’s food consumption suddenly fall?', ['The colony occupies the upper chamber of the enclosure.', 'A humidity alarm coincided with the behavioral change.', 'I consumed less storage after compressing the images.', 'Food consumption is reported in grams per day.'], 1, 'The coincident environmental event suggests a cause to investigate.'),
  response(10, 'Can the instrument distinguish those two mineral phases?', ['The phases formed at different pressures.', 'The instrument uses a monochromatic beam.', 'Only if their diagnostic peaks exceed the spectral resolution.', 'I distinguished the revised samples with colored caps.'], 2, 'Resolving features depends on instrument resolution.'),
  response(11, 'I cannot reconcile the invoice with the purchase order.', ['The order includes replacement parts for two microscopes.', 'Invoices must list institutional billing information.', 'I reconciled two spelling variants in the database.', 'Compare the partial shipment notice; one item was back-ordered.'], 3, 'Shipment status can explain the amount mismatch.'),
  response(12, 'Has the ethics amendment covered passive location logging?', ['Not yet; the committee asked for a clearer retention period.', 'Location sensors sample at five-minute intervals.', 'The amendment includes a revised recruitment poster.', 'I covered the receiver with a weatherproof case.'], 0, 'The reply states pending approval and its reason.'),
  response(13, 'When will the digitized maps become searchable?', ['The maps use several historical coordinate systems.', 'After the geographic metadata are quality-checked next month.', 'I searched the catalog by cartographer name.', 'Digitization reduces handling of fragile originals.'], 1, 'Search availability follows metadata verification.'),
  response(14, 'Would matching reduce baseline imbalance?', ['Baseline measurements occurred before treatment assignment.', 'Matching selects observations with similar measured covariates.', 'It could, though it cannot balance causes that were never measured.', 'I matched the specimen number to the shipping label.'], 2, 'Matching addresses observed, not hidden, imbalance.'),
  response(15, 'Who is responsible for the unlabeled gas cylinder?', ['The cylinder stands behind the ventilation cabinet.', 'Responsibility transfers when the delivery form is signed.', 'The label should list both contents and hazard class.', 'Safety staff are tracing it through the supplier serial number.'], 3, 'The responsible team is identified through its action.'),
  response(16, 'This photograph seems too blue compared with the object.', ['View the color target under the same calibrated workflow before correcting it.', 'The object was excavated near a blue-painted wall.', 'Photographs appear in the catalog by accession number.', 'I compared the argument with a recent review article.'], 0, 'A reference target diagnoses color-management error.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-blank', 'Listen to a Conversation', '단백질 분석', 'C1', 'Student: The control lane contains the same faint band as every treated sample. Supervisor: What was in the control? Student: Buffer went through the extraction column, but no tissue. Supervisor: Good. The shared band may come from a reagent or column rather than the specimens. Run an unopened reagent lot and a column-free buffer control before subtracting anything from the sample measurements.', [
    ['What does the control lane suggest?', ['A component of the processing workflow may generate the band', 'Every tissue sample contains an identical biological protein', 'The extraction column removed all detectable material', 'The treated specimens were never placed in buffer'], 0, 'A signal without tissue implicates background contamination or chemistry.'],
    ['Why request two additional controls?', ['They can separate reagent background from an effect introduced by the column', 'They increase the concentration of protein in every sample lane', 'They justify deleting the faint band without further evidence', 'They determine which tissue received the treatment'], 0, 'The controls isolate stages of the workflow.'],
  ]),
  ...listeningGroup('conversation-translation', 'Listen to a Conversation', '문학 번역', 'C1', 'Student: Two translations render the same metaphor very differently. Should I decide which is more accurate? Professor: First identify what each version prioritizes. One preserves the image but sounds strange; the other replaces it with an idiom familiar to modern readers. Student: So accuracy has more than one dimension? Professor: Exactly. Compare their effects and historical audiences before treating literal similarity as the only criterion.', [
    ['What contrast does the professor identify?', ['Preserving the source image versus producing familiar target-language expression', 'Translating a metaphor versus omitting the passage entirely', 'Using a historical audience versus identifying the original author', 'Choosing between two versions with identical stylistic effects'], 0, 'The translations optimize different kinds of equivalence.'],
    ['What broader point does the professor make about accuracy?', ['It depends on purpose, effect, and audience as well as lexical closeness', 'It can be measured solely by counting matching words', 'It requires every metaphor to become a modern idiom', 'It is irrelevant when translations have different dates'], 0, 'Translation quality is multidimensional.'],
  ]),
  ...listeningGroup('conversation-linkage', 'Listen to a Conversation', '행정 데이터', 'C1', 'Analyst: I linked hospital and employment records by name and birth date, but some people have multiple possible matches. Manager: Do not choose the closest spelling manually. Estimate linkage uncertainty and preserve candidate pairs. Analyst: But the outcome model expects one row per person. Manager: Then use a linkage method that propagates match probabilities or report sensitivity across defensible match rules.', [
    ['Why does the manager oppose manual selection?', ['An apparently plausible match can hide uncertainty and subjective bias', 'Names and birth dates can never identify any corresponding record', 'Outcome models require every source file to contain duplicate people', 'Spelling differences prove that two records belong to one person'], 0, 'Ambiguity should be represented rather than concealed.'],
    ['What should the final analysis incorporate?', ['Variation arising from uncertain links between records', 'Only the candidate pair with the longest matching name', 'A guarantee that every person has exactly one hospital record', 'Deletion of outcomes for all correctly linked individuals'], 0, 'Linkage uncertainty affects downstream estimates.'],
  ]),
  ...listeningGroup('conversation-glaze', 'Listen to a Conversation', '도자기 보존', 'B2', 'Curator: This repaired bowl fluoresces differently along the rim. Conservator: That may reveal an old adhesive, but some original glazes fluoresce too. Curator: Should we remove the bright area? Conservator: Not on fluorescence alone. Map the response, compare known repairs, and sample only if the research value justifies taking material.', [
    ['Why is fluorescence alone inconclusive?', ['Both restoration material and original glaze can produce the observed response', 'Every old adhesive is invisible under the examination light', 'Sampling cannot distinguish a glaze from any repair', 'The rim was manufactured from a different ceramic body'], 0, 'The signal is not unique to one material class.'],
    ['What principle guides whether to sample?', ['The expected knowledge must justify irreversible material removal', 'A visually bright region should always be removed immediately', 'Known repairs eliminate the need for comparative mapping', 'Curatorial interest automatically permits destructive testing'], 0, 'Destructive analysis requires proportional benefit.'],
  ]),
  ...listeningGroup('conversation-attendance', 'Listen to a Conversation', '강의 참여 자료', 'B2', 'Instructor: My attendance app marks students absent when they join from the overflow room. Coordinator: The Bluetooth beacon does not reach through that wall. Instructor: Can I edit the records? Coordinator: Yes, use the room-entry log for past sessions. For future classes, add the second beacon rather than asking students to check in from the corridor.', [
    ['What caused the inaccurate attendance?', ['The location signal failed to cover the overflow room', 'Students entered without signing the room log', 'The instructor deleted records after every class', 'The application counted corridor check-ins as present'], 0, 'The beacon’s range excluded a legitimate location.'],
    ['How should earlier records be corrected?', ['Use the independent entry log as supporting evidence', 'Install a future beacon and infer every past attendee', 'Require students to stand in the corridor retroactively', 'Remove attendance from the course requirements'], 0, 'The log documents historical room access.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-foundry', 'Listen to an Announcement', '주조 실습실', 'B2', 'The metal foundry closes Thursday morning for ventilation balancing. Cold-work benches remain available, but no torch, furnace, or grinding operation may begin until the green clearance notice is posted. Projects cooling from Wednesday may stay inside if they are labeled with the owner and alloy.', [
    ['Which activity may continue during the closure?', ['Nonpowered cold work at the designated benches', 'Grinding before the clearance notice appears', 'Starting a furnace with the exhaust system unbalanced', 'Using an unlabeled cooling project from Wednesday'], 0, 'The restriction targets heat and airborne-particle processes.'],
    ['What condition applies to projects left cooling?', ['They must identify both the responsible person and material', 'They need to be removed before Wednesday evening', 'They may restart automatically on Thursday morning', 'They must contain no metal alloy information'], 0, 'Clear labeling permits safe retention.'],
  ]),
  ...listeningGroup('announcement-voting', 'Listen to an Announcement', '학생회 선거', 'B2', 'Online voting opens at eight Tuesday and closes at six Wednesday. Students whose enrollment was activated after the voter list froze may cast a provisional ballot at the student center. Provisional status concerns eligibility verification; those ballots are counted once enrollment is confirmed, not automatically excluded.', [
    ['Who should use the provisional-ballot process?', ['A student added after the eligibility list was finalized', 'Every voter participating before the online system opens', 'Candidates whose enrollment ended in the previous term', 'Anyone preferring paper regardless of voter-list status'], 0, 'Late activation may be absent from the frozen list.'],
    ['What happens to a provisional ballot?', ['It is included after the voter’s eligibility is verified', 'It is discarded solely because it was submitted in person', 'It counts twice if enrollment began after Tuesday', 'It remains unexamined until the next annual election'], 0, 'Provisional means pending verification, not invalid.'],
  ]),
  ...listeningGroup('announcement-ice-core', 'Listen to an Announcement', '빙하 시료', 'C1', 'The ice-core shipment reaches the cold laboratory Friday at seven. Only staff named on the custody plan may unload it. Backup personnel should remain reachable but must not enter the receiving bay unless called, because additional bodies raise room temperature. The temperature record begins before the truck opens and continues until every core reaches assigned storage.', [
    ['Why are backup staff asked to remain outside initially?', ['Unnecessary personnel would add heat to the controlled receiving space', 'They lack permission to be contacted during the shipment', 'The truck can open only after every employee enters', 'Assigned storage is located outside the cold laboratory'], 0, 'Occupancy affects thermal control.'],
    ['How long must shipment temperature monitoring continue?', ['Through transfer of all cores into their designated storage locations', 'Only until the truck arrives at the laboratory entrance', 'From unloading until the first sample label is read', 'After cores thaw enough to permit visual inspection'], 0, 'The entire custody transition is monitored.'],
  ]),
  ...listeningGroup('announcement-festival', 'Listen to an Announcement', '언어 문화제', 'B1', 'The language festival moves indoors if rain begins before noon. Food stalls will use the student union, while performances move to the theater. Volunteers should check the event message at eleven thirty and report directly to the listed indoor or outdoor station rather than gathering at the original lawn.', [
    ['When should volunteers check their assignment?', ['At eleven thirty before reporting to the indicated station', 'Only after all performances have ended', 'When the food stalls close inside the union', 'Before the weather is assessed on festival morning'], 0, 'The update time determines the active plan.'],
    ['What should volunteers avoid doing?', ['Meeting first at the lawn despite the posted station', 'Working at a food stall inside the student union', 'Reporting to the theater when indoor performances are listed', 'Reading the event message before noon'], 0, 'Direct reporting prevents unnecessary congregation at the old site.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-upwelling', 'Listen to an Academic Talk', '해양학', 'C1', 'Coastal upwelling occurs when winds and Earth’s rotation drive surface water away from shore, allowing deeper water to rise. That water is often cold and rich in nutrients accumulated from decomposition. Nutrients support phytoplankton and productive fisheries, but strong upwelling can also bring low-oxygen, acidic water into coastal habitats. Biological effects therefore depend on duration, source depth, and local circulation. Satellite surface temperature reveals broad patterns, while subsurface instruments are needed to measure oxygen and carbonate chemistry directly.', [
    ['Why can upwelling have both beneficial and harmful effects?', ['It supplies nutrients while potentially exposing organisms to low oxygen and acidity', 'Cold water prevents all phytoplankton from using dissolved nutrients', 'Surface winds remove every decomposed substance from the ocean', 'Productive fisheries require oxygen-free coastal habitats'], 0, 'The same source water carries resources and stressors.'],
    ['Why are satellite observations insufficient by themselves?', ['Surface patterns do not directly measure crucial subsurface chemical conditions', 'Satellites cannot detect any difference in ocean temperature', 'Local circulation occurs only above the water surface', 'Carbonate chemistry is identical at all depths'], 0, 'Key mechanisms occur beneath the remotely sensed layer.'],
  ]),
  ...listeningGroup('talk-taxes', 'Listen to an Academic Talk', '공공경제학', 'C1', 'The statutory incidence of a tax identifies who sends payment to the government, but economic incidence describes who ultimately bears the burden. If demand is relatively insensitive to price while supply is flexible, consumers may bear much of a tax formally collected from sellers. Wages, rents, and product prices can transmit burdens beyond the named payer. Estimating incidence requires a counterfactual and attention to market adjustment over time; observing that firms write the checks does not establish that their owners absorb the cost.', [
    ['Why can consumers bear a tax remitted by sellers?', ['Market price adjustment can transfer burden toward the less responsive side', 'Statutory law requires buyers to reimburse every business directly', 'Flexible supply prevents any change in the product price', 'Economic incidence is defined by who completes the tax form'], 0, 'Elasticities shape equilibrium burden.'],
    ['What mistake does the lecturer warn against?', ['Equating the legal remitter with the party experiencing the economic loss', 'Examining how wages and rents change after taxation', 'Constructing a counterfactual without the policy', 'Allowing market responses to evolve through time'], 0, 'Payment mechanics do not reveal ultimate incidence.'],
  ]),
  ...listeningGroup('talk-sleep', 'Listen to an Academic Talk', '신경과학', 'C1', 'During sleep, the brain cycles through stages with different electrical patterns and physiology. Slow-wave sleep has been associated with consolidation of declarative memory, while rapid-eye-movement sleep may contribute to emotional and procedural processing. These associations are not a simple division of labor. Memories interact, stages recur, and experimental disruption can cause stress or compensation. Targeted memory reactivation presents a cue during sleep to bias processing of a learned item, but benefits depend on timing and may trade off with uncued material.', [
    ['Why should sleep stages not be assigned one exclusive memory function each?', ['Processing overlaps across recurring stages and experimental interventions have secondary effects', 'Declarative memories are erased whenever rapid eye movement begins', 'Each night contains only one stage of measurable brain activity', 'Procedural learning occurs independently of all sleep physiology'], 0, 'The relationship is distributed and experimentally confounded.'],
    ['What limitation of targeted reactivation is mentioned?', ['Enhancing cued information may occur at the expense of other memories', 'Cues can be presented only while a participant is awake', 'Timing has no influence on whether a cue affects processing', 'The method measures memory without altering it'], 0, 'Selective benefit may redistribute limited processing.'],
  ]),
  ...listeningGroup('talk-wood', 'Listen to an Academic Talk', '재료보존학', 'B2', 'Wood changes dimension as it gains or loses bound water from its cell walls. Movement differs along the grain, across growth rings, and tangentially, which is why boards can warp or split. Coatings slow moisture exchange but rarely stop it completely. Furniture makers orient grain and allow joints to move rather than rigidly restraining every part. Conservators stabilize relative humidity because repeated fluctuations can fatigue joints and decorated surfaces.', [
    ['Why are dimensional changes uneven?', ['Wood anatomy produces direction-dependent responses to moisture', 'Every coating removes water from only one end of a board', 'Growth rings prevent cell walls from binding any water', 'Rigid joints make grain orientation uniform'], 0, 'Anisotropic structure yields unequal expansion.'],
    ['Why can a movable joint improve durability?', ['It accommodates seasonal dimensional change without concentrating stress', 'It prevents humidity from reaching the furniture surface', 'It forces every board to expand along one identical direction', 'It permanently fixes decorative layers to wet wood'], 0, 'Controlled movement reduces cracking and distortion.'],
  ]),
  ...listeningGroup('talk-prosody', 'Listen to an Academic Talk', '음성학', 'C1', 'Prosody includes rhythm, stress, phrasing, and intonation. A rising pitch can signal a question in one context but continuation, politeness, or uncertainty in another. Listeners integrate pitch with duration, intensity, syntax, and discourse expectations. Researchers cannot assign a universal meaning to one acoustic contour by inspecting it in isolation. They compare controlled productions with natural conversations and examine how speakers from different language communities categorize the same signal.', [
    ['Why is a rising contour not assigned one fixed meaning?', ['Its interpretation depends on other linguistic cues and interactional context', 'Pitch cannot be measured independently of vocal intensity', 'All languages use falling contours for every question', 'Natural conversation contains no repeatable acoustic pattern'], 0, 'Prosodic function is context-sensitive.'],
    ['Why compare speakers across language communities?', ['Experience with different systems may alter how an acoustic pattern is categorized', 'Community comparison eliminates the need to analyze syntax', 'Controlled speech is identical to spontaneous interaction', 'Duration and intensity have universal categorical meanings'], 0, 'Perception is shaped by learned linguistic conventions.'],
  ]),
  ...listeningGroup('talk-commons', 'Listen to an Academic Talk', '제도경제학', 'C1', 'A common-pool resource is difficult to exclude people from using, yet one person’s extraction reduces what remains for others. Depletion is not inevitable. Communities have developed monitoring, graduated sanctions, conflict-resolution procedures, and rules matched to local conditions. Success does not imply the absence of government or markets; institutions can be nested across levels. Analysts ask who participates in rule making, how boundaries are defined, and whether users can revise arrangements as ecological and social conditions change.', [
    ['Why is a common-pool resource vulnerable to overuse?', ['Access is hard to restrict while individual extraction subtracts from the shared stock', 'Every user receives a separate supply unaffected by others', 'Local rules make ecological change impossible', 'Government ownership automatically eliminates competition'], 0, 'Low excludability combines with rivalry.'],
    ['What does institutional nesting imply?', ['Local arrangements may operate within broader governmental or market structures', 'Communities must eliminate every external organization to succeed', 'One immutable rule should govern all spatial scales', 'Conflict resolution is useful only in unregulated resources'], 0, 'Governance levels can complement rather than exclude one another.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the estimate unstable?', 'Had the instrument been even slightly weaker', ['the first-stage relationship', 'would scarcely have', 'distinguished treatment', 'from random variation'], 'f15-had-counterfactual-scarcely'],
  ['What did the excavation context show?', 'Buried beneath the collapsed doorway were', ['several tablets', 'whose seal impressions', 'linked them', 'to one office'], 'f15-locative-inversion-relative'],
  ['Why question the apparent improvement?', 'However impressive the average may appear', ['it conceals', 'the extent to which', 'outcomes varied', 'among districts'], 'f15-however-adjective-concessive'],
  ['What made comparison possible?', 'By having preserved every intermediate file', ['the team enabled', 'later auditors', 'to reconstruct', 'each transformation'], 'f15-perfect-gerund-by-clause'],
  ['When would the claim be credible?', 'Only if the same pattern emerged under a preregistered test', ['could the result', 'be distinguished', 'from a hypothesis', 'chosen afterward'], 'f15-only-if-modal-inversion'],
  ['Why did the translator retain the metaphor?', 'Not so much because it was literally transparent', ['as because', 'its strangeness', 'was central', 'to the narrator’s voice'], 'f15-not-so-much-as'],
  ['What explains the delayed response?', 'The more deeply the material had been frozen', ['the longer', 'microbial activity took', 'to resume', 'after thawing'], 'f15-correlative-comparative-perfect'],
  ['Why was the amendment necessary?', 'Lest participants mistake passive tracking for occasional surveys', ['the consent form', 'was revised', 'to specify', 'continuous collection'], 'f15-lest-subjunctive-purpose'],
  ['How should the outlier be treated?', 'Whether or not it changes the conclusion', ['the observation', 'should remain flagged', 'with its original', 'quality record'], 'f15-whether-or-not-concessive'],
  ['What did the committee conclude?', 'So little documentation accompanied the sample', ['that no attribution', 'could responsibly', 'be made', 'to a specific expedition'], 'f15-so-little-result-passive'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '표본 냉동고 이상', 'C1', 420), instruction: '관찰 사실, 불확실성, 즉각적 보존 조치와 기록 요청을 분명히 작성하세요.', prompt: 'You find that a shared specimen freezer briefly exceeded its temperature limit overnight, but the monitoring dashboard shows a gap during part of the event. Write to the collection manager. Describe the evidence, explain why sample quality cannot yet be assumed, and request quarantine, backup-log review, and a documented decision for affected materials.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '연구 데이터 연계', 'C1', 600), instruction: '사회적 이익과 재식별·통제 위험을 함께 평가하고 구체적 기준을 제시하세요.', prompt: 'Professor Alvarez: Should public agencies link administrative records across education, health, and employment to improve policy research?', passage: 'Mina: Linked records reveal long-term outcomes without repeatedly burdening participants.\nRobert: Combining databases creates privacy risks and gives institutions uses that people never anticipated.' })

const repeatSentences = ['Welcome to the shared microscopy facility.', 'Confirm that your reservation matches the instrument on the door.', 'Inspect the objective lens before placing a slide on the stage.', 'Use immersion liquid only with the lens designated for that medium.', 'Save raw image files before applying contrast or noise corrections.', 'Remove every specimen and wipe the stage with the approved material.', 'At the end of your session, export the data, complete the usage log, and report any change in alignment or performance to facility staff.']
const interviewQuestions = ['Describe an example of organizations linking information from different sources.', 'What useful insight could that linkage provide?', 'What privacy or fairness problem might arise from combining the records?', 'What safeguards should be required before linked information is used for a decision?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '현미경 공동시설', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f15-repeat', scenarioId: 'f15-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '정보 연계와 프라이버시', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f15-interview', scenarioId: 'f15-interview', sequenceIndex })),
]

export const AUTHORED_FORM_15_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_15_IDS = AUTHORED_FORM_15_ITEMS.map((item) => item.id)
