import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f22')

const reading: BaseItem[] = [
  cloze('cloze-myelin', '신경생물학', 'C1', 'Myelin is a layered membrane that wraps many axons and accelerates electrical signaling. Glial cells main___ this insulation and adap___ their support to local axon properties. In the central nervous system, oligodendrocytes myelinate segments of several axons, whereas peripheral Schwann cells usually support one segment. Gaps called nodes of Ranvier contain dense ion channels, allowing action potentials to app___ jump between nodes. Myelin also provides metabolic support to axons. Damage can slow or block conduction and expose axons to degeneration. Repair depends on precursor-cell recruitment, differentiation, and an environment that permits new wrapping. Imaging a white-matter lesion does not directly mea___ conduction or identify its cause. Inflammation, vascular injury, development, and aging can produce different changes. Researchers comb___ electrophysiology, imaging, histology, and behavior. Thicker myelin is not always better; optimal geometry dep___ on axon diameter and circuit timing. Plastic changes may fine-tune synchronization, but broad learning claims req___ evidence that altered myelination caused the behavioral change. Treatments aimed at remyelination must also pres___ surviving axons and avoid stimulating inappropriate growth. Mechanistic studies therefore dist___ protection, repair, and functional recovery rather than using them interch___.', 'tain|t|ear|sure|ine|ends|uire|erve|inguish|angeably'),
  cloze('cloze-sediment-budget', '연안지형학', 'C1', 'A coastal sediment budget accounts for sand entering, leaving, and being stored within a defined shoreline system. Waves exch___ material among compartments, and storms can exp___ large pulses offshore. Rivers, cliff erosion, and offshore transport may sup___ sediment, while currents, dredging, and wind remove or red___ it. A beach can narrow even without permanent loss if sand moves seasonally into offshore bars. Measurements must therefore span relevant timescales and boundaries. Nourishment adds sand but may not address the process causing deficit. Grain size matters because fine material may disperse rapidly. Structures such as groynes can trap sand locally while star___ downdrift beaches. Researchers compare surveys, tracers, wave climate, and historical imagery. Volume estimates carry error from changing water level and survey coverage. A closed budget is rarely exact; unmeasured exchanges may rem___. Management decisions should distinguish temporary redistribution from net system loss and consider whether intervention merely trans___ erosion elsewhere. Climate-driven sea-level rise can increase accommodation space, requiring more sediment to main___ shoreline position. Effective analysis links morphology to flux rather than inf___ supply from one beach profile and spec___ the spatial domain before calculating balance.', 'ange|ort|ply|istribute|ving|ain|fers|tain|erring|ifies'),
  cloze('cloze-glass', '재료기술사', 'B2', 'Glass forms when a melt cools without crystallizing into an ordered solid. Cooling rate infl___ crystallization, and workers anne___ finished objects to reduce internal stress. Silica creates the structural network, while fluxes lower melting temperature and stabilizers imp___ durability. Color can arise from metal ions, nanoparticles, or furnace atmosphere. Bubbles and striations may rev___ mixing and working conditions. Ancient glassmakers often recycled fragments, so chemical composition can blend several sources. Trace elements help dist___ raw materials from colorants, but contamination during recycling complicates attribution. Forming techniques include casting, blowing, pressing, and molding. Tool marks and wall thickness provide clues, yet later heating can def___ them. Weathering leaches mobile ions and creates iridescent layers that should not be mistaken for intentional decoration. Conservators avoid sudden humidity changes and test cleaning because altered surfaces are fragile. Experimental reconstructions show what methods are feasible without proving one workshop used them. Scholars comb___ chemical, technological, and archaeological evidence, identify production waste, and rec___ distribution networks. A visually uniform object may still contain multiple repair phases, which imaging can det___ before sampling and doc___ for future comparison.', 'uences|aled|rove|eal|inguish|orm|ine|onstruct|ect|ument'),
  daily('daily-balance-door', '정밀 측정실', 'B2', 'The analytical balance room door must remain closed for five minutes before a high-precision weighing. Foot traffic and pressure changes disturb the reading. Samples may acclimate inside during that interval, but containers should remain capped until weighing begins.', ['Why is there a waiting period after the door closes?', ['Air movement and pressure need time to stabilize around the balance', 'Capped containers cannot acclimate to room temperature', 'Foot traffic increases sample mass permanently', 'High-precision readings require the door to stay open'], 0, 'Environmental stabilization reduces measurement noise.']),
  daily('daily-community-map', '참여형 지도', 'C1', 'Locations contributed by community members may identify sacred or vulnerable sites. The public map should generalize coordinates according to the access agreement, while the precise layer remains restricted. Visual blurring alone is insufficient if downloadable data retain exact geometry.', ['What must be checked in addition to the displayed map?', ['Whether downloadable spatial data also protect precise locations', 'Whether every public symbol has a brighter color', 'Whether restricted coordinates appear in the legend', 'Whether contributors used identical mapping software'], 0, 'Underlying data can reveal what the interface obscures.']),
  daily('daily-orchestra-part', '악보 대여', 'B1', 'Marked orchestra parts are assigned by folder number. Musicians may add pencil bowings but should not erase a previous player’s markings unless the conductor approves a clean set. Return every loose insert inside the same numbered folder.', ['What requires the conductor’s approval?', ['Removing earlier performance markings to create a clean part', 'Adding a temporary bowing notation in pencil', 'Returning an insert to its assigned folder', 'Reading the folder number before rehearsal'], 0, 'Prior annotations are part of the working set.']),
  daily('daily-vaccine-freezer', '임상 보관', 'B2', 'The vaccine freezer’s display shows air temperature, while the buffered probe approximates vial temperature. During a brief door opening, the display may rise sharply without the product warming equally. Excursion decisions follow the probe record and stability protocol.', ['Why can the two temperature readings differ briefly?', ['Air responds faster than the thermally buffered product proxy', 'The buffered probe measures only room humidity', 'Vial temperature always changes before freezer air', 'The display automatically applies the stability protocol'], 0, 'Thermal mass smooths short air fluctuations.']),
  daily('daily-code-review', '소프트웨어 연구', 'B2', 'A code review is complete only after requested changes are resolved or explicitly declined with a reason. Pushing a new commit does not close discussion threads automatically. The author should link each change to its review comment and rerun affected tests.', ['What must accompany a declined review request?', ['A documented reason explaining why the change was not made', 'Automatic closure triggered by any new commit', 'Deletion of the original discussion thread', 'A decision to skip every affected test'], 0, 'Resolution can be acceptance or reasoned rejection.']),
  daily('daily-paint-rack', '회화 보존', 'B2', 'Paintings on the drying rack face the padded divider and remain separated by one empty slot. A small panel may not share a slot with another object because vibration can bring them into contact. Wet treatments are labeled at both rack and object.', ['Why must a small panel occupy its own slot?', ['Movement could cause contact damage despite available space', 'The padded divider accelerates every wet treatment', 'Rack labels replace labels on individual objects', 'Small paintings create no vibration risk'], 0, 'Separation protects against movement, not merely crowding.']),
  daily('daily-field-sim', '안전 훈련', 'B2', 'The field-emergency simulation uses staged coordinates that must not be entered into the real rescue-request system. Teams send messages through the training channel marked SIMULATION. If a participant accidentally contacts emergency dispatch, notify the exercise controller immediately.', ['What prevents a training message from triggering a real response?', ['Using the designated simulation channel and marking', 'Entering the staged location into emergency dispatch', 'Waiting until the exercise has finished', 'Removing coordinates from the team’s field map'], 0, 'Communication must remain within the exercise system.']),
  daily('daily-thesis-copy', '학위논문 제출', 'B1', 'The library copy of a thesis must match the final committee-approved file. Students may correct a title-page typo before deposit if the graduate office confirms it. Changes to arguments, data, or conclusions require renewed committee review.', ['Which correction may proceed without renewed committee review?', ['A confirmed typographical fix on the title page', 'Replacement of the reported dataset', 'A new interpretation in the conclusion', 'Removal of a central argument'], 0, 'A narrow production correction is distinct from substantive revision.']),
  daily('daily-salinity-bottle', '해수 표본', 'B2', 'Salinity bottles are rinsed with sample water three times before filling, but nutrient bottles follow a different contamination-control protocol. Do not transfer the rinsing rule across bottle types. Labels should be applied before gloves become wet.', ['What warning is given about the rinsing procedure?', ['It is specific to salinity bottles and should not be generalized', 'Every seawater container requires three sample rinses', 'Wet gloves improve label adhesion', 'Nutrient bottles have no contamination controls'], 0, 'Different analyses require different handling.']),
  daily('daily-license-renewal', '실험동물 교육', 'B2', 'Animal-handling certification expires at midnight on the listed date, not at the end of the scheduled experiment. A renewal submitted but not yet approved does not extend access. Another certified team member must take over procedures if approval lapses.', ['What happens when renewal remains pending after expiration?', ['The researcher must stop handling animals until approval returns', 'Submission alone extends certification automatically', 'The ongoing experiment overrides the access system', 'The expiration date moves to the experiment’s final day'], 0, 'Current approval is required for continued work.']),
  ...readingGroup('academic-synthetic', '비교사례 방법론', 'C1', 'The synthetic-control method constructs a weighted combination of untreated units that resembles a treated unit before an intervention. Postintervention divergence can estimate an effect when no single comparison unit is adequate. Credibility depends on a good preintervention fit and on the donor pool not being affected by the intervention. A fit achieved with one short preperiod may be fragile. Placebo tests apply the method to untreated units to see whether the treated gap is unusual, but they do not correct a poor design. Predictor choice and donor-pool restrictions should follow substantive knowledge rather than be tuned solely to maximize a desired post-treatment gap.', [
    ['What is the purpose of weighting untreated units?', ['To reproduce the treated unit’s preintervention trajectory with a composite comparison', 'To assign the intervention to every donor unit', 'To guarantee identical outcomes after treatment', 'To eliminate the need for historical observations'], 0, 'The weighted donor pool approximates the missing counterfactual.'],
    ['Why must donors remain unaffected?', ['Spillovers would contaminate the comparison path used as untreated', 'Affected donors always improve preperiod fit', 'Treatment effects are defined only within the donor pool', 'Placebo tests remove all spillover bias'], 0, 'The comparison must represent no intervention.'],
    ['What do placebo tests help assess?', ['Whether a gap as large as the treated one commonly appears without treatment', 'Whether a weak preintervention match becomes valid', 'Whether predictors should be selected after viewing results', 'Whether all donor weights equal one another'], 0, 'Placebos provide a reference distribution of apparent effects.'],
  ]),
  ...readingGroup('academic-pollination', '네트워크생태학', 'C1', 'Plant–pollinator communities form networks in which species differ in the number and strength of interactions. A generalist may visit many plants, but visitation does not guarantee effective pollen transfer. Network redundancy can buffer the loss of one species if others perform similar functions. Yet apparent redundancy may disappear when timing, morphology, or pollen quality is considered. Aggregate connectance can remain stable while specialist interactions vanish. Researchers combine visitation networks with experiments measuring seed set and track seasonal overlap rather than inferring resilience from topology alone.', [
    ['Why can a highly connected visitor be a poor pollinator?', ['Frequent visits may transfer little compatible pollen', 'Generalists interact with only one plant species', 'Seed set is independent of pollen delivery', 'Network links measure genetic relatedness'], 0, 'Interaction frequency and functional effectiveness differ.'],
    ['Why might topological redundancy overstate resilience?', ['Species with similar link counts may differ in season, fit, or service quality', 'Redundancy requires every species to be a specialist', 'Connectance always declines before any species disappears', 'Morphology cannot constrain pollination'], 0, 'Functional substitutability needs more than shared partners.'],
  ]),
  ...readingGroup('academic-ostraca', '고대일상사', 'C1', 'Ostraca are pieces of broken pottery or limestone used as inexpensive writing surfaces. They preserve receipts, lists, letters, school exercises, and administrative notes that might never merit papyrus. Their informality gives access to everyday transactions, but interpretation remains difficult. A date may omit the century, a personal name may belong to several people, and a fragment can preserve only part of a message. Ostraca found in a dump may have been moved from their place of use. Scholars compare handwriting, formulas, associated deposits, and named institutions while resisting the temptation to turn one brief note into a complete social narrative.', [
    ['Why are ostraca valuable for social history?', ['Their low-cost medium preserved routine writing often absent from formal archives', 'Every ostracon records a complete government decree', 'Broken pottery was reserved for elite literature', 'Papyrus never contained ordinary transactions'], 0, 'Ephemeral communication survives on durable scraps.'],
    ['What makes identifying a named person uncertain?', ['Names may recur and contextual details may be missing', 'Every writer used a unique personal alphabet', 'Century dates appear on all fragments', 'Dump deposits preserve original office location'], 0, 'Short texts often lack disambiguating information.'],
    ['Why should dump context be treated cautiously?', ['Discarded material may have been transported from another activity area', 'A dump prevents pottery from preserving ink', 'All fragments in one dump were written on the same day', 'Associated deposits cannot help chronological interpretation'], 0, 'Final disposal is not necessarily place of use.'],
  ]),
  ...readingGroup('academic-shape-memory', '금속재료', 'C1', 'Shape-memory alloys can recover a trained form through a reversible transformation between crystal structures. Below a transition temperature, the martensitic phase can be deformed by rearranging variants; heating produces austenite and restores the programmed shape. Superelastic behavior occurs when stress induces transformation above the transition, allowing large reversible strain without heating. Repeated cycling causes fatigue, and transition temperature depends on composition and processing. A dramatic one-time recovery does not establish device reliability under loads, temperature variation, corrosion, and thousands of cycles.', [
    ['What enables recovery of the trained shape?', ['A reversible phase transformation reorganizes the deformed crystal structure', 'Ordinary plastic deformation permanently fixes every variant', 'Heating melts the alloy and recasts it', 'Superelasticity requires cooling below all transition temperatures'], 0, 'Structural phase change drives recovery.'],
    ['Why is a single demonstration insufficient for engineering use?', ['Long-term cycling and environmental conditions may degrade performance', 'One recovery proves infinite fatigue resistance', 'Composition cannot influence transition temperature', 'Loads have no effect on phase transformation'], 0, 'Reliability requires repeated operational evidence.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the vaccine probe remain within the stability range?', ['Yes, despite a brief rise in the freezer-air display.', 'The freezer stores three vaccine formulations.', 'Buffered probes respond more slowly than air sensors.', 'I displayed the range on a scatterplot.'], 0, 'The response distinguishes product proxy from air fluctuation.'),
  response(1, 'Why was the community map download disabled?', ['The map shows several river restoration sites.', 'Its geometry still contained precise protected coordinates.', 'I disabled the automatic legend animation.', 'Community members contributed place names.'], 1, 'Underlying data created a disclosure risk.'),
  response(2, 'Could spillover invalidate these synthetic-control donors?', ['The donor pool includes neighboring regions.', 'Preperiod fit is measured by prediction error.', 'Yes, if the policy changed their outcomes after implementation.', 'I controlled the light spill with a black curtain.'], 2, 'Affected donors cease to represent no treatment.'),
  response(3, 'I thought every insect visit counted as pollination.', ['The insect carried pollen on its legs.', 'Pollination networks contain weighted links.', 'I counted the microscope fields systematically.', 'A visit may deposit no compatible pollen on the stigma.'], 3, 'Visitation is not equivalent to successful transfer.'),
  response(4, 'May we straighten the shape-memory wire by hand?', ['Only within the deformation and temperature limits of its test protocol.', 'The wire contains nickel and titanium.', 'Shape recovery can occur during heating.', 'I straightened the labels on the display board.'], 0, 'Uncontrolled deformation can change or damage the test article.'),
  response(5, 'Where is the full-resolution sacred-site layer?', ['The public map uses generalized symbols.', 'In the restricted geodatabase governed by the access agreement.', 'Resolution affects the appearance of raster images.', 'I layered the samples by sediment depth.'], 1, 'The response gives controlled storage and authority.'),
  response(6, 'Shouldn’t the donor pool exclude the adjacent county?', ['The county matched the treated area before the policy.', 'Adjacent areas share the same labor market.', 'Yes, if residents or firms shifted there because of the intervention.', 'I excluded the damaged slide from the tray.'], 2, 'Behavioral spillover contaminates the donor.'),
  response(7, 'The vaccine display peaked above the alarm threshold.', ['The display reports unbuffered air temperature.', 'The door was open for less than one minute.', 'I peaked during the final week of training.', 'Check the buffered probe and stability protocol before declaring an excursion.'], 3, 'Product impact requires the correct evidence.'),
  response(8, 'Is this ostracon definitely from the office where it was found?', ['No, the dump deposit may contain material moved from elsewhere.', 'The text records delivery of grain sacks.', 'Ostraca were written with carbon-based ink.', 'I found the reference in an office catalog.'], 0, 'Disposal context may be secondary.'),
  response(9, 'Why did the myelin signal rise without faster conduction?', ['The tract connects sensory and motor regions.', 'The imaging metric may reflect inflammation or water as well as myelin.', 'I conducted the interview in a quiet room.', 'Signal intensity is normalized to nearby tissue.'], 1, 'The proxy is biologically nonspecific.'),
  response(10, 'Can we call these insects functionally redundant?', ['The insects visit overlapping flower species.', 'Functional traits include body size and activity season.', 'Only after showing that they transfer comparable pollen under relevant conditions.', 'I called the specimen manager about the missing vial.'], 2, 'Shared network position does not prove equivalent service.'),
  response(11, 'I cannot reproduce the alloy’s transition temperature.', ['The alloy returns to a curved shape when heated.', 'Transition is measured by thermal analysis.', 'I reproduced the illustration with permission.', 'Verify composition, heat treatment, and prior mechanical cycling.'], 3, 'Processing history strongly affects transition.'),
  response(12, 'Has the code-review thread been resolved explicitly?', ['Yes, the author linked the revision and test result to the comment.', 'The code calculates pollen-network connectance.', 'Review threads appear beside changed lines.', 'I resolved the image into separate color channels.'], 0, 'The reply confirms traceable resolution.'),
  response(13, 'When will the analytical-balance room reopen?', ['The balance measures to six decimal places.', 'After facilities verify pressure control tomorrow morning.', 'I balanced the sample groups by age.', 'The room has a double-door entrance.'], 1, 'The response states the reopening condition and time.'),
  response(14, 'Would a placebo donor help assess the treated gap?', ['The donor had a similar prepolicy trajectory.', 'Placebo gaps are computed for untreated units.', 'It could show whether comparable false gaps occur without intervention.', 'I donated the instrument to the teaching laboratory.'], 2, 'Placebo results contextualize unusualness.'),
  response(15, 'Who can release the precise community coordinates?', ['The coordinates were collected during participatory mapping.', 'The restricted layer uses role-based access.', 'Public symbols are offset from actual sites.', 'The data steward must apply the contributors’ access agreement.'], 3, 'Release depends on stewarded consent terms.'),
  response(16, 'This glass fragment appears iridescent under side light.', ['Test whether weathering layers, not original color, produce the effect.', 'The fragment came from a vessel rim.', 'Iridescence separates reflected wavelengths.', 'I fragmented the dataset into yearly files.'], 0, 'Surface alteration can create iridescence.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-fit', 'Listen to a Conversation', '합성통제 분석', 'C1', 'Student: My synthetic control matches the treated city’s average income but misses its rising employment trend. Advisor: Then it does not reproduce the outcome process that matters. Student: Could I add more predictors until the trend matches? Advisor: Use defensible prepolicy outcomes and predictors, but do not search after viewing the postpolicy gap. Report fit limitations and alternative donor pools.', [
    ['Why is matching average income insufficient?', ['The comparison fails to reproduce the treated outcome trajectory before intervention', 'Income is never relevant to employment policy', 'Synthetic controls require one donor with identical values', 'Postpolicy fit defines the counterfactual'], 0, 'Pretrend fit is central to credibility.'],
    ['What does the advisor warn against?', ['Tuning predictors with knowledge of the desired postintervention result', 'Using any prepolicy outcome as a predictor', 'Examining fit before constructing weights', 'Reporting more than one donor pool'], 0, 'Outcome-informed design choice risks overfitting.'],
  ]),
  ...listeningGroup('conversation-rack', 'Listen to a Conversation', '회화 건조대', 'B2', 'Assistant: This small panel fits beside another painting in one rack slot. Conservator: Physical space is not the only issue. The rack vibrates when drawers move, and wet surfaces could touch. Assistant: Could I add padding between them? Conservator: Keep the required empty slot. Padding near wet treatment introduces another contact material.', [
    ['Why does the conservator require an empty slot?', ['Movement can bring separate objects into damaging contact', 'Small panels are always heavier than large paintings', 'The rack never vibrates when a drawer moves', 'Padding accelerates drying by absorbing paint'], 0, 'Dynamic clearance is necessary.'],
    ['Why is extra padding rejected?', ['It creates a new material that may contact the treated surface', 'It permanently stops every rack vibration', 'It removes the need for object labels', 'It increases the number of available slots'], 0, 'Added protection can introduce its own risk.'],
  ]),
  ...listeningGroup('conversation-signal', 'Listen to a Conversation', '신경 전도', 'C1', 'Researcher: The treated animals show more white-matter signal, so I wrote that remyelination restored function. Neurologist: Did conduction speed or behavior improve? Researcher: Behavior improved slightly, but inflammation also declined. Neurologist: Then separate protection, reduced inflammation, and new myelin. Imaging plus behavior does not identify which mechanism caused change.', [
    ['What is the main interpretive problem?', ['Several biological changes could produce the imaging and behavioral pattern', 'White matter contains no myelinated axons', 'Conduction speed is identical to lesion volume', 'Reduced inflammation proves new myelin formed'], 0, 'The evidence does not isolate remyelination.'],
    ['What additional evidence is most relevant?', ['Direct measures of conduction and tissue-level myelin repair', 'A brighter image display setting', 'More general activity without lesion assessment', 'Removal of all untreated comparisons'], 0, 'Mechanism-specific outcomes are needed.'],
  ]),
  ...listeningGroup('conversation-translation', 'Listen to a Conversation', '오스트라카 판독', 'C1', 'Student: This ostracon says “year twelve,” so I dated it exactly. Historian: Year twelve of which ruler or local era? Student: The name is missing. Historian: Use handwriting, archaeological layer, and officials named on related texts to narrow possibilities. Do not convert an incomplete date into false precision.', [
    ['Why is “year twelve” ambiguous?', ['The governing chronological system or ruler is not identified', 'Ancient writers never used numbered years', 'Handwriting provides an exact day automatically', 'Archaeological layers cannot constrain dates'], 0, 'The numeral needs an era reference.'],
    ['How should the date be reported?', ['As a constrained range supported by several contextual clues', 'As the twelfth year of the best-known ruler without qualification', 'Without reference to related documents', 'As later than every object in the layer'], 0, 'Converging evidence narrows but may not fix the date.'],
  ]),
  ...listeningGroup('conversation-salinity', 'Listen to a Conversation', '해수 채취', 'B2', 'Student: I rinsed the nutrient bottles three times with seawater, just like the salinity bottles. Technician: That can contaminate the nutrient samples because their bottles were prepared to remain clean. Student: Should I recollect them? Technician: Yes, and record the handling error rather than silently replacing the values.', [
    ['Why was the rinsing inappropriate?', ['The nutrient protocol relies on specially prepared bottles without sample rinsing', 'Salinity bottles cannot contact seawater before filling', 'Three rinses remove every dissolved nutrient', 'Prepared bottles contain the final sample already'], 0, 'A rule from one analysis conflicts with another protocol.'],
    ['Why document the recollection?', ['The audit trail should explain why the original samples were invalid', 'New samples must be presented as if no error occurred', 'Documentation changes seawater nutrient concentration', 'Silent replacement improves reproducibility'], 0, 'Transparent correction preserves data lineage.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-microelectrode', 'Listen to an Announcement', '전기생리실', 'C1', 'The microelectrode puller will receive a software update tonight. Saved programs remain, but users must verify heat and pull settings against a test capillary before making experimental electrodes. Programs lacking a named owner will be archived rather than deleted and can be restored by facility staff.', [
    ['What must users do after the update?', ['Validate stored settings on a nonexperimental capillary', 'Delete every saved pulling program', 'Use experimental tissue to test software heat', 'Rename the facility’s archived programs independently'], 0, 'Persistence of a program does not guarantee unchanged output.'],
    ['What happens to unidentified programs?', ['They move to recoverable archival storage', 'They are erased permanently tonight', 'They become the default for all users', 'They run automatically after the update'], 0, 'Archiving preserves them without cluttering active use.'],
  ]),
  ...listeningGroup('announcement-elevator', 'Listen to an Announcement', '건물 접근성', 'B1', 'The humanities elevator closes from one to three for inspection. Step-free access to the lecture theater remains available through the language building connector on level two. Signs begin at the south entrance, and staff will meet anyone who requests navigation assistance.', [
    ['How can a visitor avoid stairs during inspection?', ['Use the level-two connector from the adjacent building', 'Wait inside the closed elevator', 'Enter through the unsigned north service door', 'Cross the roof from the lecture theater'], 0, 'The connector provides an accessible detour.'],
    ['Where does marked guidance begin?', ['At the south entrance to the detour route', 'Inside the elevator shaft', 'At the theater stage', 'On the building roof'], 0, 'Signs start at the stated entrance.'],
  ]),
  ...listeningGroup('announcement-specimen-loan', 'Listen to an Announcement', '표본 대여', 'B2', 'Outgoing specimen loans pause Friday while the tracking database migrates. Returns will still be accepted and photographed, but their final shelf positions will be entered Monday. Keep returned crates in the marked intake zone; do not shelve them using a printed inventory that may be outdated.', [
    ['Which activity continues Friday?', ['Documented receipt of returning loan material', 'Creation of new outgoing shipment records', 'Final database assignment of shelf positions', 'Shelving based on the old printed inventory'], 0, 'Intake continues despite the outbound pause.'],
    ['Why must crates remain in the intake zone?', ['The migrated system must determine their authoritative locations', 'Photographs remove the need for shelf records', 'Printed inventory becomes more accurate during migration', 'Returned material is leaving again immediately'], 0, 'Temporary holding prevents location mismatch.'],
  ]),
  ...listeningGroup('announcement-debate', 'Listen to an Announcement', '윤리 토론회', 'B2', 'The technology-ethics debate begins at six. The first half is recorded for public release; audience discussion after seven remains off the record to encourage candid questions. Anyone entering late will see a notice when recording ends. Written questions submitted for the public segment may appear in the published transcript.', [
    ['Which portion will not be publicly recorded?', ['The audience discussion beginning after seven', 'The opening half of the formal debate', 'Written questions used in the public segment', 'The recording-end notice'], 0, 'The event changes confidentiality midway.'],
    ['What should a writer assume about an early submitted question?', ['It may be included in the released transcript', 'It automatically becomes off the record', 'It will be deleted when recording ends', 'It can be asked only after seven'], 0, 'Public-segment submissions can enter publication.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-enso', 'Listen to an Academic Talk', '기후역학', 'C1', 'El Niño develops when coupled changes in tropical Pacific winds and ocean temperatures weaken the usual east–west contrast. Weaker trade winds reduce upwelling of cold water in the east and allow warm surface water to shift eastward. The changed tropical heating reorganizes atmospheric circulation, influencing rainfall far away. Effects vary among events because their location, season, background climate, and interaction with other modes differ. El Niño raises the probability of particular regional conditions; it does not determine every local weather outcome.', [
    ['How does weaker trade wind reinforce eastern warming?', ['It reduces cold-water upwelling and permits warm water to spread east', 'It strengthens the normal westward pileup of surface water', 'It blocks all atmospheric heating above the Pacific', 'It forces local rainfall to be identical in every event'], 0, 'Ocean and wind changes form a coupled feedback.'],
    ['Why are regional consequences probabilistic?', ['Event structure and other climate influences vary from case to case', 'Tropical heating cannot affect atmospheric circulation', 'El Niño occurs in exactly the same season everywhere', 'Local weather is determined by one ocean index alone'], 0, 'Teleconnections alter odds amid other causes.'],
  ]),
  ...listeningGroup('talk-public-goods', 'Listen to an Academic Talk', '실험경제학', 'C1', 'In a public-goods game, individuals decide how much of an endowment to contribute to a shared account. Contributions benefit the group, but keeping resources benefits the individual, creating a social dilemma. Repeated games often show declining cooperation unless communication, reputation, punishment, or institutional rules are introduced. Laboratory behavior does not directly measure generosity in every real setting; stakes, framing, anonymity, culture, and selection into experiments matter. The game isolates incentives while simplifying social relationships.', [
    ['What creates the dilemma?', ['Private retention conflicts with a group benefit from collective contribution', 'Contributions return value only to the contributor', 'The shared account excludes noncontributors from all gains', 'Keeping resources maximizes total group payoff'], 0, 'Individual and collective incentives diverge.'],
    ['Why should results not be generalized mechanically?', ['Experimental context and participant selection differ from real institutions', 'Public goods exist only inside laboratories', 'Repetition always produces perfect cooperation', 'Framing has no effect on decisions'], 0, 'Controlled abstraction limits external validity.'],
  ]),
  ...listeningGroup('talk-grid-cells', 'Listen to an Academic Talk', '공간인지', 'C1', 'Grid cells fire at multiple locations that form a roughly hexagonal pattern as an animal moves through space. Together with place cells, head-direction cells, and sensory cues, they contribute to navigation. The regular pattern is not a literal map stored on one neuron. Grid orientation and scale can change across environments, and boundaries distort fields. Laboratory arenas simplify movement, so researchers test more complex and three-dimensional settings. Neural correlation with location does not alone establish what information is necessary for behavior.', [
    ['Why is one grid cell not a complete spatial map?', ['Its repeating fields require population activity and other signals to disambiguate location', 'It fires at only one unique point in every environment', 'Hexagonal patterns eliminate all boundary effects', 'Navigation uses no sensory information'], 0, 'Repeated codes need combination with other representations.'],
    ['Why study complex environments?', ['Simple arenas may hide how irregular boundaries and dimensions alter coding', 'Three-dimensional movement removes spatial variables', 'Grid orientation is fixed under all conditions', 'Laboratory behavior cannot be measured'], 0, 'Ecological structure tests generality.'],
  ]),
  ...listeningGroup('talk-vaults', 'Listen to an Academic Talk', '건축사', 'B2', 'A ribbed vault uses masonry ribs to define arches and support lighter webbing between them. Ribs can concentrate and redirect loads toward piers, but the entire vault and surrounding buttressing work as a system. Gothic builders used pointed arches to span bays of different widths at compatible heights. Construction required timber centering, careful geometry, and staged loading. Visible ribs may also organize the interior aesthetically, so structural and symbolic roles should not be treated as mutually exclusive.', [
    ['What advantage do pointed arches provide?', ['Different spans can reach comparable crown heights', 'They remove all outward thrust from masonry', 'They eliminate temporary construction support', 'They require every bay to have one width'], 0, 'Pointed geometry offers flexible proportions.'],
    ['Why should ribs not be studied in isolation?', ['Webbing, piers, and buttresses participate in the shared load path', 'Ribs carry no structural force at all', 'Aesthetic organization prevents compression', 'Timber centering remains permanently inside every vault'], 0, 'The assembly distributes forces systemically.'],
  ]),
  ...listeningGroup('talk-gender', 'Listen to an Academic Talk', '언어학', 'C1', 'Grammatical gender classifies nouns and controls agreement on words such as articles or adjectives. The classes may correlate partly with biological sex, shape, animacy, or other patterns, but membership is often conventional. A language can have gender without marking sex on every noun, and one noun’s class does not imply speakers believe its referent has that property. Psycholinguistic effects of gender labels are sensitive to task and bilingual experience. Researchers distinguish grammatical agreement from cultural stereotypes and lexical meaning.', [
    ['Why is grammatical class not a direct statement about a referent?', ['Agreement categories can be conventional and only partly semantically motivated', 'Every noun class encodes biological sex literally', 'Articles never change form with gender', 'Speakers choose a new class for each sentence'], 0, 'Grammar and real-world properties do not map transparently.'],
    ['Why are cognitive claims about gender treated cautiously?', ['Observed effects may depend on task, language pair, and cultural association', 'Grammar cannot influence processing under any condition', 'Bilingual speakers use no noun classifications', 'Lexical meaning is identical to agreement morphology'], 0, 'Experimental context affects interpretation.'],
  ]),
  ...listeningGroup('talk-carbon-capture', 'Listen to an Academic Talk', '에너지공학', 'C1', 'Carbon capture separates carbon dioxide from industrial exhaust or ambient air, then compresses it for use or storage. Capture from concentrated streams generally requires less energy than direct air capture because atmospheric carbon dioxide is dilute. Storage in deep geological formations depends on impermeable seals, trapping mechanisms, monitoring, and well integrity. A high capture percentage at one facility does not equal system-wide removal if energy supply, upstream emissions, transport leakage, and eventual storage are omitted.', [
    ['Why is direct air capture energy-intensive?', ['The target gas must be separated from a very low atmospheric concentration', 'Ambient air contains no carbon dioxide', 'Concentrated exhaust cannot be compressed', 'Geological seals produce all separation energy'], 0, 'Dilution raises processing work.'],
    ['Why use a system boundary broader than the capture unit?', ['Supporting energy and transport can generate emissions that reduce net removal', 'Facility capture rate already includes every upstream activity', 'Storage integrity is unrelated to climate benefit', 'Compression eliminates leakage risk'], 0, 'Net accounting covers the full chain.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the synthetic comparison rejected?', 'Had the donor regions not been exposed indirectly', ['their weighted outcome', 'might have represented', 'a credible', 'untreated path'], 'f22-had-not-passive-modal'],
  ['What did the neural recording show?', 'Distributed across the arena were', ['firing fields', 'whose repeating pattern', 'changed near', 'the boundaries'], 'f22-distributed-locative-inversion'],
  ['Why was the pollinator network reanalyzed?', 'Connected though several insects appeared', ['their actual', 'pollen delivery', 'differed', 'substantially'], 'f22-participle-though-inversion'],
  ['How should the public map be audited?', 'Only after downloadable geometry has been inspected', ['can reviewers know', 'whether visual masking', 'truly protects', 'the sites'], 'f22-only-after-perfect-passive'],
  ['What weakened the ostracon date?', 'There being no named ruler', ['the abbreviated year', 'could correspond', 'to more than', 'one chronology'], 'f22-there-being-absolute'],
  ['Why test the alloy repeatedly?', 'However complete its first recovery may seem', ['cyclic fatigue', 'could still render', 'the device', 'unreliable'], 'f22-however-complete-may-seem'],
  ['What made the placebo evidence useful?', 'The larger the treated gap was relative to placebo gaps', ['the less likely', 'ordinary instability', 'seemed to explain', 'the result'], 'f22-double-comparative-relative'],
  ['Why retain separate bottle protocols?', 'Were the salinity rinse applied to nutrient samples', ['contamination', 'would be introduced', 'before analysis', 'even began'], 'f22-were-passive-before-even'],
  ['What condition governed public release?', 'Not under any access tier were precise coordinates to be shared', ['unless contributors', 'had explicitly', 'authorized', 'that use'], 'f22-not-under-any-inversion'],
  ['Why did the engineers reject the laboratory claim?', 'So sensitive was conductivity to compression and moisture that', ['dry material tests', 'could not predict', 'panel performance', 'in service'], 'f22-so-sensitive-inversion-modal'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '보호 지도 자료', 'C1', 420), instruction: '노출 경로, 영향, 즉각적 차단과 검증 절차를 구체적으로 작성하세요.', prompt: 'You discover that a public community map visually blurs sensitive cultural sites, but its downloadable geographic file still contains exact coordinates. Write to the project’s data steward. Explain the disclosure pathway and potential harm, request immediate access restriction and audit, and propose a release test for future map versions.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '탄소 제거 투자', 'C1', 600), instruction: '기술 개발, 기회비용, 전체 시스템 배출을 함께 평가해 논지를 발전시키세요.', prompt: 'Professor Kone: Should governments invest heavily in carbon-removal technologies even if those technologies are currently expensive and energy intensive?', passage: 'Ava: Early investment can lower costs and develop tools needed for emissions that are difficult to eliminate.\nSamuel: Promises of future removal may divert money and attention from reducing fossil-fuel use now.' })

const repeatSentences = ['Welcome to the coastal-water sampling station.', 'Match each bottle type to the analysis listed on the field sheet.', 'Apply labels before gloves become wet or contaminated.', 'Rinse only the containers whose protocol explicitly requires it.', 'Collect water upstream from people and disturbed sediment.', 'Keep nutrient samples chilled and protected from direct sunlight.', 'Before departure, compare every bottle with the custody form, record the collection time, and place quality-control blanks in the correct transport container.']
const interviewQuestions = ['Describe a technology proposed to remove pollution after it has already entered the environment.', 'What advantage might this technology offer?', 'How could relying on removal weaken efforts to prevent pollution?', 'What evidence should governments require before funding the technology at large scale?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '연안 수질 채취', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f22-repeat', scenarioId: 'f22-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '오염 제거 기술', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f22-interview', scenarioId: 'f22-interview', sequenceIndex })),
]

export const AUTHORED_FORM_22_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_22_IDS = AUTHORED_FORM_22_ITEMS.map((item) => item.id)
