import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f19')

const reading: BaseItem[] = [
  cloze('cloze-overturning', '물리해양학', 'C1', 'The ocean’s overturning circulation transports heat, dissolved gases, and nutrients across basins. Surface currents comp___ deep transport. Surface water becomes den___ when it cools or loses freshwater through evaporation and sea-ice formation. In some high-latitude regions it sinks and sp___ at depth. Upwelling elsewhere eventually ret___ deep water toward the surface. The circulation is not one simple conveyor moving at a fixed speed. Wind, mixing, basin geometry, and eddies all infl___ pathways. Freshwater input can red___ surface density and weaken deep-water formation, but the response varies by location and timescale. Scientists comb___ temperature, salinity, tracers, and current measurements. Short records may capt___ natural variability rather than a persistent trend. Models help test mechanisms yet depend on mixing and ice representation. Researchers therefore assess multiple indicators instead of equ___ one regional index with the entire circulation and distin___ transport change from water-mass property change.', 'lement|ser|reads|urns|uence|uce|ine|ure|ating|guish'),
  cloze('cloze-crispr', '분자유전학', 'C1', 'CRISPR genome editing uses a guide RNA to direct a nuclease toward a complementary DNA sequence. Recognition also dep___ on a nearby short motif, so not every sequence is equally targetable. The nuclease cuts DNA, and cellular repair can dis___ a gene or insert a designed change. Repair outcomes are often het___ rather than uniform. Off-target cutting is one concern, but unintended on-target rearrangements can also occ___. Editing efficiency measured in bulk may con___ rare cell types and fail to rev___ mosaicism. Researchers sequence predicted sites, examine larger structural changes, and test function. Delivery method aff___ which tissues receive the components and how long they persist. Germ-line editing raises issues beyond technical accuracy because changes may be inh___ by future generations. Careful claims dist___ editing from correction: altering a sequence does not prove disease risk is eliminated, especially when gene effects depend on genetic background and env___.', 'ends|rupt|erogeneous|ur|ceal|eal|ects|erited|inguish|ironment'),
  cloze('cloze-glaze', '도자기과학', 'B2', 'A ceramic glaze is a glassy coating formed when mineral ingredients melt and fuse to a fired body. Silica provides a net___, while fluxes lower melting temperature and alumina helps cont___ flow. Color may arise from metal ions, crystal particles, or firing atmosphere. The same recipe can look dif___ on another clay or in another kiln zone. Bubbles, crazing, and crawling rev___ interactions among viscosity, gas release, and thermal expansion. A glaze that fits during cooling may still deg___ through moisture or repeated temperature change. Archaeometric studies exam___ composition and microstructure, but surface weathering can alt___ readings. Experimental replicas test plausible processes without proving one historical recipe. Potters adjusted raw materials by experience, and ingredients var___ by source. Researchers comb___ analysis with kiln evidence and production waste to rec___ technological choices.', 'work|rol|ferent|eal|rade|ine|er|ied|ine|onstruct'),
  daily('daily-lidar-tripod', '지형 측량', 'B2', 'A lidar tripod may remain on a benchmark between scans only while a staff member stays within sight. Placing a warning cone does not count as supervision. If the instrument must be left, remove it and photograph the benchmark before resetting.', ['What is required for the tripod to remain in place?', ['A staff member maintaining direct visual supervision', 'A warning cone placed beside an unattended instrument', 'A photograph taken instead of any responsible observer', 'Removal of the benchmark from the survey area'], 0, 'Presence, not signage alone, satisfies supervision.']),
  daily('daily-cell-line', '세포주 관리', 'C1', 'A cell-line name does not establish identity. Before publication, cultures must be authenticated against a reference profile and checked for cross-contamination. A recent vendor certificate is helpful but does not replace testing after extended local passage.', ['Why test a cell line again after local propagation?', ['Identity may change through mix-up or contamination during laboratory handling', 'Vendor certificates never contain a reference profile', 'Publication requires changing the cell-line name', 'Extended passage guarantees genetic identity remains fixed'], 0, 'Local history introduces new identity risks.']),
  daily('daily-music-stand', '공연장 장비', 'B1', 'Orchestra stands in the rehearsal hall may be moved to the stage, but each cart must return to its labeled storage bay after the concert. Individual stands should not be carried through the audience entrance because they block the narrow fire route.', ['How should the stands reach the stage?', ['On their designated transport carts rather than through the audience route', 'One at a time through the narrow public entrance', 'By leaving every cart in an unlabeled bay', 'Only after the concert audience has entered'], 0, 'The cart route protects access and tracking.']),
  daily('daily-reviewer-file', '논문 심사', 'B2', 'Supplementary reviewer files may contain author identities in document properties even when the visible text is anonymous. Before upload, reviewers should export to a clean format and inspect metadata. The editorial system removes account names from comments but cannot sanitize an attached local file.', ['What must a reviewer do before attaching a file?', ['Check and clean metadata that could reveal identity', 'Assume the editorial system rewrites every local property', 'Delete all substantive comments from the document', 'Add an account name to each anonymous annotation'], 0, 'Attachment metadata remains the reviewer’s responsibility.']),
  daily('daily-fuel-card', '현장 차량', 'B2', 'The field vehicle’s fuel card is limited to fuel and tolls. Repairs require the fleet office, even during travel. If a safety-critical repair cannot wait, call the emergency number first; paying personally does not guarantee reimbursement.', ['What should a driver do before an urgent repair?', ['Contact the fleet emergency service for authorization and guidance', 'Use the fuel card for any mechanical expense', 'Pay personally and assume reimbursement is automatic', 'Continue driving until the scheduled fieldwork ends'], 0, 'Emergency coordination precedes expenditure.']),
  daily('daily-reading-list', '강의 계획', 'B2', 'Items marked “recommended” provide background but are not assessed directly. However, a required article may cite a recommended source that helps explain an unfamiliar method. Students remain responsible for the method described in the required article, not every detail of the background source.', ['What can be inferred about a recommended source?', ['It may clarify required material without itself being directly assessed', 'Every detail in it automatically becomes examination content', 'It replaces the required article when the method is difficult', 'Students are prohibited from using it as background'], 0, 'Background value and assessment status differ.']),
  daily('daily-laser-sample', '분광실', 'B2', 'Reflective samples require a beam-stop check at the intended angle before laser power is raised. A safe setup at normal incidence may produce a hazardous reflection after rotation. Record the maximum approved angle range in the session log.', ['Why repeat the safety check after changing angle?', ['Rotation can redirect the reflected beam into an unsafe path', 'Normal incidence permanently disables the laser interlock', 'Reflective samples absorb all power at larger angles', 'The session log controls the physical beam direction'], 0, 'Geometry changes where reflected energy travels.']),
  daily('daily-community-copy', '지역 기록 프로젝트', 'C1', 'Community partners receive a preservation copy of each approved interview, but access restrictions travel with the copy. A partner organization may store the file locally yet cannot broaden access beyond what the participant authorized. Any proposed public excerpt requires renewed permission.', ['What remains unchanged when a partner receives a copy?', ['The participant-defined limits on who may access or reuse it', 'The physical location where every file must be stored', 'The partner’s authority to publish any chosen excerpt', 'The requirement that no preservation copy exist locally'], 0, 'Custody transfer does not widen consent.']),
  daily('daily-poster-size', '학술대회', 'B1', 'Poster boards are ninety centimeters wide. A wider poster may be folded during transport but must fit within one board when displayed. The organizers provide clips, not cutting tools, and cannot relocate neighboring posters.', ['What constraint applies to the displayed poster?', ['It must remain inside the width of its assigned board', 'It may cover part of a neighboring presentation', 'Organizers will trim it at the venue', 'Folding during travel increases the available display space'], 0, 'Transport format does not alter board dimensions.']),
  daily('daily-freezer-alarm', '냉동 보관', 'B2', 'A freezer alarm acknowledgment silences notifications but does not close the incident. Staff must enter the observed temperature, inspect the door and power status, and assign follow-up. The event closes only after temperature recovery is documented.', ['What does acknowledging the alarm fail to do?', ['Complete the incident record before recovery is verified', 'Silence repeated notifications temporarily', 'Prompt inspection of door and power conditions', 'Allow staff to record the observed temperature'], 0, 'Acknowledgment and resolution are separate states.']),
  ...readingGroup('academic-attrition', '종단연구', 'C1', 'Panel studies repeatedly observe the same participants, but attrition can change the sample over time. If departure is unrelated to outcomes after accounting for measured variables, weighting or imputation may reduce bias. If people leave because of unobserved dissatisfaction or illness, adjustment is harder. High retention alone does not guarantee validity: even modest selective loss can matter for a rare subgroup. Researchers compare responders and nonresponders using baseline information, document contact attempts, and test conclusions under plausible missing-data scenarios. Replacing leavers with new participants preserves sample size but does not restore the original longitudinal panel.', [
    ['Why can a study with high overall retention remain biased?', ['Loss concentrated in a distinctive subgroup may distort that group’s trajectory', 'Retention above half guarantees departure is random', 'Rare subgroups contribute no information to panel estimates', 'Weighting requires every participant to leave'], 0, 'Selectivity matters in addition to the percentage retained.'],
    ['Why does recruiting replacements not solve longitudinal attrition?', ['New entrants lack the original individuals’ within-person history', 'Replacement participants can never answer the same survey', 'Sample size necessarily declines when anyone is recruited', 'Baseline variables become unavailable for continuing participants'], 0, 'Cross-sectional numbers do not recreate repeated observation.'],
    ['What is the purpose of missing-data sensitivity analysis?', ['To assess how conclusions depend on plausible unobserved departure mechanisms', 'To prove nonresponders have identical outcomes to responders', 'To remove the need for documented contact attempts', 'To convert every missing value into an observed measurement'], 0, 'Sensitivity makes unverifiable assumptions visible.'],
  ]),
  ...readingGroup('academic-phylogenetic', '비교진화학', 'C1', 'Species cannot be treated as statistically independent observations because related species inherit traits from common ancestors. A correlation between body size and lifespan might arise partly because one large clade shares both. Phylogenetic comparative methods model expected covariance from the evolutionary tree. Results depend on branch lengths, trait models, and the tree’s uncertainty. Controlling for phylogeny is not simply removing history; evolutionary dependence is part of the question. Researchers may compare alternative models and integrate over many plausible trees rather than treating one estimated tree as known without error.', [
    ['Why can an ordinary species-level correlation be misleading?', ['Shared ancestry can create clustered trait similarities', 'Every species evolves independently after divergence', 'Body size prevents construction of an evolutionary tree', 'Branch lengths eliminate all measurement uncertainty'], 0, 'Genealogical dependence violates naive independence.'],
    ['Why analyze multiple plausible trees?', ['Uncertainty in evolutionary relationships can propagate into trait conclusions', 'Each trait requires a completely unrelated taxonomy', 'One tree makes branch length irrelevant', 'Comparative models cannot operate on estimated histories'], 0, 'Tree estimation is not error-free input.'],
  ]),
  ...readingGroup('academic-amphorae', '고대경제사', 'C1', 'Transport amphorae were ceramic containers designed for commodities such as wine, oil, or fish products. Shape, clay fabric, stamps, and residue can indicate production and contents, but reuse complicates interpretation. A jar made in one region might be refilled elsewhere. Shipwreck assemblages offer a snapshot of cargo, whereas port deposits accumulate through repeated activity and disposal. Counting vessel fragments without estimating how many containers they represent exaggerates easily broken forms. Distribution maps also reflect excavation intensity and publication history, not trade alone. Scholars combine typology, petrography, chemical analysis, context, and quantitative correction.', [
    ['Why can residue conflict with an amphora’s production origin?', ['The container may have been reused for a different product in another place', 'Clay fabric changes its geological source after firing', 'Stamps always identify the final commodity rather than the workshop', 'Shipwreck cargo cannot include refilled vessels'], 0, 'Manufacture and later contents need not share an origin.'],
    ['Why are raw fragment counts problematic?', ['Breakage rate can make one vessel contribute many observations', 'Every fragment necessarily comes from a separate container', 'Typology prevents pottery from breaking after disposal', 'Port deposits preserve only complete vessels'], 0, 'Sherd abundance is not equivalent to container abundance.'],
    ['What can bias a distribution map independently of ancient trade?', ['Uneven excavation and reporting across modern regions', 'Petrography identifying mineral composition', 'A shipwreck preserving one cargo event', 'Ceramic vessels being used for transport'], 0, 'Modern discovery processes shape apparent patterns.'],
  ]),
  ...readingGroup('academic-battery', '전기화학', 'C1', 'Rechargeable batteries lose capacity through several mechanisms. A protective interphase can stabilize an electrode yet consume active lithium as it grows. Fast charging may create concentration gradients or plate metallic lithium, especially at low temperature. High voltage accelerates electrolyte oxidation and structural change. Capacity measured after rest can differ from power available under load because internal resistance also rises. A single cycle count therefore does not define battery health; depth of discharge, temperature, current, storage state, and cell chemistry matter. Diagnostic tests separate loss of active material from loss of lithium inventory and impedance growth.', [
    ['Why can a protective interphase reduce usable capacity?', ['Its continued formation consumes mobile lithium even while shielding the electrode', 'It eliminates every reaction between electrode and electrolyte', 'It converts internal resistance directly into stored charge', 'It prevents any ion from entering the battery during manufacture'], 0, 'Protection has a finite inventory cost.'],
    ['Why is cycle count an incomplete health measure?', ['Operating conditions make nominally equal cycles impose different degradation', 'Every chemistry loses identical capacity per cycle', 'Storage state matters only after total failure', 'Power under load is independent of internal resistance'], 0, 'Usage history changes damage per cycle.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the cell-line profile match the reference database?', ['Yes, with no evidence of a second human line.', 'The cells grow in a serum-free medium.', 'Reference databases include several tissue types.', 'I matched the table width to the page.'], 0, 'The reply confirms identity and contamination screening.'),
  response(1, 'Why was the coastal scan postponed?', ['The scan covers twelve kilometers of shoreline.', 'Sea spray exceeded the lidar housing limit.', 'I postponed the appendix until the revised draft.', 'Coastal erosion varies with storm direction.'], 1, 'An environmental equipment limit caused postponement.'),
  response(2, 'Could replacement participants restore the panel?', ['The panel began with a representative household sample.', 'Replacements maintain the total number of interviews.', 'No, they cannot recreate the missing individuals’ earlier trajectories.', 'I restored the archived database from backup.'], 2, 'Longitudinal identity cannot be replaced by headcount.'),
  response(3, 'I assumed the vessel stamp named its contents.', ['The stamp appears near the amphora handle.', 'Contents can leave chemical residues in ceramic pores.', 'I named the output file after the experiment.', 'It may identify a workshop or official, not necessarily the commodity.'], 3, 'Stamp function must be established rather than assumed.'),
  response(4, 'May we fast-charge these cells in the cold chamber?', ['Only within the protocol designed to detect lithium plating.', 'The chamber maintains temperature within half a degree.', 'Fast charging reduces waiting time between tests.', 'I charged the travel cost to the fieldwork account.'], 0, 'Cold fast charging requires a controlled safety protocol.'),
  response(5, 'Where is the unredacted community interview?', ['The interview concerns the closure of a local factory.', 'In the restricted collection under the participant’s access terms.', 'Redaction removes several personal names.', 'I interviewed the curator near the main gallery.'], 1, 'The response identifies protected storage and authority.'),
  response(6, 'Shouldn’t phylogenetic uncertainty enter the interval?', ['The interval currently reflects trait measurement error.', 'Several branches have weak genetic support.', 'Yes, if alternative trees materially change the estimated relationship.', 'I entered the new specimen into the catalog.'], 2, 'Tree uncertainty can contribute inferential uncertainty.'),
  response(7, 'The beam reflection shifted after we rotated the sample.', ['The sample contains a polished metallic surface.', 'Rotation was recorded in five-degree steps.', 'I shifted the paragraph after reviewer feedback.', 'Recheck the stop position before increasing laser power.'], 3, 'Changed geometry requires renewed safety verification.'),
  response(8, 'Is the author identity hidden in this reviewer attachment?', ['Not until its document properties are inspected and cleaned.', 'The attachment contains comments on four figures.', 'Author names appear on the published article.', 'I hid the toolbar before sharing my screen.'], 0, 'Visible anonymity does not guarantee clean metadata.'),
  response(9, 'Why did capacity recover slightly after the battery rested?', ['The cell completed five hundred charge cycles.', 'Concentration gradients relaxed, reducing temporary voltage limitation.', 'I recovered the deleted dataset from version control.', 'Battery capacity is reported in ampere-hours.'], 1, 'Rest can reverse transient polarization without repairing degradation.'),
  response(10, 'Can the hair-side pattern identify the parchment species?', ['The pattern is clearer near the manuscript margin.', 'Parchment was stretched during manufacture.', 'It can suggest one, but protein or DNA evidence would strengthen attribution.', 'I identified the argument’s premise in the first paragraph.'], 2, 'Morphology is informative but not definitive.'),
  response(11, 'I cannot tell whether the warmer ocean layer is moving.', ['The layer has higher salinity than surface water.', 'Temperature sections are plotted by latitude.', 'I moved the legend below the map.', 'Use velocity or tracer observations; temperature alone shows property, not transport.'], 3, 'A water property does not directly establish motion.'),
  response(12, 'Has the emergency repair been authorized by fleet services?', ['Yes, and the approval number is attached to the receipt.', 'The vehicle requires a replacement belt.', 'Fleet vehicles are inspected every semester.', 'I authorized access to the shared calendar.'], 0, 'The answer confirms traceable authorization.'),
  response(13, 'When should the frozen samples enter the backup unit?', ['The backup freezer is on an independent circuit.', 'Immediately after the primary unit exceeds its transfer threshold.', 'I entered the threshold in the monitoring dashboard.', 'Frozen tissue remains stable at low temperature.'], 1, 'The response states the trigger for transfer.'),
  response(14, 'Would measuring impedance clarify the capacity loss?', ['The battery retained eighty percent of initial charge.', 'Impedance affects voltage under load.', 'Yes, it could distinguish resistance growth from lost active inventory.', 'I measured the jar diameter with digital calipers.'], 2, 'A complementary diagnostic separates mechanisms.'),
  response(15, 'Who approved public access to the interview excerpt?', ['The excerpt discusses a labor strike.', 'Public access begins after a five-year embargo.', 'The repository records each download.', 'The participant signed the revised release after reviewing the passage.'], 3, 'The participant supplied specific authorization.'),
  response(16, 'This pottery map seems empty in the eastern region.', ['Check excavation and publication coverage before inferring little trade.', 'Eastern fabrics contain abundant volcanic minerals.', 'The map symbols distinguish rims from handles.', 'I mapped the network with a force-directed layout.'], 0, 'Absence of plotted finds may reflect observation effort.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-attrition', 'Listen to a Conversation', '패널 조사', 'C1', 'Student: Retention is ninety-two percent, so I described attrition bias as negligible. Advisor: Which eight percent left? Student: Mostly renters under twenty-five. Advisor: Then overall retention hides concentrated loss. Compare their baseline outcomes, reweight where defensible, and show how conclusions change under less favorable assumptions about their missing responses.', [
    ['Why is the retention percentage misleading?', ['Departure is concentrated in a subgroup that may have a distinct trajectory', 'Eight percent is too small to affect any subgroup estimate', 'Renters cannot participate in longitudinal surveys', 'Baseline outcomes are available only after dropout'], 0, 'Composition of loss matters beyond its size.'],
    ['What does the advisor request beyond reweighting?', ['Sensitivity analysis for missing outcomes not explained by observed data', 'Replacement of all young renters with homeowners', 'Deletion of baseline information from continuing participants', 'A claim that the missing responses are favorable'], 0, 'Unmeasured selection needs explicit stress testing.'],
  ]),
  ...listeningGroup('conversation-poster', 'Listen to a Conversation', '학술 포스터', 'B2', 'Student: My poster text is readable on my laptop, but not when printed. Designer: The screen view is much smaller than the intended viewing distance. Student: Should I enlarge everything? Designer: Establish a hierarchy. Enlarge the question and main result, shorten the methods, and print one section at actual size before ordering the full poster.', [
    ['Why did the laptop preview mislead the student?', ['Screen viewing conditions did not represent physical scale and audience distance', 'Printers always reduce every font by half', 'Poster methods must never contain text', 'The main result was already larger than the title'], 0, 'Readability depends on final size and viewing context.'],
    ['Why print one section first?', ['A low-cost full-scale sample tests typography before final production', 'It automatically enlarges the remaining sections', 'It replaces the need to select a visual hierarchy', 'A partial print can display the complete poster content'], 0, 'A prototype catches scale problems economically.'],
  ]),
  ...listeningGroup('conversation-batch', 'Listen to a Conversation', '유전자 편집', 'C1', 'Researcher: The bulk sequencing shows seventy percent editing, but many cells still express the target protein. Specialist: The average may combine fully edited, partially edited, and unedited cells. Researcher: Should I sort by fluorescence? Specialist: If fluorescence accurately reports protein, yes, then genotype subpopulations separately. Also check whether in-frame repairs preserve function despite cutting.', [
    ['Why can bulk editing percentage misrepresent functional knockout?', ['Different cell genotypes and repair outcomes are averaged together', 'Protein expression always disappears after any DNA cut', 'Fluorescence cannot distinguish cells in a mixed culture', 'All repairs introduce the same frameshift mutation'], 0, 'Aggregate editing is not equivalent to uniform loss of function.'],
    ['What alternative explanation for protein persistence is mentioned?', ['Some repaired sequences may retain the reading frame and function', 'The guide RNA cannot enter any sorted cell', 'Bulk sequencing measures only unedited DNA', 'Fluorescence creates new target genes'], 0, 'Cutting can yield function-preserving alleles.'],
  ]),
  ...listeningGroup('conversation-context', 'Listen to a Conversation', '발굴 자료', 'C1', 'Archaeologist: These amphora fragments were found in fill used to level a later floor. Historian: Then their deposit date is later than their manufacture, and they may have come from elsewhere on the site. Archaeologist: Can they still inform trade? Historian: Yes, but distinguish evidence that the containers reached the settlement from evidence about activity in this particular room.', [
    ['Why is the floor context secondary?', ['The fill redeposited older material during later construction', 'The fragments were manufactured after the floor was abandoned', 'Leveling fill preserves every object in its original use location', 'Trade containers cannot enter architectural deposits'], 0, 'Redeployment separates deposition from original use.'],
    ['What conclusion remains supportable?', ['The vessel type was present at the broader settlement', 'The room certainly stored the original imported commodity', 'Every fragment arrived during one shipment', 'The floor builders produced the amphora locally'], 0, 'Site-level presence survives the loss of room-level association.'],
  ]),
  ...listeningGroup('conversation-telemetry', 'Listen to a Conversation', '해양 계류장치', 'B2', 'Technician: The mooring transmitted salinity but no velocity overnight. Oceanographer: Did the current meter fail? Technician: Its battery voltage is normal. A firmware update may have changed the output channel. Oceanographer: Check the raw packet map before sending a reset; a reset could erase the diagnostic buffer.', [
    ['What evidence argues against a power failure?', ['The current meter reports normal battery voltage', 'Salinity and velocity use one identical sensor', 'The diagnostic buffer has already been erased', 'Firmware cannot change output channels'], 0, 'The instrument appears powered despite missing data.'],
    ['Why inspect raw packets before resetting?', ['A reset may destroy evidence needed to diagnose channel mapping', 'Raw packets immediately restore velocity measurements', 'The salinity sensor requires a depleted battery', 'Firmware updates can be reversed only underwater'], 0, 'Preserve diagnostic state before intervention.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-autoclave', 'Listen to an Announcement', '멸균실', 'B2', 'Autoclave One returns to service at noon after pressure certification. Loads prepared earlier may remain on the staging rack, but liquid cycles cannot begin until the posted calibration sticker includes today’s date. Solid-waste cycles use Autoclave Two during the morning and should not be moved back once started.', [
    ['What confirms that liquid cycles may resume?', ['A calibration label showing the current date', 'The presence of loads on the staging rack', 'A solid-waste cycle already running elsewhere', 'The clock reaching morning opening time'], 0, 'Return to service requires documented calibration.'],
    ['What should happen to a cycle begun in Autoclave Two?', ['It should finish there rather than transfer mid-cycle', 'It should move to Autoclave One at noon', 'It must be converted into a liquid cycle', 'It may stop once certification begins'], 0, 'Active sterilization is not relocated.'],
  ]),
  ...listeningGroup('announcement-archive-tour', 'Listen to an Announcement', '기록관 견학', 'B1', 'The archive tour meets at the east entrance at ten. The reading room itself remains closed to the group because researchers are working, but the guide will show the conservation laboratory through the observation window. Bags may stay in the supervised classroom; valuables should remain with their owners.', [
    ['Which space will the group not enter?', ['The active reading room used by researchers', 'The classroom where bags may be left', 'The east entrance meeting point', 'The corridor beside the conservation window'], 0, 'Ongoing research requires quiet and access control.'],
    ['What should visitors keep with them?', ['Valuable personal items rather than leaving them with bags', 'Every bag while viewing through the window', 'Laboratory tools supplied by the conservator', 'Researchers’ archival materials'], 0, 'Supervision does not replace personal care for valuables.'],
  ]),
  ...listeningGroup('announcement-uav', 'Listen to an Announcement', '무인기 시험장', 'C1', 'Tomorrow’s autonomous-flight test moves to the southern range because the northern range has intermittent positioning interference. The approved altitude and emergency landing procedure are unchanged. Upload the southern geofence before arrival; devices showing the old boundary at check-in will remain grounded until reconfigured.', [
    ['What remains the same after relocation?', ['The altitude limit and emergency landing protocol', 'The geofence file stored on every device', 'The source of positioning interference', 'The range used for tomorrow’s launch'], 0, 'Operational safety limits persist across sites.'],
    ['What happens to a device with the old boundary?', ['It cannot fly until its geofence is updated', 'It receives automatic permission for the northern range', 'It may ignore check-in and launch manually', 'It is assigned a higher altitude'], 0, 'Correct spatial constraints are a preflight requirement.'],
  ]),
  ...listeningGroup('announcement-translation', 'Listen to an Announcement', '번역 낭독회', 'B2', 'Tonight’s translated-fiction reading includes the source-language text on screen. The first row is reserved for attendees using the low-vision display, not for late-arriving speakers. A downloadable bilingual booklet becomes available after the event because the publisher embargo ends at nine.', [
    ['Who may use the reserved first row?', ['Attendees requiring the accessible low-vision display', 'Speakers arriving after the reading starts', 'Anyone downloading the bilingual booklet', 'Publishers whose embargo lasts until nine'], 0, 'The reservation supports a specific access need.'],
    ['Why is the booklet released only afterward?', ['Its publication restriction expires at the stated time', 'The source-language text cannot be shown during the event', 'First-row attendees must edit it before download', 'The translation does not yet contain any bilingual material'], 0, 'An external rights window controls release.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-snow', 'Listen to an Academic Talk', '빙설기후학', 'C1', 'Fresh snow reflects most incoming sunlight, but its albedo declines as grains grow, impurities accumulate, or meltwater appears. Dark dust or soot absorbs energy and can accelerate melt, exposing darker ground that absorbs still more. This feedback depends on timing: an impurity deposited near the melt season may matter more than one buried by later snowfall. Satellites estimate surface reflectance over broad areas, while field measurements reveal grain size and impurity concentration. Clouds and viewing geometry complicate direct comparison.', [
    ['Why does the timing of impurity deposition matter?', ['Later clean snow may bury dark particles before strong melting begins', 'Soot always increases reflection after one day', 'Grain growth prevents any particle from absorbing light', 'Ground exposure occurs before snow is deposited'], 0, 'Surface availability during high energy input controls impact.'],
    ['Why combine satellite and field observations?', ['They provide complementary spatial coverage and physical detail', 'Field instruments can observe every snowfield simultaneously', 'Satellite reflectance directly identifies each impurity chemical', 'Clouds improve agreement between all methods'], 0, 'Scale and mechanism require different measurements.'],
  ]),
  ...listeningGroup('talk-signal-game', 'Listen to an Academic Talk', '행동생태학', 'C1', 'Animal signals can remain reliable when dishonesty carries costs or when interests overlap. A low-quality individual might be physically unable to produce an intense display, making it an index. In other cases, a signal is cheap to produce but costly to use dishonestly because receivers retaliate or test the claim. Reliability is not perfect honesty in every interaction. Researchers examine production constraints, receiver response, and the fitness consequences of deception rather than assuming conspicuous traits automatically reveal quality.', [
    ['How can a cheap signal remain reliable?', ['Social penalties or verification can make dishonest use unprofitable', 'Receivers never respond to deceptive displays', 'Only physically impossible signals convey information', 'Shared interests require signals to be costly to produce'], 0, 'Enforcement can stabilize honesty without production expense.'],
    ['What evidence is needed beyond signal conspicuousness?', ['A mechanism connecting display variation to constraints or consequences', 'Proof that every receiver ignores the display', 'A record of perfect honesty across all animals', 'Elimination of any fitness effect from deception'], 0, 'Visibility alone does not explain reliability.'],
  ]),
  ...listeningGroup('talk-charters', 'Listen to an Academic Talk', '문서사', 'C1', 'Medieval charters record grants, privileges, or transactions, but surviving copies have varied authority. An original may carry seals and witness marks; a cartulary copy was entered into a later institutional book. Later copying does not make a text useless, yet scribes could abbreviate, modernize, or select documents that supported current claims. Formulaic language helps identify document types but can also be imitated in forgeries. Historians compare handwriting, material, diplomatic form, transmission, and external events rather than accepting every dated clause at face value.', [
    ['Why can a cartulary copy still be historically useful?', ['It transmits content and shows what a later institution considered worth preserving', 'It is necessarily identical to a sealed original in every detail', 'Later scribes had no reason to select documents strategically', 'A copied charter cannot contain any dated information'], 0, 'Transmission has evidentiary value despite mediation.'],
    ['Why is formulaic language not proof of authenticity?', ['Forgeries can reproduce conventional document forms', 'Authentic charters never use recurring phrases', 'Witness marks appear only in modern copies', 'Handwriting cannot be compared across documents'], 0, 'Convention can be both genuine practice and imitation.'],
  ]),
  ...listeningGroup('talk-phoneme-restoration', 'Listen to an Academic Talk', '언어지각', 'C1', 'In phoneme restoration, listeners report hearing a speech sound that was replaced by noise when sentence context strongly predicts it. The illusion shows that perception integrates acoustic input with linguistic expectation. It does not mean listeners simply ignore sound: restoration weakens when the noise is acoustically implausible or the context supports several words. Researchers compare identification, confidence, and neural timing to determine when top-down information influences interpretation.', [
    ['What does the restoration illusion demonstrate?', ['Language expectations can fill an ambiguous gap in the acoustic signal', 'Listeners consciously invent every sound in a sentence', 'Noise improves identification regardless of context', 'Acoustic plausibility has no effect on perception'], 0, 'Perception combines signal and prediction.'],
    ['Why test contexts with several possible words?', ['Lower predictability reveals how strongly expectation drives the missing sound', 'Multiple candidates guarantee perfect restoration', 'Ambiguity removes the need for acoustic information', 'Neural timing cannot be measured in a predictable sentence'], 0, 'Contextual constraint is an experimental variable.'],
  ]),
  ...listeningGroup('talk-queues', 'Listen to an Academic Talk', '운영과학', 'C1', 'Queueing systems are governed not only by average arrival and service rates but also by variability. If customers arrive in bursts or service times vary widely, waits can grow even when average capacity exceeds average demand. High utilization leaves little buffer for random fluctuations. Pooling several servers into one line often reduces unequal waits, though specialized tasks or priority rules may limit pooling. Analysts model distributions and service discipline rather than concluding that an average five-minute service guarantees five-minute waiting.', [
    ['Why can waiting be long when average capacity is sufficient?', ['Random bursts and variable service create temporary backlogs', 'Average service time equals every individual wait', 'High utilization provides extra unused buffer', 'Pooling always increases unequal server workloads'], 0, 'Variability causes congestion around averages.'],
    ['How can a single pooled line improve performance?', ['It directs the next available server to the longest shared demand stream', 'It forces every service task to take equal time', 'It eliminates all priority and specialization constraints', 'It raises utilization by keeping some servers idle'], 0, 'Pooling shares capacity across arrivals.'],
  ]),
  ...listeningGroup('talk-piezoelectric', 'Listen to an Academic Talk', '재료물리학', 'C1', 'Piezoelectric materials generate electric polarization when mechanically strained, and conversely deform when an electric field is applied. The effect requires a crystal or aligned domain structure lacking inversion symmetry. Sensors exploit the direct effect; actuators use the converse effect. Ceramic materials can be strong but brittle, while polymers may be flexible with weaker response. Performance also depends on direction, frequency, temperature, and electrical loading. A high coefficient measured in one laboratory mode does not guarantee the best device under operational constraints.', [
    ['What structural condition enables piezoelectric response?', ['An asymmetric arrangement that permits strain to shift charge centers', 'Perfect inversion symmetry in every crystal direction', 'Complete electrical conductivity under mechanical load', 'Random domains that cancel no polarization'], 0, 'Broken centrosymmetry allows net polarization.'],
    ['Why is one high material coefficient insufficient for device selection?', ['Mechanical durability and operating conditions also determine usable performance', 'Direct and converse effects cannot occur in one material', 'Flexible polymers always produce a stronger response than ceramics', 'Frequency has no influence on electromechanical behavior'], 0, 'System requirements extend beyond a single metric.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why did the panel estimate change?', 'Had the departing renters remained observable', ['the apparent improvement', 'might have been', 'less pronounced', 'among younger households'], 'f19-had-remained-modal-perfect'],
  ['What did the amphora analysis reveal?', 'Scattered across several secondary deposits were', ['fragments', 'whose shared fabric', 'pointed to', 'one production region'], 'f19-participle-locative-inversion'],
  ['Why distrust the apparent battery recovery?', 'However much capacity returned after rest', ['the underlying', 'resistance growth', 'was unlikely', 'to have reversed'], 'f19-however-much-concessive-perfect'],
  ['What strengthened the phylogenetic result?', 'The association persisted regardless of which plausible tree', ['was used', 'to model', 'covariance among', 'the species'], 'f19-regardless-of-embedded-relative'],
  ['When did the metadata risk become clear?', 'Not until the reviewer exported the attachment', ['did the hidden', 'author field', 'appear in', 'the document properties'], 'f19-not-until-past-inversion'],
  ['Why preserve the raw telemetry?', 'Were the instrument reset before its packet map was copied', ['the evidence', 'needed to diagnose', 'the missing channel', 'would disappear'], 'f19-were-passive-before-clause'],
  ['What made the trade map uncertain?', 'So uneven was excavation coverage that', ['regional absences', 'could as easily reflect', 'modern research', 'as ancient exchange'], 'f19-so-adjective-inversion-as-easily'],
  ['Why was the repair request denied?', 'The driver had paid without first having contacted', ['the emergency office', 'whose authorization', 'the reimbursement policy', 'required'], 'f19-perfect-gerund-contact-relative'],
  ['How should the historical copy be treated?', 'While not carrying the authority of the sealed original', ['it can reveal', 'which claims', 'the later institution', 'sought to preserve'], 'f19-reduced-concessive-while'],
  ['Why did the team limit fast charging?', 'Such were the gradients predicted at low temperature that', ['continuing the protocol', 'would have risked', 'metallic lithium', 'plating'], 'f19-such-inversion-past-modal'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '패널 조사 이탈', 'C1', 420), instruction: '표본 변화의 증거, 추론 위험, 분석 및 추적 절차를 구체적으로 작성하세요.', prompt: 'You notice that most participants lost from a longitudinal housing survey are young renters, although the project report describes overall retention as excellent. Write to the survey director. Explain why the pattern matters, request subgroup diagnostics and sensitivity analyses, and propose a retention-documentation step for the next wave.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '과학 장비의 자동화', 'C1', 600), instruction: '효율성, 전문성 유지, 책임 소재를 구체적인 조건과 함께 평가하세요.', prompt: 'Professor Njeri: Should research laboratories rely more heavily on automated instruments that make complex analytical decisions with little operator intervention?', passage: 'Daniel: Automation improves consistency and lets more researchers use advanced methods.\nFarah: Users may accept outputs they cannot diagnose, allowing hidden calibration or model errors to spread.' })

const repeatSentences = ['Welcome to the autonomous field-vehicle test range.', 'Confirm that today’s geofence appears on the control tablet.', 'Inspect the wheels, antenna, and emergency stop before deployment.', 'Keep observers outside the marked route while the vehicle is moving.', 'Monitor both battery reserve and positioning confidence during the run.', 'Use the manual stop if the rover approaches an unapproved boundary.', 'After the test, recover the raw telemetry, record every intervention, and compare the actual path with the approved route before clearing the vehicle.']
const interviewQuestions = ['Describe a task in which people increasingly rely on automated decisions.', 'What benefit does automation provide in that task?', 'What error might users fail to notice if they trust the system too much?', 'How should responsibility be divided between a system designer and the person using its recommendation?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '자율 주행 시험장', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f19-repeat', scenarioId: 'f19-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '자동화와 책임', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f19-interview', scenarioId: 'f19-interview', sequenceIndex })),
]

export const AUTHORED_FORM_19_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_19_IDS = AUTHORED_FORM_19_ITEMS.map((item) => item.id)
