import { createAuthoredFormHelpers } from './authoredFormHelpers'
import type { SentenceDatum } from './authoredFormHelpers'
import type { BaseItem } from './types'

const { base, cloze, daily, readingGroup, response, listeningGroup, sentenceItems, orderedForm } = createAuthoredFormHelpers('f18')

const reading: BaseItem[] = [
  cloze('cloze-karst', '수문지질학', 'C1', 'Karst landscapes develop where slightly acidic water dissolves soluble rock such as limestone. Water enf___ fractures, enlarging them into conduits, caves, and sinkholes. Surface streams may dis___ underground and reemerge at springs far away. Because flow can be rapid and poorly filtered, contaminants may tra___ long distances with little warning. Conventional watershed boundaries based on topography may not mat___ subsurface drainage. Hydrologists inject harmless tracers and mon___ springs to map connections. Results depend on season because high water can act___ routes that remain dry at low flow. Pumping or construction may red___ hydraulic gradients and alter spring discharge. Collapse risk rises where cavities approach the surface, but not every depression ind___ an active void. Researchers comb___ geophysics, drilling, water chemistry, and historical records to assess hazards without overinf___ from one signal.', 'ters|appear|vel|ch|itor|ivate|irect|icates|ine|erring'),
  cloze('cloze-radiation', '대기물리학', 'C1', 'Earth’s climate depends on the balance between absorbed sunlight and outgoing thermal radiation. Greenhouse gases are largely trans___ to incoming visible light but absorb selected infrared wavelengths. They emit radiation in all directions, so increasing their concentration moves effective emission to colder, higher layers and red___ energy escaping to space until temperature adjusts. Clouds can both refl___ sunlight and trap infrared energy. Their net effect dep___ on altitude, thickness, droplet size, and surface conditions. Satellite instruments mea___ radiance across wavelengths rather than temperature directly. Retrieval algorithms inf___ atmospheric properties using physical models and auxiliary observations. Aerosols, viewing angle, and overlapping absorption can conf___ the inference. Scientists comp___ instruments, validate against field data, and quan___ uncertainty. A regional short-term imbalance does not alone determ___ the planet’s long-run response.', 'parent|uces|ect|ends|sure|er|ound|are|tify|ine'),
  cloze('cloze-parchment', '기록재료사', 'B2', 'Parchment is made from animal skin that is limed, dehaired, stretched, and scraped rather than tanned. Drying under tension al___ collagen fibers and creates a firm writing surface. The flesh and hair sides may dif___ in texture and follicle pattern. Makers could thin or whiten sheets, while scribes rul___ lines before writing. Moisture causes parchment to sw___ and distort because the material remains hygroscopic. Repeated humidification may erase manufacturing evidence or weak___ pigments. Conservators support distorted leaves and cont___ humidity gradually. Species identification can use protein or DNA traces, but sampling and contamination must be cons___. A fine sheet does not prove a particular geographic origin because materials and skills cir___ through trade. Scholars integ___ codicology, handwriting, decoration, and material analysis to rec___ production and later rebinding.', 'igns|fer|ed|ell|en|rol|idered|culated|rate|onstruct'),
  daily('daily-crystal-mount', '결정학 실험', 'B2', 'Mounted crystals are stored in numbered pucks under liquid nitrogen. A puck may be transferred between dewars only after both inventory locations are open on screen. Closing the source record before confirming the destination can make the sample temporarily untraceable.', ['What prevents a crystal from becoming untraceable?', ['Keeping both location records active until the transfer is confirmed', 'Closing the original record before selecting a destination', 'Removing the puck number from the inventory display', 'Allowing the liquid nitrogen to evaporate during transfer'], 0, 'Overlapping records preserve continuity of location.']),
  daily('daily-reserve-scan', '강의 자료', 'B2', 'Course-reserve staff scan only the pages listed in the instructor’s request. Adding a chapter after the scan is complete requires a new copyright review, even when the book remains on reserve. Page ranges cannot be expanded through a handwritten note at pickup.', ['What is required to add another chapter?', ['A new review of the expanded copying request', 'A handwritten amendment when collecting the book', 'Removal of the original volume from reserve', 'Automatic approval because one scan already exists'], 0, 'Permission depends on the specific copied extent.']),
  daily('daily-rover-battery', '현장 로봇', 'B2', 'The survey rover returns automatically when estimated battery capacity reaches twenty percent. Disabling the return setting is permitted only during a supervised calibration on the test field. A steep route may consume power faster than the remaining-distance display predicts.', ['Why should operators be cautious on a steep route?', ['Terrain can make the distance-based estimate understate energy demand', 'Automatic return increases battery capacity above full charge', 'Calibration is allowed only on an unsupervised field route', 'The rover consumes no power while climbing slowly'], 0, 'Energy use depends on load and terrain, not distance alone.']),
  daily('daily-fragment-box', '고고학 보관', 'B2', 'Pottery fragments from different stratigraphic contexts must not share a bag, even if they join physically. Researchers may document a cross-context fit with photographs and linked records. Combining the fragments would erase evidence about where each piece was recovered.', ['How should a cross-context fit be recorded?', ['With linked documentation while retaining separate provenience bags', 'By merging all joining pieces into one unlabeled container', 'By replacing excavation context with the reconstructed vessel number', 'With adhesive before either fragment is photographed'], 0, 'The relationship can be documented without losing provenience.']),
  daily('daily-interpretation-booth', '통역 시설', 'B1', 'Interpretation booths open thirty minutes before the conference session. Speakers should submit last-minute terminology at the technician desk, not directly through the booth window. Interpreters need quiet preparation, and the audio channel is tested during that period.', ['Where should a speaker deliver new terminology?', ['At the technician desk outside the booth', 'Through the booth window during audio testing', 'On the stage after interpretation begins', 'Inside the audience seating area'], 0, 'The desk mediates material delivery without disrupting preparation.']),
  daily('daily-clinical-code', '임상 데이터', 'C1', 'A diagnostic code may reflect billing practice rather than a confirmed disease. Researchers defining a clinical outcome should validate the algorithm against charts or combine repeated codes, medication, and laboratory evidence. Counting one isolated code as a case can inflate prevalence.', ['Why is one diagnostic code insufficient evidence?', ['It may have been recorded for administrative reasons without confirmed illness', 'Billing records never contain information related to health', 'Repeated codes necessarily refer to different patients', 'Laboratory results cannot contribute to outcome validation'], 0, 'Administrative purpose can differ from clinical truth.']),
  daily('daily-greenhouse-key', '온실 출입', 'B2', 'After-hours greenhouse access requires both a programmed key card and an active lone-worker check-in. The card opens the door but does not initiate monitoring. Users must start the check-in through the safety application before entering and close it after leaving.', ['What does the key card fail to initiate?', ['The separate safety monitoring session for a lone worker', 'Physical access through the greenhouse entrance', 'Programming of the authorized entry period', 'Closure of the door behind the researcher'], 0, 'Access control and personnel monitoring are independent.']),
  daily('daily-image-alt', '디지털 전시', 'B2', 'Alternative text should describe the information an image contributes in its context, not every visible detail. A decorative border can be marked decorative, while a graph needs its trend and relevant axes summarized. Captions and alternative text may complement rather than duplicate one another.', ['What should alternative text for a graph prioritize?', ['The relationship and labeled quantities needed to understand its point', 'An exhaustive inventory of every pixel and grid line', 'A repetition of the caption without additional context', 'The decorative qualities of the page border alone'], 0, 'Functional information guides accessible description.']),
  daily('daily-travel-receipt', '연구비 정산', 'B2', 'A foreign-currency receipt must be paired with the card statement or the university’s approved exchange-rate record. A handwritten conversion is not sufficient. When a card bundles several purchases, highlight the relevant transaction without obscuring the others.', ['How should a foreign-currency amount be supported?', ['With an approved or independently documented conversion source', 'By writing an estimated local amount on the receipt', 'By hiding every unrelated transaction on the card statement', 'With a verbal explanation after the account closes'], 0, 'Conversion requires auditable evidence.']),
  daily('daily-audio-level', '음성 자료 수집', 'B2', 'Interview recorders should be level-tested with the participant speaking naturally, not by tapping the microphone. Tapping may overload the input while saying little about conversational volume. Preserve a short test clip so later reviewers can distinguish setup problems from changes during the interview.', ['Why is microphone tapping a poor level test?', ['Its signal does not represent the participant’s ordinary speech level', 'It permanently deletes the first interview segment', 'Natural speech cannot reveal input overload', 'A saved test clip prevents any later equipment change'], 0, 'The calibration source should resemble the target signal.']),
  ...readingGroup('academic-survival', '생존분석', 'C1', 'Survival analysis studies time until an event while accounting for observations whose exact event time is unknown. Right censoring occurs when a participant has not yet experienced the event by the study’s end or is lost to follow-up. Such a participant still contributes information up to the last observation. Standard methods often assume censoring is independent of the event process after conditioning on modeled variables. If sicker participants leave disproportionately for unmeasured reasons, estimated survival may be biased upward. Competing events create another issue: death from another cause can prevent the target event rather than merely delay its observation.', [
    ['Why should a censored participant not simply be deleted?', ['The observed event-free period still constrains the possible event time', 'Censoring proves the participant never experiences the event', 'Deletion makes censoring independent by definition', 'The last observation always equals the true event date'], 0, 'Partial follow-up contains valid timing information.'],
    ['How can informative loss to follow-up bias survival estimates?', ['Departure related to unmeasured health can make remaining participants unrepresentative', 'Every lost participant necessarily has the target event immediately', 'Conditioning on measured variables creates all censoring', 'Independent censoring lowers observed survival to zero'], 0, 'Selection from unobserved risk distorts the curve.'],
    ['Why is a competing event not ordinary censoring?', ['It can make the target event impossible rather than leave its later time unknown', 'It always occurs after the target event has been observed', 'Competing risks provide no information about participant status', 'It guarantees independence from every modeled covariate'], 0, 'The alternative event changes the set of possible outcomes.'],
  ]),
  ...readingGroup('academic-trophic', '군집생태학', 'C1', 'A trophic cascade occurs when changes in predators indirectly affect organisms several feeding levels away. Removing a predator may release herbivores, which then reduce vegetation. Yet the strength and direction of cascades depend on food-web complexity, predator behavior, alternative prey, plant defenses, and habitat. Density alone can mislead: predators may alter prey foraging without changing prey abundance, producing a behaviorally mediated cascade. Evidence is stronger when experiments or natural comparisons trace linked changes across levels rather than observing vegetation recovery after predator return and assuming one pathway.', [
    ['How can predators affect plants without reducing herbivore numbers?', ['They may change where or when herbivores feed', 'They eliminate every alternative prey species', 'They make plant defenses chemically impossible', 'They convert a complex food web into one feeding link'], 0, 'Risk effects can alter consumption behavior.'],
    ['Why is vegetation recovery alone weak evidence of a cascade?', ['Other environmental changes may explain recovery unless intermediate links are demonstrated', 'Plant abundance cannot respond to herbivore feeding', 'Predator return always reduces every prey population', 'Natural comparisons are incapable of tracing mechanisms'], 0, 'A coincident outcome does not identify the causal chain.'],
  ]),
  ...readingGroup('academic-seals', '비잔틴 행정사', 'C1', 'Lead seals attached to documents carried names, titles, religious images, and institutional claims. The document itself often decayed while the durable seal survived. A seal can identify an office or sender, but it may be found far from where it was issued because the letter traveled. Titles changed over a career, and old seal matrices could be reused. Scholars compare iconography, lettering, find context, and dated officeholders. A large number of seals from one site may indicate administrative activity, discarded correspondence, collection, or later redistribution; counting them does not directly measure the size of a bureaucracy.', [
    ['Why does a seal’s find location not necessarily identify its place of production?', ['The sealed communication could travel before the lead object was deposited', 'Lead cannot preserve any information about an issuing office', 'Documents always remained beside the person who sealed them', 'Religious images were restricted to one city'], 0, 'Administrative objects move with correspondence.'],
    ['How can a title help and complicate dating?', ['It links to a career phase, but reuse and uncertain tenure can widen the range', 'Every official retained one title for life', 'A seal matrix was destroyed after a single impression', 'Lettering provides an exact calendar date by itself'], 0, 'Prosopography is informative but not automatically precise.'],
    ['Why should seal counts be interpreted cautiously?', ['Accumulation and redistribution processes can differ from institutional scale', 'Every recovered seal represents a separate government department', 'Discarded correspondence contains no administrative evidence', 'A collection cannot move archaeological material between sites'], 0, 'Deposit formation mediates the numerical pattern.'],
  ]),
  ...readingGroup('academic-metamaterials', '전자기재료', 'C1', 'Metamaterials derive unusual electromagnetic behavior from engineered structures smaller than the wavelength of interest. Their effective properties depend on geometry and arrangement as well as constituent substances. Resonant units can produce negative effective parameters over limited frequency ranges, enabling unusual refraction or compact antennas. Such effects are not magic invisibility: absorption, narrow bandwidth, fabrication error, and scale constrain performance. An effective-medium description also fails when structural units are not sufficiently small relative to wavelength. Researchers therefore distinguish a striking demonstration under controlled illumination from a practical device operating across angles, frequencies, and environmental conditions.', [
    ['What primarily creates a metamaterial’s unusual response?', ['Subwavelength architecture that organizes interaction with electromagnetic fields', 'A chemical element with negative mass at every frequency', 'Structures larger than all incident wavelengths', 'Elimination of resonance from the constituent units'], 0, 'Designed geometry produces emergent effective behavior.'],
    ['Why might a laboratory cloaking result have limited practical scope?', ['Losses, bandwidth, viewing conditions, and fabrication tolerance restrict operation', 'Controlled illumination guarantees performance from every direction', 'Effective-medium models become exact at larger structural scales', 'Absorption improves invisibility across all frequencies'], 0, 'Demonstration conditions may be narrow and idealized.'],
  ]),
]

const responses: BaseItem[] = [
  response(0, 'Did the dewar inventory reflect yesterday’s puck transfer?', ['Yes, both source and destination records were reconciled.', 'The dewar holds six cylindrical canisters.', 'Crystal pucks are numbered around the rim.', 'I transferred the paragraph to the appendix.'], 0, 'The response confirms matched location records.'),
  response(1, 'Why was the clinical cohort suddenly smaller?', ['The cohort spans five admission years.', 'A revised algorithm required two diagnostic confirmations.', 'I made the font smaller in the table.', 'Clinical records contain several code systems.'], 1, 'A stricter outcome definition reduced inclusion.'),
  response(2, 'Could the other cause of death be treated as censoring?', ['The study follows participants for ten years.', 'Cause-of-death codes come from a registry.', 'Not if it permanently prevents the event we are modeling.', 'I treated the instrument as if it were calibrated.'], 2, 'A competing event changes event possibility.'),
  response(3, 'I thought the registration included the field excursion.', ['The excursion examines coastal erosion features.', 'Registration closes once the bus is full.', 'I included the signed form in the envelope.', 'The lectures are covered, but the excursion needs a separate ticket.'], 3, 'The response distinguishes components of registration.'),
  response(4, 'May I unfold this parchment leaf for imaging?', ['Only after a conservator relaxes and supports the crease.', 'The parchment contains a faded marginal drawing.', 'Imaging works best with a calibrated color target.', 'I unfolded the statistical argument in the discussion.'], 0, 'Physical preparation requires conservation care.'),
  response(5, 'Where are the raw pressure readings from the wind tunnel?', ['The tunnel reaches a maximum speed of forty meters per second.', 'In the immutable run folder beneath the calibration record.', 'Pressure coefficients are dimensionless ratios.', 'I read the preliminary report on the train.'], 1, 'The response identifies protected raw storage.'),
  response(6, 'Shouldn’t the coders be blind to patient outcomes?', ['The coders classify narrative clinical notes.', 'Outcome data arrive from the hospital registry.', 'Yes, if outcome knowledge could influence ambiguous classifications.', 'I coded the blind samples with random letters.'], 2, 'Blinding reduces expectation-dependent judgment.'),
  response(7, 'The shipment seal number differs by one digit.', ['The shipment contains three insulated containers.', 'Seal numbers appear on both sides of the form.', 'I differed with the reviewer about the conclusion.', 'Stop the handoff until the sender verifies the discrepancy.'], 3, 'Custody should pause when identifiers conflict.'),
  response(8, 'Is the rooftop antenna available during the storm watch?', ['No, outdoor access resumes after the safety notice clears.', 'The antenna tracks radio sources automatically.', 'Storm watches are issued by the weather service.', 'I watched the calibration video last night.'], 0, 'Safety status closes outdoor access.'),
  response(9, 'Why did the reconstructed survival curve drop earlier?', ['The curve displays confidence limits as dotted lines.', 'Late adverse events were linked from a second registry.', 'I dropped the damaged sample from the rack.', 'Survival analysis handles incomplete observation times.'], 1, 'Additional events changed the timing distribution.'),
  response(10, 'Can the seal impression identify the issuing official?', ['The impression shows a figure holding a cross.', 'Officials used titles that changed through time.', 'Possibly, if the title and iconography match a documented tenure.', 'I identified the alloy with portable spectroscopy.'], 2, 'Identification requires a convergent historical match.'),
  response(11, 'I cannot reproduce the reported airflow coefficient.', ['The coefficient compares two pressure measurements.', 'Airflow becomes turbulent above a threshold.', 'I reproduced the manuscript image with permission.', 'Confirm whether the paper normalized by the inlet or local velocity.'], 3, 'Normalization choice can explain the mismatch.'),
  response(12, 'Has the revised consent translation been approved?', ['Yes, and its version number now matches the source form.', 'The consent interview lasts about fifteen minutes.', 'Translation review included two bilingual staff members.', 'I approved the invoice after checking the total.'], 0, 'The reply confirms alignment and approval.'),
  response(13, 'When will the repaired audio channel be tested?', ['The channel carries interpretation in Spanish.', 'During tomorrow’s empty-room sound check.', 'I tested the hypothesis with a permutation procedure.', 'Audio interfaces have four balanced outputs.'], 1, 'The answer specifies the test session.'),
  response(14, 'Would inverse-probability weighting address dropout?', ['Dropout occurred after the second follow-up visit.', 'The weights depend on estimated observation probability.', 'It may, if measured history adequately predicts remaining under observation.', 'I weighted the paper corners during humidification.'], 2, 'Validity depends on the observation model and measured predictors.'),
  response(15, 'Who may unlock the cabinet containing export-controlled maps?', ['The cabinet uses an electronic audit lock.', 'Export restrictions apply to high-resolution coordinates.', 'The maps are stored flat in archival folders.', 'The designated compliance custodian must approve and record entry.'], 3, 'The authorized custodian controls access.'),
  response(16, 'This simulated lens bends light opposite to the prototype.', ['Check whether the model uses the intended sign convention for its effective index.', 'The prototype contains repeating metallic elements.', 'Light bends when its speed changes across a boundary.', 'I simulated the interview before collecting data.'], 0, 'A convention mismatch may reverse the displayed direction.'),
]

const conversations: BaseItem[] = [
  ...listeningGroup('conversation-censoring', 'Listen to a Conversation', '생존분석', 'C1', 'Student: I marked everyone lost to follow-up as surviving through the end of the study. Advisor: That assumes they remained event-free after their last contact. Student: Should I mark the event at dropout instead? Advisor: No. Censor them at last known status, then examine whether dropout predictors suggest the independent-censoring assumption is plausible.', [
    ['What is wrong with treating lost participants as surviving to study end?', ['It invents event-free time after their final observed status', 'It discards all information collected before dropout', 'It records an event exactly when each participant leaves', 'It guarantees censoring is related to health'], 0, 'Unobserved follow-up cannot be counted as known survival.'],
    ['What does the advisor recommend evaluating?', ['Whether observed factors linked to dropout also indicate differential event risk', 'Whether every censored participant experienced the event immediately', 'Whether the study end can be moved to the earliest dropout', 'Whether follow-up time should be ignored in all analyses'], 0, 'Dropout mechanisms bear on censoring validity.'],
  ]),
  ...listeningGroup('conversation-exhibit-route', 'Listen to a Conversation', '전시 동선', 'B2', 'Curator: Visitors keep entering the climate gallery through its exit and miss the introductory map. Designer: The exit sign is visible from the stairs, while the entrance is hidden behind the temporary wall. Curator: Can we add more text? Designer: First redirect sightlines with a floor marker and move the entrance sign. If confusion remains, then revise the wording.', [
    ['What is the designer’s initial diagnosis?', ['Visibility and spatial cues are guiding visitors to the wrong doorway', 'The introductory map contains too little written explanation', 'Visitors intentionally skip every climate exhibit', 'The stairs prevent any sign from being moved'], 0, 'Wayfinding geometry precedes copy comprehension.'],
    ['Why delay rewriting the text?', ['The problem may be solved by making the intended route perceptually clear', 'Written labels cannot influence museum movement', 'Floor markers require the removal of the introduction', 'The exit must remain more visible than the entrance'], 0, 'Test the likely spatial cause first.'],
  ]),
  ...listeningGroup('conversation-spectrum', 'Listen to a Conversation', '원격탐사', 'C1', 'Researcher: My surface-temperature map is colder wherever clouds appear. Analyst: The retrieval should mask thick clouds, but thin cirrus may pass the quality flag and reduce measured infrared radiance. Researcher: Can I correct those pixels using the visible image? Analyst: Use the multispectral cloud probability and report sensitivity to stricter thresholds; visible brightness alone confuses cloud with snow and reflective ground.', [
    ['Why might cloudy pixels appear artificially cold?', ['Undetected thin cloud alters the infrared signal used by the retrieval', 'Clouds always make the physical surface colder by the same amount', 'Quality flags remove all clear-sky observations', 'Visible images directly measure thermal radiation'], 0, 'Cirrus contamination biases inferred surface temperature.'],
    ['Why is visible brightness an insufficient correction?', ['Several bright surfaces can resemble cloud in a single visible band', 'Snow emits no infrared radiation at any temperature', 'Multispectral probabilities contain no cloud information', 'Reflective ground is always warmer than surrounding terrain'], 0, 'Spectral ambiguity requires additional bands.'],
  ]),
  ...listeningGroup('conversation-rights', 'Listen to a Conversation', '공연 녹음 권리', 'C1', 'Student: The composer gave us permission to perform the piece. May I post our concert recording? Librarian: Performance permission does not necessarily include synchronization or online distribution. Student: The event was free. Librarian: Price is not decisive. Check the license and obtain recording rights from the relevant holders before uploading.', [
    ['Which distinction did the student overlook?', ['Authorization to perform does not automatically authorize online recording distribution', 'Free concerts cannot use any copyrighted composition', 'Synchronization rights apply only to printed programs', 'A composer always controls every right after assigning a publisher'], 0, 'Different uses require distinct permissions.'],
    ['Why does free admission not settle the issue?', ['Copyright scope depends on the licensed use rather than ticket price alone', 'No-cost events transfer recordings into the public domain', 'Online distribution is permitted only after selling tickets', 'The librarian sets admission prices for all performances'], 0, 'Noncommercial status is not equivalent to authorization.'],
  ]),
  ...listeningGroup('conversation-duplicate', 'Listen to a Conversation', '생물표본 기록', 'B2', 'Assistant: Two jars have different specimen numbers but identical collection details and photographs. Manager: They may be duplicate records created during migration, or two organisms collected together. Assistant: Should I merge them? Manager: Not yet. Compare the original ledger and preservation notes. A mistaken merge is harder to reverse once transactions attach to the combined record.', [
    ['What ambiguity must be resolved?', ['Whether the records duplicate one object or represent two related specimens', 'Whether the photographs were taken with identical cameras', 'Whether migration always creates new physical jars', 'Whether collection details should be removed from both records'], 0, 'Matching metadata has more than one explanation.'],
    ['Why postpone merging?', ['Later record activity can make an incorrect combination difficult to undo', 'Original ledgers never distinguish multiple specimens', 'Preservation notes must be deleted before migration', 'Separate identifiers prevent any comparison'], 0, 'Record consolidation has downstream consequences.'],
  ]),
]

const announcements: BaseItem[] = [
  ...listeningGroup('announcement-microtomography', 'Listen to an Announcement', 'CT 촬영실', 'C1', 'The microtomography room reopens Tuesday with a new shielding interlock. Existing radiation training remains valid, but independent users must complete a five-minute door test. Until the test is recorded, reservations may proceed only with imaging staff present. Walk-in tests are offered at the start of each hour.', [
    ['What must established users complete?', ['A brief practical check of the new door interlock', 'The full radiation course from the beginning', 'An advance reservation for every hourly test', 'A written exemption from imaging staff presence'], 0, 'The changed control requires targeted verification.'],
    ['What is allowed before verification?', ['A scheduled scan supervised by imaging staff', 'Independent entry using the previous procedure', 'Disabling the shielding system during a reservation', 'Conducting door tests without any staff record'], 0, 'Supervision permits temporary continuity.'],
  ]),
  ...listeningGroup('announcement-bridge', 'Listen to an Announcement', '보행 통로', 'B1', 'The river bridge closes to bicycles from noon to four during surface repair. Pedestrians may use the west walkway, but must follow flaggers at the narrow section. Cyclists should take the canal route; walking a bicycle across still counts as bicycle access and is not permitted.', [
    ['Who may use the west walkway during repair?', ['Pedestrians who follow directions at the narrowed area', 'Cyclists pushing their bicycles by hand', 'Repair vehicles without flagger guidance', 'Canal-route users seeking a shorter bicycle crossing'], 0, 'The route remains pedestrian-only.'],
    ['What should cyclists do instead?', ['Use the detour beside the canal', 'Carry bicycles through the narrow section', 'Wait on the bridge’s west walkway', 'Ignore the noon closure if moving slowly'], 0, 'A dedicated alternate bicycle route is provided.'],
  ]),
  ...listeningGroup('announcement-seeds', 'Listen to an Announcement', '종자 발아실', 'B2', 'Growth Chamber Five will be dark for lamp replacement Wednesday. Experiments requiring darkness may remain, but staff will not guarantee temperature uniformity while the ventilation panel is open. Light-dependent trials must move by Tuesday evening, and every relocated tray needs its new shelf entered in the experiment log.', [
    ['Which experiment may remain in Chamber Five?', ['A dark treatment that can tolerate uncertain temperature uniformity', 'A light-dependent trial with no alternate shelf', 'Any tray whose location is absent from the log', 'A temperature-critical assay requiring stable ventilation'], 0, 'Remaining work must fit both dark and thermal conditions.'],
    ['What must accompany relocation?', ['An updated record of the tray’s actual shelf position', 'Deletion of the original experiment log', 'Removal of all labels from the growth tray', 'A guarantee that lamp replacement ends Tuesday'], 0, 'Location tracking follows the physical move.'],
  ]),
  ...listeningGroup('announcement-panel', 'Listen to an Announcement', '공공정책 패널', 'B2', 'The housing-policy panel begins at five thirty. Questions submitted before five will be grouped by topic. Audience members may still submit during the event, but late questions are considered only if time remains. The overflow room receives the live feed and has an independent microphone queue.', [
    ['What advantage do questions submitted before five receive?', ['They are organized for planned moderator consideration', 'They are guaranteed an individual answer from every panelist', 'They bypass grouping and enter the late queue', 'They reserve a seat in the main room'], 0, 'Early submissions enter structured preparation.'],
    ['How can overflow attendees participate?', ['Use the separate microphone queue connected to the live event', 'Move into the main room after the panel begins', 'Submit only before the five o’clock deadline', 'Watch a delayed recording without questions'], 0, 'The secondary room retains an interactive channel.'],
  ]),
]

const talks: BaseItem[] = [
  ...listeningGroup('talk-soil-carbonate', 'Listen to an Academic Talk', '토양과학', 'C1', 'Carbonate nodules in soil can record past moisture and carbon sources, but interpretation requires understanding how they formed. Some precipitate gradually from soil water; others inherit older limestone fragments. Carbon isotopes may reflect vegetation and soil respiration, while oxygen isotopes reflect water modified by evaporation and temperature. Later dissolution and reprecipitation can reset part of the signal. Researchers use microscopy, mineral texture, stratigraphic position, and multiple isotopes rather than assigning climate from one bulk measurement.', [
    ['Why can a nodule be older than the soil process being studied?', ['It may contain inherited carbonate rather than entirely new precipitation', 'Soil water removes every preexisting mineral fragment', 'Stratigraphic position always resets isotope ratios', 'Evaporation prevents carbonate from entering soil'], 0, 'Detrital material can predate pedogenic formation.'],
    ['Why is microscopic texture useful?', ['It helps distinguish growth, inheritance, and later alteration histories', 'It directly converts oxygen isotopes into annual rainfall', 'It proves all carbonate formed at one moment', 'It eliminates the need for stratigraphic context'], 0, 'Texture tests the origin of the measured material.'],
  ]),
  ...listeningGroup('talk-liquidity', 'Listen to an Academic Talk', '금융경제학', 'C1', 'Market liquidity describes how easily an asset can be traded without causing a large price change. A narrow bid–ask spread is one indicator, but displayed quotes may vanish during stress. Trading volume can be high while depth is shallow. Liquidity providers face inventory and information risk; they widen spreads when they suspect better-informed traders. A liquidity shock can amplify price movement as investors sell assets to meet funding needs. Measures should therefore consider cost, depth, resilience, and conditions under which orders are available.', [
    ['Why can a narrow quoted spread overstate liquidity?', ['Displayed orders may be too small or may disappear when trading pressure rises', 'Every narrow spread guarantees unlimited market depth', 'High volume prevents prices from changing', 'Information risk forces all traders to use one price'], 0, 'A quote is conditional and may lack durable capacity.'],
    ['How can funding needs amplify a market decline?', ['Forced sales consume limited buying depth and push prices further', 'Liquidity providers eliminate inventory risk during stress', 'Investors meet obligations by withdrawing all sell orders', 'Price resilience increases automatically with every shock'], 0, 'Balance-sheet pressure interacts with market capacity.'],
  ]),
  ...listeningGroup('talk-metacognition', 'Listen to an Academic Talk', '학습과학', 'C1', 'Metacognition includes monitoring one’s knowledge and controlling study based on that judgment. Familiarity can make material feel learned even when recall is poor. Delayed self-testing often predicts later memory better than rereading because it requires retrieval after short-term fluency fades. Yet confidence can still be miscalibrated, especially when feedback is absent. Learners should compare predictions with performance and adjust strategies. Accurate monitoring matters only if control follows: recognizing weakness but continuing passive review brings little benefit.', [
    ['Why can rereading create excessive confidence?', ['Processing fluency may be mistaken for durable retrievability', 'Familiar text cannot be understood during study', 'Retrieval always lowers subjective confidence to zero', 'Short-term fluency guarantees long-term recall'], 0, 'Ease of perception is not the same as memory strength.'],
    ['Why is monitoring alone insufficient?', ['Study behavior must change in response to detected weaknesses', 'Confidence scores directly strengthen memory traces', 'Feedback prevents learners from selecting any strategy', 'Passive review is always superior after an error'], 0, 'Control turns diagnosis into improved learning.'],
  ]),
  ...listeningGroup('talk-stained-glass', 'Listen to an Academic Talk', '건축미술사', 'B2', 'Medieval stained glass combines colored pieces joined by lead cames. Color may come from metal ions within the glass, while painted details are fired onto the surface. Windows were not static pictures: transmitted light changed with weather and time of day, and their appearance depended on architectural position. Corrosion can roughen surfaces and scatter light. Replacing darkened glass with bright modern material may increase visibility but alter the historical balance among windows, stone, and interior illumination.', [
    ['Why did a window’s appearance vary through the day?', ['Changing transmitted light interacted with its material and location', 'Lead cames produced their own constant illumination', 'Painted details disappeared permanently after firing', 'Architectural position had no effect on viewing'], 0, 'The image was conditioned by environmental light.'],
    ['What risk accompanies bright replacement glass?', ['It can disrupt the historically evolved visual relationship within the building', 'It guarantees that corrosion spreads to every original pane', 'It removes all transmitted light from the interior', 'It makes lead support structurally unnecessary'], 0, 'Local improvement can change the ensemble.'],
  ]),
  ...listeningGroup('talk-mitochondria', 'Listen to an Academic Talk', '진화유전학', 'C1', 'Mitochondrial DNA is usually inherited through one parent and does not recombine like most nuclear DNA, making it useful for tracing lineages. But one mitochondrial tree is not the entire species history. Selection can spread one variant, introgression can transfer mitochondria between species, and sex-biased dispersal makes maternal history differ from nuclear patterns. Effective population size is also smaller, so drift acts strongly. Researchers combine mitochondrial and nuclear loci rather than interpreting a single marker as a complete demographic record.', [
    ['Why can mitochondrial and species histories differ?', ['Inheritance, selection, introgression, and sex-biased movement affect the marker specifically', 'Mitochondrial DNA contains every nuclear chromosome', 'Recombination makes maternal lineages impossible to trace', 'A smaller effective population eliminates genetic drift'], 0, 'One genomic compartment follows its own processes.'],
    ['Why include nuclear loci?', ['Independent inheritance patterns help test conclusions from the maternal marker', 'Nuclear data always produce the same genealogy', 'They prevent selection from acting on mitochondria', 'They identify every ancestor without uncertainty'], 0, 'Multiple markers reveal discordance and broader history.'],
  ]),
  ...listeningGroup('talk-evapotranspiration', 'Listen to an Academic Talk', '생태수문학', 'C1', 'Evapotranspiration combines evaporation from surfaces with water released through plant stomata. It can be estimated from energy balance, weather data, lysimeters, or flux towers, but methods operate at different scales. Closing stomata reduces transpiration during drought, yet hotter leaves may increase sensible heat. Satellite vegetation temperature can indicate stress, though clouds, viewing angle, and mixed land cover complicate inference. Comparing methods requires matching spatial footprint and time interval rather than expecting one point sensor to validate an entire satellite pixel directly.', [
    ['What happens when plants close stomata during drought?', ['Water loss may decline while leaf heating and energy partition change', 'Surface evaporation necessarily rises by the identical amount', 'Sensible heat disappears from the energy balance', 'Plant temperature becomes independent of weather'], 0, 'Stomatal control shifts both water and heat fluxes.'],
    ['Why is direct point-to-pixel validation problematic?', ['The instruments integrate different areas and possibly different time spans', 'Satellite pixels contain no vegetation temperature information', 'Flux towers measure only underground water', 'Clouds improve the spatial match automatically'], 0, 'Scale mismatch can masquerade as measurement error.'],
  ]),
]

const sentenceData: SentenceDatum[] = [
  ['Why was the survival estimate biased?', 'Had those at greatest risk not left the study disproportionately', ['the remaining cohort', 'would have provided', 'a less optimistic', 'event profile'], 'f18-had-not-counterfactual-selection'],
  ['What did the tracer experiment reveal?', 'Running beneath the apparent watershed boundary was', ['a conduit', 'that carried dye', 'to a spring', 'several valleys away'], 'f18-present-participle-locative-inversion'],
  ['Why was the seal evidence inconclusive?', 'For all that its title matched the official', ['the matrix', 'could have been', 'reused later', 'by another holder'], 'f18-for-all-that-concessive'],
  ['How should the satellite comparison be made?', 'Only by matching the instruments’ spatial footprints', ['can researchers avoid', 'attributing scale differences', 'to sensor', 'inaccuracy'], 'f18-only-by-gerund-modal-inversion'],
  ['What surprised the engineer?', 'Little did the team anticipate that', ['a minor fabrication error', 'would narrow', 'the operating band', 'so severely'], 'f18-little-did-anticipate-that'],
  ['Why retain the censored observations?', 'Incomplete though their follow-up is', ['they still establish', 'a period during which', 'the target event', 'had not occurred'], 'f18-adjective-though-subject-inversion'],
  ['What made the intervention questionable?', 'The brighter the replacement panes became', ['the less coherent', 'the interior appeared', 'under changing', 'daylight'], 'f18-double-comparative-copular'],
  ['Why was a second registry needed?', 'There had been no way of knowing whether', ['unrecorded deaths', 'had occurred', 'among participants', 'lost to follow-up'], 'f18-no-way-of-knowing-whether'],
  ['What condition did the archive set?', 'Provided that the derivative images remain access-controlled', ['researchers may', 'compare them', 'with the restricted', 'original scans'], 'f18-provided-that-modal'],
  ['Why did the committee reject the claim?', 'So confounded were material source and workshop location', ['that chemistry alone', 'could not establish', 'where the manuscript', 'was produced'], 'f18-so-participle-inversion-result'],
]

const writing: BaseItem[] = sentenceItems(sentenceData)
writing.push({ ...base('email', 'writing', 'email', 'Write an Email', '임상 결과 정의', 'C1', 420), instruction: '정의 변경의 근거, 분석 영향, 필요한 재검증 절차를 구체적으로 작성하세요.', prompt: 'You learn that one analyst counted a single billing code as a confirmed clinical outcome, while the study protocol requires two codes or supporting laboratory evidence. Write to the data-analysis lead. Explain the discrepancy and its likely effect, request a reproducible reclassification, and propose a validation and version-control step.' })
writing.push({ ...base('discussion', 'writing', 'discussion', 'Write for an Academic Discussion', '기후 개입 연구', 'C1', 600), instruction: '잠재적 이익, 불확실성, 통제·책임 문제를 균형 있게 평가하세요.', prompt: 'Professor Okoye: Should governments fund large outdoor experiments of emerging climate interventions before their global effects are fully understood?', passage: 'Liu: Carefully monitored trials are necessary to discover whether proposed interventions work and what risks they create.\nMarta: Outdoor experiments can cross borders, normalize deployment, and create consequences that participants cannot fully reverse.' })

const repeatSentences = ['Welcome to the university wind-tunnel testing area.', 'Secure loose clothing and personal items before entering the chamber.', 'Confirm that the model is mounted in the approved orientation.', 'Connect each pressure line to the numbered acquisition channel.', 'Keep the access door locked whenever the fan is rotating.', 'Save the unprocessed sensor stream before calculating any coefficient.', 'After the run, stop the fan completely, inspect the mount, and record the calibration, airflow settings, and any visible movement of the model.']
const interviewQuestions = ['Describe a scientific experiment that could affect people outside the study site.', 'What potential knowledge or benefit might justify conducting it?', 'What risks would be difficult to contain or reverse?', 'Who should have authority to approve an experiment with cross-border consequences?']

const speaking: BaseItem[] = [
  ...repeatSentences.map((audioText, sequenceIndex) => ({ ...base(`repeat-${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', '풍동 시험', sequenceIndex < 2 ? 'B1' : 'B2', sequenceIndex < 3 ? 12 : 16), instruction: '한 번 듣고 준비 시간 없이 정확한 의미와 리듬으로 반복하세요.', audioText, stimulusGroupId: 'f18-repeat', scenarioId: 'f18-repeat', sequenceIndex })),
  ...interviewQuestions.map((audioText, sequenceIndex) => ({ ...base(`interview-${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', '경계를 넘는 과학 실험', sequenceIndex === 0 ? 'B2' : 'C1', 45), instruction: '연속된 주제 질문에 주장, 이유, 사례를 포함해 답하세요.', audioText, stimulusGroupId: 'f18-interview', scenarioId: 'f18-interview', sequenceIndex })),
]

export const AUTHORED_FORM_18_ITEMS = orderedForm(reading, responses, conversations, announcements, talks, writing, speaking)
export const AUTHORED_FORM_18_IDS = AUTHORED_FORM_18_ITEMS.map((item) => item.id)
