import type { BaseItem, Section } from './types'
import { AUTHORED_BATCH_TWO_ITEMS } from './authoredBatchTwo'
import { AUTHORED_FORM_03_ITEMS } from './authoredForm03'
import { AUTHORED_FORM_04_ITEMS } from './authoredForm04'
import { AUTHORED_FORM_05_ITEMS } from './authoredForm05'
import { AUTHORED_FORM_06_ITEMS } from './authoredForm06'
import { AUTHORED_FORM_07_ITEMS } from './authoredForm07'
import { AUTHORED_FORM_08_ITEMS } from './authoredForm08'
import { AUTHORED_FORM_09_ITEMS } from './authoredForm09'
import { AUTHORED_FORM_10_ITEMS } from './authoredForm10'
import { AUTHORED_FORM_11_ITEMS } from './authoredForm11'
import { AUTHORED_FORM_12_ITEMS } from './authoredForm12'
import { AUTHORED_FORM_13_ITEMS } from './authoredForm13'
import { AUTHORED_FORM_14_ITEMS } from './authoredForm14'
import { AUTHORED_FORM_15_ITEMS } from './authoredForm15'
import { AUTHORED_FORM_16_ITEMS } from './authoredForm16'
import { AUTHORED_FORM_17_ITEMS } from './authoredForm17'
import { AUTHORED_FORM_18_ITEMS } from './authoredForm18'
import { AUTHORED_FORM_19_ITEMS } from './authoredForm19'
import { AUTHORED_FORM_20_ITEMS } from './authoredForm20'
import { AUTHORED_FORM_21_ITEMS } from './authoredForm21'
import { AUTHORED_FORM_22_ITEMS } from './authoredForm22'
import {
  AUTHORED_FORM_23_ITEMS, AUTHORED_FORM_24_ITEMS, AUTHORED_FORM_25_ITEMS, AUTHORED_FORM_26_ITEMS,
  AUTHORED_FORM_27_ITEMS, AUTHORED_FORM_28_ITEMS, AUTHORED_FORM_29_ITEMS, AUTHORED_FORM_30_ITEMS,
} from './authoredForms23to30'
import { materializeAuthoredForms } from './authoredForms'
import { AUTHORED_CONTEXT_ITEMS } from './contextBank'
import { AUTHORED_READING_SUPPLEMENT_ITEMS } from './authoredReadingSupplementBank'
import { AUTHORED_SUPPLEMENT_ITEMS } from './authoredSupplementBank'
import { prepareSentenceTiles } from './sentenceTiles'
import { buildFullBlueprint, buildReadingBlueprint, buildSectionBlueprint, prepareQuestionBank } from './examBlueprint'

type Difficulty = NonNullable<BaseItem['difficulty']>
const make = (id: string, section: Section, kind: BaseItem['kind'], title: string, topic: string, difficulty: Difficulty, timeSeconds: number): BaseItem => ({ id, section, kind, title, topic, difficulty, timeSeconds, module: 1, instruction: '', sourceFamily: 'authored-core' })

const CLOZE: Array<[string, Difficulty, string, string]> = [
  ['생태학', 'B1', 'Mangrove forests grow along tropical coastlines. Their tangled roots prot___ young fish and red___ the force of waves. The trees also cap___ carbon in coastal soils. When mangroves are rem___, communities become more vuln___ to storms. Restoration projects comb___ tree planting with limits on development. Residents often mon___ seedling survival and rep___ damaged areas. Successful programs imp___ biodiversity and human safety, making these forests val___ natural infrastructure.', 'ect|uce|ture|oved|erable|ine|itor|air|rove|uable'],
  ['천문학', 'B2', 'A solar eclipse occurs when the Moon passes between Earth and the Sun. Although the Moon is much sma___ than the Sun, it appears sim___ in size because it is closer. During totality, the bright surface is cov___ and the faint outer atmosphere becomes vis___. Scientists obs___ features normally hidden by sunlight. Modern instruments sim___ some eclipse conditions, but field teams still tra___ widely. Careful timing and clear weather rem___ essential. A few min___ of observation can reveal how heat and particles mov___ through the solar atmosphere.', 'ller|ilar|ered|ible|erve|ulate|vel|ain|utes|e'],
  ['심리학', 'B2', 'Spacing study sessions over several days usually creates stronger memories than studying at once. Each delay req___ the learner to reconstruct information, which stren___ retrieval. Some forgetting is therefore use___. Researchers also find that var___ the setting makes knowledge more flex___. Spacing does not replace foc___ attention. Learners still ben___ from checking errors and explaining ideas. A good schedule bal___ difficulty with success and revisits material before it becomes too hard to rec___. The method can be app___ to vocabulary, equations, and complex concepts.', 'uires|gthens|ful|ying|ible|used|efit|ances|all|lied'],
  ['재료공학', 'C1', 'Engineers study why tiny cracks spread through solid materials. A crack concentrates stress at its tip, so a mod___ load can become intense in one region. If the material cannot red___ that stress, the crack may grow. Metals sometimes slow this process by def___, while brittle ceramics fracture suddenly. Designers imp___ safety by rounding corners and insp___ parts regularly. Models pred___ how flaws respond to repeated loading, but laboratory tests rem___ necessary. Understanding fracture is crit___ in aircraft, bridges, and medical implants, where a small def___ could have ser___ consequences.', 'erate|istribute|orming|rove|ecting|ict|ain|ical|ect|ious'],
  ['경제학', 'B2', 'A fee for disposable bags often changes behavior quickly. Its vis___ reminds shoppers that each bag has a cost. Many people carry reusable bags, and stores ord___ fewer disposable ones. Economists call this an incentive that al___ a choice without banning it. The effect can wea___ if people stop noticing the charge. Officials must cons___ effects on low-income households and may distrib___ free bags. Evaluations comp___ behavior before and after the policy while accounting for other changes. Evidence helps leaders ref___ the program rather than ass___ one design will work everywhere, even when leaders oft___ expect it.', 'ibility|er|ters|ken|ider|ute|are|ine|ume|en'],
  ['미술사', 'B2', 'Museums use lighting to help visitors see objects and protect fragile materials. Bright light can fa___ dyes, weaken paper, and change photographs. Curators lim___ both intensity and duration. A strong lamp may make a painting dramatic but shor___ its useful life. Sensors adj___ illumination when galleries are empty. Designers also prev___ glare. The best solution bal___ visibility, atmosphere, energy use, and conservation. Staff doc___ light levels and rot___ sensitive works. This approach lets the public enj___ collections without sacrificing fra___ objects for future generations.', 'de|it|ten|ust|ent|ances|ument|ate|oy|gile'],
  ['언어학', 'C1', 'Languages constantly borrow words from one another. Trade, mig___, and popular cul___ cre___ opportunities to encounter new terms. Borrowed words rarely remain unchanged: pronunciation may sh___, and meanings can nar___ or expand. This does not make a language less auth___; it shows adaptation. Linguists trace borrowing through old texts, but the route is not always dir___. A term may pass through several languages. Digital media acc___ exchange, allowing expressions to spread rapidly. Communities still sele___ which words persist and integ___ them into existing grammar.', 'ration|ture|ate|ift|row|entic|ect|elerates|ct|rate'],
  ['공중보건', 'B1', 'Urban heat affects neighborhoods differently. Areas with few trees and dark sur___ abs___ more energy and cool slowly. Older adults and outdoor workers face partic___ risk. Cities red___ exposure with shade trees, cooling centers, and reflective roofs. Warning systems are most eff___ when messages explain concrete actions. Health departments exa___ hospital visits to identify vulnerable areas. No single measure is suff___ because heat interacts with housing and income. A strong plan comb___ physical improvements with outreach and eval___. Such preparation will become incre___ important for public safety.', 'faces|orb|ular|uce|ective|mine|icient|ines|uation|asingly'],
]

const DAILY: Array<[string, Difficulty, string, string, string[], number, string]> = [
  ['도서관', 'B1', 'The silent study floor will be closed Thursday morning for carpet cleaning. Reserved books can still be collected at the ground-floor service desk. Group rooms remain open.', 'Where should a student collect a reserved book?', ['On the silent floor', 'At the ground-floor desk', 'Inside a group room', 'At the cleaning office'], 1, 'Reserved books move to the ground-floor service desk.'],
  ['교통', 'B1', 'From Monday through Wednesday, Route 8 buses will skip the Science Gate because of road repairs. Use the temporary stop beside the stadium.', 'Why will buses skip Science Gate?', ['A sporting event nearby', 'Street work along the usual route', 'A permanent timetable revision', 'Insufficient passenger demand'], 1, 'Repair work on the road prevents buses from using the normal stop.'],
  ['식당', 'B1', 'Students who complete the dining survey before Friday will receive a drink voucher by email. The voucher is valid next week only.', 'When can the voucher be used?', ['Before the survey deadline', 'During the following week', 'At any point in the term', 'On the day the survey is submitted'], 1, 'The valid period is the week after the current one.'],
  ['기숙사', 'B2', 'The residence desk accepts ordinary parcels but has no secure space for items longer than one meter. Residents expecting a large package must meet the courier in the lobby.', 'What can be inferred about a long package?', ['It is returned.', 'A fee is charged.', 'The resident receives it personally.', 'It goes to a classroom.'], 2, 'Long items cannot be securely stored at the desk.'],
  ['연구 참여', 'B2', 'A sleep study seeks adults who do not work night shifts. Participants visit the lab twice and keep an online sleep diary for ten days.', 'Who is eligible?', ['A night-shift worker', 'Someone available for two visits', 'Someone refusing a diary', 'A child'], 1, 'Two visits are required, and night-shift workers are excluded.'],
  ['공연', 'B1', 'Tonight’s outdoor concert has moved to Hall C because rain is expected. Existing tickets remain valid, but seating is first come, first served.', 'What changed?', ['The performers', 'The price', 'The location', 'The start time'], 2, 'The concert moved indoors to Hall C.'],
  ['수업', 'B2', 'Seats marked “department hold” will be released at noon on August 28. Joining the waitlist does not guarantee a seat.', 'What happens at noon?', ['The class begins.', 'Held seats become available.', 'The waitlist closes.', 'Everyone gets a seat.'], 1, 'Department-held seats are released then.'],
  ['체육관', 'B1', 'Lane swimming ends at 4:30 p.m. Friday to prepare for a competition. The fitness room and indoor track keep regular hours.', 'Which facility closes early?', ['The fitness room', 'The track', 'The swimming lanes', 'The whole center'], 2, 'Only lane swimming ends early.'],
  ['IT 보안', 'B2', 'The university will never ask for your password by email. Forward suspicious login requests to campus security and then delete them.', 'What should a student do with a suspicious request?', ['Reply with a password', 'Open its link', 'Forward it to security', 'Post it publicly'], 2, 'The alert instructs forwarding to security.'],
  ['장학금', 'B2', 'Travel grant applications require a budget, a faculty recommendation, and proof that a conference paper was accepted. Draft papers do not satisfy the acceptance requirement.', 'Which document fails the requirement?', ['An acceptance letter', 'A recommendation', 'A budget', 'A draft without acceptance'], 3, 'A draft alone does not prove acceptance.'],
  ['봉사', 'B2', 'River-cleanup volunteers should bring water and closed shoes. The event proceeds in light rain but is postponed if lightning is reported.', 'When is the event postponed?', ['When volunteers lack gloves', 'During a light shower', 'When electrical storm activity is reported', 'When the river level is low'], 2, 'An electrical storm, rather than ordinary rain, triggers postponement.'],
  ['건강센터', 'B1', 'Vaccination appointments are available online. Walk-in service is reserved for students with accessibility needs or physician referrals.', 'Who may walk in?', ['Any currently enrolled learner', 'University employees only', 'Learners requiring disability-related access accommodations', 'Students preparing to travel'], 2, 'The exception includes people who need an accessible service arrangement.'],
]

const ACADEMIC: Array<[string, Difficulty, string, [string, string[], number, string], [string, string[], number, string]]> = [
  ['생물학', 'B2', 'Some desert plants open leaf pores only at night. Carbon dioxide enters while temperatures are lower, so less water is lost. The gas is stored temporarily and used for photosynthesis after sunrise. This strategy saves water but limits carbon intake, so these plants often grow slowly.', ['Why do the pores open at night?', ['To absorb sunlight', 'To reduce water loss', 'To release oxygen', 'To raise temperature'], 1, 'Cooler conditions reduce evaporation.'], ['What is one cost?', ['No photosynthesis', 'Slow growth', 'Frozen leaves', 'More predators'], 1, 'Limited carbon intake restricts growth.']],
  ['지질학', 'B2', 'River deltas form where flowing water enters a slower lake or ocean. As the current loses energy, sediment accumulates. Dams may reduce the sediment supply, while sea-level rise and land subsidence remove delta surfaces. A delta can therefore shrink even when the river still reaches the coast.', ['Why does sediment accumulate?', ['Slower water can no longer transport as much material.', 'The receiving ocean becomes less salty.', 'The river temperature rises near the coast.', 'Plants extract minerals from the channel.'], 0, 'A weaker current drops material it previously carried.'], ['Why can a delta shrink?', ['Rivers reverse.', 'Dams trap sediment.', 'Sand dissolves.', 'Channels stop dividing.'], 1, 'Dams reduce material that rebuilds the delta.']],
  ['인지과학', 'C1', 'People can miss a visible object while concentrating on another demanding task. This inattentional blindness does not mean the eyes failed to receive the image. Limited processing resources were allocated elsewhere. Confidence in observation can therefore exceed actual awareness.', ['What does the effect show?', ['Vision always stops.', 'Visible information may not reach awareness.', 'Attention is unlimited.', 'Confidence improves vision.'], 1, 'The image is received but not consciously processed.'], ['Why mention confidence?', ['People may overestimate what they noticed.', 'Confidence prevents distraction.', 'Vision equals hearing.', 'Complex scenes should be avoided.'], 0, 'Certainty does not guarantee complete awareness.']],
  ['고고학', 'B2', 'Microscopic traces on pottery reveal how vessels were used. Starch grains can identify plants, while absorbed fats may indicate dairy products or meat. Residues rarely provide a complete recipe, and contamination must be excluded. Combined with vessel shape and location, they reveal cooking and trade practices.', ['What can residues show?', ['Every vessel’s exact age', 'Foods processed in a pot', 'The potter’s name', 'A complete recipe'], 1, 'Starch and fats point to past foods.'], ['Why consider contamination?', ['Modern material could distort evidence.', 'All pots were painted.', 'Shape changes underground.', 'Recipes are too detailed.'], 0, 'Later substances may be mistaken for ancient traces.']],
  ['음향학', 'C1', 'Noise-canceling headphones measure incoming noise and produce a wave with nearly the opposite pattern. When the waves meet, pressure changes partially cancel. The method is less effective for sudden or high-frequency sounds, so physical padding remains important.', ['How does cancellation work?', ['It creates light.', 'It produces an opposing wave.', 'It stops vibration speed.', 'It blocks the microphone.'], 1, 'Opposing pressure patterns partially cancel.'], ['Why is padding useful?', ['Electronics cannot reduce every sound.', 'It creates power.', 'Microphones work only outside.', 'Low sounds damage circuits.'], 0, 'Sharp and high sounds are difficult to cancel.']],
  ['경제사', 'B2', 'Standardized shipping containers reduced repeated handling. Previously, workers loaded individual crates, which was slow and increased theft and damage. A sealed box could move among truck, train, and ship. Ports first needed expensive cranes and new layouts, but later transport costs fell dramatically.', ['What was the main advantage?', ['Faster ships', 'Less repeated handling', 'No ports', 'Different box sizes'], 1, 'One unit transferred among transport modes.'], ['Why was adoption expensive?', ['Ports needed equipment and redesign.', 'Rare metals were required.', 'Workers banned trains.', 'Trade had ended.'], 0, 'New cranes and layouts required investment.']],
  ['도시계획', 'C1', 'A road can carry more people without widening if travelers shift from cars to buses or bicycles. Capacity depends on people moved, not vehicles counted. Optimizing only vehicle speed can make walking, transfers, and access worse even when traffic appears efficient.', ['Why can capacity rise without widening?', ['Cars shrink.', 'Space-efficient modes move more people.', 'All vehicles speed up.', 'Destinations move.'], 1, 'Buses and bicycles use road space efficiently.'], ['What is the warning?', ['Vehicle speed alone can mislead.', 'Buses end congestion.', 'Walking cannot be measured.', 'Width decides everything.'], 0, 'Fast traffic does not necessarily improve access.']],
  ['컴퓨터과학', 'B2', 'Lossless compression preserves every original bit and suits text, software, and scientific records. Lossy methods discard details users may not notice, creating smaller media files. The acceptable trade-off depends on purpose: a website photograph and a medical image have different preservation needs.', ['When is lossless compression important?', ['Every detail must be recovered.', 'A file stays closed.', 'Audio should change.', 'Size is the only goal.'], 0, 'Lossless methods reproduce all original data.'], ['What determines acceptable loss?', ['Device color', 'The file’s purpose', 'Computer age', 'File names'], 1, 'Different uses tolerate different information loss.']],
]

const RESPONSES: Array<[string, string[], number]> = [
  ['Could you send me the revised schedule?', ['It was yesterday.', 'Sure, I will email it.', 'Revision is difficult.', 'I sent the room.'], 1],
  ['Why was the lecture moved online?', ['The hall is being repaired.', 'I moved the chemicals.', 'The website is blue.', 'At three thirty.'], 0],
  ['Is the registrar open today?', ['The fee is high.', 'I opened it.', 'Yes, until four.', 'Today is a date.'], 2],
  ['How did your presentation go?', ['The projector is there.', 'Better than expected.', 'Through the hall.', 'About energy.'], 1],
  ['Would you mind lowering the volume?', ['Not at all.', 'Three chapters.', 'I lowered a shelf.', 'I heard nothing.'], 0],
  ['Where should I leave the forms?', ['It took ten minutes.', 'On the tray by my door.', 'I left at noon.', 'They were interesting.'], 1],
  ['Haven’t you submitted the report?', ['The lab is upstairs.', 'No, one calculation remains.', 'Ana submitted it.', 'The coat fits.'], 1],
  ['Which train goes to the research park?', ['The express on platform two.', 'The research was published.', 'Every park.', 'Two pages.'], 0],
  ['Could I borrow your Tuesday notes?', ['Tuesday was sunny.', 'I borrowed a book.', 'Of course, return them tomorrow.', 'The note is C.'], 2],
  ['Why don’t we meet after the workshop?', ['That works; it ends at five.', 'There are twelve seats.', 'I met her.', 'The room is large.'], 0],
  ['Who coordinates the volunteer event?', ['By the river.', 'Professor Malik.', 'Many volunteers.', 'It was coordinated.'], 1],
  ['When will the part arrive?', ['It was expensive.', 'By Friday morning.', 'At engineering.', 'It replaced it.'], 1],
  ['Where can I print a poster?', ['It won an award.', 'Try the media lab.', 'In color.', 'Nearby.'], 1],
  ['What did the advisor recommend?', ['Taking statistics first.', 'An hour.', 'I recommended her.', 'The office closed.'], 0],
  ['Couldn’t we test it outdoors?', ['Twenty questions.', 'Yes, if it stays dry.', 'On the table.', 'Opposite indoors.'], 1],
  ['How often does the shuttle run?', ['Six kilometers.', 'North entrance.', 'Every fifteen minutes.', 'Out of fuel.'], 2],
]

const LISTENING: Array<[string, string, Difficulty, string, [string, string[], number, string], [string, string[], number, string]]> = [
  ['Listen to a Conversation', '수강 변경', 'B2', 'Student: My schedule shows the design seminar on Thursday, but that overlaps with statistics. Advisor: The Tuesday section was canceled. You can join architecture instead; it satisfies the requirement if the instructor approves by Friday.', ['What problem does the student have?', ['The seminar is full.', 'Two classes overlap.', 'Statistics was canceled.', 'The advisor is absent.'], 1, 'The Thursday seminar conflicts with statistics.'], ['What does the advisor suggest?', ['Drop the requirement.', 'Move statistics.', 'Join another approved seminar.', 'Wait a year.'], 2, 'Architecture can satisfy the same requirement.']],
  ['Listen to a Conversation', '장비 대여', 'B2', 'Student: My weekend camera reservation says return Saturday. Technician: The special battery kit is needed for another class then. You can keep the camera, return that kit, and use a standard battery.', ['Why does it list Saturday?', ['Camera repair', 'A class needs part of the equipment.', 'All loans end then.', 'Wrong camera'], 1, 'Another class needs the battery kit.'], ['What is the solution?', ['Cancel everything', 'Pay more', 'Separate camera and battery reservations', 'Move the class'], 2, 'Only the special battery returns Saturday.']],
  ['Listen to a Conversation', '연구 데이터', 'C1', 'Student: My graph differs from the article. Professor: Did you remove measurements taken while the sensor warmed up? The software marks them but does not delete them. Recalculate without the first thirty seconds before questioning the model.', ['What caused the graph?', ['Another model', 'Warm-up data were included.', 'The sensor stopped.', 'Valid data were deleted.'], 1, 'Unstable warm-up readings remained.'], ['What does the professor imply?', ['Clean the data before rejecting the model.', 'Abandon the study.', 'Never mark data.', 'The article is wrong.'], 0, 'Recalculation should precede criticism of the model.']],
  ['Listen to an Announcement', '기상', 'B1', 'Thunderstorms are forecast after three. Afternoon field groups must return by two thirty. Morning groups may leave with radios. The evening orientation will be online.', ['What must afternoon groups do?', ['Leave early', 'Return by two thirty', 'Meet indoors', 'Carry no radio'], 1, 'They must return before storms.'], ['What changed about orientation?', ['Topic', 'Instructor', 'Format', 'Date'], 2, 'It moved online.']],
  ['Listen to an Announcement', '건물 접근', 'B2', 'The west engineering entrance is locked while automatic doors are installed. Use the north entrance. For step-free access, enter through the science building and use elevators to the connecting bridge.', ['Why is the west entrance closed?', ['Broken elevator', 'Door installation', 'Locked science building', 'Bridge removal'], 1, 'Automatic doors are being installed.'], ['What should someone needing step-free access do?', ['Use stairs', 'Wait', 'Enter through science', 'Use parking'], 2, 'The connected building provides elevators.']],
  ['Listen to an Academic Talk', '해양생물학', 'B2', 'Low-frequency whale sounds can travel far through seawater. In a natural sound channel, temperature and pressure bend waves back toward the center. Human shipping noise can overlap these frequencies and reduce communication distance.', ['Why do calls travel far?', ['The channel redirects sound.', 'Whales swim fast.', 'Ships amplify them.', 'Cold removes noise.'], 0, 'Refraction holds sound in the channel.'], ['What concern is mentioned?', ['Whales stop sound.', 'Ships mask communication.', 'Pressure stops diving.', 'Sound heats water.'], 1, 'Shipping overlaps whale frequencies.']],
  ['Listen to an Academic Talk', '미생물학', 'C1', 'Bacteria can exchange plasmids, small DNA rings that may carry several resistance genes. Antibiotics do not create every gene, but they favor resistant cells while susceptible cells die.', ['What is special about plasmids?', ['They transfer resistance genes.', 'They stop reproduction.', 'Antibiotics create them.', 'They are human cells.'], 0, 'Plasmids move genes between bacteria.'], ['How do antibiotics affect resistance?', ['Remove all mutations', 'Favor already-resistant bacteria', 'Stop plasmids', 'Create viruses'], 1, 'Treatment selects resistant cells.']],
  ['Listen to an Academic Talk', '건축사', 'B2', 'Before electricity, factories used northern-facing sawtooth roof windows. They admitted diffuse light without intense afternoon heat. Modern architects sometimes reuse the form for historical character even when it is no longer technically necessary.', ['Why face windows north?', ['Direct heat', 'Steady diffuse light', 'Hide equipment', 'Support lamps'], 1, 'Northern light reduces glare and heat.'], ['Why reuse the form today?', ['Historical association', 'Flat roofs are banned.', 'No electricity', 'No heat'], 0, 'The shape signals industrial history.']],
]

const SENTENCES: Array<[string, string, string[], string]> = [
  ['Did the workshop help?', 'It showed me', ['how', 'to organize', 'the evidence', 'more clearly'], 'embedded-how-infinitive'], ['Why was the trail closed?', 'The ranger explained', ['that', 'heavy rain', 'had damaged', 'the bridge'], 'reported-past-perfect'], ['Are you joining the club?', 'I would join', ['if', 'the meetings', 'did not conflict', 'with my lab'], 'second-conditional'], ['Who recommended this?', 'It was my advisor', ['who', 'suggested', 'that I read', 'it first'], 'cleft-relative-clause'], ['How was the tour?', 'The objects', ['that the curator', 'showed us', 'were', 'well preserved'], 'relative-clause'], ['Why are results uncertain?', 'We do not know', ['whether', 'the sample', 'was large enough', 'to represent the population'], 'embedded-whether-clause'], ['Can we submit tomorrow?', 'The instructions say', ['that', 'all applications', 'must be received', 'by midnight'], 'reported-passive-clause'], ['What surprised you?', 'I had not realized', ['how quickly', 'coastal landscapes', 'can change', 'after a storm'], 'embedded-exclamation'], ['Did Maya finish?', 'She would have finished', ['if', 'the parts', 'had arrived', 'on time'], 'third-conditional'], ['Why delay the decision?', 'The committee wanted', ['to review', 'the evidence', 'that the report', 'provided'], 'infinitive-relative-clause'], ['Is the software difficult?', 'It is easier', ['than', 'the previous version', 'was', 'for beginners'], 'comparative-clause'], ['Why take statistics?', 'He needs it', ['so that', 'he can analyze', 'the survey data', 'correctly'], 'purpose-clause'], ['How did plants survive?', 'Their roots', ['were deep enough', 'to reach', 'water', 'below the soil'], 'enough-infinitive'], ['Will it be outdoors?', 'It depends on', ['whether', 'the weather', 'remains dry', 'this evening'], 'depends-whether-clause'], ['Why revise the introduction?', 'My instructor suggested', ['that', 'I explain', 'the main question', 'first'], 'mandative-that-clause'], ['Was the internship useful?', 'It gave me', ['a chance', 'to apply', 'what I learned', 'in class'], 'noun-infinitive-wh-clause'], ['Why are birds hard to count?', 'They move', ['so frequently', 'that observers', 'record', 'some twice'], 'so-that-result-clause'], ['Did the library buy it?', 'The librarian said', ['that', 'it was', 'too expensive', 'for the budget'], 'reported-too-adjective'], ['How can traffic fall?', 'One approach is', ['to improve', 'the bus network', 'before restricting', 'private cars'], 'infinitive-before-gerund'], ['Why did glass crack?', 'It was exposed', ['to', 'a sudden change', 'in temperature', 'during testing'], 'passive-prepositional-phrase'],
]

const EMAILS: Array<[string, string]> = [
  ['수업', 'You missed a required laboratory because the campus shuttle broke down. Write to the instructor. Explain what happened, describe what work you missed, and ask how to make it up.'], ['기숙사', 'A noisy ventilation unit affects your sleep. Write to the residence manager. Describe when it occurs and request an inspection or temporary solution.'], ['연구', 'A shared dataset has unlabeled columns. Write to your partner. Explain the delay and propose a documentation method.'], ['도서관', 'A book listed as available is missing. Write to a librarian. Identify it, explain why you need it soon, and ask about alternatives.'], ['동아리', 'Your club received a smaller room than reserved. Write to the events office. Explain expected attendance and request another arrangement.'], ['인턴십', 'Your internship start conflicts with a final exam. Write to the coordinator with dates and two possible solutions.'], ['장학금', 'The portal marks an uploaded document as missing. Write to the scholarship office and request confirmation before the deadline.'], ['학회', 'A conference program misspells your name and title. Write to the organizer with the corrections and ask when the program will update.'],
]
const DISCUSSIONS: Array<[string, string, string]> = [
  ['교육', 'Professor Chen: Should courses use more group projects or individual assignments?', 'Aisha: Groups develop collaboration.\nMarco: Individual work makes grading fairer.'], ['환경', 'Professor Silva: Should cities charge drivers to enter busy downtown areas?', 'Nora: A charge reduces traffic.\nEvan: It may burden workers without transit.'], ['기술', 'Professor Brooks: Does generative AI improve or weaken student learning?', 'Lena: AI gives immediate explanations.\nSam: Students may stop practicing difficult thinking.'], ['건강', 'Professor Rahman: Should universities require a course on sleep, nutrition, and stress?', 'Iris: Health supports academic success.\nTom: Students should choose their electives.'], ['역사', 'Professor Patel: Is preserving an old building more important than replacing it efficiently?', 'Jae: Old buildings give identity.\nMila: New buildings can be safer.'], ['경제', 'Professor Wilson: Should unpaid internships be permitted when they provide experience?', 'Rosa: Some organizations cannot pay.\nNoah: Unpaid work excludes students needing income.'], ['과학', 'Professor Okafor: Should scientists spend more time explaining research to the public?', 'Mei: Understanding supports decisions.\nLucas: Communication reduces research time.'], ['예술', 'Professor Laurent: Should museums return important objects to their places of origin?', 'Dina: Return repairs injustice.\nOwen: International museums broaden access.'],
]

const REPEATS: Array<[string, Difficulty, string[]]> = [
  ['도서관 안내', 'B1', ['Welcome to the media library.', 'Keep food away from the computers.', 'Headphones are available at the desk.', 'You can reserve an editing station for two hours.', 'Save your work to your own drive before logging out.', 'Staff can help you convert older video formats.', 'When finished, return all equipment to the labeled cabinet.']],
  ['실험실 안전', 'B2', ['Today we will review the safety procedure.', 'Protective glasses must remain on at all times.', 'Check each container before measuring the liquid.', 'If anything spills, notify the supervisor immediately.', 'Used materials belong in the marked disposal bins.', 'Before leaving, make sure every gas valve is closed.', 'Accurate records and careful cleanup are as important as the experiment.']],
  ['박물관 투어', 'B2', ['Our tour begins in the sculpture gallery.', 'The oldest objects are near the entrance.', 'Look closely, but do not touch the surfaces.', 'Natural light is limited to protect colored materials.', 'The second room shows how damaged works are repaired.', 'You may take photographs if you turn off the flash.', 'At the end, we will discuss how display choices influence interpretation.']],
  ['현장 조사', 'C1', ['We will collect water samples along the river.', 'Each bottle matches a numbered location.', 'Rinse the instrument before moving to the next site.', 'Record the weather even if conditions seem unchanged.', 'Measurements near bridges may reflect recent construction.', 'If the current becomes strong, remain on the bank.', 'Consistent methods let us compare today’s results with previous years.']],
  ['학생 오리엔테이션', 'B1', ['Your orientation group will meet in this hall.', 'The campus tour starts after lunch.', 'Bring identification to the registration desk.', 'Advisors will answer course questions this afternoon.', 'Accessibility services are beside the main library.', 'Student clubs have tables outside the dining center.', 'Before leaving, confirm that your emergency contact is correct.']],
  ['로봇 실습', 'B2', ['We will test the mobile robot in the marked area.', 'Keep the emergency stop within reach.', 'The first run uses low speed and an empty workspace.', 'Watch the sensor display before enabling autonomy.', 'If the path changes unexpectedly, stop and save the log.', 'Only one person should issue commands during a trial.', 'A successful simulation does not replace physical safety checks.']],
]

const INTERVIEWS: Array<[string, Difficulty, string[]]> = [
  ['학습 습관', 'B1', ['Describe a study habit that works for you.', 'How did you develop it?', 'When is it difficult to maintain?', 'What advice would you give another student?']], ['팀워크', 'B2', ['Tell me about working with people who had different ideas.', 'How did your group decide?', 'What would you do differently?', 'Do disagreements improve teamwork?']], ['기술 사용', 'B2', ['What digital tool helps your learning?', 'What problem can it not solve?', 'When do you avoid technology?', 'How might it change education?']], ['도시 생활', 'B1', ['What makes a city comfortable for students?', 'Give an example.', 'What problem can this feature create?', 'Who should improve it?']], ['실패와 개선', 'C1', ['Describe a project that did not go as planned.', 'How did you find the cause?', 'What changed in your later work?', 'Why is discussing failure difficult?']], ['환경 행동', 'B2', ['What environmental action is realistic for students?', 'Why is it difficult?', 'How could a university help?', 'Are individual actions or policies more important?']], ['의사소통', 'C1', ['Describe a misunderstanding that affected a task.', 'How did you discover it?', 'What would have prevented it?', 'Is writing always clearer than speaking?']], ['창의성', 'B2', ['What activity helps you generate ideas?', 'Do you create better alone or with others?', 'How does limited time affect creativity?', 'Should creativity receive grades?']],
]

const reading: BaseItem[] = [
  ...CLOZE.map(([topic, difficulty, passage, answer], i) => ({ ...make(`r-cloze-${i}`, 'reading', 'complete-words', 'Complete the Words', topic, difficulty, 240), instruction: '문맥과 철자를 이용해 빠진 글자를 입력하세요.', passage, answer, explanation: '문맥상 의미와 올바른 철자를 모두 만족해야 합니다.' })),
  ...DAILY.map(([topic, difficulty, passage, prompt, options, answer, explanation], i) => ({ ...make(`r-daily-${i}`, 'reading', 'multiple-choice', 'Read in Daily Life', topic, difficulty, 75), instruction: '실용문을 읽고 답하세요.', passage, prompt, options, answer, explanation })),
  ...ACADEMIC.flatMap(([topic, difficulty, passage, q1, q2], i) => [q1, q2].map(([prompt, options, answer, explanation], j) => ({ ...make(`r-academic-${i}-${j}`, 'reading', 'multiple-choice', 'Read an Academic Passage', topic, difficulty, 120), instruction: '학술 지문을 읽고 답하세요.', passage, prompt, options, answer, explanation }))),
]
const listening: BaseItem[] = [
  ...RESPONSES.map(([audioText, options, answer], i) => ({ ...make(`l-response-${i}`, 'listening', 'listen-choice', 'Listen and Choose a Response', '캠퍼스 의사소통', i < 8 ? 'B1' : 'B2', 35), instruction: '가장 자연스러운 응답을 고르세요. 이전 문항으로 돌아갈 수 없습니다.', audioText, options, answer, explanation: '질문의 의도와 문법 형태에 직접 맞는 응답입니다.' })),
  ...LISTENING.flatMap(([title, topic, difficulty, audioText, q1, q2], i) => [q1, q2].map(([prompt, options, answer, explanation], j) => ({ ...make(`l-set-${i}-${j}`, 'listening', 'listen-choice', title, topic, difficulty, 70), instruction: '오디오는 한 번 재생됩니다. 핵심 내용과 의도를 파악하세요.', audioText, prompt, options, answer, explanation }))),
]
const writing: BaseItem[] = [
  ...SENTENCES.map(([prompt, starter, source, grammarFocus], i) => {
    const id = `w-sentence-${i}`
    const tiles = prepareSentenceTiles(source, id)
    return { ...make(id, 'writing', 'sentence-build', 'Build a Sentence', '문장 구조', i < 7 ? 'B1' : i < 15 ? 'B2' : 'C1', 75), instruction: '문맥에 맞는 문장이 되도록 모든 단어와 짧은 구를 배열하세요.', prompt, starter, words: tiles.choices, answer: tiles.answer, explanation: `${starter} ${tiles.correct.join(' ')}`, grammarFocus }
  }),
  ...EMAILS.map(([topic, prompt], i) => ({ ...make(`w-email-${i}`, 'writing', 'email', 'Write an Email', topic, i < 4 ? 'B1' : 'B2', 420), instruction: '목적과 독자를 고려해 이메일을 작성하세요.', prompt })),
  ...DISCUSSIONS.map(([topic, prompt, passage], i) => ({ ...make(`w-discussion-${i}`, 'writing', 'discussion', 'Write for an Academic Discussion', topic, i < 3 ? 'B1' : i < 6 ? 'B2' : 'C1', 600), instruction: '의견과 근거를 제시하고 다른 관점에 기여하세요.', prompt, passage })),
]
const speaking: BaseItem[] = [
  ...REPEATS.flatMap(([topic, difficulty, sentences], i) => sentences.map((audioText, j) => ({ ...make(`s-repeat-${i}-${j}`, 'speaking', 'repeat', 'Listen and Repeat', topic, difficulty, j < 3 ? 12 : 16), instruction: '듣고 준비 시간 없이 한 번만 그대로 말하세요.', audioText }))),
  ...INTERVIEWS.flatMap(([topic, difficulty, questions], i) => questions.map((audioText, j) => ({ ...make(`s-interview-${i}-${j}`, 'speaking', 'interview', 'Take an Interview', topic, difficulty, 45), instruction: '면접 질문에 충분히 답하세요. 준비 시간은 없습니다.', audioText }))),
]

export const QUESTION_BANK: BaseItem[] = prepareQuestionBank([...reading, ...listening, ...writing, ...speaking, ...AUTHORED_CONTEXT_ITEMS, ...AUTHORED_READING_SUPPLEMENT_ITEMS, ...AUTHORED_SUPPLEMENT_ITEMS, ...AUTHORED_BATCH_TWO_ITEMS, ...AUTHORED_FORM_03_ITEMS, ...AUTHORED_FORM_04_ITEMS, ...AUTHORED_FORM_05_ITEMS, ...AUTHORED_FORM_06_ITEMS, ...AUTHORED_FORM_07_ITEMS, ...AUTHORED_FORM_08_ITEMS, ...AUTHORED_FORM_09_ITEMS, ...AUTHORED_FORM_10_ITEMS, ...AUTHORED_FORM_11_ITEMS, ...AUTHORED_FORM_12_ITEMS, ...AUTHORED_FORM_13_ITEMS, ...AUTHORED_FORM_14_ITEMS, ...AUTHORED_FORM_15_ITEMS, ...AUTHORED_FORM_16_ITEMS, ...AUTHORED_FORM_17_ITEMS, ...AUTHORED_FORM_18_ITEMS, ...AUTHORED_FORM_19_ITEMS, ...AUTHORED_FORM_20_ITEMS, ...AUTHORED_FORM_21_ITEMS, ...AUTHORED_FORM_22_ITEMS, ...AUTHORED_FORM_23_ITEMS, ...AUTHORED_FORM_24_ITEMS, ...AUTHORED_FORM_25_ITEMS, ...AUTHORED_FORM_26_ITEMS, ...AUTHORED_FORM_27_ITEMS, ...AUTHORED_FORM_28_ITEMS, ...AUTHORED_FORM_29_ITEMS, ...AUTHORED_FORM_30_ITEMS], { contextualizeDuplicatePrompts: false })
export const CONTEXT_TOPIC_COUNT = new Set(QUESTION_BANK.map((item) => item.topic).filter(Boolean)).size
const validateQuestionBank = () => {
  if (QUESTION_BANK.length !== 2922) throw new Error(`Expected 2922 directly authored questions, received ${QUESTION_BANK.length}.`)
  const ids = new Set(QUESTION_BANK.map((item) => item.id))
  if (ids.size !== QUESTION_BANK.length) throw new Error('Question IDs must be unique.')
  QUESTION_BANK.forEach((item) => {
    if (typeof item.answer === 'number' && (!item.options || item.answer < 0 || item.answer >= item.options.length)) {
      throw new Error(`Invalid objective answer for ${item.id}.`)
    }
    if (!item.topic || !item.difficulty) throw new Error(`Missing topic metadata for ${item.id}.`)
  })
}
validateQuestionBank()
export const AUTHORED_FORMS = materializeAuthoredForms(QUESTION_BANK)
const NO_EXCLUSIONS = new Set<string>()
export const buildReadingPracticeSet = (excludedIds: ReadonlySet<string> = NO_EXCLUSIONS) => buildReadingBlueprint(QUESTION_BANK, excludedIds)

export const countReadingScoredItems = (items: BaseItem[]) => items.reduce((total, item) => {
  if (item.section !== 'reading') return total
  if (item.kind !== 'complete-words') return total + 1
  return total + String(item.answer || '').split('|').filter(Boolean).length
}, 0)

export const buildFullPracticeSet = (excludedIds: ReadonlySet<string> = NO_EXCLUSIONS) => buildFullBlueprint(QUESTION_BANK, excludedIds)
export const buildSectionPractice = (section: Section, excludedIds: ReadonlySet<string> = NO_EXCLUSIONS) => buildSectionBlueprint(QUESTION_BANK, section, excludedIds)
export const countBySection = (section: Section, excludedIds: ReadonlySet<string> = NO_EXCLUSIONS) => QUESTION_BANK.filter((item) => item.section === section && !excludedIds.has(item.id)).length
