import type { CoachedItem } from './coachedTaskHelpers'

type InterviewSet = { topic: string; context: string; questions: [string, string, string, string]; models: [string, string, string, string]; tips: [string, string, string, string] }

const interviewSets: InterviewSet[] = [
  { topic: '공부하는 장소', context: '학생 생활에 관한 인터뷰에서 공부 장소와 습관을 이야기합니다.', questions: ['Where do you usually study, and what is that place like?', 'Do you prefer studying alone or with another person?', 'What feature of a study space helps you concentrate most?', 'If your usual study place were unavailable tomorrow, what would you do?'], models: [
    'I usually study in a small reading area on the upper floor of the library. It has enough light, and people tend to work quietly there. Last week, I used it to prepare a short presentation because I could spread my notes on the desk without distractions from my room. I like having a clear place to work and then leaving when I finish. It helps me separate study from rest. The area can be busy during examinations, so I try to arrive early and take only the materials I need for that session.',
    'I prefer studying alone when I am first learning something, then discussing it with another person afterward. On my own, I can stop at a difficult part and work at my own pace without feeling that I am delaying someone. Once I understand the main ideas, a partner helps me notice gaps in my explanation. For example, I might think I understand a chapter until a classmate asks a simple question I cannot answer clearly. So I would not choose only one method for every task. I use them at different stages of my preparation.',
    'The most helpful feature is a space where interruptions are limited. I do not need complete silence, but it is difficult to follow an argument if people repeatedly start conversations beside me. A clear desk also helps because I can keep only the current task in view. When I study in a shared area, I put my phone away and decide what I want to finish before taking a break. Those habits matter as much as the room itself. Even a good study space will not help if I keep switching to unrelated messages.',
    'I would first decide what kind of work I need to do. If it is quiet reading, I could use another library area or a calm room at home. If I need to talk through a presentation, I would look for a group room instead. I would check availability before traveling somewhere and bring a smaller set of notes in case desk space is limited. Losing my usual place might be inconvenient, but it would not mean abandoning the whole plan. I would keep the same learning goal and adapt the location around it.',
  ], tips: ['장소의 특징뿐 아니라 사용하는 상황도 설명하기', '혼자 또는 함께 공부하는 선호를 과제와 연결하기', '집중에 도움이 되는 특징과 작용을 연결하기', '장소가 바뀌어도 학습 목표를 유지하는 계획 제시'] },
  { topic: '팀 과제 협력', context: '협력 경험과 팀의 의사소통 방법을 묻는 인터뷰입니다.', questions: ['Tell me about a task you completed with other students.', 'Would you rather plan the work carefully first or begin and adjust as you go?', 'What helps a team handle a disagreement?', 'Imagine that a teammate becomes unavailable just before a deadline. How would you respond?'], models: [
    'I worked with three classmates on a presentation about a public space near campus. We visited the area, took notes, and compared how people used the seating. My role was to organize our observations into a few clear points. At first, everyone wanted to include different details, so the slides became crowded. We improved the presentation by agreeing on one main question and using examples that answered it. That experience showed me that teamwork is not only dividing tasks. We also need to check whether the separate parts make sense when they are put together.',
    'I prefer making a simple plan first, then adjusting it as we learn more. A plan helps the group see who is responsible for each task and when the parts need to be ready. Without it, two people might do the same work while another part is forgotten. However, a very detailed plan can become a problem if the information changes. I would agree on the goal, basic roles, and first deadline, then review progress together. That gives us direction without making everyone follow an arrangement that no longer fits the task.',
    'A team handles disagreement better when members explain the reason behind their suggestion. Saying that a slide is bad does not help much, but explaining that the main point is hard to find gives us something to improve. I also think it helps to compare each idea with the purpose of the project rather than with personal preference. In my group, we sometimes asked what a new listener would need to understand first. That question made the discussion less personal and helped us choose a solution. Everyone still needed a chance to speak.',
    'I would contact the teammate to find out what is already finished and what still needs attention. Then I would tell the rest of the group so we can redistribute the remaining work realistically. I would not assume that someone has done nothing simply because they are unavailable. If the missing part is too large to complete responsibly, we could explain the situation to the instructor and ask about the available options. The immediate goal would be a clear plan that the remaining members understand, while keeping the absent person informed rather than blaming them.',
  ], tips: ['팀에서 맡은 역할과 결과를 한 가지씩 말하기', '계획의 장점과 수정 가능성을 함께 설명하기', '사람 비난 대신 과제 목적을 기준으로 제시하기', '진행 상태 확인 후 분담이나 문의 순서 설명하기'] },
  { topic: '통학과 이동', context: '캠퍼스 이동 경험과 교통 선택에 관한 인터뷰입니다.', questions: ['Describe your usual journey to a class or another regular activity.', 'For a short campus trip, would you choose walking or a shuttle?', 'What makes a route convenient for students?', 'Suppose your regular bus stop moved farther away. How would you adapt?'], models: [
    'My usual journey begins with a short walk to a bus stop, followed by a ride to the campus entrance. From there, I walk to the teaching building. I normally leave enough time for one missed bus because the road can be busy in the morning. I use the ride to look over my plan for the day, although I do not try to read anything complicated. The most uncertain part is the wait at the stop, so I check the service information before leaving home. Having that routine makes the journey feel more manageable.',
    'For a short trip, I would usually walk if the route is comfortable and I have enough time. Walking gives me a break after sitting in class, and I do not have to wait for a shuttle. However, I would choose the shuttle if I were carrying heavy materials or if the weather made the route difficult. The choice also depends on whether the path is safe and easy to use. I do not think one method is always better. I prefer the option that gets me there reliably without making the next activity harder.',
    'A convenient route needs more than a short distance. Students should be able to understand where it goes, cross roads safely, and reach the entrance they actually use. A route that looks quick on a map may be inconvenient if it includes stairs, poor lighting, or an unpredictable wait. Clear signs and information about delays are useful too. For example, I can plan around a ten-minute walk, but I cannot plan well if I do not know whether a shuttle is running. Reliability and access matter as much as speed.',
    'I would check the new location and estimate how much extra time the walk requires before changing my routine. If the route is reasonable, I could leave home earlier and use the same bus. If the change makes travel difficult, I would look for another service or ask the transport office about an accessible alternative. I would also explain any repeated lateness to my instructor rather than assuming the problem is obvious. The important thing is to test the new journey once and make a realistic plan, instead of guessing that my old schedule will still work.',
  ], tips: ['여정의 단계와 자주 생기는 변수 설명하기', '선호를 말하되 날씨나 짐 같은 조건 추가하기', '편리함을 거리만으로 설명하지 않기', '새 경로를 확인하고 시간 계획을 수정하기'] },
  { topic: '행사 자원봉사', context: '학생 행사에서 도움을 주는 경험과 역할 선택에 관한 인터뷰입니다.', questions: ['Describe a time you helped with an event or shared activity.', 'Would you prefer welcoming visitors or preparing things behind the scenes?', 'Why is a short briefing useful for volunteers?', 'If you could not attend your assigned shift, what would you do?'], models: [
    'I helped at a small welcome event for new students. My main task was to guide people from the entrance to the right room and explain where they could ask questions. I was nervous at first because I did not know every answer, but the organizer had given us a clear contact person for difficult questions. That helped me feel useful without pretending to know everything. I also noticed that a friendly greeting made visitors more willing to ask for help. By the end, I understood how a simple role can affect the whole event.',
    'I would prefer welcoming visitors because I enjoy helping someone feel comfortable in an unfamiliar place. The role also gives me practice explaining information clearly. I would still want a short set of instructions so I know where to direct a question I cannot answer. Preparing things behind the scenes is equally important, but I find it easier to stay motivated when I can see how my help affects another person immediately. If the organizer needed setup support more urgently, though, I would be willing to do that. My preference should not prevent the team from meeting its needs.',
    'A short briefing helps volunteers understand the same plan and avoid giving visitors conflicting information. It should explain the main tasks, the schedule, and who makes a decision if something changes. For example, if a room becomes unavailable, volunteers should know where to send people rather than each inventing a different answer. The briefing also gives new volunteers a chance to ask simple questions before the event becomes busy. It does not need to be long. A clear explanation with a small written reference may be more useful than a large amount of information nobody can remember.',
    'I would contact the organizer as soon as I knew there was a conflict. I would explain which shift I cannot cover and offer another time or a useful task I can complete beforehand. I would not remove my name from the schedule and assume someone else will notice. If there is a system for finding a replacement, I would follow it and wait for confirmation that the change is agreed. This gives the organizer time to protect the service. Even if I cannot attend, I can still act responsibly by communicating early and clearly.',
  ], tips: ['도움을 준 구체적인 역할 중심으로 이야기하기', '역할 선호와 팀 필요를 함께 고려하기', '안내가 없을 때 생기는 문제의 예 제시하기', '조기 연락과 변경 확인을 순서대로 설명하기'] },
  { topic: '새로운 생활 기술', context: '수업 밖에서 배운 기술과 연습 방법에 관한 인터뷰입니다.', questions: ['What is a simple skill you learned outside your regular classes?', 'Do you prefer learning from a video or from a person?', 'What makes feedback useful when you practice?', 'If a friend wanted to learn the same skill quickly, what advice would you give?'], models: [
    'I learned to prepare a few simple meals when I began living away from home. At first, I could follow a recipe, but I found it difficult to get everything ready at the same time. I started choosing meals with only a few ingredients and practiced the same one several times. That made the process less confusing. I also learned to prepare the ingredients before starting to cook instead of searching for things halfway through. The skill is useful because it helps me manage ordinary days without needing a complicated plan for every meal.',
    'I prefer learning from a person when I am trying something for the first time. I can ask why a step matters and get help if my result looks different from the example. A video is useful afterward because I can pause it and review the sequence at my own pace. For cooking, seeing someone prepare the ingredients helped me notice details I had missed in written instructions. But I would not want to depend on that person every time. Combining a clear demonstration with repeated practice gives me both support and independence.',
    'Useful feedback tells me what to change and why, rather than only saying that the result is good or bad. If a meal takes too long to prepare, for example, advice about getting the ingredients ready first gives me a practical step to try. I also need to know what already worked so I do not change everything at once. One clear suggestion is often easier to use than several unrelated corrections. After trying it, I can compare the new result with the earlier one and decide whether the suggestion actually helped.',
    'I would advise my friend to begin with one manageable example and practice it more than once. Trying several difficult recipes immediately could make learning feel like a series of unrelated problems. I would show the basic steps, explain what needs attention, and let my friend do the task rather than watching me complete it. Then we could discuss one improvement for the next attempt. Learning quickly does not mean skipping every careful step. A simple method repeated successfully is more useful than a complicated performance that the person cannot reproduce independently.',
  ], tips: ['특별한 전문 기술이 아니라 생활 속 배움도 가능', '처음 학습과 복습의 도구를 구분해 설명하기', '평가와 실행 가능한 피드백의 차이 설명하기', '빨리 배우기를 무리한 단계를 건너뛰는 것으로 해석하지 않기'] },
  { topic: '바쁜 하루 계획', context: '학업과 생활을 함께 관리하는 방법을 이야기합니다.', questions: ['Describe a recent day when you had several things to do.', 'Do you prefer a fixed daily schedule or a more flexible one?', 'How can a break help you work effectively?', 'Imagine that an important new task appears unexpectedly. How would you reorganize your day?'], models: [
    'Recently, I had a morning class, a group meeting, and some work to finish before the evening. I wrote down the tasks and checked which ones depended on another person. That helped me keep the meeting time fixed while moving my individual reading to a quieter part of the day. I also prepared my materials the night before so I did not spend the morning looking for them. I did not finish everything I had hoped, but I completed the most important work. The experience taught me to make a plan that leaves some room for delays.',
    'I prefer a flexible schedule with a few fixed points. Classes and meetings need a clear time, but the order of my individual tasks can change. If I am tired after a long class, I might deal with a simple message before attempting difficult reading. A completely fixed plan can make a small delay feel like failure, while no plan at all makes it easy to avoid important work. I find it useful to choose two or three priorities for the day and fit smaller tasks around them. That gives me direction without making the schedule unrealistic.',
    'A break helps when it gives me a genuine change of attention. If I have been reading for a long time, standing up or taking a short walk can make it easier to return to the text. I also use the break to ask whether my current method is working. Sometimes I notice that I have been looking at the same paragraph without understanding it. In that case, I may return with a more specific question. A break becomes less useful if I begin an unrelated activity that is difficult to stop, so I try to keep it simple.',
    'I would check the new task’s deadline and importance before moving everything else. If it must be done today, I would decide which planned activity can safely wait and whether anyone needs to know about the change. For a group task, I would explain my new availability instead of disappearing from the meeting. I would also break the urgent work into the first few steps so I can begin without spending too long worrying about the whole day. The aim would be to make a revised plan I can actually follow, rather than pretending every task still fits.',
  ], tips: ['하루의 일을 시간순으로 나열하는 데서 그치지 않고 선택을 설명하기', '고정된 일정과 조정 가능한 일을 구분하기', '휴식의 구체적인 행동과 다시 집중되는 이유 설명하기', '새 과제의 우선순위를 확인한 뒤 계획 수정'] },
  { topic: '캠퍼스에서 도움 요청', context: '정보가 필요할 때 도움을 구하는 경험을 이야기합니다.', questions: ['Tell me about a time you asked someone on campus for help.', 'Would you rather ask a question in person or send a message?', 'Why might students hesitate to ask for help?', 'If the usual support office were closed when you needed advice, what would you do?'], models: [
    'I once asked the library desk for help finding a resource that our instructor had recommended. I had searched the title but could not tell whether it was a book or part of a journal. The librarian asked for the details I had and showed me a different way to search. I found the resource, but I also learned how to check a reference before beginning. I was glad I asked instead of continuing the same search for another hour. It showed me that asking a specific question can save time and teach a useful method.',
    'I prefer asking in person when I need to understand a process, because I can follow up if the explanation is unclear. For a simple question about opening hours or a form, a message is more convenient and gives me something to refer to later. I would also consider the other person’s time. If the desk is very busy, I can describe my question briefly and ask whether there is a better moment. So my choice depends on the kind of help I need. I want the conversation to be clear rather than necessarily long.',
    'Students may hesitate because they think the question is too simple or worry that asking will make them look unprepared. I have felt that way when everyone else seemed to understand an instruction. But appearing confident is not the same as understanding what to do. It helps when staff explain that questions are normal and give students a clear place to ask them. Students can also prepare a specific question by saying what they have already checked. That makes it easier for the person helping them to see where the confusion begins.',
    'I would first check whether the office provides written guidance or an alternative contact. If the issue can wait, I would send a clear message describing what I need and when I need it, then avoid making an unsupported decision while waiting. If there is a deadline, I would contact the relevant course or service staff and explain that the usual office is unavailable. I would not assume that a friend’s advice changes an official rule. My aim would be to find a reliable answer and keep a record of any instruction I receive.',
  ], tips: ['도움을 요청한 내용과 배운 방법을 구체화하기', '질문의 종류에 따라 연락 방법을 선택하기', '주저하는 이유와 도움이 되는 환경을 함께 설명하기', '확인되지 않은 조언 대신 공식 대안 경로 찾기'] },
  { topic: '새 동아리에 참여', context: '관심 모임에 참여하고 새 사람을 만나는 경험을 묻습니다.', questions: ['Describe a club or informal group you have joined or would like to join.', 'Would you feel more comfortable in a large group or a small one?', 'What can make a group welcoming to newcomers?', 'Suppose two new members remain quiet during an activity. What could the organizer do?'], models: [
    'I joined an informal photography group because I wanted to notice more about the places I walk through every day. We did not need expensive cameras; most people used their phones. At the first meeting, we photographed one familiar building from different angles and compared the results. That made it easy to contribute even though I was a beginner. I enjoyed hearing what other people had noticed. The group gave me both a reason to practice and a way to meet students outside my course, without needing to begin with a complicated project.',
    'I feel more comfortable in a small group when I am new. It is easier to learn names, ask a question, and understand how the activity works. In a large group, I sometimes spend too much time worrying about when to speak. However, a bigger group can offer more ideas and different people to learn from. I would like an arrangement where newcomers begin in pairs or small teams, then share something with the whole group. That would give me a manageable first step while still allowing me to benefit from the wider group.',
    'A welcoming group explains ordinary things that experienced members may take for granted. Newcomers need to know what to bring, how an activity begins, and whether they are expected to have a certain skill. It also helps if someone introduces people rather than leaving everyone to find a place alone. In my photography group, the first task was simple enough for all of us to try. That made the welcome practical, not just friendly words. I think newcomers should be given a real way to contribute without being put under pressure to perform immediately.',
    'The organizer could offer a small pair activity before asking for comments from the whole group. That gives the new members time to think and a safer opportunity to speak. I would not assume they are uninterested just because they are quiet; they may be learning the format or unsure about their language. The organizer could also ask a simple, open question and make it clear that passing is acceptable. Afterward, a brief private check might reveal what would help. The goal would be to invite participation while respecting how comfortable each person feels.',
  ], tips: ['참여 경험이 없다면 참여하고 싶은 모임과 이유를 솔직히 설명하기', '집단 크기의 선호를 참여 경험과 연결하기', '친절하다는 말보다 구체적인 환영 행동 제시하기', '조용한 참가자를 단정하지 않고 작은 참여 기회 제안'] },
  { topic: '짧은 발표 준비', context: '발표 경험과 청중에게 내용을 전달하는 방법을 이야기합니다.', questions: ['Describe a short presentation you gave or prepared.', 'Do you prefer using brief notes or relying mainly on slides?', 'How can a speaker tell whether listeners understand?', 'If your speaking time were suddenly cut in half, how would you adjust?'], models: [
    'I prepared a short presentation about a survey our class carried out near the library. I wanted to explain one clear finding rather than every response we collected. My first draft had too much information, so I asked a classmate what they thought the main point was. Their answer showed me that the introduction was not clear enough. I revised it and chose one example to support the point. Practicing aloud also helped me notice where the explanation took too long. Preparing the talk taught me to think about what a listener needs, not only what I know.',
    'I prefer using brief notes, with slides that show only the material the audience needs to see. A few notes remind me of the order without encouraging me to read every sentence. Slides are useful for a picture or a simple comparison, but a page full of text can compete with what I am saying. When I practice, I try to explain each point without looking at a complete script. If I forget something, the notes help me return to the structure. That makes the presentation feel more like communicating an idea than reciting a paragraph.',
    'A speaker can check understanding through a short question or by asking listeners to explain the main idea in their own words. Facial expressions alone can be misleading because someone may be attentive but still confused. In a small class, I might pause after an example and ask what connection people noticed. If their answers differ from what I intended, I can clarify the point before adding more detail. It is also useful to invite questions without making listeners feel that confusion is a failure. Understanding should be checked through what people can explain, not only whether they look interested.',
    'I would keep the main point, one supporting example, and a clear ending. I would remove background that is interesting but not essential to understanding the argument. Trying to say the same script twice as fast would probably make it harder to follow. I would briefly tell the audience that I am focusing on the key idea, then use the remaining time carefully. If additional details are needed, I could provide a short note afterward. The purpose would still be communication. A shorter presentation can be useful if I choose what the listener most needs to remember.',
  ], tips: ['발표 내용보다 준비 과정의 한 문제와 수정에 초점 맞추기', '메모와 슬라이드의 서로 다른 역할 설명하기', '표정만이 아닌 이해 확인 행동 제안하기', '말을 빨리 하는 대신 핵심과 예를 선별하기'] },
  { topic: '학습용 디지털 도구', context: '학습에서 사용하는 간단한 디지털 도구의 장단점을 이야기합니다.', questions: ['What digital tool do you use for an ordinary study task?', 'Would you prefer one simple tool or several tools with more features?', 'What helps you decide whether a tool is actually useful?', 'If your preferred tool stopped working before a class, what alternative would you use?'], models: [
    'I use a simple notes application to keep questions that come up while I study. I create a page for each course and write a short heading above each question. Before a tutorial, I choose the questions I still cannot answer. This is more useful than collecting large amounts of text that I never review. I also add a brief explanation after I get help, using my own words. The application is convenient because I can find the notes on my phone or computer, but the important part is the routine of reviewing them.',
    'I would prefer one simple tool that I understand well. Several tools may offer useful features, but moving between them can make me spend more time arranging work than doing it. For notes, I mainly need to find information, edit it, and keep a reliable copy. If a new feature solves a problem I actually have, I can consider it later. I do not want to adopt a tool simply because it looks impressive. A manageable system also makes it easier to continue during a busy week when I have little time to learn new settings.',
    'I judge a tool by whether it helps me complete the task more clearly or reliably. If I use it to organize questions, I should be able to find those questions and act on them when needed. A tool may feel useful because it has many options, but that does not show that I understand the course better. I sometimes compare how I worked before and after using it. If it creates extra steps without helping, I simplify the process. I also consider whether I can keep my information accessible if the tool changes or becomes unavailable.',
    'I would use a saved copy of the important notes if one is available, or write a short list of the questions I remember on paper. I would not spend the whole time trying to restore every feature just before class. After the class, I could investigate the problem and check whether any information needs to be recovered. I would also use the experience to improve my backup routine. The immediate goal would be to participate in the lesson with the essential material, even if I have to use a less convenient method for that day.',
  ], tips: ['도구 이름만 말하지 말고 구체적인 사용 과정 설명하기', '기능 수와 실제 편리함을 구분하기', '실제 과제 수행의 변화로 유용성을 판단하기', '수업 참여에 필요한 핵심 자료를 먼저 확보하기'] },
  { topic: '도서관과 읽기', context: '읽을 자료를 고르고 도서관을 이용하는 경험을 이야기합니다.', questions: ['Tell me about a book or other reading material you found useful.', 'Do you prefer borrowing a printed book or using an electronic copy?', 'How do you choose what to read when you have limited time?', 'If the material you needed was unavailable, what would you do next?'], models: [
    'I found a short guide to writing clear reports useful during my first term. It did not give me sentences to copy, but it showed how an introduction can prepare the reader for the main question. I used that idea when revising a class report that began with too much background. After moving the question earlier, I could see which details were actually needed. I liked that the guide used simple examples and explained the reason for each change. It helped me work independently instead of needing someone to rewrite the report for me.',
    'I prefer an electronic copy for a short reference because I can search for a term and use it wherever I am studying. For a longer book, I often prefer print because it is easier for me to focus without switching to other applications. Borrowing either format is useful when I only need the material for one project. I would also check whether the electronic version has the features I need, such as readable text rather than unclear page images. My preference depends on the kind of reading, not simply on which format is newer.',
    'I begin with the question I need to answer and choose material that is relevant to it. I look at the contents or a short summary before deciding how closely to read. If I only need an overview, I do not treat every page as equally important. However, I am careful not to select just the passages that agree with my first idea. A source may include a limitation that changes how I should use it. With limited time, a clear purpose helps me read efficiently while still paying attention to what the material actually says.',
    'I would ask the library whether the material is available in another format or through a request service. I would explain when I need it so the staff can suggest a realistic option. If it cannot arrive in time, I would look for another reliable source covering the same question rather than assuming that any similar title will do. I could also ask my instructor whether there is a suitable alternative. I would keep a note of what I used, because the substitute may have a different focus and should not be cited as if it were the original source.',
  ], tips: ['자료가 실제 작업을 어떻게 바꾸었는지 설명하기', '읽기 목적에 따른 형식 선호 설명하기', '읽기 질문과 자료 선택을 연결하기', '기한과 자료 적합성을 함께 확인하기'] },
  { topic: '일상 식사 계획', context: '바쁜 학생 생활에서 식사를 준비하고 선택하는 방법을 묻습니다.', questions: ['Describe how you usually arrange meals on a busy day.', 'Would you rather cook a simple meal or eat at a campus cafeteria?', 'What makes meal planning convenient for you?', 'Suppose your usual place to eat closed unexpectedly. How would you handle the day?'], models: [
    'On a busy day, I try to know in advance where I can have a meal between classes. If I have a long break, I use the cafeteria. If the break is short, I bring something simple from home so I am not depending on a queue moving quickly. I also carry water and avoid leaving all the planning until I feel hungry. The routine is not complicated, but it helps me pay attention in the next activity rather than worrying about finding food. I adjust it when my timetable changes instead of following exactly the same plan every day.',
    'I would choose cooking a simple meal when I have enough time and a suitable kitchen. I can prepare something I like and keep the process familiar. On a crowded day, the cafeteria is more practical because I do not need to fit cooking and cleanup between other tasks. I would consider the available choices and whether I can reach it during its opening hours. So I prefer cooking in principle, but I do not make it a rule for every day. A useful meal plan should fit my actual schedule rather than create another source of pressure.',
    'Meal planning is convenient when it leaves me with a few reliable options instead of many last-minute decisions. I like knowing which meals are quick to prepare and which campus outlets are open after a late class. Having that information prevents me from walking somewhere only to find it closed. I also try to use ingredients that can work in more than one simple meal, so a timetable change does not leave me with a plan I cannot follow. The goal is not to design a perfect menu. It is to make ordinary meals easier to arrange.',
    'I would check another available place before changing the rest of my day. If I have little time, I could use a simple meal I brought or choose a nearby outlet with suitable food. I would not assume every alternative has the same opening hours or options. Afterward, I would find out whether the closure is temporary and adjust my plan for the next few days if necessary. Having a backup does not mean planning every possible problem. It means knowing one reasonable alternative so an unexpected change does not make the whole day difficult.',
  ], tips: ['실제 시간표에 맞춘 식사 준비 과정 설명하기', '시간과 시설 조건을 선호에 연결하기', '복잡한 계획보다 반복 가능한 선택 설명하기', '대안의 운영 시간과 이용 조건을 확인하기'] },
  { topic: '쉬는 시간의 활동', context: '일상에서 움직임과 휴식을 선택하는 경험을 이야기합니다.', questions: ['What do you like to do during a break from study?', 'Do you prefer a quiet indoor break or spending time outside?', 'Why is it useful to separate study time from rest?', 'If you had only ten free minutes between activities, how would you use them?'], models: [
    'During a break, I usually stand up and take a short walk around the building or outside if the weather is comfortable. I spend a lot of study time sitting and looking at text, so a change of place helps the break feel different. Sometimes I talk briefly with a classmate, but I do not want the conversation to turn into another project meeting. When I return, I check what I was trying to do before continuing. I find that a simple break is easier to manage than starting something that needs a lot of attention.',
    'I prefer spending time outside when there is an easy place to sit or walk nearby. Being away from my desk helps me stop thinking about the same paragraph for a few minutes. However, a quiet indoor space is better if the weather is uncomfortable or I need a calm place after a busy class. I do not need the break to be exciting. I mainly want a change that lets me return to the next task. My preference also depends on how much time I have, because traveling far away would make a short break less useful.',
    'Separating study from rest helps me give attention to both. If I keep checking work during every break, I may feel busy without making much progress or properly resting. A clear stopping point lets me notice what is finished and what I should do next. It also makes it easier to return, because I do not have to reconstruct the whole task. For example, I sometimes write a question to begin with when I come back. I would not claim that one routine suits everyone, but having a boundary makes my own day easier to manage.',
    'I would use part of the time to prepare for the next activity and the rest for a simple change of pace. I might refill my water, walk to the next building without rushing, and sit quietly for a few minutes. I would avoid starting a video or a long conversation that I cannot finish comfortably. If I need to send an important message, I would do that first and then put the phone away. With only ten minutes, I want the break to reduce pressure rather than create a new reason to hurry or arrive late.',
  ], tips: ['휴식 활동을 과장된 효과 없이 자신의 경험으로 설명하기', '선호와 날씨·거리·시간 조건을 함께 제시하기', '공부와 휴식의 경계가 필요한 이유 설명하기', '짧은 시간 안에 실행 가능한 계획 제시하기'] },
  { topic: '새로운 전시 방문', context: '박물관이나 전시에서 새로운 내용을 접하는 방법을 이야기합니다.', questions: ['Describe an exhibition or display you remember visiting.', 'Would you prefer a guided visit or exploring at your own pace?', 'What helps a visitor understand an unfamiliar object?', 'If you were planning a first visit for a friend, how would you prepare?'], models: [
    'I remember a small exhibition of photographs showing how a neighborhood had changed. Some pictures showed ordinary shops and streets rather than famous buildings. I liked comparing those scenes with places I already knew. One display included short comments from residents, which helped me understand why a change mattered to different people. I did not remember every date afterward, but I remembered the question of who gets to describe a place. The exhibition was useful because it connected unfamiliar historical information with everyday activities I could imagine, such as walking to a market or meeting a neighbor.',
    'I prefer exploring at my own pace, especially if the exhibition has clear labels. I can spend more time on something that interests me and pause without worrying about keeping up with a group. A guided visit is helpful when the objects need background that is difficult to find on my own. I would enjoy a short introduction followed by time to explore independently. That gives me a starting point without deciding every step of the visit. I also like being able to return to one object after seeing others, because a comparison may change what I notice.',
    'A visitor needs enough context to know what an object is and why it is being shown. A clear label can connect a detail to a larger question without using too many specialized terms. It also helps to explain what remains uncertain rather than presenting a complete story that the evidence does not support. For example, knowing how a household item was used may make its shape meaningful. A picture of it in context can help too. The best explanation gives the visitor something to look for instead of replacing observation with a long paragraph to read.',
    'I would check the opening hours, travel route, and any access needs before choosing the visit time. Then I would find a brief overview so I can suggest a few interesting sections without planning every minute. I would ask my friend what they enjoy and how long they want to spend there. If they are new to museums, a shorter visit with a break may be more comfortable than trying to see everything. I would also leave room for questions that arise during the visit. Preparation should make the experience easier, not turn it into a fixed test.',
  ], tips: ['전시에서 기억나는 구체적인 부분과 의미 연결하기', '안내와 자율 관람이 각각 유용한 조건 설명하기', '설명문이 관찰을 돕는 방식을 보여 주기', '상대의 관심과 접근 조건을 확인하기'] },
  { topic: '피드백을 활용한 연습', context: '학습이나 생활 활동에서 피드백을 받고 다시 시도하는 경험을 묻습니다.', questions: ['Tell me about feedback that helped you improve something.', 'Do you prefer getting feedback immediately or after you have tried on your own?', 'What is the difference between a useful suggestion and a vague comment?', 'If you received two suggestions that seemed to conflict, what would you do?'], models: [
    'A classmate once helped me improve a short explanation in a report. I thought the paragraph was clear, but they asked which sentence contained the main point. I realized that I had put it near the end, after several details. Their question was more helpful than simply saying that the writing was confusing. I moved the main point earlier and checked whether the example supported it. Afterward, I used the same question when reviewing another paragraph. The feedback improved that piece of work, but it also gave me a method I could use independently.',
    'I prefer trying on my own first, then getting feedback while I still remember the decisions I made. If someone corrects every step immediately, I may follow the instructions without understanding the problem. A first attempt gives me something specific to discuss. However, I would ask for help early if the task involves a rule or procedure I should not guess. For ordinary writing practice, a short independent draft followed by a focused comment works well for me. I can compare the suggestion with my intention and then test whether the revision makes the explanation clearer.',
    'A useful suggestion identifies a particular issue and gives me a way to respond to it. Saying that a presentation needs to be better is vague because I do not know where to begin. Saying that the main example arrives too late tells me what to examine. A good comment may also explain the listener’s experience, such as losing track of the question. That helps me judge whether the change fits my purpose. I do not need every suggestion to include a complete replacement sentence. Sometimes a precise question encourages me to find a stronger solution myself.',
    'I would first check whether the suggestions concern the same goal. One person might want more background, while another wants a shorter introduction. Both comments could make sense for different audiences. I would ask what each person found difficult and compare that with the task requirements. Then I could try a version that keeps essential context but removes details that do not help. I would not combine every suggestion mechanically. My responsibility is to make a clear choice and test the result, while being willing to revise again if the explanation still does not work.',
  ], tips: ['피드백 전후에 바뀐 구체적인 부분 설명하기', '독립 시도와 조기 질문이 필요한 경우 구분하기', '모호한 평가와 실행 가능한 제안 비교하기', '서로 다른 제안을 목적과 청중 기준으로 판단하기'] },
  { topic: '캠퍼스 공지 이해', context: '공지와 일정 정보를 확인하는 방법을 이야기합니다.', questions: ['Describe a campus message that helped you make a decision.', 'Do you prefer a short reminder or a detailed announcement?', 'What information makes an announcement easy to act on?', 'If two notices gave different times for the same event, what would you do?'], models: [
    'A campus message once helped me decide whether I could attend a workshop. It stated the start time, expected finish, and the room, so I could compare it with my class schedule. It also explained that registration was needed even though the event was free. Without that detail, I might have arrived assuming I could simply join. I appreciated that the main action appeared near the beginning, followed by a link for further information. The message was useful because it connected the invitation with the practical steps I needed to take, rather than only describing the event.',
    'I prefer a short reminder after I have already received a detailed announcement. The first message needs enough information for me to decide and register correctly. A later reminder can focus on what I should do next, such as bring a document or arrive at a different entrance. If every reminder repeats a long description, the important change may be hard to notice. On the other hand, a very short message is not enough if I do not know the background. I like messages that clearly separate the main action from optional details and provide a reliable place to check more.',
    'An announcement is easy to act on when it tells the reader what to do, when to do it, and which conditions apply. A location is important too, especially if it differs from the usual one. For example, saying that a room has changed is less useful than naming the new room and stating which session the change affects. It should also explain where to ask a question. I do not need every message to be extremely short. I need the practical information to be easy to find and consistent with the details that follow.',
    'I would check which notice is more recent and whether it clearly says that the schedule has changed. If I still could not tell, I would contact the organizer and mention both times. I would avoid choosing the more convenient time or forwarding it to others as confirmed. Once I received a reliable answer, I could update my own plan and share the correction where appropriate. If the event were very soon, I would allow extra time while trying to confirm the information. The important point would be to resolve the conflict rather than hide it.',
  ], tips: ['공지의 정보와 자신의 결정 연결하기', '첫 안내와 후속 알림의 역할 구분하기', '행동·시점·조건을 실제 예로 설명하기', '편한 정보를 골라 믿지 않고 발행 시점과 주최자 확인'] },
  { topic: '낯선 장소 찾아가기', context: '새 장소를 방문할 때 길과 일정을 확인하는 경험을 이야기합니다.', questions: ['Tell me about a time you went to an unfamiliar place.', 'Would you rather use a map or ask someone for directions?', 'What makes directions clear and useful?', 'Suppose you reached the right building but could not find the entrance. What would you do?'], models: [
    'I once went to a different campus building for a weekend workshop. I had checked the street location, but I did not realize that the usual entrance was closed outside weekday hours. I arrived with some extra time, so I could read the sign and find the side entrance without missing the introduction. The experience taught me that reaching the building is not always the whole journey. Now I look for arrival instructions as well as the address. If an event is unfamiliar, I also keep the organizer’s contact information available in case I need clarification.',
    'I prefer using a map to understand the overall route, then asking a person if a local detail is unclear. A map helps me see the direction and estimate the journey, but it may not show which door is open or how to reach a particular room. Asking someone can solve that problem, especially if I can explain exactly where I want to go. I try not to rely on one vague instruction such as going over there. Combining the two methods gives me both an overview and practical guidance for the final part of the trip.',
    'Clear directions use recognizable points and explain the important choices along the way. Saying that a room is near a large building is less helpful than naming the entrance and the floor. It also helps to mention a step-free route if the usual way includes stairs. For an unfamiliar visitor, words such as the usual entrance do not mean much. Directions should be written from the visitor’s point of view, not only from someone who already knows the place. A simple map and a few clear steps can work together when the route has several possible turns.',
    'I would look for a sign naming an alternative entrance and check the event’s arrival instructions. If I still could not identify the route, I would contact the organizer or ask staff in a nearby public area. I would describe the building and the side I had reached so the person could give specific help. I would not try a restricted door simply because it seemed closer. Once I found the entrance, I would note the detail for the return journey. The immediate aim would be to enter through the proper route without guessing.',
  ], tips: ['여정에서 생긴 작은 문제와 배운 점 설명하기', '전체 경로와 현장 세부 안내를 구분하기', '방문자 관점에서 명확한 기준점 제시하기', '도착 안내와 직원에게 확인하는 순서 설명하기'] },
  { topic: '공용 공간 생활', context: '다른 사람과 생활 공간을 공유하는 경험과 규칙을 이야기합니다.', questions: ['Describe a shared space you use and how people look after it.', 'Would you prefer fixed responsibilities or deciding tasks together each week?', 'Why is a shared rule easier to follow when everyone understands its purpose?', 'If one person could not complete their usual task for a week, how should the group respond?'], models: [
    'I use a shared kitchen with several other students. We are expected to clean the counter and dishes after preparing food, while larger tasks are discussed together. The system works best when people deal with their own work before leaving, because the next person can begin without cleaning someone else’s mess. We had a problem with unclear storage spaces at first, so we added simple labels after agreeing where things belonged. That made the room easier to use. I learned that a shared space needs understandable arrangements as well as a general request to be considerate.',
    'I would prefer fixed responsibilities for ordinary tasks, with a chance to review them each week. Knowing who checks supplies or takes out waste prevents the task from being forgotten because everyone assumes someone else will do it. However, people’s schedules change, so there should be a way to swap responsibilities by agreement. I would not want a new long discussion about every small task. A clear basic plan with simple updates seems more practical. It gives everyone a predictable role while recognizing that fairness does not require exactly the same arrangement every week.',
    'When people understand the purpose of a rule, they can apply it more thoughtfully. A request to keep the walkway clear makes more sense when everyone sees that others need to move through safely, not merely because someone prefers a tidy room. Understanding the reason also helps when a new situation appears that the rule does not describe word for word. Still, the rule needs to be specific enough to follow. If it only says to be helpful, people may interpret it differently. I think a clear action and a clear reason work better together.',
    'The person should tell the group early and explain which task they cannot complete. The group could agree on a temporary swap or divide that task among available members, then review the arrangement afterward. I would avoid assuming the person is unwilling to help if there is a genuine short-term problem. At the same time, the change should be clear so the task is not left undone. A brief note of the agreement may be enough. The group should keep the space usable while finding a fair solution, rather than turning one difficult week into a personal conflict.',
  ], tips: ['공간의 규칙과 실제 이용 경험 함께 설명하기', '예측 가능한 책임과 일정 변경의 균형 제시하기', '규칙의 행동과 목적 연결하기', '일시적 조정과 지속적 부담을 구분하기'] },
  { topic: '수업 선택', context: '관심과 시간표를 고려하여 수업을 고르는 방법을 이야기합니다.', questions: ['Describe a class you chose because it interested you.', 'Do you prefer learning through practical activities or through reading and discussion?', 'What information helps you decide whether a course is right for you?', 'If the course you wanted were full, how would you choose another option?'], models: [
    'I chose an introductory design class because I wanted to understand how ordinary objects are made easier to use. The course asked us to observe a simple object, identify a problem, and explain a possible change. I enjoyed that because it connected an idea with something I could see. I also discovered that describing the user’s need was harder than drawing a new shape. That made the class useful beyond design: I began asking what problem an assignment was actually trying to solve. I did not choose it because I already knew the subject, but because I wanted a different way to think.',
    'I prefer practical activities followed by discussion. Trying something gives me a concrete experience to refer to, while discussion helps me understand why it worked or did not work. For example, observing how people use a room can make a planning concept more meaningful than reading its definition alone. However, practical activity without background can leave me guessing, so I still need clear reading or instruction. I would not remove either method. I learn best when I can connect a concept, an action, and a chance to explain the result in my own words.',
    'I want to know the course goals, the kind of work students will do, and the background knowledge expected. A title may sound interesting while hiding a workload or skill requirement I am not ready for. Sample activities can help me judge the fit better than a general description saying the course is exciting. I also need to check the timetable and whether it meets a requirement in my program. Advice from another student is useful, but their experience may differ from mine. I would compare it with the current course information before making a decision.',
    'I would check whether there is a waiting list and whether another section offers the same course. If neither is practical, I would identify what interested me most and look for another course that develops a related skill or question. I would also confirm that the alternative fits my program and timetable. Choosing only because a seat is available could create a problem later. If I am uncertain, I would ask an adviser with a short list of possibilities. I might take the original course in a later term rather than treat the closed class as the end of that interest.',
  ], tips: ['흥미를 보인 이유와 실제 학습 활동 연결하기', '선호하는 방식과 다른 방식의 보완 역할 설명하기', '제목 외에 확인해야 할 현재 수업 정보 제시하기', '자리 유무와 학습 목표·시간표를 함께 고려하기'] },
  { topic: '일과 진로 탐색', context: '관심 있는 일과 처음 경험해 보고 싶은 업무를 이야기합니다.', questions: ['What kind of work would you like to learn more about, and why?', 'Would you prefer trying a short placement or speaking with people who do that work?', 'What question would help you understand a job beyond its title?', 'If a placement sounded interesting but the responsibilities were unclear, how would you respond?'], models: [
    'I would like to learn more about work that involves explaining information to the public, such as a role in a museum or community service. I enjoy helping someone understand a new idea, but I do not yet know what the day-to-day work includes. It may involve preparation and coordination as well as speaking with visitors. I would like to find out how staff decide what information people need and how they respond to different questions. Exploring the work would help me judge whether my interest fits the actual responsibilities, rather than choosing it only because the title sounds appealing.',
    'I would begin by speaking with people who do the work, then consider a short placement. A conversation can help me understand the ordinary tasks, schedule, and skills before I commit time to trying the role. A placement gives a more direct experience, but it is useful only if the responsibilities are clear and someone can guide me. I would prefer to ask about a typical day and a difficult part of the job rather than only its advantages. That information could help me choose a placement where I would learn something relevant and contribute appropriately.',
    'I would ask what a person actually does during a typical week and which tasks take the most time. A title can make a job sound as if it is mainly one interesting activity, while ordinary work may include planning, checking details, and communicating with other teams. I would also ask what a new person often finds surprising. That question could reveal a challenge not included in a short description. The purpose would not be to find a perfect job without difficulties. It would be to understand whether I could learn the work and accept the less visible parts as well.',
    'I would ask the organizer to explain the main tasks, expected hours, supervision, and what I would be allowed to do. I would also want to know who I could contact if a task was unclear. I would not accept vague promises that I could learn everything after arriving. Once I had the information, I could compare the placement with my schedule and learning goals. If the answers remained unclear, I would consider another opportunity. Interest is important, but a useful placement needs a realistic role and enough support for someone who is still learning.',
  ], tips: ['직접 일해 본 경험이 없어도 관심과 확인할 내용을 설명하기', '대화와 실제 경험을 단계적으로 연결하기', '직책 이름보다 일상 업무를 묻는 질문 제시하기', '관심만으로 결정하지 않고 역할과 지도 체계를 확인하기'] },
]

const stageChecklists = [
  ['질문에 맞는 장소·활동·경험을 먼저 밝히기', '본인이 한 일이나 구체적인 장면 제시', '경험의 결과나 배운 점 연결'],
  ['선호하는 선택을 분명히 말하기', '자신에게 맞는 이유와 짧은 예 제시', '필요한 경우 다른 선택이 유용한 조건 인정'],
  ['도움이 되는 특징이나 이유를 직접 설명하기', '특징이 결과에 연결되는 과정 보여 주기', '같은 주장만 반복하지 않고 사례로 구체화'],
  ['가정된 상황에 맞는 첫 행동 제시', '가능한 확인·대안·다음 단계 설명', '실제 경험과 가정의 시제를 구분하기'],
]

export const coachedInterviewItems: CoachedItem[] = interviewSets.flatMap((set, group) => set.questions.map((audioText, index) => {
  const scenario = `coached-interview-${String(group + 1).padStart(2, '0')}`
  return {
    id: `${scenario}-${index}`, section: 'speaking', module: 1, kind: 'interview', title: 'Take an Interview',
    sourceFamily: 'authored-coached-2026', topic: set.topic, context: set.context, difficulty: 'B2',
    audioText, modelResponse: set.models[index], stimulusGroupId: scenario, scenarioId: scenario, sequenceIndex: index,
    timeSeconds: 45, responseTimeSeconds: 45,
    instruction: '질문을 듣고 자신의 경험이나 의견으로 답하세요. 전문 지식보다 질문에 맞는 내용, 구체적인 예, 이해하기 쉬운 흐름에 집중하세요.',
    taskChecklist: stageChecklists[index],
    commonMistakes: ['질문을 그대로 반복하고 직접적인 답을 미루기', '구체적인 예 없이 좋은 점이나 나쁜 점만 나열하기', '예시 답안을 자기 경험인 것처럼 그대로 외워 말하기'],
    targetSkills: ['직접적인 응답', '이유와 구체적 예', index === 3 ? '가정 상황의 실행 계획' : '자연스러운 연결과 설명'],
    rewriteGuidance: ['예시의 장소·인물·활동을 실제 자신의 상황으로 바꾸세요. 경험이 없다면 그 사실을 밝히고 가까운 사례나 가능한 선택을 설명하세요.', set.tips[index], '한 번 녹음한 뒤 질문에 직접 답했는지, 예가 이유를 뒷받침하는지 확인하고 다시 말해 보세요.'],
    explanation: `상황: ${set.context} ${set.tips[index]} 예시는 보통 속도로 약 45초를 목표로 한 답안이며 실제 발화 속도에 따라 길이를 조절하세요. 모든 질문에 억지로 어려운 문법이나 같은 서론을 넣기보다 질문의 초점에 맞게 답하세요.`,
  }
}))
