import type { CoachedItem } from './coachedTaskHelpers'
import { coachedInterviewItems } from './coachedInterviews'

type RepeatSet = { topic: string; context: string; sentences: string[] }

const repeatSets: RepeatSet[] = [
  { topic: '도서관 첫 방문', context: '도서관 직원이 새 학생에게 시설 이용을 안내합니다.', sentences: ['Welcome to the campus library.', 'The information desk is beside the main entrance.', 'You can borrow books with your current student identification card.', 'Please use the return box when the service desk is closed.', 'Quiet study spaces are upstairs, while group rooms are available on the ground floor.', 'If you need a book that is already on loan, place a request through the library website.', 'Before leaving a group room, remove your belongings, return the chairs to their usual places, and check that the door is properly closed behind you.'] },
  { topic: '팀 회의실 이용', context: '학생 조장이 팀 회의실 사용 순서를 설명합니다.', sentences: ['Our meeting room is ready.', 'Put your bags under the table near you.', 'We will begin by reviewing the questions from our last meeting.', 'Each person should explain one finding before we compare the results together.', 'Keep the shared document open so everyone can see which points still need more evidence.', 'When we disagree about a detail, write it down as a question instead of changing the report immediately.', 'At the end of the meeting, confirm who will complete each remaining task, record the agreed deadlines, and send the updated plan to every team member.'] },
  { topic: '캠퍼스 도보 안내', context: '학생 안내자가 새 방문객에게 도보 이동 경로를 설명합니다.', sentences: ['The campus walk begins here.', 'Follow the path beside the student center.', 'The building on your left contains the main lecture rooms.', 'We will stop at the next crossing before continuing toward the sports center.', 'If you need a step-free route, please tell us before the group reaches the stairs.', 'There is a short break near the cafeteria, where you can refill your water bottle and ask questions.', 'Before we continue to the residence area, check that your group is together and let the guide know if anyone needs a slower route or another rest.'] },
  { topic: '언어 교류 시작', context: '언어 교류 모임 진행자가 짝 활동을 안내합니다.', sentences: ['Thank you for joining us.', 'Choose a partner you have not met before.', 'Start by telling each other about an ordinary day on campus.', 'You do not need perfect grammar to make your meaning clear today.', 'After a few minutes, switch languages so both partners have a chance to practice speaking.', 'If your partner cannot find a word, give them time before offering a helpful example or another expression.', 'Before changing partners, mention one thing you learned from the conversation and choose a question that you would like to ask someone else during the next round.'] },
  { topic: '공원 청소 봉사', context: '봉사 담당자가 공원 청소 참가자에게 순서를 안내합니다.', sentences: ['We are meeting beside the gate.', 'Collect your gloves from the volunteer table.', 'Stay with your partner while you work along the marked path.', 'Place ordinary litter in the bags provided by the team leader.', 'If you notice anything sharp or unfamiliar, leave it where it is and tell a supervisor.', 'We will take a break halfway through the session, so keep your water bottle somewhere you can reach easily.', 'When your area is finished, return the equipment to the table, tell the leader which section you covered, and check that your partner has returned with you.'] },
  { topic: '튜터링 모임 준비', context: '학습 지원 담당자가 첫 튜터링 모임을 소개합니다.', sentences: ['Your tutor will arrive shortly.', 'Please bring your notes to the small table.', 'Choose one question that you found difficult while studying this week.', 'The tutor will help you explain your approach before suggesting another method.', 'You may discover that a small change in one step makes the whole problem easier to understand.', 'Keep a note of the explanation in your own words so you can try a similar question after the session.', 'Before you leave, tell the tutor what you will practice next and ask how you can check whether you have understood the method without copying the example.'] },
  { topic: '학생 포스터 전시', context: '행사 진행자가 발표자에게 포스터 전시 준비를 안내합니다.', sentences: ['The poster session starts soon.', 'Find the board marked with your project number.', 'Use the clips on the table to attach your poster carefully.', 'Keep the walkway clear so visitors can move between the displays easily.', 'Begin your explanation with the main question rather than reading every line printed on the poster.', 'When a visitor asks something you cannot answer, explain what you know and note what would need further checking.', 'After the session, take your poster down, collect any handouts that remain, and share useful questions with your group before deciding how to revise the project.'] },
  { topic: '사진 동아리 산책', context: '동아리 진행자가 초보자 사진 산책을 안내합니다.', sentences: ['Our photo walk starts outside.', 'Check that your camera or phone is charged.', 'We will photograph familiar spaces from several different positions this afternoon.', 'Look for a subject with clear shapes before changing any camera settings.', 'Ask permission before photographing someone closely, and respect their choice if they prefer not to appear.', 'At each stop, compare your pictures with a partner and explain which detail you wanted the viewer to notice.', 'Before returning to the meeting room, choose two photographs that show different approaches to the same subject and be ready to describe why you selected each one.'] },
  { topic: '초급 수영 강습', context: '강사가 첫 초급 수영 강습의 진행을 설명합니다.', sentences: ['Welcome to your first lesson.', 'Wait beside the pool until your instructor arrives.', 'We will begin with a short explanation before entering the water.', 'Tell the instructor if you feel unsure about any part of the activity.', 'Today you can practice at a comfortable pace rather than trying to keep up with someone else.', 'When the instructor gives a new direction, stop and listen so you know which part of the pool to use.', 'At the end of the lesson, leave the pool by the marked steps, collect your belongings, and ask the instructor which simple skill you should practice next.'] },
  { topic: '박물관 수업 방문', context: '박물관 안내자가 학생들의 관찰 활동을 소개합니다.', sentences: ['Our museum visit begins here.', 'Leave large bags in the lockers near reception.', 'You may carry a notebook into the exhibition rooms this morning.', 'Choose one object and read its label before discussing it with your partner.', 'Notice which details the label explains and which questions remain unanswered after you have read it.', 'If photography is allowed in that room, take only the pictures you need and keep clear of other visitors.', 'Before the group meets again, write a short explanation of how the object was presented and identify one question you would ask the person who prepared the display.'] },
  { topic: '요리 동아리 첫 모임', context: '동아리 진행자가 함께 간단한 식사를 준비하는 절차를 안내합니다.', sentences: ['We will cook together today.', 'Wash your hands before handling any ingredients.', 'The recipe cards are on the counter beside the bowls.', 'Read your group’s card before deciding who will complete each part of the meal.', 'Tell the organizer about any food allergy or ingredient you need to avoid before cooking begins.', 'Keep the preparation area tidy as you work so another person can use it without moving sharp or hot items.', 'When the food is ready, check that every group member has a suitable portion, clean the shared equipment, and leave the counters ready for the next session.'] },
  { topic: '컴퓨터 도움 창구', context: '지원 직원이 학생들에게 기기 문제 접수 방법을 설명합니다.', sentences: ['The help desk is open.', 'Take a number from the screen by the door.', 'Write down the message that appeared when your problem began.', 'Our staff may ask what you were doing before the device stopped working.', 'Please keep your password private and let the staff explain any step before you carry it out.', 'If the problem needs more time, we will give you a reference number and explain how to follow the request.', 'Before leaving the desk, check that you understand the next step, save the reference number somewhere safe, and ask when you should expect another update about your device.'] },
  { topic: '학생 정원 모임', context: '정원 담당자가 새 참가자에게 식물 관찰과 작업을 안내합니다.', sentences: ['The garden team meets here.', 'Choose gloves that fit comfortably before you begin.', 'We will check the soil before deciding which beds need water.', 'Some plants require less water, so follow the labels beside each section.', 'Ask the team leader before removing a plant that you do not recognize in the garden.', 'As you work, note any damaged leaves or missing labels so the next group knows what needs attention.', 'Before returning the tools, record which beds you checked and what you did, then tell the next volunteer about any question that still needs an answer.'] },
  { topic: '학생 물품 교환 행사', context: '주최자가 중고 생활용품 교환 행사 참가자를 안내합니다.', sentences: ['The exchange tables are ready.', 'Place your items beside the correct category sign.', 'Include a clear note if an item has a missing part.', 'Visitors should be able to examine an item before deciding whether to take it.', 'Keep personal information out of notebooks or devices that you plan to give to another person.', 'If you are unsure whether something can be accepted, ask a volunteer instead of leaving it on an unrelated table.', 'At the end of the event, collect any items that remain under your name, help clear your table, and ask where accepted donations will be taken afterward.'] },
  { topic: '학생 음악 행사', context: '진행자가 짧은 학생 공연의 준비와 관객 안내를 설명합니다.', sentences: ['The first performance begins soon.', 'Performers should wait beside the stage entrance.', 'Keep the central walkway open while the audience takes their seats.', 'The sound check will finish before the doors open to the public.', 'If you need assistance reaching a seat, speak to the volunteer standing beside the entrance.', 'During the interval, you may leave the hall, but please return before the next group begins its performance.', 'After the final song, wait for the host’s announcement, collect your belongings carefully, and use the marked exit so the next event can begin setting up.'] },
  { topic: '쓰기 워크숍', context: '교사가 초고를 교환하는 짧은 쓰기 활동을 소개합니다.', sentences: ['Keep your first draft nearby.', 'Choose a paragraph that you want to improve.', 'Read it aloud once before handing it to your partner.', 'Your partner will describe the main point they understood from the paragraph.', 'If that point differs from your intention, explain your goal before discussing changes to individual sentences.', 'Write down one useful suggestion, but decide for yourself whether it helps the purpose of the paragraph you are revising.', 'Before sharing the new version, check that the main idea is clear, the example supports it, and the wording still expresses what you wanted to say.'] },
  { topic: '캠퍼스 자전거 안내', context: '교통 담당자가 공유 자전거를 처음 이용하는 학생에게 안내합니다.', sentences: ['The bicycles are parked here.', 'Choose one that matches your size comfortably.', 'Check the bicycle using the instructions posted beside the stand.', 'If anything seems damaged, leave it there and report the number to staff.', 'Use the marked campus routes and give pedestrians enough room when the path becomes narrow.', 'When you stop near a building, return the bicycle to a designated space rather than blocking an entrance or crossing.', 'Before ending your trip, check that the bicycle is properly secured, confirm that the return appears in your account, and report any problem you noticed along the route.'] },
  { topic: '기숙사 입주 안내', context: '기숙사 직원이 새 거주자의 입주 확인 절차를 안내합니다.', sentences: ['Welcome to your new residence.', 'Have your confirmation ready at the reception desk.', 'A staff member will explain how to collect your room key.', 'Check the room inventory before unpacking all of your belongings this afternoon.', 'If you notice damage that is already there, record it through the form provided at reception.', 'The shared spaces are open to all residents, but please follow the posted hours and keep the walkways clear.', 'Before leaving reception, confirm where to report a problem, save the residence contact details, and ask any question about the arrival instructions that is still unclear to you.'] },
  { topic: '과학 공개 행사', context: '안내자가 방문객에게 학생 시연 관람 방법을 소개합니다.', sentences: ['The demonstrations are starting now.', 'Stay behind the line marked on the floor.', 'Each student team will explain the question its demonstration explores.', 'Watch the first example before asking the presenter to repeat a particular step.', 'You can ask why the team made a choice instead of assuming that the result explains everything.', 'If a demonstration is paused, wait for the presenter’s instructions before moving closer or handling anything on the table.', 'Before visiting the next station, tell your partner what you observed, identify one part you still wonder about, and keep the route clear for other groups.'] },
  { topic: '취업 박람회 방문', context: '진로 담당자가 박람회를 방문하는 학생에게 준비 방법을 안내합니다.', sentences: ['The career fair is open.', 'The employer list is beside the entrance desk.', 'Choose a few organizations that connect with your current interests.', 'Prepare a short introduction before joining the queue at a busy table.', 'You may ask about a typical working day as well as the requirements listed in a vacancy.', 'After each conversation, make a brief note so you can compare the information instead of relying only on memory.', 'Before leaving the fair, check the application instructions for any role that interests you and note which questions you need to research before deciding whether to apply.'] },
]

const repeatItems: CoachedItem[] = repeatSets.flatMap((set, group) => set.sentences.map((audioText, index) => {
  const scenario = `coached-repeat-${String(group + 1).padStart(2, '0')}`
  const limit = index < 2 ? 12 : index < 5 ? 16 : 22
  return {
    id: `${scenario}-${index}`, section: 'speaking', module: 1, kind: 'repeat', title: 'Listen and Repeat',
    sourceFamily: 'authored-coached-2026', topic: set.topic, context: set.context,
    difficulty: index < 2 ? 'B1' : 'B2', audioText, modelResponse: audioText,
    stimulusGroupId: scenario, scenarioId: scenario, sequenceIndex: index,
    timeSeconds: limit, responseTimeSeconds: limit,
    instruction: '문장을 한 번 듣고 그대로 말하세요. 문장을 바꾸거나 의견을 덧붙이지 말고, 의미 단위와 리듬을 살리세요.',
    targetSkills: ['듣고 기억하기', '핵심 단어와 문법 보존', '의미 단위에 따른 발화'],
    taskChecklist: ['처음과 끝의 내용을 함께 유지하기', '핵심 명사·동사와 조건·순서를 빠뜨리지 않기', '문장을 새로 만들지 않고 들은 표현을 반복하기'],
    commonMistakes: ['문장의 후반부나 조건을 생략하기', '기억나지 않는 부분을 자신의 의견으로 바꾸기', '관사·전치사·복수형을 계속 빠뜨리기'],
    rewriteGuidance: ['복습할 때 문장을 의미 단위로 나누어 표시하세요.', '원문을 보며 한 번 연습한 뒤 가리고 다시 말해 보세요.', '재말하기 과제에서는 바꿔 쓰지 않습니다. 녹음을 비교해 빠진 부분을 보완하세요.'],
    explanation: `상황: ${set.context} ${index < 2 ? '짧은 문장에서 핵심 표현을 정확히 잡으세요.' : index < 5 ? '행동과 대상, 시간이나 조건을 묶어 기억하세요.' : '긴 문장을 앞·중간·끝의 의미 단위로 나누되 마지막 행동까지 유지하세요.'} 이 과제는 원문을 반복하는 연습입니다. 자신의 의견을 만드는 인터뷰 과제와 구분하세요.`,
  }
}))

export const coachedSpeakingItems: CoachedItem[] = [...repeatItems, ...coachedInterviewItems]
