import type { BaseItem } from './types'
import { prepareSentenceTiles } from './sentenceTiles'
import { paraphraseForOption } from './readingLanguage'
import { buildServiceSentencePattern } from './sentenceBuildPatterns'
import { buildDiscussionTask, buildEmailPrompt, buildInterviewScenario, buildRepeatScenario } from './openTaskPatterns'

type Difficulty = NonNullable<BaseItem['difficulty']>
type Seed = {
  topic: string
  difficulty: Difficulty
  academic: string
  subject: string
  finding: string
  limitation: string
  service: string
  problem: string
  action: string
  actor: string
  debate: string
  counterpoint: string
  personal: string
}

// Topic categories were broadened after reviewing official IELTS, Cambridge English,
// PTE Academic, and Duolingo English Test task descriptions. All wording below is original.
const SEEDS: Seed[] = [
  { topic: '재생에너지 저장', difficulty: 'C1', academic: 'a regional energy laboratory', subject: 'how neighborhood batteries support solar power', finding: 'shared batteries reduced evening demand on the grid', limitation: 'performance varied with weather and household routines', service: 'a campus microgrid trial', problem: 'solar energy is abundant at noon but demand peaks later', action: 'install a shared battery and publish weekly performance data', actor: 'the facilities team', debate: 'Should communities invest in shared batteries or encourage individual home systems?', counterpoint: 'individual systems give households more control', personal: 'energy use at home or school' },
  { topic: '물 절약', difficulty: 'B2', academic: 'an urban water research center', subject: 'feedback displays in apartment buildings', finding: 'residents used less water when they saw daily comparisons', limitation: 'the effect weakened after several months', service: 'a residence-hall conservation program', problem: 'water use rises sharply during hot weeks', action: 'send timely usage reports and repair leaking fixtures', actor: 'the housing office', debate: 'Should water conservation rely on prices or information?', counterpoint: 'price increases may burden large low-income households', personal: 'a realistic way to save water' },
  { topic: '산불 관리', difficulty: 'C1', academic: 'a forest ecology institute', subject: 'prescribed burns in dry woodlands', finding: 'small controlled fires reduced dense surface fuel', limitation: 'smoke and shifting winds limited safe burn days', service: 'a community fire-preparation workshop', problem: 'dry vegetation has accumulated near several homes', action: 'organize supervised fuel removal before the windy season', actor: 'the local fire department', debate: 'Should authorities use more prescribed fire near populated areas?', counterpoint: 'even controlled burns can create smoke and escape risk', personal: 'preparing a community for natural hazards' },
  { topic: '내진 건축', difficulty: 'C1', academic: 'a structural engineering program', subject: 'low-cost reinforcement for older buildings', finding: 'flexible wall connections reduced damage during simulated shaking', limitation: 'results depended on construction quality', service: 'a library renovation project', problem: 'an inspection found weak connections in an older reading room', action: 'reinforce the walls while keeping part of the building open', actor: 'the university construction office', debate: 'Should cities require immediate upgrades to older private buildings?', counterpoint: 'rapid mandates may displace residents and small businesses', personal: 'balancing safety with cost' },
  { topic: '대기질', difficulty: 'B2', academic: 'a public health department', subject: 'portable air sensors near schools', finding: 'pollution spikes closely followed heavy traffic periods', limitation: 'low-cost sensors required frequent calibration', service: 'a school arrival plan', problem: 'idling cars create high pollution near the main gate', action: 'move the pickup area and create a no-idling zone', actor: 'the school administration', debate: 'Should schools restrict private-car access near their entrances?', counterpoint: 'some families lack practical transportation alternatives', personal: 'improving air quality in a familiar place' },
  { topic: '수면 과학', difficulty: 'B2', academic: 'a cognitive science laboratory', subject: 'how irregular sleep affects attention', finding: 'consistent sleep timing predicted steadier performance than weekend recovery sleep', limitation: 'participants reported some sleep data themselves', service: 'an examination-week wellness program', problem: 'students extend library hours but sleep less before exams', action: 'offer earlier study sessions and a sleep-planning workshop', actor: 'the student support center', debate: 'Should universities reduce late-night academic activities?', counterpoint: 'some students can study only after work or family duties', personal: 'a habit that affects concentration' },
  { topic: '항생제 내성', difficulty: 'C1', academic: 'a microbiology clinic network', subject: 'delayed antibiotic prescriptions', finding: 'many mild infections improved without immediate antibiotics', limitation: 'clinicians still needed to identify high-risk patients quickly', service: 'a campus medical consultation', problem: 'patients expect antibiotics for illnesses that may be viral', action: 'explain warning signs and schedule a follow-up check', actor: 'the health center', debate: 'Should access to common antibiotics be more tightly controlled?', counterpoint: 'delays can be dangerous when bacterial infections are severe', personal: 'communicating uncertain medical advice clearly' },
  { topic: '영양 정보', difficulty: 'B2', academic: 'a behavioral economics study', subject: 'simplified labels on cafeteria menus', finding: 'clear symbols improved comparison between meals', limitation: 'a single symbol could not represent every nutritional need', service: 'a dining-hall menu redesign', problem: 'students find the current nutrition chart difficult to compare', action: 'add simple front-of-menu labels with links to full details', actor: 'the dining service', debate: 'Should restaurants be required to display detailed nutrition information?', counterpoint: 'too much information can overwhelm customers', personal: 'information that influences food choices' },
  { topic: '정신건강 접근성', difficulty: 'B2', academic: 'a university health survey', subject: 'barriers to counseling services', finding: 'short waiting times and private booking increased first visits', limitation: 'some students still feared social judgment', service: 'a counseling-center expansion', problem: 'appointments fill before many students can request help', action: 'add evening sessions and a confidential online intake', actor: 'the counseling center', debate: 'Should mental-health support be integrated into ordinary academic advising?', counterpoint: 'students may prefer strict separation for privacy', personal: 'reducing barriers to asking for help' },
  { topic: '고령사회', difficulty: 'C1', academic: 'a social policy institute', subject: 'age-friendly neighborhood design', finding: 'nearby services and safe crossings supported independent living', limitation: 'physical design could not replace social support', service: 'a community center access review', problem: 'older residents have difficulty reaching activities by bus', action: 'coordinate a flexible shuttle and volunteer escort program', actor: 'the municipal community office', debate: 'Should public budgets prioritize home support or specialized residential care?', counterpoint: 'residential centers can provide intensive services efficiently', personal: 'designing services for different generations' },
  { topic: '유아 학습', difficulty: 'B2', academic: 'an early education research group', subject: 'guided play and vocabulary growth', finding: 'children learned more words when adults asked open questions during play', limitation: 'overly direct instruction reduced exploration', service: 'a public library family program', problem: 'parents want activities that support language without becoming formal lessons', action: 'train volunteers to guide play with questions and stories', actor: 'the children’s library', debate: 'Should early education emphasize structured instruction or guided play?', counterpoint: 'structured lessons can make learning goals easier to monitor', personal: 'an activity that helped you learn as a child' },
  { topic: '원격근무', difficulty: 'B2', academic: 'an organizational psychology study', subject: 'hybrid work schedules and collaboration', finding: 'teams coordinated best when shared office days were planned together', limitation: 'individual flexibility decreased on common attendance days', service: 'a research-office scheduling change', problem: 'team members visit on different days and miss important discussions', action: 'designate two shared collaboration days each month', actor: 'the project manager', debate: 'Should employees choose all remote-work days individually?', counterpoint: 'complete flexibility can weaken spontaneous teamwork', personal: 'working or studying effectively from home' },
  { topic: '직장 자동화', difficulty: 'C1', academic: 'a labor economics center', subject: 'automation in routine administrative work', finding: 'software reduced repetitive tasks but increased demand for judgment and communication', limitation: 'benefits depended on retraining existing staff', service: 'an office software introduction', problem: 'employees worry that a new system will change their roles without preparation', action: 'run paid training and gather workflow feedback before launch', actor: 'the human resources team', debate: 'Should employers automate tasks even when job roles will change substantially?', counterpoint: 'delaying useful technology can reduce competitiveness', personal: 'a task technology changed for better or worse' },
  { topic: '창업과 지역경제', difficulty: 'B2', academic: 'a regional development project', subject: 'shared workspaces for new businesses', finding: 'mentoring and supplier networks mattered more than inexpensive desks alone', limitation: 'the program attracted firms already likely to succeed', service: 'a university startup center', problem: 'student founders have workspace but little access to experienced advice', action: 'pair teams with local mentors and monthly supplier clinics', actor: 'the entrepreneurship center', debate: 'Should public funds support new businesses with grants or shared services?', counterpoint: 'direct grants let founders choose their own priorities', personal: 'skills needed to turn an idea into a project' },
  { topic: '소비자 개인정보', difficulty: 'C1', academic: 'a digital policy laboratory', subject: 'how people respond to privacy notices', finding: 'short layered explanations improved understanding of data use', limitation: 'users still accepted terms when services offered no alternative', service: 'a campus application update', problem: 'the app requests location data without explaining when it is stored', action: 'add a plain-language permission screen and an opt-out mode', actor: 'the software team', debate: 'Should companies be allowed to exchange free services for personal data?', counterpoint: 'data-supported services may remain affordable to more users', personal: 'deciding whether an application deserves access to data' },
  { topic: '사이버보안 습관', difficulty: 'B2', academic: 'a human-computer interaction lab', subject: 'phishing warnings in workplace email', finding: 'specific warnings about the suspicious feature outperformed generic alerts', limitation: 'frequent warnings caused users to ignore them', service: 'a university account-security campaign', problem: 'several users approved unexpected login requests', action: 'teach users to verify the requesting device before approval', actor: 'the information security office', debate: 'Should organizations block risky actions or let informed users decide?', counterpoint: 'strict blocks can interrupt legitimate urgent work', personal: 'a security habit that is easy to maintain' },
  { topic: '허위정보', difficulty: 'C1', academic: 'a communication research institute', subject: 'corrections shared on social media', finding: 'corrections worked better when they explained the misleading technique', limitation: 'repeating a false claim sometimes made it more familiar', service: 'a student election information page', problem: 'an inaccurate voting deadline is spreading online', action: 'publish the correct date with evidence and contact group leaders', actor: 'the student election committee', debate: 'Should platforms remove misleading posts or attach contextual corrections?', counterpoint: 'removal decisions can be disputed and reduce transparency', personal: 'checking a surprising claim before sharing it' },
  { topic: '디지털 접근성', difficulty: 'B2', academic: 'an inclusive design study', subject: 'captions and transcripts in online courses', finding: 'multiple text formats supported both disabled learners and students studying in noisy places', limitation: 'automatic captions often misrepresented technical terms', service: 'a lecture-video platform update', problem: 'recordings have captions but no way to correct specialized vocabulary', action: 'let instructors review captions and publish searchable transcripts', actor: 'the learning technology unit', debate: 'Should accessibility checks be mandatory before digital materials are published?', counterpoint: 'small organizations may need additional time and support', personal: 'a design feature that makes information easier to use' },
  { topic: '오픈 사이언스', difficulty: 'C1', academic: 'a research methods consortium', subject: 'sharing data and analysis code', finding: 'transparent materials helped other teams detect errors and reuse methods', limitation: 'privacy and consent restricted some forms of sharing', service: 'a laboratory data-policy revision', problem: 'research files use inconsistent names and cannot be reproduced easily', action: 'adopt a shared structure and document every processing step', actor: 'the laboratory director', debate: 'Should publicly funded research data always be openly available?', counterpoint: 'sensitive data can expose participants or communities', personal: 'what makes evidence trustworthy' },
  { topic: '시민과학', difficulty: 'B2', academic: 'an ecology monitoring network', subject: 'bird observations submitted by volunteers', finding: 'large volunteer datasets revealed migration changes across wide areas', limitation: 'observation effort differed greatly between locations', service: 'a weekend biodiversity survey', problem: 'new volunteers record species using inconsistent methods', action: 'provide a short calibration exercise before fieldwork', actor: 'the survey coordinators', debate: 'Can volunteer data be as valuable as data collected only by professionals?', counterpoint: 'professionals use more consistent training and equipment', personal: 'a research project the public could help conduct' },
  { topic: '생태 연결로', difficulty: 'C1', academic: 'a landscape ecology program', subject: 'wildlife movement between fragmented habitats', finding: 'vegetated crossings increased movement for several small mammals', limitation: 'nearby artificial light discouraged nocturnal species', service: 'a highway crossing proposal', problem: 'a new road will separate two forest areas', action: 'build a planted crossing and reduce lighting near it', actor: 'the transport agency', debate: 'Should infrastructure budgets include wildlife crossings by default?', counterpoint: 'some locations may offer little ecological benefit for the cost', personal: 'connecting development with habitat protection' },
  { topic: '수분매개자 감소', difficulty: 'B2', academic: 'an agricultural biology station', subject: 'flower strips beside crop fields', finding: 'diverse flowers supported pollinators across a longer season', limitation: 'benefits fell when pesticides were applied nearby', service: 'a campus garden redesign', problem: 'the garden blooms briefly and offers little food later in the year', action: 'plant native species with staggered flowering periods', actor: 'the grounds department', debate: 'Should farms reserve productive land for pollinator habitat?', counterpoint: 'farmers may lose short-term crop area and income', personal: 'making an ordinary outdoor space more useful for wildlife' },
  { topic: '토양 복원', difficulty: 'C1', academic: 'a soil science field trial', subject: 'cover crops after intensive farming', finding: 'living roots reduced erosion and improved soil structure', limitation: 'water use increased during unusually dry seasons', service: 'a community garden recovery plan', problem: 'bare soil washes from the site during heavy rain', action: 'plant seasonal cover crops and monitor soil moisture', actor: 'the garden committee', debate: 'Should land managers prioritize rapid production or long-term soil recovery?', counterpoint: 'communities may need immediate food or income from the land', personal: 'restoring a damaged natural resource' },
  { topic: '산림 탄소', difficulty: 'C1', academic: 'a forest carbon observatory', subject: 'carbon storage in mixed-age forests', finding: 'older trees stored large stocks while younger growth absorbed carbon quickly', limitation: 'fire and drought could reverse gains', service: 'a municipal tree-management plan', problem: 'many street trees are the same age and vulnerable to one disease', action: 'replace them gradually with diverse species and ages', actor: 'the urban forestry office', debate: 'Should carbon goals favor planting new forests or protecting mature ones?', counterpoint: 'new forests can be placed where communities need green space', personal: 'judging the long-term value of trees' },
  { topic: '어업 관리', difficulty: 'C1', academic: 'a marine resource institute', subject: 'seasonal fishing closures', finding: 'closures during breeding periods improved juvenile survival', limitation: 'short-term income losses affected small fishing communities', service: 'a harbor management meeting', problem: 'fishers report smaller catches while scientists observe declining breeding stock', action: 'test a seasonal closure with temporary income support', actor: 'the coastal authority', debate: 'Should fishing limits change automatically when scientific indicators decline?', counterpoint: 'rapid rule changes make business planning difficult', personal: 'balancing livelihoods with conservation' },
  { topic: '담수 습지', difficulty: 'B2', academic: 'a watershed research center', subject: 'restored wetlands near farms', finding: 'wetlands trapped nutrients before they reached the lake', limitation: 'they occupied land previously used for crops', service: 'a river-park restoration project', problem: 'storm water carries sediment into a popular pond', action: 'create a shallow wetland and a raised walking path', actor: 'the parks department', debate: 'Should cities restore natural wetlands instead of building concrete drainage channels?', counterpoint: 'engineered channels can move floodwater quickly in dense areas', personal: 'protecting water quality near a community' },
  { topic: '극한기상 경보', difficulty: 'B2', academic: 'a risk communication team', subject: 'heat warnings sent to mobile phones', finding: 'messages prompted more action when they named nearby services', limitation: 'people without smartphones received less information', service: 'a city heat-response review', problem: 'residents know a heat wave is coming but not where to find cooling centers', action: 'send location-based alerts and post printed notices at transit stops', actor: 'the emergency management office', debate: 'Should emergency alerts be personalized by location and vulnerability?', counterpoint: 'personalization requires data that residents may not wish to share', personal: 'making an urgent warning clear and useful' },
  { topic: '순환 패션', difficulty: 'B2', academic: 'a textile sustainability project', subject: 'clothing repair and resale programs', finding: 'convenient repair services extended garment use more than awareness campaigns alone', limitation: 'very low-quality fabric remained difficult to repair', service: 'a campus clothing exchange', problem: 'donated clothes arrive faster than volunteers can sort them', action: 'schedule item categories on different days and add a repair desk', actor: 'the sustainability club', debate: 'Should clothing brands be responsible for collecting used products?', counterpoint: 'collection costs may increase prices for all customers', personal: 'why people replace usable clothing' },
  { topic: '전자폐기물', difficulty: 'C1', academic: 'a materials recovery laboratory', subject: 'recovering metals from discarded electronics', finding: 'careful disassembly produced purer materials than shredding mixed devices', limitation: 'manual work increased processing cost', service: 'a university electronics collection', problem: 'devices are donated without chargers or information about stored data', action: 'add a secure data-erasure station and clearer intake categories', actor: 'the recycling office', debate: 'Should manufacturers design electronics that users can easily repair and disassemble?', counterpoint: 'modular construction can make devices larger or more expensive', personal: 'deciding whether to repair or replace electronics' },
  { topic: '친환경 건설', difficulty: 'C1', academic: 'a building performance institute', subject: 'reusing structural materials from demolished buildings', finding: 'documented components retained substantial value and reduced new material demand', limitation: 'unknown material histories made certification difficult', service: 'a campus renovation tender', problem: 'the project plans to discard reusable doors and fixtures', action: 'inventory components before demolition and invite reuse proposals', actor: 'the procurement office', debate: 'Should construction rules require reuse assessments before demolition?', counterpoint: 'assessments may delay urgent projects', personal: 'what makes a building environmentally responsible' },
  { topic: '대중교통 운영', difficulty: 'B2', academic: 'a transportation planning unit', subject: 'real-time arrival information', finding: 'accurate updates reduced perceived waiting more than decorative station improvements', limitation: 'prediction errors quickly damaged trust', service: 'a bus application review', problem: 'the app shows scheduled rather than actual arrival times', action: 'connect live vehicle data and label uncertain predictions', actor: 'the transit agency', debate: 'Should transit budgets prioritize service frequency or passenger information?', counterpoint: 'good information cannot compensate for infrequent service', personal: 'what makes public transportation dependable' },
  { topic: '주거비 부담', difficulty: 'C1', academic: 'an urban economics institute', subject: 'mixed-income housing near employment centers', finding: 'shorter commutes offset part of the higher construction cost', limitation: 'limited supply still left many applicants without housing', service: 'a student housing allocation review', problem: 'rooms are assigned without considering commuting difficulty', action: 'include travel burden in the priority criteria', actor: 'the housing committee', debate: 'Should cities require new developments to include below-market homes?', counterpoint: 'requirements may reduce the total number of projects built', personal: 'factors that make housing affordable in practice' },
  { topic: '공공공간 설계', difficulty: 'B2', academic: 'an urban design studio', subject: 'seating patterns in public squares', finding: 'movable chairs supported both social groups and people seeking privacy', limitation: 'poor maintenance caused furniture to disappear', service: 'a campus courtyard redesign', problem: 'the courtyard has open space but few comfortable places to stay', action: 'test movable seating and shaded tables for one semester', actor: 'the campus planning team', debate: 'Should public spaces be carefully programmed or left open for unplanned use?', counterpoint: 'organized events can make spaces safer and more welcoming', personal: 'a public place where people choose to remain' },
  { topic: '관광 관리', difficulty: 'C1', academic: 'a destination management study', subject: 'visitor limits at fragile heritage sites', finding: 'timed entry reduced crowding without greatly reducing total visits', limitation: 'nearby businesses depended on spontaneous visitors', service: 'a local museum reservation change', problem: 'weekend crowds block galleries and create long lines', action: 'introduce timed tickets while reserving spaces for walk-in visitors', actor: 'the museum administration', debate: 'Should popular destinations limit visitor numbers to protect local life?', counterpoint: 'tourism income supports preservation and employment', personal: 'being a responsible visitor' },
  { topic: '이주민 통합', difficulty: 'C1', academic: 'a social inclusion research center', subject: 'language mentoring for newly arrived residents', finding: 'programs worked best when language practice was linked to practical local tasks', limitation: 'volunteer availability was inconsistent', service: 'a community welcome program', problem: 'new residents receive information but have few chances to ask follow-up questions', action: 'pair written guides with monthly multilingual help sessions', actor: 'the community services office', debate: 'Should integration programs emphasize a shared language or multilingual services?', counterpoint: 'multilingual support gives immediate access to essential services', personal: 'helping newcomers participate in a community' },
  { topic: '언어 보존', difficulty: 'C1', academic: 'a sociolinguistics archive', subject: 'community-led documentation of endangered languages', finding: 'recordings were used more when speakers controlled access and teaching materials', limitation: 'documentation alone did not create daily opportunities to speak', service: 'a cultural center language program', problem: 'young learners know songs but rarely use the language in conversation', action: 'create weekly activity groups led by fluent speakers', actor: 'the cultural association', debate: 'Should governments fund languages spoken by relatively small populations?', counterpoint: 'public resources must also support widely shared services', personal: 'the relationship between language and identity' },
  { topic: '문화 교류', difficulty: 'B2', academic: 'an international education office', subject: 'short cultural exchange projects', finding: 'shared problem-solving produced deeper contact than sightseeing alone', limitation: 'brief programs sometimes reinforced simple stereotypes', service: 'a visiting-student orientation', problem: 'participants attend events but interact mainly with people from their own group', action: 'organize mixed teams around a local service project', actor: 'the exchange coordinators', debate: 'Should study-abroad programs require community participation?', counterpoint: 'students may need freedom to pursue individual academic goals', personal: 'learning from someone with a different background' },
  { topic: '박물관 접근', difficulty: 'B2', academic: 'a museum education study', subject: 'multisensory exhibition interpretation', finding: 'audio, tactile models, and clear text served different visitors without reducing engagement', limitation: 'staff needed training to maintain and explain the materials', service: 'a gallery accessibility review', problem: 'a new exhibition relies on small printed labels', action: 'add audio descriptions, large text, and selected tactile replicas', actor: 'the exhibition team', debate: 'Should museums invest more in broad access or in acquiring new objects?', counterpoint: 'new collections can attract visitors and expand knowledge', personal: 'what makes a cultural place welcoming' },
  { topic: '예술 지원', difficulty: 'C1', academic: 'a cultural economics program', subject: 'small grants for local arts organizations', finding: 'multi-year support allowed groups to plan education programs and retain staff', limitation: 'fixed recipients left fewer opportunities for new groups', service: 'a university arts-fund review', problem: 'student groups receive one-time awards too late to plan events', action: 'offer earlier decisions and a mix of annual and multi-year grants', actor: 'the arts council', debate: 'Should public arts funding support excellence, participation, or both?', counterpoint: 'trying to satisfy every goal can weaken funding impact', personal: 'how art benefits a community' },
  { topic: '음악과 기억', difficulty: 'B2', academic: 'a neuroscience and care study', subject: 'familiar music in memory-support programs', finding: 'personally meaningful songs increased conversation and positive engagement', limitation: 'the same playlist did not suit every participant', service: 'a care-center activity plan', problem: 'group music sessions use selections unfamiliar to many residents', action: 'collect individual music histories and create varied playlists', actor: 'the activity coordinators', debate: 'Should care programs personalize activities even when group delivery is cheaper?', counterpoint: 'shared activities can build social connection', personal: 'a sound or song connected to a strong memory' },
  { topic: '고고학 기술', difficulty: 'C1', academic: 'an archaeological survey project', subject: 'drone mapping before excavation', finding: 'aerial models revealed subtle landscape patterns without disturbing the ground', limitation: 'vegetation concealed some features and required seasonal surveys', service: 'a field-school data review', problem: 'students store images without consistent location labels', action: 'adopt a shared naming system and verify coordinates daily', actor: 'the field director', debate: 'Should archaeologists excavate less when remote sensing can study a site?', counterpoint: 'physical evidence may answer questions images cannot', personal: 'using technology to study the past responsibly' },
  { topic: '역사 기록 보관', difficulty: 'C1', academic: 'a digital humanities center', subject: 'digitizing fragile community newspapers', finding: 'searchable copies expanded access and protected originals from handling', limitation: 'optical recognition performed poorly on damaged pages', service: 'a university archive request system', problem: 'researchers wait weeks for scans that may already exist', action: 'publish a searchable request index and digitization status', actor: 'the archive staff', debate: 'Should archives prioritize preserving originals or expanding digital access?', counterpoint: 'digital files also require costly long-term maintenance', personal: 'which records future generations will need' },
  { topic: '미디어 문해력', difficulty: 'B2', academic: 'an education evaluation team', subject: 'source-comparison lessons', finding: 'students judged claims better when they checked several sources before reading deeply', limitation: 'time pressure reduced careful comparison', service: 'a library news workshop', problem: 'participants focus on whether an article looks professional', action: 'teach quick checks of author, evidence, date, and independent coverage', actor: 'the library instructors', debate: 'Should media literacy be a required subject at university?', counterpoint: 'the skill could be integrated into existing courses', personal: 'recognizing when information needs verification' },
  { topic: '언론 신뢰', difficulty: 'C1', academic: 'a journalism research institute', subject: 'correction policies and audience trust', finding: 'visible explanations of errors improved trust more than silent edits', limitation: 'frequent corrections also signaled weak editorial processes', service: 'a student newspaper policy review', problem: 'online articles change without showing what was corrected', action: 'add dated correction notes and a contact route for evidence', actor: 'the editorial board', debate: 'Should news organizations reveal every correction, including minor ones?', counterpoint: 'too many notices may distract from substantive errors', personal: 'what makes a news source credible' },
  { topic: '스포츠 과학', difficulty: 'B2', academic: 'a human performance laboratory', subject: 'training load and injury prevention', finding: 'gradual increases were safer than sudden intense training blocks', limitation: 'individual recovery differed widely', service: 'a university running-club plan', problem: 'new members join the same difficult program as experienced runners', action: 'offer ability groups and weekly recovery checks', actor: 'the club coaches', debate: 'Should competitive teams personalize training even if group sessions become harder to organize?', counterpoint: 'shared training can strengthen motivation and team identity', personal: 'using feedback to improve physical performance' },
  { topic: '지역사회 운동', difficulty: 'B1', academic: 'a community health project', subject: 'free outdoor exercise classes', finding: 'attendance increased when sessions were close to transit and childcare', limitation: 'participation dropped during bad weather', service: 'a neighborhood activity program', problem: 'the current class time excludes workers and caregivers', action: 'test an evening class with nearby childcare', actor: 'the recreation center', debate: 'Should cities spend more on public exercise programs or medical services?', counterpoint: 'medical services address urgent needs that exercise cannot', personal: 'making exercise easier to continue' },
  { topic: '원격 의료', difficulty: 'C1', academic: 'a rural health network', subject: 'video consultations for follow-up care', finding: 'remote visits reduced travel while maintaining routine monitoring', limitation: 'physical examinations and poor internet still required in-person options', service: 'a campus clinic telehealth launch', problem: 'students are unsure which appointments can be handled online', action: 'publish clear eligibility examples and offer technical checks', actor: 'the clinic administration', debate: 'Should telehealth become the default for routine follow-up appointments?', counterpoint: 'some patients communicate better and feel safer in person', personal: 'when remote service is better than face-to-face service' },
  { topic: '재난 대비', difficulty: 'B2', academic: 'an emergency planning study', subject: 'practice drills and household readiness', finding: 'short repeated drills improved recall more than one annual presentation', limitation: 'participants sometimes treated familiar drills less seriously', service: 'a laboratory evacuation review', problem: 'new staff do not know the alternative exit route', action: 'run a brief route exercise at the start of each term', actor: 'the safety office', debate: 'Should emergency drills be frequent even when they interrupt work?', counterpoint: 'predictable drills may create routine rather than realistic attention', personal: 'preparing for an unlikely but serious event' },
  { topic: '대학 멘토링', difficulty: 'B2', academic: 'a student success program', subject: 'peer mentoring during the first semester', finding: 'regular mentor contact improved use of academic support services', limitation: 'poorly matched pairs often stopped meeting', service: 'a mentoring-program redesign', problem: 'students are paired only by major and may share few practical needs', action: 'match schedules and goals as well as academic interests', actor: 'the advising center', debate: 'Should mentors provide direct advice or mainly help students make their own decisions?', counterpoint: 'clear advice can be essential when systems are unfamiliar', personal: 'qualities of a helpful mentor' },
  { topic: '평생학습', difficulty: 'B2', academic: 'an adult education institute', subject: 'short courses for mid-career learners', finding: 'flexible schedules improved completion when courses still included peer contact', limitation: 'fully self-paced courses had high dropout rates', service: 'an evening certificate program', problem: 'working learners miss live sessions but need discussion practice', action: 'record lectures while keeping small scheduled discussion groups', actor: 'the continuing education office', debate: 'Should employers give paid time for workers to learn new skills?', counterpoint: 'small employers may struggle to cover absent staff', personal: 'learning a difficult skill after formal schooling' },
  { topic: '도서관 현대화', difficulty: 'B2', academic: 'a library use study', subject: 'changes from book storage to mixed learning spaces', finding: 'quiet zones remained essential even as demand for collaboration rooms grew', limitation: 'renovation reduced shelf access temporarily', service: 'a main-library floor redesign', problem: 'group discussion spreads into areas intended for silent study', action: 'separate acoustic zones and improve room reservation signs', actor: 'the library administration', debate: 'Should libraries devote more space to books or to collaborative activities?', counterpoint: 'digital access does not replace every print collection', personal: 'what a modern library should provide' },
  { topic: '직장 의사소통', difficulty: 'B2', academic: 'an applied linguistics workplace study', subject: 'written summaries after team meetings', finding: 'brief action summaries reduced disagreement about responsibilities', limitation: 'summaries failed when no one confirmed them', service: 'a project handoff process', problem: 'tasks discussed verbally are remembered differently by team members', action: 'send a short owner-and-deadline summary for confirmation', actor: 'the project coordinator', debate: 'Should important workplace decisions require written confirmation?', counterpoint: 'formal documentation can slow fast-moving collaboration', personal: 'preventing misunderstandings in a group task' },
  { topic: '생명공학 윤리', difficulty: 'C1', academic: 'a bioethics research center', subject: 'gene editing for inherited disease', finding: 'treatments affecting one patient raised fewer concerns than changes inherited by future generations', limitation: 'long-term effects remained uncertain in both cases', service: 'a public science forum', problem: 'advertising presents an experimental therapy as if it were proven', action: 'add an evidence review and a clear explanation of uncertainty', actor: 'the forum organizers', debate: 'Should heritable gene editing ever be permitted for medical purposes?', counterpoint: 'a carefully regulated method might prevent severe disease', personal: 'setting limits on powerful new technology' },
]

const base = (id: string, section: BaseItem['section'], kind: BaseItem['kind'], title: string, seed: Seed, context: string, seconds: number): BaseItem => ({
  id, section, module: 1, kind, title, instruction: '', topic: seed.topic, context, difficulty: seed.difficulty, timeSeconds: seconds,
})

const objective = (item: BaseItem, prompt: string, options: string[], answer: number, explanation: string): BaseItem => ({ ...item, prompt, options, answer, explanation })

export const EXPANSION_ITEMS: BaseItem[] = SEEDS.flatMap((seed, index) => {
  const id = `x-${index}`
  const etsMethodNotes = [
    'To avoid an arbitrary threshold, the team analyzed outcomes along a continuous scale.',
    'The team also examined its capacity to generalize the finding beyond the original sample.',
    'Several measurements fluctuated across observation periods, so the researchers reported the full range.',
    'The effect was relatively stable, although its magnitude differed among groups.',
  ]
  const academicPassages = [
    `In ${seed.academic}, researchers conducted a systematic assessment of ${seed.subject}. Preliminary evidence indicated that ${seed.finding}. However, ${seed.limitation}. ${etsMethodNotes[index % etsMethodNotes.length]} This constraint qualifies any broad interpretation of the result. The authors therefore proposed a subsequent evaluation to determine whether the observed outcome would persist across contexts.`,
    `A team at ${seed.academic} asked whether policy discussions about ${seed.subject} rested on dependable evidence. Their observations showed that ${seed.finding}. ${etsMethodNotes[index % etsMethodNotes.length]} The result was not uniform, however, because ${seed.limitation}. Rather than rejecting the pattern, the team identified the conditions that a later study would need to compare.`,
    `Debate about ${seed.subject} often treats one outcome as decisive. Evidence collected by ${seed.academic} complicates that view: ${seed.finding}. The researchers also noted that ${seed.limitation}. ${etsMethodNotes[index % etsMethodNotes.length]} Together, these points suggest a useful but conditional relationship instead of a universal rule.`,
    `${seed.academic} compared earlier explanations of ${seed.subject} with a new set of observations. The comparison supported the conclusion that ${seed.finding}. Yet the authors warned that ${seed.limitation}. ${etsMethodNotes[index % etsMethodNotes.length]} The study therefore narrows the circumstances under which the explanation is likely to apply.`,
  ]
  const academicPassage = academicPassages[index % academicPassages.length]
  const noticeFormats = [
    `Community notice — ${seed.service}: Because ${seed.problem}, ${seed.actor} will ${seed.action}. The six-week trial begins Monday. Send reports of unexpected effects to the service desk before the review meeting.`,
    `${seed.service} update: ${seed.actor} is responding to a recurring issue: ${seed.problem}. The office will ${seed.action} for one month, publish an interim update, and invite participants to identify access problems.`,
    `Service advisory for ${seed.service}. Staff have confirmed that ${seed.problem}. Beginning next week, ${seed.actor} will ${seed.action}. The arrangement remains temporary until usage records and participant comments are reviewed.`,
    `Important information about ${seed.service}: a recent review found that ${seed.problem}. As an initial response, ${seed.actor} plans to ${seed.action}. Anyone affected should document dates and practical consequences so the final plan reflects actual use.`,
  ]
  const notice = noticeFormats[index % noticeFormats.length]
  const conversationFormats = [
    `Student: I am having trouble with ${seed.service} because ${seed.problem}. Staff member: Thanks for explaining that. ${seed.actor} plans to ${seed.action}. Student: How will you know whether that works? Staff member: We will compare usage records and comments before choosing the next step.`,
    `Student: Could you clarify the update about ${seed.service}? ${seed.problem}. Staff member: That is why ${seed.actor} will ${seed.action}. Student: Is there an alternative during the change? Staff member: Yes. I will send the temporary-access instructions today.`,
    `Student: I wanted to report a problem with ${seed.service}: ${seed.problem}. Staff member: Your report matches several others. We are asking ${seed.actor} to ${seed.action}. Student: Should I submit evidence? Staff member: Please include the date and the effect on your work.`,
    `Student: The current arrangement for ${seed.service} is confusing because ${seed.problem}. Staff member: Let us check your situation first. ${seed.actor} can ${seed.action}. Student: When will I hear back? Staff member: The office will confirm the schedule by Friday.`,
  ]
  const conversation = conversationFormats[index % conversationFormats.length]
  const announcement = `Announcement concerning ${seed.service}: ${seed.actor} has received reports that ${seed.problem}. Starting next week, the office will ${seed.action}. Check the updated notice for access instructions, and submit any scheduling conflict before the review date.`
  const talkFormats = [
    `Today I will analyze ${seed.subject}. Recent evidence suggests that ${seed.finding}. This pattern is important, but ${seed.limitation}. The central lesson is that a plausible result still needs a clearly stated boundary.`,
    `Consider a common question about ${seed.subject}. Researchers reported that ${seed.finding}. One explanation connects the observations, although ${seed.limitation}. This example shows why mechanisms and limitations must be evaluated together.`,
    `Our topic is ${seed.subject}. The strongest evidence indicates that ${seed.finding}. Before applying that result broadly, remember that ${seed.limitation}. A responsible interpretation separates what the study observed from what it merely suggests.`,
    `Researchers disagree about how to interpret ${seed.subject}. A recent investigation found that ${seed.finding}; on the other hand, ${seed.limitation}. The contrast does not erase the finding, but it changes the strength of the conclusion.`,
  ]
  const talk = talkFormats[index % talkFormats.length]
  const readingContext = `${seed.academic} · 연구 결과와 한계`
  const serviceContext = `${seed.service} · 생활 안내와 조치`
  const listeningContext = `${seed.service} · 문제 해결 대화`
  const lectureContext = `${seed.academic} · 학술 강의`
  const sentencePattern = buildServiceSentencePattern(seed, index)
  const sentenceTiles = prepareSentenceTiles(sentencePattern.correct, `${id}-w0`)
  const vocabularyChecks = [
    { word: 'preliminary', answer: 'initial and not yet final', distractors: ['permanent and unchangeable', 'unrelated to the study', 'hidden from the public'], explanation: '“Preliminary” describes evidence that is initial and may be revised after further study.' },
    { word: 'qualifies', answer: 'limits or modifies', distractors: ['proves beyond doubt', 'repeats word for word', 'removes completely'], explanation: 'Here, “qualifies” means that the constraint limits how broadly the result can be interpreted.' },
    { word: 'subsequent', answer: 'occurring later', distractors: ['occurring at the same time', 'based only on opinion', 'smaller than expected'], explanation: '“Subsequent” refers to the evaluation that will take place later.' },
    { word: 'persist', answer: 'continue to exist', distractors: ['appear by accident', 'become less precise', 'end immediately'], explanation: 'The researchers want to know whether the outcome continues across contexts.' },
  ]
  const vocabularyCheck = vocabularyChecks[index % vocabularyChecks.length]
  const findingParaphrase = paraphraseForOption(seed.finding)
  const actionParaphrase = paraphraseForOption(seed.action)
  const discussion = buildDiscussionTask({ ...seed, finding: seed.finding, limitation: seed.limitation }, index)
  const repeatScenario = buildRepeatScenario(seed, index)
  const interviewScenario = buildInterviewScenario(seed, index)
  return [
    { ...objective(base(`${id}-r0`, 'reading', 'multiple-choice', 'Read an Academic Passage', seed, readingContext, 120), `Which statement best captures the conclusion about ${seed.subject}?`, [`The evidence can be summarized this way: ${findingParaphrase}.`, `The investigation found no meaningful pattern related to ${seed.subject}.`, `The limitation made every observation about ${seed.subject} invalid.`, `The outcome applied identically in all settings examined by ${seed.academic}.`], 0, 'The correct choice restates the finding while preserving its limited scope.'), passage: academicPassage, instruction: '연구 결과를 의미가 같은 다른 표현과 연결하세요.' },
    { ...objective(base(`${id}-r1`, 'reading', 'multiple-choice', 'Read an Academic Passage', seed, readingContext, 120), `In the discussion of ${seed.subject}, the word “${vocabularyCheck.word}” is closest in meaning to`, [`${vocabularyCheck.answer} when describing ${seed.subject}`, ...vocabularyCheck.distractors.map((choice) => `${choice} when describing ${seed.subject}`)], 0, vocabularyCheck.explanation), passage: academicPassage, instruction: '문맥을 이용해 학술 어휘의 의미를 추론하세요.' },
    { ...objective(base(`${id}-r2`, 'reading', 'multiple-choice', 'Read in Daily Life', seed, serviceContext, 75), `Which action will ${seed.actor} take in the notice about ${seed.service}?`, [`The correct response is a limited operational adjustment: ${actionParaphrase}.`, `${seed.actor} will end ${seed.service} without offering another form of access.`, `Participants must solve the problem with ${seed.service} without institutional help.`, `The proposed response to ${seed.problem} was canceled before it began.`], 0, 'The correct choice paraphrases the action announced in the notice.'), passage: notice, instruction: '안내문에 제시된 실제 조치를 패러프레이즈와 연결하세요.' },
    { ...objective(base(`${id}-r3`, 'reading', 'multiple-choice', 'Read in Daily Life', seed, serviceContext, 75), `Why does the notice about ${seed.service} request records or comments?`, [`To help ${seed.actor} judge whether the arrangement needs revision`, `To advertise a different service unrelated to ${seed.problem}`, `To prevent evidence about ${seed.service} from being collected`, `To guarantee that ${seed.action} becomes permanent immediately`], 0, 'Reports provide evidence for reviewing and revising the temporary response.'), passage: notice, instruction: '안내문의 목적과 후속 절차를 연결해 파악하세요.' },
    { ...objective(base(`${id}-l0`, 'listening', 'listen-choice', 'Listen to a Conversation', seed, listeningContext, 70), `What issue with ${seed.service} is the student trying to resolve?`, [`The student is affected because ${seed.problem}.`, `The student wants a textbook unrelated to ${seed.service}.`, `The student intends to cancel every future activity involving ${seed.subject}.`, `The student is comparing photographs instead of requesting help with ${seed.service}.`], 0, `The student explains that ${seed.problem}.`), audioText: conversation, instruction: '대화에서 제기된 문제를 파악하세요.' },
    { ...objective(base(`${id}-l1`, 'listening', 'listen-choice', 'Listen to an Announcement', seed, `${seed.service} · 공지`, 55), `What should people affected by the ${seed.service} change do before the review date?`, [`They should check the ${seed.service} instructions and report a scheduling conflict.`, `They should assume that ${seed.service} has ended permanently.`, `They should contact an office unrelated to ${seed.actor}.`, `They should wait until the ${seed.service} review is over before reading the update.`], 0, 'The announcement asks listeners to check the update and report conflicts.'), audioText: announcement, instruction: '공지의 변경 사항과 청자가 해야 할 행동을 파악하세요.' },
    { ...objective(base(`${id}-l2`, 'listening', 'listen-choice', 'Listen to an Academic Talk', seed, lectureContext, 80), `What is the lecturer’s main point about ${seed.subject}?`, [`The reported finding about ${seed.subject} is useful only when its stated limitation is considered.`, `The subject of ${seed.subject} has no practical or academic value.`, `One limitation proves that no observation about ${seed.subject} can be trusted.`, `Personal experience should replace systematic evidence about ${seed.subject}.`], 0, 'The talk connects the reported result with a boundary on its interpretation.'), audioText: talk, instruction: '강의의 중심 주장과 논리 구조를 파악하세요.' },
    { ...objective(base(`${id}-l3`, 'listening', 'listen-choice', 'Listen to an Academic Talk', seed, lectureContext, 80), `Which caution limits the conclusion about ${seed.subject}?`, [seed.limitation, `No investigation of ${seed.subject} has ever been conducted.`, `The example concerns a historical period unrelated to ${seed.subject}.`, `Every community faces identical conditions when dealing with ${seed.subject}.`], 0, `The lecturer explicitly cautions that ${seed.limitation}.`), audioText: talk, instruction: '강의에서 강조한 한계를 찾으세요.' },
    { ...base(`${id}-w0`, 'writing', 'sentence-build', 'Build a Sentence', seed, `${seed.service} · ${sentencePattern.grammarFocus}`, 75), prompt: sentencePattern.prompt, starter: sentencePattern.starter, words: sentenceTiles.choices, answer: sentenceTiles.answer, explanation: `${sentencePattern.starter} ${sentenceTiles.correct.join(' ')}`, grammarFocus: sentencePattern.grammarFocus, instruction: '문맥에 맞는 문장이 되도록 모든 단어와 짧은 구를 배열하세요.' },
    { ...base(`${id}-w1`, 'writing', 'email', 'Write an Email', seed, `${seed.service} · 공식 요청`, 420), prompt: buildEmailPrompt(seed, index), instruction: '상황, 영향, 요청을 갖춘 이메일을 작성하세요.' },
    { ...base(`${id}-w2`, 'writing', 'discussion', 'Write for an Academic Discussion', seed, `${seed.topic} · 정책 토론`, 600), prompt: discussion.prompt, passage: discussion.passage, instruction: '두 관점을 종합하고 자신의 입장을 구체적인 근거와 함께 전개하세요.' },
    ...repeatScenario.map((audioText, sequenceIndex) => ({ ...base(`${id}-s-r${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', seed, `${seed.service} · 단계별 안내`, sequenceIndex < 2 ? 12 : 16), audioText, instruction: '같은 안내 상황에서 길이와 구조가 달라지는 문장을 한 번 듣고 반복하세요.', scenarioId: `${id}-repeat`, stimulusGroupId: `${id}-repeat`, sequenceIndex })),
    ...interviewScenario.map((audioText, sequenceIndex) => ({ ...base(`${id}-s-i${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', seed, `${seed.topic} · 연결형 인터뷰`, 45), audioText, instruction: '같은 주제의 인터뷰 질문에 구체적인 이유와 사례를 들어 답하세요.', scenarioId: `${id}-interview`, stimulusGroupId: `${id}-interview`, sequenceIndex })),
  ]
})

export const EXPANSION_TOPIC_COUNT = SEEDS.length
