import type { FullAcademicPassage } from './fullAcademicReading'

export const C1_PASSAGES: FullAcademicPassage[] = [
  {
    topic: '교육 개입의 인과 해석',
    passage: `A university offered optional tutoring to first-year students and later reported that attendees earned higher examination scores. The difference was real, but it did not establish that tutoring caused the higher scores. Students who chose to attend might already have been more motivated, or they might have received other support.

Prior grades and course load were available for nearly everyone. After accounting for these measures, the score difference became smaller but did not disappear. That result still depended on a strong assumption: the recorded measures had captured the important reasons students selected tutoring. Motivation was only partly represented by a brief survey, and unrecorded support remained possible. An analyst proposed comparing students just above and below a scheduling cutoff that determined access to one tutoring session. This comparison could reduce selection differences near the cutoff, though it would speak chiefly about students in that narrow range.

The report separated its findings accordingly. It described the full-group association, then presented the cutoff analysis as a more focused estimate with a limited scope. The cutoff estimate was positive but imprecise. Rather than announcing that tutoring raised every student\'s score, the authors explained what each analysis could and could not support. Their caution was not a rejection of tutoring; it was a refusal to turn one observed pattern into a universal causal claim.`,
    questions: [
      ['Which statement best summarizes the passage?', 'Different analyses suggest a possible tutoring benefit but support claims of different scope.', ['The score gap proves a benefit for every first-year student.', 'A positive cutoff estimate makes the full-group comparison unnecessary.', 'The authors concluded that tutoring had no possible value.'], ['전체 연관성과 컷오프 추정은 근거 강도·적용 범위가 다르다.', '전 학생에게 인과 효과가 증명되지 않았다.', '전체집단 기술도 여전히 보고했다.', '효과 가능성을 부정하지 않았다.']],
      ['What happened after prior grades and course load were accounted for?', 'The score gap narrowed but remained.', ['The gap grew large enough to prove causation.', 'Tutoring enrollment became mandatory.', 'The cutoff was removed from the schedule.'], ['기존 차이가 줄었지만 사라지지 않았다.', '그것만으로 인과를 증명하지 못한다.', '참여 의무화는 없다.', '컷오프는 별도 분석에 쓰였다.']],
      ['Why might the cutoff analysis have limited generality?', 'It chiefly estimates an effect for students close to the access threshold.', ['It includes every student at the university equally.', 'It ignores whether any student attended tutoring.', 'It proves motivation was identical across all courses.'], ['경계 부근 학생의 비교라 전체집단으로 일반화가 제한된다.', '모든 학생을 동일하게 포함하지 않는다.', '참여 접근의 차이를 이용한다.', '동기 동일성을 입증하지 않는다.']],
      ['In the passage, “imprecise” most nearly means', 'Estimated with substantial uncertainty.', ['Known to be exactly zero.', 'Measured only after graduation.', 'Deliberately withheld from readers.'], ['추정치의 불확실성이 크다는 뜻이다.', '정확히 0이라는 뜻이 아니다.', '졸업 후 측정만을 뜻하지 않는다.', '비공개라는 뜻이 아니다.']],
      ['How is the final paragraph organized?', 'It distinguishes the claims warranted by two analyses and rejects overgeneralization.', ['It introduces the tutoring program for the first time.', 'It replaces the cutoff estimate with a new experiment.', 'It argues that every observational comparison is useless.'], ['두 분석의 해석 범위를 나누고 과도한 인과 일반화를 경계한다.', '프로그램은 앞에서 소개됐다.', '새 실험은 추가하지 않는다.', '관찰 연구 전체를 무용하다고 하지 않는다.']],
    ],
  },
  {
    topic: '유전자 조절 요소',
    passage: `Two cell types in an organism contain the same DNA sequence but produce different proteins. A research team studied a short region of DNA that appeared to help activate a nearby gene in one cell type. When the team removed the region in laboratory cells, production of the gene\'s RNA declined. This supported a regulatory role, but it did not show exactly which protein had bound to the region.

The researchers next altered several small stretches within the region. One alteration reduced RNA production only in the first cell type; another had little measurable effect in either type. The result suggested that specific sequence features mattered and that the region\'s effect depended on cellular context. The team also measured RNA from neighboring genes, since removing DNA can influence more than the intended target. No large change appeared in those neighbors under the tested conditions, but small effects could have escaped detection.

The researchers resisted calling the region an on-off switch. Its removal reduced expression rather than abolishing it, and laboratory cells did not represent every tissue or developmental stage. They proposed measuring binding proteins and testing the region in additional cell types. The study narrowed the explanation for one expression difference while leaving open the precise molecular route by which the DNA region acted.`,
    questions: [
      ['What is the passage\'s central conclusion?', 'A DNA region contributes to cell-dependent gene expression, but its precise mechanism remains unresolved.', ['The region is the only cause of all protein differences.', 'The same sequence forces identical RNA production in every cell.', 'Removing the region identified the binding protein directly.'], ['조절 기여는 지지되지만 작용 단백질과 경로는 미확정이다.', '모든 차이의 유일 원인으로 제시되지 않는다.', '세포별 발현은 달랐다.', '결합 단백질을 직접 확인하지 못했다.']],
      ['What did removal of the DNA region do in laboratory cells?', 'It lowered production of the nearby gene\'s RNA.', ['It eliminated the organism\'s entire DNA sequence.', 'It raised every neighboring gene equally.', 'It identified a specific protein bound to the region.'], ['인접 유전자의 RNA 생산이 감소했다.', '전체 DNA 제거가 아니다.', '이웃 유전자 큰 변화는 없었다.', '결합 단백질은 확인 전이다.']],
      ['Why did the team measure neighboring genes?', 'A deletion could affect genes beyond the intended target.', ['The target gene produced no RNA before any test.', 'Neighboring genes determine the cell\'s DNA sequence.', 'Measuring neighbors would reveal every binding protein.'], ['삭제가 의도 밖 유전자에도 영향을 줄 수 있어서다.', '표적 RNA는 원래 생산됐다.', 'DNA 염기서열 결정 목적이 아니다.', '결합 단백질 모두를 밝히지 못한다.']],
      ['In the passage, “abolishing” most nearly means', 'Ending completely.', ['Making slightly stronger.', 'Moving to a different cell.', 'Measuring repeatedly.'], ['발현을 완전히 없앤다는 뜻이다.', '약간 강화가 아니다.', '세포 이동이 아니다.', '반복 측정 뜻이 아니다.']],
      ['Why does the final paragraph reject the switch metaphor?', 'The region changes the amount of expression rather than simply turning it fully on or off.', ['RNA production was never measured.', 'The region had exactly the same effect in all tissues.', 'All neighboring genes were conclusively unaffected in every setting.'], ['감소는 있었지만 완전 차단이 아니어서 이분법적 비유가 과하다.', 'RNA를 측정했다.', '모든 조직에서 동일 효과는 아니다.', '모든 조건을 검사하지 않았다.']],
    ],
  },
  {
    topic: '호수 퇴적층과 과거 기후',
    passage: `A lake\'s bottom accumulates layers of sediment that may preserve clues about past rainfall. Researchers examining one core found that coarse particles became more common during several intervals. They first considered whether stronger storms had carried heavier material into the lake. That interpretation was plausible, but a road built near the shore might also have increased erosion without any change in regional rainfall.

To separate these possibilities, the team dated the layers and compared them with records from a smaller lake beyond the road\'s drainage area. A coarse interval appeared in both cores before road construction, supporting a broader environmental event. A later coarse interval appeared only in the first lake, near the time of construction. The correspondence was suggestive, not decisive: the lakes differed in size, and a local storm could have affected one basin without affecting the other. The researchers also inspected pollen and organic material, which responded to conditions differently from particle size.

The resulting climate history included uncertainty rather than one line labeled “rainfall.” The early interval was compatible with increased storm activity across the area; the later one could reflect local disturbance. By combining multiple indicators and a comparison lake, the team avoided treating every coarse layer as the same signal. The core remained valuable precisely because its interpretation could be tested against other evidence.`,
    questions: [
      ['What is the main methodological lesson of the passage?', 'A sediment clue to climate must be checked against local disturbance and other indicators.', ['Every coarse layer directly measures regional rainfall.', 'Road construction explains all layers, including those formed earlier.', 'Two lakes necessarily record identical local storms.'], ['입자 크기만 보지 않고 도로·비교호수·다른 지표를 함께 본다.', '굵은 층이 강우의 직접 계기는 아니다.', '도로 이전 층은 도로 탓이 아니다.', '두 호수가 모든 국지 폭풍을 공유하지 않는다.']],
      ['Which observation supported a broad event before the road was built?', 'Both lake cores contained a coarse interval from that earlier period.', ['Only the road-side lake had a later coarse interval.', 'The lakes had exactly the same size.', 'The road carried sediment into both basins before it existed.'], ['도로 전 시기의 굵은 층이 두 호수에 모두 있었다.', '후기 단일호수 층은 별도 문제다.', '호수 크기는 달랐다.', '도로 이전에는 도로 유입이 불가능하다.']],
      ['Why was the later coarse interval interpreted cautiously?', 'It might reflect road-related erosion or a local storm rather than regional rainfall.', ['It was absent from the first lake.', 'It had been dated before the earlier shared interval.', 'Pollen proved that particle size never changes.'], ['후기 층에는 국지 교란과 국지 폭풍이라는 대안이 있다.', '첫 호수에는 있었다.', '앞 시기 뒤에 형성됐다.', '꽃가루가 입자 변화를 부정하지 않는다.']],
      ['In the passage, “correspondence” most nearly means', 'A match or close relation in timing or pattern.', ['A letter sent between the two laboratories.', 'A measurement of lake depth.', 'The physical transfer of sediment between lakes.'], ['층의 시기·양상이 서로 맞는다는 뜻이다.', '편지를 뜻하지 않는다.', '수심 측정이 아니다.', '호수 간 퇴적물 이동이 아니다.']],
      ['What role does the comparison lake serve?', 'It helps distinguish a local shore change from a wider environmental pattern.', ['It guarantees that the first lake\'s core has no dating error.', 'It measures road traffic directly.', 'It replaces the need to examine pollen and organic material.'], ['도로 영향권 밖 기록으로 지역·광역 원인을 비교한다.', '연대 오류를 완전히 배제하지 않는다.', '교통량 직접 측정이 아니다.', '다른 지표도 계속 살폈다.']],
    ],
  },
  {
    topic: '네트워크 혼잡 제어',
    passage: `Computers share a link whose capacity changes as traffic arrives. Each sender estimates available capacity from acknowledgments and packet losses, then adjusts its sending rate. Because feedback arrives late, a sender may increase its rate just as the link becomes crowded. A loss can therefore signal congestion, but one loss does not reveal the link\'s exact capacity.

Engineers tested two rate-control schemes against identical traffic. Scheme A reduced its rate sharply after a loss and recovered slowly. Scheme B reduced less sharply but checked delay more often. In one test, B delivered more data, yet it also kept queues longer. The team refused to rank the schemes using delivery alone, since long queues delayed interactive messages. It measured both throughput and delay and repeated the tests with different mixes of long transfers and short requests.

Results changed with the traffic mix. A scheme that favored large transfers when the link was quiet did not necessarily serve short requests well during crowded periods. The engineers also noted that a test replay could not reproduce every behavior of a live network, where senders react to one another. They published conditions for each result rather than announcing a universally superior controller. The comparison illustrated a general difficulty: maximizing one performance measure can make another worse when capacity is shared and feedback is delayed.`,
    questions: [
      ['Which conclusion follows from comparing the two congestion schemes?', 'The preferred congestion scheme depends on traffic mix and the performance measure considered.', ['Higher throughput always means better service for short requests.', 'Delayed feedback makes packet loss unrelated to congestion.', 'The test established one controller as superior in every network.'], ['처리량·지연·트래픽 구성에 따라 평가가 달라진다.', '짧은 요청의 지연이 길어질 수 있다.', '손실은 혼잡 신호가 될 수 있다.', '보편 우위를 선언하지 않았다.']],
      ['How did Scheme A react after a loss?', 'It cut its rate strongly and increased it again slowly.', ['It held its rate steady until delay disappeared.', 'It raised its rate faster than Scheme B.', 'It stopped receiving acknowledgments permanently.'], ['A는 급격히 줄이고 천천히 회복했다.', '속도를 유지하지 않았다.', 'B보다 빠른 증가는 제시되지 않았다.', '응답 수신 영구 중단은 없다.']],
      ['Why did engineers measure delay as well as throughput?', 'More delivered data could still come with longer queues for interactive traffic.', ['A longer queue always increases link capacity.', 'Delay and throughput were defined as the same quantity.', 'The traffic mix contained no short requests.'], ['B의 처리량 이득이 짧은 요청 지연을 악화시킬 수 있다.', '대기열은 용량을 늘리지 않는다.', '두 지표는 다르다.', '짧은 요청도 시험했다.']],
      ['In the passage, “replay” most nearly means', 'A test that runs a previously recorded traffic pattern again.', ['A message sent only to one receiver.', 'A way of permanently increasing link capacity.', 'A written explanation of a packet loss.'], ['기록된 트래픽을 다시 실행하는 시험이다.', '단일 수신 메시지가 아니다.', '용량 확대 기술이 아니다.', '손실 서면 설명이 아니다.']],
      ['Why does the last paragraph mention live senders reacting to one another?', 'To limit how far the recorded-traffic test can be generalized.', ['To show that the test used no traffic records.', 'To claim a controller never changes its rate.', 'To prove that interactive messages are irrelevant.'], ['재생 시험이 실제 상호반응을 완전히 재현하지 못하는 한계다.', '기록된 트래픽을 사용했다.', '제어기는 속도를 조정한다.', '대화형 메시지도 중요하다.']],
    ],
  },
  {
    topic: '고고학 자료의 부재',
    passage: `Excavators found many stone tools at a campsite but no wooden handles. One interpretation was that the tools had been used without handles. Another was that wood had decayed while stone survived. To evaluate the alternatives, researchers examined tool edges for wear and looked for traces of binding material. A few tools had marks consistent with attachment, but those marks were not unique to handles.

The team then considered where the site had been excavated. Only a portion of the campsite lay inside the construction area where digging was permitted. Handles might have been stored in unexcavated spaces, and the soil in the opened area was acidic enough to damage organic material. At a nearby waterlogged site of similar age, wooden objects had survived, demonstrating how preservation conditions could change the record. That comparison did not prove wooden handles had existed at the first site; it showed why their absence there was weak evidence of nonuse.

The researchers framed their conclusion as a question of detection. They could describe where stone tools were found and which attachment traces appeared. They could not equate “not recovered” with “never present” without a credible account of preservation and sampling. Future work might find more traces, but the existing evidence already ruled out the simplest claim that the missing wood decisively demonstrated handle-free tools.`,
    questions: [
      ['What can be concluded from the missing wooden handles?', 'The absence of preserved wood cannot by itself establish that tools lacked handles.', ['The nearby site proves every tool had a handle.', 'Acidic soil preserves wood better than waterlogging.', 'Attachment marks uniquely identify one handle design.'], ['보존·발굴 범위를 고려하면 미발견을 미사용으로 단정할 수 없다.', '인근 유적은 가능성을 보여 줄 뿐이다.', '산성 토양은 유기물을 손상시켰다.', '흔적은 손잡이만의 고유 표지가 아니다.']],
      ['What limited excavation at the first campsite?', 'Digging was allowed only within a construction area.', ['Researchers had lost every stone tool.', 'The entire campsite was under water.', 'The nearby comparison site had already been destroyed.'], ['공사 허가 범위의 일부만 발굴했다.', '석기는 많이 발견됐다.', '첫 유적 전체가 수중은 아니다.', '비교 유적에서 목재가 남았다.']],
      ['Why is the waterlogged site relevant?', 'It shows that different preservation conditions can change which materials survive.', ['It identifies the exact handles missing from the first site.', 'It proves the first campsite was also waterlogged.', 'It shows that stone tools cannot survive in acidic soil.'], ['습한 환경에서 목재가 남아 보존 조건의 중요성을 보여 준다.', '같은 손잡이를 특정하지 않는다.', '첫 유적은 산성 토양이었다.', '첫 유적에서 석기가 남았다.']],
      ['In the passage, “decisively” most nearly means', 'In a way that settles the issue.', ['At an earlier date.', 'Without any excavation.', 'By using only wooden objects.'], ['논쟁을 확정할 만큼 결정적으로라는 뜻이다.', '이른 날짜 뜻이 아니다.', '발굴 없이란 뜻이 아니다.', '목재만 쓴다는 뜻이 아니다.']],
      ['What does the final paragraph add to the earlier evidence?', 'It states a general rule for interpreting material that was not recovered.', ['It changes the number of stone tools found.', 'It claims future discoveries are impossible.', 'It abandons preservation as a relevant factor.'], ['구체 사례에서 미발견 해석의 원칙으로 나아간다.', '석기 수를 바꾸지 않는다.', '향후 발견 가능성을 남긴다.', '보존을 핵심 요인으로 본다.']],
    ],
  },
  {
    topic: '차용어와 발음 변화',
    passage: `When a community borrows a word from another language, speakers may reshape its sounds to fit patterns they already use. Linguists studying one coastal community noticed that an imported word ended in a consonant cluster unusual in the local language. Older recordings showed two pronunciations: some speakers kept the cluster, while others inserted a short vowel between the consonants.

At first, the researchers expected younger speakers to use the vowel more often because the borrowed word had become familiar. Interviews produced the opposite pattern. Younger speakers who attended schools where the source language was taught often retained the cluster. Older speakers with little formal contact with that language more often inserted the vowel. Age was therefore associated with pronunciation, but schooling and contact offered a plausible explanation for the association. The team compared speakers with similar schooling before drawing any conclusion about generational change.

The word also occurred in formal announcements and casual conversations. Some speakers changed pronunciation across these settings. The researchers argued that borrowing was not a one-time adjustment completed when the word entered the language. Instead, pronunciation could be reshaped again as speakers encountered new models and audiences. They did not claim that one form was more authentic. Their account described how local sound patterns, exposure to the source language, and conversational setting jointly influenced use.`,
    questions: [
      ['What is the passage\'s main claim?', 'A borrowed word\'s pronunciation can vary with local patterns, language contact, and setting.', ['All borrowed words immediately acquire one permanent pronunciation.', 'Schooling made every younger speaker insert a vowel.', 'The researchers declared one pronunciation authentic and the other wrong.'], ['차용어 발음은 음운 패턴·접촉·상황의 영향을 받는다.', '고정된 단일 발음이 아니다.', '젊은 층은 오히려 자음군을 유지하는 경향이었다.', '어느 쪽을 정통이라 판정하지 않았다.']],
      ['What did some speakers insert into the consonant cluster?', 'An extra vowel sound between its consonants.', ['A new written letter at the start.', 'A second borrowed word.', 'A pause after the whole sentence.'], ['자음 사이에 짧은 모음을 넣었다.', '첫 글자 변경이 아니다.', '새 단어 추가가 아니다.', '문장 뒤 쉼이 아니다.']],
      ['Why did the team compare speakers with similar schooling?', 'To separate an age pattern from differences in exposure to the source language.', ['To prove all schools taught identical pronunciation.', 'To eliminate the local language from the study.', 'To show casual speech never changed pronunciation.'], ['나이와 원어 접촉·교육 효과를 구분하려는 것이다.', '학교의 동일 수업은 확인되지 않는다.', '지역 언어도 분석 대상이다.', '일상 대화에서도 변이가 있었다.']],
      ['In the passage, “retained” most nearly means', 'Kept rather than changing.', ['Recorded for the first time.', 'Used only in writing.', 'Explained to an interviewer.'], ['자음군을 바꾸지 않고 유지했다는 뜻이다.', '첫 기록의 의미가 아니다.', '글에서만 쓴 것이 아니다.', '설명 행위 자체가 아니다.']],
      ['Why does the passage move from age to schooling and then setting?', 'To show that a simple age association has several possible mechanisms and contexts.', ['To prove that age alone explains every pronunciation choice.', 'To replace speech evidence with spelling rules.', 'To argue that formal announcements were never recorded.'], ['처음 연령 차이를 교육·사용 상황으로 정밀화한다.', '나이 단독 설명을 경계한다.', '실제 발화 자료를 사용했다.', '격식 발화도 관찰했다.']],
    ],
  },
  {
    topic: '금속 부품의 반복 피로',
    passage: `A bridge component can fail after many small load cycles even when no single cycle approaches the force required to break it at once. Engineers call this process fatigue. A team inspected a metal joint that had developed a short crack near a bolt hole. The crack\'s location suggested that repeated bending had concentrated stress there, but corrosion might also have weakened the surface.

The team tested intact joints from the same production batch under controlled loading. Some were kept dry, while others were exposed to salt spray. Cracks appeared earlier in the exposed group, yet the spread of results within each group was substantial. The team also examined the failed bridge joint under a microscope. Features along its crack showed successive stages of growth, consistent with repeated loading rather than one sudden overload. The evidence supported a combined explanation: cyclic stress drove the crack, and surface corrosion may have accelerated it.

The engineers recommended both improved sealing and more frequent inspection of similar joints. They did not set a fixed replacement date from the laboratory average. Actual bridges experience different loads and maintenance histories, and a small sample cannot define the lifespan of every joint. Their recommendation linked a plausible mechanism to practical monitoring without presenting the test results as an exact countdown to failure.`,
    questions: [
      ['What conclusion is best supported?', 'Repeated loading drove crack growth, possibly accelerated by corrosion.', ['One unusually large load was the only possible cause.', 'Salt exposure guaranteed identical failure times.', 'The laboratory average fixed an exact replacement date.'], ['반복 응력이 주원인이고 부식이 촉진했을 수 있다.', '현미경 흔적은 단일 과하중보다 반복 성장을 지지한다.', '그룹 안 결과 분산이 컸다.', '평균으로 정확한 교체일을 정하지 않았다.']],
      ['What distinguished the salt-spray group?', 'Cracks generally appeared earlier than in the dry group.', ['Every joint failed on the same cycle.', 'No crack appeared under controlled loading.', 'Its joints came from a different production batch.'], ['염분 노출군에서 대체로 더 일찍 균열이 나타났다.', '모두 같은 시점은 아니었다.', '균열이 관찰됐다.', '동일 생산 배치의 부품이다.']],
      ['Why was an exact replacement date rejected?', 'Real load histories and the limited sample prevent a universal lifespan estimate.', ['The team found no evidence of repeated loading.', 'All bridges have the same maintenance conditions.', 'The microscope could not show any crack-growth stages.'], ['실제 하중·정비 차이와 소표본 때문에 일괄 수명은 불확실하다.', '반복 하중 흔적을 찾았다.', '교량 조건은 다르다.', '성장 단계 흔적이 있었다.']],
      ['In the passage, “substantial” most nearly means', 'Considerable in size or amount.', ['Exactly zero.', 'Hidden by a seal.', 'Occurring only once.'], ['그룹 내부 결과 차이가 상당히 크다는 뜻이다.', '0이라는 뜻이 아니다.', '밀봉 상태를 뜻하지 않는다.', '한 번 발생이 아니다.']],
      ['How does the last paragraph use the test results?', 'It converts mechanistic evidence into cautious maintenance advice.', ['It declares every joint already unsafe for use.', 'It withdraws the earlier role of corrosion.', 'It replaces inspection with a single calendar date.'], ['기전 근거를 밀봉·점검 권고로 연결하되 수명 단정은 피한다.', '모든 부품의 즉각 위험을 선언하지 않는다.', '부식 가능성을 유지한다.', '정기 점검을 제안한다.']],
    ],
  },
  {
    topic: '외계행성 통과 시각',
    passage: `When a planet crosses the face of its star, observers see a small dip in brightness. If the planet\'s orbit were perfectly regular and no other body disturbed it, the dips would recur at predictable times. Astronomers monitoring one star found that several transits arrived a few minutes early or late. They considered whether a second planet\'s gravity might explain the pattern.

The first measurements came from one telescope, whose clock had been adjusted halfway through the season. The team reprocessed the images using the recorded clock corrections and asked another observatory to measure later transits. The timing pattern persisted, making a simple clock error less likely. Still, different combinations of a second planet\'s mass and orbit could produce similar deviations over the short observing window. The team therefore reported a range of models rather than announcing a single companion.

They also distinguished timing from brightness. The depth of each dip helped estimate how much starlight the transiting planet blocked; its exact time addressed a different question about orbital motion. By combining repeated timings with future observations, the astronomers hoped to narrow the possible gravitational explanations. Their evidence supported a perturbation worth investigating, not a direct image of another planet or a final measurement of its mass.`,
    questions: [
      ['What is the central interpretation of the timing data?', 'Repeated departures from a strict schedule may indicate gravitational influence from another body.', ['The dips prove that the star stopped producing light.', 'One early transit uniquely measures a second planet\'s mass.', 'Timing deviations are the same thing as dip depth.'], ['반복되는 시각 편차가 추가 천체의 중력 작용 가능성을 시사한다.', '별빛 자체의 중단이 아니다.', '한 번으로 질량을 확정할 수 없다.', '깊이와 시각은 다른 측정이다.']],
      ['How did the team check a possible clock problem?', 'It reapplied recorded corrections and obtained later timings from another observatory.', ['It ignored all early-season images.', 'It assumed the first telescope\'s clock was perfect.', 'It changed the star\'s predicted brightness.'], ['시계 보정 기록을 반영하고 다른 관측소 자료와 비교했다.', '초기 영상을 무시하지 않았다.', '완전한 시계를 가정하지 않았다.', '밝기 변경은 시각 검증이 아니다.']],
      ['Why did the team publish a range of companion models?', 'Several masses and orbits could fit the short timing series.', ['The transit depth was impossible to measure.', 'The clock correction erased all timing differences.', 'A second planet had been directly photographed.'], ['짧은 관측기간에는 질량·궤도 조합이 여러 개 맞을 수 있다.', '깊이도 별도 관측했다.', '시각 차이는 남았다.', '직접 촬영한 것은 아니다.']],
      ['In the passage, “persisted” most nearly means', 'Continued to be observed after a check.', ['Moved closer to the telescope.', 'Became brighter with each event.', 'Was deliberately removed from the data.'], ['재처리와 추가 관측 뒤에도 패턴이 계속 나타났다는 뜻이다.', '거리 이동 뜻이 아니다.', '밝기 증가 뜻이 아니다.', '자료에서 제거되지 않았다.']],
      ['Why does the final paragraph separate timing from brightness?', 'To clarify that two features of a transit answer different questions.', ['To show that brightness dips have no relationship to transits.', 'To argue that only one transit is ever needed.', 'To claim that clock corrections determine a planet\'s size.'], ['통과 깊이와 시각은 각각 차광량·궤도 운동에 관련된다.', '밝기 감소도 통과 현상이다.', '반복 관측이 필요하다.', '시계 보정으로 크기를 알 수 없다.']],
    ],
  },
  {
    topic: '먹이그물과 포식자 복귀',
    passage: `After a large predator returned to a mountain valley, observers reported more young trees along a stream. A common story held that the predator had reduced browsing animals, allowing trees to recover. The story was possible, but the valley had also experienced several wet years and a change in livestock grazing. Researchers sought evidence that could distinguish these pathways.

They compared stream sections visited frequently by predators with sections where predators were rarely detected. Browsing marks declined more in the first group, and young trees survived more often there. Yet predator visits were not assigned at random: predators might have favored sections that already offered better cover or more prey. The team measured soil moisture, livestock use, and initial vegetation in each section. Adjusting for those variables narrowed the difference in tree survival without eliminating it. That result made a predator effect plausible, not certain.

The researchers avoided claiming a complete trophic cascade from one valley. They had evidence for several links—predator presence, browsing pressure, and tree survival—but limited evidence about how each link changed through time. They proposed repeated measurements and a comparison valley with a different grazing history. Their account treated the familiar story as a testable chain of causes rather than as a single event proved by the sight of new trees.`,
    questions: [
      ['How should the observed tree recovery be interpreted?', 'The proposed predator-to-tree chain is plausible but needs each causal link tested.', ['The new trees alone prove a complete trophic cascade.', 'Wet years and livestock changes were shown irrelevant.', 'Predators were assigned randomly to stream sections.'], ['포식자→초식 압력→나무 생존의 연쇄를 검증해야 한다.', '새 나무만으로 전체 연쇄는 증명되지 않는다.', '수분·가축도 고려한다.', '포식자 방문은 무작위가 아니다.']],
      ['What pattern differed across stream sections?', 'Browsing marks fell more where predators were often detected.', ['Young trees survived only where no predators visited.', 'Soil moisture was never measured.', 'Every section had identical livestock use.'], ['포식자 자주 탐지 구역에서 뜯어먹은 흔적 감소가 컸다.', '포식자 구역의 나무 생존이 높았다.', '토양 수분도 측정했다.', '가축 이용은 비교 변수였다.']],
      ['Why did adjustment narrow the survival difference?', 'Initial habitat and land-use differences explained part of the observed pattern.', ['The researchers had removed all young trees from the data.', 'Adjustment proved the predator had no possible effect.', 'Predator visits were made random after the fact.'], ['초기 식생·수분·가축 차이가 차이의 일부를 설명했다.', '나무 자료를 삭제한 것이 아니다.', '차이가 완전히 사라지지 않았다.', '사후에 무작위 배정할 수 없다.']],
      ['In the passage, “favored” most nearly means', 'Selected or preferred.', ['Caused to disappear.', 'Measured exactly.', 'Visited only after dark.'], ['포식자가 더 좋은 은신처 등의 장소를 선호했다는 뜻이다.', '소멸시켰다는 뜻이 아니다.', '정확 측정 뜻이 아니다.', '야간 방문만을 뜻하지 않는다.']],
      ['What is the purpose of proposing a comparison valley?', 'To test whether the same links hold under a different grazing history.', ['To show that the first valley had no browsing animals.', 'To replace measurements over time with one photograph.', 'To ensure that all valleys have identical soil moisture.'], ['방목 이력이 다른 곳에서도 인과 고리가 성립하는지 보려 한다.', '첫 계곡에도 초식동물이 있었다.', '반복 측정도 제안했다.', '토양 수분의 완전 동일을 요구하지 않는다.']],
    ],
  },
  {
    topic: '기록 보존과 선택 편향',
    passage: `A city archive found repeated workshop-noise complaints in nineteenth-century letters. A historian considered using the letters to estimate how common such complaints had been. The collection was large but not a random sample of opinion. People with time and writing materials were more likely to send letters, and archivists had retained some offices' files more fully than others.

The historian compared the letters with meeting minutes and a directory of workshops. Complaints clustered near several busy streets, yet some streets with many workshops had few surviving letters. That contrast could mean residents there were less concerned; it could also mean that their correspondence had not survived. The directory described businesses, not the feelings of nearby residents, so it could not resolve the question alone. The historian mapped where each source was produced and where gaps in preservation appeared.

The final essay used individual letters to illustrate how some residents described workshop noise. It did not convert the number of surviving letters into a percentage of all residents who objected. By naming whose voices were more likely to enter the archive, the historian made the evidence more useful rather than less. The collection could reveal language, conflicts, and specific events, provided readers did not mistake its surviving contents for an equal sample of every person who had lived there.`,
    questions: [
      ['What is the passage\'s central warning?', 'Surviving letters cannot be treated as an equal sample of all neighborhood opinions.', ['A large archive contains no useful historical information.', 'Meeting minutes automatically represent every resident.', 'Workshop directories directly measure residents\' feelings.'], ['작성·보존 과정의 편향 때문에 전체 여론 비율로 환산할 수 없다.', '구체 경험 자료로는 유용하다.', '회의록도 전 주민 대표는 아니다.', '사업체 명부는 감정을 기록하지 않는다.']],
      ['What did the workshop directory record?', 'The presence and location of businesses.', ['Every resident\'s opinion of noise.', 'Which letters had been destroyed by archivists.', 'The final percentage of objecting residents.'], ['명부는 사업체 정보를 담는다.', '주민 감정은 담지 않는다.', '편지 소실 목록이 아니다.', '반대 비율을 제공하지 않는다.']],
      ['What could explain a workshop-heavy street with few letters?', 'Correspondence from that street may have survived poorly.', ['No workshops had ever existed there.', 'The historian had proven every resident approved of noise.', 'The meeting minutes were written centuries later.'], ['불만이 적었을 수도 있지만 편지 보존 부족도 대안이다.', '명부에는 작업장이 많았다.', '모두 찬성한 것은 입증되지 않았다.', '회의록의 집필 시기 주장은 없다.']],
      ['In the passage, “clustered” most nearly means', 'Appeared in concentrated groups.', ['Were translated into another language.', 'Were hidden inside one letter.', 'Were distributed evenly everywhere.'], ['불만 편지가 일부 거리 주변에 몰렸다는 뜻이다.', '번역이 아니다.', '한 편지 안에 숨은 것이 아니다.', '균등 분포의 반대다.']],
      ['Why does the final paragraph contrast illustration with percentage?', 'To separate what individual letters can show from a population claim they cannot support.', ['To argue that maps are more accurate than all written sources.', 'To show that the archive held no specific events.', 'To claim that writing materials were equally available to everyone.'], ['구체 사례 서술은 가능하지만 전체 주민 비율 추정은 어렵다.', '지도 우월성 일반론이 아니다.', '구체 사건을 알 수 있다.', '작성 기회는 균등하지 않았다.']],
    ],
  },
]
