import type { FullAcademicPassage } from './fullAcademicReading'

export const B2_PASSAGES: FullAcademicPassage[] = [
  {
    topic: '도시 지붕과 표면 온도',
    passage: `On hot days, a dark roof can become much warmer than the air above it. A city tested a pale roof coating on six public buildings, expecting that the coating would reflect more sunlight. Maintenance staff measured roof-surface temperature before and after treatment. On clear afternoons, the treated roofs were cooler than they had been under similar weather conditions the previous year.

The city also wanted to know whether occupants used less air conditioning. This was harder to establish. Two buildings gained new insulation during the study, and one changed its opening hours. Energy records reflected these changes as well as the roof coating. Researchers compared buildings without such alterations, but they still treated the energy estimate as provisional. Surface cooling was directly observed; a reduction in electricity use required a more careful comparison.

The coating needed inspection after winter because dirt could reduce its ability to reflect light. Officials therefore calculated maintenance cost alongside potential energy savings. They did not assume that every pale roof would perform alike: roof angle, nearby shade, and local weather differed. The study supported using the coating where strong sunlight reached the roof, while leaving its long-term financial benefit open to further measurement.`,
    questions: [
      ['What distinction is central to the passage?', 'A cooler roof was observed, but lower energy use was harder to attribute to the coating.', ['The coating made every building use more electricity.', 'The city measured energy use but never roof temperature.', 'Roof angle was proven irrelevant to coating performance.'], ['표면 냉각은 관측됐지만 전력 절감의 원인 판단은 어렵다.', '모든 건물 전력 증가가 아니다.', '지붕 온도를 측정했다.', '지붕 각도도 변수라고 했다.']],
      ['Which changes complicated the electricity comparison?', 'New insulation in two buildings and changed hours in another.', ['A complete loss of roof-temperature records.', 'The removal of all untreated buildings.', 'A ban on air conditioning during the experiment.'], ['단열 보강과 운영시간 변경이 에너지 기록에 영향을 줬다.', '온도 기록은 있었다.', '비처리 건물을 모두 제거했다는 내용은 없다.', '냉방 금지는 없다.']],
      ['What can be inferred about buildings with little direct sunlight?', 'The coating may provide less benefit there than on exposed roofs.', ['They must be warmer than all dark-roofed buildings.', 'They need no winter inspection.', 'Their energy use can be predicted from roof color alone.'], ['반사 효과를 얻을 햇빛이 적어 이점이 작을 수 있다.', '절대적 온도 비교는 할 수 없다.', '점검 면제 근거는 없다.', '색만으로 전력 사용을 예측할 수 없다.']],
      ['In the passage, “provisional” most nearly means', 'Not yet firmly established.', ['Measured without any instruments.', 'Required by law.', 'Certain to remain unchanged.'], ['전력 절감 추정이 잠정적이라는 뜻이다.', '도구 없이 측정했다는 뜻이 아니다.', '법적 의무가 아니다.', '확정·불변의 반대다.']],
      ['Why does the final paragraph discuss dirt and maintenance?', 'To qualify the initial cooling result with long-term performance and cost.', ['To argue that the first measurements were fabricated.', 'To show that winter weather created the original summer data.', 'To replace the coating with new insulation in every building.'], ['초기 냉각 효과와 장기 유지·비용을 구분한다.', '자료 조작 주장은 없다.', '겨울이 여름 측정치를 만들지 않았다.', '전면 단열 교체 제안이 아니다.']],
    ],
  },
  {
    topic: '고대 관개 수로 해석',
    passage: `Archaeologists studying an ancient farming settlement found shallow channels running from a river toward former fields. The channels seemed to be part of an irrigation system, but their shape alone could not reveal when water had flowed through them. Floods might have cut some channels naturally. To investigate, the team mapped their connections and collected sediment from the channel floors and nearby undisturbed ground.

Sediment in several channels contained thin layers of material carried by slow-moving water. Similar layers were absent from the comparison ground. The team also found places where one channel crossed and cut into another, showing that at least two phases of construction had occurred. These observations supported repeated human modification, though they did not show exactly which crops had been watered. Plant remains near the fields could have arrived through farming, floodwater, or later disturbance.

The archaeologists avoided drawing a single map labeled “the irrigation system.” Instead, they published separate maps for the earlier and later channels. This distinction mattered because a channel built in one phase might have been abandoned before another was dug. Treating all traces as simultaneous would exaggerate the amount of land watered at any one time. The researchers described the evidence for water movement, the limits of crop identification, and the changing layout of the settlement.`,
    questions: [
      ['Which description best captures the channel study?', 'Using several kinds of evidence to reconstruct changing ancient water channels.', ['Proving that floods never affected the settlement.', 'Identifying every crop from channel shape alone.', 'Showing that all channels operated at the same time.'], ['퇴적층·교차 관계로 시기별 수로를 재구성한다.', '자연 홍수 가능성을 완전히 배제하지 않는다.', '모든 작물을 특정하지 못했다.', '동시 사용을 부정한다.']],
      ['What showed that channels had been built in more than one phase?', 'A later waterway cut across the course of an earlier one.', ['All channels contained identical crops.', 'The nearby ground had the same layers.', 'The river stopped moving permanently.'], ['수로 간 절단 관계가 선후 건설을 보여 준다.', '작물 동일성은 확인되지 않았다.', '비교 토양에는 해당 층이 없었다.', '하천의 영구 정지는 없다.']],
      ['Why would one combined map exaggerate irrigated land?', 'Some channels may have been abandoned before others were constructed.', ['The fields could never have grown crops.', 'The sediment samples contained no water-carried material.', 'The later channels were all natural flood cuts.'], ['시기가 다른 수로를 동시에 작동한 것처럼 합치게 된다.', '농사 불가능을 뜻하지 않는다.', '물 운반 층이 있었다.', '후기 수로를 모두 자연물로 보지 않았다.']],
      ['In the passage, “undisturbed” most nearly means', 'Not altered by the activity being studied.', ['Too dry to collect.', 'Built by the same workers.', 'Farther from every river.'], ['비교 토양은 수로 작용으로 교란되지 않은 상태다.', '채집 불가능한 건조함이 아니다.', '동일 작업자가 만들지 않았다.', '하천과의 절대 거리를 뜻하지 않는다.']],
      ['What is the function of the discussion of plant remains?', 'It illustrates a limit on identifying crops from nearby traces.', ['It proves the exact harvest of each construction phase.', 'It rules out all later disturbance.', 'It provides the date of every channel.'], ['식물 흔적의 유입 경로가 여러 가지라 작물 특정에 한계가 있다.', '정확한 수확물을 입증하지 않는다.', '후대 교란 가능성을 남긴다.', '수로 연대 전체를 제공하지 않는다.']],
    ],
  },
  {
    topic: '어류 음향 추적',
    passage: `To study the movement of river fish, biologists attached small acoustic tags to a sample of adults. Receivers placed along the river recorded a tag whenever a fish passed close enough. During the spring survey, most tagged fish were detected near the upstream spawning area. Several tags, however, disappeared from the receiver records for weeks before reappearing downstream.

An absence from the records did not mean a fish had stopped moving. A fish could swim outside a receiver\'s range, a receiver could fail, or the tag battery could run down. The team checked receiver performance with a test tag and estimated where gaps in coverage remained. They also compared detection times with river flow, because strong currents might alter both fish travel and sound transmission. The data gave a series of known detections, not a continuous path for each animal.

The researchers used the findings to propose a new receiver location near a side channel. They expected it to reduce one large gap in the network. Even with that addition, they would not treat every missing detection as evidence that a fish had died. The study\'s strongest claim was narrower: many tagged adults used the upstream area during the monitored period, and the existing receiver network could not fully describe their routes between stations.`,
    questions: [
      ['What is the main point about the tag records?', 'They show detections at receiver locations but not complete fish routes.', ['They continuously map every fish between stations.', 'They prove that missing fish died in the river.', 'They show that all fish avoided the upstream area.'], ['수신 지점의 탐지만 보여 주며 연속 이동 경로는 아니다.', '지점 사이를 계속 추적하지 못한다.', '미탐지를 죽음으로 단정하지 않는다.', '상류에서 다수가 탐지됐다.']],
      ['How did researchers check whether receivers were working?', 'They used a test tag.', ['They counted only untagged fish.', 'They replaced flow records with photographs.', 'They assumed every receiver had identical range.'], ['시험용 태그로 수신기 성능을 확인했다.', '비표지 개체 계수는 해당 점검이 아니다.', '유량 기록을 사진으로 바꾸지 않았다.', '수신 범위를 동일하다고 가정하지 않았다.']],
      ['Why propose a receiver near the side channel?', 'To reduce a gap in the detection network.', ['To make existing tags transmit without batteries.', 'To prevent fish from entering the upstream area.', 'To remove the need to interpret missing detections.'], ['측정망의 빈 구간을 줄이려는 것이다.', '태그 전지 문제를 없애지 못한다.', '어류 이동을 막으려는 것이 아니다.', '미탐지 해석 문제는 남는다.']],
      ['In the passage, “coverage” most nearly means', 'The area effectively monitored by the receivers.', ['A physical cover placed over each fish.', 'The number of pages in a report.', 'A guarantee that every fish was found.'], ['수신기가 탐지할 수 있는 공간 범위다.', '물리적 덮개가 아니다.', '보고서 분량이 아니다.', '모든 어류 탐지 보장은 아니다.']],
      ['Why does the middle paragraph list several causes of missing records?', 'To warn against equating a detection gap with lack of movement or death.', ['To show that acoustic tags never produce useful information.', 'To establish that all receivers failed at once.', 'To argue that river flow does not matter.'], ['미탐지의 여러 원인을 들어 단일 해석을 경계한다.', '태그 자료 전체가 무용한 것은 아니다.', '모든 수신기 동시 고장은 아니다.', '유량도 고려했다.']],
    ],
  },
  {
    topic: '학교 시작 시각 연구',
    passage: `A district moved the first lesson at three secondary schools from 7:30 to 8:15 in the morning. Teachers hoped students would arrive less tired. During the first term, the district recorded attendance and asked students about sleep. More students reported sleeping at least eight hours, and late arrivals became less frequent. The change was welcomed, but the district knew that a new bus route had begun in the same term.

The route might explain some of the improvement in punctuality. To examine this possibility, analysts compared students who used the new route with students who did not. Late arrivals fell in both groups, though the decline was larger among bus riders. Sleep reports changed similarly across the groups. The survey could not verify the exact time each student fell asleep; it measured what students said. Analysts therefore separated the attendance records from the self-reported sleep data.

The district kept the later start the following year while collecting another term of information. Officials avoided saying that the schedule alone improved grades, because coursework and assessment rules had also changed. Their more limited conclusion was that the later start was associated with more reported sleep and fewer late arrivals under the conditions studied. The additional year would show whether those patterns continued after families adjusted their morning routines.`,
    questions: [
      ['What is the study\'s most defensible conclusion?', 'The later start coincided with more reported sleep and fewer late arrivals.', ['The schedule alone raised grades at every school.', 'The new bus route had no effect on punctuality.', 'Every student actually slept at least eight hours.'], ['관측된 것은 수면 자기보고 증가와 지각 감소의 연관이다.', '성적 단독 효과는 입증하지 않았다.', '버스 노선 영향 가능성이 있다.', '모든 학생의 실제 수면을 확인하지 못했다.']],
      ['What happened to late arrivals in the two bus-use groups?', 'They decreased in both, more strongly among new-route riders.', ['They rose equally in both groups.', 'They decreased only among students who did not ride the bus.', 'They were not recorded during the study.'], ['두 집단 모두 줄었지만 버스 이용자에서 감소폭이 컸다.', '증가가 아니다.', '비이용자에게만 나타난 것이 아니다.', '지각 기록을 수집했다.']],
      ['Why did analysts separate attendance records from sleep reports?', 'The former were administrative counts, while the latter relied on students\' statements.', ['The two kinds of data described different school years only.', 'Sleep reports were collected from teachers instead of students.', 'Attendance data contained exact bedtimes.'], ['출석은 기록, 수면은 학생의 자기보고로 근거 성격이 다르다.', '동일 학기 자료가 있다.', '수면은 학생에게 물었다.', '출석표에 취침 시각은 없다.']],
      ['In the passage, “punctuality” most nearly means', 'Arriving at the expected time.', ['Earning a high examination grade.', 'Taking a longer bus ride.', 'Sleeping without interruption.'], ['제시간에 도착하는 성질이다.', '시험 성적이 아니다.', '버스 시간 길이가 아니다.', '수면의 연속성과 다르다.']],
      ['Why does the passage mention coursework and assessment changes?', 'To limit any claim that the start time alone caused grade changes.', ['To explain why the bus route was canceled.', 'To prove that sleep reports were fabricated.', 'To show that the district stopped collecting attendance.'], ['성적 변화를 시간표 하나에 귀속시키기 어렵다는 이유다.', '버스 취소는 없다.', '보고 자료 조작 주장은 없다.', '출석 수집 중단도 없다.']],
    ],
  },
  {
    topic: '해조숲과 초식동물',
    passage: `Along a rocky coast, kelp once formed dense stands. Divers later found areas with almost no kelp and many sea urchins grazing on the rock. It was tempting to say that urchins alone had caused the change. The divers had not measured urchin numbers before the decline, and a warm-water event had occurred then.

Researchers placed small cages over patches of rock. The cages kept larger grazers out while allowing water and light to enter. They compared kelp growth inside the cages with growth on nearby open rock. Young kelp survived more often inside, which supported a role for grazing. Yet the cages also changed water movement slightly, so the team measured flow and added partial cages that blocked water similarly without excluding all urchins. Results from those controls helped distinguish grazing from a cage effect.

The researchers did not conclude that warming had been irrelevant. Heat might have weakened older kelp before the young plants faced grazing pressure. They proposed that two stresses could act in sequence: an initial loss from warm water followed by slower recovery where urchins were abundant. A longer series of temperature and animal counts would be needed to test that history. For now, the cage study showed that reducing access by grazers improved the survival of young kelp in the tested patches.`,
    questions: [
      ['What does the passage suggest about kelp decline?', 'Warming and grazing may have acted at different stages of the change.', ['Cage tests proved that warm water never affects kelp.', 'Urchins were counted before the first loss and excluded as a cause.', 'Kelp failed equally inside and outside every cage.'], ['초기 손실과 회복 저해에 서로 다른 요인이 작용했을 수 있다.', '온난화 무관은 입증하지 않았다.', '초기 성게 수는 없었다.', '어린 다시마 생존은 우리 안에서 높았다.']],
      ['What did the full cages do?', 'Keep larger grazers out while admitting water and light.', ['Stop all water from reaching the rock.', 'Increase the number of urchins inside the patch.', 'Move older kelp to a new coast.'], ['큰 초식동물 접근을 막고 물·빛은 통과시켰다.', '물을 전부 차단하지 않았다.', '성게를 늘리지 않았다.', '다른 해안으로 옮기지 않았다.']],
      ['Why were partial cages added?', 'To separate a grazing effect from changes caused by the cage itself.', ['To prevent researchers from measuring water flow.', 'To make every patch equally inaccessible to urchins.', 'To reproduce the earlier warm-water event.'], ['우리 구조 자체의 물 흐름 효과와 방목 배제 효과를 분리했다.', '유량도 측정했다.', '일부 우리는 완전 배제하지 않았다.', '온난 수온을 재현한 것이 아니다.']],
      ['In the passage, “abundant” most nearly means', 'Present in large numbers.', ['Unable to move.', 'Recently born.', 'Difficult to observe.'], ['성게가 많이 있다는 뜻이다.', '이동 불능이 아니다.', '갓 태어났다는 뜻이 아니다.', '관측 난도를 뜻하지 않는다.']],
      ['How does the final paragraph extend the cage findings?', 'It offers a possible sequence of stresses without treating it as established.', ['It claims cages directly measured historical temperature.', 'It removes the need for future animal counts.', 'It says grazing prevented all growth in every tested patch.'], ['실험 결과를 바탕으로 역사적 순서를 가설로 제시한다.', '우리가 과거 수온을 직접 측정하지 않았다.', '추가 계수가 필요하다.', '모든 성장 완전 차단이라고 하지 않았다.']],
    ],
  },
  {
    topic: '이중언어 대화의 언어 전환',
    passage: `In a bilingual neighborhood, speakers sometimes moved between two languages during a single conversation. One researcher originally counted every switch as evidence that a speaker lacked a word in the first language. Interviews challenged that explanation. Several speakers could provide the same word in either language but chose one form when quoting a family member or referring to a local custom.

The researcher recorded conversations among friends and compared them with conversations between strangers. Switches were more common in the friend groups, where listeners shared references to events and people. Yet friendship was not the only difference: friends also talked about different topics. To avoid confusing audience with topic, the researcher asked some pairs to discuss the same photograph in both settings. That comparison reduced, but did not remove, the difference in switching frequency.

The revised account did not treat switching as random or as a sign of linguistic failure. A switch could mark a quotation, signal shared identity, or help organize a story. The same form might serve different purposes in different conversations, so the researcher examined the words surrounding each switch. Frequency counts remained useful, but interpretation required attention to context. The project showed why a simple tally could not, by itself, explain what speakers were doing.`,
    questions: [
      ['What is the passage\'s main argument?', 'Language switching can serve conversational purposes beyond filling a vocabulary gap.', ['A switch always means the speaker lacks a word.', 'Friends and strangers use identical topics and language patterns.', 'Frequency counts alone fully explain each switch.'], ['인용·정체성·담화 구성 등 여러 기능을 가질 수 있다.', '단어 부족만의 증거가 아니다.', '주제와 사용 양상이 같지 않았다.', '횟수만으로 기능은 알 수 없다.']],
      ['Why did the researcher use the same photograph in two settings?', 'To reduce the effect of different conversation topics.', ['To make speakers forget both languages.', 'To replace all interviews with written tests.', 'To prove that friendship had no influence.'], ['친구·낯선 사람 대화의 주제 차이를 줄이려는 것이다.', '언어를 잊게 하려는 것이 아니다.', '인터뷰를 전부 없애지 않았다.', '친밀감 영향이 남았다.']],
      ['What can be inferred from the remaining difference after the photo comparison?', 'Factors besides topic may influence switching.', ['Topic was the only possible influence.', 'The comparison showed no difference at all.', 'Every switch marked an unknown word.'], ['주제를 맞춰도 차이가 남아 다른 요인 가능성이 있다.', '주제만이 유일 원인은 아니다.', '차이가 완전히 사라지지 않았다.', '어휘 부족만을 뜻하지 않는다.']],
      ['In the passage, “tally” most nearly means', 'A count or recorded total.', ['A translation of a quotation.', 'A conversation partner.', 'A photograph used as a prompt.'], ['전환 횟수를 세어 기록한 수치다.', '인용 번역이 아니다.', '대화 상대를 뜻하지 않는다.', '사진 자체가 아니다.']],
      ['What does the first paragraph do in the passage?', 'It presents an initial explanation and evidence that challenges it.', ['It proves that neither language contains local words.', 'It describes the final experiment\'s numerical results.', 'It argues that quotations cannot involve a switch.'], ['초기 가설과 그에 반하는 인터뷰 사실을 제시한다.', '두 언어의 어휘 부재가 아니다.', '최종 수치 결과는 뒤에 나온다.', '인용은 전환 이유 중 하나다.']],
    ],
  },
  {
    topic: '범람원과 퇴적물',
    passage: `A river carries fine sediment during floods. When water spreads across a floodplain and slows, some sediment settles on the ground. Farmers living downstream of a new levee noticed that their fields no longer received a thin layer of fresh material after spring floods. They suspected the levee, which kept most floodwater inside the channel, but the river\'s sediment supply had also changed upstream.

Geographers compared old field records with samples collected on both sides of the levee. The protected fields received less new sediment than unprotected ground nearby. To examine the upstream change, the team also measured suspended material in the river during several floods. Those samples showed that the river still carried sediment, though not necessarily in the same quantity as decades earlier. The contrast across the levee supported a local effect, but the available records could not fully separate it from the long-term upstream trend.

Some farmers wanted the levee removed. Others valued its protection against damaging floods. The researchers proposed controlled openings at selected times rather than an immediate removal. They stressed that such openings would require safety review and careful monitoring of water and sediment. Their study did not decide the policy question. It clarified the trade-off between keeping fields dry and allowing the river to deliver material that had once accumulated there.`,
    questions: [
      ['What is the central issue in the passage?', 'A levee protects fields from floods but may also reduce their sediment input.', ['A levee permanently stops all sediment from moving in a river.', 'Upstream sediment supplies were measured as unchanged for decades.', 'Farmers agreed unanimously to remove the levee.'], ['홍수 보호와 범람원 퇴적물 유입 사이의 상충을 설명한다.', '강 안의 이동 전체가 멈춘 것은 아니다.', '장기 공급량 동일은 확인되지 않았다.', '농민 의견이 갈렸다.']],
      ['What comparison supported a local levee effect?', 'Protected fields received less new sediment than nearby unprotected ground.', ['All river water disappeared above the levee.', 'Every field received equal sediment after floods.', 'The river carried no suspended material in recent floods.'], ['제방 안팎의 인접 지면 퇴적 차이가 근거다.', '상류 물 소실은 없다.', '동일 퇴적이 아니다.', '최근 강에도 부유 퇴적물이 있었다.']],
      ['Why could the team not assign the entire change to the levee?', 'The river\'s upstream sediment supply may also have changed.', ['There were no differences across the levee.', 'Fine sediment never settles when water slows.', 'The new levee had been removed before sampling.'], ['상류 공급의 장기 변화도 영향을 줄 수 있다.', '안팎 차이가 있었다.', '느려진 물에서 퇴적된다.', '조사 당시 제방은 있었다.']],
      ['In the passage, “suspended” most nearly means', 'Carried within flowing water rather than settled on the ground.', ['Stored under the fields for centuries.', 'Removed from every water sample.', 'Protected from all flood damage.'], ['흐르는 물속에 떠서 운반되는 상태다.', '지하 장기 저장이 아니다.', '모든 표본에서 제거된 것이 아니다.', '홍수 피해 보호를 뜻하지 않는다.']],
      ['What is the purpose of describing controlled openings?', 'To offer a possible response while emphasizing safety and monitoring needs.', ['To say that an opening had already solved the problem.', 'To prove that farmers no longer valued flood protection.', 'To reject the need for any policy discussion.'], ['절충 가능성을 제시하되 안전·관찰 필요성을 붙인다.', '이미 해결됐다고 하지 않았다.', '홍수 보호 수요가 남아 있다.', '정책 논의가 필요하다.']],
    ],
  },
  {
    topic: '시민 참여 천문 관측',
    passage: `A small observatory asked volunteers to help record when a variable star appeared bright or faint. Professional instruments could measure the star precisely on some nights, but cloudy weather and limited telescope time left gaps. Volunteers in different towns used modest cameras and submitted observations with a timestamp and a note about sky conditions.

The first collection contained many reports, yet some values could not be compared. Cameras had different settings, and a few volunteers had used local time without stating their time zone. The observatory provided a common reference star and a simple calibration guide. It also required each report to name the time standard. After these changes, fewer reports had to be excluded. A larger number of observations was useful only when their measurements could be interpreted on the same scale.

Analysts looked for a repeating pattern in the star\'s brightness. They did not remove a surprising report merely because it failed to match an expected cycle. Instead, they checked the camera settings and sky notes before deciding whether the report was reliable. Several unusual observations remained uncertain. The project showed how volunteers could widen the observing window, while also showing why open participation needed clear procedures. Its result was a better-supported time series, not a claim that every submitted photograph was equally accurate.`,
    questions: [
      ['What is the star-reporting passage mainly about?', 'How volunteer observations became more useful through shared calibration and reporting rules.', ['Why professionals stopped observing the variable star.', 'How a single camera measured every town\'s sky.', 'Why unexpected observations were deleted automatically.'], ['자원봉사 관측을 공통 기준으로 비교 가능하게 만든 과정이다.', '전문가 관측은 계속된다.', '카메라는 여러 종류였다.', '예상 밖 관측을 자동 삭제하지 않았다.']],
      ['What information was missing from some early timestamps?', 'The time zone used by the observer.', ['The name of the reference star.', 'The date the guide was published.', 'The camera\'s purchase price.'], ['현지 시각의 시간대 표기가 빠져 있었다.', '기준별은 후속 보정에 쓰였다.', '안내서 발행일 문제는 없다.', '가격은 언급되지 않는다.']],
      ['Why did analysts check surprising reports before excluding them?', 'A mismatch with the expected cycle was not itself proof of measurement error.', ['Every surprising value must be the true brightness.', 'Camera settings never affect reported values.', 'Sky conditions had already been made identical everywhere.'], ['예상 패턴과 다르다는 이유만으로 오류라 단정할 수 없다.', '이상치가 모두 참이라는 뜻은 아니다.', '설정은 수치에 영향을 준다.', '지역별 하늘은 동일하지 않았다.']],
      ['In the passage, “calibration” most nearly means', 'Adjustment to make measurements comparable against a reference.', ['A schedule for assigning volunteers.', 'A way of removing cloudy nights.', 'An estimate of each camera\'s age.'], ['기준별을 이용해 측정값을 비교 가능하게 맞추는 과정이다.', '배정 일정이 아니다.', '흐린 날을 없애지 않는다.', '카메라 연식 추정이 아니다.']],
      ['Why does the second paragraph describe excluded reports?', 'To show that data quantity alone did not guarantee usable evidence.', ['To argue that volunteer reports could never be useful.', 'To prove the star had stopped changing brightness.', 'To introduce a second star that replaced the target.'], ['보고량보다 비교 가능한 품질이 중요함을 보여 준다.', '시민 관측 전체를 부정하지 않는다.', '변광이 멈춘 것은 아니다.', '대상별을 바꾸지 않았다.']],
    ],
  },
  {
    topic: '농경지 꽃띠와 수분매개자',
    passage: `Several farms planted narrow strips of flowering plants beside crop fields. The strips were intended to provide food for pollinators outside the crop\'s short flowering season. During one summer, researchers counted visits by bees and other flower-visiting animals. The strips attracted many visitors, but the crop fields themselves did not show the same increase at every farm.

Distance appeared to matter. In fields immediately beside a strip, researchers observed more visits during the crop\'s flowering period. In fields separated by roads or large bare areas, the pattern was weaker. The team also noted that some visitors carried pollen from the crop while others visited flowers without clearly moving its pollen. A visit count was therefore not identical to a count of successful pollination. Weather and the kinds of flowers planted could further influence the results.

The researchers did not dismiss the strips. They argued that the strips could support flower-visiting animals over more of the season, even when crop yield did not rise in the first year. To test crop effects more directly, they planned to compare fruit set at several distances from strips over multiple seasons. Farmers considering the approach would need to choose plants that flower at useful times and maintain the strips so they do not become dominated by only one species.`,
    questions: [
      ['What is the passage\'s main conclusion?', 'Flower strips attract visitors, but crop benefits depend on distance and actual pollen transfer.', ['Every farm had the same increase in crop yield.', 'Flower visits always equal successful crop pollination.', 'Roads strengthened the effect of nearby strips.'], ['유인 효과와 작물 수분 효과를 구분하며 거리도 고려한다.', '수확량 동일 증가는 관측되지 않았다.', '방문만으로 성공 수분은 아니다.', '도로가 있는 곳은 효과가 약했다.']],
      ['Where were crop visits more numerous?', 'In fields directly next to a planted strip.', ['In the most distant fields across bare ground.', 'Only on farms without any flowering strip.', 'Equally at every distance from the strip.'], ['꽃띠 바로 옆 밭에서 방문이 더 많았다.', '멀리 떨어진 밭은 약했다.', '꽃띠 없는 농장만이 아니다.', '거리별 차이가 있었다.']],
      ['Why would fruit set be a useful later measure?', 'It could test crop outcomes more directly than visitor counts alone.', ['It would remove the need to identify any crop field.', 'It would prove every visitor carried the same pollen.', 'It could replace all comparisons across distance.'], ['결실은 단순 방문보다 작물 성과에 가까운 지표다.', '밭 식별은 여전히 필요하다.', '방문자 꽃가루를 모두 같게 만들지 않는다.', '거리 비교도 계속 계획한다.']],
      ['In the passage, “dominated” most nearly means', 'Occupied or controlled mainly by one kind.', ['Planted for the first time.', 'Measured during cold weather.', 'Hidden from nearby fields.'], ['한 종이 꽃띠의 대부분을 차지한다는 뜻이다.', '첫 식재와 다르다.', '추운 날 측정 뜻이 아니다.', '밭에서 안 보인다는 뜻이 아니다.']],
      ['Why does the passage distinguish visits from successful pollination?', 'To explain why animal counts alone cannot establish crop benefit.', ['To show that no animal visited the crop flowers.', 'To prove that every flower strip lowers yield.', 'To argue that distance cannot matter.'], ['방문이 실제 꽃가루 전달과 다를 수 있어 성과 판단을 제한한다.', '작물 꽃 방문은 있었다.', '모든 꽃띠의 수확량 감소는 없다.', '거리 영향이 관측됐다.']],
    ],
  },
  {
    topic: '도서관 신문 디지털화',
    passage: `A library scanned a collection of local newspapers so readers could search them without handling fragile pages. The first search system worked well for recent issues, but it missed many words in older papers. Their faded ink, narrow columns, and unusual typefaces confused the text-recognition program. A search for a street name might return no result even when that name appeared in an image.

Librarians selected pages from different decades and checked recognized text against images by hand. Errors were especially common near column edges. Rather than claiming that all issues were fully searchable, the library attached a notice describing the limitation. It also let users view page images when a text search failed. Staff used volunteers' corrections of names and dates to refine recognition rules, then tested retrieval on separate pages the volunteers had not edited.

The corrected sample improved several searches, but the library did not apply its error rate to every paper. Some editions were printed more clearly than others. The librarians planned to add more reviewed samples before deciding where correction work would have the greatest effect. Digital access reduced handling of old pages, yet the library treated the searchable text as an imperfect guide to the images rather than a complete substitute for them.`,
    questions: [
      ['What issue is the passage mainly addressing?', 'Why searchable text from scanned newspapers needs checking against page images.', ['Why the library stopped preserving the original newspapers.', 'How recent issues became less searchable than all older ones.', 'Why no reader could access the scanned images.'], ['OCR 검색문과 실제 이미지의 불일치를 점검해야 한다.', '원본 보존을 중단하지 않았다.', '문제는 주로 오래된 신문이다.', '이미지는 열람 가능했다.']],
      ['Where were recognition errors particularly frequent?', 'Near newspaper column edges.', ['Only in modern digital articles.', 'Only on pages without street names.', 'On the outside of storage boxes.'], ['신문 단 가장자리에서 오류가 잦았다.', '현대 디지털 기사만의 문제는 아니다.', '거리 이름 유무와 무관하다.', '보관 상자 표면이 아니다.']],
      ['Why test searches on pages volunteers had not edited?', 'To see whether corrections improved retrieval beyond the training sample.', ['To ensure the original page images were destroyed.', 'To prevent users from viewing any corrected text.', 'To make every edition have the same printing quality.'], ['수정에 쓰지 않은 자료에서 검색 개선을 확인하기 위해서다.', '원본 이미지는 보존된다.', '수정문 열람을 막지 않았다.', '인쇄 품질을 동일하게 만들 수 없다.']],
      ['In the passage, “retrieval” most nearly means', 'Finding requested information through a search.', ['Repairing a torn physical page.', 'Printing a new newspaper edition.', 'Counting the number of library volunteers.'], ['검색으로 원하는 정보를 찾아내는 뜻이다.', '찢긴 종이 수리가 아니다.', '새 판 발행이 아니다.', '봉사자 수 계산이 아니다.']],
      ['What is the function of the final sentence?', 'It balances the value of digital access against limits of machine-readable text.', ['It says the page images should be discarded.', 'It claims every historical article has been corrected.', 'It announces that text search is no longer offered.'], ['디지털 접근의 이점과 OCR 텍스트 한계를 함께 정리한다.', '이미지 폐기를 주장하지 않는다.', '전체 교정 완료가 아니다.', '검색 기능 중단이 아니다.']],
    ],
  },
]
