import type { FullAcademicPassage } from './fullAcademicReading'

export const B1_PASSAGES: FullAcademicPassage[] = [
  {
    topic: '공동체 정원의 물 관리',
    passage: `The Maple Street garden began with a simple rule: each plot holder could use the shared tap whenever it was free. The rule worked during a rainy spring. In June, however, the tap was often left running while gardeners carried tools or talked. Some plots received far more water than others, and the garden\'s monthly bill rose.

The committee did not ban watering. Instead, it put two rain barrels beside the tool shed and allocated short tap periods to each plot. Volunteers measured the water held in the barrels after storms and posted the amount on a board. When the barrels were nearly empty, tap periods became shorter for everyone. Gardeners with newly planted seedlings could request an extra period, but they had to record it. The records made exceptions visible rather than secret.

By late summer, the bill had fallen and complaints about unfair access had become less common. The committee could not tell how much of the savings came from the barrels and how much came from the schedule. Both changes began at about the same time. Still, its members kept the records, believing that a future dry summer might show which measure mattered most.`,
    questions: [
      ['What is the passage mainly about?', 'How a garden made shared watering more accountable during the summer.', ['Why the garden replaced all its plots with rain barrels.', 'How a rainy spring permanently solved the water shortage.', 'Why gardeners stopped growing seedlings in summer.'], ['물 사용 규칙과 기록을 통해 공정성을 높인 과정이다.', '화단을 물통으로 바꾸지 않았다.', '봄비만으로 여름 문제가 해결되지 않았다.', '모종 재배를 중단하지 않았다.']],
      ['What happened when the rain barrels were nearly empty?', 'The tap periods were shortened for all plot holders.', ['Only the newest gardeners lost access to the tap.', 'The committee removed the water-use board.', 'The tap was left open until the next storm.'], ['물통이 거의 비면 모두의 사용 시간이 줄었다.', '신규 정원사만 제한한 것이 아니다.', '게시판을 없애지 않았다.', '수도꼭지를 계속 열어 두지 않았다.']],
      ['Why did the committee keep records after the bill fell?', 'The records might help compare the effects of the two changes later.', ['The records proved the barrels alone caused all savings.', 'The committee planned to charge each gardener for every seedling.', 'The schedule had already been judged ineffective.'], ['다음 건조한 여름에 두 조치의 효과를 구분하려는 것이다.', '물통 단독 효과는 입증되지 않았다.', '모종별 요금 계획은 없다.', '일정의 무효가 확인되지 않았다.']],
      ['In the passage, what does “allocated” most nearly mean?', 'Set aside for a particular user or purpose.', ['Thrown away after use.', 'Hidden from public view.', 'Made larger without limit.'], ['문맥상 특정 사용자에게 배정한다는 뜻이다.', '폐기를 뜻하지 않는다.', '비공개로 숨긴다는 뜻이 아니다.', '무제한 확대가 아니다.']],
      ['Why does the final paragraph mention that two changes began together?', 'To explain why the savings cannot yet be assigned to only one measure.', ['To show that neither change affected water use.', 'To argue that the bill was measured incorrectly.', 'To introduce a third watering rule.'], ['동시 시행 때문에 어느 조치의 기여인지 분리하기 어렵다.', '두 조치가 무효였다는 뜻이 아니다.', '청구서 오류는 제시되지 않았다.', '세 번째 규칙은 나오지 않는다.']],
    ],
  },
  {
    topic: '박물관 전시 설명',
    passage: `For many years, the Harbor Museum displayed a fishing boat with a short label: “Built in 1912.” Visitors could see its wooden hull, but they learned little about the people who used it. When the museum planned a new exhibition, staff interviewed families whose relatives had worked on similar boats. They also examined repair marks on the vessel. One patch showed that a damaged side had been fixed with wood from a different kind of tree.

The new label did not pretend that every mark had a known story. It explained that the patch might reflect a repair made when the usual wood was hard to obtain. A separate panel described what one family remembered about storm-season work. The panel clearly identified that account as a memory, not as a record of this particular boat. Staff wanted visitors to understand both the value and the limits of each source.

After the change, visitors spent more time at the boat and asked more questions. The museum did not conclude that longer visits proved the label was historically correct. Instead, it invited former fishers and local historians to review the text each year. Their comments could correct errors or add context without erasing the evidence already on display.`,
    questions: [
      ['What is the central purpose of the revised boat display?', 'To connect physical evidence with local accounts while noting uncertainty.', ['To replace the boat with recorded interviews.', 'To claim that every repair mark has a certain explanation.', 'To prove that longer visits make a label accurate.'], ['실물 흔적과 구술 기억을 함께 보여 주되 불확실성을 구분한다.', '배를 인터뷰로 대체하지 않았다.', '모든 수리 이유를 확정하지 않았다.', '체류 시간은 정확성의 증거가 아니다.']],
      ['What did the museum find on the boat?', 'A repair made with a different kind of wood.', ['A written log attached to the hull.', 'A label naming every former crew member.', 'A second boat hidden inside the display.'], ['선체 한쪽에 다른 수종 목재로 고친 흔적이 있었다.', '선박 일지는 언급되지 않는다.', '모든 선원의 이름은 없었다.', '다른 배가 발견된 것이 아니다.']],
      ['Why was the family account identified as a memory?', 'It concerned similar boats but was not a direct record of this vessel.', ['The family had never seen any fishing boat.', 'The museum knew the memory was false.', 'Repair marks were unavailable for comparison.'], ['기억은 유사한 배의 경험이지 이 배 자체의 직접 기록은 아니다.', '가족이 배를 본 적 없다는 말은 없다.', '거짓으로 판정하지 않았다.', '수리 흔적은 실제로 조사했다.']],
      ['In the passage, what does “context” most nearly mean?', 'Information that helps explain the boat and its use.', ['The wood placed under the boat.', 'A visitor\'s ticket price.', 'A rule that prevents further study.'], ['문맥상 배를 이해하는 데 보태는 배경 정보다.', '배 밑의 목재를 뜻하지 않는다.', '입장료가 아니다.', '추가 연구 금지도 아니다.']],
      ['What role does the final paragraph play?', 'It describes public response and a plan for continuing review.', ['It supplies a definite date for the repair.', 'It withdraws the new label after complaints.', 'It argues that interviews should never be used.'], ['관람객 반응과 매년 내용 재검토 계획을 제시한다.', '수리 날짜를 확정하지 않는다.', '새 설명을 철회하지 않았다.', '인터뷰 사용을 부정하지 않는다.']],
    ],
  },
  {
    topic: '철새와 도시 불빛',
    passage: `Many small birds travel at night during migration. On clear nights they can use stars and other cues to maintain a direction. Bright city lights may draw some birds toward buildings, where glass and unfamiliar streets create hazards. A coastal town noticed many exhausted birds near its waterfront towers after foggy nights. Residents first proposed turning off every light for the entire autumn.

The town\'s wildlife group suggested a narrower plan. It asked building managers to dim decorative lights from midnight until dawn during the busiest migration weeks. Safety lights at entrances remained on. Volunteers walked the same short routes each morning and recorded the birds they found. They also noted weather, since fog could influence both migration and the number of birds that landed nearby. The counts fell after the lighting change, especially on foggy mornings.

The group called the result encouraging but not conclusive. It had no way to count all birds flying over the town, and volunteers might have missed birds that rested in hidden places. To learn more, the group planned to repeat the counts the next year and compare buildings that changed their lights with similar buildings that did not. The new plan kept public safety needs in view while testing whether dimmer lighting helped.`,
    questions: [
      ['Which initiative involving migrating birds is the passage mainly about?', 'A town\'s attempt to reduce possible light-related risks for migrating birds.', ['A plan to stop all nighttime travel by birds.', 'Proof that fog alone caused every bird landing.', 'A proposal to remove safety lighting from all buildings.'], ['철새의 도시 불빛 노출을 줄이고 효과를 살펴보는 이야기다.', '새의 야간 이동을 막지 않는다.', '안개만이 모든 원인이라고 증명하지 않았다.', '안전등은 유지했다.']],
      ['Which lights remained on under the plan?', 'Lights needed at building entrances for safety.', ['All decorative tower lights.', 'Only lights inside empty offices.', 'Every waterfront advertisement.'], ['출입구의 안전 조명은 계속 켜 두었다.', '장식 조명은 어둡게 했다.', '빈 사무실 조명만을 지정하지 않았다.', '광고 조명을 모두 유지한 것은 아니다.']],
      ['Why did volunteers record the weather?', 'Fog might affect both bird movement and the counts.', ['Weather determined which buildings owned the towers.', 'The group wanted to replace bird counts with forecasts.', 'Clear weather always prevented migration.'], ['안개가 실제 이동과 관측 수에 모두 영향을 줄 수 있다.', '건물 소유와는 관계없다.', '일기예보로 관측을 대체하지 않았다.', '맑은 날 이동이 불가능한 것은 아니다.']],
      ['In the passage, “conclusive” most nearly means', 'Strong enough to settle the question.', ['Easy to carry out.', 'Hidden from the public.', 'Limited to one season.'], ['결론을 확정할 만큼 결정적이라는 뜻이다.', '시행의 용이성을 뜻하지 않는다.', '비공개라는 뜻이 아니다.', '한 계절로 제한된다는 뜻도 아니다.']],
      ['Why does the final paragraph describe a second year of counting?', 'To show how the group plans to test its first observation more carefully.', ['To announce that the original counts were deleted.', 'To introduce a new species that does not migrate.', 'To argue that buildings need no comparison group.'], ['첫 관측의 한계를 보완할 후속 비교 계획이다.', '기존 기록을 삭제하지 않았다.', '새 종의 발견이 아니다.', '비교 건물을 사용하려 한다.']],
    ],
  },
  {
    topic: '도자기 복원과 기록',
    passage: `A museum received a bowl that had broken into twelve pieces. Some pieces fit neatly together, but two were missing. The conservator could have filled the gaps and painted the new material to match the old surface. That approach would make the bowl look complete from a distance, yet visitors might then mistake modern additions for ancient clay.

The museum chose a different method. The conservator attached the original pieces with a reversible adhesive and used a plain, light-colored fill in the missing areas. Reversible means that another specialist can remove the adhesive without greatly harming the original material. Before any work began, the team photographed each piece and drew a map of where it belonged. They also kept a small sample of an older glue found on the bowl. That sample could help future researchers understand an earlier repair.

The finished bowl was stable enough for display, but the light fill remained easy to see. A label explained which parts were ancient and which had been added. Some visitors said they would have preferred a perfect-looking bowl. The museum replied that showing the repair honestly was part of telling the object\'s history. It treated restoration not as a way to erase damage, but as a way to preserve and explain the surviving evidence.`,
    questions: [
      ['What principle guides the museum\'s treatment of the bowl?', 'Stabilize it while making modern repairs distinguishable from original material.', ['Hide every repair so the object appears untouched.', 'Discard pieces that do not fit at once.', 'Replace the ancient clay with stronger modern material.'], ['안정화하되 새로 보수한 부분을 원형과 구별한다.', '수리를 감추지 않았다.', '맞지 않는 조각을 버리지 않았다.', '원래 점토를 모두 바꾸지 않았다.']],
      ['What did the team do before attaching the pieces?', 'It photographed and mapped the fragments.', ['It painted every gap to match the old surface.', 'It removed the old glue sample and threw it away.', 'It displayed the bowl without recording its condition.'], ['작업 전 각 조각의 사진과 배치도를 만들었다.', '틈을 옛 표면처럼 칠하지 않았다.', '옛 접착제 표본을 보관했다.', '상태를 기록한 뒤 전시했다.']],
      ['Why did the team keep a sample of the older glue?', 'It might reveal something about a previous repair.', ['It proved the bowl had never been broken before.', 'It would be used to hide the modern fill.', 'It showed that all twelve pieces were original.'], ['예전 수리 방법을 연구할 자료가 될 수 있다.', '오히려 이전 수리 흔적이다.', '현대 보충부를 숨기기 위한 것이 아니다.', '모든 조각의 연대를 증명하지 않는다.']],
      ['In the passage, “reversible” most nearly means', 'Able to be undone without seriously damaging the original.', ['Certain to change color over time.', 'Impossible to remove after drying.', 'Suitable only for a single display.'], ['원래 부분을 크게 해치지 않고 되돌릴 수 있다는 뜻이다.', '색 변화 뜻이 아니다.', '제거 불가능의 반대다.', '전시 횟수 제한을 뜻하지 않는다.']],
      ['How does the final paragraph relate to the earlier description of the fill?', 'It explains why the visible repair is part of the museum\'s interpretation.', ['It reports that the fill was secretly repainted.', 'It changes the number of missing pieces.', 'It argues that visitors should not read labels.'], ['보이는 보수 흔적이 왜 설명의 일부인지 밝힌다.', '몰래 다시 칠하지 않았다.', '없어진 조각 수는 변하지 않는다.', '설명문을 읽지 말라고 하지 않는다.']],
    ],
  },
  {
    topic: '이동 도서관 서비스',
    passage: `A county library had a building in the largest town, but residents of smaller villages rarely visited it. A weekly bus service already carried parcels between the villages. Library staff proposed using part of the bus to deliver books that readers had reserved. The plan seemed simple until staff considered how books would be returned and how readers without internet access could place requests.

The library added a paper request form at each village store. Drivers collected the forms on Mondays and delivered requested books the following week. Returns went into locked boxes at the stores. At first, several books were recorded as missing because a driver had collected them but the library had not yet scanned them. Staff changed the record so a book received a temporary “in transit” status as soon as it left the box. That status did not mean the book had reached the central building.

After six months, more village residents held library cards. The staff did not claim that the bus alone had caused the increase; a new school reading project began during the same period. However, the forms and transit records showed that the service reached readers who had not used online reservations. The library kept both request methods and asked drivers to report missed stops before expanding the route.`,
    questions: [
      ['What is the passage chiefly about?', 'How a library adapted an existing bus route to reach village readers.', ['Why the county closed its main library building.', 'How online requests replaced all paper forms.', 'Why parcel delivery ended when books were added.'], ['기존 버스 노선에 도서 신청·배달 절차를 얹은 과정이다.', '본관을 닫지 않았다.', '종이 양식을 유지했다.', '소포 운송이 끝났다는 말은 없다.']],
      ['How could a reader without internet access request a book?', 'By leaving a paper form at a village store.', ['By waiting for the driver to choose a title.', 'By returning an unrelated parcel.', 'By asking the central building to close its website.'], ['마을 상점의 종이 신청서를 이용할 수 있었다.', '기사가 임의로 책을 고르지 않았다.', '소포 반환은 신청 방식이 아니다.', '웹사이트 폐쇄가 필요하지 않다.']],
      ['Why was the “in transit” status introduced?', 'To distinguish a collected return from a book already scanned at the library.', ['To show that every returned book was truly lost.', 'To mark a reserved book as delivered to its reader.', 'To remove the need for locked return boxes.'], ['수거됐지만 본관에서 스캔·등록되기 전인 책의 상태를 구분한다.', '실제 분실이라고 단정하지 않았다.', '독자에게 배달 완료와 다르다.', '반납함은 계속 사용한다.']],
      ['In the passage, “expanding” most nearly means', 'Making the route cover more places.', ['Shortening every book.', 'Changing the color of the bus.', 'Locking the returns permanently.'], ['노선 범위를 넓힌다는 뜻이다.', '책 길이를 줄이는 뜻이 아니다.', '차량 색과 무관하다.', '반납을 막지 않는다.']],
      ['Why is the school project mentioned near the end?', 'It is another possible cause of the rise in library cards.', ['It explains why the bus stopped visiting villages.', 'It proves that paper forms were not used.', 'It shows that the book service existed before the library.'], ['이용증 증가에 영향을 줬을 다른 요인을 밝힌다.', '버스 운행 중단 근거가 아니다.', '종이 양식 사용 기록이 있다.', '서비스는 도서관이 제안했다.']],
    ],
  },
  {
    topic: '해안 사구 보전',
    passage: `A narrow line of dunes separates Seabrook village from the beach. Beach grass holds sand with its roots, while wind deposits new sand among its leaves. Over several summers, visitors began cutting across the dunes to reach the water. Their footsteps broke the grass and formed low paths. During storms, waves passed through those low places more easily.

The village built a wooden walkway above one existing path and placed simple signs at its entrances. The walkway did not close the beach; it directed people over one protected route. Volunteers planted grass in several damaged places, but they left one small area unplanted for comparison. They measured the height of both areas after windy days. Sand collected faster near the new grass in the first season, although the unplanted area also changed as wind moved sand naturally.

Local officials were pleased but cautious. One season of measurements could not show how the dunes would behave during a major storm, and the walkway itself might affect where people entered the beach. They planned to check the grass and sand levels each spring and after strong storms. The project joined visitor access with a test of whether vegetation helped rebuild the dunes, rather than treating the beach and its protection as separate concerns.`,
    questions: [
      ['What is the main idea of the passage?', 'A village protected dunes while keeping beach access and monitoring the results.', ['The village permanently closed its beach to visitors.', 'Wind was found to have no role in moving sand.', 'A single season proved the dunes safe from every storm.'], ['접근을 유지하면서 사구를 보호하고 결과를 관찰했다.', '해변을 영구 폐쇄하지 않았다.', '바람은 모래 이동에 중요하다.', '한 계절로 모든 폭풍에 대비된 것은 아니다.']],
      ['What happened on the paths visitors made through the dunes?', 'Grass was damaged and the dune surface became lower.', ['New trees grew immediately in the tracks.', 'Wooden walkways appeared without village action.', 'Waves stopped reaching the village during storms.'], ['발자국이 풀을 망가뜨리고 낮은 통로를 만들었다.', '나무 성장 언급은 없다.', '보행로는 나중에 설치했다.', '폭풍 때 파도가 오히려 쉽게 지났다.']],
      ['Why leave one damaged area unplanted?', 'To compare its sand changes with the replanted areas.', ['To provide a shorter route across the dunes.', 'To keep volunteers away from the beach.', 'To prove the grass would not survive.'], ['식재 지역과 자연 변화량을 비교하려는 것이다.', '새 지름길을 위한 것이 아니다.', '자원봉사자 접근 금지가 아니다.', '생존 실패를 미리 증명하려는 것이 아니다.']],
      ['In the passage, “deposits” most nearly means', 'Leaves material in a place.', ['Counts visitors at an entrance.', 'Removes the roots of a plant.', 'Predicts the date of a storm.'], ['바람이 모래를 쌓아 둔다는 뜻이다.', '방문객을 세는 뜻이 아니다.', '뿌리를 제거하지 않는다.', '폭풍 날짜 예측과 무관하다.']],
      ['What is the function of the final paragraph?', 'It qualifies early success and describes longer-term checks.', ['It states that the comparison area was forgotten.', 'It repeats only the first paragraph’s definition of grass.', 'It concludes that storms can no longer affect the village.'], ['초기 결과의 한계를 밝히고 장기 점검을 제시한다.', '비교구역을 잊었다는 말은 없다.', '풀 설명만 반복하지 않는다.', '폭풍 위험이 사라졌다는 결론은 아니다.']],
    ],
  },
  {
    topic: '도시 가로수 조사',
    passage: `A city planted two kinds of street trees along a hot commercial road. One kind grew quickly and made broad shade. The other grew more slowly but had a deeper root system. After four years, shop owners said the road felt cooler. The city wanted to know whether the trees were responsible, not just whether people liked them.

Workers placed temperature sensors at shaded and unshaded points at the same height above the pavement. They measured during similar afternoon hours and recorded cloud cover. The shaded points were usually cooler. Yet the busiest shops also had awnings, which might have contributed shade. To separate the effects, the team added sensors beneath awnings where no tree stood. It also checked whether watering schedules differed between the two tree types, since water could influence growth.

The city decided to keep both kinds of trees for now. The fast-growing ones provided shade sooner, but their shallow roots sometimes lifted paving stones. The slower trees caused fewer such repairs in the surveyed blocks. Officials did not announce one species as universally better. Instead, they planned to match future plantings to sidewalk width, maintenance capacity, and the need for early shade. Their report treated temperature and repair costs as related but distinct outcomes.`,
    questions: [
      ['What does the passage mainly examine about street trees?', 'How a city evaluated both cooling and maintenance effects of street trees.', ['Why the city removed every slow-growing tree.', 'How shop owners measured root depth directly.', 'Why cloud cover was judged the only cause of cooling.'], ['나무의 냉각 효과와 보도 관리 비용을 함께 살폈다.', '느리게 자라는 나무를 모두 제거하지 않았다.', '점주가 뿌리 깊이를 직접 측정한 것은 아니다.', '구름만이 원인이라고 보지 않았다.']],
      ['Where did workers add sensors to check the effect of awnings?', 'Under awnings where no tree provided shade.', ['Only beside the deepest tree roots.', 'Inside shops with no windows.', 'At a different height on every block.'], ['나무가 없는 차양 아래에 센서를 추가했다.', '뿌리 옆만 측정하지 않았다.', '실내 측정은 제시되지 않는다.', '같은 높이로 측정했다.']],
      ['Why did officials avoid naming one tree species as best everywhere?', 'Sidewalk space, repair needs, and the timing of shade vary by location.', ['The two species had identical roots and growth rates.', 'No temperature differences had been recorded.', 'The city had decided to stop all future planting.'], ['장소별 폭·관리 여건과 그늘 시점이 다르기 때문이다.', '두 수종의 성장과 뿌리가 같지 않다.', '온도 차이를 관측했다.', '식재 중단 계획은 없다.']],
      ['In the passage, “distinct” most nearly means', 'Separate and not identical.', ['Impossible to measure.', 'Caused by the same root.', 'Always equally important.'], ['온도와 수리비가 서로 다른 결과라는 뜻이다.', '측정 불가능은 아니다.', '같은 뿌리 원인이라는 뜻이 아니다.', '항상 동일 비중이라는 뜻도 아니다.']],
      ['Why does the middle paragraph discuss sensors beneath awnings?', 'To show how the team tested another explanation for shade.', ['To introduce a new tree species.', 'To argue that pavement repairs cause cloud cover.', 'To show that the first sensors were never used.'], ['차양이라는 다른 그늘 원인을 분리하려는 비교다.', '새 수종은 소개되지 않는다.', '수리와 구름의 인과가 아니다.', '처음 센서도 사용했다.']],
    ],
  },
  {
    topic: '수어와 의사소통',
    passage: `A school opened a weekly class in the local sign language. Some hearing students expected to learn a list of hand shapes and then translate spoken sentences word for word. Their teacher explained that a sign language is a full language with its own grammar. Facial expression and the space around a signer can carry information alongside hand movement.

During one lesson, pairs of students described where objects sat on a table. A speaker of the local sign language showed how to establish a place in signing space and refer to it again later. Students who watched only the hands missed some of the location information. The teacher then asked them to describe the same arrangement from a different viewpoint. This exercise made clear that copying a shape was not enough; signers also had to track what the shape referred to.

The class did not make students fluent in a month. It did help them recognize why a printed list of signs cannot replace practice with skilled users of the language. The teacher invited local Deaf adults to lead later sessions and to review the class materials. She wanted the lessons to reflect how people actually communicate, rather than treating the language as a set of gestures invented for hearing learners.`,
    questions: [
      ['What is the passage\'s main point?', 'Learning a sign language requires attention to its grammar and community use.', ['A sign language is only a list of hand shapes.', 'Hearing students can become fluent after one short class.', 'Facial expression should be ignored when signing.'], ['수어의 문법과 실제 사용자 맥락을 배우는 것이 핵심이다.', '손 모양 목록만이 아니다.', '한 달 유창성은 부정했다.', '표정도 정보를 담는다.']],
      ['What did some students miss when watching only the hands?', 'Part of the information about object locations.', ['The teacher\'s invitation to local adults.', 'The names printed on the classroom table.', 'Every hand movement in the demonstration.'], ['공간과 지시 대상에 관한 일부 정보를 놓쳤다.', '초대 사실은 뒤에 나온다.', '탁자 이름은 제시되지 않는다.', '손동작을 전혀 못 본 것은 아니다.']],
      ['Why did the teacher ask for a different viewpoint?', 'To test whether students could track references rather than copy shapes alone.', ['To prove that every viewpoint uses identical spatial references.', 'To stop students from using the local language.', 'To replace the signer with a printed word list.'], ['형태 모방을 넘어 지시 대상 관계를 이해하는지 보려 했다.', '관점이 달라도 표지가 동일하다는 뜻이 아니다.', '수어 사용을 막지 않았다.', '인쇄 목록으로 대체하지 않았다.']],
      ['In the passage, “fluent” most nearly means', 'Able to use a language smoothly and effectively.', ['Able to memorize one hand shape.', 'Willing to attend every school class.', 'Able to print a list of words.'], ['언어를 자연스럽고 원활하게 사용할 수 있다는 뜻이다.', '손 모양 하나의 암기와 다르다.', '출석 의지와 무관하다.', '목록 인쇄 능력이 아니다.']],
      ['What does the final paragraph add?', 'It explains the class\'s limits and the role of local Deaf instructors.', ['It proves that the class should never meet again.', 'It gives a complete grammar of the language.', 'It says students had already mastered the language.'], ['수업의 한계와 실제 사용자 주도의 후속 수업을 제시한다.', '수업 폐지를 주장하지 않는다.', '문법 전체를 제시하지 않는다.', '이미 숙달했다고 하지 않는다.']],
    ],
  },
  {
    topic: '빵 반죽의 발효',
    passage: `A neighborhood bakery changed the time it allowed bread dough to rise. The old method used warm water and a short wait. The new method used cooler water and left the dough for many hours. Customers said the new loaves had a deeper flavor, but the baker wanted to understand what else had changed. She weighed each loaf and recorded the time and temperature of the dough.

Yeast in the dough releases gas as it uses sugars. A longer wait can allow more gas to form, but only if the dough can hold it. If the dough rises too long, it may weaken and collapse when baked. The baker therefore compared loaves made from the same flour and the same amount of yeast. She changed the water temperature and waiting time while keeping the oven setting steady. She also cut the loaves open to compare the holes in their centers.

The cooler, longer method usually produced loaves with a more open center, but not every trial was successful. On one humid day the dough became too soft. The baker decided to keep checking the dough itself rather than following a clock alone. Her records did not prove why customers preferred the flavor; they did help her make the texture more consistent.`,
    questions: [
      ['What is the bakery study mainly concerned with?', 'A baker\'s controlled comparison of dough-rising methods and bread texture.', ['A decision to stop using yeast in bread.', 'Proof that waiting longer always improves a loaf.', 'A study showing oven temperature alone determines flavor.'], ['발효 시간과 온도를 비교해 빵 조직을 살핀 이야기다.', '효모를 중단하지 않았다.', '오래 기다리면 언제나 좋다는 결론이 아니다.', '오븐만이 맛을 결정했다고 하지 않는다.']],
      ['What did the baker keep the same in her comparisons?', 'The flour, yeast amount, and oven setting.', ['The waiting time and water temperature.', 'The level of humidity on every day.', 'The size of every hole in the finished bread.'], ['밀가루·효모 양·오븐 설정을 유지했다.', '대기 시간과 물 온도는 바꿨다.', '날씨 습도는 같지 않았다.', '기공 크기는 결과로 비교했다.']],
      ['Why did the baker inspect the centers of the loaves?', 'To compare how their internal texture changed.', ['To measure the price customers would pay.', 'To decide whether the flour was a different grain.', 'To prove the loaves had identical flavors.'], ['속의 구멍을 보고 조직 차이를 비교했다.', '가격 조사는 아니다.', '밀가루는 동일하게 유지했다.', '동일한 맛을 입증하지 않는다.']],
      ['In the passage, “consistent” most nearly means', 'Similar from one attempt to the next.', ['More expensive than before.', 'Prepared without any yeast.', 'Certain to please every customer.'], ['매번 비슷하게 재현된다는 뜻이다.', '가격과 관계없다.', '효모를 사용했다.', '모든 고객의 취향 보장은 아니다.']],
      ['Why does the last paragraph mention a humid day?', 'To illustrate why the dough\'s condition matters beyond elapsed time.', ['To show that humidity was held constant in every trial.', 'To explain why the bakery changed its oven.', 'To prove that long rising never works.'], ['습도 탓에 반죽 상태가 달라져 시계만 따를 수 없음을 보여 준다.', '습도는 일정하지 않았다.', '오븐을 바꾸지 않았다.', '긴 발효 전체를 부정하지 않는다.']],
    ],
  },
  {
    topic: '갯벌과 조수의 흐름',
    passage: `A fishing town restored a small tidal wetland beside its harbor. Years earlier, a low bank had been built to keep seawater out. That bank protected a storage yard, but it also prevented the wetland from receiving regular tides. Plants that once grew in salty water declined. The town moved the storage yard and cut a narrow opening through the bank.

Water returned through the opening twice each day. Students placed simple markers at several points to see how high the water reached. They also counted young fish in shallow channels, using the same method each month. Some fish appeared soon after the opening, but the students could not know whether those fish had grown in the wetland or had entered from the harbor. They recorded both the water levels and fish counts instead of treating the counts as proof of a complete recovery.

The town left part of the old bank in place because a nearby walking path still needed protection. Engineers said the opening might have to change if storms carried too much sediment into the channels. For now, the project was considered an experiment in reconnecting the wetland with the sea. Its success would depend on continued plant growth, water movement, and safe public use, not on one month\'s fish count.`,
    questions: [
      ['What is the main purpose of the wetland project?', 'To restore tidal connection while observing ecological and safety effects.', ['To close the harbor to all fishing vessels.', 'To stop seawater from reaching every part of the wetland.', 'To remove the walking path immediately.'], ['조수 연결을 복원하면서 생태·안전 변화를 관찰한다.', '항구 폐쇄가 아니다.', '바닷물 유입을 회복했다.', '산책로는 보호했다.']],
      ['How did students measure the returning tide?', 'They placed markers to show water height at several locations.', ['They weighed every fish in the harbor.', 'They measured only the old storage yard.', 'They checked the water once before the opening was cut.'], ['여러 지점의 표시로 물이 닿는 높이를 확인했다.', '항구 물고기 모두를 달지 않았다.', '창고 부지만 보지 않았다.', '개구 후 반복해서 측정했다.']],
      ['Why were early fish counts not proof of full recovery?', 'The fish could have moved in from the harbor rather than grown there.', ['The students had stopped measuring water levels.', 'No fish were observed in the channels.', 'The bank had been completely removed.'], ['어린 물고기가 외부에서 들어왔을 수도 있다.', '물 높이도 기록했다.', '물고기를 관찰했다.', '제방 일부는 남겼다.']],
      ['In the passage, “declined” most nearly means', 'Became fewer or less common.', ['Moved to a higher place overnight.', 'Returned to their former level.', 'Were counted more carefully.'], ['염수 식물이 줄었다는 뜻이다.', '밤사이 이동 뜻이 아니다.', '예전 수준 회복이 아니다.', '조사 방식 변화가 아니다.']],
      ['What is the role of the final paragraph?', 'It gives practical limits and criteria for judging the project over time.', ['It announces that the first fish count ended the project.', 'It says storms cannot move sediment.', 'It replaces the need to observe plants.'], ['남은 제방·폭풍 가능성·장기 평가 기준을 제시한다.', '첫 조사로 끝내지 않았다.', '폭풍 퇴적 우려가 있다.', '식물 성장도 계속 살핀다.']],
    ],
  },
]
