import { prepareSentenceTiles } from './sentenceTiles'
import { paraphraseForOption } from './readingLanguage'
import { buildResearchSentencePattern } from './sentenceBuildPatterns'
import { buildDiscussionTask, buildEmailPrompt, buildInterviewScenario, buildRepeatScenario } from './openTaskPatterns'
import type { BaseItem } from './types'

type Difficulty = NonNullable<BaseItem['difficulty']>
type Seed = {
  topic: string; difficulty: Difficulty; subject: string; finding: string; mechanism: string; caveat: string; implication: string
  focusWord: string; focusMeaning: string; service: string; problem: string; actor: string; action: string
  exchangePrompt: string; exchangeCorrect: string; repeatSimple: string; debate: string; counterpoint: string; personal: string
}

// The academic fields use selected B2-C1 vocabulary already present in the bundled
// vocabulary corpus. Service, response, email, and early speaking tasks deliberately
// use familiar language because the ETS construct does not require technical knowledge.
const SEEDS: Seed[] = [
  { topic: '동물 이동과 방향 감각', difficulty: 'B1', subject: 'how migrating birds choose a route', finding: 'young birds used both landmarks and the position of the sun', mechanism: 'Each source helped when the other was hidden by clouds or distance', caveat: 'the study followed one species during a single season', implication: 'navigation should be understood as a flexible combination of cues', focusWord: 'orientation', focusMeaning: 'the ability to determine direction', service: 'a campus bird-monitoring walk', problem: 'the meeting point on the event page is unclear', actor: 'the ecology club', action: 'add a map and place a volunteer beside the east gate', exchangePrompt: 'Did you bring the field guide?', exchangeCorrect: 'Yes, it is in my backpack.', repeatSimple: 'Meet the group beside the east gate.', debate: 'Should cities dim unnecessary lights during migration seasons?', counterpoint: 'some lighting is important for safety', personal: 'an animal behavior that you have observed' },
  { topic: '균류와 산림 생태', difficulty: 'B2', subject: 'nutrient exchange between tree roots and fungi', finding: 'fungal partners improved phosphorus uptake in nutrient-poor soil', mechanism: 'Fine fungal threads reached small spaces that roots could not enter efficiently', caveat: 'the benefit declined when water became extremely scarce', implication: 'forest models should represent partnerships as well as competition', focusWord: 'symbiosis', focusMeaning: 'a close relationship between different organisms', service: 'a woodland field course', problem: 'students are leaving the trail to photograph mushrooms', actor: 'the course staff', action: 'create two marked observation areas', exchangePrompt: 'May I collect this mushroom?', exchangeCorrect: 'No, please photograph it where it is.', repeatSimple: 'Leave every mushroom where you found it.', debate: 'Should damaged forests be replanted quickly or allowed to recover naturally?', counterpoint: 'active planting may help where soil has been heavily altered', personal: 'a natural relationship that people often overlook' },
  { topic: '화산 감시', difficulty: 'B2', subject: 'small changes that occur before volcanic unrest', finding: 'ground swelling and gas composition changed before several active periods', mechanism: 'Rising magma pushed rock outward and released gases at lower pressure', caveat: 'similar signals sometimes ended without an eruption', implication: 'warnings should combine measurements and communicate uncertainty', focusWord: 'precursor', focusMeaning: 'a sign that may come before an event', service: 'a geology field trip', problem: 'the northern trail is closed for sensor repairs', actor: 'the trip leader', action: 'use the southern viewpoint instead', exchangePrompt: 'Why is the north trail closed?', exchangeCorrect: 'The monitoring team is repairing a sensor.', repeatSimple: 'The southern viewpoint remains open today.', debate: 'How should officials balance early warnings with unnecessary evacuations?', counterpoint: 'waiting for certainty may leave too little time', personal: 'how you respond to an uncertain warning' },
  { topic: '지하수 관리', difficulty: 'B1', subject: 'how quickly rain refills an underground water supply', finding: 'recharge was faster under fields with permeable soil than under pavement', mechanism: 'Open soil let water move downward instead of flowing into drains', caveat: 'heavy pumping removed water faster than seasonal rain replaced it', implication: 'water plans should protect recharge areas and control extraction', focusWord: 'permeable', focusMeaning: 'allowing liquid to pass through', service: 'a residence-hall water repair', problem: 'cold water will be unavailable for one hour', actor: 'the housing office', action: 'provide drinking-water stations in the lobby', exchangePrompt: 'Is the water safe to drink now?', exchangeCorrect: 'Yes, the repair is finished.', repeatSimple: 'Fill your bottle before the repair begins.', debate: 'Should new buildings leave more ground uncovered for rainwater?', counterpoint: 'dense neighborhoods also need space for housing', personal: 'a practical way to reduce water use' },
  { topic: '빙하와 과거 기후', difficulty: 'B2', subject: 'air bubbles preserved in old ice', finding: 'the bubbles recorded atmospheric gases from thousands of years ago', mechanism: 'Falling snow trapped small air samples and compressed them into layers', caveat: 'flowing ice distorted the oldest layers near the bottom', implication: 'depth records must be combined with models of ice movement', focusWord: 'layered', focusMeaning: 'arranged in distinct levels or layers', service: 'a cold-room laboratory tour', problem: 'visitors often arrive without warm clothing', actor: 'the laboratory', action: 'lend insulated jackets at check-in', exchangePrompt: 'How cold is the storage room?', exchangeCorrect: 'It stays below freezing.', repeatSimple: 'Wear the insulated jacket inside the cold room.', debate: 'Should rare ice samples be used now or saved for future instruments?', counterpoint: 'current tests can answer urgent climate questions', personal: 'why people preserve evidence for future researchers' },
  { topic: '소리경관 생태학', difficulty: 'C1', subject: 'sound patterns in restored wetlands', finding: 'sites with more diverse calls supported more bird and insect species', mechanism: 'Long recordings captured activity when observers were absent', caveat: 'wind, traffic, and a few loud species distorted the acoustic index', implication: 'sound data should complement rather than replace field surveys', focusWord: 'attenuate', focusMeaning: 'to reduce the strength of something', service: 'an outdoor recording assignment', problem: 'construction noise overlaps the scheduled recording time', actor: 'the instructor', action: 'offer a dawn session at a quieter site', exchangePrompt: 'Did the recorder capture the frogs?', exchangeCorrect: 'Mostly, but traffic covered part of the call.', repeatSimple: 'Check the wind before you begin recording.', debate: 'Should quiet natural areas receive legal protection from noise?', counterpoint: 'transportation may still be necessary nearby', personal: 'a sound that changes how you experience a place' },
  { topic: '인지 편향과 판단', difficulty: 'B2', subject: 'how the first number people see affects later estimates', finding: 'random starting numbers shifted estimates even when people knew they were irrelevant', mechanism: 'Participants adjusted away from the first value but usually not far enough', caveat: 'the effect varied with experience and time for reflection', implication: 'important estimates should begin with independent evidence', focusWord: 'salient', focusMeaning: 'especially noticeable or prominent', service: 'a student budget workshop', problem: 'the form shows an outdated example of monthly costs', actor: 'the financial support office', action: 'replace it with a current cost calculator', exchangePrompt: 'Could you check my estimate?', exchangeCorrect: 'Sure, show me how you calculated it.', repeatSimple: 'Use current prices when you prepare your budget.', debate: 'Should public forms avoid examples that might influence answers?', counterpoint: 'examples can make unfamiliar questions clearer', personal: 'a time when a first impression affected a decision' },
  { topic: '기억 재구성과 학습', difficulty: 'C1', subject: 'what happens when a stored memory is recalled', finding: 'a recalled memory briefly became open to modification', mechanism: 'Retrieval activated the memory together with new contextual information', caveat: 'not every reminder produced the same period of change', implication: 'learning schedules should distinguish review from active updating', focusWord: 'retrieval', focusMeaning: 'the act of recalling stored information', service: 'a study-skills experiment', problem: 'some participants received the wrong reminder schedule', actor: 'the research coordinator', action: 'offer a corrected follow-up session', exchangePrompt: 'Do I need to repeat the session?', exchangeCorrect: 'Only if you received the wrong schedule.', repeatSimple: 'The follow-up session uses a corrected schedule.', debate: 'Is correcting a mistaken memory more important than preserving confidence?', counterpoint: 'constant doubt can make ordinary decisions difficult', personal: 'a study method that changed what you remembered' },
  { topic: '수어와 언어 구조', difficulty: 'B2', subject: 'how sign languages mark questions and emphasis', finding: 'signers combined hand movement with facial and body signals systematically', mechanism: 'Visual grammar distributed information across simultaneous channels', caveat: 'the exact patterns differed across languages and communities', implication: 'linguistic analysis should not assume spoken structure is universal', focusWord: 'simultaneous', focusMeaning: 'occurring at the same time', service: 'an interpreted campus lecture', problem: 'reserved seats do not show both the speaker and interpreter clearly', actor: 'the events team', action: 'move the seating area and improve stage lighting', exchangePrompt: 'Where will the interpreter stand?', exchangeCorrect: 'On the right side of the stage.', repeatSimple: 'Keep a clear view of the interpreter.', debate: 'Should teacher training include basic knowledge of signed languages?', counterpoint: 'programs already have limited time', personal: 'how communication changes across different channels' },
  { topic: '글자 디자인과 가독성', difficulty: 'B1', subject: 'how spacing affects reading on small screens', finding: 'moderate line spacing improved accuracy for many readers', mechanism: 'Clear separation helped the eyes move to the correct next line', caveat: 'very wide spacing slowed reading and increased scrolling', implication: 'designers should test a practical range instead of maximizing spacing', focusWord: 'legibility', focusMeaning: 'the quality of being easy to read', service: 'a course website redesign', problem: 'assignment dates are hard to read on phones', actor: 'the course assistant', action: 'increase contrast and text size', exchangePrompt: 'Can you read the date on your phone?', exchangeCorrect: 'Not clearly; the text is too small.', repeatSimple: 'The larger text is easier to read.', debate: 'Should websites let users change text spacing and size?', counterpoint: 'too many controls can confuse users', personal: 'a design choice that made information easier to understand' },
  { topic: '네트워크 과학', difficulty: 'C1', subject: 'how failures spread through connected systems', finding: 'removing a few central nodes caused more disruption than many random failures', mechanism: 'Central nodes linked separate groups and carried many interactions', caveat: 'real networks can reorganize after damage', implication: 'resilience plans should consider both structure and adaptation', focusWord: 'topology', focusMeaning: 'the pattern in which parts of a network are connected', service: 'a campus network maintenance window', problem: 'the diagram does not show when each dormitory loses service', actor: 'the IT office', action: 'publish a building-by-building schedule', exchangePrompt: 'Will the dormitory Wi-Fi stop tonight?', exchangeCorrect: 'Yes, but only for twenty minutes.', repeatSimple: 'Save your work before the maintenance.', debate: 'Should essential services favor simple networks over highly connected ones?', counterpoint: 'extra connections can provide alternative routes', personal: 'a system you depend on without noticing its connections' },
  { topic: '암호화와 디지털 신뢰', difficulty: 'B2', subject: 'how public-key encryption supports secure messages', finding: 'users shared a locking key without revealing the private unlocking key', mechanism: 'The operation was easy in one direction but difficult to reverse', caveat: 'encryption did not help when users revealed passwords through false links', implication: 'technical protection must be combined with safe behavior', focusWord: 'authentication', focusMeaning: 'the process of verifying identity', service: 'a library account security update', problem: 'students mistake a test notice for a fraudulent message', actor: 'the library IT team', action: 'label the test and post an official example', exchangePrompt: 'Should I click this password link?', exchangeCorrect: 'No, open the official account page instead.', repeatSimple: 'Open your account from the official website.', debate: 'Should stronger security be required even when it slows access?', counterpoint: 'complex steps may encourage unsafe shortcuts', personal: 'how you decide whether a message is trustworthy' },
  { topic: '인간과 로봇의 협업', difficulty: 'B2', subject: 'how workers respond when a robot signals uncertainty', finding: 'people checked the robot more carefully when it showed low confidence', mechanism: 'The signal indicated when human judgment was most useful', caveat: 'too many warnings caused users to ignore the display', implication: 'automation should communicate uncertainty selectively', focusWord: 'autonomous', focusMeaning: 'able to operate with limited direct control', service: 'a robotics laboratory demonstration', problem: 'visitors enter the marked robot workspace', actor: 'the laboratory staff', action: 'add a visible boundary and automatic pause', exchangePrompt: 'Is the robot ready to move?', exchangeCorrect: 'Not yet; the safety check is running.', repeatSimple: 'Stay outside the marked robot workspace.', debate: 'When should a person approve an automated decision?', counterpoint: 'constant approval removes the speed advantage', personal: 'a task you would trust a robot to perform' },
  { topic: '적층 제조', difficulty: 'B1', subject: 'using three-dimensional printing for replacement parts', finding: 'local printing reduced waiting time for simple components', mechanism: 'A digital design was produced near the place where the part was needed', caveat: 'printed material did not meet every strength requirement', implication: 'the production method should match the part’s function', focusWord: 'additive', focusMeaning: 'made by building material up in layers', service: 'a student fabrication workshop', problem: 'users leave print jobs without their names', actor: 'the workshop manager', action: 'require a label on every job', exchangePrompt: 'When will my part be finished?', exchangeCorrect: 'The printer should finish it by noon.', repeatSimple: 'Put your name on every print job.', debate: 'Should schools teach repair and fabrication as basic skills?', counterpoint: 'equipment and supervision can be expensive', personal: 'something that is better repaired than replaced' },
  { topic: '생체모방 설계', difficulty: 'B2', subject: 'surfaces inspired by water-repelling leaves', finding: 'microscopic patterns reduced how strongly dirt and water attached', mechanism: 'Tiny bumps limited contact and let rolling drops collect particles', caveat: 'abrasion weakened the effect by damaging the fine pattern', implication: 'durability must be tested alongside initial performance', focusWord: 'emulate', focusMeaning: 'to reproduce a useful quality or process', service: 'a design exhibition', problem: 'labels describe inspiration but omit engineering limits', actor: 'the exhibition team', action: 'add results from durability tests', exchangePrompt: 'Can I touch the sample?', exchangeCorrect: 'Please use the demonstration piece.', repeatSimple: 'Use the demonstration sample on the table.', debate: 'Does copying nature always create sustainable technology?', counterpoint: 'the imitation may require harmful materials', personal: 'a design that learns from nature' },
  { topic: '지열 에너지', difficulty: 'B1', subject: 'using underground heat for buildings', finding: 'a ground-source system used less electricity than separate heaters', mechanism: 'Underground temperature changed less than outdoor air', caveat: 'installation cost was high where drilling access was limited', implication: 'site conditions should be checked before choosing the system', focusWord: 'geothermal', focusMeaning: 'related to heat from within the Earth', service: 'an energy center tour', problem: 'the main entrance is blocked by drilling equipment', actor: 'the tour coordinator', action: 'meet visitors at the south entrance', exchangePrompt: 'Where does the tour begin?', exchangeCorrect: 'At the south entrance today.', repeatSimple: 'The tour begins at the south entrance.', debate: 'Should public buildings pay more initially to reduce later energy use?', counterpoint: 'future savings differ by site', personal: 'a realistic energy-saving change in a building' },
  { topic: '담수화 기술', difficulty: 'B2', subject: 'reducing the energy required for seawater desalination', finding: 'pressure-recovery equipment lowered electricity use', mechanism: 'The device captured energy from outgoing concentrated water', caveat: 'salty waste still threatened sensitive coastal habitats', implication: 'water production and environmental impact must be assessed together', focusWord: 'membrane', focusMeaning: 'a thin barrier that allows some substances to pass', service: 'a coastal engineering open house', problem: 'the schedule lists two tours at the same time', actor: 'the visitor center', action: 'send each guest a corrected room assignment', exchangePrompt: 'Which room is my tour in?', exchangeCorrect: 'Check the new message from the visitor center.', repeatSimple: 'Check your updated room assignment.', debate: 'Should dry cities invest in desalination or water conservation?', counterpoint: 'conservation may not supply enough water in a long drought', personal: 'choosing between new supply and lower demand' },
  { topic: '도시 녹색 지붕', difficulty: 'B1', subject: 'how planted roofs affect rain and temperature', finding: 'shallow soil held storm water and kept the roof cooler', mechanism: 'Plants shaded the surface while soil delayed water entering drains', caveat: 'performance declined during long dry periods', implication: 'plant choice and local climate matter as much as roof area', focusWord: 'runoff', focusMeaning: 'water that flows over a surface after rain', service: 'a rooftop garden volunteer day', problem: 'the elevator cannot carry soil during morning maintenance', actor: 'the garden coordinator', action: 'move the soil delivery to the afternoon', exchangePrompt: 'Should I bring a shovel?', exchangeCorrect: 'No, the garden has tools for volunteers.', repeatSimple: 'The soil delivery will arrive this afternoon.', debate: 'Should cities require planted roofs on suitable new buildings?', counterpoint: 'maintenance makes them impractical on some sites', personal: 'a small green space that improves a neighborhood' },
  { topic: '행동경제학과 선택 설계', difficulty: 'B2', subject: 'how default options affect savings-plan enrollment', finding: 'participation rose when enrollment was automatic but easy to decline', mechanism: 'The default removed a small decision step while preserving choice', caveat: 'some people remained enrolled without understanding the fees', implication: 'defaults should be paired with clear repeated information', focusWord: 'incentive', focusMeaning: 'something that encourages a particular action', service: 'a campus meal-plan form', problem: 'the form preselects the largest plan', actor: 'the student services office', action: 'remove the preselection and compare the plans clearly', exchangePrompt: 'Can I change my meal plan later?', exchangeCorrect: 'Yes, during the first two weeks.', repeatSimple: 'Compare the plans before you choose one.', debate: 'Is it fair to use defaults to encourage beneficial choices?', counterpoint: 'defaults influence people who do not examine options', personal: 'a time when an easy option shaped your choice' },
  { topic: '하수 기반 감염 감시', difficulty: 'B2', subject: 'using wastewater to track community infection trends', finding: 'viral material increased before many patients sought clinical tests', mechanism: 'Samples combined traces from many households without naming individuals', caveat: 'rainfall and water use changed the concentration in each sample', implication: 'trends should be adjusted and confirmed with other health measures', focusWord: 'aggregate', focusMeaning: 'combined from many separate sources', service: 'a campus sampling project', problem: 'construction blocks access to one sampling point', actor: 'the project supervisor', action: 'use the upstream site and document the change', exchangePrompt: 'Are the samples linked to student names?', exchangeCorrect: 'No, they show only a combined signal.', repeatSimple: 'The samples do not identify individual students.', debate: 'When should communities publish uncertain early health signals?', counterpoint: 'delayed information may reduce prevention time', personal: 'how officials should explain uncertain health information' },
]

const base = (id: string, section: BaseItem['section'], kind: BaseItem['kind'], title: string, seed: Seed, context: string, timeSeconds: number): BaseItem => ({ id, section, module: 1, kind, title, instruction: '', topic: seed.topic, context, difficulty: seed.difficulty, timeSeconds })

const question = (prompt: string, correct: string, distractors: [string, string, string], explanation: string, key: number) => {
  const answer = key % 4
  const options = [...distractors]
  options.splice(answer, 0, correct)
  return { prompt, options, answer, explanation }
}

const FOCUS_PARAPHRASES: Record<string, string> = {
  orientation: 'the capacity to work out which way to travel',
  symbiosis: 'an interdependent association between unlike species',
  precursor: 'an early indication of a possible later event',
  permeable: 'able to let water move through its surface',
  layered: 'formed in a sequence of separate bands',
  attenuate: 'make something weaker or less intense',
  salient: 'particularly prominent and likely to attract attention',
  retrieval: 'bringing previously stored information back to mind',
  simultaneous: 'taking place together rather than one after another',
  legibility: 'how readily written material can be recognized and understood',
  topology: 'the arrangement of links among the parts of a system',
  authentication: 'confirming that a person or source is genuine',
  autonomous: 'capable of functioning with little immediate human direction',
  additive: 'created by placing successive amounts of material on top of one another',
  emulate: 'copy a useful feature in order to achieve a similar result',
  geothermal: 'connected with energy obtained from below Earth’s surface',
  membrane: 'a selective sheet through which only certain materials can move',
  runoff: 'rainwater moving across land rather than soaking into it',
  incentive: 'a motivating benefit or pressure that makes an action more likely',
  aggregate: 'a combined total formed from several separate amounts',
}

const makeCloze = (text: string) => {
  const firstSentenceEnd = text.indexOf('.')
  let candidateIndex = 0
  const answers: string[] = []
  const passage = text.replace(/\b[A-Za-z]{4,}\b/g, (word, offset: number) => {
    if (offset <= firstSentenceEnd || answers.length >= 10) return word
    candidateIndex += 1
    if (candidateIndex % 2 !== 0) return word
    const keep = Math.ceil(word.length / 2)
    answers.push(word.slice(keep))
    return `${word.slice(0, keep)}___`
  })
  if (answers.length !== 10) throw new Error('New-topic cloze text must contain exactly 10 gaps.')
  return { passage, answer: answers.join('|') }
}

export const NEW_TOPIC_ITEMS: BaseItem[] = SEEDS.flatMap((seed, index) => {
  const id = `n-${index}`
  const academicFormats = [
    `Researchers examined ${seed.subject}. They found that ${seed.finding}. ${seed.mechanism}. The report used the term ${seed.focusWord} for this feature, describing it as ${seed.focusMeaning}. However, ${seed.caveat}. The team therefore concluded that ${seed.implication}.`,
    `A recent investigation asked how to interpret ${seed.subject}. Evidence showed that ${seed.finding}. The proposed mechanism was straightforward: ${seed.mechanism}. In this context, ${seed.focusWord} means ${seed.focusMeaning}. Because ${seed.caveat}, the authors argued that ${seed.implication}.`,
    `Explanations of ${seed.subject} have often emphasized a single factor. New observations instead indicated that ${seed.finding}. ${seed.mechanism}. Researchers described the relevant feature as ${seed.focusWord}, meaning ${seed.focusMeaning}. Yet ${seed.caveat}. This limitation led them to conclude that ${seed.implication}.`,
    `To evaluate ${seed.subject}, a research team compared an observed result with a possible explanation. The result was that ${seed.finding}; the explanation was that ${seed.mechanism}. The term ${seed.focusWord} refers to ${seed.focusMeaning}. The conclusion remained conditional since ${seed.caveat}, so ${seed.implication}.`,
  ]
  const academicPassage = `${academicFormats[index % academicFormats.length]} This distinction matters when evidence guides a practical decision.`
  const cloze = makeCloze(academicPassage)
  const notice = `Campus notice: Because ${seed.problem}, ${seed.actor} will ${seed.action}. The temporary change begins Monday and will be reviewed after three weeks. Questions should be sent to the service desk.`
  const conversation = `Student: I am having trouble because ${seed.problem}. Staff member: I understand. ${seed.actor} will ${seed.action}. Student: Is that permanent? Staff member: Not yet. We will test it for three weeks, collect comments, and then decide.`
  const announcement = `Campus announcement about ${seed.service}: ${seed.actor} will ${seed.action} because ${seed.problem}. The temporary arrangement begins Monday. Review the updated instructions and report any access conflict before the three-week evaluation.`
  const talk = `Professor: Today we will consider ${seed.subject}. A recent study found that ${seed.finding}. ${seed.mechanism}. The term ${seed.focusWord} here refers to ${seed.focusMeaning}. We should not overstate the result because ${seed.caveat}. The broader lesson is that ${seed.implication}.`
  const sentencePattern = buildResearchSentencePattern(seed, index)
  const tiles = prepareSentenceTiles(sentencePattern.correct, `${id}-w0`)
  const response = question(`Which reply best fits the brief exchange about ${seed.service}?`, seed.exchangeCorrect, [`The office responsible for ${seed.subject} closes at five.`, `I read the ${seed.subject} report last week.`, `The building for ${seed.service} is beside the library.`], 'The response directly answers the short spoken prompt.', index)
  const findingParaphrase = paraphraseForOption(seed.finding)
  const actionParaphrase = paraphraseForOption(seed.action)
  const academicMain = question(`Which option best restates the principal finding about ${seed.subject}?`, `The observations can be summarized as follows: ${findingParaphrase}.`, [`No consistent evidence was found concerning ${seed.subject}.`, `The caveat erased every observation about ${seed.subject}.`, `All conditions produced an identical result in the ${seed.subject} study.`], 'The correct choice preserves the scope of the finding while using different language.', index + 1)
  const academicLimit = question(`What does the caveat imply about using the ${seed.subject} result elsewhere?`, `The result about ${seed.subject} remains conditional until it is tested beyond the stated limitation.`, [`The investigation of ${seed.subject} produced no observations.`, `The finding about ${seed.subject} is universal merely because a mechanism was proposed.`, `Only specialists can understand ${seed.subject}, regardless of the evidence.`], 'The caveat places a boundary on claims that extend beyond the observed setting.', index + 2)
  const academicVocabulary = question(`In the passage about ${seed.subject}, “${seed.focusWord}” is closest in meaning to`, `${FOCUS_PARAPHRASES[seed.focusWord]} in the discussion of ${seed.subject}`, [`a temporary schedule change involving ${seed.service}`, `an unsupported statement about ${seed.subject}`, `a measurement of ${seed.subject} that can never vary`], `The surrounding explanation supports the meaning of “${seed.focusWord}.”`, index + 3)
  const dailyAction = question(`What action is announced for ${seed.service}?`, `The notice introduces a limited operational adjustment: ${actionParaphrase}.`, [`${seed.service} will be permanently canceled without a replacement.`, `Individuals must resolve ${seed.problem} without assistance.`, `${seed.actor} will delay every response until the review is complete.`], 'The correct option paraphrases the action announced in the notice.', index + 2)
  const dailyReason = question(`What does the review schedule imply about the change to ${seed.service}?`, `${seed.actor} may revise the arrangement after examining how well it works.`, [`The ${seed.service} arrangement will become permanent regardless of its effects.`, `The service desk will decide whether ${seed.problem} ever existed.`, `Comments about ${seed.service} will be rejected until the trial ends.`], 'A temporary period followed by review means later evidence can affect the plan.', index + 3)
  const conversationProblem = question(`What difficulty with ${seed.service} does the student report?`, seed.problem, [`a grade unrelated to ${seed.subject} was entered incorrectly`, `a required textbook for ${seed.subject} has disappeared from the library`, `a student organization unrelated to ${seed.service} canceled its meeting`], 'The student states the practical problem at the beginning.', index)
  const announcementAction = question(`What should listeners do if the ${seed.service} change creates an access conflict?`, `They should report the ${seed.service} conflict before the evaluation.`, [`They should wait until ${seed.service} becomes permanent.`, `They should contact an organization unrelated to ${seed.actor}.`, `They should ignore the updated ${seed.service} instructions until Monday.`], 'The announcement requests reports before the three-week evaluation.', index + 1)
  const talkMain = question(`What is the professor’s main purpose in discussing ${seed.subject}?`, `To explain a finding about ${seed.subject}, its mechanism, and its limitation`, [`To provide ${seed.service} directions instead of explaining ${seed.subject}`, `To argue that ${seed.subject} has no value`, `To compare two biographies unrelated to ${seed.subject}`], 'The talk connects a finding, a mechanism, and a caveat.', index + 2)
  const talkLimit = question(`Which caution restricts the conclusion about ${seed.subject}?`, seed.caveat, [`the study of ${seed.subject} asked no research question`, `the example about ${seed.subject} was entirely fictional`, `the researchers proposed no mechanism for ${seed.subject}`], 'The professor states this limitation explicitly.', index + 3)
  const discussion = buildDiscussionTask({ ...seed, service: seed.service, action: seed.action, limitation: seed.caveat }, index + 53)
  const repeatScenario = buildRepeatScenario({ ...seed, service: seed.service, action: seed.action }, index + 53)
  const interviewScenario = buildInterviewScenario({ ...seed, service: seed.service, action: seed.action }, index + 53)

  return [
    { ...base(`${id}-c0`, 'reading', 'complete-words', 'Complete the Words', seed, '학술 문맥과 철자', 240), instruction: '첫 문장은 그대로 읽고, 이후 빠진 단어의 나머지 철자를 완성하세요.', passage: cloze.passage, answer: cloze.answer, explanation: '문맥, 문법 형태, 철자를 함께 확인하세요.' },
    { ...base(`${id}-r0`, 'reading', 'multiple-choice', 'Read an Academic Passage', seed, '연구 결과', 120), instruction: '학술 지문의 핵심 결과를 파악하세요.', passage: academicPassage, ...academicMain },
    { ...base(`${id}-r1`, 'reading', 'multiple-choice', 'Read an Academic Passage', seed, '연구 한계', 120), instruction: '결론의 범위를 제한하는 정보를 찾으세요.', passage: academicPassage, ...academicLimit },
    { ...base(`${id}-r2`, 'reading', 'multiple-choice', 'Read an Academic Passage', seed, '문맥 어휘', 120), instruction: '문맥에서 학술 어휘의 뜻을 추론하세요.', passage: academicPassage, ...academicVocabulary },
    { ...base(`${id}-r3`, 'reading', 'multiple-choice', 'Read in Daily Life', seed, `${seed.service} · 조치`, 75), difficulty: index % 3 === 0 ? 'B1' : 'B2', instruction: '짧은 공지에서 필요한 행동을 찾으세요.', passage: notice, ...dailyAction },
    { ...base(`${id}-r4`, 'reading', 'multiple-choice', 'Read in Daily Life', seed, `${seed.service} · 이유`, 75), difficulty: index % 3 === 0 ? 'B1' : 'B2', instruction: '짧은 공지의 이유를 파악하세요.', passage: notice, ...dailyReason },
    { ...base(`${id}-l0`, 'listening', 'listen-choice', 'Listen and Choose a Response', seed, '짧은 캠퍼스 대화', 35), difficulty: 'B1', instruction: '짧은 말을 듣고 가장 자연스러운 응답을 고르세요.', audioText: seed.exchangePrompt, ...response },
    { ...base(`${id}-l1`, 'listening', 'listen-choice', 'Listen to a Conversation', seed, `${seed.service} · 문제`, 70), instruction: '대화에서 제기된 실제 문제를 파악하세요.', audioText: conversation, ...conversationProblem },
    { ...base(`${id}-l2`, 'listening', 'listen-choice', 'Listen to an Announcement', seed, `${seed.service} · 변경 공지`, 55), instruction: '공지에서 청자가 해야 할 행동을 파악하세요.', audioText: announcement, ...announcementAction },
    { ...base(`${id}-l3`, 'listening', 'listen-choice', 'Listen to an Academic Talk', seed, '학술 강의 중심 내용', 80), instruction: '짧은 강의의 중심 목적을 파악하세요.', audioText: talk, ...talkMain },
    { ...base(`${id}-l4`, 'listening', 'listen-choice', 'Listen to an Academic Talk', seed, '학술 강의 한계', 80), instruction: '강의에서 강조한 한계를 찾으세요.', audioText: talk, ...talkLimit },
    { ...base(`${id}-w0`, 'writing', 'sentence-build', 'Build a Sentence', seed, sentencePattern.grammarFocus, 75), instruction: '문맥에 맞는 문장이 되도록 모든 단어와 짧은 구를 배열하세요.', prompt: sentencePattern.prompt, starter: sentencePattern.starter, words: tiles.choices, answer: tiles.answer, explanation: `${sentencePattern.starter} ${tiles.correct.join(' ')}`, grammarFocus: sentencePattern.grammarFocus },
    { ...base(`${id}-w1`, 'writing', 'email', 'Write an Email', seed, `${seed.service} · 실제 요청`, 420), difficulty: index % 2 === 0 ? 'B1' : 'B2', instruction: '상황과 독자를 고려해 분명하고 실용적인 이메일을 작성하세요.', prompt: buildEmailPrompt({ ...seed, service: seed.service, action: seed.action }, index + 53) },
    { ...base(`${id}-w2`, 'writing', 'discussion', 'Write for an Academic Discussion', seed, '학술 토론', 600), instruction: '입장을 밝히고 근거를 들며 다른 관점에 기여하세요.', prompt: discussion.prompt, passage: discussion.passage },
    ...repeatScenario.map((audioText, sequenceIndex) => ({ ...base(`${id}-s-r${sequenceIndex}`, 'speaking', 'repeat', 'Listen and Repeat', seed, `${seed.service} · 단계별 안내`, sequenceIndex < 2 ? 12 : 16), difficulty: sequenceIndex < 2 ? 'B1' : seed.difficulty, instruction: '같은 안내 상황에서 길이와 구조가 달라지는 문장을 한 번 듣고 반복하세요.', audioText, scenarioId: `${id}-repeat`, stimulusGroupId: `${id}-repeat`, sequenceIndex })),
    ...interviewScenario.map((audioText, sequenceIndex) => ({ ...base(`${id}-s-i${sequenceIndex}`, 'speaking', 'interview', 'Take an Interview', seed, '연결형 인터뷰', 45), instruction: '같은 주제의 인터뷰 질문에 구체적인 이유와 사례를 들어 답하세요.', audioText, scenarioId: `${id}-interview`, stimulusGroupId: `${id}-interview`, sequenceIndex })),
  ]
})

export const NEW_TOPIC_COUNT = SEEDS.length
