const REWRITES: Array<[RegExp, string]> = [
  [/\bthe bubbles recorded atmospheric gases from thousands of years ago\b/gi, 'air trapped in the ice preserved evidence of the ancient atmosphere'],
  [/\bsigners combined hand movement with facial and body signals systematically\b/gi, 'users of sign language coordinated manual gestures with expressions and posture in regular patterns'],
  [/\bremoving a few central nodes caused more disruption than many random failures\b/gi, 'failures at a limited number of highly connected points were more damaging than numerous scattered breakdowns'],
  [/\bused less water\b/gi, 'lowered their water consumption'],
  [/\bworked best\b/gi, 'were most effective'],
  [/\bmattered more than\b/gi, 'had a greater influence than'],
  [/\bmore than\b/gi, 'to a greater degree than'],
  [/\bwithout immediate antibiotics\b/gi, 'before antibiotics were prescribed'],
  [/\bwithout greatly reducing\b/gi, 'while largely preserving'],
  [/\bwithout reducing\b/gi, 'while preserving'],
  [/\bshared batteries\b/gi, 'jointly operated energy-storage units'],
  [/\bground-source system\b/gi, 'underground heat-exchange system'],
  [/\bpressure-recovery equipment\b/gi, 'devices that recapture pressure'],
  [/\bstarting numbers\b/gi, 'initial numerical anchors'],
  [/\bpublic-key encryption\b/gi, 'asymmetric encryption'],
  [/\bclinical tests\b/gi, 'tests at medical facilities'],
  [/\bpeer contact\b/gi, 'interaction with classmates'],
  [/\bshared office days\b/gi, 'days when colleagues were on site together'],
  [/\bclear symbols\b/gi, 'easy-to-interpret icons'],
  [/\bshort waiting times\b/gi, 'brief delays before service'],
  [/\bopen questions\b/gi, 'questions allowing extended answers'],
  [/\bnearby services\b/gi, 'resources located close to residents'],
  [/\bsafe crossings\b/gi, 'protected places to cross streets'],
  [/\bremote visits\b/gi, 'appointments conducted at a distance'],
  [/\bquiet zones\b/gi, 'areas reserved for low-noise work'],
  [/\broad repairs\b/gi, 'street maintenance'],
  [/\breduced\b/gi, 'lowered'],
  [/\bimproved\b/gi, 'produced better'],
  [/\bincreased\b/gi, 'led to greater'],
  [/\bexpanded\b/gi, 'broadened'],
  [/\brevealed\b/gi, 'made it possible to detect'],
  [/\bsupported\b/gi, 'helped sustain'],
  [/\bprompted\b/gi, 'encouraged'],
  [/\bpredicted\b/gi, 'was a stronger indicator of'],
  [/\boutperformed\b/gi, 'was more effective than'],
  [/\bproduced\b/gi, 'yielded'],
  [/\bused more\b/gi, 'received greater use'],
  [/\bused\b/gi, 'relied on'],
  [/\bhelped\b/gi, 'enabled'],
  [/\bworked\b/gi, 'succeeded'],
  [/\bgrew\b/gi, 'became greater'],
  [/\brose\b/gi, 'became higher'],
  [/\bchanged\b/gi, 'shifted'],
  [/\bdeclined\b/gi, 'became weaker'],
  [/\bshort\b/gi, 'brief'],
  [/\bregular\b/gi, 'consistent'],
  [/\baccurate\b/gi, 'reliable'],
  [/\bdiverse\b/gi, 'varied'],
  [/\blarge\b/gi, 'substantial'],
  [/\bsmall\b/gi, 'limited'],
  [/\byoung\b/gi, 'juvenile'],
  [/\bpeople\b/gi, 'participants'],
  [/\bresidents\b/gi, 'community members'],
  [/\bstudents\b/gi, 'learners'],
  [/\bteams\b/gi, 'groups'],
  [/\bstaff\b/gi, 'employees'],
  [/\bservices\b/gi, 'resources'],
  [/\bresults\b/gi, 'outcomes'],
  [/\bperformance\b/gi, 'task outcomes'],
  [/\bdamage\b/gi, 'harm'],
  [/\bdemand\b/gi, 'load'],
  [/\bgrid\b/gi, 'power network'],
  [/\bwhen\b/gi, 'in cases where'],
  [/\bwhile\b/gi, 'whereas'],
  [/\bbefore\b/gi, 'prior to'],
  [/\bafter\b/gi, 'following'],
]

export const paraphraseForOption = (source: string) => {
  let result = source
  for (const [pattern, replacement] of REWRITES) result = result.replace(pattern, replacement)
  return result.replace(/\s+/g, ' ').trim()
}
